.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_14_80074700
/* 47B3C30 80074700 40050880 */ .word .L80080540_
/* 47B3C34 80074704 94060880 */ .word .L80080694_
/* 47B3C38 80074708 80100880 */ .word .Llevel_14_80081080
/* 47B3C3C 8007470C 80100880 */ .word .Llevel_14_80081080
/* 47B3C40 80074710 80100880 */ .word .Llevel_14_80081080
/* 47B3C44 80074714 80100880 */ .word .Llevel_14_80081080
/* 47B3C48 80074718 80100880 */ .word .Llevel_14_80081080
/* 47B3C4C 8007471C 80100880 */ .word .Llevel_14_80081080
/* 47B3C50 80074720 80100880 */ .word .Llevel_14_80081080
/* 47B3C54 80074724 80100880 */ .word .Llevel_14_80081080
/* 47B3C58 80074728 80100880 */ .word .Llevel_14_80081080
/* 47B3C5C 8007472C 80100880 */ .word .Llevel_14_80081080
/* 47B3C60 80074730 80100880 */ .word .Llevel_14_80081080
/* 47B3C64 80074734 80100880 */ .word .Llevel_14_80081080
/* 47B3C68 80074738 80100880 */ .word .Llevel_14_80081080
/* 47B3C6C 8007473C 80100880 */ .word .Llevel_14_80081080
/* 47B3C70 80074740 80100880 */ .word .Llevel_14_80081080
/* 47B3C74 80074744 80100880 */ .word .Llevel_14_80081080
/* 47B3C78 80074748 80100880 */ .word .Llevel_14_80081080
/* 47B3C7C 8007474C 80100880 */ .word .Llevel_14_80081080
/* 47B3C80 80074750 80100880 */ .word .Llevel_14_80081080
/* 47B3C84 80074754 80100880 */ .word .Llevel_14_80081080
/* 47B3C88 80074758 80100880 */ .word .Llevel_14_80081080
/* 47B3C8C 8007475C 80100880 */ .word .Llevel_14_80081080
/* 47B3C90 80074760 80100880 */ .word .Llevel_14_80081080
/* 47B3C94 80074764 80100880 */ .word .Llevel_14_80081080
/* 47B3C98 80074768 80100880 */ .word .Llevel_14_80081080
/* 47B3C9C 8007476C 80100880 */ .word .Llevel_14_80081080
/* 47B3CA0 80074770 80100880 */ .word .Llevel_14_80081080
/* 47B3CA4 80074774 80100880 */ .word .Llevel_14_80081080
/* 47B3CA8 80074778 74020880 */ .word .L80080274_
/* 47B3CAC 8007477C E80B0880 */ .word .L80080BE8_
/* 47B3CB0 80074780 980C0880 */ .word .L80080C98_
/* 47B3CB4 80074784 900D0880 */ .word .L80080D90_
/* 47B3CB8 80074788 240E0880 */ .word .L80080E24_
/* 47B3CBC 8007478C 8C0F0880 */ .word .L80080F8C_
/* 47B3CC0 80074790 28100880 */ .word .L80081028_
/* 47B3CC4 80074794 640F0880 */ .word .L80080F64_
/* 47B3CC8 80074798 94070880 */ .word .L80080794_
/* 47B3CCC 8007479C 80100880 */ .word .Llevel_14_80081080
/* 47B3CD0 800747A0 480B0880 */ .word .L80080B48_
/* 47B3CD4 800747A4 80100880 */ .word .Llevel_14_80081080
/* 47B3CD8 800747A8 54020880 */ .word .L80080254_
/* 47B3CDC 800747AC 1C050880 */ .word .L8008051C_
/* 47B3CE0 800747B0 EC090880 */ .word .L800809EC_
/* 47B3CE4 800747B4 D40A0880 */ .word .L80080AD4_
/* 47B3CE8 800747B8 B4020880 */ .word .L800802B4_
/* 47B3CEC 800747BC 0C050880 */ .word .Llevel_14_8008050C
/* 47B3CF0 800747C0 CC090880 */ .word .L800809CC_
.size jtbl_level_14_80074700, . - jtbl_level_14_80074700


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_14_800801D4
/* 47BF704 800801D4 48FFBD27 */  addiu      $sp, $sp, -0xB8
/* 47BF708 800801D8 B000BEAF */  sw         $fp, 0xB0($sp)
/* 47BF70C 800801DC 21F08000 */  addu       $fp, $a0, $zero
/* 47BF710 800801E0 B400BFAF */  sw         $ra, 0xB4($sp)
/* 47BF714 800801E4 AC00B7AF */  sw         $s7, 0xAC($sp)
/* 47BF718 800801E8 A800B6AF */  sw         $s6, 0xA8($sp)
/* 47BF71C 800801EC A400B5AF */  sw         $s5, 0xA4($sp)
/* 47BF720 800801F0 A000B4AF */  sw         $s4, 0xA0($sp)
/* 47BF724 800801F4 9C00B3AF */  sw         $s3, 0x9C($sp)
/* 47BF728 800801F8 9800B2AF */  sw         $s2, 0x98($sp)
/* 47BF72C 800801FC 9400B1AF */  sw         $s1, 0x94($sp)
/* 47BF730 80080200 9000B0AF */  sw         $s0, 0x90($sp)
/* 47BF734 80080204 0000D78F */  lw         $s7, 0x0($fp)
/* 47BF738 80080208 0780053C */  lui        $a1, %hi(D_level_14_800746F0)
/* 47BF73C 8008020C F046A524 */  addiu      $a1, $a1, %lo(D_level_14_800746F0)
/* 47BF740 80080210 0000A28C */  lw         $v0, 0x0($a1)
/* 47BF744 80080214 0400A38C */  lw         $v1, 0x4($a1)
/* 47BF748 80080218 0800A48C */  lw         $a0, 0x8($a1)
/* 47BF74C 8008021C 2000A2AF */  sw         $v0, 0x20($sp)
/* 47BF750 80080220 2400A3AF */  sw         $v1, 0x24($sp)
/* 47BF754 80080224 2800A4AF */  sw         $a0, 0x28($sp)
/* 47BF758 80080228 4800C393 */  lbu        $v1, 0x48($fp)
/* 47BF75C 8008022C 00000000 */  nop
/* 47BF760 80080230 3100622C */  sltiu      $v0, $v1, 0x31
/* 47BF764 80080234 92034010 */  beqz       $v0, .Llevel_14_80081080
/* 47BF768 80080238 80100300 */   sll       $v0, $v1, 2
/* 47BF76C 8008023C 0780013C */  lui        $at, %hi(jtbl_level_14_80074700)
/* 47BF770 80080240 21082200 */  addu       $at, $at, $v0
/* 47BF774 80080244 0047228C */  lw         $v0, %lo(jtbl_level_14_80074700)($at)
/* 47BF778 80080248 00000000 */  nop
/* 47BF77C 8008024C 08004000 */  jr         $v0
/* 47BF780 80080250 00000000 */   nop
.L80080254_:
/* 47BF784 80080254 2120C003 */  addu       $a0, $fp, $zero
/* 47BF788 80080258 4957010C */  jal        func_80055D24
/* 47BF78C 8008025C 05000524 */   addiu     $a1, $zero, 0x5
/* 47BF790 80080260 2120C003 */  addu       $a0, $fp, $zero
/* 47BF794 80080264 E0D3000C */  jal        func_80034F80
/* 47BF798 80080268 06000524 */   addiu     $a1, $zero, 0x6
/* 47BF79C 8008026C 1F040208 */  j          .Llevel_14_8008107C
/* 47BF7A0 80080270 1E000224 */   addiu     $v0, $zero, 0x1E
.L80080274_:
/* 47BF7A4 80080274 2120C003 */  addu       $a0, $fp, $zero
/* 47BF7A8 80080278 4957010C */  jal        func_80055D24
/* 47BF7AC 8008027C 05000524 */   addiu     $a1, $zero, 0x5
/* 47BF7B0 80080280 3C00C393 */  lbu        $v1, 0x3C($fp)
/* 47BF7B4 80080284 04000224 */  addiu      $v0, $zero, 0x4
/* 47BF7B8 80080288 7D036214 */  bne        $v1, $v0, .Llevel_14_80081080
/* 47BF7BC 8008028C 00000000 */   nop
/* 47BF7C0 80080290 0780023C */  lui        $v0, %hi(D_8006C770)
/* 47BF7C4 80080294 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 47BF7C8 80080298 00000000 */  nop
/* 47BF7CC 8008029C 78034010 */  beqz       $v0, .Llevel_14_80081080
/* 47BF7D0 800802A0 2120C003 */   addu      $a0, $fp, $zero
/* 47BF7D4 800802A4 E0D3000C */  jal        func_80034F80
/* 47BF7D8 800802A8 21280000 */   addu      $a1, $zero, $zero
/* 47BF7DC 800802AC 20040208 */  j          .Llevel_14_80081080
/* 47BF7E0 800802B0 00000000 */   nop
.L800802B4_:
/* 47BF7E4 800802B4 4900C393 */  lbu        $v1, 0x49($fp)
/* 47BF7E8 800802B8 05000224 */  addiu      $v0, $zero, 0x5
/* 47BF7EC 800802BC 60006210 */  beq        $v1, $v0, .Llevel_14_80080440
/* 47BF7F0 800802C0 05000224 */   addiu     $v0, $zero, 0x5
/* 47BF7F4 800802C4 4900C2A3 */  sb         $v0, 0x49($fp)
/* 47BF7F8 800802C8 21980000 */  addu       $s3, $zero, $zero
/* 47BF7FC 800802CC 2180E002 */  addu       $s0, $s7, $zero
.Llevel_14_800802D0:
/* 47BF800 800802D0 21900000 */  addu       $s2, $zero, $zero
/* 47BF804 800802D4 38001126 */  addiu      $s1, $s0, 0x38
.Llevel_14_800802D8:
/* 47BF808 800802D8 0000238E */  lw         $v1, 0x0($s1)
/* 47BF80C 800802DC FFFF0224 */  addiu      $v0, $zero, -0x1
/* 47BF810 800802E0 2B006210 */  beq        $v1, $v0, .Llevel_14_80080390
/* 47BF814 800802E4 40100300 */   sll       $v0, $v1, 1
/* 47BF818 800802E8 21104300 */  addu       $v0, $v0, $v1
/* 47BF81C 800802EC 80100200 */  sll        $v0, $v0, 2
/* 47BF820 800802F0 23104300 */  subu       $v0, $v0, $v1
/* 47BF824 800802F4 0780033C */  lui        $v1, %hi(D_8006C550)
/* 47BF828 800802F8 50C5638C */  lw         $v1, %lo(D_8006C550)($v1)
/* 47BF82C 800802FC C0100200 */  sll        $v0, $v0, 3
/* 47BF830 80080300 21204300 */  addu       $a0, $v0, $v1
/* 47BF834 80080304 48008290 */  lbu        $v0, 0x48($a0)
/* 47BF838 80080308 00000000 */  nop
/* 47BF83C 8008030C 80004230 */  andi       $v0, $v0, 0x80
/* 47BF840 80080310 1F004014 */  bnez       $v0, .Llevel_14_80080390
/* 47BF844 80080314 FF000224 */   addiu     $v0, $zero, 0xFF
/* 47BF848 80080318 3A008390 */  lbu        $v1, 0x3A($a0)
/* 47BF84C 8008031C 00000000 */  nop
/* 47BF850 80080320 19006214 */  bne        $v1, $v0, .Llevel_14_80080388
/* 47BF854 80080324 01000524 */   addiu     $a1, $zero, 0x1
/* 47BF858 80080328 21300000 */  addu       $a2, $zero, $zero
/* 47BF85C 8008032C 9ADA000C */  jal        func_80036A68
/* 47BF860 80080330 21380000 */   addu      $a3, $zero, $zero
/* 47BF864 80080334 0000228E */  lw         $v0, 0x0($s1)
/* 47BF868 80080338 00000000 */  nop
/* 47BF86C 8008033C 40200200 */  sll        $a0, $v0, 1
/* 47BF870 80080340 21208200 */  addu       $a0, $a0, $v0
/* 47BF874 80080344 80200400 */  sll        $a0, $a0, 2
/* 47BF878 80080348 23208200 */  subu       $a0, $a0, $v0
/* 47BF87C 8008034C 0780023C */  lui        $v0, %hi(D_8006C550)
/* 47BF880 80080350 50C5428C */  lw         $v0, %lo(D_8006C550)($v0)
/* 47BF884 80080354 C0200400 */  sll        $a0, $a0, 3
/* 47BF888 80080358 80EE000C */  jal        func_8003BA00
/* 47BF88C 8008035C 21204400 */   addu      $a0, $v0, $a0
/* 47BF890 80080360 0000228E */  lw         $v0, 0x0($s1)
/* 47BF894 80080364 00000000 */  nop
/* 47BF898 80080368 40200200 */  sll        $a0, $v0, 1
/* 47BF89C 8008036C 21208200 */  addu       $a0, $a0, $v0
/* 47BF8A0 80080370 80200400 */  sll        $a0, $a0, 2
/* 47BF8A4 80080374 23208200 */  subu       $a0, $a0, $v0
/* 47BF8A8 80080378 0780023C */  lui        $v0, %hi(D_8006C550)
/* 47BF8AC 8008037C 50C5428C */  lw         $v0, %lo(D_8006C550)($v0)
/* 47BF8B0 80080380 C0200400 */  sll        $a0, $a0, 3
/* 47BF8B4 80080384 21204400 */  addu       $a0, $v0, $a0
.Llevel_14_80080388:
/* 47BF8B8 80080388 C656010C */  jal        func_80055B18
/* 47BF8BC 8008038C 00000000 */   nop
.Llevel_14_80080390:
/* 47BF8C0 80080390 01005226 */  addiu      $s2, $s2, 0x1
/* 47BF8C4 80080394 1800422A */  slti       $v0, $s2, 0x18
/* 47BF8C8 80080398 CFFF4014 */  bnez       $v0, .Llevel_14_800802D8
/* 47BF8CC 8008039C 04003126 */   addiu     $s1, $s1, 0x4
/* 47BF8D0 800803A0 01007326 */  addiu      $s3, $s3, 0x1
/* 47BF8D4 800803A4 0300622A */  slti       $v0, $s3, 0x3
/* 47BF8D8 800803A8 C9FF4014 */  bnez       $v0, .Llevel_14_800802D0
/* 47BF8DC 800803AC 60001026 */   addiu     $s0, $s0, 0x60
/* 47BF8E0 800803B0 0780103C */  lui        $s0, %hi(D_8006C550)
/* 47BF8E4 800803B4 50C5108E */  lw         $s0, %lo(D_8006C550)($s0)
/* 47BF8E8 800803B8 0780023C */  lui        $v0, %hi(D_8006C704)
/* 47BF8EC 800803BC 04C7428C */  lw         $v0, %lo(D_8006C704)($v0)
/* 47BF8F0 800803C0 00000000 */  nop
/* 47BF8F4 800803C4 2B100202 */  sltu       $v0, $s0, $v0
/* 47BF8F8 800803C8 1D004010 */  beqz       $v0, .Llevel_14_80080440
/* 47BF8FC 800803CC 3A001126 */   addiu     $s1, $s0, 0x3A
/* 47BF900 800803D0 C2011224 */  addiu      $s2, $zero, 0x1C2
.Llevel_14_800803D4:
/* 47BF904 800803D4 FCFF2286 */  lh         $v0, -0x4($s1)
/* 47BF908 800803D8 00000000 */  nop
/* 47BF90C 800803DC 12005214 */  bne        $v0, $s2, .Llevel_14_80080428
/* 47BF910 800803E0 00000000 */   nop
/* 47BF914 800803E4 0E002292 */  lbu        $v0, 0xE($s1)
/* 47BF918 800803E8 00000000 */  nop
/* 47BF91C 800803EC 80004230 */  andi       $v0, $v0, 0x80
/* 47BF920 800803F0 0D004014 */  bnez       $v0, .Llevel_14_80080428
/* 47BF924 800803F4 FF000224 */   addiu     $v0, $zero, 0xFF
/* 47BF928 800803F8 00002392 */  lbu        $v1, 0x0($s1)
/* 47BF92C 800803FC 00000000 */  nop
/* 47BF930 80080400 07006214 */  bne        $v1, $v0, .Llevel_14_80080420
/* 47BF934 80080404 21200002 */   addu      $a0, $s0, $zero
/* 47BF938 80080408 01000524 */  addiu      $a1, $zero, 0x1
/* 47BF93C 8008040C 21300000 */  addu       $a2, $zero, $zero
/* 47BF940 80080410 9ADA000C */  jal        func_80036A68
/* 47BF944 80080414 21380000 */   addu      $a3, $zero, $zero
/* 47BF948 80080418 80EE000C */  jal        func_8003BA00
/* 47BF94C 8008041C 21200002 */   addu      $a0, $s0, $zero
.Llevel_14_80080420:
/* 47BF950 80080420 C656010C */  jal        func_80055B18
/* 47BF954 80080424 21200002 */   addu      $a0, $s0, $zero
.Llevel_14_80080428:
/* 47BF958 80080428 0780023C */  lui        $v0, %hi(D_8006C704)
/* 47BF95C 8008042C 04C7428C */  lw         $v0, %lo(D_8006C704)($v0)
/* 47BF960 80080430 58001026 */  addiu      $s0, $s0, 0x58
/* 47BF964 80080434 2B100202 */  sltu       $v0, $s0, $v0
/* 47BF968 80080438 E6FF4014 */  bnez       $v0, .Llevel_14_800803D4
/* 47BF96C 8008043C 58003126 */   addiu     $s1, $s1, 0x58
.Llevel_14_80080440:
/* 47BF970 80080440 09000424 */  addiu      $a0, $zero, 0x9
/* 47BF974 80080444 FF000224 */  addiu      $v0, $zero, 0xFF
/* 47BF978 80080448 4A00C2A3 */  sb         $v0, 0x4A($fp)
/* 47BF97C 8008044C 4100C0A3 */  sb         $zero, 0x41($fp)
/* 47BF980 80080450 4C00C0A3 */  sb         $zero, 0x4C($fp)
/* 47BF984 80080454 4D00C0A3 */  sb         $zero, 0x4D($fp)
/* 47BF988 80080458 CF87000C */  jal        func_80021F3C
/* 47BF98C 8008045C 0800C0AF */   sw        $zero, 0x8($fp)
/* 47BF990 80080460 21884000 */  addu       $s1, $v0, $zero
/* 47BF994 80080464 03121100 */  sra        $v0, $s1, 8
/* 47BF998 80080468 FF005030 */  andi       $s0, $v0, 0xFF
/* 47BF99C 8008046C 06000016 */  bnez       $s0, .Llevel_14_80080488
/* 47BF9A0 80080470 0F002232 */   andi      $v0, $s1, 0xF
/* 47BF9A4 80080474 04004010 */  beqz       $v0, .Llevel_14_80080488
/* 47BF9A8 80080478 09000424 */   addiu     $a0, $zero, 0x9
/* 47BF9AC 8008047C FC000524 */  addiu      $a1, $zero, 0xFC
/* 47BF9B0 80080480 B687000C */  jal        func_80021ED8
/* 47BF9B4 80080484 21300000 */   addu      $a2, $zero, $zero
.Llevel_14_80080488:
/* 47BF9B8 80080488 CF87000C */  jal        func_80021F3C
/* 47BF9BC 8008048C 0A000424 */   addiu     $a0, $zero, 0xA
/* 47BF9C0 80080490 21884000 */  addu       $s1, $v0, $zero
/* 47BF9C4 80080494 03121100 */  sra        $v0, $s1, 8
/* 47BF9C8 80080498 FF005030 */  andi       $s0, $v0, 0xFF
/* 47BF9CC 8008049C 3C000224 */  addiu      $v0, $zero, 0x3C
/* 47BF9D0 800804A0 1A000212 */  beq        $s0, $v0, .Llevel_14_8008050C
/* 47BF9D4 800804A4 0F003232 */   andi      $s2, $s1, 0xF
/* 47BF9D8 800804A8 04004012 */  beqz       $s2, .Llevel_14_800804BC
/* 47BF9DC 800804AC 0A000424 */   addiu     $a0, $zero, 0xA
/* 47BF9E0 800804B0 FC000524 */  addiu      $a1, $zero, 0xFC
/* 47BF9E4 800804B4 B687000C */  jal        func_80021ED8
/* 47BF9E8 800804B8 21300000 */   addu      $a2, $zero, $zero
.Llevel_14_800804BC:
/* 47BF9EC 800804BC FEFF0226 */  addiu      $v0, $s0, -0x2
/* 47BF9F0 800804C0 1000422C */  sltiu      $v0, $v0, 0x10
/* 47BF9F4 800804C4 06004010 */  beqz       $v0, .Llevel_14_800804E0
/* 47BF9F8 800804C8 00000000 */   nop
/* 47BF9FC 800804CC 05004016 */  bnez       $s2, .Llevel_14_800804E4
/* 47BFA00 800804D0 ECFF0226 */   addiu     $v0, $s0, -0x14
/* 47BFA04 800804D4 0A000424 */  addiu      $a0, $zero, 0xA
/* 47BFA08 800804D8 3F010208 */  j          .Llevel_14_800804FC
/* 47BFA0C 800804DC 12000524 */   addiu     $a1, $zero, 0x12
.Llevel_14_800804E0:
/* 47BFA10 800804E0 ECFF0226 */  addiu      $v0, $s0, -0x14
.Llevel_14_800804E4:
/* 47BFA14 800804E4 2700422C */  sltiu      $v0, $v0, 0x27
/* 47BFA18 800804E8 E5024010 */  beqz       $v0, .Llevel_14_80081080
/* 47BFA1C 800804EC 0F002232 */   andi      $v0, $s1, 0xF
/* 47BFA20 800804F0 E3024014 */  bnez       $v0, .Llevel_14_80081080
/* 47BFA24 800804F4 0A000424 */   addiu     $a0, $zero, 0xA
/* 47BFA28 800804F8 3B000524 */  addiu      $a1, $zero, 0x3B
.Llevel_14_800804FC:
/* 47BFA2C 800804FC E387000C */  jal        func_80021F8C
/* 47BFA30 80080500 21300000 */   addu      $a2, $zero, $zero
/* 47BFA34 80080504 20040208 */  j          .Llevel_14_80081080
/* 47BFA38 80080508 00000000 */   nop
.Llevel_14_8008050C:
/* 47BFA3C 8008050C C656010C */  jal        func_80055B18
/* 47BFA40 80080510 2120C003 */   addu      $a0, $fp, $zero
/* 47BFA44 80080514 20040208 */  j          .Llevel_14_80081080
/* 47BFA48 80080518 00000000 */   nop
.L8008051C_:
/* 47BFA4C 8008051C 2800E28E */  lw         $v0, 0x28($s7)
/* 47BFA50 80080520 00000000 */  nop
/* 47BFA54 80080524 01004224 */  addiu      $v0, $v0, 0x1
/* 47BFA58 80080528 2800E2AE */  sw         $v0, 0x28($s7)
/* 47BFA5C 8008052C 1E004228 */  slti       $v0, $v0, 0x1E
/* 47BFA60 80080530 D3024014 */  bnez       $v0, .Llevel_14_80081080
/* 47BFA64 80080534 00000000 */   nop
/* 47BFA68 80080538 20040208 */  j          .Llevel_14_80081080
/* 47BFA6C 8008053C 4800C0A3 */   sb        $zero, 0x48($fp)
.L80080540_:
/* 47BFA70 80080540 0C00C427 */  addiu      $a0, $fp, 0xC
/* 47BFA74 80080544 0780113C */  lui        $s1, %hi(D_80070328)
/* 47BFA78 80080548 28033126 */  addiu      $s1, $s1, %lo(D_80070328)
/* 47BFA7C 8008054C CD3C010C */  jal        func_8004F334
/* 47BFA80 80080550 21282002 */   addu      $a1, $s1, $zero
/* 47BFA84 80080554 2120C003 */  addu       $a0, $fp, $zero
/* 47BFA88 80080558 21280000 */  addu       $a1, $zero, $zero
/* 47BFA8C 8008055C EFDE000C */  jal        func_80037BBC
/* 47BFA90 80080560 21804000 */   addu      $s0, $v0, $zero
/* 47BFA94 80080564 15004014 */  bnez       $v0, .Llevel_14_800805BC
/* 47BFA98 80080568 00000000 */   nop
/* 47BFA9C 8008056C 000C022A */  slti       $v0, $s0, 0xC00
/* 47BFAA0 80080570 12004014 */  bnez       $v0, .Llevel_14_800805BC
/* 47BFAA4 80080574 00000000 */   nop
/* 47BFAA8 80080578 0018022A */  slti       $v0, $s0, 0x1800
/* 47BFAAC 8008057C C0024010 */  beqz       $v0, .Llevel_14_80081080
/* 47BFAB0 80080580 21300000 */   addu      $a2, $zero, $zero
/* 47BFAB4 80080584 0000238E */  lw         $v1, 0x0($s1)
/* 47BFAB8 80080588 0C00C48F */  lw         $a0, 0xC($fp)
/* 47BFABC 8008058C 0780023C */  lui        $v0, %hi(D_80070328 + 4)
/* 47BFAC0 80080590 2C03428C */  lw         $v0, %lo(D_80070328 + 4)($v0)
/* 47BFAC4 80080594 1000C58F */  lw         $a1, 0x10($fp)
/* 47BFAC8 80080598 23206400 */  subu       $a0, $v1, $a0
/* 47BFACC 8008059C 203A010C */  jal        func_8004E880
/* 47BFAD0 800805A0 23284500 */   subu      $a1, $v0, $a1
/* 47BFAD4 800805A4 4600C593 */  lbu        $a1, 0x46($fp)
/* 47BFAD8 800805A8 993C010C */  jal        func_8004F264
/* 47BFADC 800805AC 21204000 */   addu      $a0, $v0, $zero
/* 47BFAE0 800805B0 41004228 */  slti       $v0, $v0, 0x41
/* 47BFAE4 800805B4 B2024014 */  bnez       $v0, .Llevel_14_80081080
/* 47BFAE8 800805B8 00000000 */   nop
.Llevel_14_800805BC:
/* 47BFAEC 800805BC 4800D027 */  addiu      $s0, $fp, 0x48
/* 47BFAF0 800805C0 21200002 */  addu       $a0, $s0, $zero
/* 47BFAF4 800805C4 01000524 */  addiu      $a1, $zero, 0x1
/* 47BFAF8 800805C8 0780113C */  lui        $s1, %hi(D_8006D088)
/* 47BFAFC 800805CC 88D03126 */  addiu      $s1, $s1, %lo(D_8006D088)
/* 47BFB00 800805D0 21302002 */  addu       $a2, $s1, $zero
/* 47BFB04 800805D4 2B000224 */  addiu      $v0, $zero, 0x2B
/* 47BFB08 800805D8 EDED000C */  jal        func_8003B7B4
/* 47BFB0C 800805DC 4800C2A3 */   sb        $v0, 0x48($fp)
/* 47BFB10 800805E0 21200002 */  addu       $a0, $s0, $zero
/* 47BFB14 800805E4 0780063C */  lui        $a2, %hi(D_8006C7F8)
/* 47BFB18 800805E8 F8C7C624 */  addiu      $a2, $a2, %lo(D_8006C7F8)
/* 47BFB1C 800805EC EDED000C */  jal        func_8003B7B4
/* 47BFB20 800805F0 01000524 */   addiu     $a1, $zero, 0x1
/* 47BFB24 800805F4 4600C293 */  lbu        $v0, 0x46($fp)
/* 47BFB28 800805F8 3000B027 */  addiu      $s0, $sp, 0x30
/* 47BFB2C 800805FC 40100200 */  sll        $v0, $v0, 1
/* 47BFB30 80080600 0680013C */  lui        $at, %hi(D_80065920)
/* 47BFB34 80080604 21082200 */  addu       $at, $at, $v0
/* 47BFB38 80080608 20592384 */  lh         $v1, %lo(D_80065920)($at)
/* 47BFB3C 8008060C 21200002 */  addu       $a0, $s0, $zero
/* 47BFB40 80080610 40100300 */  sll        $v0, $v1, 1
/* 47BFB44 80080614 21104300 */  addu       $v0, $v0, $v1
/* 47BFB48 80080618 80100200 */  sll        $v0, $v0, 2
/* 47BFB4C 8008061C 21104300 */  addu       $v0, $v0, $v1
/* 47BFB50 80080620 43110200 */  sra        $v0, $v0, 5
/* 47BFB54 80080624 3000A2AF */  sw         $v0, 0x30($sp)
/* 47BFB58 80080628 4600C293 */  lbu        $v0, 0x46($fp)
/* 47BFB5C 8008062C 0C00C527 */  addiu      $a1, $fp, 0xC
/* 47BFB60 80080630 40100200 */  sll        $v0, $v0, 1
/* 47BFB64 80080634 0680013C */  lui        $at, %hi(D_800658A0)
/* 47BFB68 80080638 21082200 */  addu       $at, $at, $v0
/* 47BFB6C 8008063C A0582384 */  lh         $v1, %lo(D_800658A0)($at)
/* 47BFB70 80080640 21300002 */  addu       $a2, $s0, $zero
/* 47BFB74 80080644 3800A0AF */  sw         $zero, 0x38($sp)
/* 47BFB78 80080648 40100300 */  sll        $v0, $v1, 1
/* 47BFB7C 8008064C 21104300 */  addu       $v0, $v0, $v1
/* 47BFB80 80080650 80100200 */  sll        $v0, $v0, 2
/* 47BFB84 80080654 21104300 */  addu       $v0, $v0, $v1
/* 47BFB88 80080658 43110200 */  sra        $v0, $v0, 5
/* 47BFB8C 8008065C 653C010C */  jal        func_8004F194
/* 47BFB90 80080660 3400A2AF */   sw        $v0, 0x34($sp)
/* 47BFB94 80080664 21202002 */  addu       $a0, $s1, $zero
/* 47BFB98 80080668 4600C693 */  lbu        $a2, 0x46($fp)
/* 47BFB9C 8008066C 21280002 */  addu       $a1, $s0, $zero
/* 47BFBA0 80080670 8000C624 */  addiu      $a2, $a2, 0x80
/* 47BFBA4 80080674 8DED000C */  jal        func_8003B634
/* 47BFBA8 80080678 FF00C630 */   andi      $a2, $a2, 0xFF
/* 47BFBAC 8008067C 2120C003 */  addu       $a0, $fp, $zero
/* 47BFBB0 80080680 21280000 */  addu       $a1, $zero, $zero
/* 47BFBB4 80080684 B944010C */  jal        func_800512E4
/* 47BFBB8 80080688 01000624 */   addiu     $a2, $zero, 0x1
/* 47BFBBC 8008068C 1F040208 */  j          .Llevel_14_8008107C
/* 47BFBC0 80080690 01000224 */   addiu     $v0, $zero, 0x1
.L80080694_:
/* 47BFBC4 80080694 0780023C */  lui        $v0, %hi(D_8006E344)
/* 47BFBC8 80080698 44E3428C */  lw         $v0, %lo(D_8006E344)($v0)
/* 47BFBCC 8008069C 01001024 */  addiu      $s0, $zero, 0x1
/* 47BFBD0 800806A0 77025010 */  beq        $v0, $s0, .Llevel_14_80081080
/* 47BFBD4 800806A4 2120C003 */   addu      $a0, $fp, $zero
/* 47BFBD8 800806A8 D0D3000C */  jal        func_80034F40
/* 47BFBDC 800806AC 21280000 */   addu      $a1, $zero, $zero
/* 47BFBE0 800806B0 0000E292 */  lbu        $v0, 0x0($s7)
/* 47BFBE4 800806B4 00000000 */  nop
/* 47BFBE8 800806B8 6F025014 */  bne        $v0, $s0, .Llevel_14_80081078
/* 47BFBEC 800806BC 00000000 */   nop
/* 47BFBF0 800806C0 0400E392 */  lbu        $v1, 0x4($s7)
/* 47BFBF4 800806C4 00000000 */  nop
/* 47BFBF8 800806C8 03006010 */  beqz       $v1, .Llevel_14_800806D8
/* 47BFBFC 800806CC 03000224 */   addiu     $v0, $zero, 0x3
/* 47BFC00 800806D0 2C006214 */  bne        $v1, $v0, .Llevel_14_80080784
/* 47BFC04 800806D4 04000224 */   addiu     $v0, $zero, 0x4
.Llevel_14_800806D8:
/* 47BFC08 800806D8 0200F026 */  addiu      $s0, $s7, 0x2
/* 47BFC0C 800806DC 21200002 */  addu       $a0, $s0, $zero
/* 47BFC10 800806E0 01000524 */  addiu      $a1, $zero, 0x1
/* 47BFC14 800806E4 0780063C */  lui        $a2, %hi(D_8006D088)
/* 47BFC18 800806E8 88D0C624 */  addiu      $a2, $a2, %lo(D_8006D088)
/* 47BFC1C 800806EC 02000224 */  addiu      $v0, $zero, 0x2
/* 47BFC20 800806F0 EDED000C */  jal        func_8003B7B4
/* 47BFC24 800806F4 0200E2A2 */   sb        $v0, 0x2($s7)
/* 47BFC28 800806F8 21200002 */  addu       $a0, $s0, $zero
/* 47BFC2C 800806FC 0780063C */  lui        $a2, %hi(D_8006C7F8)
/* 47BFC30 80080700 F8C7C624 */  addiu      $a2, $a2, %lo(D_8006C7F8)
/* 47BFC34 80080704 EDED000C */  jal        func_8003B7B4
/* 47BFC38 80080708 01000524 */   addiu     $a1, $zero, 0x1
/* 47BFC3C 8008070C FF000224 */  addiu      $v0, $zero, 0xFF
/* 47BFC40 80080710 4A00C2A3 */  sb         $v0, 0x4A($fp)
/* 47BFC44 80080714 26000224 */  addiu      $v0, $zero, 0x26
/* 47BFC48 80080718 4800C2A3 */  sb         $v0, 0x48($fp)
/* 47BFC4C 8008071C 5801E28E */  lw         $v0, 0x158($s7)
/* 47BFC50 80080720 00000000 */  nop
/* 47BFC54 80080724 56024014 */  bnez       $v0, .Llevel_14_80081080
/* 47BFC58 80080728 12000424 */   addiu     $a0, $zero, 0x12
/* 47BFC5C 8008072C 03000524 */  addiu      $a1, $zero, 0x3
/* 47BFC60 80080730 21300000 */  addu       $a2, $zero, $zero
/* 47BFC64 80080734 21380000 */  addu       $a3, $zero, $zero
/* 47BFC68 80080738 0780023C */  lui        $v0, %hi(D_8006C7C4)
/* 47BFC6C 8008073C C4C7428C */  lw         $v0, %lo(D_8006C7C4)($v0)
/* 47BFC70 80080740 0780033C */  lui        $v1, %hi(unk_ovlheader_80074370)
/* 47BFC74 80080744 7043638C */  lw         $v1, %lo(unk_ovlheader_80074370)($v1)
/* 47BFC78 80080748 80100200 */  sll        $v0, $v0, 2
/* 47BFC7C 8008074C 2110A203 */  addu       $v0, $sp, $v0
/* 47BFC80 80080750 2000428C */  lw         $v0, 0x20($v0)
/* 47BFC84 80080754 18150824 */  addiu      $t0, $zero, 0x1518
/* 47BFC88 80080758 5C01E8AE */  sw         $t0, 0x15C($s7)
/* 47BFC8C 8008075C 2800E2AE */  sw         $v0, 0x28($s7)
/* 47BFC90 80080760 5C01E226 */  addiu      $v0, $s7, 0x15C
/* 47BFC94 80080764 1000A3AF */  sw         $v1, 0x10($sp)
/* 47BFC98 80080768 1400A2AF */  sw         $v0, 0x14($sp)
/* 47BFC9C 8008076C 0FA0000C */  jal        func_8002803C
/* 47BFCA0 80080770 1800A8AF */   sw        $t0, 0x18($sp)
/* 47BFCA4 80080774 00140200 */  sll        $v0, $v0, 16
/* 47BFCA8 80080778 03140200 */  sra        $v0, $v0, 16
/* 47BFCAC 8008077C 20040208 */  j          .Llevel_14_80081080
/* 47BFCB0 80080780 5801E2AE */   sw        $v0, 0x158($s7)
.Llevel_14_80080784:
/* 47BFCB4 80080784 3D026214 */  bne        $v1, $v0, .Llevel_14_8008107C
/* 47BFCB8 80080788 1E000224 */   addiu     $v0, $zero, 0x1E
/* 47BFCBC 8008078C 1F040208 */  j          .Llevel_14_8008107C
/* 47BFCC0 80080790 28000224 */   addiu     $v0, $zero, 0x28
.L80080794_:
/* 47BFCC4 80080794 2800E426 */  addiu      $a0, $s7, 0x28
/* 47BFCC8 80080798 69D6000C */  jal        func_800359A4
/* 47BFCCC 8008079C 04000524 */   addiu     $a1, $zero, 0x4
/* 47BFCD0 800807A0 6F004010 */  beqz       $v0, .Llevel_14_80080960
/* 47BFCD4 800807A4 00000000 */   nop
/* 47BFCD8 800807A8 5801E48E */  lw         $a0, 0x158($s7)
/* 47BFCDC 800807AC 55A0000C */  jal        func_80028154
/* 47BFCE0 800807B0 0C00D627 */   addiu     $s6, $fp, 0xC
/* 47BFCE4 800807B4 2120C003 */  addu       $a0, $fp, $zero
/* 47BFCE8 800807B8 04000524 */  addiu      $a1, $zero, 0x4
/* 47BFCEC 800807BC 4957010C */  jal        func_80055D24
/* 47BFCF0 800807C0 5801E0AE */   sw        $zero, 0x158($s7)
/* 47BFCF4 800807C4 2000C927 */  addiu      $t1, $fp, 0x20
/* 47BFCF8 800807C8 4000B227 */  addiu      $s2, $sp, 0x40
/* 47BFCFC 800807CC 21284002 */  addu       $a1, $s2, $zero
/* 47BFD00 800807D0 21304002 */  addu       $a2, $s2, $zero
/* 47BFD04 800807D4 8800A9AF */  sw         $t1, 0x88($sp)
/* 47BFD08 800807D8 8800A48F */  lw         $a0, 0x88($sp)
/* 47BFD0C 800807DC 00080224 */  addiu      $v0, $zero, 0x800
/* 47BFD10 800807E0 4000A2AF */  sw         $v0, 0x40($sp)
/* 47BFD14 800807E4 00020224 */  addiu      $v0, $zero, 0x200
/* 47BFD18 800807E8 4400A0AF */  sw         $zero, 0x44($sp)
/* 47BFD1C 800807EC 5B3B010C */  jal        func_8004ED6C
/* 47BFD20 800807F0 4800A2AF */   sw        $v0, 0x48($sp)
/* 47BFD24 800807F4 21204002 */  addu       $a0, $s2, $zero
/* 47BFD28 800807F8 2128C002 */  addu       $a1, $s6, $zero
/* 47BFD2C 800807FC 653C010C */  jal        func_8004F194
/* 47BFD30 80080800 21304002 */   addu      $a2, $s2, $zero
/* 47BFD34 80080804 5000B527 */  addiu      $s5, $sp, 0x50
/* 47BFD38 80080808 2120A002 */  addu       $a0, $s5, $zero
/* 47BFD3C 8008080C 0780103C */  lui        $s0, %hi(D_80070328)
/* 47BFD40 80080810 28031026 */  addiu      $s0, $s0, %lo(D_80070328)
/* 47BFD44 80080814 5E3C010C */  jal        func_8004F178
/* 47BFD48 80080818 21280002 */   addu      $a1, $s0, $zero
/* 47BFD4C 8008081C 21200002 */  addu       $a0, $s0, $zero
/* 47BFD50 80080820 0E000992 */  lbu        $t1, 0xE($s0)
/* 47BFD54 80080824 21284002 */  addu       $a1, $s2, $zero
/* 47BFD58 80080828 5E3C010C */  jal        func_8004F178
/* 47BFD5C 8008082C 8000A9AF */   sw        $t1, 0x80($sp)
/* 47BFD60 80080830 21200002 */  addu       $a0, $s0, $zero
/* 47BFD64 80080834 04000524 */  addiu      $a1, $zero, 0x4
/* 47BFD68 80080838 0780143C */  lui        $s4, %hi(D_8006D088)
/* 47BFD6C 8008083C 88D09426 */  addiu      $s4, $s4, %lo(D_8006D088)
/* 47BFD70 80080840 4600C293 */  lbu        $v0, 0x46($fp)
/* 47BFD74 80080844 21308002 */  addu       $a2, $s4, $zero
/* 47BFD78 80080848 80004224 */  addiu      $v0, $v0, 0x80
/* 47BFD7C 8008084C EDED000C */  jal        func_8003B7B4
/* 47BFD80 80080850 0E0002A2 */   sb        $v0, 0xE($s0)
/* 47BFD84 80080854 21200002 */  addu       $a0, $s0, $zero
/* 47BFD88 80080858 04000524 */  addiu      $a1, $zero, 0x4
/* 47BFD8C 8008085C 0780133C */  lui        $s3, %hi(D_8006C7F8)
/* 47BFD90 80080860 F8C77326 */  addiu      $s3, $s3, %lo(D_8006C7F8)
/* 47BFD94 80080864 EDED000C */  jal        func_8003B7B4
/* 47BFD98 80080868 21306002 */   addu      $a2, $s3, $zero
/* 47BFD9C 8008086C 04001126 */  addiu      $s1, $s0, 0x4
/* 47BFDA0 80080870 21202002 */  addu       $a0, $s1, $zero
/* 47BFDA4 80080874 04000524 */  addiu      $a1, $zero, 0x4
/* 47BFDA8 80080878 EDED000C */  jal        func_8003B7B4
/* 47BFDAC 8008087C 21308002 */   addu      $a2, $s4, $zero
/* 47BFDB0 80080880 21202002 */  addu       $a0, $s1, $zero
/* 47BFDB4 80080884 04000524 */  addiu      $a1, $zero, 0x4
/* 47BFDB8 80080888 EDED000C */  jal        func_8003B7B4
/* 47BFDBC 8008088C 21306002 */   addu      $a2, $s3, $zero
/* 47BFDC0 80080890 08001126 */  addiu      $s1, $s0, 0x8
/* 47BFDC4 80080894 21202002 */  addu       $a0, $s1, $zero
/* 47BFDC8 80080898 04000524 */  addiu      $a1, $zero, 0x4
/* 47BFDCC 8008089C EDED000C */  jal        func_8003B7B4
/* 47BFDD0 800808A0 21308002 */   addu      $a2, $s4, $zero
/* 47BFDD4 800808A4 21202002 */  addu       $a0, $s1, $zero
/* 47BFDD8 800808A8 04000524 */  addiu      $a1, $zero, 0x4
/* 47BFDDC 800808AC EDED000C */  jal        func_8003B7B4
/* 47BFDE0 800808B0 21306002 */   addu      $a2, $s3, $zero
/* 47BFDE4 800808B4 0E001126 */  addiu      $s1, $s0, 0xE
/* 47BFDE8 800808B8 21202002 */  addu       $a0, $s1, $zero
/* 47BFDEC 800808BC 01000524 */  addiu      $a1, $zero, 0x1
/* 47BFDF0 800808C0 EDED000C */  jal        func_8003B7B4
/* 47BFDF4 800808C4 21308002 */   addu      $a2, $s4, $zero
/* 47BFDF8 800808C8 21202002 */  addu       $a0, $s1, $zero
/* 47BFDFC 800808CC 01000524 */  addiu      $a1, $zero, 0x1
/* 47BFE00 800808D0 EDED000C */  jal        func_8003B7B4
/* 47BFE04 800808D4 21306002 */   addu      $a2, $s3, $zero
/* 47BFE08 800808D8 21200002 */  addu       $a0, $s0, $zero
/* 47BFE0C 800808DC 5E3C010C */  jal        func_8004F178
/* 47BFE10 800808E0 2128A002 */   addu      $a1, $s5, $zero
/* 47BFE14 800808E4 21284002 */  addu       $a1, $s2, $zero
/* 47BFE18 800808E8 21304002 */  addu       $a2, $s2, $zero
/* 47BFE1C 800808EC 8800A48F */  lw         $a0, 0x88($sp)
/* 47BFE20 800808F0 8000A993 */  lbu        $t1, 0x80($sp)
/* 47BFE24 800808F4 00140224 */  addiu      $v0, $zero, 0x1400
/* 47BFE28 800808F8 0E0009A2 */  sb         $t1, 0xE($s0)
/* 47BFE2C 800808FC 4000A2AF */  sw         $v0, 0x40($sp)
/* 47BFE30 80080900 FC0F0224 */  addiu      $v0, $zero, 0xFFC
/* 47BFE34 80080904 4400A0AF */  sw         $zero, 0x44($sp)
/* 47BFE38 80080908 5B3B010C */  jal        func_8004ED6C
/* 47BFE3C 8008090C 4800A2AF */   sw        $v0, 0x48($sp)
/* 47BFE40 80080910 21204002 */  addu       $a0, $s2, $zero
/* 47BFE44 80080914 2128C002 */  addu       $a1, $s6, $zero
/* 47BFE48 80080918 653C010C */  jal        func_8004F194
/* 47BFE4C 8008091C 21304002 */   addu      $a2, $s2, $zero
/* 47BFE50 80080920 2120A002 */  addu       $a0, $s5, $zero
/* 47BFE54 80080924 5E3C010C */  jal        func_8004F178
/* 47BFE58 80080928 2128C002 */   addu      $a1, $s6, $zero
/* 47BFE5C 8008092C 21204002 */  addu       $a0, $s2, $zero
/* 47BFE60 80080930 5800A28F */  lw         $v0, 0x58($sp)
/* 47BFE64 80080934 2128A002 */  addu       $a1, $s5, $zero
/* 47BFE68 80080938 2C014224 */  addiu      $v0, $v0, 0x12C
/* 47BFE6C 8008093C B94E000C */  jal        func_80013AE4
/* 47BFE70 80080940 5800A2AF */   sw        $v0, 0x58($sp)
/* 47BFE74 80080944 2120C003 */  addu       $a0, $fp, $zero
/* 47BFE78 80080948 E0D3000C */  jal        func_80034F80
/* 47BFE7C 8008094C 06000524 */   addiu     $a1, $zero, 0x6
/* 47BFE80 80080950 3C000224 */  addiu      $v0, $zero, 0x3C
/* 47BFE84 80080954 2800E2AE */  sw         $v0, 0x28($s7)
/* 47BFE88 80080958 1F040208 */  j          .Llevel_14_8008107C
/* 47BFE8C 8008095C 2C000224 */   addiu     $v0, $zero, 0x2C
.Llevel_14_80080960:
/* 47BFE90 80080960 2800E38E */  lw         $v1, 0x28($s7)
/* 47BFE94 80080964 00000000 */  nop
/* 47BFE98 80080968 40100300 */  sll        $v0, $v1, 1
/* 47BFE9C 8008096C 21104300 */  addu       $v0, $v0, $v1
/* 47BFEA0 80080970 00210200 */  sll        $a0, $v0, 4
/* 47BFEA4 80080974 23208200 */  subu       $a0, $a0, $v0
/* 47BFEA8 80080978 00110400 */  sll        $v0, $a0, 4
/* 47BFEAC 8008097C 0780033C */  lui        $v1, %hi(D_8006C7C4)
/* 47BFEB0 80080980 C4C7638C */  lw         $v1, %lo(D_8006C7C4)($v1)
/* 47BFEB4 80080984 23104400 */  subu       $v0, $v0, $a0
/* 47BFEB8 80080988 80180300 */  sll        $v1, $v1, 2
/* 47BFEBC 8008098C 2118A303 */  addu       $v1, $sp, $v1
/* 47BFEC0 80080990 2000638C */  lw         $v1, 0x20($v1)
/* 47BFEC4 80080994 C0100200 */  sll        $v0, $v0, 3
/* 47BFEC8 80080998 1A004300 */  div        $zero, $v0, $v1
/* 47BFECC 8008099C 02006014 */  bnez       $v1, .Llevel_14_800809A8
/* 47BFED0 800809A0 00000000 */   nop
/* 47BFED4 800809A4 0D000700 */  break      7
.Llevel_14_800809A8:
/* 47BFED8 800809A8 FFFF0124 */  addiu      $at, $zero, -0x1
/* 47BFEDC 800809AC 04006114 */  bne        $v1, $at, .Llevel_14_800809C0
/* 47BFEE0 800809B0 0080013C */   lui       $at, (0x80000000 >> 16)
/* 47BFEE4 800809B4 02004114 */  bne        $v0, $at, .Llevel_14_800809C0
/* 47BFEE8 800809B8 00000000 */   nop
/* 47BFEEC 800809BC 0D000600 */  break      6
.Llevel_14_800809C0:
/* 47BFEF0 800809C0 12100000 */  mflo       $v0
/* 47BFEF4 800809C4 20040208 */  j          .Llevel_14_80081080
/* 47BFEF8 800809C8 5C01E2AE */   sw        $v0, 0x15C($s7)
.L800809CC_:
/* 47BFEFC 800809CC 5801E48E */  lw         $a0, 0x158($s7)
/* 47BFF00 800809D0 00000000 */  nop
/* 47BFF04 800809D4 AA018010 */  beqz       $a0, .Llevel_14_80081080
/* 47BFF08 800809D8 00000000 */   nop
/* 47BFF0C 800809DC 55A0000C */  jal        func_80028154
/* 47BFF10 800809E0 00000000 */   nop
/* 47BFF14 800809E4 20040208 */  j          .Llevel_14_80081080
/* 47BFF18 800809E8 5801E0AE */   sw        $zero, 0x158($s7)
.L800809EC_:
/* 47BFF1C 800809EC 2800E426 */  addiu      $a0, $s7, 0x28
/* 47BFF20 800809F0 69D6000C */  jal        func_800359A4
/* 47BFF24 800809F4 04000524 */   addiu     $a1, $zero, 0x4
/* 47BFF28 800809F8 A1014010 */  beqz       $v0, .Llevel_14_80081080
/* 47BFF2C 800809FC 00000000 */   nop
/* 47BFF30 80080A00 0780103C */  lui        $s0, %hi(D_8006C550)
/* 47BFF34 80080A04 50C5108E */  lw         $s0, %lo(D_8006C550)($s0)
/* 47BFF38 80080A08 0780023C */  lui        $v0, %hi(D_8006C704)
/* 47BFF3C 80080A0C 04C7428C */  lw         $v0, %lo(D_8006C704)($v0)
/* 47BFF40 80080A10 00000000 */  nop
/* 47BFF44 80080A14 2B100202 */  sltu       $v0, $s0, $v0
/* 47BFF48 80080A18 2A004010 */  beqz       $v0, .Llevel_14_80080AC4
/* 47BFF4C 80080A1C 2C011424 */   addiu     $s4, $zero, 0x12C
/* 47BFF50 80080A20 6000B327 */  addiu      $s3, $sp, 0x60
/* 47BFF54 80080A24 46001226 */  addiu      $s2, $s0, 0x46
.Llevel_14_80080A28:
/* 47BFF58 80080A28 F0FF4386 */  lh         $v1, -0x10($s2)
/* 47BFF5C 80080A2C 02010224 */  addiu      $v0, $zero, 0x102
/* 47BFF60 80080A30 1E006214 */  bne        $v1, $v0, .Llevel_14_80080AAC
/* 47BFF64 80080A34 9B010424 */   addiu     $a0, $zero, 0x19B
/* 47BFF68 80080A38 0780023C */  lui        $v0, %hi(SpawnMoby)
/* 47BFF6C 80080A3C E042428C */  lw         $v0, %lo(SpawnMoby)($v0)
/* 47BFF70 80080A40 00000000 */  nop
/* 47BFF74 80080A44 09F84000 */  jalr       $v0
/* 47BFF78 80080A48 2128C003 */   addu      $a1, $fp, $zero
/* 47BFF7C 80080A4C 21884000 */  addu       $s1, $v0, $zero
/* 47BFF80 80080A50 13002012 */  beqz       $s1, .Llevel_14_80080AA0
/* 47BFF84 80080A54 21200002 */   addu      $a0, $s0, $zero
/* 47BFF88 80080A58 0000228E */  lw         $v0, 0x0($s1)
/* 47BFF8C 80080A5C 04000524 */  addiu      $a1, $zero, 0x4
/* 47BFF90 80080A60 4957010C */  jal        func_80055D24
/* 47BFF94 80080A64 000040AC */   sw        $zero, 0x0($v0)
/* 47BFF98 80080A68 20000426 */  addiu      $a0, $s0, 0x20
/* 47BFF9C 80080A6C 21286002 */  addu       $a1, $s3, $zero
/* 47BFFA0 80080A70 21306002 */  addu       $a2, $s3, $zero
/* 47BFFA4 80080A74 6000B4AF */  sw         $s4, 0x60($sp)
/* 47BFFA8 80080A78 6400A0AF */  sw         $zero, 0x64($sp)
/* 47BFFAC 80080A7C 5B3B010C */  jal        func_8004ED6C
/* 47BFFB0 80080A80 6800B4AF */   sw        $s4, 0x68($sp)
/* 47BFFB4 80080A84 0C002426 */  addiu      $a0, $s1, 0xC
/* 47BFFB8 80080A88 0C000526 */  addiu      $a1, $s0, 0xC
/* 47BFFBC 80080A8C 653C010C */  jal        func_8004F194
/* 47BFFC0 80080A90 21306002 */   addu      $a2, $s3, $zero
/* 47BFFC4 80080A94 00004292 */  lbu        $v0, 0x0($s2)
/* 47BFFC8 80080A98 00000000 */  nop
/* 47BFFCC 80080A9C 460022A2 */  sb         $v0, 0x46($s1)
.Llevel_14_80080AA0:
/* 47BFFD0 80080AA0 21200002 */  addu       $a0, $s0, $zero
/* 47BFFD4 80080AA4 E0D3000C */  jal        func_80034F80
/* 47BFFD8 80080AA8 04000524 */   addiu     $a1, $zero, 0x4
.Llevel_14_80080AAC:
/* 47BFFDC 80080AAC 0780023C */  lui        $v0, %hi(D_8006C704)
/* 47BFFE0 80080AB0 04C7428C */  lw         $v0, %lo(D_8006C704)($v0)
/* 47BFFE4 80080AB4 58001026 */  addiu      $s0, $s0, 0x58
/* 47BFFE8 80080AB8 2B100202 */  sltu       $v0, $s0, $v0
/* 47BFFEC 80080ABC DAFF4014 */  bnez       $v0, .Llevel_14_80080A28
/* 47BFFF0 80080AC0 58005226 */   addiu     $s2, $s2, 0x58
.Llevel_14_80080AC4:
/* 47BFFF4 80080AC4 5A000224 */  addiu      $v0, $zero, 0x5A
/* 47BFFF8 80080AC8 2800E2AE */  sw         $v0, 0x28($s7)
/* 47BFFFC 80080ACC 1F040208 */  j          .Llevel_14_8008107C
/* 47C0000 80080AD0 2D000224 */   addiu     $v0, $zero, 0x2D
.L80080AD4_:
/* 47C0004 80080AD4 0780023C */  lui        $v0, %hi(D_8006C770)
/* 47C0008 80080AD8 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 47C000C 80080ADC 00000000 */  nop
/* 47C0010 80080AE0 03004010 */  beqz       $v0, .Llevel_14_80080AF0
/* 47C0014 80080AE4 2120C003 */   addu      $a0, $fp, $zero
/* 47C0018 80080AE8 D0D3000C */  jal        func_80034F40
/* 47C001C 80080AEC 21280000 */   addu      $a1, $zero, $zero
.Llevel_14_80080AF0:
/* 47C0020 80080AF0 2800E426 */  addiu      $a0, $s7, 0x28
/* 47C0024 80080AF4 69D6000C */  jal        func_800359A4
/* 47C0028 80080AF8 04000524 */   addiu     $a1, $zero, 0x4
/* 47C002C 80080AFC 60014010 */  beqz       $v0, .Llevel_14_80081080
/* 47C0030 80080B00 05000224 */   addiu     $v0, $zero, 0x5
/* 47C0034 80080B04 0200E2A2 */  sb         $v0, 0x2($s7)
/* 47C0038 80080B08 0200F026 */  addiu      $s0, $s7, 0x2
/* 47C003C 80080B0C 21200002 */  addu       $a0, $s0, $zero
/* 47C0040 80080B10 01000524 */  addiu      $a1, $zero, 0x1
/* 47C0044 80080B14 0780113C */  lui        $s1, %hi(D_8006D088)
/* 47C0048 80080B18 88D03126 */  addiu      $s1, $s1, %lo(D_8006D088)
/* 47C004C 80080B1C EDED000C */  jal        func_8003B7B4
/* 47C0050 80080B20 21302002 */   addu      $a2, $s1, $zero
/* 47C0054 80080B24 21200002 */  addu       $a0, $s0, $zero
/* 47C0058 80080B28 0780063C */  lui        $a2, %hi(D_8006C7F8)
/* 47C005C 80080B2C F8C7C624 */  addiu      $a2, $a2, %lo(D_8006C7F8)
/* 47C0060 80080B30 EDED000C */  jal        func_8003B7B4
/* 47C0064 80080B34 01000524 */   addiu     $a1, $zero, 0x1
/* 47C0068 80080B38 D3ED000C */  jal        func_8003B74C
/* 47C006C 80080B3C 21202002 */   addu      $a0, $s1, $zero
/* 47C0070 80080B40 20040208 */  j          .Llevel_14_80081080
/* 47C0074 80080B44 00000000 */   nop
.L80080B48_:
/* 47C0078 80080B48 2120C003 */  addu       $a0, $fp, $zero
/* 47C007C 80080B4C 4957010C */  jal        func_80055D24
/* 47C0080 80080B50 04000524 */   addiu     $a1, $zero, 0x4
/* 47C0084 80080B54 2000C427 */  addiu      $a0, $fp, 0x20
/* 47C0088 80080B58 6000B027 */  addiu      $s0, $sp, 0x60
/* 47C008C 80080B5C 21280002 */  addu       $a1, $s0, $zero
/* 47C0090 80080B60 21300002 */  addu       $a2, $s0, $zero
/* 47C0094 80080B64 00140224 */  addiu      $v0, $zero, 0x1400
/* 47C0098 80080B68 6000A2AF */  sw         $v0, 0x60($sp)
/* 47C009C 80080B6C 6400A0AF */  sw         $zero, 0x64($sp)
/* 47C00A0 80080B70 5B3B010C */  jal        func_8004ED6C
/* 47C00A4 80080B74 6800A0AF */   sw        $zero, 0x68($sp)
/* 47C00A8 80080B78 21200002 */  addu       $a0, $s0, $zero
/* 47C00AC 80080B7C 0C00C527 */  addiu      $a1, $fp, 0xC
/* 47C00B0 80080B80 653C010C */  jal        func_8004F194
/* 47C00B4 80080B84 21300002 */   addu      $a2, $s0, $zero
/* 47C00B8 80080B88 21200002 */  addu       $a0, $s0, $zero
/* 47C00BC 80080B8C 4600C593 */  lbu        $a1, 0x46($fp)
/* 47C00C0 80080B90 0780023C */  lui        $v0, %hi(unk_ovlheader_80074330)
/* 47C00C4 80080B94 3043428C */  lw         $v0, %lo(unk_ovlheader_80074330)($v0)
/* 47C00C8 80080B98 00000000 */  nop
/* 47C00CC 80080B9C 09F84000 */  jalr       $v0
/* 47C00D0 80080BA0 21300000 */   addu      $a2, $zero, $zero
/* 47C00D4 80080BA4 36014010 */  beqz       $v0, .Llevel_14_80081080
/* 47C00D8 80080BA8 0200F026 */   addiu     $s0, $s7, 0x2
/* 47C00DC 80080BAC 21200002 */  addu       $a0, $s0, $zero
/* 47C00E0 80080BB0 01000524 */  addiu      $a1, $zero, 0x1
/* 47C00E4 80080BB4 0780063C */  lui        $a2, %hi(D_8006D088)
/* 47C00E8 80080BB8 88D0C624 */  addiu      $a2, $a2, %lo(D_8006D088)
/* 47C00EC 80080BBC EDED000C */  jal        func_8003B7B4
/* 47C00F0 80080BC0 0200E0A2 */   sb        $zero, 0x2($s7)
/* 47C00F4 80080BC4 21200002 */  addu       $a0, $s0, $zero
/* 47C00F8 80080BC8 0780063C */  lui        $a2, %hi(D_8006C7F8)
/* 47C00FC 80080BCC F8C7C624 */  addiu      $a2, $a2, %lo(D_8006C7F8)
/* 47C0100 80080BD0 EDED000C */  jal        func_8003B7B4
/* 47C0104 80080BD4 01000524 */   addiu     $a1, $zero, 0x1
/* 47C0108 80080BD8 02000224 */  addiu      $v0, $zero, 0x2
/* 47C010C 80080BDC 4800C0A3 */  sb         $zero, 0x48($fp)
/* 47C0110 80080BE0 20040208 */  j          .Llevel_14_80081080
/* 47C0114 80080BE4 0200E2A2 */   sb        $v0, 0x2($s7)
.L80080BE8_:
/* 47C0118 80080BE8 5801E48E */  lw         $a0, 0x158($s7)
/* 47C011C 80080BEC 00000000 */  nop
/* 47C0120 80080BF0 03008010 */  beqz       $a0, .Llevel_14_80080C00
/* 47C0124 80080BF4 00000000 */   nop
/* 47C0128 80080BF8 55A0000C */  jal        func_80028154
/* 47C012C 80080BFC 00000000 */   nop
.Llevel_14_80080C00:
/* 47C0130 80080C00 3400E28E */  lw         $v0, 0x34($s7)
/* 47C0134 80080C04 00000000 */  nop
/* 47C0138 80080C08 0C00508C */  lw         $s0, 0xC($v0)
/* 47C013C 80080C0C 0C00C427 */  addiu      $a0, $fp, 0xC
/* 47C0140 80080C10 5E3C010C */  jal        func_8004F178
/* 47C0144 80080C14 21280002 */   addu      $a1, $s0, $zero
/* 47C0148 80080C18 21300000 */  addu       $a2, $zero, $zero
/* 47C014C 80080C1C 3400E28E */  lw         $v0, 0x34($s7)
/* 47C0150 80080C20 0000048E */  lw         $a0, 0x0($s0)
/* 47C0154 80080C24 0C00428C */  lw         $v0, 0xC($v0)
/* 47C0158 80080C28 0400058E */  lw         $a1, 0x4($s0)
/* 47C015C 80080C2C 1000438C */  lw         $v1, 0x10($v0)
/* 47C0160 80080C30 1400428C */  lw         $v0, 0x14($v0)
/* 47C0164 80080C34 23206400 */  subu       $a0, $v1, $a0
/* 47C0168 80080C38 203A010C */  jal        func_8004E880
/* 47C016C 80080C3C 23284500 */   subu      $a1, $v0, $a1
/* 47C0170 80080C40 2120C003 */  addu       $a0, $fp, $zero
/* 47C0174 80080C44 05000524 */  addiu      $a1, $zero, 0x5
/* 47C0178 80080C48 E0D3000C */  jal        func_80034F80
/* 47C017C 80080C4C 4600C2A3 */   sb        $v0, 0x46($fp)
/* 47C0180 80080C50 3600C287 */  lh         $v0, 0x36($fp)
/* 47C0184 80080C54 00000000 */  nop
/* 47C0188 80080C58 80100200 */  sll        $v0, $v0, 2
/* 47C018C 80080C5C 0780013C */  lui        $at, %hi(D_8006EE2C)
/* 47C0190 80080C60 21082200 */  addu       $at, $at, $v0
/* 47C0194 80080C64 2CEE228C */  lw         $v0, %lo(D_8006EE2C)($at)
/* 47C0198 80080C68 00000000 */  nop
/* 47C019C 80080C6C 5000428C */  lw         $v0, 0x50($v0)
/* 47C01A0 80080C70 00000000 */  nop
/* 47C01A4 80080C74 00004590 */  lbu        $a1, 0x0($v0)
/* 47C01A8 80080C78 21200000 */  addu       $a0, $zero, $zero
/* 47C01AC 80080C7C DBD8000C */  jal        func_8003636C
/* 47C01B0 80080C80 FEFFA524 */   addiu     $a1, $a1, -0x2
/* 47C01B4 80080C84 3E00C2A3 */  sb         $v0, 0x3E($fp)
/* 47C01B8 80080C88 01004224 */  addiu      $v0, $v0, 0x1
/* 47C01BC 80080C8C 3F00C2A3 */  sb         $v0, 0x3F($fp)
/* 47C01C0 80080C90 1F040208 */  j          .Llevel_14_8008107C
/* 47C01C4 80080C94 20000224 */   addiu     $v0, $zero, 0x20
.L80080C98_:
/* 47C01C8 80080C98 2120C003 */  addu       $a0, $fp, $zero
/* 47C01CC 80080C9C 78000624 */  addiu      $a2, $zero, 0x78
/* 47C01D0 80080CA0 04000224 */  addiu      $v0, $zero, 0x4
/* 47C01D4 80080CA4 1400A2AF */  sw         $v0, 0x14($sp)
/* 47C01D8 80080CA8 20000224 */  addiu      $v0, $zero, 0x20
/* 47C01DC 80080CAC 1000A0AF */  sw         $zero, 0x10($sp)
/* 47C01E0 80080CB0 1800A2AF */  sw         $v0, 0x18($sp)
/* 47C01E4 80080CB4 1C00A0AF */  sw         $zero, 0x1C($sp)
/* 47C01E8 80080CB8 3400E58E */  lw         $a1, 0x34($s7)
/* 47C01EC 80080CBC A0D6000C */  jal        func_80035A80
/* 47C01F0 80080CC0 64000724 */   addiu     $a3, $zero, 0x64
/* 47C01F4 80080CC4 02004230 */  andi       $v0, $v0, 0x2
/* 47C01F8 80080CC8 ED004010 */  beqz       $v0, .Llevel_14_80081080
/* 47C01FC 80080CCC 03000224 */   addiu     $v0, $zero, 0x3
/* 47C0200 80080CD0 4900C393 */  lbu        $v1, 0x49($fp)
/* 47C0204 80080CD4 00000000 */  nop
/* 47C0208 80080CD8 0F006214 */  bne        $v1, $v0, .Llevel_14_80080D18
/* 47C020C 80080CDC 2120C003 */   addu      $a0, $fp, $zero
/* 47C0210 80080CE0 4ED7000C */  jal        func_80035D38
/* 47C0214 80080CE4 2120C003 */   addu      $a0, $fp, $zero
/* 47C0218 80080CE8 02004010 */  beqz       $v0, .Llevel_14_80080CF4
/* 47C021C 80080CEC 2120C003 */   addu      $a0, $fp, $zero
/* 47C0220 80080CF0 1400C2AF */  sw         $v0, 0x14($fp)
.Llevel_14_80080CF4:
/* 47C0224 80080CF4 E0D3000C */  jal        func_80034F80
/* 47C0228 80080CF8 21280000 */   addu      $a1, $zero, $zero
/* 47C022C 80080CFC 3C000224 */  addiu      $v0, $zero, 0x3C
/* 47C0230 80080D00 2800E2AE */  sw         $v0, 0x28($s7)
/* 47C0234 80080D04 4600C293 */  lbu        $v0, 0x46($fp)
/* 47C0238 80080D08 22000324 */  addiu      $v1, $zero, 0x22
/* 47C023C 80080D0C 4900C0A3 */  sb         $zero, 0x49($fp)
/* 47C0240 80080D10 85030208 */  j          .Llevel_14_80080E14
/* 47C0244 80080D14 4800C3A3 */   sb        $v1, 0x48($fp)
.Llevel_14_80080D18:
/* 47C0248 80080D18 E0D3000C */  jal        func_80034F80
/* 47C024C 80080D1C 03000524 */   addiu     $a1, $zero, 0x3
/* 47C0250 80080D20 3600C287 */  lh         $v0, 0x36($fp)
/* 47C0254 80080D24 00000000 */  nop
/* 47C0258 80080D28 80100200 */  sll        $v0, $v0, 2
/* 47C025C 80080D2C 0780013C */  lui        $at, %hi(D_8006EE2C)
/* 47C0260 80080D30 21082200 */  addu       $at, $at, $v0
/* 47C0264 80080D34 2CEE228C */  lw         $v0, %lo(D_8006EE2C)($at)
/* 47C0268 80080D38 00000000 */  nop
/* 47C026C 80080D3C 4800428C */  lw         $v0, 0x48($v0)
/* 47C0270 80080D40 00000000 */  nop
/* 47C0274 80080D44 00004590 */  lbu        $a1, 0x0($v0)
/* 47C0278 80080D48 21200000 */  addu       $a0, $zero, $zero
/* 47C027C 80080D4C DBD8000C */  jal        func_8003636C
/* 47C0280 80080D50 FEFFA524 */   addiu     $a1, $a1, -0x2
/* 47C0284 80080D54 3E00C2A3 */  sb         $v0, 0x3E($fp)
/* 47C0288 80080D58 01004224 */  addiu      $v0, $v0, 0x1
/* 47C028C 80080D5C 3F00C2A3 */  sb         $v0, 0x3F($fp)
/* 47C0290 80080D60 21000224 */  addiu      $v0, $zero, 0x21
/* 47C0294 80080D64 4800C2A3 */  sb         $v0, 0x48($fp)
/* 47C0298 80080D68 3400E38E */  lw         $v1, 0x34($s7)
/* 47C029C 80080D6C FFFF0224 */  addiu      $v0, $zero, -0x1
/* 47C02A0 80080D70 0A0062A4 */  sh         $v0, 0xA($v1)
/* 47C02A4 80080D74 3400E38E */  lw         $v1, 0x34($s7)
/* 47C02A8 80080D78 00000000 */  nop
/* 47C02AC 80080D7C 00006294 */  lhu        $v0, 0x0($v1)
/* 47C02B0 80080D80 00000000 */  nop
/* 47C02B4 80080D84 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 47C02B8 80080D88 20040208 */  j          .Llevel_14_80081080
/* 47C02BC 80080D8C 020062A4 */   sh        $v0, 0x2($v1)
.L80080D90_:
/* 47C02C0 80080D90 2120C003 */  addu       $a0, $fp, $zero
/* 47C02C4 80080D94 78000624 */  addiu      $a2, $zero, 0x78
/* 47C02C8 80080D98 04000224 */  addiu      $v0, $zero, 0x4
/* 47C02CC 80080D9C 1400A2AF */  sw         $v0, 0x14($sp)
/* 47C02D0 80080DA0 20000224 */  addiu      $v0, $zero, 0x20
/* 47C02D4 80080DA4 1000A0AF */  sw         $zero, 0x10($sp)
/* 47C02D8 80080DA8 1800A2AF */  sw         $v0, 0x18($sp)
/* 47C02DC 80080DAC 1C00A0AF */  sw         $zero, 0x1C($sp)
/* 47C02E0 80080DB0 3400E58E */  lw         $a1, 0x34($s7)
/* 47C02E4 80080DB4 A0D6000C */  jal        func_80035A80
/* 47C02E8 80080DB8 64000724 */   addiu     $a3, $zero, 0x64
/* 47C02EC 80080DBC 02004230 */  andi       $v0, $v0, 0x2
/* 47C02F0 80080DC0 AF004010 */  beqz       $v0, .Llevel_14_80081080
/* 47C02F4 80080DC4 4800D027 */   addiu     $s0, $fp, 0x48
/* 47C02F8 80080DC8 21200002 */  addu       $a0, $s0, $zero
/* 47C02FC 80080DCC 01000524 */  addiu      $a1, $zero, 0x1
/* 47C0300 80080DD0 0780063C */  lui        $a2, %hi(D_8006D088)
/* 47C0304 80080DD4 88D0C624 */  addiu      $a2, $a2, %lo(D_8006D088)
/* 47C0308 80080DD8 2F000224 */  addiu      $v0, $zero, 0x2F
/* 47C030C 80080DDC EDED000C */  jal        func_8003B7B4
/* 47C0310 80080DE0 4800C2A3 */   sb        $v0, 0x48($fp)
/* 47C0314 80080DE4 21200002 */  addu       $a0, $s0, $zero
/* 47C0318 80080DE8 0780063C */  lui        $a2, %hi(D_8006C7F8)
/* 47C031C 80080DEC F8C7C624 */  addiu      $a2, $a2, %lo(D_8006C7F8)
/* 47C0320 80080DF0 EDED000C */  jal        func_8003B7B4
/* 47C0324 80080DF4 01000524 */   addiu     $a1, $zero, 0x1
/* 47C0328 80080DF8 2120C003 */  addu       $a0, $fp, $zero
/* 47C032C 80080DFC 21280000 */  addu       $a1, $zero, $zero
/* 47C0330 80080E00 25000224 */  addiu      $v0, $zero, 0x25
/* 47C0334 80080E04 0500E0A2 */  sb         $zero, 0x5($s7)
/* 47C0338 80080E08 E0D3000C */  jal        func_80034F80
/* 47C033C 80080E0C 4800C2A3 */   sb        $v0, 0x48($fp)
/* 47C0340 80080E10 4600C293 */  lbu        $v0, 0x46($fp)
.Llevel_14_80080E14:
/* 47C0344 80080E14 00000000 */  nop
/* 47C0348 80080E18 80004224 */  addiu      $v0, $v0, 0x80
/* 47C034C 80080E1C 20040208 */  j          .Llevel_14_80081080
/* 47C0350 80080E20 4600C2A3 */   sb        $v0, 0x46($fp)
.L80080E24_:
/* 47C0354 80080E24 0010043C */  lui        $a0, (0x10002000 >> 16)
/* 47C0358 80080E28 0780033C */  lui        $v1, %hi(D_80070328 + 0x20C)
/* 47C035C 80080E2C 34056324 */  addiu      $v1, $v1, %lo(D_80070328 + 0x20C)
/* 47C0360 80080E30 0000628C */  lw         $v0, 0x0($v1)
/* 47C0364 80080E34 00208434 */  ori        $a0, $a0, (0x10002000 & 0xFFFF)
/* 47C0368 80080E38 25104400 */  or         $v0, $v0, $a0
/* 47C036C 80080E3C 000062AC */  sw         $v0, 0x0($v1)
/* 47C0370 80080E40 4900C393 */  lbu        $v1, 0x49($fp)
/* 47C0374 80080E44 04000224 */  addiu      $v0, $zero, 0x4
/* 47C0378 80080E48 08006210 */  beq        $v1, $v0, .Llevel_14_80080E6C
/* 47C037C 80080E4C 00000000 */   nop
/* 47C0380 80080E50 CF87000C */  jal        func_80021F3C
/* 47C0384 80080E54 06000424 */   addiu     $a0, $zero, 0x6
/* 47C0388 80080E58 0F004230 */  andi       $v0, $v0, 0xF
/* 47C038C 80080E5C 88004014 */  bnez       $v0, .Llevel_14_80081080
/* 47C0390 80080E60 04000224 */   addiu     $v0, $zero, 0x4
/* 47C0394 80080E64 20040208 */  j          .Llevel_14_80081080
/* 47C0398 80080E68 4900C2A3 */   sb        $v0, 0x49($fp)
.Llevel_14_80080E6C:
/* 47C039C 80080E6C CF87000C */  jal        func_80021F3C
/* 47C03A0 80080E70 06000424 */   addiu     $a0, $zero, 0x6
/* 47C03A4 80080E74 0F004230 */  andi       $v0, $v0, 0xF
/* 47C03A8 80080E78 81004010 */  beqz       $v0, .Llevel_14_80081080
/* 47C03AC 80080E7C 2800E426 */   addiu     $a0, $s7, 0x28
/* 47C03B0 80080E80 69D6000C */  jal        func_800359A4
/* 47C03B4 80080E84 04000524 */   addiu     $a1, $zero, 0x4
/* 47C03B8 80080E88 7D004010 */  beqz       $v0, .Llevel_14_80081080
/* 47C03BC 80080E8C 06000224 */   addiu     $v0, $zero, 0x6
/* 47C03C0 80080E90 0000C38F */  lw         $v1, 0x0($fp)
/* 47C03C4 80080E94 4900C2A3 */  sb         $v0, 0x49($fp)
/* 47C03C8 80080E98 23000224 */  addiu      $v0, $zero, 0x23
/* 47C03CC 80080E9C 4800C2A3 */  sb         $v0, 0x48($fp)
/* 47C03D0 80080EA0 02000224 */  addiu      $v0, $zero, 0x2
/* 47C03D4 80080EA4 050062A0 */  sb         $v0, 0x5($v1)
/* 47C03D8 80080EA8 4600C293 */  lbu        $v0, 0x46($fp)
/* 47C03DC 80080EAC 7000B027 */  addiu      $s0, $sp, 0x70
/* 47C03E0 80080EB0 40100200 */  sll        $v0, $v0, 1
/* 47C03E4 80080EB4 0680013C */  lui        $at, %hi(D_80065920)
/* 47C03E8 80080EB8 21082200 */  addu       $at, $at, $v0
/* 47C03EC 80080EBC 20592384 */  lh         $v1, %lo(D_80065920)($at)
/* 47C03F0 80080EC0 21200002 */  addu       $a0, $s0, $zero
/* 47C03F4 80080EC4 80100300 */  sll        $v0, $v1, 2
/* 47C03F8 80080EC8 21104300 */  addu       $v0, $v0, $v1
/* 47C03FC 80080ECC C0100200 */  sll        $v0, $v0, 3
/* 47C0400 80080ED0 23104300 */  subu       $v0, $v0, $v1
/* 47C0404 80080ED4 83110200 */  sra        $v0, $v0, 6
/* 47C0408 80080ED8 7000A2AF */  sw         $v0, 0x70($sp)
/* 47C040C 80080EDC 4600C293 */  lbu        $v0, 0x46($fp)
/* 47C0410 80080EE0 21280002 */  addu       $a1, $s0, $zero
/* 47C0414 80080EE4 40100200 */  sll        $v0, $v0, 1
/* 47C0418 80080EE8 0680013C */  lui        $at, %hi(D_800658A0)
/* 47C041C 80080EEC 21082200 */  addu       $at, $at, $v0
/* 47C0420 80080EF0 A0582384 */  lh         $v1, %lo(D_800658A0)($at)
/* 47C0424 80080EF4 0780023C */  lui        $v0, %hi(D_80070328 + 0x44)
/* 47C0428 80080EF8 6C03428C */  lw         $v0, %lo(D_80070328 + 0x44)($v0)
/* 47C042C 80080EFC 0C00C627 */  addiu      $a2, $fp, 0xC
/* 47C0430 80080F00 7800A0AF */  sw         $zero, 0x78($sp)
/* 47C0434 80080F04 7800A2AF */  sw         $v0, 0x78($sp)
/* 47C0438 80080F08 80100300 */  sll        $v0, $v1, 2
/* 47C043C 80080F0C 21104300 */  addu       $v0, $v0, $v1
/* 47C0440 80080F10 C0100200 */  sll        $v0, $v0, 3
/* 47C0444 80080F14 23104300 */  subu       $v0, $v0, $v1
/* 47C0448 80080F18 83110200 */  sra        $v0, $v0, 6
/* 47C044C 80080F1C 653C010C */  jal        func_8004F194
/* 47C0450 80080F20 7400A2AF */   sw        $v0, 0x74($sp)
/* 47C0454 80080F24 21200002 */  addu       $a0, $s0, $zero
/* 47C0458 80080F28 21300000 */  addu       $a2, $zero, $zero
/* 47C045C 80080F2C 4600C593 */  lbu        $a1, 0x46($fp)
/* 47C0460 80080F30 21380000 */  addu       $a3, $zero, $zero
/* 47C0464 80080F34 8000A524 */  addiu      $a1, $a1, 0x80
/* 47C0468 80080F38 514F000C */  jal        func_80013D44
/* 47C046C 80080F3C FF00A530 */   andi      $a1, $a1, 0xFF
/* 47C0470 80080F40 0780023C */  lui        $v0, %hi(D_80070328 + 0x280)
/* 47C0474 80080F44 A805428C */  lw         $v0, %lo(D_80070328 + 0x280)($v0)
/* 47C0478 80080F48 00000000 */  nop
/* 47C047C 80080F4C 4C004104 */  bgez       $v0, .Llevel_14_80081080
/* 47C0480 80080F50 00000000 */   nop
/* 47C0484 80080F54 0780013C */  lui        $at, %hi(D_80070328 + 0x280)
/* 47C0488 80080F58 A80520AC */  sw         $zero, %lo(D_80070328 + 0x280)($at)
/* 47C048C 80080F5C 20040208 */  j          .Llevel_14_80081080
/* 47C0490 80080F60 00000000 */   nop
.L80080F64_:
/* 47C0494 80080F64 2120C003 */  addu       $a0, $fp, $zero
/* 47C0498 80080F68 EFDE000C */  jal        func_80037BBC
/* 47C049C 80080F6C 21280000 */   addu      $a1, $zero, $zero
/* 47C04A0 80080F70 43004010 */  beqz       $v0, .Llevel_14_80081080
/* 47C04A4 80080F74 2120C003 */   addu      $a0, $fp, $zero
/* 47C04A8 80080F78 21280000 */  addu       $a1, $zero, $zero
/* 47C04AC 80080F7C B944010C */  jal        func_800512E4
/* 47C04B0 80080F80 01000624 */   addiu     $a2, $zero, 0x1
/* 47C04B4 80080F84 1F040208 */  j          .Llevel_14_8008107C
/* 47C04B8 80080F88 24000224 */   addiu     $v0, $zero, 0x24
.L80080F8C_:
/* 47C04BC 80080F8C 4900C393 */  lbu        $v1, 0x49($fp)
/* 47C04C0 80080F90 06000224 */  addiu      $v0, $zero, 0x6
/* 47C04C4 80080F94 15006214 */  bne        $v1, $v0, .Llevel_14_80080FEC
/* 47C04C8 80080F98 2120C003 */   addu      $a0, $fp, $zero
/* 47C04CC 80080F9C 0010043C */  lui        $a0, (0x10002000 >> 16)
/* 47C04D0 80080FA0 0780033C */  lui        $v1, %hi(D_80070328 + 0x20C)
/* 47C04D4 80080FA4 34056324 */  addiu      $v1, $v1, %lo(D_80070328 + 0x20C)
/* 47C04D8 80080FA8 0000628C */  lw         $v0, 0x0($v1)
/* 47C04DC 80080FAC 00208434 */  ori        $a0, $a0, (0x10002000 & 0xFFFF)
/* 47C04E0 80080FB0 25104400 */  or         $v0, $v0, $a0
/* 47C04E4 80080FB4 000062AC */  sw         $v0, 0x0($v1)
/* 47C04E8 80080FB8 0780033C */  lui        $v1, %hi(D_8006E048)
/* 47C04EC 80080FBC 48E0638C */  lw         $v1, %lo(D_8006E048)($v1)
/* 47C04F0 80080FC0 01000224 */  addiu      $v0, $zero, 0x1
/* 47C04F4 80080FC4 08006214 */  bne        $v1, $v0, .Llevel_14_80080FE8
/* 47C04F8 80080FC8 07000224 */   addiu     $v0, $zero, 0x7
/* 47C04FC 80080FCC 4900C2A3 */  sb         $v0, 0x49($fp)
/* 47C0500 80080FD0 0780033C */  lui        $v1, %hi(D_8006C65C)
/* 47C0504 80080FD4 5CC6638C */  lw         $v1, %lo(D_8006C65C)($v1)
/* 47C0508 80080FD8 00000000 */  nop
/* 47C050C 80080FDC 02006010 */  beqz       $v1, .Llevel_14_80080FE8
/* 47C0510 80080FE0 10000224 */   addiu     $v0, $zero, 0x10
/* 47C0514 80080FE4 4C0062A0 */  sb         $v0, 0x4C($v1)
.Llevel_14_80080FE8:
/* 47C0518 80080FE8 2120C003 */  addu       $a0, $fp, $zero
.Llevel_14_80080FEC:
/* 47C051C 80080FEC EFDE000C */  jal        func_80037BBC
/* 47C0520 80080FF0 21280000 */   addu      $a1, $zero, $zero
/* 47C0524 80080FF4 22004010 */  beqz       $v0, .Llevel_14_80081080
/* 47C0528 80080FF8 2120C003 */   addu      $a0, $fp, $zero
/* 47C052C 80080FFC 21280000 */  addu       $a1, $zero, $zero
/* 47C0530 80081000 0780023C */  lui        $v0, %hi(D_8006C7B4)
/* 47C0534 80081004 B4C74290 */  lbu        $v0, %lo(D_8006C7B4)($v0)
/* 47C0538 80081008 01000624 */  addiu      $a2, $zero, 0x1
/* 47C053C 8008100C 04004234 */  ori        $v0, $v0, 0x4
/* 47C0540 80081010 0780013C */  lui        $at, %hi(D_8006C7B4)
/* 47C0544 80081014 B4C722A0 */  sb         $v0, %lo(D_8006C7B4)($at)
/* 47C0548 80081018 B944010C */  jal        func_800512E4
/* 47C054C 8008101C 4900C0A3 */   sb        $zero, 0x49($fp)
/* 47C0550 80081020 1F040208 */  j          .Llevel_14_8008107C
/* 47C0554 80081024 24000224 */   addiu     $v0, $zero, 0x24
.L80081028_:
/* 47C0558 80081028 0780033C */  lui        $v1, %hi(D_8006E344)
/* 47C055C 8008102C 44E3638C */  lw         $v1, %lo(D_8006E344)($v1)
/* 47C0560 80081030 01000224 */  addiu      $v0, $zero, 0x1
/* 47C0564 80081034 12006210 */  beq        $v1, $v0, .Llevel_14_80081080
/* 47C0568 80081038 4800D027 */   addiu     $s0, $fp, 0x48
/* 47C056C 8008103C 21200002 */  addu       $a0, $s0, $zero
/* 47C0570 80081040 01000524 */  addiu      $a1, $zero, 0x1
/* 47C0574 80081044 0780063C */  lui        $a2, %hi(D_8006D088)
/* 47C0578 80081048 88D0C624 */  addiu      $a2, $a2, %lo(D_8006D088)
/* 47C057C 8008104C 2E000224 */  addiu      $v0, $zero, 0x2E
/* 47C0580 80081050 EDED000C */  jal        func_8003B7B4
/* 47C0584 80081054 4800C2A3 */   sb        $v0, 0x48($fp)
/* 47C0588 80081058 21200002 */  addu       $a0, $s0, $zero
/* 47C058C 8008105C 0780063C */  lui        $a2, %hi(D_8006C7F8)
/* 47C0590 80081060 F8C7C624 */  addiu      $a2, $a2, %lo(D_8006C7F8)
/* 47C0594 80081064 EDED000C */  jal        func_8003B7B4
/* 47C0598 80081068 01000524 */   addiu     $a1, $zero, 0x1
/* 47C059C 8008106C 2120C003 */  addu       $a0, $fp, $zero
/* 47C05A0 80081070 D0D3000C */  jal        func_80034F40
/* 47C05A4 80081074 21280000 */   addu      $a1, $zero, $zero
.Llevel_14_80081078:
/* 47C05A8 80081078 1E000224 */  addiu      $v0, $zero, 0x1E
.Llevel_14_8008107C:
/* 47C05AC 8008107C 4800C2A3 */  sb         $v0, 0x48($fp)
.Llevel_14_80081080:
/* 47C05B0 80081080 B400BF8F */  lw         $ra, 0xB4($sp)
/* 47C05B4 80081084 B000BE8F */  lw         $fp, 0xB0($sp)
/* 47C05B8 80081088 AC00B78F */  lw         $s7, 0xAC($sp)
/* 47C05BC 8008108C A800B68F */  lw         $s6, 0xA8($sp)
/* 47C05C0 80081090 A400B58F */  lw         $s5, 0xA4($sp)
/* 47C05C4 80081094 A000B48F */  lw         $s4, 0xA0($sp)
/* 47C05C8 80081098 9C00B38F */  lw         $s3, 0x9C($sp)
/* 47C05CC 8008109C 9800B28F */  lw         $s2, 0x98($sp)
/* 47C05D0 800810A0 9400B18F */  lw         $s1, 0x94($sp)
/* 47C05D4 800810A4 9000B08F */  lw         $s0, 0x90($sp)
/* 47C05D8 800810A8 B800BD27 */  addiu      $sp, $sp, 0xB8
/* 47C05DC 800810AC 0800E003 */  jr         $ra
/* 47C05E0 800810B0 00000000 */   nop
.size func_level_14_800801D4, . - func_level_14_800801D4
