.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_37_80074C54
/* 7AA0984 80074C54 D0A20880 */ .word .L8008A2D0_
/* 7AA0988 80074C58 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA098C 80074C5C F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA0990 80074C60 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA0994 80074C64 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA0998 80074C68 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA099C 80074C6C F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA09A0 80074C70 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA09A4 80074C74 E4A30880 */ .word .L8008A3E4_
/* 7AA09A8 80074C78 18A30880 */ .word .L8008A318_
/* 7AA09AC 80074C7C C0A40880 */ .word .L8008A4C0_
/* 7AA09B0 80074C80 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA09B4 80074C84 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA09B8 80074C88 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA09BC 80074C8C F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA09C0 80074C90 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA09C4 80074C94 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA09C8 80074C98 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA09CC 80074C9C F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA09D0 80074CA0 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA09D4 80074CA4 D8A50880 */ .word .L8008A5D8_
/* 7AA09D8 80074CA8 D8A50880 */ .word .L8008A5D8_
/* 7AA09DC 80074CAC B4A70880 */ .word .L8008A7B4_
/* 7AA09E0 80074CB0 90A90880 */ .word .L8008A990_
/* 7AA09E4 80074CB4 90A90880 */ .word .L8008A990_
/* 7AA09E8 80074CB8 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA09EC 80074CBC F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA09F0 80074CC0 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA09F4 80074CC4 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA09F8 80074CC8 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA09FC 80074CCC F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA0A00 80074CD0 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA0A04 80074CD4 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA0A08 80074CD8 C0AA0880 */ .word .L8008AAC0_
/* 7AA0A0C 80074CDC C0AA0880 */ .word .L8008AAC0_
/* 7AA0A10 80074CE0 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA0A14 80074CE4 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA0A18 80074CE8 F4AA0880 */ .word .Llevel_37_8008AAF4
/* 7AA0A1C 80074CEC 70A50880 */ .word .L8008A570_
/* 7AA0A20 80074CF0 00000000 */ .word 0x00000000
.size jtbl_level_37_80074C54, . - jtbl_level_37_80074C54


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_37_8008A294
/* 7AB5FC4 8008A294 B0FFBD27 */  addiu      $sp, $sp, -0x50
/* 7AB5FC8 8008A298 4400B1AF */  sw         $s1, 0x44($sp)
/* 7AB5FCC 8008A29C 21888000 */  addu       $s1, $a0, $zero
/* 7AB5FD0 8008A2A0 ECFF2326 */  addiu      $v1, $s1, -0x14
/* 7AB5FD4 8008A2A4 2700622C */  sltiu      $v0, $v1, 0x27
/* 7AB5FD8 8008A2A8 4800BFAF */  sw         $ra, 0x48($sp)
/* 7AB5FDC 8008A2AC 11024010 */  beqz       $v0, .Llevel_37_8008AAF4
/* 7AB5FE0 8008A2B0 4000B0AF */   sw        $s0, 0x40($sp)
/* 7AB5FE4 8008A2B4 80100300 */  sll        $v0, $v1, 2
/* 7AB5FE8 8008A2B8 0780013C */  lui        $at, %hi(jtbl_level_37_80074C54)
/* 7AB5FEC 8008A2BC 21082200 */  addu       $at, $at, $v0
/* 7AB5FF0 8008A2C0 544C228C */  lw         $v0, %lo(jtbl_level_37_80074C54)($at)
/* 7AB5FF4 8008A2C4 00000000 */  nop
/* 7AB5FF8 8008A2C8 08004000 */  jr         $v0
/* 7AB5FFC 8008A2CC 00000000 */   nop
.L8008A2D0_:
/* 7AB6000 8008A2D0 0780013C */  lui        $at, %hi(D_80070328 + 0x50)
/* 7AB6004 8008A2D4 780320AC */  sw         $zero, %lo(D_80070328 + 0x50)($at)
/* 7AB6008 8008A2D8 0780013C */  lui        $at, %hi(D_80070328 + 0x4C)
/* 7AB600C 8008A2DC 740320AC */  sw         $zero, %lo(D_80070328 + 0x4C)($at)
/* 7AB6010 8008A2E0 7C10010C */  jal        func_800441F0
/* 7AB6014 8008A2E4 00000000 */   nop
/* 7AB6018 8008A2E8 01000424 */  addiu      $a0, $zero, 0x1
/* 7AB601C 8008A2EC 01000224 */  addiu      $v0, $zero, 0x1
/* 7AB6020 8008A2F0 0780013C */  lui        $at, %hi(D_80070328 + 0x1B4)
/* 7AB6024 8008A2F4 DC0422A0 */  sb         $v0, %lo(D_80070328 + 0x1B4)($at)
/* 7AB6028 8008A2F8 DBD8000C */  jal        func_8003636C
/* 7AB602C 8008A2FC 03000524 */   addiu     $a1, $zero, 0x3
/* 7AB6030 8008A300 0780013C */  lui        $at, %hi(D_80070328 + 0x144)
/* 7AB6034 8008A304 6C0422AC */  sw         $v0, %lo(D_80070328 + 0x144)($at)
/* 7AB6038 8008A308 0780013C */  lui        $at, %hi(D_80070328 + 0x148)
/* 7AB603C 8008A30C 700420AC */  sw         $zero, %lo(D_80070328 + 0x148)($at)
/* 7AB6040 8008A310 B92A0208 */  j          .Llevel_37_8008AAE4
/* 7AB6044 8008A314 00000000 */   nop
.L8008A318_:
/* 7AB6048 8008A318 0780043C */  lui        $a0, %hi(D_80070328 + 0x50)
/* 7AB604C 8008A31C 7803848C */  lw         $a0, %lo(D_80070328 + 0x50)($a0)
/* 7AB6050 8008A320 0780033C */  lui        $v1, %hi(D_80070328 + 0x21C)
/* 7AB6054 8008A324 4405638C */  lw         $v1, %lo(D_80070328 + 0x21C)($v1)
/* 7AB6058 8008A328 07000224 */  addiu      $v0, $zero, 0x7
/* 7AB605C 8008A32C 0780013C */  lui        $at, %hi(D_80070328 + 0x50)
/* 7AB6060 8008A330 780322AC */  sw         $v0, %lo(D_80070328 + 0x50)($at)
/* 7AB6064 8008A334 0780023C */  lui        $v0, %hi(D_80070328 + 0x220)
/* 7AB6068 8008A338 4805428C */  lw         $v0, %lo(D_80070328 + 0x220)($v0)
/* 7AB606C 8008A33C 0780013C */  lui        $at, %hi(D_80070328 + 0x4C)
/* 7AB6070 8008A340 740320AC */  sw         $zero, %lo(D_80070328 + 0x4C)($at)
/* 7AB6074 8008A344 80190300 */  sll        $v1, $v1, 6
/* 7AB6078 8008A348 0780013C */  lui        $at, %hi(D_80070328 + 0x8C)
/* 7AB607C 8008A34C B40323AC */  sw         $v1, %lo(D_80070328 + 0x8C)($at)
/* 7AB6080 8008A350 0780033C */  lui        $v1, %hi(D_80070328 + 0x224)
/* 7AB6084 8008A354 4C05638C */  lw         $v1, %lo(D_80070328 + 0x224)($v1)
/* 7AB6088 8008A358 80110200 */  sll        $v0, $v0, 6
/* 7AB608C 8008A35C 0780013C */  lui        $at, %hi(D_80070328 + 0x144)
/* 7AB6090 8008A360 6C0424AC */  sw         $a0, %lo(D_80070328 + 0x144)($at)
/* 7AB6094 8008A364 0780013C */  lui        $at, %hi(D_80070328 + 0x90)
/* 7AB6098 8008A368 B80322AC */  sw         $v0, %lo(D_80070328 + 0x90)($at)
/* 7AB609C 8008A36C 03006014 */  bnez       $v1, .Llevel_37_8008A37C
/* 7AB60A0 8008A370 80110300 */   sll       $v0, $v1, 6
/* 7AB60A4 8008A374 0780023C */  lui        $v0, %hi(D_80070328 + 0xA0)
/* 7AB60A8 8008A378 C803428C */  lw         $v0, %lo(D_80070328 + 0xA0)($v0)
.Llevel_37_8008A37C:
/* 7AB60AC 8008A37C 0780013C */  lui        $at, %hi(D_80070328 + 0x94)
/* 7AB60B0 8008A380 BC0322AC */  sw         $v0, %lo(D_80070328 + 0x94)($at)
/* 7AB60B4 8008A384 8E0E010C */  jal        func_80043A38
/* 7AB60B8 8008A388 000C0424 */   addiu     $a0, $zero, 0xC00
/* 7AB60BC 8008A38C 0780033C */  lui        $v1, %hi(SpawnParticle)
/* 7AB60C0 8008A390 E442638C */  lw         $v1, %lo(SpawnParticle)($v1)
/* 7AB60C4 8008A394 01000224 */  addiu      $v0, $zero, 0x1
/* 7AB60C8 8008A398 0780013C */  lui        $at, %hi(D_80070328 + 0x1B4)
/* 7AB60CC 8008A39C DC0422A0 */  sb         $v0, %lo(D_80070328 + 0x1B4)($at)
/* 7AB60D0 8008A3A0 0F000224 */  addiu      $v0, $zero, 0xF
/* 7AB60D4 8008A3A4 0780013C */  lui        $at, %hi(D_8006E524)
/* 7AB60D8 8008A3A8 24E522AC */  sw         $v0, %lo(D_8006E524)($at)
/* 7AB60DC 8008A3AC 05006010 */  beqz       $v1, .Llevel_37_8008A3C4
/* 7AB60E0 8008A3B0 05000424 */   addiu     $a0, $zero, 0x5
/* 7AB60E4 8008A3B4 0A000524 */  addiu      $a1, $zero, 0xA
/* 7AB60E8 8008A3B8 21300000 */  addu       $a2, $zero, $zero
/* 7AB60EC 8008A3BC 09F86000 */  jalr       $v1
/* 7AB60F0 8008A3C0 21380000 */   addu      $a3, $zero, $zero
.Llevel_37_8008A3C4:
/* 7AB60F4 8008A3C4 0780023C */  lui        $v0, %hi(D_8006C654)
/* 7AB60F8 8008A3C8 54C6428C */  lw         $v0, %lo(D_8006C654)($v0)
/* 7AB60FC 8008A3CC 21280000 */  addu       $a1, $zero, $zero
/* 7AB6100 8008A3D0 15004490 */  lbu        $a0, 0x15($v0)
/* 7AB6104 8008A3D4 D4EE000C */  jal        func_8003BB50
/* 7AB6108 8008A3D8 21300000 */   addu      $a2, $zero, $zero
/* 7AB610C 8008A3DC B92A0208 */  j          .Llevel_37_8008AAE4
/* 7AB6110 8008A3E0 00000000 */   nop
.L8008A3E4_:
/* 7AB6114 8008A3E4 0780033C */  lui        $v1, %hi(D_80070328 + 0x144)
/* 7AB6118 8008A3E8 6C046324 */  addiu      $v1, $v1, %lo(D_80070328 + 0x144)
/* 7AB611C 8008A3EC 48FF6424 */  addiu      $a0, $v1, -0xB8
/* 7AB6120 8008A3F0 54FF7024 */  addiu      $s0, $v1, -0xAC
/* 7AB6124 8008A3F4 21280002 */  addu       $a1, $s0, $zero
/* 7AB6128 8008A3F8 0780063C */  lui        $a2, %hi(D_80070328 + 0x50)
/* 7AB612C 8008A3FC 7803C68C */  lw         $a2, %lo(D_80070328 + 0x50)($a2)
/* 7AB6130 8008A400 07000224 */  addiu      $v0, $zero, 0x7
/* 7AB6134 8008A404 0780013C */  lui        $at, %hi(D_80070328 + 0x50)
/* 7AB6138 8008A408 780322AC */  sw         $v0, %lo(D_80070328 + 0x50)($at)
/* 7AB613C 8008A40C 0780013C */  lui        $at, %hi(D_80070328 + 0x4C)
/* 7AB6140 8008A410 740320AC */  sw         $zero, %lo(D_80070328 + 0x4C)($at)
/* 7AB6144 8008A414 5E3C010C */  jal        func_8004F178
/* 7AB6148 8008A418 000066AC */   sw        $a2, 0x0($v1)
/* 7AB614C 8008A41C 21200002 */  addu       $a0, $s0, $zero
/* 7AB6150 8008A420 7A3B010C */  jal        func_8004EDE8
/* 7AB6154 8008A424 21280000 */   addu      $a1, $zero, $zero
/* 7AB6158 8008A428 0780033C */  lui        $v1, %hi(SpawnParticle)
/* 7AB615C 8008A42C E442638C */  lw         $v1, %lo(SpawnParticle)($v1)
/* 7AB6160 8008A430 0780013C */  lui        $at, %hi(D_80070328 + 0xB0)
/* 7AB6164 8008A434 D80322AC */  sw         $v0, %lo(D_80070328 + 0xB0)($at)
/* 7AB6168 8008A438 C00D0224 */  addiu      $v0, $zero, 0xDC0
/* 7AB616C 8008A43C 0780013C */  lui        $at, %hi(D_80070328 + 0x94)
/* 7AB6170 8008A440 BC0322AC */  sw         $v0, %lo(D_80070328 + 0x94)($at)
/* 7AB6174 8008A444 0F000224 */  addiu      $v0, $zero, 0xF
/* 7AB6178 8008A448 0780013C */  lui        $at, %hi(D_80070328 + 0x1B4)
/* 7AB617C 8008A44C DC0420A0 */  sb         $zero, %lo(D_80070328 + 0x1B4)($at)
/* 7AB6180 8008A450 0780013C */  lui        $at, %hi(D_8006E524)
/* 7AB6184 8008A454 24E522AC */  sw         $v0, %lo(D_8006E524)($at)
/* 7AB6188 8008A458 05006010 */  beqz       $v1, .Llevel_37_8008A470
/* 7AB618C 8008A45C 05000424 */   addiu     $a0, $zero, 0x5
/* 7AB6190 8008A460 0A000524 */  addiu      $a1, $zero, 0xA
/* 7AB6194 8008A464 21300000 */  addu       $a2, $zero, $zero
/* 7AB6198 8008A468 09F86000 */  jalr       $v1
/* 7AB619C 8008A46C 21380000 */   addu      $a3, $zero, $zero
.Llevel_37_8008A470:
/* 7AB61A0 8008A470 0780023C */  lui        $v0, %hi(D_80070328 + 0x24)
/* 7AB61A4 8008A474 4C03428C */  lw         $v0, %lo(D_80070328 + 0x24)($v0)
/* 7AB61A8 8008A478 00000000 */  nop
/* 7AB61AC 8008A47C 00024230 */  andi       $v0, $v0, 0x200
/* 7AB61B0 8008A480 05004010 */  beqz       $v0, .Llevel_37_8008A498
/* 7AB61B4 8008A484 21280000 */   addu      $a1, $zero, $zero
/* 7AB61B8 8008A488 0780013C */  lui        $at, %hi(D_80070328 + 0x148)
/* 7AB61BC 8008A48C 700420AC */  sw         $zero, %lo(D_80070328 + 0x148)($at)
/* 7AB61C0 8008A490 B92A0208 */  j          .Llevel_37_8008AAE4
/* 7AB61C4 8008A494 00000000 */   nop
.Llevel_37_8008A498:
/* 7AB61C8 8008A498 0780033C */  lui        $v1, %hi(D_8006C654)
/* 7AB61CC 8008A49C 54C6638C */  lw         $v1, %lo(D_8006C654)($v1)
/* 7AB61D0 8008A4A0 01000224 */  addiu      $v0, $zero, 0x1
/* 7AB61D4 8008A4A4 0780013C */  lui        $at, %hi(D_80070328 + 0x148)
/* 7AB61D8 8008A4A8 700422AC */  sw         $v0, %lo(D_80070328 + 0x148)($at)
/* 7AB61DC 8008A4AC 0C006490 */  lbu        $a0, 0xC($v1)
/* 7AB61E0 8008A4B0 D4EE000C */  jal        func_8003BB50
/* 7AB61E4 8008A4B4 21300000 */   addu      $a2, $zero, $zero
/* 7AB61E8 8008A4B8 B92A0208 */  j          .Llevel_37_8008AAE4
/* 7AB61EC 8008A4BC 00000000 */   nop
.L8008A4C0_:
/* 7AB61F0 8008A4C0 0780033C */  lui        $v1, %hi(D_80070328 + 0x50)
/* 7AB61F4 8008A4C4 7803638C */  lw         $v1, %lo(D_80070328 + 0x50)($v1)
/* 7AB61F8 8008A4C8 0780083C */  lui        $t0, %hi(SpawnParticle)
/* 7AB61FC 8008A4CC E442088D */  lw         $t0, %lo(SpawnParticle)($t0)
/* 7AB6200 8008A4D0 07000224 */  addiu      $v0, $zero, 0x7
/* 7AB6204 8008A4D4 0780013C */  lui        $at, %hi(D_80070328 + 0x50)
/* 7AB6208 8008A4D8 780322AC */  sw         $v0, %lo(D_80070328 + 0x50)($at)
/* 7AB620C 8008A4DC 01000224 */  addiu      $v0, $zero, 0x1
/* 7AB6210 8008A4E0 0780013C */  lui        $at, %hi(D_80070328 + 0x1B4)
/* 7AB6214 8008A4E4 DC0422A0 */  sb         $v0, %lo(D_80070328 + 0x1B4)($at)
/* 7AB6218 8008A4E8 0F000224 */  addiu      $v0, $zero, 0xF
/* 7AB621C 8008A4EC 0780013C */  lui        $at, %hi(D_8006E524)
/* 7AB6220 8008A4F0 24E522AC */  sw         $v0, %lo(D_8006E524)($at)
/* 7AB6224 8008A4F4 0780023C */  lui        $v0, %hi(D_80070328 + 0x144)
/* 7AB6228 8008A4F8 6C044224 */  addiu      $v0, $v0, %lo(D_80070328 + 0x144)
/* 7AB622C 8008A4FC 0780013C */  lui        $at, %hi(D_80070328 + 0x4C)
/* 7AB6230 8008A500 740320AC */  sw         $zero, %lo(D_80070328 + 0x4C)($at)
/* 7AB6234 8008A504 000043AC */  sw         $v1, 0x0($v0)
/* 7AB6238 8008A508 06000011 */  beqz       $t0, .Llevel_37_8008A524
/* 7AB623C 8008A50C 000040AC */   sw        $zero, 0x0($v0)
/* 7AB6240 8008A510 05000424 */  addiu      $a0, $zero, 0x5
/* 7AB6244 8008A514 0A000524 */  addiu      $a1, $zero, 0xA
/* 7AB6248 8008A518 21300000 */  addu       $a2, $zero, $zero
/* 7AB624C 8008A51C 09F80001 */  jalr       $t0
/* 7AB6250 8008A520 21380000 */   addu      $a3, $zero, $zero
.Llevel_37_8008A524:
/* 7AB6254 8008A524 0780023C */  lui        $v0, %hi(D_8006C654)
/* 7AB6258 8008A528 54C6428C */  lw         $v0, %lo(D_8006C654)($v0)
/* 7AB625C 8008A52C 21280000 */  addu       $a1, $zero, $zero
/* 7AB6260 8008A530 0E004490 */  lbu        $a0, 0xE($v0)
/* 7AB6264 8008A534 D4EE000C */  jal        func_8003BB50
/* 7AB6268 8008A538 21300000 */   addu      $a2, $zero, $zero
/* 7AB626C 8008A53C 0780033C */  lui        $v1, %hi(D_8006C654)
/* 7AB6270 8008A540 54C6638C */  lw         $v1, %lo(D_8006C654)($v1)
/* 7AB6274 8008A544 0780013C */  lui        $at, %hi(D_80070328 + 0x28C)
/* 7AB6278 8008A548 B40522AC */  sw         $v0, %lo(D_80070328 + 0x28C)($at)
/* 7AB627C 8008A54C 0E006290 */  lbu        $v0, 0xE($v1)
/* 7AB6280 8008A550 0780013C */  lui        $at, %hi(D_80070328 + 0x244)
/* 7AB6284 8008A554 6C0520AC */  sw         $zero, %lo(D_80070328 + 0x244)($at)
/* 7AB6288 8008A558 0780013C */  lui        $at, %hi(D_80070328 + 0x250)
/* 7AB628C 8008A55C 780520AC */  sw         $zero, %lo(D_80070328 + 0x250)($at)
/* 7AB6290 8008A560 0780013C */  lui        $at, %hi(D_80070328 + 0x290)
/* 7AB6294 8008A564 B80522AC */  sw         $v0, %lo(D_80070328 + 0x290)($at)
/* 7AB6298 8008A568 BD2A0208 */  j          .Llevel_37_8008AAF4
/* 7AB629C 8008A56C 00000000 */   nop
.L8008A570_:
/* 7AB62A0 8008A570 08000224 */  addiu      $v0, $zero, 0x8
/* 7AB62A4 8008A574 0780013C */  lui        $at, %hi(D_80070328 + 0x50)
/* 7AB62A8 8008A578 780322AC */  sw         $v0, %lo(D_80070328 + 0x50)($at)
/* 7AB62AC 8008A57C 0780013C */  lui        $at, %hi(D_80070328 + 0x4C)
/* 7AB62B0 8008A580 740320AC */  sw         $zero, %lo(D_80070328 + 0x4C)($at)
/* 7AB62B4 8008A584 8E0E010C */  jal        func_80043A38
/* 7AB62B8 8008A588 000C0424 */   addiu     $a0, $zero, 0xC00
/* 7AB62BC 8008A58C 01000224 */  addiu      $v0, $zero, 0x1
/* 7AB62C0 8008A590 0780013C */  lui        $at, %hi(D_80070328 + 0x1B4)
/* 7AB62C4 8008A594 DC0422A0 */  sb         $v0, %lo(D_80070328 + 0x1B4)($at)
/* 7AB62C8 8008A598 3A000224 */  addiu      $v0, $zero, 0x3A
/* 7AB62CC 8008A59C 03002212 */  beq        $s1, $v0, .Llevel_37_8008A5AC
/* 7AB62D0 8008A5A0 6C000224 */   addiu     $v0, $zero, 0x6C
/* 7AB62D4 8008A5A4 08002216 */  bne        $s1, $v0, .Llevel_37_8008A5C8
/* 7AB62D8 8008A5A8 0F000224 */   addiu     $v0, $zero, 0xF
.Llevel_37_8008A5AC:
/* 7AB62DC 8008A5AC 0780023C */  lui        $v0, %hi(D_8006C654)
/* 7AB62E0 8008A5B0 54C6428C */  lw         $v0, %lo(D_8006C654)($v0)
/* 7AB62E4 8008A5B4 21280000 */  addu       $a1, $zero, $zero
/* 7AB62E8 8008A5B8 0C004490 */  lbu        $a0, 0xC($v0)
/* 7AB62EC 8008A5BC D4EE000C */  jal        func_8003BB50
/* 7AB62F0 8008A5C0 21300000 */   addu      $a2, $zero, $zero
/* 7AB62F4 8008A5C4 0F000224 */  addiu      $v0, $zero, 0xF
.Llevel_37_8008A5C8:
/* 7AB62F8 8008A5C8 0780013C */  lui        $at, %hi(D_8006E524)
/* 7AB62FC 8008A5CC 24E522AC */  sw         $v0, %lo(D_8006E524)($at)
/* 7AB6300 8008A5D0 B92A0208 */  j          .Llevel_37_8008AAE4
/* 7AB6304 8008A5D4 00000000 */   nop
.L8008A5D8_:
/* 7AB6308 8008A5D8 0780103C */  lui        $s0, %hi(D_80070328 + 0x50)
/* 7AB630C 8008A5DC 78031026 */  addiu      $s0, $s0, %lo(D_80070328 + 0x50)
/* 7AB6310 8008A5E0 0000038E */  lw         $v1, 0x0($s0)
/* 7AB6314 8008A5E4 00000000 */  nop
/* 7AB6318 8008A5E8 F5FF6224 */  addiu      $v0, $v1, -0xB
/* 7AB631C 8008A5EC 0200422C */  sltiu      $v0, $v0, 0x2
/* 7AB6320 8008A5F0 5D004014 */  bnez       $v0, .Llevel_37_8008A768
/* 7AB6324 8008A5F4 07000224 */   addiu     $v0, $zero, 0x7
/* 7AB6328 8008A5F8 5B006210 */  beq        $v1, $v0, .Llevel_37_8008A768
/* 7AB632C 8008A5FC 00000000 */   nop
/* 7AB6330 8008A600 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 7AB6334 8008A604 E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 7AB6338 8008A608 00000000 */  nop
/* 7AB633C 8008A60C 2F004010 */  beqz       $v0, .Llevel_37_8008A6CC
/* 7AB6340 8008A610 1000A427 */   addiu     $a0, $sp, 0x10
/* 7AB6344 8008A614 5E3C010C */  jal        func_8004F178
/* 7AB6348 8008A618 B0FF0526 */   addiu     $a1, $s0, -0x50
/* 7AB634C 8008A61C 0000038E */  lw         $v1, 0x0($s0)
/* 7AB6350 8008A620 0A000224 */  addiu      $v0, $zero, 0xA
/* 7AB6354 8008A624 11006214 */  bne        $v1, $v0, .Llevel_37_8008A66C
/* 7AB6358 8008A628 00000000 */   nop
/* 7AB635C 8008A62C 0780033C */  lui        $v1, %hi(D_80070328 + 0x28)
/* 7AB6360 8008A630 5003638C */  lw         $v1, %lo(D_80070328 + 0x28)($v1)
/* 7AB6364 8008A634 00000000 */  nop
/* 7AB6368 8008A638 0C006104 */  bgez       $v1, .Llevel_37_8008A66C
/* 7AB636C 8008A63C 06000424 */   addiu     $a0, $zero, 0x6
/* 7AB6370 8008A640 2E000524 */  addiu      $a1, $zero, 0x2E
/* 7AB6374 8008A644 1000A627 */  addiu      $a2, $sp, 0x10
/* 7AB6378 8008A648 21380000 */  addu       $a3, $zero, $zero
/* 7AB637C 8008A64C 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 7AB6380 8008A650 E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 7AB6384 8008A654 23180300 */  negu       $v1, $v1
/* 7AB6388 8008A658 09F84000 */  jalr       $v0
/* 7AB638C 8008A65C 1800A3AF */   sw        $v1, 0x18($sp)
/* 7AB6390 8008A660 04000424 */  addiu      $a0, $zero, 0x4
/* 7AB6394 8008A664 AD290208 */  j          .Llevel_37_8008A6B4
/* 7AB6398 8008A668 29000524 */   addiu     $a1, $zero, 0x29
.Llevel_37_8008A66C:
/* 7AB639C 8008A66C 0780033C */  lui        $v1, %hi(D_80070328 + 0x50)
/* 7AB63A0 8008A670 7803638C */  lw         $v1, %lo(D_80070328 + 0x50)($v1)
/* 7AB63A4 8008A674 04000224 */  addiu      $v0, $zero, 0x4
/* 7AB63A8 8008A678 14006214 */  bne        $v1, $v0, .Llevel_37_8008A6CC
/* 7AB63AC 8008A67C 1000A427 */   addiu     $a0, $sp, 0x10
/* 7AB63B0 8008A680 1800A28F */  lw         $v0, 0x18($sp)
/* 7AB63B4 8008A684 00080524 */  addiu      $a1, $zero, 0x800
/* 7AB63B8 8008A688 00044224 */  addiu      $v0, $v0, 0x400
/* 7AB63BC 8008A68C D668000C */  jal        func_8001A358
/* 7AB63C0 8008A690 1800A2AF */   sw        $v0, 0x18($sp)
/* 7AB63C4 8008A694 0D004010 */  beqz       $v0, .Llevel_37_8008A6CC
/* 7AB63C8 8008A698 1800A2AF */   sw        $v0, 0x18($sp)
/* 7AB63CC 8008A69C 0780023C */  lui        $v0, %hi(D_80071934)
/* 7AB63D0 8008A6A0 3419428C */  lw         $v0, %lo(D_80071934)($v0)
/* 7AB63D4 8008A6A4 00000000 */  nop
/* 7AB63D8 8008A6A8 08004010 */  beqz       $v0, .Llevel_37_8008A6CC
/* 7AB63DC 8008A6AC 06000424 */   addiu     $a0, $zero, 0x6
/* 7AB63E0 8008A6B0 2E000524 */  addiu      $a1, $zero, 0x2E
.Llevel_37_8008A6B4:
/* 7AB63E4 8008A6B4 1000A627 */  addiu      $a2, $sp, 0x10
/* 7AB63E8 8008A6B8 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 7AB63EC 8008A6BC E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 7AB63F0 8008A6C0 00000000 */  nop
/* 7AB63F4 8008A6C4 09F84000 */  jalr       $v0
/* 7AB63F8 8008A6C8 21380000 */   addu      $a3, $zero, $zero
.Llevel_37_8008A6CC:
/* 7AB63FC 8008A6CC 0780103C */  lui        $s0, %hi(D_80070328 + 0x60)
/* 7AB6400 8008A6D0 88031026 */  addiu      $s0, $s0, %lo(D_80070328 + 0x60)
/* 7AB6404 8008A6D4 0000028E */  lw         $v0, 0x0($s0)
/* 7AB6408 8008A6D8 00000000 */  nop
/* 7AB640C 8008A6DC FF0F4330 */  andi       $v1, $v0, 0xFFF
/* 7AB6410 8008A6E0 01086228 */  slti       $v0, $v1, 0x801
/* 7AB6414 8008A6E4 03004014 */  bnez       $v0, .Llevel_37_8008A6F4
/* 7AB6418 8008A6E8 000003AE */   sw        $v1, 0x0($s0)
/* 7AB641C 8008A6EC 00F06224 */  addiu      $v0, $v1, -0x1000
/* 7AB6420 8008A6F0 000002AE */  sw         $v0, 0x0($s0)
.Llevel_37_8008A6F4:
/* 7AB6424 8008A6F4 0000028E */  lw         $v0, 0x0($s0)
/* 7AB6428 8008A6F8 00000000 */  nop
/* 7AB642C 8008A6FC 02004018 */  blez       $v0, .Llevel_37_8008A708
/* 7AB6430 8008A700 28000224 */   addiu     $v0, $zero, 0x28
/* 7AB6434 8008A704 000000AE */  sw         $zero, 0x0($s0)
.Llevel_37_8008A708:
/* 7AB6438 8008A708 03002216 */  bne        $s1, $v0, .Llevel_37_8008A718
/* 7AB643C 8008A70C 01000224 */   addiu     $v0, $zero, 0x1
/* 7AB6440 8008A710 0780013C */  lui        $at, %hi(D_80070328 + 0x4C)
/* 7AB6444 8008A714 740322AC */  sw         $v0, %lo(D_80070328 + 0x4C)($at)
.Llevel_37_8008A718:
/* 7AB6448 8008A718 5A3C010C */  jal        func_8004F168
/* 7AB644C 8008A71C EC000426 */   addiu     $a0, $s0, 0xEC
/* 7AB6450 8008A720 38000426 */  addiu      $a0, $s0, 0x38
/* 7AB6454 8008A724 0780013C */  lui        $at, %hi(D_80070328 + 0x144)
/* 7AB6458 8008A728 6C0420AC */  sw         $zero, %lo(D_80070328 + 0x144)($at)
/* 7AB645C 8008A72C 7A3B010C */  jal        func_8004EDE8
/* 7AB6460 8008A730 21280000 */   addu      $a1, $zero, $zero
/* 7AB6464 8008A734 0780033C */  lui        $v1, %hi(D_8006C654)
/* 7AB6468 8008A738 54C6638C */  lw         $v1, %lo(D_8006C654)($v1)
/* 7AB646C 8008A73C 21280000 */  addu       $a1, $zero, $zero
/* 7AB6470 8008A740 0780013C */  lui        $at, %hi(D_80070328 + 0xB0)
/* 7AB6474 8008A744 D80322AC */  sw         $v0, %lo(D_80070328 + 0xB0)($at)
/* 7AB6478 8008A748 01000224 */  addiu      $v0, $zero, 0x1
/* 7AB647C 8008A74C 0780013C */  lui        $at, %hi(D_80070328 + 0x1B4)
/* 7AB6480 8008A750 DC0422A0 */  sb         $v0, %lo(D_80070328 + 0x1B4)($at)
/* 7AB6484 8008A754 08006490 */  lbu        $a0, 0x8($v1)
/* 7AB6488 8008A758 D4EE000C */  jal        func_8003BB50
/* 7AB648C 8008A75C 21300000 */   addu      $a2, $zero, $zero
/* 7AB6490 8008A760 E2290208 */  j          .Llevel_37_8008A788
/* 7AB6494 8008A764 00000000 */   nop
.Llevel_37_8008A768:
/* 7AB6498 8008A768 0780033C */  lui        $v1, %hi(D_80070328 + 0x48)
/* 7AB649C 8008A76C 7003638C */  lw         $v1, %lo(D_80070328 + 0x48)($v1)
/* 7AB64A0 8008A770 2A000224 */  addiu      $v0, $zero, 0x2A
/* 7AB64A4 8008A774 07006214 */  bne        $v1, $v0, .Llevel_37_8008A794
/* 7AB64A8 8008A778 0B000224 */   addiu     $v0, $zero, 0xB
/* 7AB64AC 8008A77C 02000224 */  addiu      $v0, $zero, 0x2
/* 7AB64B0 8008A780 0780013C */  lui        $at, %hi(D_80070328 + 0x4C)
/* 7AB64B4 8008A784 740322AC */  sw         $v0, %lo(D_80070328 + 0x4C)($at)
.Llevel_37_8008A788:
/* 7AB64B8 8008A788 0780013C */  lui        $at, %hi(D_80070328 + 0x158)
/* 7AB64BC 8008A78C 800420AC */  sw         $zero, %lo(D_80070328 + 0x158)($at)
/* 7AB64C0 8008A790 0B000224 */  addiu      $v0, $zero, 0xB
.Llevel_37_8008A794:
/* 7AB64C4 8008A794 0780013C */  lui        $at, %hi(D_80070328 + 0x50)
/* 7AB64C8 8008A798 780322AC */  sw         $v0, %lo(D_80070328 + 0x50)($at)
/* 7AB64CC 8008A79C 0780013C */  lui        $at, %hi(D_80070328 + 0x244)
/* 7AB64D0 8008A7A0 6C0520AC */  sw         $zero, %lo(D_80070328 + 0x244)($at)
/* 7AB64D4 8008A7A4 0780013C */  lui        $at, %hi(D_80070328 + 0x250)
/* 7AB64D8 8008A7A8 780520AC */  sw         $zero, %lo(D_80070328 + 0x250)($at)
/* 7AB64DC 8008A7AC B92A0208 */  j          .Llevel_37_8008AAE4
/* 7AB64E0 8008A7B0 00000000 */   nop
.L8008A7B4_:
/* 7AB64E4 8008A7B4 0780113C */  lui        $s1, %hi(D_80070328 + 0x50)
/* 7AB64E8 8008A7B8 78033126 */  addiu      $s1, $s1, %lo(D_80070328 + 0x50)
/* 7AB64EC 8008A7BC 0000228E */  lw         $v0, 0x0($s1)
/* 7AB64F0 8008A7C0 00000000 */  nop
/* 7AB64F4 8008A7C4 F5FF4224 */  addiu      $v0, $v0, -0xB
/* 7AB64F8 8008A7C8 0200422C */  sltiu      $v0, $v0, 0x2
/* 7AB64FC 8008A7CC 69004014 */  bnez       $v0, .Llevel_37_8008A974
/* 7AB6500 8008A7D0 0C000224 */   addiu     $v0, $zero, 0xC
/* 7AB6504 8008A7D4 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 7AB6508 8008A7D8 E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 7AB650C 8008A7DC 00000000 */  nop
/* 7AB6510 8008A7E0 31004010 */  beqz       $v0, .Llevel_37_8008A8A8
/* 7AB6514 8008A7E4 2000B027 */   addiu     $s0, $sp, 0x20
/* 7AB6518 8008A7E8 21200002 */  addu       $a0, $s0, $zero
/* 7AB651C 8008A7EC 5E3C010C */  jal        func_8004F178
/* 7AB6520 8008A7F0 B0FF2526 */   addiu     $a1, $s1, -0x50
/* 7AB6524 8008A7F4 0000238E */  lw         $v1, 0x0($s1)
/* 7AB6528 8008A7F8 0A000224 */  addiu      $v0, $zero, 0xA
/* 7AB652C 8008A7FC 11006214 */  bne        $v1, $v0, .Llevel_37_8008A844
/* 7AB6530 8008A800 00000000 */   nop
/* 7AB6534 8008A804 0780033C */  lui        $v1, %hi(D_80070328 + 0x28)
/* 7AB6538 8008A808 5003638C */  lw         $v1, %lo(D_80070328 + 0x28)($v1)
/* 7AB653C 8008A80C 00000000 */  nop
/* 7AB6540 8008A810 0C006104 */  bgez       $v1, .Llevel_37_8008A844
/* 7AB6544 8008A814 06000424 */   addiu     $a0, $zero, 0x6
/* 7AB6548 8008A818 2E000524 */  addiu      $a1, $zero, 0x2E
/* 7AB654C 8008A81C 21300002 */  addu       $a2, $s0, $zero
/* 7AB6550 8008A820 21380000 */  addu       $a3, $zero, $zero
/* 7AB6554 8008A824 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 7AB6558 8008A828 E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 7AB655C 8008A82C 23180300 */  negu       $v1, $v1
/* 7AB6560 8008A830 09F84000 */  jalr       $v0
/* 7AB6564 8008A834 2800A3AF */   sw        $v1, 0x28($sp)
/* 7AB6568 8008A838 04000424 */  addiu      $a0, $zero, 0x4
/* 7AB656C 8008A83C 242A0208 */  j          .Llevel_37_8008A890
/* 7AB6570 8008A840 29000524 */   addiu     $a1, $zero, 0x29
.Llevel_37_8008A844:
/* 7AB6574 8008A844 0780033C */  lui        $v1, %hi(D_80070328 + 0x50)
/* 7AB6578 8008A848 7803638C */  lw         $v1, %lo(D_80070328 + 0x50)($v1)
/* 7AB657C 8008A84C 04000224 */  addiu      $v0, $zero, 0x4
/* 7AB6580 8008A850 15006214 */  bne        $v1, $v0, .Llevel_37_8008A8A8
/* 7AB6584 8008A854 2000B027 */   addiu     $s0, $sp, 0x20
/* 7AB6588 8008A858 21200002 */  addu       $a0, $s0, $zero
/* 7AB658C 8008A85C 2800A28F */  lw         $v0, 0x28($sp)
/* 7AB6590 8008A860 00080524 */  addiu      $a1, $zero, 0x800
/* 7AB6594 8008A864 00044224 */  addiu      $v0, $v0, 0x400
/* 7AB6598 8008A868 D668000C */  jal        func_8001A358
/* 7AB659C 8008A86C 2800A2AF */   sw        $v0, 0x28($sp)
/* 7AB65A0 8008A870 0D004010 */  beqz       $v0, .Llevel_37_8008A8A8
/* 7AB65A4 8008A874 2800A2AF */   sw        $v0, 0x28($sp)
/* 7AB65A8 8008A878 0780023C */  lui        $v0, %hi(D_80071934)
/* 7AB65AC 8008A87C 3419428C */  lw         $v0, %lo(D_80071934)($v0)
/* 7AB65B0 8008A880 00000000 */  nop
/* 7AB65B4 8008A884 08004010 */  beqz       $v0, .Llevel_37_8008A8A8
/* 7AB65B8 8008A888 06000424 */   addiu     $a0, $zero, 0x6
/* 7AB65BC 8008A88C 2E000524 */  addiu      $a1, $zero, 0x2E
.Llevel_37_8008A890:
/* 7AB65C0 8008A890 21300002 */  addu       $a2, $s0, $zero
/* 7AB65C4 8008A894 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 7AB65C8 8008A898 E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 7AB65CC 8008A89C 00000000 */  nop
/* 7AB65D0 8008A8A0 09F84000 */  jalr       $v0
/* 7AB65D4 8008A8A4 21380000 */   addu      $a3, $zero, $zero
.Llevel_37_8008A8A8:
/* 7AB65D8 8008A8A8 0780103C */  lui        $s0, %hi(D_80070328 + 0x48)
/* 7AB65DC 8008A8AC 70031026 */  addiu      $s0, $s0, %lo(D_80070328 + 0x48)
/* 7AB65E0 8008A8B0 0000038E */  lw         $v1, 0x0($s0)
/* 7AB65E4 8008A8B4 2E000224 */  addiu      $v0, $zero, 0x2E
/* 7AB65E8 8008A8B8 07006214 */  bne        $v1, $v0, .Llevel_37_8008A8D8
/* 7AB65EC 8008A8BC 00000000 */   nop
/* 7AB65F0 8008A8C0 0780023C */  lui        $v0, %hi(D_80070328 + 0x60)
/* 7AB65F4 8008A8C4 8803428C */  lw         $v0, %lo(D_80070328 + 0x60)($v0)
/* 7AB65F8 8008A8C8 00000000 */  nop
/* 7AB65FC 8008A8CC 00FC4224 */  addiu      $v0, $v0, -0x400
/* 7AB6600 8008A8D0 0780013C */  lui        $at, %hi(D_80070328 + 0x60)
/* 7AB6604 8008A8D4 880322AC */  sw         $v0, %lo(D_80070328 + 0x60)($at)
.Llevel_37_8008A8D8:
/* 7AB6608 8008A8D8 0780023C */  lui        $v0, %hi(D_80070328 + 0x60)
/* 7AB660C 8008A8DC 8803428C */  lw         $v0, %lo(D_80070328 + 0x60)($v0)
/* 7AB6610 8008A8E0 00000000 */  nop
/* 7AB6614 8008A8E4 FF0F4330 */  andi       $v1, $v0, 0xFFF
/* 7AB6618 8008A8E8 01086228 */  slti       $v0, $v1, 0x801
/* 7AB661C 8008A8EC 0780013C */  lui        $at, %hi(D_80070328 + 0x60)
/* 7AB6620 8008A8F0 880323AC */  sw         $v1, %lo(D_80070328 + 0x60)($at)
/* 7AB6624 8008A8F4 03004014 */  bnez       $v0, .Llevel_37_8008A904
/* 7AB6628 8008A8F8 00F06224 */   addiu     $v0, $v1, -0x1000
/* 7AB662C 8008A8FC 0780013C */  lui        $at, %hi(D_80070328 + 0x60)
/* 7AB6630 8008A900 880322AC */  sw         $v0, %lo(D_80070328 + 0x60)($at)
.Llevel_37_8008A904:
/* 7AB6634 8008A904 0780023C */  lui        $v0, %hi(D_80070328 + 0x60)
/* 7AB6638 8008A908 8803428C */  lw         $v0, %lo(D_80070328 + 0x60)($v0)
/* 7AB663C 8008A90C 00000000 */  nop
/* 7AB6640 8008A910 03004018 */  blez       $v0, .Llevel_37_8008A920
/* 7AB6644 8008A914 01000224 */   addiu     $v0, $zero, 0x1
/* 7AB6648 8008A918 0780013C */  lui        $at, %hi(D_80070328 + 0x60)
/* 7AB664C 8008A91C 880320AC */  sw         $zero, %lo(D_80070328 + 0x60)($at)
.Llevel_37_8008A920:
/* 7AB6650 8008A920 0780013C */  lui        $at, %hi(D_80070328 + 0x4C)
/* 7AB6654 8008A924 740322AC */  sw         $v0, %lo(D_80070328 + 0x4C)($at)
/* 7AB6658 8008A928 5A3C010C */  jal        func_8004F168
/* 7AB665C 8008A92C 04010426 */   addiu     $a0, $s0, 0x104
/* 7AB6660 8008A930 50000426 */  addiu      $a0, $s0, 0x50
/* 7AB6664 8008A934 0780013C */  lui        $at, %hi(D_80070328 + 0x144)
/* 7AB6668 8008A938 6C0420AC */  sw         $zero, %lo(D_80070328 + 0x144)($at)
/* 7AB666C 8008A93C 7A3B010C */  jal        func_8004EDE8
/* 7AB6670 8008A940 21280000 */   addu      $a1, $zero, $zero
/* 7AB6674 8008A944 0780033C */  lui        $v1, %hi(D_8006C654)
/* 7AB6678 8008A948 54C6638C */  lw         $v1, %lo(D_8006C654)($v1)
/* 7AB667C 8008A94C 21280000 */  addu       $a1, $zero, $zero
/* 7AB6680 8008A950 0780013C */  lui        $at, %hi(D_80070328 + 0xB0)
/* 7AB6684 8008A954 D80322AC */  sw         $v0, %lo(D_80070328 + 0xB0)($at)
/* 7AB6688 8008A958 01000224 */  addiu      $v0, $zero, 0x1
/* 7AB668C 8008A95C 0780013C */  lui        $at, %hi(D_80070328 + 0x1B4)
/* 7AB6690 8008A960 DC0422A0 */  sb         $v0, %lo(D_80070328 + 0x1B4)($at)
/* 7AB6694 8008A964 08006490 */  lbu        $a0, 0x8($v1)
/* 7AB6698 8008A968 D4EE000C */  jal        func_8003BB50
/* 7AB669C 8008A96C 21300000 */   addu      $a2, $zero, $zero
/* 7AB66A0 8008A970 0C000224 */  addiu      $v0, $zero, 0xC
.Llevel_37_8008A974:
/* 7AB66A4 8008A974 0780013C */  lui        $at, %hi(D_80070328 + 0x50)
/* 7AB66A8 8008A978 780322AC */  sw         $v0, %lo(D_80070328 + 0x50)($at)
/* 7AB66AC 8008A97C 0200023C */  lui        $v0, (0x20000 >> 16)
/* 7AB66B0 8008A980 0780013C */  lui        $at, %hi(D_80070328 + 0x130)
/* 7AB66B4 8008A984 580422AC */  sw         $v0, %lo(D_80070328 + 0x130)($at)
/* 7AB66B8 8008A988 B92A0208 */  j          .Llevel_37_8008AAE4
/* 7AB66BC 8008A98C 00000000 */   nop
.L8008A990_:
/* 7AB66C0 8008A990 0780033C */  lui        $v1, %hi(D_80070328 + 0x50)
/* 7AB66C4 8008A994 7803638C */  lw         $v1, %lo(D_80070328 + 0x50)($v1)
/* 7AB66C8 8008A998 0A000224 */  addiu      $v0, $zero, 0xA
/* 7AB66CC 8008A99C 51006210 */  beq        $v1, $v0, .Llevel_37_8008AAE4
/* 7AB66D0 8008A9A0 21280000 */   addu      $a1, $zero, $zero
/* 7AB66D4 8008A9A4 0780023C */  lui        $v0, %hi(D_8006C654)
/* 7AB66D8 8008A9A8 54C6428C */  lw         $v0, %lo(D_8006C654)($v0)
/* 7AB66DC 8008A9AC 00000000 */  nop
/* 7AB66E0 8008A9B0 07004490 */  lbu        $a0, 0x7($v0)
/* 7AB66E4 8008A9B4 D4EE000C */  jal        func_8003BB50
/* 7AB66E8 8008A9B8 21300000 */   addu      $a2, $zero, $zero
/* 7AB66EC 8008A9BC 0780023C */  lui        $v0, %hi(D_80070328 + 0x94)
/* 7AB66F0 8008A9C0 BC03428C */  lw         $v0, %lo(D_80070328 + 0x94)($v0)
/* 7AB66F4 8008A9C4 0780113C */  lui        $s1, %hi(D_80070328 + 0x144)
/* 7AB66F8 8008A9C8 6C043126 */  addiu      $s1, $s1, %lo(D_80070328 + 0x144)
/* 7AB66FC 8008A9CC 23100200 */  negu       $v0, $v0
/* 7AB6700 8008A9D0 83100200 */  sra        $v0, $v0, 2
/* 7AB6704 8008A9D4 000022AE */  sw         $v0, 0x0($s1)
/* 7AB6708 8008A9D8 0780033C */  lui        $v1, %hi(D_80070328 + 0x50)
/* 7AB670C 8008A9DC 7803638C */  lw         $v1, %lo(D_80070328 + 0x50)($v1)
/* 7AB6710 8008A9E0 08000224 */  addiu      $v0, $zero, 0x8
/* 7AB6714 8008A9E4 06006210 */  beq        $v1, $v0, .Llevel_37_8008AA00
/* 7AB6718 8008A9E8 00590224 */   addiu     $v0, $zero, 0x5900
/* 7AB671C 8008A9EC 0780013C */  lui        $at, %hi(D_80070328 + 0x148)
/* 7AB6720 8008A9F0 700422AC */  sw         $v0, %lo(D_80070328 + 0x148)($at)
/* 7AB6724 8008A9F4 0A000224 */  addiu      $v0, $zero, 0xA
/* 7AB6728 8008A9F8 0780013C */  lui        $at, %hi(D_80070328 + 0x50)
/* 7AB672C 8008A9FC 780322AC */  sw         $v0, %lo(D_80070328 + 0x50)($at)
.Llevel_37_8008AA00:
/* 7AB6730 8008AA00 54FF2426 */  addiu      $a0, $s1, -0xAC
/* 7AB6734 8008AA04 0780013C */  lui        $at, %hi(D_80070328 + 0x4C)
/* 7AB6738 8008AA08 740320AC */  sw         $zero, %lo(D_80070328 + 0x4C)($at)
/* 7AB673C 8008AA0C 7A3B010C */  jal        func_8004EDE8
/* 7AB6740 8008AA10 21280000 */   addu      $a1, $zero, $zero
/* 7AB6744 8008AA14 3000B027 */  addiu      $s0, $sp, 0x30
/* 7AB6748 8008AA18 21200002 */  addu       $a0, $s0, $zero
/* 7AB674C 8008AA1C 0780013C */  lui        $at, %hi(D_80070328 + 0xB0)
/* 7AB6750 8008AA20 D80322AC */  sw         $v0, %lo(D_80070328 + 0xB0)($at)
/* 7AB6754 8008AA24 01000224 */  addiu      $v0, $zero, 0x1
/* 7AB6758 8008AA28 0780013C */  lui        $at, %hi(D_80070328 + 0x1B4)
/* 7AB675C 8008AA2C DC0422A0 */  sb         $v0, %lo(D_80070328 + 0x1B4)($at)
/* 7AB6760 8008AA30 0780013C */  lui        $at, %hi(D_80070328 + 0x1B5)
/* 7AB6764 8008AA34 DD0422A0 */  sb         $v0, %lo(D_80070328 + 0x1B5)($at)
/* 7AB6768 8008AA38 5E3C010C */  jal        func_8004F178
/* 7AB676C 8008AA3C BCFE2526 */   addiu     $a1, $s1, -0x144
/* 7AB6770 8008AA40 21200002 */  addu       $a0, $s0, $zero
/* 7AB6774 8008AA44 3800A28F */  lw         $v0, 0x38($sp)
/* 7AB6778 8008AA48 00080524 */  addiu      $a1, $zero, 0x800
/* 7AB677C 8008AA4C 00044224 */  addiu      $v0, $v0, 0x400
/* 7AB6780 8008AA50 D668000C */  jal        func_8001A358
/* 7AB6784 8008AA54 3800A2AF */   sw        $v0, 0x38($sp)
/* 7AB6788 8008AA58 22004010 */  beqz       $v0, .Llevel_37_8008AAE4
/* 7AB678C 8008AA5C 3800A2AF */   sw        $v0, 0x38($sp)
/* 7AB6790 8008AA60 0780023C */  lui        $v0, %hi(D_80071934)
/* 7AB6794 8008AA64 3419428C */  lw         $v0, %lo(D_80071934)($v0)
/* 7AB6798 8008AA68 00000000 */  nop
/* 7AB679C 8008AA6C 1D004010 */  beqz       $v0, .Llevel_37_8008AAE4
/* 7AB67A0 8008AA70 00000000 */   nop
/* 7AB67A4 8008AA74 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 7AB67A8 8008AA78 E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 7AB67AC 8008AA7C 00000000 */  nop
/* 7AB67B0 8008AA80 18004010 */  beqz       $v0, .Llevel_37_8008AAE4
/* 7AB67B4 8008AA84 0A000424 */   addiu     $a0, $zero, 0xA
/* 7AB67B8 8008AA88 29000524 */  addiu      $a1, $zero, 0x29
/* 7AB67BC 8008AA8C 21300002 */  addu       $a2, $s0, $zero
/* 7AB67C0 8008AA90 09F84000 */  jalr       $v0
/* 7AB67C4 8008AA94 21380000 */   addu      $a3, $zero, $zero
/* 7AB67C8 8008AA98 06000424 */  addiu      $a0, $zero, 0x6
/* 7AB67CC 8008AA9C 2E000524 */  addiu      $a1, $zero, 0x2E
/* 7AB67D0 8008AAA0 21300002 */  addu       $a2, $s0, $zero
/* 7AB67D4 8008AAA4 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 7AB67D8 8008AAA8 E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 7AB67DC 8008AAAC 00000000 */  nop
/* 7AB67E0 8008AAB0 09F84000 */  jalr       $v0
/* 7AB67E4 8008AAB4 21380000 */   addu      $a3, $zero, $zero
/* 7AB67E8 8008AAB8 B92A0208 */  j          .Llevel_37_8008AAE4
/* 7AB67EC 8008AABC 00000000 */   nop
.L8008AAC0_:
/* 7AB67F0 8008AAC0 0780013C */  lui        $at, %hi(D_80070328 + 0x50)
/* 7AB67F4 8008AAC4 780320AC */  sw         $zero, %lo(D_80070328 + 0x50)($at)
/* 7AB67F8 8008AAC8 0780013C */  lui        $at, %hi(D_80070328 + 0x4C)
/* 7AB67FC 8008AACC 740320AC */  sw         $zero, %lo(D_80070328 + 0x4C)($at)
/* 7AB6800 8008AAD0 7C10010C */  jal        func_800441F0
/* 7AB6804 8008AAD4 00000000 */   nop
/* 7AB6808 8008AAD8 01000224 */  addiu      $v0, $zero, 0x1
/* 7AB680C 8008AADC 0780013C */  lui        $at, %hi(D_80070328 + 0x1B4)
/* 7AB6810 8008AAE0 DC0422A0 */  sb         $v0, %lo(D_80070328 + 0x1B4)($at)
.Llevel_37_8008AAE4:
/* 7AB6814 8008AAE4 0780013C */  lui        $at, %hi(D_80070328 + 0x244)
/* 7AB6818 8008AAE8 6C0520AC */  sw         $zero, %lo(D_80070328 + 0x244)($at)
/* 7AB681C 8008AAEC 0780013C */  lui        $at, %hi(D_80070328 + 0x250)
/* 7AB6820 8008AAF0 780520AC */  sw         $zero, %lo(D_80070328 + 0x250)($at)
.Llevel_37_8008AAF4:
/* 7AB6824 8008AAF4 4800BF8F */  lw         $ra, 0x48($sp)
/* 7AB6828 8008AAF8 4400B18F */  lw         $s1, 0x44($sp)
/* 7AB682C 8008AAFC 4000B08F */  lw         $s0, 0x40($sp)
/* 7AB6830 8008AB00 5000BD27 */  addiu      $sp, $sp, 0x50
/* 7AB6834 8008AB04 0800E003 */  jr         $ra
/* 7AB6838 8008AB08 00000000 */   nop
.size func_level_37_8008A294, . - func_level_37_8008A294
