.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_37_80074B8C
/* 7AA08BC 80074B8C 30A10880 */ .word .L8008A130_
/* 7AA08C0 80074B90 38A10880 */ .word .L8008A138_
/* 7AA08C4 80074B94 40A10880 */ .word .L8008A140_
/* 7AA08C8 80074B98 48A10880 */ .word .L8008A148_
/* 7AA08CC 80074B9C 50A10880 */ .word .L8008A150_
/* 7AA08D0 80074BA0 58A10880 */ .word .L8008A158_
/* 7AA08D4 80074BA4 60A10880 */ .word .L8008A160_
/* 7AA08D8 80074BA8 68A10880 */ .word .L8008A168_
/* 7AA08DC 80074BAC 70A10880 */ .word .L8008A170_
/* 7AA08E0 80074BB0 00000000 */ .word 0x00000000
.size jtbl_level_37_80074B8C, . - jtbl_level_37_80074B8C


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_37_8008A0DC
/* 7AB5E0C 8008A0DC 0780023C */  lui        $v0, %hi(D_80070328 + 0x244)
/* 7AB5E10 8008A0E0 6C05428C */  lw         $v0, %lo(D_80070328 + 0x244)($v0)
/* 7AB5E14 8008A0E4 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 7AB5E18 8008A0E8 1400BFAF */  sw         $ra, 0x14($sp)
/* 7AB5E1C 8008A0EC 27004010 */  beqz       $v0, .Llevel_37_8008A18C
/* 7AB5E20 8008A0F0 1000B0AF */   sw        $s0, 0x10($sp)
/* 7AB5E24 8008A0F4 0780033C */  lui        $v1, %hi(D_80070328 + 0x24C)
/* 7AB5E28 8008A0F8 7405638C */  lw         $v1, %lo(D_80070328 + 0x24C)($v1)
/* 7AB5E2C 8008A0FC 0780023C */  lui        $v0, %hi(D_80070328 + 0x250)
/* 7AB5E30 8008A100 7805428C */  lw         $v0, %lo(D_80070328 + 0x250)($v0)
/* 7AB5E34 8008A104 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 7AB5E38 8008A108 3C004490 */  lbu        $a0, 0x3C($v0)
/* 7AB5E3C 8008A10C 0900622C */  sltiu      $v0, $v1, 0x9
/* 7AB5E40 8008A110 18004010 */  beqz       $v0, .Llevel_37_8008A174
/* 7AB5E44 8008A114 80100300 */   sll       $v0, $v1, 2
/* 7AB5E48 8008A118 0780013C */  lui        $at, %hi(jtbl_level_37_80074B8C)
/* 7AB5E4C 8008A11C 21082200 */  addu       $at, $at, $v0
/* 7AB5E50 8008A120 8C4B228C */  lw         $v0, %lo(jtbl_level_37_80074B8C)($at)
/* 7AB5E54 8008A124 00000000 */  nop
/* 7AB5E58 8008A128 08004000 */  jr         $v0
/* 7AB5E5C 8008A12C 00000000 */   nop
.L8008A130_:
/* 7AB5E60 8008A130 5D280208 */  j          .Llevel_37_8008A174
/* 7AB5E64 8008A134 41008424 */   addiu     $a0, $a0, 0x41
.L8008A138_:
/* 7AB5E68 8008A138 5D280208 */  j          .Llevel_37_8008A174
/* 7AB5E6C 8008A13C 55008424 */   addiu     $a0, $a0, 0x55
.L8008A140_:
/* 7AB5E70 8008A140 5D280208 */  j          .Llevel_37_8008A174
/* 7AB5E74 8008A144 64008424 */   addiu     $a0, $a0, 0x64
.L8008A148_:
/* 7AB5E78 8008A148 5D280208 */  j          .Llevel_37_8008A174
/* 7AB5E7C 8008A14C 73008424 */   addiu     $a0, $a0, 0x73
.L8008A150_:
/* 7AB5E80 8008A150 5D280208 */  j          .Llevel_37_8008A174
/* 7AB5E84 8008A154 87008424 */   addiu     $a0, $a0, 0x87
.L8008A158_:
/* 7AB5E88 8008A158 5D280208 */  j          .Llevel_37_8008A174
/* 7AB5E8C 8008A15C 96008424 */   addiu     $a0, $a0, 0x96
.L8008A160_:
/* 7AB5E90 8008A160 5D280208 */  j          .Llevel_37_8008A174
/* 7AB5E94 8008A164 98008424 */   addiu     $a0, $a0, 0x98
.L8008A168_:
/* 7AB5E98 8008A168 5D280208 */  j          .Llevel_37_8008A174
/* 7AB5E9C 8008A16C A0008424 */   addiu     $a0, $a0, 0xA0
.L8008A170_:
/* 7AB5EA0 8008A170 A5008424 */  addiu      $a0, $a0, 0xA5
.Llevel_37_8008A174:
/* 7AB5EA4 8008A174 0780023C */  lui        $v0, %hi(D_80070328 + 0x250)
/* 7AB5EA8 8008A178 7805428C */  lw         $v0, %lo(D_80070328 + 0x250)($v0)
/* 7AB5EAC 8008A17C 00000000 */  nop
/* 7AB5EB0 8008A180 3E005090 */  lbu        $s0, 0x3E($v0)
/* 7AB5EB4 8008A184 68280208 */  j          .Llevel_37_8008A1A0
/* 7AB5EB8 8008A188 2B000224 */   addiu     $v0, $zero, 0x2B
.Llevel_37_8008A18C:
/* 7AB5EBC 8008A18C 0780043C */  lui        $a0, %hi(D_80070328 + 0x14)
/* 7AB5EC0 8008A190 3C038490 */  lbu        $a0, %lo(D_80070328 + 0x14)($a0)
/* 7AB5EC4 8008A194 0780103C */  lui        $s0, %hi(D_80070328 + 0x16)
/* 7AB5EC8 8008A198 3E031092 */  lbu        $s0, %lo(D_80070328 + 0x16)($s0)
/* 7AB5ECC 8008A19C 2B000224 */  addiu      $v0, $zero, 0x2B
.Llevel_37_8008A1A0:
/* 7AB5ED0 8008A1A0 05008210 */  beq        $a0, $v0, .Llevel_37_8008A1B8
/* 7AB5ED4 8008A1A4 3A000224 */   addiu     $v0, $zero, 0x3A
/* 7AB5ED8 8008A1A8 0C008210 */  beq        $a0, $v0, .Llevel_37_8008A1DC
/* 7AB5EDC 8008A1AC 0D000224 */   addiu     $v0, $zero, 0xD
/* 7AB5EE0 8008A1B0 81280208 */  j          .Llevel_37_8008A204
/* 7AB5EE4 8008A1B4 00000000 */   nop
.Llevel_37_8008A1B8:
/* 7AB5EE8 8008A1B8 01000224 */  addiu      $v0, $zero, 0x1
/* 7AB5EEC 8008A1BC 11000216 */  bne        $s0, $v0, .Llevel_37_8008A204
/* 7AB5EF0 8008A1C0 21280000 */   addu      $a1, $zero, $zero
/* 7AB5EF4 8008A1C4 0780023C */  lui        $v0, %hi(D_8006C654)
/* 7AB5EF8 8008A1C8 54C6428C */  lw         $v0, %lo(D_8006C654)($v0)
/* 7AB5EFC 8008A1CC 00000000 */  nop
/* 7AB5F00 8008A1D0 0A004490 */  lbu        $a0, 0xA($v0)
/* 7AB5F04 8008A1D4 7D280208 */  j          .Llevel_37_8008A1F4
/* 7AB5F08 8008A1D8 00000000 */   nop
.Llevel_37_8008A1DC:
/* 7AB5F0C 8008A1DC 09000216 */  bne        $s0, $v0, .Llevel_37_8008A204
/* 7AB5F10 8008A1E0 21280000 */   addu      $a1, $zero, $zero
/* 7AB5F14 8008A1E4 0780023C */  lui        $v0, %hi(D_8006C654)
/* 7AB5F18 8008A1E8 54C6428C */  lw         $v0, %lo(D_8006C654)($v0)
/* 7AB5F1C 8008A1EC 00000000 */  nop
/* 7AB5F20 8008A1F0 0D004490 */  lbu        $a0, 0xD($v0)
.Llevel_37_8008A1F4:
/* 7AB5F24 8008A1F4 D4EE000C */  jal        func_8003BB50
/* 7AB5F28 8008A1F8 21300000 */   addu      $a2, $zero, $zero
/* 7AB5F2C 8008A1FC 0780013C */  lui        $at, %hi(D_80070328 + 0x29C)
/* 7AB5F30 8008A200 C40530AC */  sw         $s0, %lo(D_80070328 + 0x29C)($at)
.Llevel_37_8008A204:
/* 7AB5F34 8008A204 1400BF8F */  lw         $ra, 0x14($sp)
/* 7AB5F38 8008A208 1000B08F */  lw         $s0, 0x10($sp)
/* 7AB5F3C 8008A20C 1800BD27 */  addiu      $sp, $sp, 0x18
/* 7AB5F40 8008A210 0800E003 */  jr         $ra
/* 7AB5F44 8008A214 00000000 */   nop
.size func_level_37_8008A0DC, . - func_level_37_8008A0DC
