.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_18_80074678
/* 4EA73A8 80074678 64C50780 */ .word .L8007C564_
/* 4EA73AC 8007467C 10C60780 */ .word .L8007C610_
/* 4EA73B0 80074680 78C60780 */ .word .L8007C678_
/* 4EA73B4 80074684 74C90780 */ .word .L8007C974_
/* 4EA73B8 80074688 24CB0780 */ .word .L8007CB24_
/* 4EA73BC 8007468C 00000000 */ .word 0x00000000
.size jtbl_level_18_80074678, . - jtbl_level_18_80074678


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_18_8007C2B4
/* 4EAEFE4 8007C2B4 60FFBD27 */  addiu      $sp, $sp, -0xA0
/* 4EAEFE8 8007C2B8 8400B1AF */  sw         $s1, 0x84($sp)
/* 4EAEFEC 8007C2BC 21888000 */  addu       $s1, $a0, $zero
/* 4EAEFF0 8007C2C0 8C00B3AF */  sw         $s3, 0x8C($sp)
/* 4EAEFF4 8007C2C4 0C003326 */  addiu      $s3, $s1, 0xC
/* 4EAEFF8 8007C2C8 0780053C */  lui        $a1, %hi(D_80070328)
/* 4EAEFFC 8007C2CC 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 4EAF000 8007C2D0 9C00BFAF */  sw         $ra, 0x9C($sp)
/* 4EAF004 8007C2D4 9800B6AF */  sw         $s6, 0x98($sp)
/* 4EAF008 8007C2D8 9400B5AF */  sw         $s5, 0x94($sp)
/* 4EAF00C 8007C2DC 9000B4AF */  sw         $s4, 0x90($sp)
/* 4EAF010 8007C2E0 8800B2AF */  sw         $s2, 0x88($sp)
/* 4EAF014 8007C2E4 8000B0AF */  sw         $s0, 0x80($sp)
/* 4EAF018 8007C2E8 0000328E */  lw         $s2, 0x0($s1)
/* 4EAF01C 8007C2EC CD3C010C */  jal        func_8004F334
/* 4EAF020 8007C2F0 21206002 */   addu      $a0, $s3, $zero
/* 4EAF024 8007C2F4 0A004386 */  lh         $v1, 0xA($s2)
/* 4EAF028 8007C2F8 00000000 */  nop
/* 4EAF02C 8007C2FC 21206000 */  addu       $a0, $v1, $zero
/* 4EAF030 8007C300 18026328 */  slti       $v1, $v1, 0x218
/* 4EAF034 8007C304 07006010 */  beqz       $v1, .Llevel_18_8007C324
/* 4EAF038 8007C308 21B04000 */   addu      $s6, $v0, $zero
/* 4EAF03C 8007C30C 0780023C */  lui        $v0, %hi(D_8006C648)
/* 4EAF040 8007C310 48C6428C */  lw         $v0, %lo(D_8006C648)($v0)
/* 4EAF044 8007C314 00000000 */  nop
/* 4EAF048 8007C318 21108200 */  addu       $v0, $a0, $v0
/* 4EAF04C 8007C31C 06F10108 */  j          .Llevel_18_8007C418
/* 4EAF050 8007C320 0A0042A6 */   sh        $v0, 0xA($s2)
.Llevel_18_8007C324:
/* 4EAF054 8007C324 49002492 */  lbu        $a0, 0x49($s1)
/* 4EAF058 8007C328 10BC000C */  jal        func_8002F040
/* 4EAF05C 8007C32C 00000000 */   nop
/* 4EAF060 8007C330 21804000 */  addu       $s0, $v0, $zero
/* 4EAF064 8007C334 2E000012 */  beqz       $s0, .Llevel_18_8007C3F0
/* 4EAF068 8007C338 0030C22A */   slti      $v0, $s6, 0x3000
/* 4EAF06C 8007C33C 10004010 */  beqz       $v0, .Llevel_18_8007C380
/* 4EAF070 8007C340 21200002 */   addu      $a0, $s0, $zero
/* 4EAF074 8007C344 0780023C */  lui        $v0, %hi(D_8006DEF8)
/* 4EAF078 8007C348 F8DE4224 */  addiu      $v0, $v0, %lo(D_8006DEF8)
/* 4EAF07C 8007C34C 23100202 */  subu       $v0, $s0, $v0
/* 4EAF080 8007C350 0A004396 */  lhu        $v1, 0xA($s2)
/* 4EAF084 8007C354 03110200 */  sra        $v0, $v0, 4
/* 4EAF088 8007C358 130042A2 */  sb         $v0, 0x13($s2)
/* 4EAF08C 8007C35C E0FF6324 */  addiu      $v1, $v1, -0x20
/* 4EAF090 8007C360 9171010C */  jal        func_8005C644
/* 4EAF094 8007C364 0A0043A6 */   sh        $v1, 0xA($s2)
/* 4EAF098 8007C368 49002392 */  lbu        $v1, 0x49($s1)
/* 4EAF09C 8007C36C 01004230 */  andi       $v0, $v0, 0x1
/* 4EAF0A0 8007C370 40180300 */  sll        $v1, $v1, 1
/* 4EAF0A4 8007C374 21186200 */  addu       $v1, $v1, $v0
/* 4EAF0A8 8007C378 F5F00108 */  j          .Llevel_18_8007C3D4
/* 4EAF0AC 8007C37C 140043A2 */   sb        $v1, 0x14($s2)
.Llevel_18_8007C380:
/* 4EAF0B0 8007C380 5E3C010C */  jal        func_8004F178
/* 4EAF0B4 8007C384 21286002 */   addu      $a1, $s3, $zero
/* 4EAF0B8 8007C388 FF7F0224 */  addiu      $v0, $zero, 0x7FFF
/* 4EAF0BC 8007C38C 2A105600 */  slt        $v0, $v0, $s6
/* 4EAF0C0 8007C390 0A004014 */  bnez       $v0, .Llevel_18_8007C3BC
/* 4EAF0C4 8007C394 00000000 */   nop
/* 4EAF0C8 8007C398 0A004296 */  lhu        $v0, 0xA($s2)
/* 4EAF0CC 8007C39C 00000000 */  nop
/* 4EAF0D0 8007C3A0 80FF4224 */  addiu      $v0, $v0, -0x80
/* 4EAF0D4 8007C3A4 0A0042A6 */  sh         $v0, 0xA($s2)
/* 4EAF0D8 8007C3A8 0800028E */  lw         $v0, 0x8($s0)
/* 4EAF0DC 8007C3AC 00000000 */  nop
/* 4EAF0E0 8007C3B0 80004224 */  addiu      $v0, $v0, 0x80
/* 4EAF0E4 8007C3B4 F3F00108 */  j          .Llevel_18_8007C3CC
/* 4EAF0E8 8007C3B8 080002AE */   sw        $v0, 0x8($s0)
.Llevel_18_8007C3BC:
/* 4EAF0EC 8007C3BC 0A004296 */  lhu        $v0, 0xA($s2)
/* 4EAF0F0 8007C3C0 00000000 */  nop
/* 4EAF0F4 8007C3C4 00FF4224 */  addiu      $v0, $v0, -0x100
/* 4EAF0F8 8007C3C8 0A0042A6 */  sh         $v0, 0xA($s2)
.Llevel_18_8007C3CC:
/* 4EAF0FC 8007C3CC FF000224 */  addiu      $v0, $zero, 0xFF
/* 4EAF100 8007C3D0 130042A2 */  sb         $v0, 0x13($s2)
.Llevel_18_8007C3D4:
/* 4EAF104 8007C3D4 9171010C */  jal        func_8005C644
/* 4EAF108 8007C3D8 00000000 */   nop
/* 4EAF10C 8007C3DC 0D000392 */  lbu        $v1, 0xD($s0)
/* 4EAF110 8007C3E0 3F004230 */  andi       $v0, $v0, 0x3F
/* 4EAF114 8007C3E4 21186200 */  addu       $v1, $v1, $v0
/* 4EAF118 8007C3E8 00F10108 */  j          .Llevel_18_8007C400
/* 4EAF11C 8007C3EC 0D0003A2 */   sb        $v1, 0xD($s0)
.Llevel_18_8007C3F0:
/* 4EAF120 8007C3F0 0A004296 */  lhu        $v0, 0xA($s2)
/* 4EAF124 8007C3F4 00000000 */  nop
/* 4EAF128 8007C3F8 00FF4224 */  addiu      $v0, $v0, -0x100
/* 4EAF12C 8007C3FC 0A0042A6 */  sh         $v0, 0xA($s2)
.Llevel_18_8007C400:
/* 4EAF130 8007C400 9171010C */  jal        func_8005C644
/* 4EAF134 8007C404 00000000 */   nop
/* 4EAF138 8007C408 0A004396 */  lhu        $v1, 0xA($s2)
/* 4EAF13C 8007C40C FF004230 */  andi       $v0, $v0, 0xFF
/* 4EAF140 8007C410 23186200 */  subu       $v1, $v1, $v0
/* 4EAF144 8007C414 0A0043A6 */  sh         $v1, 0xA($s2)
.Llevel_18_8007C418:
/* 4EAF148 8007C418 13005092 */  lbu        $s0, 0x13($s2)
/* 4EAF14C 8007C41C 00000000 */  nop
/* 4EAF150 8007C420 1000022E */  sltiu      $v0, $s0, 0x10
/* 4EAF154 8007C424 22004010 */  beqz       $v0, .Llevel_18_8007C4B0
/* 4EAF158 8007C428 21202002 */   addu      $a0, $s1, $zero
/* 4EAF15C 8007C42C 04000524 */  addiu      $a1, $zero, 0x4
/* 4EAF160 8007C430 00811000 */  sll        $s0, $s0, 4
/* 4EAF164 8007C434 0780023C */  lui        $v0, %hi(D_8006DEF8)
/* 4EAF168 8007C438 F8DE4224 */  addiu      $v0, $v0, %lo(D_8006DEF8)
/* 4EAF16C 8007C43C 4957010C */  jal        func_80055D24
/* 4EAF170 8007C440 21800202 */   addu      $s0, $s0, $v0
/* 4EAF174 8007C444 14004292 */  lbu        $v0, 0x14($s2)
/* 4EAF178 8007C448 21200002 */  addu       $a0, $s0, $zero
/* 4EAF17C 8007C44C 40280200 */  sll        $a1, $v0, 1
/* 4EAF180 8007C450 2128A200 */  addu       $a1, $a1, $v0
/* 4EAF184 8007C454 80280500 */  sll        $a1, $a1, 2
/* 4EAF188 8007C458 0680023C */  lui        $v0, %hi(D_80066A48 + 0x30)
/* 4EAF18C 8007C45C 786A4224 */  addiu      $v0, $v0, %lo(D_80066A48 + 0x30)
/* 4EAF190 8007C460 5E3C010C */  jal        func_8004F178
/* 4EAF194 8007C464 2128A200 */   addu      $a1, $a1, $v0
/* 4EAF198 8007C468 21200002 */  addu       $a0, $s0, $zero
/* 4EAF19C 8007C46C 21280002 */  addu       $a1, $s0, $zero
/* 4EAF1A0 8007C470 7F3C010C */  jal        func_8004F1FC
/* 4EAF1A4 8007C474 02000624 */   addiu     $a2, $zero, 0x2
/* 4EAF1A8 8007C478 20002426 */  addiu      $a0, $s1, 0x20
/* 4EAF1AC 8007C47C 21280002 */  addu       $a1, $s0, $zero
/* 4EAF1B0 8007C480 5B3B010C */  jal        func_8004ED6C
/* 4EAF1B4 8007C484 21300002 */   addu      $a2, $s0, $zero
/* 4EAF1B8 8007C488 21200002 */  addu       $a0, $s0, $zero
/* 4EAF1BC 8007C48C 21280002 */  addu       $a1, $s0, $zero
/* 4EAF1C0 8007C490 653C010C */  jal        func_8004F194
/* 4EAF1C4 8007C494 0C002626 */   addiu     $a2, $s1, 0xC
/* 4EAF1C8 8007C498 0C000292 */  lbu        $v0, 0xC($s0)
/* 4EAF1CC 8007C49C 00000000 */  nop
/* 4EAF1D0 8007C4A0 0400422C */  sltiu      $v0, $v0, 0x4
/* 4EAF1D4 8007C4A4 02004010 */  beqz       $v0, .Llevel_18_8007C4B0
/* 4EAF1D8 8007C4A8 FF000224 */   addiu     $v0, $zero, 0xFF
/* 4EAF1DC 8007C4AC 130042A2 */  sb         $v0, 0x13($s2)
.Llevel_18_8007C4B0:
/* 4EAF1E0 8007C4B0 4D002292 */  lbu        $v0, 0x4D($s1)
/* 4EAF1E4 8007C4B4 00000000 */  nop
/* 4EAF1E8 8007C4B8 0B004014 */  bnez       $v0, .Llevel_18_8007C4E8
/* 4EAF1EC 8007C4BC 0118C22A */   slti      $v0, $s6, 0x1801
/* 4EAF1F0 8007C4C0 09004014 */  bnez       $v0, .Llevel_18_8007C4E8
/* 4EAF1F4 8007C4C4 01000224 */   addiu     $v0, $zero, 0x1
/* 4EAF1F8 8007C4C8 48002392 */  lbu        $v1, 0x48($s1)
/* 4EAF1FC 8007C4CC 00000000 */  nop
/* 4EAF200 8007C4D0 05006214 */  bne        $v1, $v0, .Llevel_18_8007C4E8
/* 4EAF204 8007C4D4 00000000 */   nop
/* 4EAF208 8007C4D8 11004292 */  lbu        $v0, 0x11($s2)
/* 4EAF20C 8007C4DC 00000000 */  nop
/* 4EAF210 8007C4E0 CC014010 */  beqz       $v0, .Llevel_18_8007CC14
/* 4EAF214 8007C4E4 00000000 */   nop
.Llevel_18_8007C4E8:
/* 4EAF218 8007C4E8 0680043C */  lui        $a0, %hi(D_800676E8)
/* 4EAF21C 8007C4EC E8768424 */  addiu      $a0, $a0, %lo(D_800676E8)
/* 4EAF220 8007C4F0 0780033C */  lui        $v1, %hi(D_8006C58C)
/* 4EAF224 8007C4F4 8CC5638C */  lw         $v1, %lo(D_8006C58C)($v1)
/* 4EAF228 8007C4F8 0780023C */  lui        $v0, %hi(D_8006C5C8)
/* 4EAF22C 8007C4FC C8C5428C */  lw         $v0, %lo(D_8006C5C8)($v0)
/* 4EAF230 8007C500 00190300 */  sll        $v1, $v1, 4
/* 4EAF234 8007C504 21186400 */  addu       $v1, $v1, $a0
/* 4EAF238 8007C508 80100200 */  sll        $v0, $v0, 2
/* 4EAF23C 8007C50C 21104300 */  addu       $v0, $v0, $v1
/* 4EAF240 8007C510 1400238E */  lw         $v1, 0x14($s1)
/* 4EAF244 8007C514 0000428C */  lw         $v0, 0x0($v0)
/* 4EAF248 8007C518 00000000 */  nop
/* 4EAF24C 8007C51C 2A104300 */  slt        $v0, $v0, $v1
/* 4EAF250 8007C520 05004014 */  bnez       $v0, .Llevel_18_8007C538
/* 4EAF254 8007C524 00000000 */   nop
/* 4EAF258 8007C528 0780053C */  lui        $a1, %hi(D_80070328)
/* 4EAF25C 8007C52C 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 4EAF260 8007C530 5E3C010C */  jal        func_8004F178
/* 4EAF264 8007C534 0C002426 */   addiu     $a0, $s1, 0xC
.Llevel_18_8007C538:
/* 4EAF268 8007C538 48002392 */  lbu        $v1, 0x48($s1)
/* 4EAF26C 8007C53C 00000000 */  nop
/* 4EAF270 8007C540 0500622C */  sltiu      $v0, $v1, 0x5
/* 4EAF274 8007C544 92014010 */  beqz       $v0, .Llevel_18_8007CB90
/* 4EAF278 8007C548 80100300 */   sll       $v0, $v1, 2
/* 4EAF27C 8007C54C 0780013C */  lui        $at, %hi(jtbl_level_18_80074678)
/* 4EAF280 8007C550 21082200 */  addu       $at, $at, $v0
/* 4EAF284 8007C554 7846228C */  lw         $v0, %lo(jtbl_level_18_80074678)($at)
/* 4EAF288 8007C558 00000000 */  nop
/* 4EAF28C 8007C55C 08004000 */  jr         $v0
/* 4EAF290 8007C560 00000000 */   nop
.L8007C564_:
/* 4EAF294 8007C564 1000A427 */  addiu      $a0, $sp, 0x10
/* 4EAF298 8007C568 5E3C010C */  jal        func_8004F178
/* 4EAF29C 8007C56C 0C002526 */   addiu     $a1, $s1, 0xC
/* 4EAF2A0 8007C570 1000A427 */  addiu      $a0, $sp, 0x10
/* 4EAF2A4 8007C574 1800A28F */  lw         $v0, 0x18($sp)
/* 4EAF2A8 8007C578 0100053C */  lui        $a1, (0x10000 >> 16)
/* 4EAF2AC 8007C57C 00044224 */  addiu      $v0, $v0, 0x400
/* 4EAF2B0 8007C580 D668000C */  jal        func_8001A358
/* 4EAF2B4 8007C584 1800A2AF */   sw        $v0, 0x18($sp)
/* 4EAF2B8 8007C588 62D8000C */  jal        func_80036188
/* 4EAF2BC 8007C58C 0E004426 */   addiu     $a0, $s2, 0xE
/* 4EAF2C0 8007C590 0C00428E */  lw         $v0, 0xC($s2)
/* 4EAF2C4 8007C594 FFFF033C */  lui        $v1, (0xFFFF0000 >> 16)
/* 4EAF2C8 8007C598 24104300 */  and        $v0, $v0, $v1
/* 4EAF2CC 8007C59C 02004010 */  beqz       $v0, .Llevel_18_8007C5A8
/* 4EAF2D0 8007C5A0 00000000 */   nop
/* 4EAF2D4 8007C5A4 460020A2 */  sb         $zero, 0x46($s1)
.Llevel_18_8007C5A8:
/* 4EAF2D8 8007C5A8 0780023C */  lui        $v0, %hi(D_80071908)
/* 4EAF2DC 8007C5AC 0819428C */  lw         $v0, %lo(D_80071908)($v0)
/* 4EAF2E0 8007C5B0 9171010C */  jal        func_8005C644
/* 4EAF2E4 8007C5B4 140022AE */   sw        $v0, 0x14($s1)
/* 4EAF2E8 8007C5B8 FF004230 */  andi       $v0, $v0, 0xFF
/* 4EAF2EC 8007C5BC 00014224 */  addiu      $v0, $v0, 0x100
/* 4EAF2F0 8007C5C0 0A0042A6 */  sh         $v0, 0xA($s2)
/* 4EAF2F4 8007C5C4 50002392 */  lbu        $v1, 0x50($s1)
/* 4EAF2F8 8007C5C8 01000224 */  addiu      $v0, $zero, 0x1
/* 4EAF2FC 8007C5CC 480022A2 */  sb         $v0, 0x48($s1)
/* 4EAF300 8007C5D0 0680013C */  lui        $at, %hi(D_80066964)
/* 4EAF304 8007C5D4 21082300 */  addu       $at, $at, $v1
/* 4EAF308 8007C5D8 64692290 */  lbu        $v0, %lo(D_80066964)($at)
/* 4EAF30C 8007C5DC 00000000 */  nop
/* 4EAF310 8007C5E0 490022A2 */  sb         $v0, 0x49($s1)
/* 4EAF314 8007C5E4 FF004230 */  andi       $v0, $v0, 0xFF
/* 4EAF318 8007C5E8 0680013C */  lui        $at, %hi(D_80066988)
/* 4EAF31C 8007C5EC 21082200 */  addu       $at, $at, $v0
/* 4EAF320 8007C5F0 88692290 */  lbu        $v0, %lo(D_80066988)($at)
/* 4EAF324 8007C5F4 49002392 */  lbu        $v1, 0x49($s1)
/* 4EAF328 8007C5F8 3C0022A2 */  sb         $v0, 0x3C($s1)
/* 4EAF32C 8007C5FC 0680013C */  lui        $at, %hi(D_80066990)
/* 4EAF330 8007C600 21082300 */  addu       $at, $at, $v1
/* 4EAF334 8007C604 90692290 */  lbu        $v0, %lo(D_80066990)($at)
/* 4EAF338 8007C608 E4F20108 */  j          .Llevel_18_8007CB90
/* 4EAF33C 8007C60C 540022A2 */   sb        $v0, 0x54($s1)
.L8007C610_:
/* 4EAF340 8007C610 0A004286 */  lh         $v0, 0xA($s2)
/* 4EAF344 8007C614 00000000 */  nop
/* 4EAF348 8007C618 1E004228 */  slti       $v0, $v0, 0x1E
/* 4EAF34C 8007C61C 5C014014 */  bnez       $v0, .Llevel_18_8007CB90
/* 4EAF350 8007C620 00000000 */   nop
/* 4EAF354 8007C624 0780043C */  lui        $a0, %hi(D_80070328 + 0x44)
/* 4EAF358 8007C628 6C03848C */  lw         $a0, %lo(D_80070328 + 0x44)($a0)
/* 4EAF35C 8007C62C 00000000 */  nop
/* 4EAF360 8007C630 80018224 */  addiu      $v0, $a0, 0x180
/* 4EAF364 8007C634 2A10C202 */  slt        $v0, $s6, $v0
/* 4EAF368 8007C638 55014010 */  beqz       $v0, .Llevel_18_8007CB90
/* 4EAF36C 8007C63C 00000000 */   nop
/* 4EAF370 8007C640 0780033C */  lui        $v1, %hi(D_80070328 + 8)
/* 4EAF374 8007C644 3003638C */  lw         $v1, %lo(D_80070328 + 8)($v1)
/* 4EAF378 8007C648 1400228E */  lw         $v0, 0x14($s1)
/* 4EAF37C 8007C64C 00000000 */  nop
/* 4EAF380 8007C650 23186200 */  subu       $v1, $v1, $v0
/* 4EAF384 8007C654 80008224 */  addiu      $v0, $a0, 0x80
/* 4EAF388 8007C658 2A106200 */  slt        $v0, $v1, $v0
/* 4EAF38C 8007C65C 4C014010 */  beqz       $v0, .Llevel_18_8007CB90
/* 4EAF390 8007C660 23100400 */   negu      $v0, $a0
/* 4EAF394 8007C664 2A104300 */  slt        $v0, $v0, $v1
/* 4EAF398 8007C668 49014010 */  beqz       $v0, .Llevel_18_8007CB90
/* 4EAF39C 8007C66C 04000224 */   addiu     $v0, $zero, 0x4
/* 4EAF3A0 8007C670 C7F20108 */  j          .Llevel_18_8007CB1C
/* 4EAF3A4 8007C674 00000000 */   nop
.L8007C678_:
/* 4EAF3A8 8007C678 2000B327 */  addiu      $s3, $sp, 0x20
/* 4EAF3AC 8007C67C 21206002 */  addu       $a0, $s3, $zero
/* 4EAF3B0 8007C680 553D010C */  jal        func_8004F554
/* 4EAF3B4 8007C684 04004526 */   addiu     $a1, $s2, 0x4
/* 4EAF3B8 8007C688 21206002 */  addu       $a0, $s3, $zero
/* 4EAF3BC 8007C68C 0780063C */  lui        $a2, %hi(D_8006C648)
/* 4EAF3C0 8007C690 48C6C68C */  lw         $a2, %lo(D_8006C648)($a2)
/* 4EAF3C4 8007C694 7F3C010C */  jal        func_8004F1FC
/* 4EAF3C8 8007C698 21286002 */   addu      $a1, $s3, $zero
/* 4EAF3CC 8007C69C 21206002 */  addu       $a0, $s3, $zero
/* 4EAF3D0 8007C6A0 443C010C */  jal        func_8004F110
/* 4EAF3D4 8007C6A4 01000524 */   addiu     $a1, $zero, 0x1
/* 4EAF3D8 8007C6A8 21206002 */  addu       $a0, $s3, $zero
/* 4EAF3DC 8007C6AC 0C003426 */  addiu      $s4, $s1, 0xC
/* 4EAF3E0 8007C6B0 21288002 */  addu       $a1, $s4, $zero
/* 4EAF3E4 8007C6B4 653C010C */  jal        func_8004F194
/* 4EAF3E8 8007C6B8 21306002 */   addu      $a2, $s3, $zero
/* 4EAF3EC 8007C6BC 08004286 */  lh         $v0, 0x8($s2)
/* 4EAF3F0 8007C6C0 00000000 */  nop
/* 4EAF3F4 8007C6C4 21204000 */  addu       $a0, $v0, $zero
/* 4EAF3F8 8007C6C8 29FF4228 */  slti       $v0, $v0, -0xD7
/* 4EAF3FC 8007C6CC 08004014 */  bnez       $v0, .Llevel_18_8007C6F0
/* 4EAF400 8007C6D0 00000000 */   nop
/* 4EAF404 8007C6D4 0780033C */  lui        $v1, %hi(D_8006C648)
/* 4EAF408 8007C6D8 48C6638C */  lw         $v1, %lo(D_8006C648)($v1)
/* 4EAF40C 8007C6DC 00000000 */  nop
/* 4EAF410 8007C6E0 80100300 */  sll        $v0, $v1, 2
/* 4EAF414 8007C6E4 21104300 */  addu       $v0, $v0, $v1
/* 4EAF418 8007C6E8 23108200 */  subu       $v0, $a0, $v0
/* 4EAF41C 8007C6EC 080042A6 */  sh         $v0, 0x8($s2)
.Llevel_18_8007C6F0:
/* 4EAF420 8007C6F0 2800A38F */  lw         $v1, 0x28($sp)
/* 4EAF424 8007C6F4 00000000 */  nop
/* 4EAF428 8007C6F8 00046228 */  slti       $v0, $v1, 0x400
/* 4EAF42C 8007C6FC 07004010 */  beqz       $v0, .Llevel_18_8007C71C
/* 4EAF430 8007C700 F0006224 */   addiu     $v0, $v1, 0xF0
/* 4EAF434 8007C704 98DB000C */  jal        func_80036E60
/* 4EAF438 8007C708 21202002 */   addu      $a0, $s1, $zero
/* 4EAF43C 8007C70C C656010C */  jal        func_80055B18
/* 4EAF440 8007C710 21202002 */   addu      $a0, $s1, $zero
/* 4EAF444 8007C714 05F30108 */  j          .Llevel_18_8007CC14
/* 4EAF448 8007C718 00000000 */   nop
.Llevel_18_8007C71C:
/* 4EAF44C 8007C71C 2800A2AF */  sw         $v0, 0x28($sp)
/* 4EAF450 8007C720 21206002 */  addu       $a0, $s3, $zero
/* 4EAF454 8007C724 6564000C */  jal        func_80019194
/* 4EAF458 8007C728 F0000524 */   addiu     $a1, $zero, 0xF0
/* 4EAF45C 8007C72C 6D004010 */  beqz       $v0, .Llevel_18_8007C8E4
/* 4EAF460 8007C730 3000B527 */   addiu     $s5, $sp, 0x30
/* 4EAF464 8007C734 2120A002 */  addu       $a0, $s5, $zero
/* 4EAF468 8007C738 0780103C */  lui        $s0, %hi(D_80071918)
/* 4EAF46C 8007C73C 18191026 */  addiu      $s0, $s0, %lo(D_80071918)
/* 4EAF470 8007C740 5E3C010C */  jal        func_8004F178
/* 4EAF474 8007C744 21280002 */   addu      $a1, $s0, $zero
/* 4EAF478 8007C748 21208002 */  addu       $a0, $s4, $zero
/* 4EAF47C 8007C74C 5E3C010C */  jal        func_8004F178
/* 4EAF480 8007C750 F4FF0526 */   addiu     $a1, $s0, -0xC
/* 4EAF484 8007C754 1400228E */  lw         $v0, 0x14($s1)
/* 4EAF488 8007C758 00000000 */  nop
/* 4EAF48C 8007C75C 10FF4224 */  addiu      $v0, $v0, -0xF0
/* 4EAF490 8007C760 140022AE */  sw         $v0, 0x14($s1)
/* 4EAF494 8007C764 12004292 */  lbu        $v0, 0x12($s2)
/* 4EAF498 8007C768 00000000 */  nop
/* 4EAF49C 8007C76C 32004014 */  bnez       $v0, .Llevel_18_8007C838
/* 4EAF4A0 8007C770 4000B027 */   addiu     $s0, $sp, 0x40
/* 4EAF4A4 8007C774 21206002 */  addu       $a0, $s3, $zero
/* 4EAF4A8 8007C778 D668000C */  jal        func_8001A358
/* 4EAF4AC 8007C77C 00040524 */   addiu     $a1, $zero, 0x400
/* 4EAF4B0 8007C780 2120A002 */  addu       $a0, $s5, $zero
/* 4EAF4B4 8007C784 21280000 */  addu       $a1, $zero, $zero
/* 4EAF4B8 8007C788 7A3B010C */  jal        func_8004EDE8
/* 4EAF4BC 8007C78C 21804000 */   addu      $s0, $v0, $zero
/* 4EAF4C0 8007C790 21284000 */  addu       $a1, $v0, $zero
/* 4EAF4C4 8007C794 3800A48F */  lw         $a0, 0x38($sp)
/* 4EAF4C8 8007C798 203A010C */  jal        func_8004E880
/* 4EAF4CC 8007C79C 21300000 */   addu      $a2, $zero, $zero
/* 4EAF4D0 8007C7A0 00160200 */  sll        $v0, $v0, 24
/* 4EAF4D4 8007C7A4 2800A38F */  lw         $v1, 0x28($sp)
/* 4EAF4D8 8007C7A8 00000000 */  nop
/* 4EAF4DC 8007C7AC 70FE6324 */  addiu      $v1, $v1, -0x190
/* 4EAF4E0 8007C7B0 2A187000 */  slt        $v1, $v1, $s0
/* 4EAF4E4 8007C7B4 18006010 */  beqz       $v1, .Llevel_18_8007C818
/* 4EAF4E8 8007C7B8 03160200 */   sra       $v0, $v0, 24
/* 4EAF4EC 8007C7BC 18004228 */  slti       $v0, $v0, 0x18
/* 4EAF4F0 8007C7C0 15004010 */  beqz       $v0, .Llevel_18_8007C818
/* 4EAF4F4 8007C7C4 21208002 */   addu      $a0, $s4, $zero
/* 4EAF4F8 8007C7C8 21286002 */  addu       $a1, $s3, $zero
/* 4EAF4FC 8007C7CC 01000224 */  addiu      $v0, $zero, 0x1
/* 4EAF500 8007C7D0 5E3C010C */  jal        func_8004F178
/* 4EAF504 8007C7D4 480022A2 */   sb        $v0, 0x48($s1)
/* 4EAF508 8007C7D8 0E004426 */  addiu      $a0, $s2, 0xE
/* 4EAF50C 8007C7DC 62D8000C */  jal        func_80036188
/* 4EAF510 8007C7E0 140030AE */   sw        $s0, 0x14($s1)
/* 4EAF514 8007C7E4 0C00428E */  lw         $v0, 0xC($s2)
/* 4EAF518 8007C7E8 FFFF033C */  lui        $v1, (0xFFFF0000 >> 16)
/* 4EAF51C 8007C7EC 24104300 */  and        $v0, $v0, $v1
/* 4EAF520 8007C7F0 02004010 */  beqz       $v0, .Llevel_18_8007C7FC
/* 4EAF524 8007C7F4 00000000 */   nop
/* 4EAF528 8007C7F8 460020A2 */  sb         $zero, 0x46($s1)
.Llevel_18_8007C7FC:
/* 4EAF52C 8007C7FC 520020A2 */  sb         $zero, 0x52($s1)
/* 4EAF530 8007C800 9C58010C */  jal        func_80056270
/* 4EAF534 8007C804 21202002 */   addu      $a0, $s1, $zero
/* 4EAF538 8007C808 A758010C */  jal        func_8005629C
/* 4EAF53C 8007C80C 21202002 */   addu      $a0, $s1, $zero
/* 4EAF540 8007C810 0AF20108 */  j          .Llevel_18_8007C828
/* 4EAF544 8007C814 00000000 */   nop
.Llevel_18_8007C818:
/* 4EAF548 8007C818 12004292 */  lbu        $v0, 0x12($s2)
/* 4EAF54C 8007C81C 00000000 */  nop
/* 4EAF550 8007C820 01004224 */  addiu      $v0, $v0, 0x1
/* 4EAF554 8007C824 120042A2 */  sb         $v0, 0x12($s2)
.Llevel_18_8007C828:
/* 4EAF558 8007C828 12004292 */  lbu        $v0, 0x12($s2)
/* 4EAF55C 8007C82C 00000000 */  nop
/* 4EAF560 8007C830 37004010 */  beqz       $v0, .Llevel_18_8007C910
/* 4EAF564 8007C834 4000B027 */   addiu     $s0, $sp, 0x40
.Llevel_18_8007C838:
/* 4EAF568 8007C838 21200002 */  addu       $a0, $s0, $zero
/* 4EAF56C 8007C83C 04005326 */  addiu      $s3, $s2, 0x4
/* 4EAF570 8007C840 553D010C */  jal        func_8004F554
/* 4EAF574 8007C844 21286002 */   addu      $a1, $s3, $zero
/* 4EAF578 8007C848 21200002 */  addu       $a0, $s0, $zero
/* 4EAF57C 8007C84C 3000A527 */  addiu      $a1, $sp, 0x30
/* 4EAF580 8007C850 DD3B010C */  jal        func_8004EF74
/* 4EAF584 8007C854 21300002 */   addu      $a2, $s0, $zero
/* 4EAF588 8007C858 1E004010 */  beqz       $v0, .Llevel_18_8007C8D4
/* 4EAF58C 8007C85C 21206002 */   addu      $a0, $s3, $zero
/* 4EAF590 8007C860 12004292 */  lbu        $v0, 0x12($s2)
/* 4EAF594 8007C864 00000000 */  nop
/* 4EAF598 8007C868 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 4EAF59C 8007C86C 9171010C */  jal        func_8005C644
/* 4EAF5A0 8007C870 120042A2 */   sb        $v0, 0x12($s2)
/* 4EAF5A4 8007C874 4000A38F */  lw         $v1, 0x40($sp)
/* 4EAF5A8 8007C878 3F004230 */  andi       $v0, $v0, 0x3F
/* 4EAF5AC 8007C87C C3180300 */  sra        $v1, $v1, 3
/* 4EAF5B0 8007C880 21186200 */  addu       $v1, $v1, $v0
/* 4EAF5B4 8007C884 E0FF6324 */  addiu      $v1, $v1, -0x20
/* 4EAF5B8 8007C888 9171010C */  jal        func_8005C644
/* 4EAF5BC 8007C88C 4000A3AF */   sw        $v1, 0x40($sp)
/* 4EAF5C0 8007C890 4400A38F */  lw         $v1, 0x44($sp)
/* 4EAF5C4 8007C894 3F004230 */  andi       $v0, $v0, 0x3F
/* 4EAF5C8 8007C898 C3180300 */  sra        $v1, $v1, 3
/* 4EAF5CC 8007C89C 21186200 */  addu       $v1, $v1, $v0
/* 4EAF5D0 8007C8A0 E0FF6324 */  addiu      $v1, $v1, -0x20
/* 4EAF5D4 8007C8A4 9171010C */  jal        func_8005C644
/* 4EAF5D8 8007C8A8 4400A3AF */   sw        $v1, 0x44($sp)
/* 4EAF5DC 8007C8AC 21202002 */  addu       $a0, $s1, $zero
/* 4EAF5E0 8007C8B0 01000524 */  addiu      $a1, $zero, 0x1
/* 4EAF5E4 8007C8B4 21300000 */  addu       $a2, $zero, $zero
/* 4EAF5E8 8007C8B8 4800A38F */  lw         $v1, 0x48($sp)
/* 4EAF5EC 8007C8BC 0F004230 */  andi       $v0, $v0, 0xF
/* 4EAF5F0 8007C8C0 83180300 */  sra        $v1, $v1, 2
/* 4EAF5F4 8007C8C4 21186200 */  addu       $v1, $v1, $v0
/* 4EAF5F8 8007C8C8 AFEE000C */  jal        func_8003BABC
/* 4EAF5FC 8007C8CC 4800A3AF */   sw        $v1, 0x48($sp)
/* 4EAF600 8007C8D0 21206002 */  addu       $a0, $s3, $zero
.Llevel_18_8007C8D4:
/* 4EAF604 8007C8D4 5C3D010C */  jal        func_8004F570
/* 4EAF608 8007C8D8 21280002 */   addu      $a1, $s0, $zero
/* 4EAF60C 8007C8DC 44F20108 */  j          .Llevel_18_8007C910
/* 4EAF610 8007C8E0 00000000 */   nop
.Llevel_18_8007C8E4:
/* 4EAF614 8007C8E4 21208002 */  addu       $a0, $s4, $zero
/* 4EAF618 8007C8E8 2800A28F */  lw         $v0, 0x28($sp)
/* 4EAF61C 8007C8EC 21286002 */  addu       $a1, $s3, $zero
/* 4EAF620 8007C8F0 10FF4224 */  addiu      $v0, $v0, -0xF0
/* 4EAF624 8007C8F4 5E3C010C */  jal        func_8004F178
/* 4EAF628 8007C8F8 2800A2AF */   sw        $v0, 0x28($sp)
/* 4EAF62C 8007C8FC 21206002 */  addu       $a0, $s3, $zero
/* 4EAF630 8007C900 D668000C */  jal        func_8001A358
/* 4EAF634 8007C904 0100053C */   lui       $a1, (0x10000 >> 16)
/* 4EAF638 8007C908 A758010C */  jal        func_8005629C
/* 4EAF63C 8007C90C 21202002 */   addu      $a0, $s1, $zero
.Llevel_18_8007C910:
/* 4EAF640 8007C910 0A004286 */  lh         $v0, 0xA($s2)
/* 4EAF644 8007C914 00000000 */  nop
/* 4EAF648 8007C918 1E004228 */  slti       $v0, $v0, 0x1E
/* 4EAF64C 8007C91C 9C004014 */  bnez       $v0, .Llevel_18_8007CB90
/* 4EAF650 8007C920 00000000 */   nop
/* 4EAF654 8007C924 0780053C */  lui        $a1, %hi(D_80070328 + 0x44)
/* 4EAF658 8007C928 6C03A58C */  lw         $a1, %lo(D_80070328 + 0x44)($a1)
/* 4EAF65C 8007C92C 00000000 */  nop
/* 4EAF660 8007C930 8000A424 */  addiu      $a0, $a1, 0x80
/* 4EAF664 8007C934 2A10C402 */  slt        $v0, $s6, $a0
/* 4EAF668 8007C938 95004010 */  beqz       $v0, .Llevel_18_8007CB90
/* 4EAF66C 8007C93C 00000000 */   nop
/* 4EAF670 8007C940 0780023C */  lui        $v0, %hi(D_80070328 + 8)
/* 4EAF674 8007C944 3003428C */  lw         $v0, %lo(D_80070328 + 8)($v0)
/* 4EAF678 8007C948 1400238E */  lw         $v1, 0x14($s1)
/* 4EAF67C 8007C94C 00000000 */  nop
/* 4EAF680 8007C950 23184300 */  subu       $v1, $v0, $v1
/* 4EAF684 8007C954 2A106400 */  slt        $v0, $v1, $a0
/* 4EAF688 8007C958 8D004010 */  beqz       $v0, .Llevel_18_8007CB90
/* 4EAF68C 8007C95C 23100500 */   negu      $v0, $a1
/* 4EAF690 8007C960 2A104300 */  slt        $v0, $v0, $v1
/* 4EAF694 8007C964 8A004010 */  beqz       $v0, .Llevel_18_8007CB90
/* 4EAF698 8007C968 04000224 */   addiu     $v0, $zero, 0x4
/* 4EAF69C 8007C96C C7F20108 */  j          .Llevel_18_8007CB1C
/* 4EAF6A0 8007C970 00000000 */   nop
.L8007C974_:
/* 4EAF6A4 8007C974 6000B327 */  addiu      $s3, $sp, 0x60
/* 4EAF6A8 8007C978 21206002 */  addu       $a0, $s3, $zero
/* 4EAF6AC 8007C97C 553D010C */  jal        func_8004F554
/* 4EAF6B0 8007C980 04004526 */   addiu     $a1, $s2, 0x4
/* 4EAF6B4 8007C984 0A004286 */  lh         $v0, 0xA($s2)
/* 4EAF6B8 8007C988 00000000 */  nop
/* 4EAF6BC 8007C98C 1E004228 */  slti       $v0, $v0, 0x1E
/* 4EAF6C0 8007C990 07004014 */  bnez       $v0, .Llevel_18_8007C9B0
/* 4EAF6C4 8007C994 5000B027 */   addiu     $s0, $sp, 0x50
/* 4EAF6C8 8007C998 0780053C */  lui        $a1, %hi(D_80070328)
/* 4EAF6CC 8007C99C 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 4EAF6D0 8007C9A0 5E3C010C */  jal        func_8004F178
/* 4EAF6D4 8007C9A4 0C002426 */   addiu     $a0, $s1, 0xC
/* 4EAF6D8 8007C9A8 9CF20108 */  j          .Llevel_18_8007CA70
/* 4EAF6DC 8007C9AC 00000000 */   nop
.Llevel_18_8007C9B0:
/* 4EAF6E0 8007C9B0 21200002 */  addu       $a0, $s0, $zero
/* 4EAF6E4 8007C9B4 0780143C */  lui        $s4, %hi(D_80070328)
/* 4EAF6E8 8007C9B8 28039426 */  addiu      $s4, $s4, %lo(D_80070328)
/* 4EAF6EC 8007C9BC 21288002 */  addu       $a1, $s4, $zero
/* 4EAF6F0 8007C9C0 723C010C */  jal        func_8004F1C8
/* 4EAF6F4 8007C9C4 21306002 */   addu      $a2, $s3, $zero
/* 4EAF6F8 8007C9C8 21200002 */  addu       $a0, $s0, $zero
/* 4EAF6FC 8007C9CC 21280002 */  addu       $a1, $s0, $zero
/* 4EAF700 8007C9D0 8A3C010C */  jal        func_8004F228
/* 4EAF704 8007C9D4 1E000624 */   addiu     $a2, $zero, 0x1E
/* 4EAF708 8007C9D8 21200002 */  addu       $a0, $s0, $zero
/* 4EAF70C 8007C9DC 7A3B010C */  jal        func_8004EDE8
/* 4EAF710 8007C9E0 01000524 */   addiu     $a1, $zero, 0x1
/* 4EAF714 8007C9E4 E1014228 */  slti       $v0, $v0, 0x1E1
/* 4EAF718 8007C9E8 07004014 */  bnez       $v0, .Llevel_18_8007CA08
/* 4EAF71C 8007C9EC 21200002 */   addu      $a0, $s0, $zero
/* 4EAF720 8007C9F0 0C002426 */  addiu      $a0, $s1, 0xC
/* 4EAF724 8007C9F4 5E3C010C */  jal        func_8004F178
/* 4EAF728 8007C9F8 21288002 */   addu      $a1, $s4, $zero
/* 4EAF72C 8007C9FC 1E000224 */  addiu      $v0, $zero, 0x1E
/* 4EAF730 8007CA00 9CF20108 */  j          .Llevel_18_8007CA70
/* 4EAF734 8007CA04 0A0042A6 */   sh        $v0, 0xA($s2)
.Llevel_18_8007CA08:
/* 4EAF738 8007CA08 0A004686 */  lh         $a2, 0xA($s2)
/* 4EAF73C 8007CA0C 7F3C010C */  jal        func_8004F1FC
/* 4EAF740 8007CA10 21280002 */   addu      $a1, $s0, $zero
/* 4EAF744 8007CA14 0C002426 */  addiu      $a0, $s1, 0xC
/* 4EAF748 8007CA18 21286002 */  addu       $a1, $s3, $zero
/* 4EAF74C 8007CA1C 653C010C */  jal        func_8004F194
/* 4EAF750 8007CA20 21300002 */   addu      $a2, $s0, $zero
/* 4EAF754 8007CA24 0A004286 */  lh         $v0, 0xA($s2)
/* 4EAF758 8007CA28 6666043C */  lui        $a0, (0x66666667 >> 16)
/* 4EAF75C 8007CA2C C0100200 */  sll        $v0, $v0, 3
/* 4EAF760 8007CA30 0680013C */  lui        $at, %hi(D_800658A0)
/* 4EAF764 8007CA34 21082200 */  addu       $at, $at, $v0
/* 4EAF768 8007CA38 A0582394 */  lhu        $v1, %lo(D_800658A0)($at)
/* 4EAF76C 8007CA3C 67668434 */  ori        $a0, $a0, (0x66666667 & 0xFFFF)
/* 4EAF770 8007CA40 001C0300 */  sll        $v1, $v1, 16
/* 4EAF774 8007CA44 03140300 */  sra        $v0, $v1, 16
/* 4EAF778 8007CA48 18004400 */  mult       $v0, $a0
/* 4EAF77C 8007CA4C C31F0300 */  sra        $v1, $v1, 31
/* 4EAF780 8007CA50 10400000 */  mfhi       $t0
/* 4EAF784 8007CA54 83100800 */  sra        $v0, $t0, 2
/* 4EAF788 8007CA58 23104300 */  subu       $v0, $v0, $v1
/* 4EAF78C 8007CA5C 00140200 */  sll        $v0, $v0, 16
/* 4EAF790 8007CA60 1400238E */  lw         $v1, 0x14($s1)
/* 4EAF794 8007CA64 03140200 */  sra        $v0, $v0, 16
/* 4EAF798 8007CA68 21186200 */  addu       $v1, $v1, $v0
/* 4EAF79C 8007CA6C 140023AE */  sw         $v1, 0x14($s1)
.Llevel_18_8007CA70:
/* 4EAF7A0 8007CA70 0E004292 */  lbu        $v0, 0xE($s2)
/* 4EAF7A4 8007CA74 44002392 */  lbu        $v1, 0x44($s1)
/* 4EAF7A8 8007CA78 F9004224 */  addiu      $v0, $v0, 0xF9
/* 4EAF7AC 8007CA7C 21186200 */  addu       $v1, $v1, $v0
/* 4EAF7B0 8007CA80 440023A2 */  sb         $v1, 0x44($s1)
/* 4EAF7B4 8007CA84 0F004292 */  lbu        $v0, 0xF($s2)
/* 4EAF7B8 8007CA88 45002392 */  lbu        $v1, 0x45($s1)
/* 4EAF7BC 8007CA8C F9004224 */  addiu      $v0, $v0, 0xF9
/* 4EAF7C0 8007CA90 21186200 */  addu       $v1, $v1, $v0
/* 4EAF7C4 8007CA94 450023A2 */  sb         $v1, 0x45($s1)
/* 4EAF7C8 8007CA98 10004292 */  lbu        $v0, 0x10($s2)
/* 4EAF7CC 8007CA9C 46002392 */  lbu        $v1, 0x46($s1)
/* 4EAF7D0 8007CAA0 F9004224 */  addiu      $v0, $v0, 0xF9
/* 4EAF7D4 8007CAA4 21186200 */  addu       $v1, $v1, $v0
/* 4EAF7D8 8007CAA8 460023A2 */  sb         $v1, 0x46($s1)
/* 4EAF7DC 8007CAAC 0A004286 */  lh         $v0, 0xA($s2)
/* 4EAF7E0 8007CAB0 00000000 */  nop
/* 4EAF7E4 8007CAB4 1E004228 */  slti       $v0, $v0, 0x1E
/* 4EAF7E8 8007CAB8 13004014 */  bnez       $v0, .Llevel_18_8007CB08
/* 4EAF7EC 8007CABC 00000000 */   nop
/* 4EAF7F0 8007CAC0 0780053C */  lui        $a1, %hi(D_80070328 + 0x44)
/* 4EAF7F4 8007CAC4 6C03A58C */  lw         $a1, %lo(D_80070328 + 0x44)($a1)
/* 4EAF7F8 8007CAC8 00000000 */  nop
/* 4EAF7FC 8007CACC 8000A424 */  addiu      $a0, $a1, 0x80
/* 4EAF800 8007CAD0 2A10C402 */  slt        $v0, $s6, $a0
/* 4EAF804 8007CAD4 0C004010 */  beqz       $v0, .Llevel_18_8007CB08
/* 4EAF808 8007CAD8 00000000 */   nop
/* 4EAF80C 8007CADC 0780023C */  lui        $v0, %hi(D_80070328 + 8)
/* 4EAF810 8007CAE0 3003428C */  lw         $v0, %lo(D_80070328 + 8)($v0)
/* 4EAF814 8007CAE4 1400238E */  lw         $v1, 0x14($s1)
/* 4EAF818 8007CAE8 00000000 */  nop
/* 4EAF81C 8007CAEC 23184300 */  subu       $v1, $v0, $v1
/* 4EAF820 8007CAF0 2A106400 */  slt        $v0, $v1, $a0
/* 4EAF824 8007CAF4 04004010 */  beqz       $v0, .Llevel_18_8007CB08
/* 4EAF828 8007CAF8 23100500 */   negu      $v0, $a1
/* 4EAF82C 8007CAFC 2A104300 */  slt        $v0, $v0, $v1
/* 4EAF830 8007CB00 06004014 */  bnez       $v0, .Llevel_18_8007CB1C
/* 4EAF834 8007CB04 04000224 */   addiu     $v0, $zero, 0x4
.Llevel_18_8007CB08:
/* 4EAF838 8007CB08 0A004286 */  lh         $v0, 0xA($s2)
/* 4EAF83C 8007CB0C 00000000 */  nop
/* 4EAF840 8007CB10 41004228 */  slti       $v0, $v0, 0x41
/* 4EAF844 8007CB14 1E004014 */  bnez       $v0, .Llevel_18_8007CB90
/* 4EAF848 8007CB18 04000224 */   addiu     $v0, $zero, 0x4
.Llevel_18_8007CB1C:
/* 4EAF84C 8007CB1C E4F20108 */  j          .Llevel_18_8007CB90
/* 4EAF850 8007CB20 480022A2 */   sb        $v0, 0x48($s1)
.L8007CB24_:
/* 4EAF854 8007CB24 21202002 */  addu       $a0, $s1, $zero
/* 4EAF858 8007CB28 4957010C */  jal        func_80055D24
/* 4EAF85C 8007CB2C 04000524 */   addiu     $a1, $zero, 0x4
/* 4EAF860 8007CB30 04000424 */  addiu      $a0, $zero, 0x4
/* 4EAF864 8007CB34 0C000524 */  addiu      $a1, $zero, 0xC
/* 4EAF868 8007CB38 49002792 */  lbu        $a3, 0x49($s1)
/* 4EAF86C 8007CB3C 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 4EAF870 8007CB40 E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 4EAF874 8007CB44 00000000 */  nop
/* 4EAF878 8007CB48 09F84000 */  jalr       $v0
/* 4EAF87C 8007CB4C 21302002 */   addu      $a2, $s1, $zero
/* 4EAF880 8007CB50 04000424 */  addiu      $a0, $zero, 0x4
/* 4EAF884 8007CB54 0C000524 */  addiu      $a1, $zero, 0xC
/* 4EAF888 8007CB58 49002792 */  lbu        $a3, 0x49($s1)
/* 4EAF88C 8007CB5C 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 4EAF890 8007CB60 E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 4EAF894 8007CB64 00000000 */  nop
/* 4EAF898 8007CB68 09F84000 */  jalr       $v0
/* 4EAF89C 8007CB6C 21302002 */   addu      $a2, $s1, $zero
/* 4EAF8A0 8007CB70 98DB000C */  jal        func_80036E60
/* 4EAF8A4 8007CB74 21202002 */   addu      $a0, $s1, $zero
/* 4EAF8A8 8007CB78 21202002 */  addu       $a0, $s1, $zero
/* 4EAF8AC 8007CB7C 21280000 */  addu       $a1, $zero, $zero
/* 4EAF8B0 8007CB80 AFEE000C */  jal        func_8003BABC
/* 4EAF8B4 8007CB84 21300000 */   addu      $a2, $zero, $zero
/* 4EAF8B8 8007CB88 C656010C */  jal        func_80055B18
/* 4EAF8BC 8007CB8C 21202002 */   addu      $a0, $s1, $zero
.Llevel_18_8007CB90:
/* 4EAF8C0 8007CB90 48002292 */  lbu        $v0, 0x48($s1)
/* 4EAF8C4 8007CB94 00000000 */  nop
/* 4EAF8C8 8007CB98 0300422C */  sltiu      $v0, $v0, 0x3
/* 4EAF8CC 8007CB9C 1D004010 */  beqz       $v0, .Llevel_18_8007CC14
/* 4EAF8D0 8007CBA0 00000000 */   nop
/* 4EAF8D4 8007CBA4 10004292 */  lbu        $v0, 0x10($s2)
/* 4EAF8D8 8007CBA8 00000000 */  nop
/* 4EAF8DC 8007CBAC 40100200 */  sll        $v0, $v0, 1
/* 4EAF8E0 8007CBB0 0680013C */  lui        $at, %hi(D_80065920)
/* 4EAF8E4 8007CBB4 21082200 */  addu       $at, $at, $v0
/* 4EAF8E8 8007CBB8 20592294 */  lhu        $v0, %lo(D_80065920)($at)
/* 4EAF8EC 8007CBBC 0E004392 */  lbu        $v1, 0xE($s2)
/* 4EAF8F0 8007CBC0 00140200 */  sll        $v0, $v0, 16
/* 4EAF8F4 8007CBC4 C3150200 */  sra        $v0, $v0, 23
/* 4EAF8F8 8007CBC8 21104300 */  addu       $v0, $v0, $v1
/* 4EAF8FC 8007CBCC 440022A2 */  sb         $v0, 0x44($s1)
/* 4EAF900 8007CBD0 10004292 */  lbu        $v0, 0x10($s2)
/* 4EAF904 8007CBD4 00000000 */  nop
/* 4EAF908 8007CBD8 40100200 */  sll        $v0, $v0, 1
/* 4EAF90C 8007CBDC 0680013C */  lui        $at, %hi(D_800658A0)
/* 4EAF910 8007CBE0 21082200 */  addu       $at, $at, $v0
/* 4EAF914 8007CBE4 A0582294 */  lhu        $v0, %lo(D_800658A0)($at)
/* 4EAF918 8007CBE8 0F004392 */  lbu        $v1, 0xF($s2)
/* 4EAF91C 8007CBEC 00140200 */  sll        $v0, $v0, 16
/* 4EAF920 8007CBF0 C3150200 */  sra        $v0, $v0, 23
/* 4EAF924 8007CBF4 21104300 */  addu       $v0, $v0, $v1
/* 4EAF928 8007CBF8 450022A2 */  sb         $v0, 0x45($s1)
/* 4EAF92C 8007CBFC 0780023C */  lui        $v0, %hi(D_8006C648)
/* 4EAF930 8007CC00 48C6428C */  lw         $v0, %lo(D_8006C648)($v0)
/* 4EAF934 8007CC04 10004392 */  lbu        $v1, 0x10($s2)
/* 4EAF938 8007CC08 40100200 */  sll        $v0, $v0, 1
/* 4EAF93C 8007CC0C 21186200 */  addu       $v1, $v1, $v0
/* 4EAF940 8007CC10 100043A2 */  sb         $v1, 0x10($s2)
.Llevel_18_8007CC14:
/* 4EAF944 8007CC14 9C00BF8F */  lw         $ra, 0x9C($sp)
/* 4EAF948 8007CC18 9800B68F */  lw         $s6, 0x98($sp)
/* 4EAF94C 8007CC1C 9400B58F */  lw         $s5, 0x94($sp)
/* 4EAF950 8007CC20 9000B48F */  lw         $s4, 0x90($sp)
/* 4EAF954 8007CC24 8C00B38F */  lw         $s3, 0x8C($sp)
/* 4EAF958 8007CC28 8800B28F */  lw         $s2, 0x88($sp)
/* 4EAF95C 8007CC2C 8400B18F */  lw         $s1, 0x84($sp)
/* 4EAF960 8007CC30 8000B08F */  lw         $s0, 0x80($sp)
/* 4EAF964 8007CC34 A000BD27 */  addiu      $sp, $sp, 0xA0
/* 4EAF968 8007CC38 0800E003 */  jr         $ra
/* 4EAF96C 8007CC3C 00000000 */   nop
.size func_level_18_8007C2B4, . - func_level_18_8007C2B4
