.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_50_800744A8
/* 95C89D8 800744A8 706B0780 */ .word .L80076B70_
/* 95C89DC 800744AC FC6D0780 */ .word .L80076DFC_
/* 95C89E0 800744B0 A06E0780 */ .word .L80076EA0_
/* 95C89E4 800744B4 7C7B0780 */ .word .Llevel_50_80077B7C
/* 95C89E8 800744B8 FC6E0780 */ .word .L80076EFC_
/* 95C89EC 800744BC 34700780 */ .word .L80077034_
/* 95C89F0 800744C0 7C7B0780 */ .word .Llevel_50_80077B7C
/* 95C89F4 800744C4 7C7B0780 */ .word .Llevel_50_80077B7C
/* 95C89F8 800744C8 7C7B0780 */ .word .Llevel_50_80077B7C
/* 95C89FC 800744CC 60710780 */ .word .L80077160_
.size jtbl_level_50_800744A8, . - jtbl_level_50_800744A8

.align 3
dlabel jtbl_level_50_800744D0
/* 95C8A00 800744D0 8C730780 */ .word .L8007738C_
/* 95C8A04 800744D4 8C730780 */ .word .L8007738C_
/* 95C8A08 800744D8 38740780 */ .word .L80077438_
/* 95C8A0C 800744DC 8C730780 */ .word .L8007738C_
/* 95C8A10 800744E0 70740780 */ .word .L80077470_
/* 95C8A14 800744E4 84740780 */ .word .Llevel_50_80077484
/* 95C8A18 800744E8 8C730780 */ .word .L8007738C_
/* 95C8A1C 800744EC 00000000 */ .word 0x00000000
.size jtbl_level_50_800744D0, . - jtbl_level_50_800744D0

.align 3
dlabel jtbl_level_50_800744F0
/* 95C8A20 800744F0 D8730780 */ .word .L800773D8_
/* 95C8A24 800744F4 D8730780 */ .word .L800773D8_
/* 95C8A28 800744F8 D8730780 */ .word .L800773D8_
/* 95C8A2C 800744FC D8730780 */ .word .L800773D8_
/* 95C8A30 80074500 EC730780 */ .word .L800773EC_
/* 95C8A34 80074504 EC730780 */ .word .L800773EC_
/* 95C8A38 80074508 EC730780 */ .word .L800773EC_
/* 95C8A3C 8007450C 00740780 */ .word .L80077400_
/* 95C8A40 80074510 00740780 */ .word .L80077400_
/* 95C8A44 80074514 14740780 */ .word .L80077414_
.size jtbl_level_50_800744F0, . - jtbl_level_50_800744F0

.align 3
dlabel jtbl_level_50_80074518
/* 95C8A48 80074518 BC740780 */ .word .L800774BC_
/* 95C8A4C 8007451C BC740780 */ .word .L800774BC_
/* 95C8A50 80074520 78750780 */ .word .L80077578_
/* 95C8A54 80074524 98750780 */ .word .L80077598_
/* 95C8A58 80074528 B0750780 */ .word .L800775B0_
/* 95C8A5C 8007452C B0750780 */ .word .L800775B0_
/* 95C8A60 80074530 70760780 */ .word .Llevel_50_80077670
/* 95C8A64 80074534 00000000 */ .word 0x00000000
.size jtbl_level_50_80074518, . - jtbl_level_50_80074518

.align 3
dlabel jtbl_level_50_80074538
/* 95C8A68 80074538 CC760780 */ .word .L800776CC_
/* 95C8A6C 8007453C F8780780 */ .word .L800778F8_
/* 95C8A70 80074540 F8780780 */ .word .L800778F8_
/* 95C8A74 80074544 A07A0780 */ .word .L80077AA0_
/* 95C8A78 80074548 CC760780 */ .word .L800776CC_
/* 95C8A7C 8007454C CC760780 */ .word .L800776CC_
/* 95C8A80 80074550 EC7A0780 */ .word .L80077AEC_
/* 95C8A84 80074554 00000000 */ .word 0x00000000
.size jtbl_level_50_80074538, . - jtbl_level_50_80074538


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_50_800766A8
/* 95CABD8 800766A8 20FFBD27 */  addiu      $sp, $sp, -0xE0
/* 95CABDC 800766AC C800B4AF */  sw         $s4, 0xC8($sp)
/* 95CABE0 800766B0 21A08000 */  addu       $s4, $a0, $zero
/* 95CABE4 800766B4 D800BFAF */  sw         $ra, 0xD8($sp)
/* 95CABE8 800766B8 D400B7AF */  sw         $s7, 0xD4($sp)
/* 95CABEC 800766BC D000B6AF */  sw         $s6, 0xD0($sp)
/* 95CABF0 800766C0 CC00B5AF */  sw         $s5, 0xCC($sp)
/* 95CABF4 800766C4 C400B3AF */  sw         $s3, 0xC4($sp)
/* 95CABF8 800766C8 C000B2AF */  sw         $s2, 0xC0($sp)
/* 95CABFC 800766CC BC00B1AF */  sw         $s1, 0xBC($sp)
/* 95CAC00 800766D0 B800B0AF */  sw         $s0, 0xB8($sp)
/* 95CAC04 800766D4 0000938E */  lw         $s3, 0x0($s4)
/* 95CAC08 800766D8 0780023C */  lui        $v0, %hi(D_80070328 + 0x244)
/* 95CAC0C 800766DC 6C05428C */  lw         $v0, %lo(D_80070328 + 0x244)($v0)
/* 95CAC10 800766E0 46009792 */  lbu        $s7, 0x46($s4)
/* 95CAC14 800766E4 18004010 */  beqz       $v0, .Llevel_50_80076748
/* 95CAC18 800766E8 00000000 */   nop
/* 95CAC1C 800766EC 0780023C */  lui        $v0, %hi(D_80070328 + 0x250)
/* 95CAC20 800766F0 7805428C */  lw         $v0, %lo(D_80070328 + 0x250)($v0)
/* 95CAC24 800766F4 00000000 */  nop
/* 95CAC28 800766F8 36004384 */  lh         $v1, 0x36($v0)
/* 95CAC2C 800766FC 72000224 */  addiu      $v0, $zero, 0x72
/* 95CAC30 80076700 11006214 */  bne        $v1, $v0, .Llevel_50_80076748
/* 95CAC34 80076704 00000000 */   nop
/* 95CAC38 80076708 0780043C */  lui        $a0, %hi(D_8006C65C)
/* 95CAC3C 8007670C 5CC6848C */  lw         $a0, %lo(D_8006C65C)($a0)
/* 95CAC40 80076710 00000000 */  nop
/* 95CAC44 80076714 48058010 */  beqz       $a0, .Llevel_50_80077C38
/* 95CAC48 80076718 00000000 */   nop
/* 95CAC4C 8007671C 0000908C */  lw         $s0, 0x0($a0)
/* 95CAC50 80076720 C656010C */  jal        func_80055B18
/* 95CAC54 80076724 00000000 */   nop
/* 95CAC58 80076728 1000028E */  lw         $v0, 0x10($s0)
/* 95CAC5C 8007672C 0780013C */  lui        $at, %hi(D_8006C65C)
/* 95CAC60 80076730 5CC620AC */  sw         $zero, %lo(D_8006C65C)($at)
/* 95CAC64 80076734 40054010 */  beqz       $v0, .Llevel_50_80077C38
/* 95CAC68 80076738 00000000 */   nop
/* 95CAC6C 8007673C 100040A0 */  sb         $zero, 0x10($v0)
/* 95CAC70 80076740 0EDF0108 */  j          .Llevel_50_80077C38
/* 95CAC74 80076744 100000AE */   sw        $zero, 0x10($s0)
.Llevel_50_80076748:
/* 95CAC78 80076748 0780023C */  lui        $v0, %hi(D_80070328 + 0x50)
/* 95CAC7C 8007674C 7803428C */  lw         $v0, %lo(D_80070328 + 0x50)($v0)
/* 95CAC80 80076750 00000000 */  nop
/* 95CAC84 80076754 F5FF4224 */  addiu      $v0, $v0, -0xB
/* 95CAC88 80076758 0200422C */  sltiu      $v0, $v0, 0x2
/* 95CAC8C 8007675C 1B004010 */  beqz       $v0, .Llevel_50_800767CC
/* 95CAC90 80076760 00000000 */   nop
/* 95CAC94 80076764 0A006292 */  lbu        $v0, 0xA($s3)
/* 95CAC98 80076768 00000000 */  nop
/* 95CAC9C 8007676C 17004014 */  bnez       $v0, .Llevel_50_800767CC
/* 95CACA0 80076770 00000000 */   nop
/* 95CACA4 80076774 4D008292 */  lbu        $v0, 0x4D($s4)
/* 95CACA8 80076778 00000000 */  nop
/* 95CACAC 8007677C 13004010 */  beqz       $v0, .Llevel_50_800767CC
/* 95CACB0 80076780 AA000424 */   addiu     $a0, $zero, 0xAA
/* 95CACB4 80076784 0780023C */  lui        $v0, %hi(SpawnMoby)
/* 95CACB8 80076788 E042428C */  lw         $v0, %lo(SpawnMoby)($v0)
/* 95CACBC 8007678C 00000000 */  nop
/* 95CACC0 80076790 09F84000 */  jalr       $v0
/* 95CACC4 80076794 21288002 */   addu      $a1, $s4, $zero
/* 95CACC8 80076798 0000448C */  lw         $a0, 0x0($v0)
/* 95CACCC 8007679C 01000624 */  addiu      $a2, $zero, 0x1
/* 95CACD0 800767A0 040094AC */  sw         $s4, 0x4($a0)
/* 95CACD4 800767A4 000086A0 */  sb         $a2, 0x0($a0)
/* 95CACD8 800767A8 36008596 */  lhu        $a1, 0x36($s4)
/* 95CACDC 800767AC 1C000324 */  addiu      $v1, $zero, 0x1C
/* 95CACE0 800767B0 020083A4 */  sh         $v1, 0x2($a0)
/* 95CACE4 800767B4 7F000324 */  addiu      $v1, $zero, 0x7F
/* 95CACE8 800767B8 010085A0 */  sb         $a1, 0x1($a0)
/* 95CACEC 800767BC 4F0043A0 */  sb         $v1, 0x4F($v0)
/* 95CACF0 800767C0 07000324 */  addiu      $v1, $zero, 0x7
/* 95CACF4 800767C4 470043A0 */  sb         $v1, 0x47($v0)
/* 95CACF8 800767C8 0A0066A2 */  sb         $a2, 0xA($s3)
.Llevel_50_800767CC:
/* 95CACFC 800767CC 0780023C */  lui        $v0, %hi(D_80070328 + 0x280)
/* 95CAD00 800767D0 A805428C */  lw         $v0, %lo(D_80070328 + 0x280)($v0)
/* 95CAD04 800767D4 00000000 */  nop
/* 95CAD08 800767D8 02004228 */  slti       $v0, $v0, 0x2
/* 95CAD0C 800767DC 35004014 */  bnez       $v0, .Llevel_50_800768B4
/* 95CAD10 800767E0 00000000 */   nop
/* 95CAD14 800767E4 4D008292 */  lbu        $v0, 0x4D($s4)
/* 95CAD18 800767E8 00000000 */  nop
/* 95CAD1C 800767EC 31004010 */  beqz       $v0, .Llevel_50_800768B4
/* 95CAD20 800767F0 4800B027 */   addiu     $s0, $sp, 0x48
/* 95CAD24 800767F4 21200002 */  addu       $a0, $s0, $zero
/* 95CAD28 800767F8 46008392 */  lbu        $v1, 0x46($s4)
/* 95CAD2C 800767FC 3800A527 */  addiu      $a1, $sp, 0x38
/* 95CAD30 80076800 40006324 */  addiu      $v1, $v1, 0x40
/* 95CAD34 80076804 FF006330 */  andi       $v1, $v1, 0xFF
/* 95CAD38 80076808 40180300 */  sll        $v1, $v1, 1
/* 95CAD3C 8007680C 0680013C */  lui        $at, %hi(D_80065920)
/* 95CAD40 80076810 21082300 */  addu       $at, $at, $v1
/* 95CAD44 80076814 20592684 */  lh         $a2, %lo(D_80065920)($at)
/* 95CAD48 80076818 0C009126 */  addiu      $s1, $s4, 0xC
/* 95CAD4C 8007681C 40100600 */  sll        $v0, $a2, 1
/* 95CAD50 80076820 21104600 */  addu       $v0, $v0, $a2
/* 95CAD54 80076824 C0100200 */  sll        $v0, $v0, 3
/* 95CAD58 80076828 21104600 */  addu       $v0, $v0, $a2
/* 95CAD5C 8007682C 83120200 */  sra        $v0, $v0, 10
/* 95CAD60 80076830 3800A2AF */  sw         $v0, 0x38($sp)
/* 95CAD64 80076834 0680013C */  lui        $at, %hi(D_800658A0)
/* 95CAD68 80076838 21082300 */  addu       $at, $at, $v1
/* 95CAD6C 8007683C A0582384 */  lh         $v1, %lo(D_800658A0)($at)
/* 95CAD70 80076840 21302002 */  addu       $a2, $s1, $zero
/* 95CAD74 80076844 4000A0AF */  sw         $zero, 0x40($sp)
/* 95CAD78 80076848 40100300 */  sll        $v0, $v1, 1
/* 95CAD7C 8007684C 21104300 */  addu       $v0, $v0, $v1
/* 95CAD80 80076850 C0100200 */  sll        $v0, $v0, 3
/* 95CAD84 80076854 21104300 */  addu       $v0, $v0, $v1
/* 95CAD88 80076858 83120200 */  sra        $v0, $v0, 10
/* 95CAD8C 8007685C 653C010C */  jal        func_8004F194
/* 95CAD90 80076860 3C00A2AF */   sw        $v0, 0x3C($sp)
/* 95CAD94 80076864 02000424 */  addiu      $a0, $zero, 0x2
/* 95CAD98 80076868 42000524 */  addiu      $a1, $zero, 0x42
/* 95CAD9C 8007686C 21300002 */  addu       $a2, $s0, $zero
/* 95CADA0 80076870 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 95CADA4 80076874 E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 95CADA8 80076878 00000000 */  nop
/* 95CADAC 8007687C 09F84000 */  jalr       $v0
/* 95CADB0 80076880 21380000 */   addu      $a3, $zero, $zero
/* 95CADB4 80076884 21200002 */  addu       $a0, $s0, $zero
/* 95CADB8 80076888 21282002 */  addu       $a1, $s1, $zero
/* 95CADBC 8007688C 723C010C */  jal        func_8004F1C8
/* 95CADC0 80076890 3800A627 */   addiu     $a2, $sp, 0x38
/* 95CADC4 80076894 02000424 */  addiu      $a0, $zero, 0x2
/* 95CADC8 80076898 42000524 */  addiu      $a1, $zero, 0x42
/* 95CADCC 8007689C 21300002 */  addu       $a2, $s0, $zero
/* 95CADD0 800768A0 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 95CADD4 800768A4 E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 95CADD8 800768A8 00000000 */  nop
/* 95CADDC 800768AC 09F84000 */  jalr       $v0
/* 95CADE0 800768B0 21380000 */   addu      $a3, $zero, $zero
.Llevel_50_800768B4:
/* 95CADE4 800768B4 0780023C */  lui        $v0, %hi(D_80070328 + 0x280)
/* 95CADE8 800768B8 A805428C */  lw         $v0, %lo(D_80070328 + 0x280)($v0)
/* 95CADEC 800768BC 00000000 */  nop
/* 95CADF0 800768C0 03004228 */  slti       $v0, $v0, 0x3
/* 95CADF4 800768C4 0F004014 */  bnez       $v0, .Llevel_50_80076904
/* 95CADF8 800768C8 00000000 */   nop
/* 95CADFC 800768CC 4C008292 */  lbu        $v0, 0x4C($s4)
/* 95CAE00 800768D0 00000000 */  nop
/* 95CAE04 800768D4 0B004010 */  beqz       $v0, .Llevel_50_80076904
/* 95CAE08 800768D8 00000000 */   nop
/* 95CAE0C 800768DC 1000628E */  lw         $v0, 0x10($s3)
/* 95CAE10 800768E0 00000000 */  nop
/* 95CAE14 800768E4 0D004014 */  bnez       $v0, .Llevel_50_8007691C
/* 95CAE18 800768E8 01000424 */   addiu     $a0, $zero, 0x1
/* 95CAE1C 800768EC 40000524 */  addiu      $a1, $zero, 0x40
/* 95CAE20 800768F0 4800063C */  lui        $a2, (0x489090 >> 16)
/* 95CAE24 800768F4 14BB000C */  jal        func_8002EC50
/* 95CAE28 800768F8 9090C634 */   ori       $a2, $a2, (0x489090 & 0xFFFF)
/* 95CAE2C 800768FC 47DA0108 */  j          .Llevel_50_8007691C
/* 95CAE30 80076900 100062AE */   sw        $v0, 0x10($s3)
.Llevel_50_80076904:
/* 95CAE34 80076904 1000628E */  lw         $v0, 0x10($s3)
/* 95CAE38 80076908 00000000 */  nop
/* 95CAE3C 8007690C 03004010 */  beqz       $v0, .Llevel_50_8007691C
/* 95CAE40 80076910 00000000 */   nop
/* 95CAE44 80076914 100040A0 */  sb         $zero, 0x10($v0)
/* 95CAE48 80076918 100060AE */  sw         $zero, 0x10($s3)
.Llevel_50_8007691C:
/* 95CAE4C 8007691C 0780053C */  lui        $a1, %hi(D_80070328 + 0x280)
/* 95CAE50 80076920 A805A524 */  addiu      $a1, $a1, %lo(D_80070328 + 0x280)
/* 95CAE54 80076924 0000A28C */  lw         $v0, 0x0($a1)
/* 95CAE58 80076928 00000000 */  nop
/* 95CAE5C 8007692C 1C00401C */  bgtz       $v0, .Llevel_50_800769A0
/* 95CAE60 80076930 00000000 */   nop
/* 95CAE64 80076934 1400638E */  lw         $v1, 0x14($s3)
/* 95CAE68 80076938 00000000 */  nop
/* 95CAE6C 8007693C 0D006010 */  beqz       $v1, .Llevel_50_80076974
/* 95CAE70 80076940 00000000 */   nop
/* 95CAE74 80076944 48006290 */  lbu        $v0, 0x48($v1)
/* 95CAE78 80076948 00000000 */  nop
/* 95CAE7C 8007694C 8000422C */  sltiu      $v0, $v0, 0x80
/* 95CAE80 80076950 08004010 */  beqz       $v0, .Llevel_50_80076974
/* 95CAE84 80076954 10000224 */   addiu     $v0, $zero, 0x10
/* 95CAE88 80076958 36006484 */  lh         $a0, 0x36($v1)
/* 95CAE8C 8007695C 00000000 */  nop
/* 95CAE90 80076960 03008210 */  beq        $a0, $v0, .Llevel_50_80076970
/* 95CAE94 80076964 D3000224 */   addiu     $v0, $zero, 0xD3
/* 95CAE98 80076968 02008214 */  bne        $a0, $v0, .Llevel_50_80076974
/* 95CAE9C 8007696C 00000000 */   nop
.Llevel_50_80076970:
/* 95CAEA0 80076970 480060A0 */  sb         $zero, 0x48($v1)
.Llevel_50_80076974:
/* 95CAEA4 80076974 1000628E */  lw         $v0, 0x10($s3)
/* 95CAEA8 80076978 0780013C */  lui        $at, %hi(D_8006C65C)
/* 95CAEAC 8007697C 5CC620AC */  sw         $zero, %lo(D_8006C65C)($at)
/* 95CAEB0 80076980 03004010 */  beqz       $v0, .Llevel_50_80076990
/* 95CAEB4 80076984 00000000 */   nop
/* 95CAEB8 80076988 100040A0 */  sb         $zero, 0x10($v0)
/* 95CAEBC 8007698C 100060AE */  sw         $zero, 0x10($s3)
.Llevel_50_80076990:
/* 95CAEC0 80076990 C656010C */  jal        func_80055B18
/* 95CAEC4 80076994 21208002 */   addu      $a0, $s4, $zero
/* 95CAEC8 80076998 0EDF0108 */  j          .Llevel_50_80077C38
/* 95CAECC 8007699C 00000000 */   nop
.Llevel_50_800769A0:
/* 95CAED0 800769A0 1400628E */  lw         $v0, 0x14($s3)
/* 95CAED4 800769A4 00000000 */  nop
/* 95CAED8 800769A8 07004010 */  beqz       $v0, .Llevel_50_800769C8
/* 95CAEDC 800769AC 0C008426 */   addiu     $a0, $s4, 0xC
/* 95CAEE0 800769B0 CD3C010C */  jal        func_8004F334
/* 95CAEE4 800769B4 80FDA524 */   addiu     $a1, $a1, -0x280
/* 95CAEE8 800769B8 010C4228 */  slti       $v0, $v0, 0xC01
/* 95CAEEC 800769BC 02004014 */  bnez       $v0, .Llevel_50_800769C8
/* 95CAEF0 800769C0 00000000 */   nop
/* 95CAEF4 800769C4 000060A6 */  sh         $zero, 0x0($s3)
.Llevel_50_800769C8:
/* 95CAEF8 800769C8 1000638E */  lw         $v1, 0x10($s3)
/* 95CAEFC 800769CC 00000000 */  nop
/* 95CAF00 800769D0 02006010 */  beqz       $v1, .Llevel_50_800769DC
/* 95CAF04 800769D4 04000224 */   addiu     $v0, $zero, 0x4
/* 95CAF08 800769D8 130062A0 */  sb         $v0, 0x13($v1)
.Llevel_50_800769DC:
/* 95CAF0C 800769DC 0680023C */  lui        $v0, %hi(D_80065820)
/* 95CAF10 800769E0 2058428C */  lw         $v0, %lo(D_80065820)($v0)
/* 95CAF14 800769E4 0680053C */  lui        $a1, %hi(D_80065830)
/* 95CAF18 800769E8 3058A524 */  addiu      $a1, $a1, %lo(D_80065830)
/* 95CAF1C 800769EC 51004010 */  beqz       $v0, .Llevel_50_80076B34
/* 95CAF20 800769F0 0000A0AC */   sw        $zero, 0x0($a1)
/* 95CAF24 800769F4 0780023C */  lui        $v0, %hi(D_8006E538)
/* 95CAF28 800769F8 38E5428C */  lw         $v0, %lo(D_8006E538)($v0)
/* 95CAF2C 800769FC 0E000324 */  addiu      $v1, $zero, 0xE
/* 95CAF30 80076A00 0E004230 */  andi       $v0, $v0, 0xE
/* 95CAF34 80076A04 4B004314 */  bne        $v0, $v1, .Llevel_50_80076B34
/* 95CAF38 80076A08 FF000224 */   addiu     $v0, $zero, 0xFF
/* 95CAF3C 80076A0C 0780113C */  lui        $s1, %hi(D_8006C550)
/* 95CAF40 80076A10 50C5318E */  lw         $s1, %lo(D_8006C550)($s1)
/* 95CAF44 80076A14 00000000 */  nop
/* 95CAF48 80076A18 48002492 */  lbu        $a0, 0x48($s1)
/* 95CAF4C 80076A1C 00000000 */  nop
/* 95CAF50 80076A20 FF008330 */  andi       $v1, $a0, 0xFF
/* 95CAF54 80076A24 43006210 */  beq        $v1, $v0, .Llevel_50_80076B34
/* 95CAF58 80076A28 00000000 */   nop
/* 95CAF5C 80076A2C 2190A000 */  addu       $s2, $a1, $zero
/* 95CAF60 80076A30 48003026 */  addiu      $s0, $s1, 0x48
.Llevel_50_80076A34:
/* 95CAF64 80076A34 FF008230 */  andi       $v0, $a0, 0xFF
/* 95CAF68 80076A38 8000422C */  sltiu      $v0, $v0, 0x80
/* 95CAF6C 80076A3C 37004010 */  beqz       $v0, .Llevel_50_80076B1C
/* 95CAF70 80076A40 01000224 */   addiu     $v0, $zero, 0x1
/* 95CAF74 80076A44 EEFF0386 */  lh         $v1, -0x12($s0)
/* 95CAF78 80076A48 00000000 */  nop
/* 95CAF7C 80076A4C 0E006210 */  beq        $v1, $v0, .Llevel_50_80076A88
/* 95CAF80 80076A50 00000000 */   nop
/* 95CAF84 80076A54 08000392 */  lbu        $v1, 0x8($s0)
/* 95CAF88 80076A58 00000000 */  nop
/* 95CAF8C 80076A5C FFFF6224 */  addiu      $v0, $v1, -0x1
/* 95CAF90 80076A60 0200422C */  sltiu      $v0, $v0, 0x2
/* 95CAF94 80076A64 08004014 */  bnez       $v0, .Llevel_50_80076A88
/* 95CAF98 80076A68 FF006330 */   andi      $v1, $v1, 0xFF
/* 95CAF9C 80076A6C 05000224 */  addiu      $v0, $zero, 0x5
/* 95CAFA0 80076A70 05006210 */  beq        $v1, $v0, .Llevel_50_80076A88
/* 95CAFA4 80076A74 0A000224 */   addiu     $v0, $zero, 0xA
/* 95CAFA8 80076A78 03006210 */  beq        $v1, $v0, .Llevel_50_80076A88
/* 95CAFAC 80076A7C 19000224 */   addiu     $v0, $zero, 0x19
/* 95CAFB0 80076A80 26006214 */  bne        $v1, $v0, .Llevel_50_80076B1C
/* 95CAFB4 80076A84 00000000 */   nop
.Llevel_50_80076A88:
/* 95CAFB8 80076A88 3800A427 */  addiu      $a0, $sp, 0x38
/* 95CAFBC 80076A8C 0780063C */  lui        $a2, %hi(D_80070328)
/* 95CAFC0 80076A90 2803C624 */  addiu      $a2, $a2, %lo(D_80070328)
/* 95CAFC4 80076A94 723C010C */  jal        func_8004F1C8
/* 95CAFC8 80076A98 0C002526 */   addiu     $a1, $s1, 0xC
/* 95CAFCC 80076A9C 3800A48F */  lw         $a0, 0x38($sp)
/* 95CAFD0 80076AA0 3C00A38F */  lw         $v1, 0x3C($sp)
/* 95CAFD4 80076AA4 4000A28F */  lw         $v0, 0x40($sp)
/* 95CAFD8 80076AA8 02008104 */  bgez       $a0, .Llevel_50_80076AB4
/* 95CAFDC 80076AAC 00000000 */   nop
/* 95CAFE0 80076AB0 23200400 */  negu       $a0, $a0
.Llevel_50_80076AB4:
/* 95CAFE4 80076AB4 02006104 */  bgez       $v1, .Llevel_50_80076AC0
/* 95CAFE8 80076AB8 00000000 */   nop
/* 95CAFEC 80076ABC 23180300 */  negu       $v1, $v1
.Llevel_50_80076AC0:
/* 95CAFF0 80076AC0 21208300 */  addu       $a0, $a0, $v1
/* 95CAFF4 80076AC4 02004104 */  bgez       $v0, .Llevel_50_80076AD0
/* 95CAFF8 80076AC8 00000000 */   nop
/* 95CAFFC 80076ACC 23100200 */  negu       $v0, $v0
.Llevel_50_80076AD0:
/* 95CB000 80076AD0 21208200 */  addu       $a0, $a0, $v0
/* 95CB004 80076AD4 00408228 */  slti       $v0, $a0, 0x4000
/* 95CB008 80076AD8 05004010 */  beqz       $v0, .Llevel_50_80076AF0
/* 95CB00C 80076ADC 00000000 */   nop
/* 95CB010 80076AE0 3800A427 */  addiu      $a0, $sp, 0x38
/* 95CB014 80076AE4 7A3B010C */  jal        func_8004EDE8
/* 95CB018 80076AE8 01000524 */   addiu     $a1, $zero, 0x1
/* 95CB01C 80076AEC 21204000 */  addu       $a0, $v0, $zero
.Llevel_50_80076AF0:
/* 95CB020 80076AF0 0000428E */  lw         $v0, 0x0($s2)
/* 95CB024 80076AF4 00000000 */  nop
/* 95CB028 80076AF8 06004010 */  beqz       $v0, .Llevel_50_80076B14
/* 95CB02C 80076AFC 00000000 */   nop
/* 95CB030 80076B00 F8FF428E */  lw         $v0, -0x8($s2)
/* 95CB034 80076B04 00000000 */  nop
/* 95CB038 80076B08 2A108200 */  slt        $v0, $a0, $v0
/* 95CB03C 80076B0C 03004010 */  beqz       $v0, .Llevel_50_80076B1C
/* 95CB040 80076B10 00000000 */   nop
.Llevel_50_80076B14:
/* 95CB044 80076B14 000051AE */  sw         $s1, 0x0($s2)
/* 95CB048 80076B18 F8FF44AE */  sw         $a0, -0x8($s2)
.Llevel_50_80076B1C:
/* 95CB04C 80076B1C 58001026 */  addiu      $s0, $s0, 0x58
/* 95CB050 80076B20 00000492 */  lbu        $a0, 0x0($s0)
/* 95CB054 80076B24 FF000224 */  addiu      $v0, $zero, 0xFF
/* 95CB058 80076B28 FF008330 */  andi       $v1, $a0, 0xFF
/* 95CB05C 80076B2C C1FF6214 */  bne        $v1, $v0, .Llevel_50_80076A34
/* 95CB060 80076B30 58003126 */   addiu     $s1, $s1, 0x58
.Llevel_50_80076B34:
/* 95CB064 80076B34 1400628E */  lw         $v0, 0x14($s3)
/* 95CB068 80076B38 00000000 */  nop
/* 95CB06C 80076B3C 8F014010 */  beqz       $v0, .Llevel_50_8007717C
/* 95CB070 80076B40 00000000 */   nop
/* 95CB074 80076B44 49008392 */  lbu        $v1, 0x49($s4)
/* 95CB078 80076B48 00000000 */  nop
/* 95CB07C 80076B4C 0A00622C */  sltiu      $v0, $v1, 0xA
/* 95CB080 80076B50 0A044010 */  beqz       $v0, .Llevel_50_80077B7C
/* 95CB084 80076B54 80100300 */   sll       $v0, $v1, 2
/* 95CB088 80076B58 0780013C */  lui        $at, %hi(jtbl_level_50_800744A8)
/* 95CB08C 80076B5C 21082200 */  addu       $at, $at, $v0
/* 95CB090 80076B60 A844228C */  lw         $v0, %lo(jtbl_level_50_800744A8)($at)
/* 95CB094 80076B64 00000000 */  nop
/* 95CB098 80076B68 08004000 */  jr         $v0
/* 95CB09C 80076B6C 00000000 */   nop
.L80076B70_:
/* 95CB0A0 80076B70 5800A427 */  addiu      $a0, $sp, 0x58
/* 95CB0A4 80076B74 1400658E */  lw         $a1, 0x14($s3)
/* 95CB0A8 80076B78 3D009192 */  lbu        $s1, 0x3D($s4)
/* 95CB0AC 80076B7C 5E3C010C */  jal        func_8004F178
/* 95CB0B0 80076B80 0C00A524 */   addiu     $a1, $a1, 0xC
/* 95CB0B4 80076B84 1A002016 */  bnez       $s1, .Llevel_50_80076BF0
/* 95CB0B8 80076B88 00000000 */   nop
/* 95CB0BC 80076B8C 1400628E */  lw         $v0, 0x14($s3)
/* 95CB0C0 80076B90 00000000 */  nop
/* 95CB0C4 80076B94 46004290 */  lbu        $v0, 0x46($v0)
/* 95CB0C8 80076B98 00000000 */  nop
/* 95CB0CC 80076B9C 40100200 */  sll        $v0, $v0, 1
/* 95CB0D0 80076BA0 0680013C */  lui        $at, %hi(D_80065920)
/* 95CB0D4 80076BA4 21082200 */  addu       $at, $at, $v0
/* 95CB0D8 80076BA8 20592294 */  lhu        $v0, %lo(D_80065920)($at)
/* 95CB0DC 80076BAC 5800A38F */  lw         $v1, 0x58($sp)
/* 95CB0E0 80076BB0 00140200 */  sll        $v0, $v0, 16
/* 95CB0E4 80076BB4 03150200 */  sra        $v0, $v0, 20
/* 95CB0E8 80076BB8 23186200 */  subu       $v1, $v1, $v0
/* 95CB0EC 80076BBC 5800A3AF */  sw         $v1, 0x58($sp)
/* 95CB0F0 80076BC0 1400628E */  lw         $v0, 0x14($s3)
/* 95CB0F4 80076BC4 00000000 */  nop
/* 95CB0F8 80076BC8 46004290 */  lbu        $v0, 0x46($v0)
/* 95CB0FC 80076BCC 00000000 */  nop
/* 95CB100 80076BD0 40100200 */  sll        $v0, $v0, 1
/* 95CB104 80076BD4 0680013C */  lui        $at, %hi(D_800658A0)
/* 95CB108 80076BD8 21082200 */  addu       $at, $at, $v0
/* 95CB10C 80076BDC A0582294 */  lhu        $v0, %lo(D_800658A0)($at)
/* 95CB110 80076BE0 5C00A38F */  lw         $v1, 0x5C($sp)
/* 95CB114 80076BE4 00140200 */  sll        $v0, $v0, 16
/* 95CB118 80076BE8 14DB0108 */  j          .Llevel_50_80076C50
/* 95CB11C 80076BEC 03150200 */   sra       $v0, $v0, 20
.Llevel_50_80076BF0:
/* 95CB120 80076BF0 1400628E */  lw         $v0, 0x14($s3)
/* 95CB124 80076BF4 00000000 */  nop
/* 95CB128 80076BF8 46004290 */  lbu        $v0, 0x46($v0)
/* 95CB12C 80076BFC 00000000 */  nop
/* 95CB130 80076C00 40100200 */  sll        $v0, $v0, 1
/* 95CB134 80076C04 0680013C */  lui        $at, %hi(D_80065920)
/* 95CB138 80076C08 21082200 */  addu       $at, $at, $v0
/* 95CB13C 80076C0C 20592294 */  lhu        $v0, %lo(D_80065920)($at)
/* 95CB140 80076C10 5800A38F */  lw         $v1, 0x58($sp)
/* 95CB144 80076C14 00140200 */  sll        $v0, $v0, 16
/* 95CB148 80076C18 83150200 */  sra        $v0, $v0, 22
/* 95CB14C 80076C1C 23186200 */  subu       $v1, $v1, $v0
/* 95CB150 80076C20 5800A3AF */  sw         $v1, 0x58($sp)
/* 95CB154 80076C24 1400628E */  lw         $v0, 0x14($s3)
/* 95CB158 80076C28 00000000 */  nop
/* 95CB15C 80076C2C 46004290 */  lbu        $v0, 0x46($v0)
/* 95CB160 80076C30 00000000 */  nop
/* 95CB164 80076C34 40100200 */  sll        $v0, $v0, 1
/* 95CB168 80076C38 0680013C */  lui        $at, %hi(D_800658A0)
/* 95CB16C 80076C3C 21082200 */  addu       $at, $at, $v0
/* 95CB170 80076C40 A0582294 */  lhu        $v0, %lo(D_800658A0)($at)
/* 95CB174 80076C44 5C00A38F */  lw         $v1, 0x5C($sp)
/* 95CB178 80076C48 00140200 */  sll        $v0, $v0, 16
/* 95CB17C 80076C4C 83150200 */  sra        $v0, $v0, 22
.Llevel_50_80076C50:
/* 95CB180 80076C50 23186200 */  subu       $v1, $v1, $v0
/* 95CB184 80076C54 1B002012 */  beqz       $s1, .Llevel_50_80076CC4
/* 95CB188 80076C58 5C00A3AF */   sw        $v1, 0x5C($sp)
/* 95CB18C 80076C5C 3F008292 */  lbu        $v0, 0x3F($s4)
/* 95CB190 80076C60 00000000 */  nop
/* 95CB194 80076C64 0700422C */  sltiu      $v0, $v0, 0x7
/* 95CB198 80076C68 05004014 */  bnez       $v0, .Llevel_50_80076C80
/* 95CB19C 80076C6C 00000000 */   nop
/* 95CB1A0 80076C70 49008292 */  lbu        $v0, 0x49($s4)
/* 95CB1A4 80076C74 00000000 */  nop
/* 95CB1A8 80076C78 01004224 */  addiu      $v0, $v0, 0x1
/* 95CB1AC 80076C7C 490082A2 */  sb         $v0, 0x49($s4)
.Llevel_50_80076C80:
/* 95CB1B0 80076C80 45008492 */  lbu        $a0, 0x45($s4)
/* 95CB1B4 80076C84 00000000 */  nop
/* 95CB1B8 80076C88 FDFF8224 */  addiu      $v0, $a0, -0x3
/* 95CB1BC 80076C8C FF004230 */  andi       $v0, $v0, 0xFF
/* 95CB1C0 80076C90 FB00422C */  sltiu      $v0, $v0, 0xFB
/* 95CB1C4 80076C94 0B004010 */  beqz       $v0, .Llevel_50_80076CC4
/* 95CB1C8 80076C98 23180400 */   negu      $v1, $a0
/* 95CB1CC 80076C9C 03006228 */  slti       $v0, $v1, 0x3
/* 95CB1D0 80076CA0 03004014 */  bnez       $v0, .Llevel_50_80076CB0
/* 95CB1D4 80076CA4 FEFF6228 */   slti      $v0, $v1, -0x2
/* 95CB1D8 80076CA8 02000324 */  addiu      $v1, $zero, 0x2
/* 95CB1DC 80076CAC FEFF6228 */  slti       $v0, $v1, -0x2
.Llevel_50_80076CB0:
/* 95CB1E0 80076CB0 03004010 */  beqz       $v0, .Llevel_50_80076CC0
/* 95CB1E4 80076CB4 21108300 */   addu      $v0, $a0, $v1
/* 95CB1E8 80076CB8 FEFF0324 */  addiu      $v1, $zero, -0x2
/* 95CB1EC 80076CBC 21108300 */  addu       $v0, $a0, $v1
.Llevel_50_80076CC0:
/* 95CB1F0 80076CC0 450082A2 */  sb         $v0, 0x45($s4)
.Llevel_50_80076CC4:
/* 95CB1F4 80076CC4 5800B027 */  addiu      $s0, $sp, 0x58
/* 95CB1F8 80076CC8 21200002 */  addu       $a0, $s0, $zero
/* 95CB1FC 80076CCC 21280002 */  addu       $a1, $s0, $zero
/* 95CB200 80076CD0 723C010C */  jal        func_8004F1C8
/* 95CB204 80076CD4 0C008626 */   addiu     $a2, $s4, 0xC
/* 95CB208 80076CD8 21200002 */  addu       $a0, $s0, $zero
/* 95CB20C 80076CDC 7A3B010C */  jal        func_8004EDE8
/* 95CB210 80076CE0 01000524 */   addiu     $a1, $zero, 0x1
/* 95CB214 80076CE4 1F002016 */  bnez       $s1, .Llevel_50_80076D64
/* 95CB218 80076CE8 21804000 */   addu      $s0, $v0, $zero
/* 95CB21C 80076CEC 21206002 */  addu       $a0, $s3, $zero
/* 95CB220 80076CF0 69D6000C */  jal        func_800359A4
/* 95CB224 80076CF4 02000524 */   addiu     $a1, $zero, 0x2
/* 95CB228 80076CF8 1A004010 */  beqz       $v0, .Llevel_50_80076D64
/* 95CB22C 80076CFC 00000000 */   nop
/* 95CB230 80076D00 02006592 */  lbu        $a1, 0x2($s3)
/* 95CB234 80076D04 F0EF000C */  jal        func_8003BFC0
/* 95CB238 80076D08 21208002 */   addu      $a0, $s4, $zero
/* 95CB23C 80076D0C 05004014 */  bnez       $v0, .Llevel_50_80076D24
/* 95CB240 80076D10 21208002 */   addu      $a0, $s4, $zero
/* 95CB244 80076D14 21280000 */  addu       $a1, $zero, $zero
/* 95CB248 80076D18 AFEE000C */  jal        func_8003BABC
/* 95CB24C 80076D1C 21300000 */   addu      $a2, $zero, $zero
/* 95CB250 80076D20 020062A2 */  sb         $v0, 0x2($s3)
.Llevel_50_80076D24:
/* 95CB254 80076D24 3D008392 */  lbu        $v1, 0x3D($s4)
/* 95CB258 80076D28 01000224 */  addiu      $v0, $zero, 0x1
/* 95CB25C 80076D2C 0D006210 */  beq        $v1, $v0, .Llevel_50_80076D64
/* 95CB260 80076D30 21208002 */   addu      $a0, $s4, $zero
/* 95CB264 80076D34 0780013C */  lui        $at, %hi(D_8006C770)
/* 95CB268 80076D38 70C720AC */  sw         $zero, %lo(D_8006C770)($at)
/* 95CB26C 80076D3C 3D008392 */  lbu        $v1, 0x3D($s4)
/* 95CB270 80076D40 3F008592 */  lbu        $a1, 0x3F($s4)
/* 95CB274 80076D44 72000224 */  addiu      $v0, $zero, 0x72
/* 95CB278 80076D48 400082A2 */  sb         $v0, 0x40($s4)
/* 95CB27C 80076D4C 01000224 */  addiu      $v0, $zero, 0x1
/* 95CB280 80076D50 3D0082A2 */  sb         $v0, 0x3D($s4)
/* 95CB284 80076D54 3F0080A2 */  sb         $zero, 0x3F($s4)
/* 95CB288 80076D58 3C0083A2 */  sb         $v1, 0x3C($s4)
/* 95CB28C 80076D5C CDD5000C */  jal        func_80035734
/* 95CB290 80076D60 3E0085A2 */   sb        $a1, 0x3E($s4)
.Llevel_50_80076D64:
/* 95CB294 80076D64 02002012 */  beqz       $s1, .Llevel_50_80076D70
/* 95CB298 80076D68 82000624 */   addiu     $a2, $zero, 0x82
/* 95CB29C 80076D6C 96000624 */  addiu      $a2, $zero, 0x96
.Llevel_50_80076D70:
/* 95CB2A0 80076D70 0500C324 */  addiu      $v1, $a2, 0x5
/* 95CB2A4 80076D74 2A107000 */  slt        $v0, $v1, $s0
/* 95CB2A8 80076D78 05004010 */  beqz       $v0, .Llevel_50_80076D90
/* 95CB2AC 80076D7C 00000000 */   nop
/* 95CB2B0 80076D80 5800A427 */  addiu      $a0, $sp, 0x58
/* 95CB2B4 80076D84 21280002 */  addu       $a1, $s0, $zero
/* 95CB2B8 80076D88 67DB0108 */  j          .Llevel_50_80076D9C
/* 95CB2BC 80076D8C 21306000 */   addu      $a2, $v1, $zero
.Llevel_50_80076D90:
/* 95CB2C0 80076D90 5800A427 */  addiu      $a0, $sp, 0x58
/* 95CB2C4 80076D94 21280002 */  addu       $a1, $s0, $zero
/* 95CB2C8 80076D98 FBFFC624 */  addiu      $a2, $a2, -0x5
.Llevel_50_80076D9C:
/* 95CB2CC 80076D9C 233C010C */  jal        func_8004F08C
/* 95CB2D0 80076DA0 00000000 */   nop
/* 95CB2D4 80076DA4 0C008426 */  addiu      $a0, $s4, 0xC
/* 95CB2D8 80076DA8 21288000 */  addu       $a1, $a0, $zero
/* 95CB2DC 80076DAC 5800B027 */  addiu      $s0, $sp, 0x58
/* 95CB2E0 80076DB0 653C010C */  jal        func_8004F194
/* 95CB2E4 80076DB4 21300002 */   addu      $a2, $s0, $zero
/* 95CB2E8 80076DB8 5800A48F */  lw         $a0, 0x58($sp)
/* 95CB2EC 80076DBC 5C00A58F */  lw         $a1, 0x5C($sp)
/* 95CB2F0 80076DC0 203A010C */  jal        func_8004E880
/* 95CB2F4 80076DC4 21300000 */   addu      $a2, $zero, $zero
/* 95CB2F8 80076DC8 21208002 */  addu       $a0, $s4, $zero
/* 95CB2FC 80076DCC 21284000 */  addu       $a1, $v0, $zero
/* 95CB300 80076DD0 0A000624 */  addiu      $a2, $zero, 0xA
/* 95CB304 80076DD4 21380000 */  addu       $a3, $zero, $zero
/* 95CB308 80076DD8 1000A0AF */  sw         $zero, 0x10($sp)
/* 95CB30C 80076DDC 17D6000C */  jal        func_8003585C
/* 95CB310 80076DE0 1400A0AF */   sw        $zero, 0x14($sp)
/* 95CB314 80076DE4 21200002 */  addu       $a0, $s0, $zero
/* 95CB318 80076DE8 7A3B010C */  jal        func_8004EDE8
/* 95CB31C 80076DEC 21280000 */   addu      $a1, $zero, $zero
/* 95CB320 80076DF0 6000A58F */  lw         $a1, 0x60($sp)
/* 95CB324 80076DF4 4FDC0108 */  j          .Llevel_50_8007713C
/* 95CB328 80076DF8 21204000 */   addu      $a0, $v0, $zero
.L80076DFC_:
/* 95CB32C 80076DFC 1400628E */  lw         $v0, 0x14($s3)
/* 95CB330 80076E00 00000000 */  nop
/* 95CB334 80076E04 36004384 */  lh         $v1, 0x36($v0)
/* 95CB338 80076E08 10000224 */  addiu      $v0, $zero, 0x10
/* 95CB33C 80076E0C 0D006214 */  bne        $v1, $v0, .Llevel_50_80076E44
/* 95CB340 80076E10 00000000 */   nop
/* 95CB344 80076E14 0780033C */  lui        $v1, %hi(D_80070328 + 0x280)
/* 95CB348 80076E18 A8056324 */  addiu      $v1, $v1, %lo(D_80070328 + 0x280)
/* 95CB34C 80076E1C 0000628C */  lw         $v0, 0x0($v1)
/* 95CB350 80076E20 0680043C */  lui        $a0, %hi(D_8006580C)
/* 95CB354 80076E24 0C58848C */  lw         $a0, %lo(D_8006580C)($a0)
/* 95CB358 80076E28 01004224 */  addiu      $v0, $v0, 0x1
/* 95CB35C 80076E2C 000062AC */  sw         $v0, 0x0($v1)
/* 95CB360 80076E30 2A108200 */  slt        $v0, $a0, $v0
/* 95CB364 80076E34 11004010 */  beqz       $v0, .Llevel_50_80076E7C
/* 95CB368 80076E38 00000000 */   nop
/* 95CB36C 80076E3C 9FDB0108 */  j          .Llevel_50_80076E7C
/* 95CB370 80076E40 000064AC */   sw        $a0, 0x0($v1)
.Llevel_50_80076E44:
/* 95CB374 80076E44 0780023C */  lui        $v0, %hi(D_8006C784)
/* 95CB378 80076E48 84C7428C */  lw         $v0, %lo(D_8006C784)($v0)
/* 95CB37C 80076E4C 0680033C */  lui        $v1, %hi(D_8006580C)
/* 95CB380 80076E50 0C58638C */  lw         $v1, %lo(D_8006580C)($v1)
/* 95CB384 80076E54 01004224 */  addiu      $v0, $v0, 0x1
/* 95CB388 80076E58 0780013C */  lui        $at, %hi(D_8006C784)
/* 95CB38C 80076E5C 84C722AC */  sw         $v0, %lo(D_8006C784)($at)
/* 95CB390 80076E60 64004228 */  slti       $v0, $v0, 0x64
/* 95CB394 80076E64 0780013C */  lui        $at, %hi(D_80070328 + 0x280)
/* 95CB398 80076E68 A80523AC */  sw         $v1, %lo(D_80070328 + 0x280)($at)
/* 95CB39C 80076E6C 03004014 */  bnez       $v0, .Llevel_50_80076E7C
/* 95CB3A0 80076E70 63000224 */   addiu     $v0, $zero, 0x63
/* 95CB3A4 80076E74 0780013C */  lui        $at, %hi(D_8006C784)
/* 95CB3A8 80076E78 84C722AC */  sw         $v0, %lo(D_8006C784)($at)
.Llevel_50_80076E7C:
/* 95CB3AC 80076E7C 49008292 */  lbu        $v0, 0x49($s4)
/* 95CB3B0 80076E80 00000000 */  nop
/* 95CB3B4 80076E84 01004224 */  addiu      $v0, $v0, 0x1
/* 95CB3B8 80076E88 490082A2 */  sb         $v0, 0x49($s4)
/* 95CB3BC 80076E8C 1400648E */  lw         $a0, 0x14($s3)
/* 95CB3C0 80076E90 C656010C */  jal        func_80055B18
/* 95CB3C4 80076E94 00000000 */   nop
/* 95CB3C8 80076E98 DFDE0108 */  j          .Llevel_50_80077B7C
/* 95CB3CC 80076E9C 00000000 */   nop
.L80076EA0_:
/* 95CB3D0 80076EA0 0780023C */  lui        $v0, %hi(D_8006C770)
/* 95CB3D4 80076EA4 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 95CB3D8 80076EA8 00000000 */  nop
/* 95CB3DC 80076EAC 33034010 */  beqz       $v0, .Llevel_50_80077B7C
/* 95CB3E0 80076EB0 00000000 */   nop
/* 95CB3E4 80076EB4 3D008292 */  lbu        $v0, 0x3D($s4)
/* 95CB3E8 80076EB8 00000000 */  nop
/* 95CB3EC 80076EBC 0C004010 */  beqz       $v0, .Llevel_50_80076EF0
/* 95CB3F0 80076EC0 21208002 */   addu      $a0, $s4, $zero
/* 95CB3F4 80076EC4 0780013C */  lui        $at, %hi(D_8006C770)
/* 95CB3F8 80076EC8 70C720AC */  sw         $zero, %lo(D_8006C770)($at)
/* 95CB3FC 80076ECC 3D008292 */  lbu        $v0, 0x3D($s4)
/* 95CB400 80076ED0 3F008592 */  lbu        $a1, 0x3F($s4)
/* 95CB404 80076ED4 72000324 */  addiu      $v1, $zero, 0x72
/* 95CB408 80076ED8 400083A2 */  sb         $v1, 0x40($s4)
/* 95CB40C 80076EDC 3D0080A2 */  sb         $zero, 0x3D($s4)
/* 95CB410 80076EE0 3F0080A2 */  sb         $zero, 0x3F($s4)
/* 95CB414 80076EE4 3C0082A2 */  sb         $v0, 0x3C($s4)
/* 95CB418 80076EE8 CDD5000C */  jal        func_80035734
/* 95CB41C 80076EEC 3E0085A2 */   sb        $a1, 0x3E($s4)
.Llevel_50_80076EF0:
/* 95CB420 80076EF0 490080A2 */  sb         $zero, 0x49($s4)
/* 95CB424 80076EF4 DFDE0108 */  j          .Llevel_50_80077B7C
/* 95CB428 80076EF8 140060AE */   sw        $zero, 0x14($s3)
.L80076EFC_:
/* 95CB42C 80076EFC 6800B027 */  addiu      $s0, $sp, 0x68
/* 95CB430 80076F00 21200002 */  addu       $a0, $s0, $zero
/* 95CB434 80076F04 1400628E */  lw         $v0, 0x14($s3)
/* 95CB438 80076F08 0C008626 */  addiu      $a2, $s4, 0xC
/* 95CB43C 80076F0C 0000518C */  lw         $s1, 0x0($v0)
/* 95CB440 80076F10 723C010C */  jal        func_8004F1C8
/* 95CB444 80076F14 0C004524 */   addiu     $a1, $v0, 0xC
/* 95CB448 80076F18 21200002 */  addu       $a0, $s0, $zero
/* 95CB44C 80076F1C 7A3B010C */  jal        func_8004EDE8
/* 95CB450 80076F20 01000524 */   addiu     $a1, $zero, 0x1
/* 95CB454 80076F24 21284000 */  addu       $a1, $v0, $zero
/* 95CB458 80076F28 0002A228 */  slti       $v0, $a1, 0x200
/* 95CB45C 80076F2C 22004010 */  beqz       $v0, .Llevel_50_80076FB8
/* 95CB460 80076F30 36010224 */   addiu     $v0, $zero, 0x136
/* 95CB464 80076F34 1400648E */  lw         $a0, 0x14($s3)
/* 95CB468 80076F38 4957010C */  jal        func_80055D24
/* 95CB46C 80076F3C 04000524 */   addiu     $a1, $zero, 0x4
/* 95CB470 80076F40 04000424 */  addiu      $a0, $zero, 0x4
/* 95CB474 80076F44 1400668E */  lw         $a2, 0x14($s3)
/* 95CB478 80076F48 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 95CB47C 80076F4C E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 95CB480 80076F50 4900C790 */  lbu        $a3, 0x49($a2)
/* 95CB484 80076F54 09F84000 */  jalr       $v0
/* 95CB488 80076F58 0C000524 */   addiu     $a1, $zero, 0xC
/* 95CB48C 80076F5C 9171010C */  jal        func_8005C644
/* 95CB490 80076F60 0A0020A6 */   sh        $zero, 0xA($s1)
/* 95CB494 80076F64 0E004230 */  andi       $v0, $v0, 0xE
/* 95CB498 80076F68 9171010C */  jal        func_8005C644
/* 95CB49C 80076F6C 0E0022A2 */   sb        $v0, 0xE($s1)
/* 95CB4A0 80076F70 0E004230 */  andi       $v0, $v0, 0xE
/* 95CB4A4 80076F74 9171010C */  jal        func_8005C644
/* 95CB4A8 80076F78 0F0022A2 */   sb        $v0, 0xF($s1)
/* 95CB4AC 80076F7C 0E004230 */  andi       $v0, $v0, 0xE
/* 95CB4B0 80076F80 100022A2 */  sb         $v0, 0x10($s1)
/* 95CB4B4 80076F84 1400658E */  lw         $a1, 0x14($s3)
/* 95CB4B8 80076F88 04002426 */  addiu      $a0, $s1, 0x4
/* 95CB4BC 80076F8C 413D010C */  jal        func_8004F504
/* 95CB4C0 80076F90 0C00A524 */   addiu     $a1, $a1, 0xC
/* 95CB4C4 80076F94 01000524 */  addiu      $a1, $zero, 0x1
/* 95CB4C8 80076F98 1400638E */  lw         $v1, 0x14($s3)
/* 95CB4CC 80076F9C 03000224 */  addiu      $v0, $zero, 0x3
/* 95CB4D0 80076FA0 480062A0 */  sb         $v0, 0x48($v1)
/* 95CB4D4 80076FA4 1400648E */  lw         $a0, 0x14($s3)
/* 95CB4D8 80076FA8 AFEE000C */  jal        func_8003BABC
/* 95CB4DC 80076FAC 21300000 */   addu      $a2, $zero, $zero
/* 95CB4E0 80076FB0 DFDE0108 */  j          .Llevel_50_80077B7C
/* 95CB4E4 80076FB4 140060AE */   sw        $zero, 0x14($s3)
.Llevel_50_80076FB8:
/* 95CB4E8 80076FB8 2A104500 */  slt        $v0, $v0, $a1
/* 95CB4EC 80076FBC 03004010 */  beqz       $v0, .Llevel_50_80076FCC
/* 95CB4F0 80076FC0 36010624 */   addiu     $a2, $zero, 0x136
/* 95CB4F4 80076FC4 F5DB0108 */  j          .Llevel_50_80076FD4
/* 95CB4F8 80076FC8 21200002 */   addu      $a0, $s0, $zero
.Llevel_50_80076FCC:
/* 95CB4FC 80076FCC 21200002 */  addu       $a0, $s0, $zero
/* 95CB500 80076FD0 22010624 */  addiu      $a2, $zero, 0x122
.Llevel_50_80076FD4:
/* 95CB504 80076FD4 233C010C */  jal        func_8004F08C
/* 95CB508 80076FD8 00000000 */   nop
/* 95CB50C 80076FDC 0C008426 */  addiu      $a0, $s4, 0xC
/* 95CB510 80076FE0 21288000 */  addu       $a1, $a0, $zero
/* 95CB514 80076FE4 6800B027 */  addiu      $s0, $sp, 0x68
/* 95CB518 80076FE8 653C010C */  jal        func_8004F194
/* 95CB51C 80076FEC 21300002 */   addu      $a2, $s0, $zero
/* 95CB520 80076FF0 6800A48F */  lw         $a0, 0x68($sp)
/* 95CB524 80076FF4 6C00A58F */  lw         $a1, 0x6C($sp)
/* 95CB528 80076FF8 203A010C */  jal        func_8004E880
/* 95CB52C 80076FFC 21300000 */   addu      $a2, $zero, $zero
/* 95CB530 80077000 21208002 */  addu       $a0, $s4, $zero
/* 95CB534 80077004 21284000 */  addu       $a1, $v0, $zero
/* 95CB538 80077008 0A000624 */  addiu      $a2, $zero, 0xA
/* 95CB53C 8007700C 21380000 */  addu       $a3, $zero, $zero
/* 95CB540 80077010 1000A0AF */  sw         $zero, 0x10($sp)
/* 95CB544 80077014 17D6000C */  jal        func_8003585C
/* 95CB548 80077018 1400A0AF */   sw        $zero, 0x14($sp)
/* 95CB54C 8007701C 21200002 */  addu       $a0, $s0, $zero
/* 95CB550 80077020 7A3B010C */  jal        func_8004EDE8
/* 95CB554 80077024 21280000 */   addu      $a1, $zero, $zero
/* 95CB558 80077028 7000A58F */  lw         $a1, 0x70($sp)
/* 95CB55C 8007702C 4FDC0108 */  j          .Llevel_50_8007713C
/* 95CB560 80077030 21204000 */   addu      $a0, $v0, $zero
.L80077034_:
/* 95CB564 80077034 7800B027 */  addiu      $s0, $sp, 0x78
/* 95CB568 80077038 1400628E */  lw         $v0, 0x14($s3)
/* 95CB56C 8007703C 04006386 */  lh         $v1, 0x4($s3)
/* 95CB570 80077040 0C00428C */  lw         $v0, 0xC($v0)
/* 95CB574 80077044 21200002 */  addu       $a0, $s0, $zero
/* 95CB578 80077048 21104300 */  addu       $v0, $v0, $v1
/* 95CB57C 8007704C 7800A2AF */  sw         $v0, 0x78($sp)
/* 95CB580 80077050 1400628E */  lw         $v0, 0x14($s3)
/* 95CB584 80077054 06006386 */  lh         $v1, 0x6($s3)
/* 95CB588 80077058 1000428C */  lw         $v0, 0x10($v0)
/* 95CB58C 8007705C 21280002 */  addu       $a1, $s0, $zero
/* 95CB590 80077060 21104300 */  addu       $v0, $v0, $v1
/* 95CB594 80077064 7C00A2AF */  sw         $v0, 0x7C($sp)
/* 95CB598 80077068 1400628E */  lw         $v0, 0x14($s3)
/* 95CB59C 8007706C 08006386 */  lh         $v1, 0x8($s3)
/* 95CB5A0 80077070 1400428C */  lw         $v0, 0x14($v0)
/* 95CB5A4 80077074 0C008626 */  addiu      $a2, $s4, 0xC
/* 95CB5A8 80077078 21104300 */  addu       $v0, $v0, $v1
/* 95CB5AC 8007707C 723C010C */  jal        func_8004F1C8
/* 95CB5B0 80077080 8000A2AF */   sw        $v0, 0x80($sp)
/* 95CB5B4 80077084 21200002 */  addu       $a0, $s0, $zero
/* 95CB5B8 80077088 7A3B010C */  jal        func_8004EDE8
/* 95CB5BC 8007708C 01000524 */   addiu     $a1, $zero, 0x1
/* 95CB5C0 80077090 21284000 */  addu       $a1, $v0, $zero
/* 95CB5C4 80077094 0002A228 */  slti       $v0, $a1, 0x200
/* 95CB5C8 80077098 09004010 */  beqz       $v0, .Llevel_50_800770C0
/* 95CB5CC 8007709C 0010043C */   lui       $a0, (0x10000000 >> 16)
/* 95CB5D0 800770A0 1400628E */  lw         $v0, 0x14($s3)
/* 95CB5D4 800770A4 00000000 */  nop
/* 95CB5D8 800770A8 1800438C */  lw         $v1, 0x18($v0)
/* 95CB5DC 800770AC 00000000 */  nop
/* 95CB5E0 800770B0 25186400 */  or         $v1, $v1, $a0
/* 95CB5E4 800770B4 180043AC */  sw         $v1, 0x18($v0)
/* 95CB5E8 800770B8 DFDE0108 */  j          .Llevel_50_80077B7C
/* 95CB5EC 800770BC 140060AE */   sw        $zero, 0x14($s3)
.Llevel_50_800770C0:
/* 95CB5F0 800770C0 0680033C */  lui        $v1, %hi(D_80065814)
/* 95CB5F4 800770C4 1458638C */  lw         $v1, %lo(D_80065814)($v1)
/* 95CB5F8 800770C8 00000000 */  nop
/* 95CB5FC 800770CC 0A006624 */  addiu      $a2, $v1, 0xA
/* 95CB600 800770D0 2A10C500 */  slt        $v0, $a2, $a1
/* 95CB604 800770D4 02004014 */  bnez       $v0, .Llevel_50_800770E0
/* 95CB608 800770D8 21200002 */   addu      $a0, $s0, $zero
/* 95CB60C 800770DC F6FF6624 */  addiu      $a2, $v1, -0xA
.Llevel_50_800770E0:
/* 95CB610 800770E0 233C010C */  jal        func_8004F08C
/* 95CB614 800770E4 00000000 */   nop
/* 95CB618 800770E8 0C008426 */  addiu      $a0, $s4, 0xC
/* 95CB61C 800770EC 21288000 */  addu       $a1, $a0, $zero
/* 95CB620 800770F0 7800B027 */  addiu      $s0, $sp, 0x78
/* 95CB624 800770F4 653C010C */  jal        func_8004F194
/* 95CB628 800770F8 21300002 */   addu      $a2, $s0, $zero
/* 95CB62C 800770FC 7800A48F */  lw         $a0, 0x78($sp)
/* 95CB630 80077100 7C00A58F */  lw         $a1, 0x7C($sp)
/* 95CB634 80077104 203A010C */  jal        func_8004E880
/* 95CB638 80077108 21300000 */   addu      $a2, $zero, $zero
/* 95CB63C 8007710C 21208002 */  addu       $a0, $s4, $zero
/* 95CB640 80077110 21284000 */  addu       $a1, $v0, $zero
/* 95CB644 80077114 0A000624 */  addiu      $a2, $zero, 0xA
/* 95CB648 80077118 21380000 */  addu       $a3, $zero, $zero
/* 95CB64C 8007711C 1000A0AF */  sw         $zero, 0x10($sp)
/* 95CB650 80077120 17D6000C */  jal        func_8003585C
/* 95CB654 80077124 1400A0AF */   sw        $zero, 0x14($sp)
/* 95CB658 80077128 21200002 */  addu       $a0, $s0, $zero
/* 95CB65C 8007712C 7A3B010C */  jal        func_8004EDE8
/* 95CB660 80077130 21280000 */   addu      $a1, $zero, $zero
/* 95CB664 80077134 21204000 */  addu       $a0, $v0, $zero
/* 95CB668 80077138 8000A58F */  lw         $a1, 0x80($sp)
.Llevel_50_8007713C:
/* 95CB66C 8007713C 203A010C */  jal        func_8004E880
/* 95CB670 80077140 21300000 */   addu      $a2, $zero, $zero
/* 95CB674 80077144 FF004430 */  andi       $a0, $v0, 0xFF
/* 95CB678 80077148 21280000 */  addu       $a1, $zero, $zero
/* 95CB67C 8007714C 30000624 */  addiu      $a2, $zero, 0x30
/* 95CB680 80077150 06D8000C */  jal        func_80036018
/* 95CB684 80077154 450082A2 */   sb        $v0, 0x45($s4)
/* 95CB688 80077158 DFDE0108 */  j          .Llevel_50_80077B7C
/* 95CB68C 8007715C 450082A2 */   sb        $v0, 0x45($s4)
.L80077160_:
/* 95CB690 80077160 80010224 */  addiu      $v0, $zero, 0x180
/* 95CB694 80077164 080062A6 */  sh         $v0, 0x8($s3)
/* 95CB698 80077168 05000224 */  addiu      $v0, $zero, 0x5
/* 95CB69C 8007716C 040060A6 */  sh         $zero, 0x4($s3)
/* 95CB6A0 80077170 060060A6 */  sh         $zero, 0x6($s3)
/* 95CB6A4 80077174 DFDE0108 */  j          .Llevel_50_80077B7C
/* 95CB6A8 80077178 490082A2 */   sb        $v0, 0x49($s4)
.Llevel_50_8007717C:
/* 95CB6AC 8007717C 0680053C */  lui        $a1, %hi(D_80065830)
/* 95CB6B0 80077180 3058A58C */  lw         $a1, %lo(D_80065830)($a1)
/* 95CB6B4 80077184 00000000 */  nop
/* 95CB6B8 80077188 5500A010 */  beqz       $a1, .Llevel_50_800772E0
/* 95CB6BC 8007718C 3800A427 */   addiu     $a0, $sp, 0x38
/* 95CB6C0 80077190 0780063C */  lui        $a2, %hi(D_80070328)
/* 95CB6C4 80077194 2803C624 */  addiu      $a2, $a2, %lo(D_80070328)
/* 95CB6C8 80077198 723C010C */  jal        func_8004F1C8
/* 95CB6CC 8007719C 0C00A524 */   addiu     $a1, $a1, 0xC
/* 95CB6D0 800771A0 0680043C */  lui        $a0, %hi(D_80065828)
/* 95CB6D4 800771A4 2858848C */  lw         $a0, %lo(D_80065828)($a0)
/* 95CB6D8 800771A8 00000000 */  nop
/* 95CB6DC 800771AC 01048228 */  slti       $v0, $a0, 0x401
/* 95CB6E0 800771B0 15004014 */  bnez       $v0, .Llevel_50_80077208
/* 95CB6E4 800771B4 01408228 */   slti      $v0, $a0, 0x4001
/* 95CB6E8 800771B8 06004014 */  bnez       $v0, .Llevel_50_800771D4
/* 95CB6EC 800771BC 00000000 */   nop
/* 95CB6F0 800771C0 9D3A010C */  jal        func_8004EA74
/* 95CB6F4 800771C4 00000000 */   nop
/* 95CB6F8 800771C8 3800A427 */  addiu      $a0, $sp, 0x38
/* 95CB6FC 800771CC 443C010C */  jal        func_8004F110
/* 95CB700 800771D0 F2FF4524 */   addiu     $a1, $v0, -0xE
.Llevel_50_800771D4:
/* 95CB704 800771D4 0780023C */  lui        $v0, %hi(D_8006C644)
/* 95CB708 800771D8 44C6428C */  lw         $v0, %lo(D_8006C644)($v0)
/* 95CB70C 800771DC 00000000 */  nop
/* 95CB710 800771E0 00110200 */  sll        $v0, $v0, 4
/* 95CB714 800771E4 F0014230 */  andi       $v0, $v0, 0x1F0
/* 95CB718 800771E8 0680013C */  lui        $at, %hi(D_800658A0)
/* 95CB71C 800771EC 21082200 */  addu       $at, $at, $v0
/* 95CB720 800771F0 A0582294 */  lhu        $v0, %lo(D_800658A0)($at)
/* 95CB724 800771F4 3800A427 */  addiu      $a0, $sp, 0x38
/* 95CB728 800771F8 00140200 */  sll        $v0, $v0, 16
/* 95CB72C 800771FC 43150200 */  sra        $v0, $v0, 21
/* 95CB730 80077200 C13B010C */  jal        func_8004EF04
/* 95CB734 80077204 00044524 */   addiu     $a1, $v0, 0x400
.Llevel_50_80077208:
/* 95CB738 80077208 4000A28F */  lw         $v0, 0x40($sp)
/* 95CB73C 8007720C 00000000 */  nop
/* 95CB740 80077210 00FF4228 */  slti       $v0, $v0, -0x100
/* 95CB744 80077214 02004010 */  beqz       $v0, .Llevel_50_80077220
/* 95CB748 80077218 00FF0224 */   addiu     $v0, $zero, -0x100
/* 95CB74C 8007721C 4000A2AF */  sw         $v0, 0x40($sp)
.Llevel_50_80077220:
/* 95CB750 80077220 3800A427 */  addiu      $a0, $sp, 0x38
/* 95CB754 80077224 21280000 */  addu       $a1, $zero, $zero
/* 95CB758 80077228 7A3B010C */  jal        func_8004EDE8
/* 95CB75C 8007722C 440080A2 */   sb        $zero, 0x44($s4)
/* 95CB760 80077230 21204000 */  addu       $a0, $v0, $zero
/* 95CB764 80077234 4000A58F */  lw         $a1, 0x40($sp)
/* 95CB768 80077238 203A010C */  jal        func_8004E880
/* 95CB76C 8007723C 21300000 */   addu      $a2, $zero, $zero
/* 95CB770 80077240 21300000 */  addu       $a2, $zero, $zero
/* 95CB774 80077244 0C00838E */  lw         $v1, 0xC($s4)
/* 95CB778 80077248 0780103C */  lui        $s0, %hi(D_80070328)
/* 95CB77C 8007724C 28031026 */  addiu      $s0, $s0, %lo(D_80070328)
/* 95CB780 80077250 450082A2 */  sb         $v0, 0x45($s4)
/* 95CB784 80077254 0000048E */  lw         $a0, 0x0($s0)
/* 95CB788 80077258 1000828E */  lw         $v0, 0x10($s4)
/* 95CB78C 8007725C 0780053C */  lui        $a1, %hi(D_80070328 + 4)
/* 95CB790 80077260 2C03A58C */  lw         $a1, %lo(D_80070328 + 4)($a1)
/* 95CB794 80077264 23206400 */  subu       $a0, $v1, $a0
/* 95CB798 80077268 203A010C */  jal        func_8004E880
/* 95CB79C 8007726C 23284500 */   subu      $a1, $v0, $a1
/* 95CB7A0 80077270 3800A427 */  addiu      $a0, $sp, 0x38
/* 95CB7A4 80077274 21288000 */  addu       $a1, $a0, $zero
/* 95CB7A8 80077278 21300002 */  addu       $a2, $s0, $zero
/* 95CB7AC 8007727C 653C010C */  jal        func_8004F194
/* 95CB7B0 80077280 460082A2 */   sb        $v0, 0x46($s4)
/* 95CB7B4 80077284 3800A427 */  addiu      $a0, $sp, 0x38
/* 95CB7B8 80077288 21288000 */  addu       $a1, $a0, $zero
/* 95CB7BC 8007728C 0C009026 */  addiu      $s0, $s4, 0xC
/* 95CB7C0 80077290 723C010C */  jal        func_8004F1C8
/* 95CB7C4 80077294 21300002 */   addu      $a2, $s0, $zero
/* 95CB7C8 80077298 3800A427 */  addiu      $a0, $sp, 0x38
/* 95CB7CC 8007729C 443C010C */  jal        func_8004F110
/* 95CB7D0 800772A0 02000524 */   addiu     $a1, $zero, 0x2
/* 95CB7D4 800772A4 21200002 */  addu       $a0, $s0, $zero
/* 95CB7D8 800772A8 21280002 */  addu       $a1, $s0, $zero
/* 95CB7DC 800772AC 653C010C */  jal        func_8004F194
/* 95CB7E0 800772B0 3800A627 */   addiu     $a2, $sp, 0x38
/* 95CB7E4 800772B4 21200002 */  addu       $a0, $s0, $zero
/* 95CB7E8 800772B8 6564000C */  jal        func_80019194
/* 95CB7EC 800772BC 00010524 */   addiu     $a1, $zero, 0x100
/* 95CB7F0 800772C0 2E024010 */  beqz       $v0, .Llevel_50_80077B7C
/* 95CB7F4 800772C4 00000000 */   nop
/* 95CB7F8 800772C8 0780053C */  lui        $a1, %hi(D_8007190C)
/* 95CB7FC 800772CC 0C19A524 */  addiu      $a1, $a1, %lo(D_8007190C)
/* 95CB800 800772D0 5E3C010C */  jal        func_8004F178
/* 95CB804 800772D4 21200002 */   addu      $a0, $s0, $zero
/* 95CB808 800772D8 DFDE0108 */  j          .Llevel_50_80077B7C
/* 95CB80C 800772DC 00000000 */   nop
.Llevel_50_800772E0:
/* 95CB810 800772E0 0780023C */  lui        $v0, %hi(D_80070328 + 0x50)
/* 95CB814 800772E4 7803428C */  lw         $v0, %lo(D_80070328 + 0x50)($v0)
/* 95CB818 800772E8 00000000 */  nop
/* 95CB81C 800772EC 10004014 */  bnez       $v0, .Llevel_50_80077330
/* 95CB820 800772F0 21280000 */   addu      $a1, $zero, $zero
/* 95CB824 800772F4 0780023C */  lui        $v0, %hi(D_80070328 + 0x240)
/* 95CB828 800772F8 6805428C */  lw         $v0, %lo(D_80070328 + 0x240)($v0)
/* 95CB82C 800772FC 00000000 */  nop
/* 95CB830 80077300 0B004014 */  bnez       $v0, .Llevel_50_80077330
/* 95CB834 80077304 00000000 */   nop
/* 95CB838 80077308 0780023C */  lui        $v0, %hi(D_80070328 + 0x20C)
/* 95CB83C 8007730C 3405428C */  lw         $v0, %lo(D_80070328 + 0x20C)($v0)
/* 95CB840 80077310 00000000 */  nop
/* 95CB844 80077314 08004230 */  andi       $v0, $v0, 0x8
/* 95CB848 80077318 05004014 */  bnez       $v0, .Llevel_50_80077330
/* 95CB84C 8007731C 00000000 */   nop
/* 95CB850 80077320 0780023C */  lui        $v0, %hi(D_8006E534)
/* 95CB854 80077324 34E54290 */  lbu        $v0, %lo(D_8006E534)($v0)
/* 95CB858 80077328 00000000 */  nop
/* 95CB85C 8007732C 2B280200 */  sltu       $a1, $zero, $v0
.Llevel_50_80077330:
/* 95CB860 80077330 0600A010 */  beqz       $a1, .Llevel_50_8007734C
/* 95CB864 80077334 78000224 */   addiu     $v0, $zero, 0x78
/* 95CB868 80077338 0D006426 */  addiu      $a0, $s3, 0xD
/* 95CB86C 8007733C 69D6000C */  jal        func_800359A4
/* 95CB870 80077340 01000524 */   addiu     $a1, $zero, 0x1
/* 95CB874 80077344 D4DC0108 */  j          .Llevel_50_80077350
/* 95CB878 80077348 21284000 */   addu      $a1, $v0, $zero
.Llevel_50_8007734C:
/* 95CB87C 8007734C 0D0062A2 */  sb         $v0, 0xD($s3)
.Llevel_50_80077350:
/* 95CB880 80077350 00006286 */  lh         $v0, 0x0($s3)
/* 95CB884 80077354 00000000 */  nop
/* 95CB888 80077358 C800401C */  bgtz       $v0, .Llevel_50_8007767C
/* 95CB88C 8007735C 21204000 */   addu      $a0, $v0, $zero
/* 95CB890 80077360 03006392 */  lbu        $v1, 0x3($s3)
/* 95CB894 80077364 00000000 */  nop
/* 95CB898 80077368 0700622C */  sltiu      $v0, $v1, 0x7
/* 95CB89C 8007736C 49004010 */  beqz       $v0, .Llevel_50_80077494
/* 95CB8A0 80077370 80100300 */   sll       $v0, $v1, 2
/* 95CB8A4 80077374 0780013C */  lui        $at, %hi(jtbl_level_50_800744D0)
/* 95CB8A8 80077378 21082200 */  addu       $at, $at, $v0
/* 95CB8AC 8007737C D044228C */  lw         $v0, %lo(jtbl_level_50_800744D0)($at)
/* 95CB8B0 80077380 00000000 */  nop
/* 95CB8B4 80077384 08004000 */  jr         $v0
/* 95CB8B8 80077388 00000000 */   nop
.L8007738C_:
/* 95CB8BC 8007738C 2400A010 */  beqz       $a1, .Llevel_50_80077420
/* 95CB8C0 80077390 00000000 */   nop
/* 95CB8C4 80077394 9171010C */  jal        func_8005C644
/* 95CB8C8 80077398 00000000 */   nop
/* 95CB8CC 8007739C AA2A4228 */  slti       $v0, $v0, 0x2AAA
/* 95CB8D0 800773A0 1F004010 */  beqz       $v0, .Llevel_50_80077420
/* 95CB8D4 800773A4 21200000 */   addu      $a0, $zero, $zero
/* 95CB8D8 800773A8 DBD8000C */  jal        func_8003636C
/* 95CB8DC 800773AC 09000524 */   addiu     $a1, $zero, 0x9
/* 95CB8E0 800773B0 21184000 */  addu       $v1, $v0, $zero
/* 95CB8E4 800773B4 0A00622C */  sltiu      $v0, $v1, 0xA
/* 95CB8E8 800773B8 35004010 */  beqz       $v0, .Llevel_50_80077490
/* 95CB8EC 800773BC 80100300 */   sll       $v0, $v1, 2
/* 95CB8F0 800773C0 0780013C */  lui        $at, %hi(jtbl_level_50_800744F0)
/* 95CB8F4 800773C4 21082200 */  addu       $at, $at, $v0
/* 95CB8F8 800773C8 F044228C */  lw         $v0, %lo(jtbl_level_50_800744F0)($at)
/* 95CB8FC 800773CC 00000000 */  nop
/* 95CB900 800773D0 08004000 */  jr         $v0
/* 95CB904 800773D4 00000000 */   nop
.L800773D8_:
/* 95CB908 800773D8 10000224 */  addiu      $v0, $zero, 0x10
/* 95CB90C 800773DC 0C0062A2 */  sb         $v0, 0xC($s3)
/* 95CB910 800773E0 03000224 */  addiu      $v0, $zero, 0x3
/* 95CB914 800773E4 24DD0108 */  j          .Llevel_50_80077490
/* 95CB918 800773E8 030062A2 */   sb        $v0, 0x3($s3)
.L800773EC_:
/* 95CB91C 800773EC 0C000224 */  addiu      $v0, $zero, 0xC
/* 95CB920 800773F0 0C0062A2 */  sb         $v0, 0xC($s3)
/* 95CB924 800773F4 02000224 */  addiu      $v0, $zero, 0x2
/* 95CB928 800773F8 24DD0108 */  j          .Llevel_50_80077490
/* 95CB92C 800773FC 030062A2 */   sb        $v0, 0x3($s3)
.L80077400_:
/* 95CB930 80077400 14000224 */  addiu      $v0, $zero, 0x14
/* 95CB934 80077404 0C0062A2 */  sb         $v0, 0xC($s3)
/* 95CB938 80077408 06000224 */  addiu      $v0, $zero, 0x6
/* 95CB93C 8007740C 24DD0108 */  j          .Llevel_50_80077490
/* 95CB940 80077410 030062A2 */   sb        $v0, 0x3($s3)
.L80077414_:
/* 95CB944 80077414 10000224 */  addiu      $v0, $zero, 0x10
/* 95CB948 80077418 16DD0108 */  j          .Llevel_50_80077458
/* 95CB94C 8007741C 0C0062A2 */   sb        $v0, 0xC($s3)
.Llevel_50_80077420:
/* 95CB950 80077420 03006392 */  lbu        $v1, 0x3($s3)
/* 95CB954 80077424 03000224 */  addiu      $v0, $zero, 0x3
/* 95CB958 80077428 16006210 */  beq        $v1, $v0, .Llevel_50_80077484
/* 95CB95C 8007742C 04000224 */   addiu     $v0, $zero, 0x4
/* 95CB960 80077430 23DD0108 */  j          .Llevel_50_8007748C
/* 95CB964 80077434 0C0062A2 */   sb        $v0, 0xC($s3)
.L80077438_:
/* 95CB968 80077438 0C000224 */  addiu      $v0, $zero, 0xC
/* 95CB96C 8007743C 0900A010 */  beqz       $a1, .Llevel_50_80077464
/* 95CB970 80077440 0C0062A2 */   sb        $v0, 0xC($s3)
/* 95CB974 80077444 9171010C */  jal        func_8005C644
/* 95CB978 80077448 00000000 */   nop
/* 95CB97C 8007744C FF3F4228 */  slti       $v0, $v0, 0x3FFF
/* 95CB980 80077450 05004010 */  beqz       $v0, .Llevel_50_80077468
/* 95CB984 80077454 01000224 */   addiu     $v0, $zero, 0x1
.Llevel_50_80077458:
/* 95CB988 80077458 04000224 */  addiu      $v0, $zero, 0x4
/* 95CB98C 8007745C 24DD0108 */  j          .Llevel_50_80077490
/* 95CB990 80077460 030062A2 */   sb        $v0, 0x3($s3)
.Llevel_50_80077464:
/* 95CB994 80077464 01000224 */  addiu      $v0, $zero, 0x1
.Llevel_50_80077468:
/* 95CB998 80077468 24DD0108 */  j          .Llevel_50_80077490
/* 95CB99C 8007746C 030062A2 */   sb        $v0, 0x3($s3)
.L80077470_:
/* 95CB9A0 80077470 10000224 */  addiu      $v0, $zero, 0x10
/* 95CB9A4 80077474 0C0062A2 */  sb         $v0, 0xC($s3)
/* 95CB9A8 80077478 05000224 */  addiu      $v0, $zero, 0x5
/* 95CB9AC 8007747C 24DD0108 */  j          .Llevel_50_80077490
/* 95CB9B0 80077480 030062A2 */   sb        $v0, 0x3($s3)
.Llevel_50_80077484:
/* 95CB9B4 80077484 10000224 */  addiu      $v0, $zero, 0x10
/* 95CB9B8 80077488 0C0062A2 */  sb         $v0, 0xC($s3)
.Llevel_50_8007748C:
/* 95CB9BC 8007748C 030060A2 */  sb         $zero, 0x3($s3)
.Llevel_50_80077490:
/* 95CB9C0 80077490 03006392 */  lbu        $v1, 0x3($s3)
.Llevel_50_80077494:
/* 95CB9C4 80077494 00000000 */  nop
/* 95CB9C8 80077498 0700622C */  sltiu      $v0, $v1, 0x7
/* 95CB9CC 8007749C B7014010 */  beqz       $v0, .Llevel_50_80077B7C
/* 95CB9D0 800774A0 80100300 */   sll       $v0, $v1, 2
/* 95CB9D4 800774A4 0780013C */  lui        $at, %hi(jtbl_level_50_80074518)
/* 95CB9D8 800774A8 21082200 */  addu       $at, $at, $v0
/* 95CB9DC 800774AC 1845228C */  lw         $v0, %lo(jtbl_level_50_80074518)($at)
/* 95CB9E0 800774B0 00000000 */  nop
/* 95CB9E4 800774B4 08004000 */  jr         $v0
/* 95CB9E8 800774B8 00000000 */   nop
.L800774BC_:
/* 95CB9EC 800774BC A8FD0224 */  addiu      $v0, $zero, -0x258
/* 95CB9F0 800774C0 9171010C */  jal        func_8005C644
/* 95CB9F4 800774C4 3800A2AF */   sw        $v0, 0x38($sp)
/* 95CB9F8 800774C8 10034230 */  andi       $v0, $v0, 0x310
/* 95CB9FC 800774CC 0780033C */  lui        $v1, %hi(D_8006E044)
/* 95CBA00 800774D0 44E0638C */  lw         $v1, %lo(D_8006E044)($v1)
/* 95CBA04 800774D4 78FE4224 */  addiu      $v0, $v0, -0x188
/* 95CBA08 800774D8 3C00A2AF */  sw         $v0, 0x3C($sp)
/* 95CBA0C 800774DC 02000224 */  addiu      $v0, $zero, 0x2
/* 95CBA10 800774E0 06006214 */  bne        $v1, $v0, .Llevel_50_800774FC
/* 95CBA14 800774E4 00000000 */   nop
/* 95CBA18 800774E8 9171010C */  jal        func_8005C644
/* 95CBA1C 800774EC 00000000 */   nop
/* 95CBA20 800774F0 7F004230 */  andi       $v0, $v0, 0x7F
/* 95CBA24 800774F4 43DD0108 */  j          .Llevel_50_8007750C
/* 95CBA28 800774F8 64004224 */   addiu     $v0, $v0, 0x64
.Llevel_50_800774FC:
/* 95CBA2C 800774FC 9171010C */  jal        func_8005C644
/* 95CBA30 80077500 00000000 */   nop
/* 95CBA34 80077504 FF014230 */  andi       $v0, $v0, 0x1FF
/* 95CBA38 80077508 38FF4224 */  addiu      $v0, $v0, -0xC8
.Llevel_50_8007750C:
/* 95CBA3C 8007750C 4000A2AF */  sw         $v0, 0x40($sp)
/* 95CBA40 80077510 0A006292 */  lbu        $v0, 0xA($s3)
/* 95CBA44 80077514 00000000 */  nop
/* 95CBA48 80077518 06004010 */  beqz       $v0, .Llevel_50_80077534
/* 95CBA4C 8007751C 38FF0224 */   addiu     $v0, $zero, -0xC8
/* 95CBA50 80077520 9171010C */  jal        func_8005C644
/* 95CBA54 80077524 3800A2AF */   sw        $v0, 0x38($sp)
/* 95CBA58 80077528 7F004230 */  andi       $v0, $v0, 0x7F
/* 95CBA5C 8007752C 06FF4224 */  addiu      $v0, $v0, -0xFA
/* 95CBA60 80077530 4000A2AF */  sw         $v0, 0x40($sp)
.Llevel_50_80077534:
/* 95CBA64 80077534 3800A28F */  lw         $v0, 0x38($sp)
/* 95CBA68 80077538 03006392 */  lbu        $v1, 0x3($s3)
/* 95CBA6C 8007753C 040062A6 */  sh         $v0, 0x4($s3)
/* 95CBA70 80077540 3C00A28F */  lw         $v0, 0x3C($sp)
/* 95CBA74 80077544 00000000 */  nop
/* 95CBA78 80077548 060062A6 */  sh         $v0, 0x6($s3)
/* 95CBA7C 8007754C 4000A28F */  lw         $v0, 0x40($sp)
/* 95CBA80 80077550 47006014 */  bnez       $v1, .Llevel_50_80077670
/* 95CBA84 80077554 080062A6 */   sh        $v0, 0x8($s3)
/* 95CBA88 80077558 9171010C */  jal        func_8005C644
/* 95CBA8C 8007755C 00000000 */   nop
/* 95CBA90 80077560 3F004230 */  andi       $v0, $v0, 0x3F
/* 95CBA94 80077564 3C004224 */  addiu      $v0, $v0, 0x3C
/* 95CBA98 80077568 000062A6 */  sh         $v0, 0x0($s3)
/* 95CBA9C 8007756C 05000224 */  addiu      $v0, $zero, 0x5
/* 95CBAA0 80077570 DFDE0108 */  j          .Llevel_50_80077B7C
/* 95CBAA4 80077574 0B0062A2 */   sb        $v0, 0xB($s3)
.L80077578_:
/* 95CBAA8 80077578 F4010224 */  addiu      $v0, $zero, 0x1F4
/* 95CBAAC 8007757C 040062A6 */  sh         $v0, 0x4($s3)
/* 95CBAB0 80077580 2C010224 */  addiu      $v0, $zero, 0x12C
/* 95CBAB4 80077584 080062A6 */  sh         $v0, 0x8($s3)
/* 95CBAB8 80077588 78000224 */  addiu      $v0, $zero, 0x78
/* 95CBABC 8007758C 060060A6 */  sh         $zero, 0x6($s3)
/* 95CBAC0 80077590 DFDE0108 */  j          .Llevel_50_80077B7C
/* 95CBAC4 80077594 000062A6 */   sh        $v0, 0x0($s3)
.L80077598_:
/* 95CBAC8 80077598 9171010C */  jal        func_8005C644
/* 95CBACC 8007759C 00000000 */   nop
/* 95CBAD0 800775A0 1F004230 */  andi       $v0, $v0, 0x1F
/* 95CBAD4 800775A4 3C004224 */  addiu      $v0, $v0, 0x3C
/* 95CBAD8 800775A8 DFDE0108 */  j          .Llevel_50_80077B7C
/* 95CBADC 800775AC 000062A6 */   sh        $v0, 0x0($s3)
.L800775B0_:
/* 95CBAE0 800775B0 21200000 */  addu       $a0, $zero, $zero
/* 95CBAE4 800775B4 DBD8000C */  jal        func_8003636C
/* 95CBAE8 800775B8 03000524 */   addiu     $a1, $zero, 0x3
/* 95CBAEC 800775BC BC020324 */  addiu      $v1, $zero, 0x2BC
/* 95CBAF0 800775C0 21804000 */  addu       $s0, $v0, $zero
/* 95CBAF4 800775C4 040063A6 */  sh         $v1, 0x4($s3)
/* 95CBAF8 800775C8 03006392 */  lbu        $v1, 0x3($s3)
/* 95CBAFC 800775CC 04000224 */  addiu      $v0, $zero, 0x4
/* 95CBB00 800775D0 08006214 */  bne        $v1, $v0, .Llevel_50_800775F4
/* 95CBB04 800775D4 00000000 */   nop
/* 95CBB08 800775D8 9171010C */  jal        func_8005C644
/* 95CBB0C 800775DC 00000000 */   nop
/* 95CBB10 800775E0 FF3F4228 */  slti       $v0, $v0, 0x3FFF
/* 95CBB14 800775E4 07004014 */  bnez       $v0, .Llevel_50_80077604
/* 95CBB18 800775E8 40101000 */   sll       $v0, $s0, 1
/* 95CBB1C 800775EC 88DD0108 */  j          .Llevel_50_80077620
/* 95CBB20 800775F0 21105000 */   addu      $v0, $v0, $s0
.Llevel_50_800775F4:
/* 95CBB24 800775F4 06006286 */  lh         $v0, 0x6($s3)
/* 95CBB28 800775F8 00000000 */  nop
/* 95CBB2C 800775FC 07004104 */  bgez       $v0, .Llevel_50_8007761C
/* 95CBB30 80077600 40101000 */   sll       $v0, $s0, 1
.Llevel_50_80077604:
/* 95CBB34 80077604 21105000 */  addu       $v0, $v0, $s0
/* 95CBB38 80077608 C0100200 */  sll        $v0, $v0, 3
/* 95CBB3C 8007760C 21105000 */  addu       $v0, $v0, $s0
/* 95CBB40 80077610 40100200 */  sll        $v0, $v0, 1
/* 95CBB44 80077614 8DDD0108 */  j          .Llevel_50_80077634
/* 95CBB48 80077618 64004224 */   addiu     $v0, $v0, 0x64
.Llevel_50_8007761C:
/* 95CBB4C 8007761C 21105000 */  addu       $v0, $v0, $s0
.Llevel_50_80077620:
/* 95CBB50 80077620 C0100200 */  sll        $v0, $v0, 3
/* 95CBB54 80077624 21105000 */  addu       $v0, $v0, $s0
/* 95CBB58 80077628 40100200 */  sll        $v0, $v0, 1
/* 95CBB5C 8007762C 23100200 */  negu       $v0, $v0
/* 95CBB60 80077630 9CFF4224 */  addiu      $v0, $v0, -0x64
.Llevel_50_80077634:
/* 95CBB64 80077634 060062A6 */  sh         $v0, 0x6($s3)
/* 95CBB68 80077638 21200000 */  addu       $a0, $zero, $zero
/* 95CBB6C 8007763C DBD8000C */  jal        func_8003636C
/* 95CBB70 80077640 03000524 */   addiu     $a1, $zero, 0x3
/* 95CBB74 80077644 40180200 */  sll        $v1, $v0, 1
/* 95CBB78 80077648 21186200 */  addu       $v1, $v1, $v0
/* 95CBB7C 8007764C C0180300 */  sll        $v1, $v1, 3
/* 95CBB80 80077650 21186200 */  addu       $v1, $v1, $v0
/* 95CBB84 80077654 40180300 */  sll        $v1, $v1, 1
/* 95CBB88 80077658 3C000224 */  addiu      $v0, $zero, 0x3C
/* 95CBB8C 8007765C 000062A6 */  sh         $v0, 0x0($s3)
/* 95CBB90 80077660 0A000224 */  addiu      $v0, $zero, 0xA
/* 95CBB94 80077664 080063A6 */  sh         $v1, 0x8($s3)
/* 95CBB98 80077668 DFDE0108 */  j          .Llevel_50_80077B7C
/* 95CBB9C 8007766C 0B0062A2 */   sb        $v0, 0xB($s3)
.Llevel_50_80077670:
/* 95CBBA0 80077670 78000224 */  addiu      $v0, $zero, 0x78
/* 95CBBA4 80077674 DFDE0108 */  j          .Llevel_50_80077B7C
/* 95CBBA8 80077678 000062A6 */   sh        $v0, 0x0($s3)
.Llevel_50_8007767C:
/* 95CBBAC 8007767C 0780023C */  lui        $v0, %hi(D_8006C648)
/* 95CBBB0 80077680 48C6428C */  lw         $v0, %lo(D_8006C648)($v0)
/* 95CBBB4 80077684 03006392 */  lbu        $v1, 0x3($s3)
/* 95CBBB8 80077688 23108200 */  subu       $v0, $a0, $v0
/* 95CBBBC 8007768C 04006010 */  beqz       $v1, .Llevel_50_800776A0
/* 95CBBC0 80077690 000062A6 */   sh        $v0, 0x0($s3)
/* 95CBBC4 80077694 0200A014 */  bnez       $a1, .Llevel_50_800776A0
/* 95CBBC8 80077698 00000000 */   nop
/* 95CBBCC 8007769C 000060A6 */  sh         $zero, 0x0($s3)
.Llevel_50_800776A0:
/* 95CBBD0 800776A0 03006392 */  lbu        $v1, 0x3($s3)
/* 95CBBD4 800776A4 00000000 */  nop
/* 95CBBD8 800776A8 0700622C */  sltiu      $v0, $v1, 0x7
/* 95CBBDC 800776AC 33014010 */  beqz       $v0, .Llevel_50_80077B7C
/* 95CBBE0 800776B0 80100300 */   sll       $v0, $v1, 2
/* 95CBBE4 800776B4 0780013C */  lui        $at, %hi(jtbl_level_50_80074538)
/* 95CBBE8 800776B8 21082200 */  addu       $at, $at, $v0
/* 95CBBEC 800776BC 3845228C */  lw         $v0, %lo(jtbl_level_50_80074538)($at)
/* 95CBBF0 800776C0 00000000 */  nop
/* 95CBBF4 800776C4 08004000 */  jr         $v0
/* 95CBBF8 800776C8 00000000 */   nop
.L800776CC_:
/* 95CBBFC 800776CC 0B006392 */  lbu        $v1, 0xB($s3)
/* 95CBC00 800776D0 00000000 */  nop
/* 95CBC04 800776D4 01006230 */  andi       $v0, $v1, 0x1
/* 95CBC08 800776D8 36004010 */  beqz       $v0, .Llevel_50_800777B4
/* 95CBC0C 800776DC 02000224 */   addiu     $v0, $zero, 0x2
/* 95CBC10 800776E0 0780043C */  lui        $a0, %hi(D_8006E044)
/* 95CBC14 800776E4 44E0848C */  lw         $a0, %lo(D_8006E044)($a0)
/* 95CBC18 800776E8 00000000 */  nop
/* 95CBC1C 800776EC 06008210 */  beq        $a0, $v0, .Llevel_50_80077708
/* 95CBC20 800776F0 0C000224 */   addiu     $v0, $zero, 0xC
/* 95CBC24 800776F4 0780033C */  lui        $v1, %hi(D_80070328 + 0x50)
/* 95CBC28 800776F8 7803638C */  lw         $v1, %lo(D_80070328 + 0x50)($v1)
/* 95CBC2C 800776FC 00000000 */  nop
/* 95CBC30 80077700 14006214 */  bne        $v1, $v0, .Llevel_50_80077754
/* 95CBC34 80077704 07000224 */   addiu     $v0, $zero, 0x7
.Llevel_50_80077708:
/* 95CBC38 80077708 0780023C */  lui        $v0, %hi(D_80070328 + 0xB0)
/* 95CBC3C 8007770C D803428C */  lw         $v0, %lo(D_80070328 + 0xB0)($v0)
/* 95CBC40 80077710 04006386 */  lh         $v1, 0x4($s3)
/* 95CBC44 80077714 83100200 */  sra        $v0, $v0, 2
/* 95CBC48 80077718 21186200 */  addu       $v1, $v1, $v0
/* 95CBC4C 8007771C 3800A3AF */  sw         $v1, 0x38($sp)
/* 95CBC50 80077720 06006286 */  lh         $v0, 0x6($s3)
/* 95CBC54 80077724 0780033C */  lui        $v1, %hi(D_80070328 + 0x50)
/* 95CBC58 80077728 7803638C */  lw         $v1, %lo(D_80070328 + 0x50)($v1)
/* 95CBC5C 8007772C 3C00A2AF */  sw         $v0, 0x3C($sp)
/* 95CBC60 80077730 08006486 */  lh         $a0, 0x8($s3)
/* 95CBC64 80077734 0C000224 */  addiu      $v0, $zero, 0xC
/* 95CBC68 80077738 14006210 */  beq        $v1, $v0, .Llevel_50_8007778C
/* 95CBC6C 8007773C 4000A4AF */   sw        $a0, 0x40($sp)
/* 95CBC70 80077740 64008228 */  slti       $v0, $a0, 0x64
/* 95CBC74 80077744 11004010 */  beqz       $v0, .Llevel_50_8007778C
/* 95CBC78 80077748 64000224 */   addiu     $v0, $zero, 0x64
/* 95CBC7C 8007774C E3DD0108 */  j          .Llevel_50_8007778C
/* 95CBC80 80077750 4000A2AF */   sw        $v0, 0x40($sp)
.Llevel_50_80077754:
/* 95CBC84 80077754 04008214 */  bne        $a0, $v0, .Llevel_50_80077768
/* 95CBC88 80077758 00000000 */   nop
/* 95CBC8C 8007775C 04006286 */  lh         $v0, 0x4($s3)
/* 95CBC90 80077760 DBDD0108 */  j          .Llevel_50_8007776C
/* 95CBC94 80077764 00FE4224 */   addiu     $v0, $v0, -0x200
.Llevel_50_80077768:
/* 95CBC98 80077768 04006286 */  lh         $v0, 0x4($s3)
.Llevel_50_8007776C:
/* 95CBC9C 8007776C 00000000 */  nop
/* 95CBCA0 80077770 3800A2AF */  sw         $v0, 0x38($sp)
/* 95CBCA4 80077774 06006286 */  lh         $v0, 0x6($s3)
/* 95CBCA8 80077778 00000000 */  nop
/* 95CBCAC 8007777C 3C00A2AF */  sw         $v0, 0x3C($sp)
/* 95CBCB0 80077780 08006286 */  lh         $v0, 0x8($s3)
/* 95CBCB4 80077784 00000000 */  nop
/* 95CBCB8 80077788 4000A2AF */  sw         $v0, 0x40($sp)
.Llevel_50_8007778C:
/* 95CBCBC 8007778C 0780103C */  lui        $s0, %hi(D_80070328 + 0x30)
/* 95CBCC0 80077790 58031026 */  addiu      $s0, $s0, %lo(D_80070328 + 0x30)
/* 95CBCC4 80077794 21200002 */  addu       $a0, $s0, $zero
/* 95CBCC8 80077798 3800A527 */  addiu      $a1, $sp, 0x38
/* 95CBCCC 8007779C 5B3B010C */  jal        func_8004ED6C
/* 95CBCD0 800777A0 2130A000 */   addu      $a2, $a1, $zero
/* 95CBCD4 800777A4 3800A427 */  addiu      $a0, $sp, 0x38
/* 95CBCD8 800777A8 21288000 */  addu       $a1, $a0, $zero
/* 95CBCDC 800777AC FFDD0108 */  j          .Llevel_50_800777FC
/* 95CBCE0 800777B0 D0FF0626 */   addiu     $a2, $s0, -0x30
.Llevel_50_800777B4:
/* 95CBCE4 800777B4 02006230 */  andi       $v0, $v1, 0x2
/* 95CBCE8 800777B8 12004010 */  beqz       $v0, .Llevel_50_80077804
/* 95CBCEC 800777BC 8800B027 */   addiu     $s0, $sp, 0x88
/* 95CBCF0 800777C0 21200002 */  addu       $a0, $s0, $zero
/* 95CBCF4 800777C4 0780113C */  lui        $s1, %hi(D_8006E00C)
/* 95CBCF8 800777C8 0CE03126 */  addiu      $s1, $s1, %lo(D_8006E00C)
/* 95CBCFC 800777CC 3D3B010C */  jal        func_8004ECF4
/* 95CBD00 800777D0 21282002 */   addu      $a1, $s1, $zero
/* 95CBD04 800777D4 3800A427 */  addiu      $a0, $sp, 0x38
/* 95CBD08 800777D8 553D010C */  jal        func_8004F554
/* 95CBD0C 800777DC 04006526 */   addiu     $a1, $s3, 0x4
/* 95CBD10 800777E0 21200002 */  addu       $a0, $s0, $zero
/* 95CBD14 800777E4 3800A527 */  addiu      $a1, $sp, 0x38
/* 95CBD18 800777E8 5B3B010C */  jal        func_8004ED6C
/* 95CBD1C 800777EC 2130A000 */   addu      $a2, $a1, $zero
/* 95CBD20 800777F0 3800A427 */  addiu      $a0, $sp, 0x38
/* 95CBD24 800777F4 21288000 */  addu       $a1, $a0, $zero
/* 95CBD28 800777F8 14002626 */  addiu      $a2, $s1, 0x14
.Llevel_50_800777FC:
/* 95CBD2C 800777FC 653C010C */  jal        func_8004F194
/* 95CBD30 80077800 00000000 */   nop
.Llevel_50_80077804:
/* 95CBD34 80077804 3800A427 */  addiu      $a0, $sp, 0x38
/* 95CBD38 80077808 21288000 */  addu       $a1, $a0, $zero
/* 95CBD3C 8007780C 0C009026 */  addiu      $s0, $s4, 0xC
/* 95CBD40 80077810 723C010C */  jal        func_8004F1C8
/* 95CBD44 80077814 21300002 */   addu      $a2, $s0, $zero
/* 95CBD48 80077818 3800A427 */  addiu      $a0, $sp, 0x38
/* 95CBD4C 8007781C 443C010C */  jal        func_8004F110
/* 95CBD50 80077820 02000524 */   addiu     $a1, $zero, 0x2
/* 95CBD54 80077824 21200002 */  addu       $a0, $s0, $zero
/* 95CBD58 80077828 21280002 */  addu       $a1, $s0, $zero
/* 95CBD5C 8007782C 653C010C */  jal        func_8004F194
/* 95CBD60 80077830 3800A627 */   addiu     $a2, $sp, 0x38
/* 95CBD64 80077834 21200002 */  addu       $a0, $s0, $zero
/* 95CBD68 80077838 6564000C */  jal        func_80019194
/* 95CBD6C 8007783C 00010524 */   addiu     $a1, $zero, 0x100
/* 95CBD70 80077840 05004010 */  beqz       $v0, .Llevel_50_80077858
/* 95CBD74 80077844 00000000 */   nop
/* 95CBD78 80077848 0780053C */  lui        $a1, %hi(D_8007190C)
/* 95CBD7C 8007784C 0C19A524 */  addiu      $a1, $a1, %lo(D_8007190C)
/* 95CBD80 80077850 5E3C010C */  jal        func_8004F178
/* 95CBD84 80077854 21200002 */   addu      $a0, $s0, $zero
.Llevel_50_80077858:
/* 95CBD88 80077858 4000A28F */  lw         $v0, 0x40($sp)
/* 95CBD8C 8007785C 00000000 */  nop
/* 95CBD90 80077860 21004228 */  slti       $v0, $v0, 0x21
/* 95CBD94 80077864 02004014 */  bnez       $v0, .Llevel_50_80077870
/* 95CBD98 80077868 20000224 */   addiu     $v0, $zero, 0x20
/* 95CBD9C 8007786C 4000A2AF */  sw         $v0, 0x40($sp)
.Llevel_50_80077870:
/* 95CBDA0 80077870 4000A28F */  lw         $v0, 0x40($sp)
/* 95CBDA4 80077874 00000000 */  nop
/* 95CBDA8 80077878 E0FF4228 */  slti       $v0, $v0, -0x20
/* 95CBDAC 8007787C 02004010 */  beqz       $v0, .Llevel_50_80077888
/* 95CBDB0 80077880 E0FF0224 */   addiu     $v0, $zero, -0x20
/* 95CBDB4 80077884 4000A2AF */  sw         $v0, 0x40($sp)
.Llevel_50_80077888:
/* 95CBDB8 80077888 440080A2 */  sb         $zero, 0x44($s4)
/* 95CBDBC 8007788C 4000A28F */  lw         $v0, 0x40($sp)
/* 95CBDC0 80077890 00000000 */  nop
/* 95CBDC4 80077894 450082A2 */  sb         $v0, 0x45($s4)
/* 95CBDC8 80077898 0B006392 */  lbu        $v1, 0xB($s3)
/* 95CBDCC 8007789C 00000000 */  nop
/* 95CBDD0 800778A0 04006230 */  andi       $v0, $v1, 0x4
/* 95CBDD4 800778A4 05004010 */  beqz       $v0, .Llevel_50_800778BC
/* 95CBDD8 800778A8 21208002 */   addu      $a0, $s4, $zero
/* 95CBDDC 800778AC 0780053C */  lui        $a1, %hi(D_80070328 + 0xE)
/* 95CBDE0 800778B0 3603A590 */  lbu        $a1, %lo(D_80070328 + 0xE)($a1)
/* 95CBDE4 800778B4 B4DE0108 */  j          .Llevel_50_80077AD0
/* 95CBDE8 800778B8 00000000 */   nop
.Llevel_50_800778BC:
/* 95CBDEC 800778BC 08006230 */  andi       $v0, $v1, 0x8
/* 95CBDF0 800778C0 AE004010 */  beqz       $v0, .Llevel_50_80077B7C
/* 95CBDF4 800778C4 21380000 */   addu      $a3, $zero, $zero
/* 95CBDF8 800778C8 0780053C */  lui        $a1, %hi(D_8006E040)
/* 95CBDFC 800778CC 40E0A594 */  lhu        $a1, %lo(D_8006E040)($a1)
/* 95CBE00 800778D0 0C006692 */  lbu        $a2, 0xC($s3)
/* 95CBE04 800778D4 1000A0AF */  sw         $zero, 0x10($sp)
/* 95CBE08 800778D8 1400A0AF */  sw         $zero, 0x14($sp)
/* 95CBE0C 800778DC 002C0500 */  sll        $a1, $a1, 16
/* 95CBE10 800778E0 032D0500 */  sra        $a1, $a1, 20
/* 95CBE14 800778E4 8000A524 */  addiu      $a1, $a1, 0x80
/* 95CBE18 800778E8 17D6000C */  jal        func_8003585C
/* 95CBE1C 800778EC FF00A530 */   andi      $a1, $a1, 0xFF
/* 95CBE20 800778F0 DFDE0108 */  j          .Llevel_50_80077B7C
/* 95CBE24 800778F4 00000000 */   nop
.L800778F8_:
/* 95CBE28 800778F8 A000B027 */  addiu      $s0, $sp, 0xA0
/* 95CBE2C 800778FC 21200002 */  addu       $a0, $s0, $zero
/* 95CBE30 80077900 0C009626 */  addiu      $s6, $s4, 0xC
/* 95CBE34 80077904 2128C002 */  addu       $a1, $s6, $zero
/* 95CBE38 80077908 0780123C */  lui        $s2, %hi(D_80070328)
/* 95CBE3C 8007790C 28035226 */  addiu      $s2, $s2, %lo(D_80070328)
/* 95CBE40 80077910 723C010C */  jal        func_8004F1C8
/* 95CBE44 80077914 21304002 */   addu      $a2, $s2, $zero
/* 95CBE48 80077918 21200002 */  addu       $a0, $s0, $zero
/* 95CBE4C 8007791C 7A3B010C */  jal        func_8004EDE8
/* 95CBE50 80077920 21280000 */   addu      $a1, $zero, $zero
/* 95CBE54 80077924 21884000 */  addu       $s1, $v0, $zero
/* 95CBE58 80077928 A000A48F */  lw         $a0, 0xA0($sp)
/* 95CBE5C 8007792C A400A58F */  lw         $a1, 0xA4($sp)
/* 95CBE60 80077930 203A010C */  jal        func_8004E880
/* 95CBE64 80077934 21300000 */   addu      $a2, $zero, $zero
/* 95CBE68 80077938 21A84000 */  addu       $s5, $v0, $zero
/* 95CBE6C 8007793C 21200002 */  addu       $a0, $s0, $zero
/* 95CBE70 80077940 553D010C */  jal        func_8004F554
/* 95CBE74 80077944 04006526 */   addiu     $a1, $s3, 0x4
/* 95CBE78 80077948 30004426 */  addiu      $a0, $s2, 0x30
/* 95CBE7C 8007794C 21280002 */  addu       $a1, $s0, $zero
/* 95CBE80 80077950 5B3B010C */  jal        func_8004ED6C
/* 95CBE84 80077954 21300002 */   addu      $a2, $s0, $zero
/* 95CBE88 80077958 21200002 */  addu       $a0, $s0, $zero
/* 95CBE8C 8007795C 7A3B010C */  jal        func_8004EDE8
/* 95CBE90 80077960 21280000 */   addu      $a1, $zero, $zero
/* 95CBE94 80077964 21300000 */  addu       $a2, $zero, $zero
/* 95CBE98 80077968 A000A48F */  lw         $a0, 0xA0($sp)
/* 95CBE9C 8007796C A400A58F */  lw         $a1, 0xA4($sp)
/* 95CBEA0 80077970 203A010C */  jal        func_8004E880
/* 95CBEA4 80077974 21804000 */   addu      $s0, $v0, $zero
/* 95CBEA8 80077978 21204000 */  addu       $a0, $v0, $zero
/* 95CBEAC 8007797C 2128A002 */  addu       $a1, $s5, $zero
/* 95CBEB0 80077980 23801102 */  subu       $s0, $s0, $s1
/* 95CBEB4 80077984 A93C010C */  jal        func_8004F2A4
/* 95CBEB8 80077988 C3801000 */   sra       $s0, $s0, 3
/* 95CBEBC 8007798C C3100200 */  sra        $v0, $v0, 3
/* 95CBEC0 80077990 2110A202 */  addu       $v0, $s5, $v0
/* 95CBEC4 80077994 FF005530 */  andi       $s5, $v0, 0xFF
/* 95CBEC8 80077998 40281500 */  sll        $a1, $s5, 1
/* 95CBECC 8007799C 0680013C */  lui        $at, %hi(D_80065920)
/* 95CBED0 800779A0 21082500 */  addu       $at, $at, $a1
/* 95CBED4 800779A4 20592284 */  lh         $v0, %lo(D_80065920)($at)
/* 95CBED8 800779A8 21883002 */  addu       $s1, $s1, $s0
/* 95CBEDC 800779AC 18005100 */  mult       $v0, $s1
/* 95CBEE0 800779B0 A800A38F */  lw         $v1, 0xA8($sp)
/* 95CBEE4 800779B4 0000448E */  lw         $a0, 0x0($s2)
/* 95CBEE8 800779B8 0780063C */  lui        $a2, %hi(D_80070328 + 8)
/* 95CBEEC 800779BC 3003C68C */  lw         $a2, %lo(D_80070328 + 8)($a2)
/* 95CBEF0 800779C0 12400000 */  mflo       $t0
/* 95CBEF4 800779C4 03130800 */  sra        $v0, $t0, 12
/* 95CBEF8 800779C8 21104400 */  addu       $v0, $v0, $a0
/* 95CBEFC 800779CC 0C0082AE */  sw         $v0, 0xC($s4)
/* 95CBF00 800779D0 0680013C */  lui        $at, %hi(D_800658A0)
/* 95CBF04 800779D4 21082500 */  addu       $at, $at, $a1
/* 95CBF08 800779D8 A0582284 */  lh         $v0, %lo(D_800658A0)($at)
/* 95CBF0C 800779DC 00000000 */  nop
/* 95CBF10 800779E0 18005100 */  mult       $v0, $s1
/* 95CBF14 800779E4 21186600 */  addu       $v1, $v1, $a2
/* 95CBF18 800779E8 2120C002 */  addu       $a0, $s6, $zero
/* 95CBF1C 800779EC 1400828E */  lw         $v0, 0x14($s4)
/* 95CBF20 800779F0 00010524 */  addiu      $a1, $zero, 0x100
/* 95CBF24 800779F4 23186200 */  subu       $v1, $v1, $v0
/* 95CBF28 800779F8 C3800300 */  sra        $s0, $v1, 3
/* 95CBF2C 800779FC 1400828E */  lw         $v0, 0x14($s4)
/* 95CBF30 80077A00 0780033C */  lui        $v1, %hi(D_80070328 + 4)
/* 95CBF34 80077A04 2C03638C */  lw         $v1, %lo(D_80070328 + 4)($v1)
/* 95CBF38 80077A08 21105000 */  addu       $v0, $v0, $s0
/* 95CBF3C 80077A0C 140082AE */  sw         $v0, 0x14($s4)
/* 95CBF40 80077A10 12400000 */  mflo       $t0
/* 95CBF44 80077A14 03130800 */  sra        $v0, $t0, 12
/* 95CBF48 80077A18 21104300 */  addu       $v0, $v0, $v1
/* 95CBF4C 80077A1C 6564000C */  jal        func_80019194
/* 95CBF50 80077A20 100082AE */   sw        $v0, 0x10($s4)
/* 95CBF54 80077A24 06004010 */  beqz       $v0, .Llevel_50_80077A40
/* 95CBF58 80077A28 2100022A */   slti      $v0, $s0, 0x21
/* 95CBF5C 80077A2C 0780053C */  lui        $a1, %hi(D_8007190C)
/* 95CBF60 80077A30 0C19A524 */  addiu      $a1, $a1, %lo(D_8007190C)
/* 95CBF64 80077A34 5E3C010C */  jal        func_8004F178
/* 95CBF68 80077A38 2120C002 */   addu      $a0, $s6, $zero
/* 95CBF6C 80077A3C 2100022A */  slti       $v0, $s0, 0x21
.Llevel_50_80077A40:
/* 95CBF70 80077A40 02004014 */  bnez       $v0, .Llevel_50_80077A4C
/* 95CBF74 80077A44 440080A2 */   sb        $zero, 0x44($s4)
/* 95CBF78 80077A48 20001024 */  addiu      $s0, $zero, 0x20
.Llevel_50_80077A4C:
/* 95CBF7C 80077A4C E0FF022A */  slti       $v0, $s0, -0x20
/* 95CBF80 80077A50 02004010 */  beqz       $v0, .Llevel_50_80077A5C
/* 95CBF84 80077A54 00000000 */   nop
/* 95CBF88 80077A58 E0FF1024 */  addiu      $s0, $zero, -0x20
.Llevel_50_80077A5C:
/* 95CBF8C 80077A5C 450090A2 */  sb         $s0, 0x45($s4)
/* 95CBF90 80077A60 03006392 */  lbu        $v1, 0x3($s3)
/* 95CBF94 80077A64 01000224 */  addiu      $v0, $zero, 0x1
/* 95CBF98 80077A68 0B006214 */  bne        $v1, $v0, .Llevel_50_80077A98
/* 95CBF9C 80077A6C 80FFA226 */   addiu     $v0, $s5, -0x80
/* 95CBFA0 80077A70 00006286 */  lh         $v0, 0x0($s3)
/* 95CBFA4 80077A74 00000000 */  nop
/* 95CBFA8 80077A78 65004228 */  slti       $v0, $v0, 0x65
/* 95CBFAC 80077A7C 05004010 */  beqz       $v0, .Llevel_50_80077A94
/* 95CBFB0 80077A80 21208002 */   addu      $a0, $s4, $zero
/* 95CBFB4 80077A84 0780053C */  lui        $a1, %hi(D_80070328 + 0xE)
/* 95CBFB8 80077A88 3603A590 */  lbu        $a1, %lo(D_80070328 + 0xE)($a1)
/* 95CBFBC 80077A8C B4DE0108 */  j          .Llevel_50_80077AD0
/* 95CBFC0 80077A90 00000000 */   nop
.Llevel_50_80077A94:
/* 95CBFC4 80077A94 80FFA226 */  addiu      $v0, $s5, -0x80
.Llevel_50_80077A98:
/* 95CBFC8 80077A98 DFDE0108 */  j          .Llevel_50_80077B7C
/* 95CBFCC 80077A9C 460082A2 */   sb        $v0, 0x46($s4)
.L80077AA0_:
/* 95CBFD0 80077AA0 21300000 */  addu       $a2, $zero, $zero
/* 95CBFD4 80077AA4 0780033C */  lui        $v1, %hi(D_8006E020)
/* 95CBFD8 80077AA8 20E0638C */  lw         $v1, %lo(D_8006E020)($v1)
/* 95CBFDC 80077AAC 0C00848E */  lw         $a0, 0xC($s4)
/* 95CBFE0 80077AB0 0780023C */  lui        $v0, %hi(D_8006E024)
/* 95CBFE4 80077AB4 24E0428C */  lw         $v0, %lo(D_8006E024)($v0)
/* 95CBFE8 80077AB8 1000858E */  lw         $a1, 0x10($s4)
/* 95CBFEC 80077ABC 23206400 */  subu       $a0, $v1, $a0
/* 95CBFF0 80077AC0 203A010C */  jal        func_8004E880
/* 95CBFF4 80077AC4 23284500 */   subu      $a1, $v0, $a1
/* 95CBFF8 80077AC8 21208002 */  addu       $a0, $s4, $zero
/* 95CBFFC 80077ACC 21284000 */  addu       $a1, $v0, $zero
.Llevel_50_80077AD0:
/* 95CC000 80077AD0 0C006692 */  lbu        $a2, 0xC($s3)
/* 95CC004 80077AD4 21380000 */  addu       $a3, $zero, $zero
/* 95CC008 80077AD8 1000A0AF */  sw         $zero, 0x10($sp)
/* 95CC00C 80077ADC 17D6000C */  jal        func_8003585C
/* 95CC010 80077AE0 1400A0AF */   sw        $zero, 0x14($sp)
/* 95CC014 80077AE4 DFDE0108 */  j          .Llevel_50_80077B7C
/* 95CC018 80077AE8 00000000 */   nop
.L80077AEC_:
/* 95CC01C 80077AEC 21208002 */  addu       $a0, $s4, $zero
/* 95CC020 80077AF0 0780053C */  lui        $a1, %hi(D_80070328)
/* 95CC024 80077AF4 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 95CC028 80077AF8 46008792 */  lbu        $a3, 0x46($s4)
/* 95CC02C 80077AFC 08000224 */  addiu      $v0, $zero, 0x8
/* 95CC030 80077B00 1000A2AF */  sw         $v0, 0x10($sp)
/* 95CC034 80077B04 A0000224 */  addiu      $v0, $zero, 0xA0
/* 95CC038 80077B08 1400A2AF */  sw         $v0, 0x14($sp)
/* 95CC03C 80077B0C 0C006392 */  lbu        $v1, 0xC($s3)
/* 95CC040 80077B10 80000224 */  addiu      $v0, $zero, 0x80
/* 95CC044 80077B14 1C00A2AF */  sw         $v0, 0x1C($sp)
/* 95CC048 80077B18 FF000224 */  addiu      $v0, $zero, 0xFF
/* 95CC04C 80077B1C 2000A2AF */  sw         $v0, 0x20($sp)
/* 95CC050 80077B20 2400A2AF */  sw         $v0, 0x24($sp)
/* 95CC054 80077B24 0780023C */  lui        $v0, %hi(unk_ovlheader_80074314)
/* 95CC058 80077B28 1443428C */  lw         $v0, %lo(unk_ovlheader_80074314)($v0)
/* 95CC05C 80077B2C 21300000 */  addu       $a2, $zero, $zero
/* 95CC060 80077B30 2800A0AF */  sw         $zero, 0x28($sp)
/* 95CC064 80077B34 2C00A0AF */  sw         $zero, 0x2C($sp)
/* 95CC068 80077B38 3000A0AF */  sw         $zero, 0x30($sp)
/* 95CC06C 80077B3C 09F84000 */  jalr       $v0
/* 95CC070 80077B40 1800A3AF */   sw        $v1, 0x18($sp)
/* 95CC074 80077B44 02004104 */  bgez       $v0, .Llevel_50_80077B50
/* 95CC078 80077B48 00000000 */   nop
/* 95CC07C 80077B4C 000060A6 */  sh         $zero, 0x0($s3)
.Llevel_50_80077B50:
/* 95CC080 80077B50 1400828E */  lw         $v0, 0x14($s4)
/* 95CC084 80077B54 0780033C */  lui        $v1, %hi(D_80070328 + 8)
/* 95CC088 80077B58 3003638C */  lw         $v1, %lo(D_80070328 + 8)($v1)
/* 95CC08C 80077B5C D4FE4224 */  addiu      $v0, $v0, -0x12C
/* 95CC090 80077B60 23186200 */  subu       $v1, $v1, $v0
/* 95CC094 80077B64 83180300 */  sra        $v1, $v1, 2
/* 95CC098 80077B68 4000A3AF */  sw         $v1, 0x40($sp)
/* 95CC09C 80077B6C 1400828E */  lw         $v0, 0x14($s4)
/* 95CC0A0 80077B70 00000000 */  nop
/* 95CC0A4 80077B74 21104300 */  addu       $v0, $v0, $v1
/* 95CC0A8 80077B78 140082AE */  sw         $v0, 0x14($s4)
.Llevel_50_80077B7C:
/* 95CC0AC 80077B7C 1000628E */  lw         $v0, 0x10($s3)
/* 95CC0B0 80077B80 00000000 */  nop
/* 95CC0B4 80077B84 07004010 */  beqz       $v0, .Llevel_50_80077BA4
/* 95CC0B8 80077B88 00000000 */   nop
/* 95CC0BC 80077B8C 46008292 */  lbu        $v0, 0x46($s4)
/* 95CC0C0 80077B90 00000000 */  nop
/* 95CC0C4 80077B94 03005710 */  beq        $v0, $s7, .Llevel_50_80077BA4
/* 95CC0C8 80077B98 21208002 */   addu      $a0, $s4, $zero
/* 95CC0CC 80077B9C 4957010C */  jal        func_80055D24
/* 95CC0D0 80077BA0 04000524 */   addiu     $a1, $zero, 0x4
.Llevel_50_80077BA4:
/* 95CC0D4 80077BA4 0780023C */  lui        $v0, %hi(D_80070328 + 0x280)
/* 95CC0D8 80077BA8 A805428C */  lw         $v0, %lo(D_80070328 + 0x280)($v0)
/* 95CC0DC 80077BAC 00000000 */  nop
/* 95CC0E0 80077BB0 80100200 */  sll        $v0, $v0, 2
/* 95CC0E4 80077BB4 0680013C */  lui        $at, %hi(D_8006585C)
/* 95CC0E8 80077BB8 21082200 */  addu       $at, $at, $v0
/* 95CC0EC 80077BBC 5C58228C */  lw         $v0, %lo(D_8006585C)($at)
/* 95CC0F0 80077BC0 00000000 */  nop
/* 95CC0F4 80077BC4 540082AE */  sw         $v0, 0x54($s4)
/* 95CC0F8 80077BC8 1000638E */  lw         $v1, 0x10($s3)
/* 95CC0FC 80077BCC 00000000 */  nop
/* 95CC100 80077BD0 0E006010 */  beqz       $v1, .Llevel_50_80077C0C
/* 95CC104 80077BD4 00000000 */   nop
/* 95CC108 80077BD8 0780043C */  lui        $a0, %hi(D_80070328 + 0x280)
/* 95CC10C 80077BDC A805848C */  lw         $a0, %lo(D_80070328 + 0x280)($a0)
/* 95CC110 80077BE0 00000000 */  nop
/* 95CC114 80077BE4 04008228 */  slti       $v0, $a0, 0x4
/* 95CC118 80077BE8 03004014 */  bnez       $v0, .Llevel_50_80077BF8
/* 95CC11C 80077BEC 01000224 */   addiu     $v0, $zero, 0x1
/* 95CC120 80077BF0 FFDE0108 */  j          .Llevel_50_80077BFC
/* 95CC124 80077BF4 100064A0 */   sb        $a0, 0x10($v1)
.Llevel_50_80077BF8:
/* 95CC128 80077BF8 100062A0 */  sb         $v0, 0x10($v1)
.Llevel_50_80077BFC:
/* 95CC12C 80077BFC 21208002 */  addu       $a0, $s4, $zero
/* 95CC130 80077C00 1000668E */  lw         $a2, 0x10($s3)
/* 95CC134 80077C04 C557010C */  jal        func_80055F14
/* 95CC138 80077C08 21280000 */   addu      $a1, $zero, $zero
.Llevel_50_80077C0C:
/* 95CC13C 80077C0C 3D008392 */  lbu        $v1, 0x3D($s4)
/* 95CC140 80077C10 01000224 */  addiu      $v0, $zero, 0x1
/* 95CC144 80077C14 08006214 */  bne        $v1, $v0, .Llevel_50_80077C38
/* 95CC148 80077C18 00000000 */   nop
/* 95CC14C 80077C1C 0780023C */  lui        $v0, %hi(D_8006C770)
/* 95CC150 80077C20 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 95CC154 80077C24 00000000 */  nop
/* 95CC158 80077C28 03004010 */  beqz       $v0, .Llevel_50_80077C38
/* 95CC15C 80077C2C 21208002 */   addu      $a0, $s4, $zero
/* 95CC160 80077C30 D0D3000C */  jal        func_80034F40
/* 95CC164 80077C34 21280000 */   addu      $a1, $zero, $zero
.Llevel_50_80077C38:
/* 95CC168 80077C38 D800BF8F */  lw         $ra, 0xD8($sp)
/* 95CC16C 80077C3C D400B78F */  lw         $s7, 0xD4($sp)
/* 95CC170 80077C40 D000B68F */  lw         $s6, 0xD0($sp)
/* 95CC174 80077C44 CC00B58F */  lw         $s5, 0xCC($sp)
/* 95CC178 80077C48 C800B48F */  lw         $s4, 0xC8($sp)
/* 95CC17C 80077C4C C400B38F */  lw         $s3, 0xC4($sp)
/* 95CC180 80077C50 C000B28F */  lw         $s2, 0xC0($sp)
/* 95CC184 80077C54 BC00B18F */  lw         $s1, 0xBC($sp)
/* 95CC188 80077C58 B800B08F */  lw         $s0, 0xB8($sp)
/* 95CC18C 80077C5C E000BD27 */  addiu      $sp, $sp, 0xE0
/* 95CC190 80077C60 0800E003 */  jr         $ra
/* 95CC194 80077C64 00000000 */   nop
.size func_level_50_800766A8, . - func_level_50_800766A8
