.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_46_80074A10
/* 8F46F40 80074A10 F8C20880 */ .word .L8008C2F8_
/* 8F46F44 80074A14 7CC30880 */ .word .L8008C37C_
/* 8F46F48 80074A18 00C40880 */ .word .L8008C400_
/* 8F46F4C 80074A1C 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46F50 80074A20 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46F54 80074A24 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46F58 80074A28 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46F5C 80074A2C 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46F60 80074A30 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46F64 80074A34 C8C40880 */ .word .L8008C4C8_
/* 8F46F68 80074A38 28C50880 */ .word .L8008C528_
/* 8F46F6C 80074A3C 30C60880 */ .word .L8008C630_
/* 8F46F70 80074A40 B8C60880 */ .word .L8008C6B8_
/* 8F46F74 80074A44 30C70880 */ .word .L8008C730_
/* 8F46F78 80074A48 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46F7C 80074A4C 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46F80 80074A50 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46F84 80074A54 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46F88 80074A58 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46F8C 80074A5C 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46F90 80074A60 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46F94 80074A64 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46F98 80074A68 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46F9C 80074A6C 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FA0 80074A70 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FA4 80074A74 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FA8 80074A78 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FAC 80074A7C 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FB0 80074A80 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FB4 80074A84 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FB8 80074A88 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FBC 80074A8C 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FC0 80074A90 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FC4 80074A94 60C80880 */ .word .L8008C860_
/* 8F46FC8 80074A98 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FCC 80074A9C 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FD0 80074AA0 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FD4 80074AA4 00C90880 */ .word .L8008C900_
/* 8F46FD8 80074AA8 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FDC 80074AAC 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FE0 80074AB0 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FE4 80074AB4 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FE8 80074AB8 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FEC 80074ABC 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FF0 80074AC0 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FF4 80074AC4 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F46FF8 80074AC8 E8CA0880 */ .word .L8008CAE8_
/* 8F46FFC 80074ACC 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47000 80074AD0 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47004 80074AD4 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47008 80074AD8 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F4700C 80074ADC 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47010 80074AE0 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47014 80074AE4 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47018 80074AE8 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F4701C 80074AEC 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47020 80074AF0 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47024 80074AF4 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47028 80074AF8 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F4702C 80074AFC 44CB0880 */ .word .L8008CB44_
/* 8F47030 80074B00 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47034 80074B04 E4CB0880 */ .word .L8008CBE4_
/* 8F47038 80074B08 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F4703C 80074B0C 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47040 80074B10 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47044 80074B14 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47048 80074B18 4CCC0880 */ .word .L8008CC4C_
/* 8F4704C 80074B1C 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47050 80074B20 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47054 80074B24 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47058 80074B28 38CD0880 */ .word .L8008CD38_
/* 8F4705C 80074B2C 28CF0880 */ .word .L8008CF28_
/* 8F47060 80074B30 9CD00880 */ .word .L8008D09C_
/* 8F47064 80074B34 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47068 80074B38 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F4706C 80074B3C 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47070 80074B40 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47074 80074B44 0CD40880 */ .word .Llevel_46_8008D40C
/* 8F47078 80074B48 D8D10880 */ .word .L8008D1D8_
/* 8F4707C 80074B4C D8D20880 */ .word .L8008D2D8_
.size jtbl_level_46_80074A10, . - jtbl_level_46_80074A10


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_46_8008C224
/* 8F5E754 8008C224 88FFBD27 */  addiu      $sp, $sp, -0x78
/* 8F5E758 8008C228 5800B2AF */  sw         $s2, 0x58($sp)
/* 8F5E75C 8008C22C 0780123C */  lui        $s2, %hi(D_8006C554)
/* 8F5E760 8008C230 54C5528E */  lw         $s2, %lo(D_8006C554)($s2)
/* 8F5E764 8008C234 6800B6AF */  sw         $s6, 0x68($sp)
/* 8F5E768 8008C238 21B08000 */  addu       $s6, $a0, $zero
/* 8F5E76C 8008C23C 7400BFAF */  sw         $ra, 0x74($sp)
/* 8F5E770 8008C240 7000BEAF */  sw         $fp, 0x70($sp)
/* 8F5E774 8008C244 6C00B7AF */  sw         $s7, 0x6C($sp)
/* 8F5E778 8008C248 6400B5AF */  sw         $s5, 0x64($sp)
/* 8F5E77C 8008C24C 6000B4AF */  sw         $s4, 0x60($sp)
/* 8F5E780 8008C250 5C00B3AF */  sw         $s3, 0x5C($sp)
/* 8F5E784 8008C254 5400B1AF */  sw         $s1, 0x54($sp)
/* 8F5E788 8008C258 5000B0AF */  sw         $s0, 0x50($sp)
/* 8F5E78C 8008C25C 01004492 */  lbu        $a0, 0x1($s2)
/* 8F5E790 8008C260 FF000224 */  addiu      $v0, $zero, 0xFF
/* 8F5E794 8008C264 FF008330 */  andi       $v1, $a0, 0xFF
/* 8F5E798 8008C268 71046210 */  beq        $v1, $v0, .Llevel_46_8008D430
/* 8F5E79C 8008C26C 21104002 */   addu      $v0, $s2, $zero
/* 8F5E7A0 8008C270 40F01600 */  sll        $fp, $s6, 1
/* 8F5E7A4 8008C274 80A01600 */  sll        $s4, $s6, 2
/* 8F5E7A8 8008C278 01005126 */  addiu      $s1, $s2, 0x1
/* 8F5E7AC 8008C27C 18005726 */  addiu      $s7, $s2, 0x18
/* 8F5E7B0 8008C280 04005326 */  addiu      $s3, $s2, 0x4
/* 8F5E7B4 8008C284 FF008330 */  andi       $v1, $a0, 0xFF
.Llevel_46_8008C288:
/* 8F5E7B8 8008C288 FE000224 */  addiu      $v0, $zero, 0xFE
/* 8F5E7BC 8008C28C 5F046210 */  beq        $v1, $v0, .Llevel_46_8008D40C
/* 8F5E7C0 8008C290 04000224 */   addiu     $v0, $zero, 0x4
/* 8F5E7C4 8008C294 0780033C */  lui        $v1, %hi(D_8006E344)
/* 8F5E7C8 8008C298 44E3638C */  lw         $v1, %lo(D_8006E344)($v1)
/* 8F5E7CC 8008C29C 00000000 */  nop
/* 8F5E7D0 8008C2A0 0A006214 */  bne        $v1, $v0, .Llevel_46_8008C2CC
/* 8F5E7D4 8008C2A4 42000224 */   addiu     $v0, $zero, 0x42
/* 8F5E7D8 8008C2A8 00004392 */  lbu        $v1, 0x0($s2)
/* 8F5E7DC 8008C2AC 00000000 */  nop
/* 8F5E7E0 8008C2B0 56046214 */  bne        $v1, $v0, .Llevel_46_8008D40C
/* 8F5E7E4 8008C2B4 00000000 */   nop
/* 8F5E7E8 8008C2B8 0780023C */  lui        $v0, %hi(D_8006C598)
/* 8F5E7EC 8008C2BC 98C5428C */  lw         $v0, %lo(D_8006C598)($v0)
/* 8F5E7F0 8008C2C0 00000000 */  nop
/* 8F5E7F4 8008C2C4 3C044014 */  bnez       $v0, .Llevel_46_8008D3B8
/* 8F5E7F8 8008C2C8 00000000 */   nop
.Llevel_46_8008C2CC:
/* 8F5E7FC 8008C2CC 00004392 */  lbu        $v1, 0x0($s2)
/* 8F5E800 8008C2D0 00000000 */  nop
/* 8F5E804 8008C2D4 5000622C */  sltiu      $v0, $v1, 0x50
/* 8F5E808 8008C2D8 4C044010 */  beqz       $v0, .Llevel_46_8008D40C
/* 8F5E80C 8008C2DC 80100300 */   sll       $v0, $v1, 2
/* 8F5E810 8008C2E0 0780013C */  lui        $at, %hi(jtbl_level_46_80074A10)
/* 8F5E814 8008C2E4 21082200 */  addu       $at, $at, $v0
/* 8F5E818 8008C2E8 104A228C */  lw         $v0, %lo(jtbl_level_46_80074A10)($at)
/* 8F5E81C 8008C2EC 00000000 */  nop
/* 8F5E820 8008C2F0 08004000 */  jr         $v0
/* 8F5E824 8008C2F4 00000000 */   nop
.L8008C2F8_:
/* 8F5E828 8008C2F8 21206002 */  addu       $a0, $s3, $zero
/* 8F5E82C 8008C2FC 21286002 */  addu       $a1, $s3, $zero
/* 8F5E830 8008C300 6A3D010C */  jal        func_8004F5A8
/* 8F5E834 8008C304 2130E002 */   addu      $a2, $s7, $zero
/* 8F5E838 8008C308 1D002286 */  lh         $v0, 0x1D($s1)
/* 8F5E83C 8008C30C 00000000 */  nop
/* 8F5E840 8008C310 05004010 */  beqz       $v0, .Llevel_46_8008C328
/* 8F5E844 8008C314 01000824 */   addiu     $t0, $zero, 0x1
/* 8F5E848 8008C318 1B002296 */  lhu        $v0, 0x1B($s1)
/* 8F5E84C 8008C31C 00000000 */  nop
/* 8F5E850 8008C320 01004224 */  addiu      $v0, $v0, 0x1
/* 8F5E854 8008C324 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_46_8008C328:
/* 8F5E858 8008C328 09002392 */  lbu        $v1, 0x9($s1)
/* 8F5E85C 8008C32C 1D002296 */  lhu        $v0, 0x1D($s1)
/* 8F5E860 8008C330 21187E00 */  addu       $v1, $v1, $fp
/* 8F5E864 8008C334 090023A2 */  sb         $v1, 0x9($s1)
/* 8F5E868 8008C338 0C002392 */  lbu        $v1, 0xC($s1)
/* 8F5E86C 8008C33C 23100201 */  subu       $v0, $t0, $v0
/* 8F5E870 8008C340 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 8F5E874 8008C344 0B002292 */  lbu        $v0, 0xB($s1)
/* 8F5E878 8008C348 23187400 */  subu       $v1, $v1, $s4
/* 8F5E87C 8008C34C 0C0023A2 */  sb         $v1, 0xC($s1)
/* 8F5E880 8008C350 0D002392 */  lbu        $v1, 0xD($s1)
/* 8F5E884 8008C354 23105400 */  subu       $v0, $v0, $s4
/* 8F5E888 8008C358 0B0022A2 */  sb         $v0, 0xB($s1)
/* 8F5E88C 8008C35C 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5E890 8008C360 23187400 */  subu       $v1, $v1, $s4
/* 8F5E894 8008C364 21105600 */  addu       $v0, $v0, $s6
/* 8F5E898 8008C368 010022A2 */  sb         $v0, 0x1($s1)
/* 8F5E89C 8008C36C FF004230 */  andi       $v0, $v0, 0xFF
/* 8F5E8A0 8008C370 2000422C */  sltiu      $v0, $v0, 0x20
/* 8F5E8A4 8008C374 46330208 */  j          .Llevel_46_8008CD18
/* 8F5E8A8 8008C378 0D0023A2 */   sb        $v1, 0xD($s1)
.L8008C37C_:
/* 8F5E8AC 8008C37C 21206002 */  addu       $a0, $s3, $zero
/* 8F5E8B0 8008C380 21286002 */  addu       $a1, $s3, $zero
/* 8F5E8B4 8008C384 6A3D010C */  jal        func_8004F5A8
/* 8F5E8B8 8008C388 2130E002 */   addu      $a2, $s7, $zero
/* 8F5E8BC 8008C38C 1D002286 */  lh         $v0, 0x1D($s1)
/* 8F5E8C0 8008C390 00000000 */  nop
/* 8F5E8C4 8008C394 05004010 */  beqz       $v0, .Llevel_46_8008C3AC
/* 8F5E8C8 8008C398 01000824 */   addiu     $t0, $zero, 0x1
/* 8F5E8CC 8008C39C 1B002296 */  lhu        $v0, 0x1B($s1)
/* 8F5E8D0 8008C3A0 00000000 */  nop
/* 8F5E8D4 8008C3A4 01004224 */  addiu      $v0, $v0, 0x1
/* 8F5E8D8 8008C3A8 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_46_8008C3AC:
/* 8F5E8DC 8008C3AC 09002392 */  lbu        $v1, 0x9($s1)
/* 8F5E8E0 8008C3B0 1D002296 */  lhu        $v0, 0x1D($s1)
/* 8F5E8E4 8008C3B4 21187400 */  addu       $v1, $v1, $s4
/* 8F5E8E8 8008C3B8 090023A2 */  sb         $v1, 0x9($s1)
/* 8F5E8EC 8008C3BC 0C002392 */  lbu        $v1, 0xC($s1)
/* 8F5E8F0 8008C3C0 23100201 */  subu       $v0, $t0, $v0
/* 8F5E8F4 8008C3C4 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 8F5E8F8 8008C3C8 0B002292 */  lbu        $v0, 0xB($s1)
/* 8F5E8FC 8008C3CC 23187400 */  subu       $v1, $v1, $s4
/* 8F5E900 8008C3D0 0C0023A2 */  sb         $v1, 0xC($s1)
/* 8F5E904 8008C3D4 0D002392 */  lbu        $v1, 0xD($s1)
/* 8F5E908 8008C3D8 23105400 */  subu       $v0, $v0, $s4
/* 8F5E90C 8008C3DC 0B0022A2 */  sb         $v0, 0xB($s1)
/* 8F5E910 8008C3E0 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5E914 8008C3E4 23187400 */  subu       $v1, $v1, $s4
/* 8F5E918 8008C3E8 21105600 */  addu       $v0, $v0, $s6
/* 8F5E91C 8008C3EC 010022A2 */  sb         $v0, 0x1($s1)
/* 8F5E920 8008C3F0 FF004230 */  andi       $v0, $v0, 0xFF
/* 8F5E924 8008C3F4 1800422C */  sltiu      $v0, $v0, 0x18
/* 8F5E928 8008C3F8 46330208 */  j          .Llevel_46_8008CD18
/* 8F5E92C 8008C3FC 0D0023A2 */   sb        $v1, 0xD($s1)
.L8008C400_:
/* 8F5E930 8008C400 21206002 */  addu       $a0, $s3, $zero
/* 8F5E934 8008C404 21286002 */  addu       $a1, $s3, $zero
/* 8F5E938 8008C408 6A3D010C */  jal        func_8004F5A8
/* 8F5E93C 8008C40C 2130E002 */   addu      $a2, $s7, $zero
/* 8F5E940 8008C410 1D002286 */  lh         $v0, 0x1D($s1)
/* 8F5E944 8008C414 00000000 */  nop
/* 8F5E948 8008C418 05004010 */  beqz       $v0, .Llevel_46_8008C430
/* 8F5E94C 8008C41C 00000000 */   nop
/* 8F5E950 8008C420 1B002296 */  lhu        $v0, 0x1B($s1)
/* 8F5E954 8008C424 00000000 */  nop
/* 8F5E958 8008C428 01004224 */  addiu      $v0, $v0, 0x1
/* 8F5E95C 8008C42C 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_46_8008C430:
/* 8F5E960 8008C430 1D002296 */  lhu        $v0, 0x1D($s1)
/* 8F5E964 8008C434 01000824 */  addiu      $t0, $zero, 0x1
/* 8F5E968 8008C438 23100201 */  subu       $v0, $t0, $v0
/* 8F5E96C 8008C43C 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 8F5E970 8008C440 09002292 */  lbu        $v0, 0x9($s1)
/* 8F5E974 8008C444 0B002392 */  lbu        $v1, 0xB($s1)
/* 8F5E978 8008C448 21105E00 */  addu       $v0, $v0, $fp
/* 8F5E97C 8008C44C 090022A2 */  sb         $v0, 0x9($s1)
/* 8F5E980 8008C450 2A107400 */  slt        $v0, $v1, $s4
/* 8F5E984 8008C454 03004014 */  bnez       $v0, .Llevel_46_8008C464
/* 8F5E988 8008C458 23107400 */   subu      $v0, $v1, $s4
/* 8F5E98C 8008C45C 1A310208 */  j          .Llevel_46_8008C468
/* 8F5E990 8008C460 0B0022A2 */   sb        $v0, 0xB($s1)
.Llevel_46_8008C464:
/* 8F5E994 8008C464 0B0020A2 */  sb         $zero, 0xB($s1)
.Llevel_46_8008C468:
/* 8F5E998 8008C468 0C002392 */  lbu        $v1, 0xC($s1)
/* 8F5E99C 8008C46C 00000000 */  nop
/* 8F5E9A0 8008C470 2A107400 */  slt        $v0, $v1, $s4
/* 8F5E9A4 8008C474 03004014 */  bnez       $v0, .Llevel_46_8008C484
/* 8F5E9A8 8008C478 23107400 */   subu      $v0, $v1, $s4
/* 8F5E9AC 8008C47C 22310208 */  j          .Llevel_46_8008C488
/* 8F5E9B0 8008C480 0C0022A2 */   sb        $v0, 0xC($s1)
.Llevel_46_8008C484:
/* 8F5E9B4 8008C484 0C0020A2 */  sb         $zero, 0xC($s1)
.Llevel_46_8008C488:
/* 8F5E9B8 8008C488 0D002392 */  lbu        $v1, 0xD($s1)
/* 8F5E9BC 8008C48C 00000000 */  nop
/* 8F5E9C0 8008C490 2A107400 */  slt        $v0, $v1, $s4
/* 8F5E9C4 8008C494 04004014 */  bnez       $v0, .Llevel_46_8008C4A8
/* 8F5E9C8 8008C498 00000000 */   nop
/* 8F5E9CC 8008C49C 23107400 */  subu       $v0, $v1, $s4
/* 8F5E9D0 8008C4A0 2B310208 */  j          .Llevel_46_8008C4AC
/* 8F5E9D4 8008C4A4 0D0022A2 */   sb        $v0, 0xD($s1)
.Llevel_46_8008C4A8:
/* 8F5E9D8 8008C4A8 0D0020A2 */  sb         $zero, 0xD($s1)
.Llevel_46_8008C4AC:
/* 8F5E9DC 8008C4AC 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5E9E0 8008C4B0 00000000 */  nop
/* 8F5E9E4 8008C4B4 21105600 */  addu       $v0, $v0, $s6
/* 8F5E9E8 8008C4B8 010022A2 */  sb         $v0, 0x1($s1)
/* 8F5E9EC 8008C4BC FF004230 */  andi       $v0, $v0, 0xFF
/* 8F5E9F0 8008C4C0 46330208 */  j          .Llevel_46_8008CD18
/* 8F5E9F4 8008C4C4 2000422C */   sltiu     $v0, $v0, 0x20
.L8008C4C8_:
/* 8F5E9F8 8008C4C8 21206002 */  addu       $a0, $s3, $zero
/* 8F5E9FC 8008C4CC 21286002 */  addu       $a1, $s3, $zero
/* 8F5EA00 8008C4D0 6A3D010C */  jal        func_8004F5A8
/* 8F5EA04 8008C4D4 2130E002 */   addu      $a2, $s7, $zero
/* 8F5EA08 8008C4D8 1D002286 */  lh         $v0, 0x1D($s1)
/* 8F5EA0C 8008C4DC 00000000 */  nop
/* 8F5EA10 8008C4E0 05004010 */  beqz       $v0, .Llevel_46_8008C4F8
/* 8F5EA14 8008C4E4 01000824 */   addiu     $t0, $zero, 0x1
/* 8F5EA18 8008C4E8 1B002296 */  lhu        $v0, 0x1B($s1)
/* 8F5EA1C 8008C4EC 00000000 */  nop
/* 8F5EA20 8008C4F0 01004224 */  addiu      $v0, $v0, 0x1
/* 8F5EA24 8008C4F4 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_46_8008C4F8:
/* 8F5EA28 8008C4F8 1D002296 */  lhu        $v0, 0x1D($s1)
/* 8F5EA2C 8008C4FC 09002392 */  lbu        $v1, 0x9($s1)
/* 8F5EA30 8008C500 23100201 */  subu       $v0, $t0, $v0
/* 8F5EA34 8008C504 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 8F5EA38 8008C508 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5EA3C 8008C50C 21187E00 */  addu       $v1, $v1, $fp
/* 8F5EA40 8008C510 090023A2 */  sb         $v1, 0x9($s1)
/* 8F5EA44 8008C514 21105600 */  addu       $v0, $v0, $s6
/* 8F5EA48 8008C518 010022A2 */  sb         $v0, 0x1($s1)
/* 8F5EA4C 8008C51C FF004230 */  andi       $v0, $v0, 0xFF
/* 8F5EA50 8008C520 46330208 */  j          .Llevel_46_8008CD18
/* 8F5EA54 8008C524 2000422C */   sltiu     $v0, $v0, 0x20
.L8008C528_:
/* 8F5EA58 8008C528 0780033C */  lui        $v1, %hi(D_80070328 + 0x48)
/* 8F5EA5C 8008C52C 7003638C */  lw         $v1, %lo(D_80070328 + 0x48)($v1)
/* 8F5EA60 8008C530 1E000224 */  addiu      $v0, $zero, 0x1E
/* 8F5EA64 8008C534 06006214 */  bne        $v1, $v0, .Llevel_46_8008C550
/* 8F5EA68 8008C538 00000000 */   nop
/* 8F5EA6C 8008C53C 0780023C */  lui        $v0, %hi(D_80070328 + 0x280)
/* 8F5EA70 8008C540 A805428C */  lw         $v0, %lo(D_80070328 + 0x280)($v0)
/* 8F5EA74 8008C544 00000000 */  nop
/* 8F5EA78 8008C548 9B034004 */  bltz       $v0, .Llevel_46_8008D3B8
/* 8F5EA7C 8008C54C 00000000 */   nop
.Llevel_46_8008C550:
/* 8F5EA80 8008C550 0780053C */  lui        $a1, %hi(D_80070328 + 0x288)
/* 8F5EA84 8008C554 B005A524 */  addiu      $a1, $a1, %lo(D_80070328 + 0x288)
/* 8F5EA88 8008C558 0000A28C */  lw         $v0, 0x0($a1)
/* 8F5EA8C 8008C55C 00000000 */  nop
/* 8F5EA90 8008C560 95034014 */  bnez       $v0, .Llevel_46_8008D3B8
/* 8F5EA94 8008C564 00000000 */   nop
/* 8F5EA98 8008C568 0780023C */  lui        $v0, %hi(D_80070328 + 0x284)
/* 8F5EA9C 8008C56C AC05428C */  lw         $v0, %lo(D_80070328 + 0x284)($v0)
/* 8F5EAA0 8008C570 00000000 */  nop
/* 8F5EAA4 8008C574 90034010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5EAA8 8008C578 1000A427 */   addiu     $a0, $sp, 0x10
/* 8F5EAAC 8008C57C 5E3C010C */  jal        func_8004F178
/* 8F5EAB0 8008C580 78FDA524 */   addiu     $a1, $a1, -0x288
/* 8F5EAB4 8008C584 17002486 */  lh         $a0, 0x17($s1)
/* 8F5EAB8 8008C588 8B3A010C */  jal        func_8004EA2C
/* 8F5EABC 8008C58C 00000000 */   nop
/* 8F5EAC0 8008C590 1000A38F */  lw         $v1, 0x10($sp)
/* 8F5EAC4 8008C594 03110200 */  sra        $v0, $v0, 4
/* 8F5EAC8 8008C598 21186200 */  addu       $v1, $v1, $v0
/* 8F5EACC 8008C59C 1000A3AF */  sw         $v1, 0x10($sp)
/* 8F5EAD0 8008C5A0 17002486 */  lh         $a0, 0x17($s1)
/* 8F5EAD4 8008C5A4 793A010C */  jal        func_8004E9E4
/* 8F5EAD8 8008C5A8 00000000 */   nop
/* 8F5EADC 8008C5AC 21206002 */  addu       $a0, $s3, $zero
/* 8F5EAE0 8008C5B0 1000A527 */  addiu      $a1, $sp, 0x10
/* 8F5EAE4 8008C5B4 03110200 */  sra        $v0, $v0, 4
/* 8F5EAE8 8008C5B8 1400A38F */  lw         $v1, 0x14($sp)
/* 8F5EAEC 8008C5BC 1800A68F */  lw         $a2, 0x18($sp)
/* 8F5EAF0 8008C5C0 21186200 */  addu       $v1, $v1, $v0
/* 8F5EAF4 8008C5C4 0001C624 */  addiu      $a2, $a2, 0x100
/* 8F5EAF8 8008C5C8 1400A3AF */  sw         $v1, 0x14($sp)
/* 8F5EAFC 8008C5CC 413D010C */  jal        func_8004F504
/* 8F5EB00 8008C5D0 1800A6AF */   sw        $a2, 0x18($sp)
/* 8F5EB04 8008C5D4 17002496 */  lhu        $a0, 0x17($s1)
/* 8F5EB08 8008C5D8 00000000 */  nop
/* 8F5EB0C 8008C5DC 40008424 */  addiu      $a0, $a0, 0x40
/* 8F5EB10 8008C5E0 170024A6 */  sh         $a0, 0x17($s1)
/* 8F5EB14 8008C5E4 00240400 */  sll        $a0, $a0, 16
/* 8F5EB18 8008C5E8 0780023C */  lui        $v0, %hi(D_8006E040)
/* 8F5EB1C 8008C5EC 40E04284 */  lh         $v0, %lo(D_8006E040)($v0)
/* 8F5EB20 8008C5F0 03240400 */  sra        $a0, $a0, 16
/* 8F5EB24 8008C5F4 23208200 */  subu       $a0, $a0, $v0
/* 8F5EB28 8008C5F8 8B3A010C */  jal        func_8004EA2C
/* 8F5EB2C 8008C5FC FF0F8430 */   andi      $a0, $a0, 0xFFF
/* 8F5EB30 8008C600 6060033C */  lui        $v1, (0x60606061 >> 16)
/* 8F5EB34 8008C604 61606334 */  ori        $v1, $v1, (0x60606061 & 0xFFFF)
/* 8F5EB38 8008C608 02004104 */  bgez       $v0, .Llevel_46_8008C614
/* 8F5EB3C 8008C60C 00000000 */   nop
/* 8F5EB40 8008C610 23100200 */  negu       $v0, $v0
.Llevel_46_8008C614:
/* 8F5EB44 8008C614 18004300 */  mult       $v0, $v1
/* 8F5EB48 8008C618 C3170200 */  sra        $v0, $v0, 31
/* 8F5EB4C 8008C61C 10400000 */  mfhi       $t0
/* 8F5EB50 8008C620 83190800 */  sra        $v1, $t0, 6
/* 8F5EB54 8008C624 23186200 */  subu       $v1, $v1, $v0
/* 8F5EB58 8008C628 03350208 */  j          .Llevel_46_8008D40C
/* 8F5EB5C 8008C62C 090023A2 */   sb        $v1, 0x9($s1)
.L8008C630_:
/* 8F5EB60 8008C630 1D002286 */  lh         $v0, 0x1D($s1)
/* 8F5EB64 8008C634 00000000 */  nop
/* 8F5EB68 8008C638 05004010 */  beqz       $v0, .Llevel_46_8008C650
/* 8F5EB6C 8008C63C 21206002 */   addu      $a0, $s3, $zero
/* 8F5EB70 8008C640 15002296 */  lhu        $v0, 0x15($s1)
/* 8F5EB74 8008C644 00000000 */  nop
/* 8F5EB78 8008C648 01004224 */  addiu      $v0, $v0, 0x1
/* 8F5EB7C 8008C64C 150022A6 */  sh         $v0, 0x15($s1)
.Llevel_46_8008C650:
/* 8F5EB80 8008C650 21286002 */  addu       $a1, $s3, $zero
/* 8F5EB84 8008C654 12004626 */  addiu      $a2, $s2, 0x12
/* 8F5EB88 8008C658 1D002296 */  lhu        $v0, 0x1D($s1)
/* 8F5EB8C 8008C65C 01000824 */  addiu      $t0, $zero, 0x1
/* 8F5EB90 8008C660 23100201 */  subu       $v0, $t0, $v0
/* 8F5EB94 8008C664 6A3D010C */  jal        func_8004F5A8
/* 8F5EB98 8008C668 1D0022A6 */   sh        $v0, 0x1D($s1)
/* 8F5EB9C 8008C66C 09002292 */  lbu        $v0, 0x9($s1)
/* 8F5EBA0 8008C670 0B002392 */  lbu        $v1, 0xB($s1)
/* 8F5EBA4 8008C674 21105E00 */  addu       $v0, $v0, $fp
/* 8F5EBA8 8008C678 090022A2 */  sb         $v0, 0x9($s1)
/* 8F5EBAC 8008C67C 0A002292 */  lbu        $v0, 0xA($s1)
/* 8F5EBB0 8008C680 FCFF6324 */  addiu      $v1, $v1, -0x4
/* 8F5EBB4 8008C684 0B0023A2 */  sb         $v1, 0xB($s1)
/* 8F5EBB8 8008C688 0D002392 */  lbu        $v1, 0xD($s1)
/* 8F5EBBC 8008C68C 21105400 */  addu       $v0, $v0, $s4
/* 8F5EBC0 8008C690 0A0022A2 */  sb         $v0, 0xA($s1)
/* 8F5EBC4 8008C694 0C002292 */  lbu        $v0, 0xC($s1)
/* 8F5EBC8 8008C698 FCFF6324 */  addiu      $v1, $v1, -0x4
/* 8F5EBCC 8008C69C 0D0023A2 */  sb         $v1, 0xD($s1)
/* 8F5EBD0 8008C6A0 FF006330 */  andi       $v1, $v1, 0xFF
/* 8F5EBD4 8008C6A4 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 8F5EBD8 8008C6A8 43036010 */  beqz       $v1, .Llevel_46_8008D3B8
/* 8F5EBDC 8008C6AC 0C0022A2 */   sb        $v0, 0xC($s1)
/* 8F5EBE0 8008C6B0 48330208 */  j          .Llevel_46_8008CD20
/* 8F5EBE4 8008C6B4 00000000 */   nop
.L8008C6B8_:
/* 8F5EBE8 8008C6B8 21206002 */  addu       $a0, $s3, $zero
/* 8F5EBEC 8008C6BC 21286002 */  addu       $a1, $s3, $zero
/* 8F5EBF0 8008C6C0 0A002292 */  lbu        $v0, 0xA($s1)
/* 8F5EBF4 8008C6C4 2130E002 */  addu       $a2, $s7, $zero
/* 8F5EBF8 8008C6C8 08004224 */  addiu      $v0, $v0, 0x8
/* 8F5EBFC 8008C6CC 6A3D010C */  jal        func_8004F5A8
/* 8F5EC00 8008C6D0 0A0022A2 */   sb        $v0, 0xA($s1)
/* 8F5EC04 8008C6D4 0B002292 */  lbu        $v0, 0xB($s1)
/* 8F5EC08 8008C6D8 00000000 */  nop
/* 8F5EC0C 8008C6DC 02004010 */  beqz       $v0, .Llevel_46_8008C6E8
/* 8F5EC10 8008C6E0 F8FF4224 */   addiu     $v0, $v0, -0x8
/* 8F5EC14 8008C6E4 0B0022A2 */  sb         $v0, 0xB($s1)
.Llevel_46_8008C6E8:
/* 8F5EC18 8008C6E8 0C002292 */  lbu        $v0, 0xC($s1)
/* 8F5EC1C 8008C6EC 00000000 */  nop
/* 8F5EC20 8008C6F0 02004010 */  beqz       $v0, .Llevel_46_8008C6FC
/* 8F5EC24 8008C6F4 F8FF4224 */   addiu     $v0, $v0, -0x8
/* 8F5EC28 8008C6F8 0C0022A2 */  sb         $v0, 0xC($s1)
.Llevel_46_8008C6FC:
/* 8F5EC2C 8008C6FC 0D002292 */  lbu        $v0, 0xD($s1)
/* 8F5EC30 8008C700 00000000 */  nop
/* 8F5EC34 8008C704 02004010 */  beqz       $v0, .Llevel_46_8008C710
/* 8F5EC38 8008C708 F8FF4224 */   addiu     $v0, $v0, -0x8
/* 8F5EC3C 8008C70C 0D0022A2 */  sb         $v0, 0xD($s1)
.Llevel_46_8008C710:
/* 8F5EC40 8008C710 FF00033C */  lui        $v1, (0xFFFFFF >> 16)
/* 8F5EC44 8008C714 0B00228E */  lw         $v0, 0xB($s1)
/* 8F5EC48 8008C718 FFFF6334 */  ori        $v1, $v1, (0xFFFFFF & 0xFFFF)
/* 8F5EC4C 8008C71C 24104300 */  and        $v0, $v0, $v1
/* 8F5EC50 8008C720 25034010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5EC54 8008C724 00000000 */   nop
/* 8F5EC58 8008C728 48330208 */  j          .Llevel_46_8008CD20
/* 8F5EC5C 8008C72C 00000000 */   nop
.L8008C730_:
/* 8F5EC60 8008C730 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5EC64 8008C734 00000000 */  nop
/* 8F5EC68 8008C738 1C00422C */  sltiu      $v0, $v0, 0x1C
/* 8F5EC6C 8008C73C 1E034010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5EC70 8008C740 00000000 */   nop
/* 8F5EC74 8008C744 02002292 */  lbu        $v0, 0x2($s1)
/* 8F5EC78 8008C748 00000000 */  nop
/* 8F5EC7C 8008C74C 1A034010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5EC80 8008C750 21206002 */   addu      $a0, $s3, $zero
/* 8F5EC84 8008C754 21286002 */  addu       $a1, $s3, $zero
/* 8F5EC88 8008C758 6A3D010C */  jal        func_8004F5A8
/* 8F5EC8C 8008C75C 2130E002 */   addu      $a2, $s7, $zero
/* 8F5EC90 8008C760 1D002286 */  lh         $v0, 0x1D($s1)
/* 8F5EC94 8008C764 00000000 */  nop
/* 8F5EC98 8008C768 05004010 */  beqz       $v0, .Llevel_46_8008C780
/* 8F5EC9C 8008C76C 00000000 */   nop
/* 8F5ECA0 8008C770 1B002296 */  lhu        $v0, 0x1B($s1)
/* 8F5ECA4 8008C774 00000000 */  nop
/* 8F5ECA8 8008C778 01004224 */  addiu      $v0, $v0, 0x1
/* 8F5ECAC 8008C77C 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_46_8008C780:
/* 8F5ECB0 8008C780 1D002296 */  lhu        $v0, 0x1D($s1)
/* 8F5ECB4 8008C784 01000824 */  addiu      $t0, $zero, 0x1
/* 8F5ECB8 8008C788 23100201 */  subu       $v0, $t0, $v0
/* 8F5ECBC 8008C78C 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 8F5ECC0 8008C790 09002292 */  lbu        $v0, 0x9($s1)
/* 8F5ECC4 8008C794 01002392 */  lbu        $v1, 0x1($s1)
/* 8F5ECC8 8008C798 21105E00 */  addu       $v0, $v0, $fp
/* 8F5ECCC 8008C79C 090022A2 */  sb         $v0, 0x9($s1)
/* 8F5ECD0 8008C7A0 0D00622C */  sltiu      $v0, $v1, 0xD
/* 8F5ECD4 8008C7A4 14004014 */  bnez       $v0, .Llevel_46_8008C7F8
/* 8F5ECD8 8008C7A8 0500622C */   sltiu     $v0, $v1, 0x5
/* 8F5ECDC 8008C7AC F4FF6224 */  addiu      $v0, $v1, -0xC
/* 8F5ECE0 8008C7B0 C0100200 */  sll        $v0, $v0, 3
/* 8F5ECE4 8008C7B4 80000324 */  addiu      $v1, $zero, 0x80
/* 8F5ECE8 8008C7B8 23106200 */  subu       $v0, $v1, $v0
/* 8F5ECEC 8008C7BC 02004104 */  bgez       $v0, .Llevel_46_8008C7C8
/* 8F5ECF0 8008C7C0 00000000 */   nop
/* 8F5ECF4 8008C7C4 21100000 */  addu       $v0, $zero, $zero
.Llevel_46_8008C7C8:
/* 8F5ECF8 8008C7C8 01002392 */  lbu        $v1, 0x1($s1)
/* 8F5ECFC 8008C7CC 0B0022A2 */  sb         $v0, 0xB($s1)
/* 8F5ED00 8008C7D0 40000224 */  addiu      $v0, $zero, 0x40
/* 8F5ED04 8008C7D4 F4FF6324 */  addiu      $v1, $v1, -0xC
/* 8F5ED08 8008C7D8 80180300 */  sll        $v1, $v1, 2
/* 8F5ED0C 8008C7DC 23104300 */  subu       $v0, $v0, $v1
/* 8F5ED10 8008C7E0 02004104 */  bgez       $v0, .Llevel_46_8008C7EC
/* 8F5ED14 8008C7E4 00000000 */   nop
/* 8F5ED18 8008C7E8 21100000 */  addu       $v0, $zero, $zero
.Llevel_46_8008C7EC:
/* 8F5ED1C 8008C7EC 0C0022A2 */  sb         $v0, 0xC($s1)
/* 8F5ED20 8008C7F0 13320208 */  j          .Llevel_46_8008C84C
/* 8F5ED24 8008C7F4 0D0020A2 */   sb        $zero, 0xD($s1)
.Llevel_46_8008C7F8:
/* 8F5ED28 8008C7F8 0A004014 */  bnez       $v0, .Llevel_46_8008C824
/* 8F5ED2C 8008C7FC 80000224 */   addiu     $v0, $zero, 0x80
/* 8F5ED30 8008C800 01002392 */  lbu        $v1, 0x1($s1)
/* 8F5ED34 8008C804 0B0022A2 */  sb         $v0, 0xB($s1)
/* 8F5ED38 8008C808 80FF0224 */  addiu      $v0, $zero, -0x80
/* 8F5ED3C 8008C80C 0D0020A2 */  sb         $zero, 0xD($s1)
/* 8F5ED40 8008C810 FCFF6324 */  addiu      $v1, $v1, -0x4
/* 8F5ED44 8008C814 C0180300 */  sll        $v1, $v1, 3
/* 8F5ED48 8008C818 23104300 */  subu       $v0, $v0, $v1
/* 8F5ED4C 8008C81C 13320208 */  j          .Llevel_46_8008C84C
/* 8F5ED50 8008C820 0C0022A2 */   sb        $v0, 0xC($s1)
.Llevel_46_8008C824:
/* 8F5ED54 8008C824 01002392 */  lbu        $v1, 0x1($s1)
/* 8F5ED58 8008C828 0B0022A2 */  sb         $v0, 0xB($s1)
/* 8F5ED5C 8008C82C 0C0022A2 */  sb         $v0, 0xC($s1)
/* 8F5ED60 8008C830 80000224 */  addiu      $v0, $zero, 0x80
/* 8F5ED64 8008C834 40190300 */  sll        $v1, $v1, 5
/* 8F5ED68 8008C838 23104300 */  subu       $v0, $v0, $v1
/* 8F5ED6C 8008C83C 02004104 */  bgez       $v0, .Llevel_46_8008C848
/* 8F5ED70 8008C840 00000000 */   nop
/* 8F5ED74 8008C844 21100000 */  addu       $v0, $zero, $zero
.Llevel_46_8008C848:
/* 8F5ED78 8008C848 0D0022A2 */  sb         $v0, 0xD($s1)
.Llevel_46_8008C84C:
/* 8F5ED7C 8008C84C 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5ED80 8008C850 00000000 */  nop
/* 8F5ED84 8008C854 21105600 */  addu       $v0, $v0, $s6
/* 8F5ED88 8008C858 03350208 */  j          .Llevel_46_8008D40C
/* 8F5ED8C 8008C85C 010022A2 */   sb        $v0, 0x1($s1)
.L8008C860_:
/* 8F5ED90 8008C860 21206002 */  addu       $a0, $s3, $zero
/* 8F5ED94 8008C864 21286002 */  addu       $a1, $s3, $zero
/* 8F5ED98 8008C868 6A3D010C */  jal        func_8004F5A8
/* 8F5ED9C 8008C86C 2130E002 */   addu      $a2, $s7, $zero
/* 8F5EDA0 8008C870 1D002286 */  lh         $v0, 0x1D($s1)
/* 8F5EDA4 8008C874 00000000 */  nop
/* 8F5EDA8 8008C878 05004010 */  beqz       $v0, .Llevel_46_8008C890
/* 8F5EDAC 8008C87C 01000824 */   addiu     $t0, $zero, 0x1
/* 8F5EDB0 8008C880 1B002296 */  lhu        $v0, 0x1B($s1)
/* 8F5EDB4 8008C884 00000000 */  nop
/* 8F5EDB8 8008C888 01004224 */  addiu      $v0, $v0, 0x1
/* 8F5EDBC 8008C88C 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_46_8008C890:
/* 8F5EDC0 8008C890 0B002292 */  lbu        $v0, 0xB($s1)
/* 8F5EDC4 8008C894 09002392 */  lbu        $v1, 0x9($s1)
/* 8F5EDC8 8008C898 23205E00 */  subu       $a0, $v0, $fp
/* 8F5EDCC 8008C89C 1D002296 */  lhu        $v0, 0x1D($s1)
/* 8F5EDD0 8008C8A0 21187E00 */  addu       $v1, $v1, $fp
/* 8F5EDD4 8008C8A4 090023A2 */  sb         $v1, 0x9($s1)
/* 8F5EDD8 8008C8A8 23100201 */  subu       $v0, $t0, $v0
/* 8F5EDDC 8008C8AC 02008104 */  bgez       $a0, .Llevel_46_8008C8B8
/* 8F5EDE0 8008C8B0 1D0022A6 */   sh        $v0, 0x1D($s1)
/* 8F5EDE4 8008C8B4 21200000 */  addu       $a0, $zero, $zero
.Llevel_46_8008C8B8:
/* 8F5EDE8 8008C8B8 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5EDEC 8008C8BC 0B0024A2 */  sb         $a0, 0xB($s1)
/* 8F5EDF0 8008C8C0 0C0024A2 */  sb         $a0, 0xC($s1)
/* 8F5EDF4 8008C8C4 0D0024A2 */  sb         $a0, 0xD($s1)
/* 8F5EDF8 8008C8C8 21105600 */  addu       $v0, $v0, $s6
/* 8F5EDFC 8008C8CC 010022A2 */  sb         $v0, 0x1($s1)
/* 8F5EE00 8008C8D0 FF004230 */  andi       $v0, $v0, 0xFF
/* 8F5EE04 8008C8D4 2000422C */  sltiu      $v0, $v0, 0x20
/* 8F5EE08 8008C8D8 B7024010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5EE0C 8008C8DC 00000000 */   nop
/* 8F5EE10 8008C8E0 02002292 */  lbu        $v0, 0x2($s1)
/* 8F5EE14 8008C8E4 00000000 */  nop
/* 8F5EE18 8008C8E8 B3024010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5EE1C 8008C8EC 00000000 */   nop
/* 8F5EE20 8008C8F0 B1028010 */  beqz       $a0, .Llevel_46_8008D3B8
/* 8F5EE24 8008C8F4 00000000 */   nop
/* 8F5EE28 8008C8F8 04350208 */  j          .Llevel_46_8008D410
/* 8F5EE2C 8008C8FC 20003126 */   addiu     $s1, $s1, 0x20
.L8008C900_:
/* 8F5EE30 8008C900 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5EE34 8008C904 00000000 */  nop
/* 8F5EE38 8008C908 21185600 */  addu       $v1, $v0, $s6
/* 8F5EE3C 8008C90C FF005530 */  andi       $s5, $v0, 0xFF
/* 8F5EE40 8008C910 010023A2 */  sb         $v1, 0x1($s1)
/* 8F5EE44 8008C914 FF006330 */  andi       $v1, $v1, 0xFF
/* 8F5EE48 8008C918 3100622C */  sltiu      $v0, $v1, 0x31
/* 8F5EE4C 8008C91C A6024010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5EE50 8008C920 1000622C */   sltiu     $v0, $v1, 0x10
/* 8F5EE54 8008C924 34004010 */  beqz       $v0, .Llevel_46_8008C9F8
/* 8F5EE58 8008C928 21280000 */   addu      $a1, $zero, $zero
/* 8F5EE5C 8008C92C 17002286 */  lh         $v0, 0x17($s1)
/* 8F5EE60 8008C930 00000000 */  nop
/* 8F5EE64 8008C934 18004300 */  mult       $v0, $v1
/* 8F5EE68 8008C938 12400000 */  mflo       $t0
/* 8F5EE6C 8008C93C 43100800 */  sra        $v0, $t0, 1
/* 8F5EE70 8008C940 2000A2A7 */  sh         $v0, 0x20($sp)
/* 8F5EE74 8008C944 19002386 */  lh         $v1, 0x19($s1)
/* 8F5EE78 8008C948 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5EE7C 8008C94C 00000000 */  nop
/* 8F5EE80 8008C950 18006200 */  mult       $v1, $v0
/* 8F5EE84 8008C954 12400000 */  mflo       $t0
/* 8F5EE88 8008C958 43100800 */  sra        $v0, $t0, 1
/* 8F5EE8C 8008C95C 2200A2A7 */  sh         $v0, 0x22($sp)
/* 8F5EE90 8008C960 1B002386 */  lh         $v1, 0x1B($s1)
/* 8F5EE94 8008C964 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5EE98 8008C968 00000000 */  nop
/* 8F5EE9C 8008C96C 18006200 */  mult       $v1, $v0
/* 8F5EEA0 8008C970 2800B027 */  addiu      $s0, $sp, 0x28
/* 8F5EEA4 8008C974 12400000 */  mflo       $t0
/* 8F5EEA8 8008C978 43100800 */  sra        $v0, $t0, 1
/* 8F5EEAC 8008C97C 2400A2A7 */  sh         $v0, 0x24($sp)
/* 8F5EEB0 8008C980 1D002286 */  lh         $v0, 0x1D($s1)
/* 8F5EEB4 8008C984 21300002 */  addu       $a2, $s0, $zero
/* 8F5EEB8 8008C988 40200200 */  sll        $a0, $v0, 1
/* 8F5EEBC 8008C98C 21208200 */  addu       $a0, $a0, $v0
/* 8F5EEC0 8008C990 80200400 */  sll        $a0, $a0, 2
/* 8F5EEC4 8008C994 23208200 */  subu       $a0, $a0, $v0
/* 8F5EEC8 8008C998 0780023C */  lui        $v0, %hi(D_8006C550)
/* 8F5EECC 8008C99C 50C5428C */  lw         $v0, %lo(D_8006C550)($v0)
/* 8F5EED0 8008C9A0 C0200400 */  sll        $a0, $a0, 3
/* 8F5EED4 8008C9A4 C557010C */  jal        func_80055F14
/* 8F5EED8 8008C9A8 21204400 */   addu      $a0, $v0, $a0
/* 8F5EEDC 8008C9AC 21200002 */  addu       $a0, $s0, $zero
/* 8F5EEE0 8008C9B0 443C010C */  jal        func_8004F110
/* 8F5EEE4 8008C9B4 02000524 */   addiu     $a1, $zero, 0x2
/* 8F5EEE8 8008C9B8 2800A38F */  lw         $v1, 0x28($sp)
/* 8F5EEEC 8008C9BC 2000A297 */  lhu        $v0, 0x20($sp)
/* 8F5EEF0 8008C9C0 00000000 */  nop
/* 8F5EEF4 8008C9C4 21104300 */  addu       $v0, $v0, $v1
/* 8F5EEF8 8008C9C8 030022A6 */  sh         $v0, 0x3($s1)
/* 8F5EEFC 8008C9CC 2C00A38F */  lw         $v1, 0x2C($sp)
/* 8F5EF00 8008C9D0 2200A297 */  lhu        $v0, 0x22($sp)
/* 8F5EF04 8008C9D4 00000000 */  nop
/* 8F5EF08 8008C9D8 21104300 */  addu       $v0, $v0, $v1
/* 8F5EF0C 8008C9DC 050022A6 */  sh         $v0, 0x5($s1)
/* 8F5EF10 8008C9E0 3000A38F */  lw         $v1, 0x30($sp)
/* 8F5EF14 8008C9E4 2400A297 */  lhu        $v0, 0x24($sp)
/* 8F5EF18 8008C9E8 00000000 */  nop
/* 8F5EF1C 8008C9EC 21104300 */  addu       $v0, $v0, $v1
/* 8F5EF20 8008C9F0 82320208 */  j          .Llevel_46_8008CA08
/* 8F5EF24 8008C9F4 070022A6 */   sh        $v0, 0x7($s1)
.Llevel_46_8008C9F8:
/* 8F5EF28 8008C9F8 21206002 */  addu       $a0, $s3, $zero
/* 8F5EF2C 8008C9FC 21286002 */  addu       $a1, $s3, $zero
/* 8F5EF30 8008CA00 6A3D010C */  jal        func_8004F5A8
/* 8F5EF34 8008CA04 2130E002 */   addu      $a2, $s7, $zero
.Llevel_46_8008CA08:
/* 8F5EF38 8008CA08 09002292 */  lbu        $v0, 0x9($s1)
/* 8F5EF3C 8008CA0C 00000000 */  nop
/* 8F5EF40 8008CA10 21105600 */  addu       $v0, $v0, $s6
/* 8F5EF44 8008CA14 090022A2 */  sb         $v0, 0x9($s1)
/* 8F5EF48 8008CA18 FF004230 */  andi       $v0, $v0, 0xFF
/* 8F5EF4C 8008CA1C 8100422C */  sltiu      $v0, $v0, 0x81
/* 8F5EF50 8008CA20 02004014 */  bnez       $v0, .Llevel_46_8008CA2C
/* 8F5EF54 8008CA24 80000224 */   addiu     $v0, $zero, 0x80
/* 8F5EF58 8008CA28 090022A2 */  sb         $v0, 0x9($s1)
.Llevel_46_8008CA2C:
/* 8F5EF5C 8008CA2C 01002392 */  lbu        $v1, 0x1($s1)
/* 8F5EF60 8008CA30 00000000 */  nop
/* 8F5EF64 8008CA34 1100622C */  sltiu      $v0, $v1, 0x11
/* 8F5EF68 8008CA38 20004014 */  bnez       $v0, .Llevel_46_8008CABC
/* 8F5EF6C 8008CA3C 00010224 */   addiu     $v0, $zero, 0x100
/* 8F5EF70 8008CA40 1100A22A */  slti       $v0, $s5, 0x11
/* 8F5EF74 8008CA44 08004010 */  beqz       $v0, .Llevel_46_8008CA68
/* 8F5EF78 8008CA48 01000424 */   addiu     $a0, $zero, 0x1
/* 8F5EF7C 8008CA4C 38000524 */  addiu      $a1, $zero, 0x38
/* 8F5EF80 8008CA50 21304002 */  addu       $a2, $s2, $zero
/* 8F5EF84 8008CA54 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 8F5EF88 8008CA58 E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 8F5EF8C 8008CA5C 00000000 */  nop
/* 8F5EF90 8008CA60 09F84000 */  jalr       $v0
/* 8F5EF94 8008CA64 21380000 */   addu      $a3, $zero, $zero
.Llevel_46_8008CA68:
/* 8F5EF98 8008CA68 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5EF9C 8008CA6C 00000000 */  nop
/* 8F5EFA0 8008CA70 F0FF4224 */  addiu      $v0, $v0, -0x10
/* 8F5EFA4 8008CA74 C0180200 */  sll        $v1, $v0, 3
/* 8F5EFA8 8008CA78 00010224 */  addiu      $v0, $zero, 0x100
/* 8F5EFAC 8008CA7C 23184300 */  subu       $v1, $v0, $v1
/* 8F5EFB0 8008CA80 00016228 */  slti       $v0, $v1, 0x100
/* 8F5EFB4 8008CA84 02004014 */  bnez       $v0, .Llevel_46_8008CA90
/* 8F5EFB8 8008CA88 00000000 */   nop
/* 8F5EFBC 8008CA8C FF000324 */  addiu      $v1, $zero, 0xFF
.Llevel_46_8008CA90:
/* 8F5EFC0 8008CA90 02006104 */  bgez       $v1, .Llevel_46_8008CA9C
/* 8F5EFC4 8008CA94 00000000 */   nop
/* 8F5EFC8 8008CA98 21180000 */  addu       $v1, $zero, $zero
.Llevel_46_8008CA9C:
/* 8F5EFCC 8008CA9C 0C002292 */  lbu        $v0, 0xC($s1)
/* 8F5EFD0 8008CAA0 0B0023A2 */  sb         $v1, 0xB($s1)
/* 8F5EFD4 8008CAA4 43180300 */  sra        $v1, $v1, 1
/* 8F5EFD8 8008CAA8 2A106200 */  slt        $v0, $v1, $v0
/* 8F5EFDC 8008CAAC 57024010 */  beqz       $v0, .Llevel_46_8008D40C
/* 8F5EFE0 8008CAB0 00000000 */   nop
.Llevel_46_8008CAB4:
/* 8F5EFE4 8008CAB4 03350208 */  j          .Llevel_46_8008D40C
/* 8F5EFE8 8008CAB8 0C0023A2 */   sb        $v1, 0xC($s1)
.Llevel_46_8008CABC:
/* 8F5EFEC 8008CABC 00190300 */  sll        $v1, $v1, 4
/* 8F5EFF0 8008CAC0 23184300 */  subu       $v1, $v0, $v1
/* 8F5EFF4 8008CAC4 00016228 */  slti       $v0, $v1, 0x100
/* 8F5EFF8 8008CAC8 03004014 */  bnez       $v0, .Llevel_46_8008CAD8
/* 8F5EFFC 8008CACC 20006228 */   slti      $v0, $v1, 0x20
/* 8F5F000 8008CAD0 FF000324 */  addiu      $v1, $zero, 0xFF
/* 8F5F004 8008CAD4 20006228 */  slti       $v0, $v1, 0x20
.Llevel_46_8008CAD8:
/* 8F5F008 8008CAD8 F6FF4010 */  beqz       $v0, .Llevel_46_8008CAB4
/* 8F5F00C 8008CADC 00000000 */   nop
/* 8F5F010 8008CAE0 AD320208 */  j          .Llevel_46_8008CAB4
/* 8F5F014 8008CAE4 20000324 */   addiu     $v1, $zero, 0x20
.L8008CAE8_:
/* 8F5F018 8008CAE8 01002392 */  lbu        $v1, 0x1($s1)
/* 8F5F01C 8008CAEC 00000000 */  nop
/* 8F5F020 8008CAF0 01006224 */  addiu      $v0, $v1, 0x1
/* 8F5F024 8008CAF4 1000632C */  sltiu      $v1, $v1, 0x10
/* 8F5F028 8008CAF8 2F026010 */  beqz       $v1, .Llevel_46_8008D3B8
/* 8F5F02C 8008CAFC 010022A2 */   sb        $v0, 0x1($s1)
/* 8F5F030 8008CB00 02002292 */  lbu        $v0, 0x2($s1)
/* 8F5F034 8008CB04 00000000 */  nop
/* 8F5F038 8008CB08 2B024010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5F03C 8008CB0C 00000000 */   nop
/* 8F5F040 8008CB10 09002292 */  lbu        $v0, 0x9($s1)
/* 8F5F044 8008CB14 0B002392 */  lbu        $v1, 0xB($s1)
/* 8F5F048 8008CB18 03004224 */  addiu      $v0, $v0, 0x3
/* 8F5F04C 8008CB1C 090022A2 */  sb         $v0, 0x9($s1)
/* 8F5F050 8008CB20 0C002292 */  lbu        $v0, 0xC($s1)
/* 8F5F054 8008CB24 F8FF6324 */  addiu      $v1, $v1, -0x8
/* 8F5F058 8008CB28 0B0023A2 */  sb         $v1, 0xB($s1)
/* 8F5F05C 8008CB2C 0D002392 */  lbu        $v1, 0xD($s1)
/* 8F5F060 8008CB30 F8FF4224 */  addiu      $v0, $v0, -0x8
/* 8F5F064 8008CB34 F8FF6324 */  addiu      $v1, $v1, -0x8
/* 8F5F068 8008CB38 0C0022A2 */  sb         $v0, 0xC($s1)
/* 8F5F06C 8008CB3C 03350208 */  j          .Llevel_46_8008D40C
/* 8F5F070 8008CB40 0D0023A2 */   sb        $v1, 0xD($s1)
.L8008CB44_:
/* 8F5F074 8008CB44 21206002 */  addu       $a0, $s3, $zero
/* 8F5F078 8008CB48 21286002 */  addu       $a1, $s3, $zero
/* 8F5F07C 8008CB4C 0A002292 */  lbu        $v0, 0xA($s1)
/* 8F5F080 8008CB50 2130E002 */  addu       $a2, $s7, $zero
/* 8F5F084 8008CB54 08004224 */  addiu      $v0, $v0, 0x8
/* 8F5F088 8008CB58 6A3D010C */  jal        func_8004F5A8
/* 8F5F08C 8008CB5C 0A0022A2 */   sb        $v0, 0xA($s1)
/* 8F5F090 8008CB60 0780023C */  lui        $v0, %hi(D_8006C640)
/* 8F5F094 8008CB64 40C6428C */  lw         $v0, %lo(D_8006C640)($v0)
/* 8F5F098 8008CB68 00000000 */  nop
/* 8F5F09C 8008CB6C 01004230 */  andi       $v0, $v0, 0x1
/* 8F5F0A0 8008CB70 05004010 */  beqz       $v0, .Llevel_46_8008CB88
/* 8F5F0A4 8008CB74 00000000 */   nop
/* 8F5F0A8 8008CB78 19002296 */  lhu        $v0, 0x19($s1)
/* 8F5F0AC 8008CB7C 00000000 */  nop
/* 8F5F0B0 8008CB80 01004224 */  addiu      $v0, $v0, 0x1
/* 8F5F0B4 8008CB84 190022A6 */  sh         $v0, 0x19($s1)
.Llevel_46_8008CB88:
/* 8F5F0B8 8008CB88 0B002292 */  lbu        $v0, 0xB($s1)
/* 8F5F0BC 8008CB8C 00000000 */  nop
/* 8F5F0C0 8008CB90 02004010 */  beqz       $v0, .Llevel_46_8008CB9C
/* 8F5F0C4 8008CB94 FCFF4224 */   addiu     $v0, $v0, -0x4
/* 8F5F0C8 8008CB98 0B0022A2 */  sb         $v0, 0xB($s1)
.Llevel_46_8008CB9C:
/* 8F5F0CC 8008CB9C 0C002292 */  lbu        $v0, 0xC($s1)
/* 8F5F0D0 8008CBA0 00000000 */  nop
/* 8F5F0D4 8008CBA4 02004010 */  beqz       $v0, .Llevel_46_8008CBB0
/* 8F5F0D8 8008CBA8 FCFF4224 */   addiu     $v0, $v0, -0x4
/* 8F5F0DC 8008CBAC 0C0022A2 */  sb         $v0, 0xC($s1)
.Llevel_46_8008CBB0:
/* 8F5F0E0 8008CBB0 0D002292 */  lbu        $v0, 0xD($s1)
/* 8F5F0E4 8008CBB4 00000000 */  nop
/* 8F5F0E8 8008CBB8 02004010 */  beqz       $v0, .Llevel_46_8008CBC4
/* 8F5F0EC 8008CBBC FCFF4224 */   addiu     $v0, $v0, -0x4
/* 8F5F0F0 8008CBC0 0D0022A2 */  sb         $v0, 0xD($s1)
.Llevel_46_8008CBC4:
/* 8F5F0F4 8008CBC4 FF00033C */  lui        $v1, (0xFFFFFF >> 16)
/* 8F5F0F8 8008CBC8 0B00228E */  lw         $v0, 0xB($s1)
/* 8F5F0FC 8008CBCC FFFF6334 */  ori        $v1, $v1, (0xFFFFFF & 0xFFFF)
/* 8F5F100 8008CBD0 24104300 */  and        $v0, $v0, $v1
/* 8F5F104 8008CBD4 F8014010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5F108 8008CBD8 00000000 */   nop
/* 8F5F10C 8008CBDC 48330208 */  j          .Llevel_46_8008CD20
/* 8F5F110 8008CBE0 00000000 */   nop
.L8008CBE4_:
/* 8F5F114 8008CBE4 1D002286 */  lh         $v0, 0x1D($s1)
/* 8F5F118 8008CBE8 00000000 */  nop
/* 8F5F11C 8008CBEC 05004010 */  beqz       $v0, .Llevel_46_8008CC04
/* 8F5F120 8008CBF0 01000824 */   addiu     $t0, $zero, 0x1
/* 8F5F124 8008CBF4 1B002296 */  lhu        $v0, 0x1B($s1)
/* 8F5F128 8008CBF8 00000000 */  nop
/* 8F5F12C 8008CBFC 01004224 */  addiu      $v0, $v0, 0x1
/* 8F5F130 8008CC00 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_46_8008CC04:
/* 8F5F134 8008CC04 1D002296 */  lhu        $v0, 0x1D($s1)
/* 8F5F138 8008CC08 0C002392 */  lbu        $v1, 0xC($s1)
/* 8F5F13C 8008CC0C 23100201 */  subu       $v0, $t0, $v0
/* 8F5F140 8008CC10 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 8F5F144 8008CC14 0B002292 */  lbu        $v0, 0xB($s1)
/* 8F5F148 8008CC18 23187400 */  subu       $v1, $v1, $s4
/* 8F5F14C 8008CC1C 0C0023A2 */  sb         $v1, 0xC($s1)
/* 8F5F150 8008CC20 0D002392 */  lbu        $v1, 0xD($s1)
/* 8F5F154 8008CC24 23105400 */  subu       $v0, $v0, $s4
/* 8F5F158 8008CC28 0B0022A2 */  sb         $v0, 0xB($s1)
/* 8F5F15C 8008CC2C 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5F160 8008CC30 23187400 */  subu       $v1, $v1, $s4
/* 8F5F164 8008CC34 0D0023A2 */  sb         $v1, 0xD($s1)
/* 8F5F168 8008CC38 21105600 */  addu       $v0, $v0, $s6
/* 8F5F16C 8008CC3C 010022A2 */  sb         $v0, 0x1($s1)
/* 8F5F170 8008CC40 FF004230 */  andi       $v0, $v0, 0xFF
/* 8F5F174 8008CC44 46330208 */  j          .Llevel_46_8008CD18
/* 8F5F178 8008CC48 2000422C */   sltiu     $v0, $v0, 0x20
.L8008CC4C_:
/* 8F5F17C 8008CC4C 2F00C01A */  blez       $s6, .Llevel_46_8008CD0C
/* 8F5F180 8008CC50 21800000 */   addu      $s0, $zero, $zero
.Llevel_46_8008CC54:
/* 8F5F184 8008CC54 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5F188 8008CC58 00000000 */  nop
/* 8F5F18C 8008CC5C 01004230 */  andi       $v0, $v0, 0x1
/* 8F5F190 8008CC60 23004010 */  beqz       $v0, .Llevel_46_8008CCF0
/* 8F5F194 8008CC64 00000000 */   nop
/* 8F5F198 8008CC68 03002296 */  lhu        $v0, 0x3($s1)
/* 8F5F19C 8008CC6C 0F002496 */  lhu        $a0, 0xF($s1)
/* 8F5F1A0 8008CC70 05002396 */  lhu        $v1, 0x5($s1)
/* 8F5F1A4 8008CC74 11002596 */  lhu        $a1, 0x11($s1)
/* 8F5F1A8 8008CC78 21104400 */  addu       $v0, $v0, $a0
/* 8F5F1AC 8008CC7C 030022A6 */  sh         $v0, 0x3($s1)
/* 8F5F1B0 8008CC80 07002296 */  lhu        $v0, 0x7($s1)
/* 8F5F1B4 8008CC84 13002496 */  lhu        $a0, 0x13($s1)
/* 8F5F1B8 8008CC88 21186500 */  addu       $v1, $v1, $a1
/* 8F5F1BC 8008CC8C 050023A6 */  sh         $v1, 0x5($s1)
/* 8F5F1C0 8008CC90 01002392 */  lbu        $v1, 0x1($s1)
/* 8F5F1C4 8008CC94 21104400 */  addu       $v0, $v0, $a0
/* 8F5F1C8 8008CC98 02006330 */  andi       $v1, $v1, 0x2
/* 8F5F1CC 8008CC9C 14006010 */  beqz       $v1, .Llevel_46_8008CCF0
/* 8F5F1D0 8008CCA0 070022A6 */   sh        $v0, 0x7($s1)
/* 8F5F1D4 8008CCA4 9171010C */  jal        func_8005C644
/* 8F5F1D8 8008CCA8 00000000 */   nop
/* 8F5F1DC 8008CCAC 0F002396 */  lhu        $v1, 0xF($s1)
/* 8F5F1E0 8008CCB0 02004230 */  andi       $v0, $v0, 0x2
/* 8F5F1E4 8008CCB4 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 8F5F1E8 8008CCB8 21186200 */  addu       $v1, $v1, $v0
/* 8F5F1EC 8008CCBC 9171010C */  jal        func_8005C644
/* 8F5F1F0 8008CCC0 0F0023A6 */   sh        $v1, 0xF($s1)
/* 8F5F1F4 8008CCC4 11002396 */  lhu        $v1, 0x11($s1)
/* 8F5F1F8 8008CCC8 02004230 */  andi       $v0, $v0, 0x2
/* 8F5F1FC 8008CCCC FFFF6324 */  addiu      $v1, $v1, -0x1
/* 8F5F200 8008CCD0 21186200 */  addu       $v1, $v1, $v0
/* 8F5F204 8008CCD4 9171010C */  jal        func_8005C644
/* 8F5F208 8008CCD8 110023A6 */   sh        $v1, 0x11($s1)
/* 8F5F20C 8008CCDC 13002396 */  lhu        $v1, 0x13($s1)
/* 8F5F210 8008CCE0 02004230 */  andi       $v0, $v0, 0x2
/* 8F5F214 8008CCE4 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 8F5F218 8008CCE8 21186200 */  addu       $v1, $v1, $v0
/* 8F5F21C 8008CCEC 130023A6 */  sh         $v1, 0x13($s1)
.Llevel_46_8008CCF0:
/* 8F5F220 8008CCF0 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5F224 8008CCF4 01001026 */  addiu      $s0, $s0, 0x1
/* 8F5F228 8008CCF8 01004224 */  addiu      $v0, $v0, 0x1
/* 8F5F22C 8008CCFC 010022A2 */  sb         $v0, 0x1($s1)
/* 8F5F230 8008CD00 2A101602 */  slt        $v0, $s0, $s6
/* 8F5F234 8008CD04 D3FF4014 */  bnez       $v0, .Llevel_46_8008CC54
/* 8F5F238 8008CD08 00000000 */   nop
.Llevel_46_8008CD0C:
/* 8F5F23C 8008CD0C 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5F240 8008CD10 00000000 */  nop
/* 8F5F244 8008CD14 1800422C */  sltiu      $v0, $v0, 0x18
.Llevel_46_8008CD18:
/* 8F5F248 8008CD18 A7014010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5F24C 8008CD1C 00000000 */   nop
.Llevel_46_8008CD20:
/* 8F5F250 8008CD20 02002292 */  lbu        $v0, 0x2($s1)
/* 8F5F254 8008CD24 00000000 */  nop
/* 8F5F258 8008CD28 A3014010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5F25C 8008CD2C 00000000 */   nop
/* 8F5F260 8008CD30 04350208 */  j          .Llevel_46_8008D410
/* 8F5F264 8008CD34 20003126 */   addiu     $s1, $s1, 0x20
.L8008CD38_:
/* 8F5F268 8008CD38 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5F26C 8008CD3C 00000000 */  nop
/* 8F5F270 8008CD40 01004224 */  addiu      $v0, $v0, 0x1
/* 8F5F274 8008CD44 010022A2 */  sb         $v0, 0x1($s1)
/* 8F5F278 8008CD48 FF004230 */  andi       $v0, $v0, 0xFF
/* 8F5F27C 8008CD4C 2000422C */  sltiu      $v0, $v0, 0x20
/* 8F5F280 8008CD50 99014010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5F284 8008CD54 00000000 */   nop
/* 8F5F288 8008CD58 02002292 */  lbu        $v0, 0x2($s1)
/* 8F5F28C 8008CD5C 00000000 */  nop
/* 8F5F290 8008CD60 95014010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5F294 8008CD64 00000000 */   nop
/* 8F5F298 8008CD68 09002486 */  lh         $a0, 0x9($s1)
/* 8F5F29C 8008CD6C 03002286 */  lh         $v0, 0x3($s1)
/* 8F5F2A0 8008CD70 00000000 */  nop
/* 8F5F2A4 8008CD74 23208200 */  subu       $a0, $a0, $v0
/* 8F5F2A8 8008CD78 43200400 */  sra        $a0, $a0, 1
/* 8F5F2AC 8008CD7C 2000A4A7 */  sh         $a0, 0x20($sp)
/* 8F5F2B0 8008CD80 0B002286 */  lh         $v0, 0xB($s1)
/* 8F5F2B4 8008CD84 05002386 */  lh         $v1, 0x5($s1)
/* 8F5F2B8 8008CD88 00000000 */  nop
/* 8F5F2BC 8008CD8C 23104300 */  subu       $v0, $v0, $v1
/* 8F5F2C0 8008CD90 43100200 */  sra        $v0, $v0, 1
/* 8F5F2C4 8008CD94 2200A2A7 */  sh         $v0, 0x22($sp)
/* 8F5F2C8 8008CD98 0D002286 */  lh         $v0, 0xD($s1)
/* 8F5F2CC 8008CD9C 07002386 */  lh         $v1, 0x7($s1)
/* 8F5F2D0 8008CDA0 00000000 */  nop
/* 8F5F2D4 8008CDA4 23104300 */  subu       $v0, $v0, $v1
/* 8F5F2D8 8008CDA8 43100200 */  sra        $v0, $v0, 1
/* 8F5F2DC 8008CDAC 2400A2A7 */  sh         $v0, 0x24($sp)
/* 8F5F2E0 8008CDB0 03002296 */  lhu        $v0, 0x3($s1)
/* 8F5F2E4 8008CDB4 00000000 */  nop
/* 8F5F2E8 8008CDB8 21104400 */  addu       $v0, $v0, $a0
/* 8F5F2EC 8008CDBC 030022A6 */  sh         $v0, 0x3($s1)
/* 8F5F2F0 8008CDC0 05002296 */  lhu        $v0, 0x5($s1)
/* 8F5F2F4 8008CDC4 2200A397 */  lhu        $v1, 0x22($sp)
/* 8F5F2F8 8008CDC8 00000000 */  nop
/* 8F5F2FC 8008CDCC 21104300 */  addu       $v0, $v0, $v1
/* 8F5F300 8008CDD0 050022A6 */  sh         $v0, 0x5($s1)
/* 8F5F304 8008CDD4 07002296 */  lhu        $v0, 0x7($s1)
/* 8F5F308 8008CDD8 2400A397 */  lhu        $v1, 0x24($sp)
/* 8F5F30C 8008CDDC 00000000 */  nop
/* 8F5F310 8008CDE0 21104300 */  addu       $v0, $v0, $v1
/* 8F5F314 8008CDE4 9171010C */  jal        func_8005C644
/* 8F5F318 8008CDE8 070022A6 */   sh        $v0, 0x7($s1)
/* 8F5F31C 8008CDEC 2000A397 */  lhu        $v1, 0x20($sp)
/* 8F5F320 8008CDF0 02004230 */  andi       $v0, $v0, 0x2
/* 8F5F324 8008CDF4 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 8F5F328 8008CDF8 21186200 */  addu       $v1, $v1, $v0
/* 8F5F32C 8008CDFC 9171010C */  jal        func_8005C644
/* 8F5F330 8008CE00 2000A3A7 */   sh        $v1, 0x20($sp)
/* 8F5F334 8008CE04 2200A397 */  lhu        $v1, 0x22($sp)
/* 8F5F338 8008CE08 02004230 */  andi       $v0, $v0, 0x2
/* 8F5F33C 8008CE0C FFFF6324 */  addiu      $v1, $v1, -0x1
/* 8F5F340 8008CE10 21186200 */  addu       $v1, $v1, $v0
/* 8F5F344 8008CE14 2200A3A7 */  sh         $v1, 0x22($sp)
/* 8F5F348 8008CE18 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5F34C 8008CE1C 00000000 */  nop
/* 8F5F350 8008CE20 01004230 */  andi       $v0, $v0, 0x1
/* 8F5F354 8008CE24 05004010 */  beqz       $v0, .Llevel_46_8008CE3C
/* 8F5F358 8008CE28 00000000 */   nop
/* 8F5F35C 8008CE2C 2400A297 */  lhu        $v0, 0x24($sp)
/* 8F5F360 8008CE30 00000000 */  nop
/* 8F5F364 8008CE34 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 8F5F368 8008CE38 2400A2A7 */  sh         $v0, 0x24($sp)
.Llevel_46_8008CE3C:
/* 8F5F36C 8008CE3C 09002296 */  lhu        $v0, 0x9($s1)
/* 8F5F370 8008CE40 2000A397 */  lhu        $v1, 0x20($sp)
/* 8F5F374 8008CE44 00000000 */  nop
/* 8F5F378 8008CE48 21104300 */  addu       $v0, $v0, $v1
/* 8F5F37C 8008CE4C 090022A6 */  sh         $v0, 0x9($s1)
/* 8F5F380 8008CE50 0B002296 */  lhu        $v0, 0xB($s1)
/* 8F5F384 8008CE54 2200A397 */  lhu        $v1, 0x22($sp)
/* 8F5F388 8008CE58 00000000 */  nop
/* 8F5F38C 8008CE5C 21104300 */  addu       $v0, $v0, $v1
/* 8F5F390 8008CE60 0D002396 */  lhu        $v1, 0xD($s1)
/* 8F5F394 8008CE64 0B0022A6 */  sh         $v0, 0xB($s1)
/* 8F5F398 8008CE68 0F002292 */  lbu        $v0, 0xF($s1)
/* 8F5F39C 8008CE6C 2400A497 */  lhu        $a0, 0x24($sp)
/* 8F5F3A0 8008CE70 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 8F5F3A4 8008CE74 21186400 */  addu       $v1, $v1, $a0
/* 8F5F3A8 8008CE78 0F0022A2 */  sb         $v0, 0xF($s1)
/* 8F5F3AC 8008CE7C FF004230 */  andi       $v0, $v0, 0xFF
/* 8F5F3B0 8008CE80 8000422C */  sltiu      $v0, $v0, 0x80
/* 8F5F3B4 8008CE84 03004010 */  beqz       $v0, .Llevel_46_8008CE94
/* 8F5F3B8 8008CE88 0D0023A6 */   sh        $v1, 0xD($s1)
/* 8F5F3BC 8008CE8C 80000224 */  addiu      $v0, $zero, 0x80
/* 8F5F3C0 8008CE90 0F0022A2 */  sb         $v0, 0xF($s1)
.Llevel_46_8008CE94:
/* 8F5F3C4 8008CE94 10002292 */  lbu        $v0, 0x10($s1)
/* 8F5F3C8 8008CE98 00000000 */  nop
/* 8F5F3CC 8008CE9C FCFF4224 */  addiu      $v0, $v0, -0x4
/* 8F5F3D0 8008CEA0 100022A2 */  sb         $v0, 0x10($s1)
/* 8F5F3D4 8008CEA4 FF004230 */  andi       $v0, $v0, 0xFF
/* 8F5F3D8 8008CEA8 6000422C */  sltiu      $v0, $v0, 0x60
/* 8F5F3DC 8008CEAC 02004010 */  beqz       $v0, .Llevel_46_8008CEB8
/* 8F5F3E0 8008CEB0 60000224 */   addiu     $v0, $zero, 0x60
/* 8F5F3E4 8008CEB4 100022A2 */  sb         $v0, 0x10($s1)
.Llevel_46_8008CEB8:
/* 8F5F3E8 8008CEB8 13002292 */  lbu        $v0, 0x13($s1)
/* 8F5F3EC 8008CEBC 110020A2 */  sb         $zero, 0x11($s1)
/* 8F5F3F0 8008CEC0 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 8F5F3F4 8008CEC4 130022A2 */  sb         $v0, 0x13($s1)
/* 8F5F3F8 8008CEC8 FF004230 */  andi       $v0, $v0, 0xFF
/* 8F5F3FC 8008CECC C000422C */  sltiu      $v0, $v0, 0xC0
/* 8F5F400 8008CED0 02004010 */  beqz       $v0, .Llevel_46_8008CEDC
/* 8F5F404 8008CED4 C0000224 */   addiu     $v0, $zero, 0xC0
/* 8F5F408 8008CED8 130022A2 */  sb         $v0, 0x13($s1)
.Llevel_46_8008CEDC:
/* 8F5F40C 8008CEDC 14002292 */  lbu        $v0, 0x14($s1)
/* 8F5F410 8008CEE0 00000000 */  nop
/* 8F5F414 8008CEE4 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 8F5F418 8008CEE8 140022A2 */  sb         $v0, 0x14($s1)
/* 8F5F41C 8008CEEC FF004230 */  andi       $v0, $v0, 0xFF
/* 8F5F420 8008CEF0 8000422C */  sltiu      $v0, $v0, 0x80
/* 8F5F424 8008CEF4 02004010 */  beqz       $v0, .Llevel_46_8008CF00
/* 8F5F428 8008CEF8 80000224 */   addiu     $v0, $zero, 0x80
/* 8F5F42C 8008CEFC 140022A2 */  sb         $v0, 0x14($s1)
.Llevel_46_8008CF00:
/* 8F5F430 8008CF00 15002292 */  lbu        $v0, 0x15($s1)
/* 8F5F434 8008CF04 00000000 */  nop
/* 8F5F438 8008CF08 FAFF4224 */  addiu      $v0, $v0, -0x6
/* 8F5F43C 8008CF0C 150022A2 */  sb         $v0, 0x15($s1)
/* 8F5F440 8008CF10 FF004230 */  andi       $v0, $v0, 0xFF
/* 8F5F444 8008CF14 2000422C */  sltiu      $v0, $v0, 0x20
/* 8F5F448 8008CF18 3C014010 */  beqz       $v0, .Llevel_46_8008D40C
/* 8F5F44C 8008CF1C 20000224 */   addiu     $v0, $zero, 0x20
/* 8F5F450 8008CF20 03350208 */  j          .Llevel_46_8008D40C
/* 8F5F454 8008CF24 150022A2 */   sb        $v0, 0x15($s1)
.L8008CF28_:
/* 8F5F458 8008CF28 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5F45C 8008CF2C 00000000 */  nop
/* 8F5F460 8008CF30 01004224 */  addiu      $v0, $v0, 0x1
/* 8F5F464 8008CF34 010022A2 */  sb         $v0, 0x1($s1)
/* 8F5F468 8008CF38 FF004230 */  andi       $v0, $v0, 0xFF
/* 8F5F46C 8008CF3C 2000422C */  sltiu      $v0, $v0, 0x20
/* 8F5F470 8008CF40 1D014010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5F474 8008CF44 00000000 */   nop
/* 8F5F478 8008CF48 02002292 */  lbu        $v0, 0x2($s1)
/* 8F5F47C 8008CF4C 00000000 */  nop
/* 8F5F480 8008CF50 19014010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5F484 8008CF54 00000000 */   nop
/* 8F5F488 8008CF58 09002286 */  lh         $v0, 0x9($s1)
/* 8F5F48C 8008CF5C 03002386 */  lh         $v1, 0x3($s1)
/* 8F5F490 8008CF60 00000000 */  nop
/* 8F5F494 8008CF64 23104300 */  subu       $v0, $v0, $v1
/* 8F5F498 8008CF68 3800A2AF */  sw         $v0, 0x38($sp)
/* 8F5F49C 8008CF6C 0B002286 */  lh         $v0, 0xB($s1)
/* 8F5F4A0 8008CF70 05002386 */  lh         $v1, 0x5($s1)
/* 8F5F4A4 8008CF74 00000000 */  nop
/* 8F5F4A8 8008CF78 23104300 */  subu       $v0, $v0, $v1
/* 8F5F4AC 8008CF7C 3C00A2AF */  sw         $v0, 0x3C($sp)
/* 8F5F4B0 8008CF80 0D002286 */  lh         $v0, 0xD($s1)
/* 8F5F4B4 8008CF84 07002386 */  lh         $v1, 0x7($s1)
/* 8F5F4B8 8008CF88 00000000 */  nop
/* 8F5F4BC 8008CF8C 23104300 */  subu       $v0, $v0, $v1
/* 8F5F4C0 8008CF90 9171010C */  jal        func_8005C644
/* 8F5F4C4 8008CF94 4000A2AF */   sw        $v0, 0x40($sp)
/* 8F5F4C8 8008CF98 3800A38F */  lw         $v1, 0x38($sp)
/* 8F5F4CC 8008CF9C 02004230 */  andi       $v0, $v0, 0x2
/* 8F5F4D0 8008CFA0 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 8F5F4D4 8008CFA4 21186200 */  addu       $v1, $v1, $v0
/* 8F5F4D8 8008CFA8 9171010C */  jal        func_8005C644
/* 8F5F4DC 8008CFAC 3800A3AF */   sw        $v1, 0x38($sp)
/* 8F5F4E0 8008CFB0 3C00A38F */  lw         $v1, 0x3C($sp)
/* 8F5F4E4 8008CFB4 02004230 */  andi       $v0, $v0, 0x2
/* 8F5F4E8 8008CFB8 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 8F5F4EC 8008CFBC 21186200 */  addu       $v1, $v1, $v0
/* 8F5F4F0 8008CFC0 9171010C */  jal        func_8005C644
/* 8F5F4F4 8008CFC4 3C00A3AF */   sw        $v1, 0x3C($sp)
/* 8F5F4F8 8008CFC8 4000A38F */  lw         $v1, 0x40($sp)
/* 8F5F4FC 8008CFCC 02004230 */  andi       $v0, $v0, 0x2
/* 8F5F500 8008CFD0 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 8F5F504 8008CFD4 21186200 */  addu       $v1, $v1, $v0
/* 8F5F508 8008CFD8 4000A3AF */  sw         $v1, 0x40($sp)
/* 8F5F50C 8008CFDC 3800A38F */  lw         $v1, 0x38($sp)
/* 8F5F510 8008CFE0 09002296 */  lhu        $v0, 0x9($s1)
/* 8F5F514 8008CFE4 00000000 */  nop
/* 8F5F518 8008CFE8 21104300 */  addu       $v0, $v0, $v1
/* 8F5F51C 8008CFEC 090022A6 */  sh         $v0, 0x9($s1)
/* 8F5F520 8008CFF0 3C00A38F */  lw         $v1, 0x3C($sp)
/* 8F5F524 8008CFF4 0B002296 */  lhu        $v0, 0xB($s1)
/* 8F5F528 8008CFF8 00000000 */  nop
/* 8F5F52C 8008CFFC 21104300 */  addu       $v0, $v0, $v1
/* 8F5F530 8008D000 0B0022A6 */  sh         $v0, 0xB($s1)
/* 8F5F534 8008D004 4000A38F */  lw         $v1, 0x40($sp)
/* 8F5F538 8008D008 0D002296 */  lhu        $v0, 0xD($s1)
/* 8F5F53C 8008D00C 00000000 */  nop
/* 8F5F540 8008D010 21104300 */  addu       $v0, $v0, $v1
/* 8F5F544 8008D014 0D0022A6 */  sh         $v0, 0xD($s1)
/* 8F5F548 8008D018 3800A38F */  lw         $v1, 0x38($sp)
/* 8F5F54C 8008D01C 09002296 */  lhu        $v0, 0x9($s1)
/* 8F5F550 8008D020 00000000 */  nop
/* 8F5F554 8008D024 23104300 */  subu       $v0, $v0, $v1
/* 8F5F558 8008D028 030022A6 */  sh         $v0, 0x3($s1)
/* 8F5F55C 8008D02C 3C00A38F */  lw         $v1, 0x3C($sp)
/* 8F5F560 8008D030 0B002296 */  lhu        $v0, 0xB($s1)
/* 8F5F564 8008D034 00000000 */  nop
/* 8F5F568 8008D038 23104300 */  subu       $v0, $v0, $v1
/* 8F5F56C 8008D03C 050022A6 */  sh         $v0, 0x5($s1)
/* 8F5F570 8008D040 13002292 */  lbu        $v0, 0x13($s1)
/* 8F5F574 8008D044 4000A48F */  lw         $a0, 0x40($sp)
/* 8F5F578 8008D048 15002392 */  lbu        $v1, 0x15($s1)
/* 8F5F57C 8008D04C FEFF4224 */  addiu      $v0, $v0, -0x2
/* 8F5F580 8008D050 130022A2 */  sb         $v0, 0x13($s1)
/* 8F5F584 8008D054 14002292 */  lbu        $v0, 0x14($s1)
/* 8F5F588 8008D058 FCFF6324 */  addiu      $v1, $v1, -0x4
/* 8F5F58C 8008D05C 150023A2 */  sb         $v1, 0x15($s1)
/* 8F5F590 8008D060 10002392 */  lbu        $v1, 0x10($s1)
/* 8F5F594 8008D064 FEFF4224 */  addiu      $v0, $v0, -0x2
/* 8F5F598 8008D068 140022A2 */  sb         $v0, 0x14($s1)
/* 8F5F59C 8008D06C 0F002292 */  lbu        $v0, 0xF($s1)
/* 8F5F5A0 8008D070 FDFF6324 */  addiu      $v1, $v1, -0x3
/* 8F5F5A4 8008D074 100023A2 */  sb         $v1, 0x10($s1)
/* 8F5F5A8 8008D078 0D002396 */  lhu        $v1, 0xD($s1)
/* 8F5F5AC 8008D07C FDFF4224 */  addiu      $v0, $v0, -0x3
/* 8F5F5B0 8008D080 0F0022A2 */  sb         $v0, 0xF($s1)
/* 8F5F5B4 8008D084 11002292 */  lbu        $v0, 0x11($s1)
/* 8F5F5B8 8008D088 23186400 */  subu       $v1, $v1, $a0
/* 8F5F5BC 8008D08C 070023A6 */  sh         $v1, 0x7($s1)
/* 8F5F5C0 8008D090 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 8F5F5C4 8008D094 03350208 */  j          .Llevel_46_8008D40C
/* 8F5F5C8 8008D098 110022A2 */   sb        $v0, 0x11($s1)
.L8008D09C_:
/* 8F5F5CC 8008D09C 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5F5D0 8008D0A0 00000000 */  nop
/* 8F5F5D4 8008D0A4 01004224 */  addiu      $v0, $v0, 0x1
/* 8F5F5D8 8008D0A8 010022A2 */  sb         $v0, 0x1($s1)
/* 8F5F5DC 8008D0AC FF004230 */  andi       $v0, $v0, 0xFF
/* 8F5F5E0 8008D0B0 3800422C */  sltiu      $v0, $v0, 0x38
/* 8F5F5E4 8008D0B4 C0004010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5F5E8 8008D0B8 00000000 */   nop
/* 8F5F5EC 8008D0BC 02002292 */  lbu        $v0, 0x2($s1)
/* 8F5F5F0 8008D0C0 00000000 */  nop
/* 8F5F5F4 8008D0C4 BC004010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5F5F8 8008D0C8 00000000 */   nop
/* 8F5F5FC 8008D0CC 03002286 */  lh         $v0, 0x3($s1)
/* 8F5F600 8008D0D0 09002386 */  lh         $v1, 0x9($s1)
/* 8F5F604 8008D0D4 00000000 */  nop
/* 8F5F608 8008D0D8 23104300 */  subu       $v0, $v0, $v1
/* 8F5F60C 8008D0DC 43100200 */  sra        $v0, $v0, 1
/* 8F5F610 8008D0E0 3800A2AF */  sw         $v0, 0x38($sp)
/* 8F5F614 8008D0E4 05002286 */  lh         $v0, 0x5($s1)
/* 8F5F618 8008D0E8 0B002386 */  lh         $v1, 0xB($s1)
/* 8F5F61C 8008D0EC 00000000 */  nop
/* 8F5F620 8008D0F0 23104300 */  subu       $v0, $v0, $v1
/* 8F5F624 8008D0F4 43100200 */  sra        $v0, $v0, 1
/* 8F5F628 8008D0F8 3C00A2AF */  sw         $v0, 0x3C($sp)
/* 8F5F62C 8008D0FC 07002286 */  lh         $v0, 0x7($s1)
/* 8F5F630 8008D100 0D002386 */  lh         $v1, 0xD($s1)
/* 8F5F634 8008D104 00000000 */  nop
/* 8F5F638 8008D108 23104300 */  subu       $v0, $v0, $v1
/* 8F5F63C 8008D10C 43100200 */  sra        $v0, $v0, 1
/* 8F5F640 8008D110 9171010C */  jal        func_8005C644
/* 8F5F644 8008D114 4000A2AF */   sw        $v0, 0x40($sp)
/* 8F5F648 8008D118 3800A38F */  lw         $v1, 0x38($sp)
/* 8F5F64C 8008D11C 04004230 */  andi       $v0, $v0, 0x4
/* 8F5F650 8008D120 FEFF6324 */  addiu      $v1, $v1, -0x2
/* 8F5F654 8008D124 21186200 */  addu       $v1, $v1, $v0
/* 8F5F658 8008D128 9171010C */  jal        func_8005C644
/* 8F5F65C 8008D12C 3800A3AF */   sw        $v1, 0x38($sp)
/* 8F5F660 8008D130 3C00A38F */  lw         $v1, 0x3C($sp)
/* 8F5F664 8008D134 04004230 */  andi       $v0, $v0, 0x4
/* 8F5F668 8008D138 FEFF6324 */  addiu      $v1, $v1, -0x2
/* 8F5F66C 8008D13C 21186200 */  addu       $v1, $v1, $v0
/* 8F5F670 8008D140 9171010C */  jal        func_8005C644
/* 8F5F674 8008D144 3C00A3AF */   sw        $v1, 0x3C($sp)
/* 8F5F678 8008D148 4000A38F */  lw         $v1, 0x40($sp)
/* 8F5F67C 8008D14C 02004230 */  andi       $v0, $v0, 0x2
/* 8F5F680 8008D150 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 8F5F684 8008D154 21186200 */  addu       $v1, $v1, $v0
/* 8F5F688 8008D158 4000A3AF */  sw         $v1, 0x40($sp)
/* 8F5F68C 8008D15C 3800A38F */  lw         $v1, 0x38($sp)
/* 8F5F690 8008D160 03002296 */  lhu        $v0, 0x3($s1)
/* 8F5F694 8008D164 00000000 */  nop
/* 8F5F698 8008D168 21104300 */  addu       $v0, $v0, $v1
/* 8F5F69C 8008D16C 030022A6 */  sh         $v0, 0x3($s1)
/* 8F5F6A0 8008D170 3C00A38F */  lw         $v1, 0x3C($sp)
/* 8F5F6A4 8008D174 05002296 */  lhu        $v0, 0x5($s1)
/* 8F5F6A8 8008D178 00000000 */  nop
/* 8F5F6AC 8008D17C 21104300 */  addu       $v0, $v0, $v1
/* 8F5F6B0 8008D180 050022A6 */  sh         $v0, 0x5($s1)
/* 8F5F6B4 8008D184 4000A38F */  lw         $v1, 0x40($sp)
/* 8F5F6B8 8008D188 07002296 */  lhu        $v0, 0x7($s1)
/* 8F5F6BC 8008D18C 00000000 */  nop
/* 8F5F6C0 8008D190 21104300 */  addu       $v0, $v0, $v1
/* 8F5F6C4 8008D194 070022A6 */  sh         $v0, 0x7($s1)
/* 8F5F6C8 8008D198 3800A28F */  lw         $v0, 0x38($sp)
/* 8F5F6CC 8008D19C 03002396 */  lhu        $v1, 0x3($s1)
/* 8F5F6D0 8008D1A0 40100200 */  sll        $v0, $v0, 1
/* 8F5F6D4 8008D1A4 23186200 */  subu       $v1, $v1, $v0
/* 8F5F6D8 8008D1A8 090023A6 */  sh         $v1, 0x9($s1)
/* 8F5F6DC 8008D1AC 3C00A28F */  lw         $v0, 0x3C($sp)
/* 8F5F6E0 8008D1B0 05002396 */  lhu        $v1, 0x5($s1)
/* 8F5F6E4 8008D1B4 40100200 */  sll        $v0, $v0, 1
/* 8F5F6E8 8008D1B8 23186200 */  subu       $v1, $v1, $v0
/* 8F5F6EC 8008D1BC 0B0023A6 */  sh         $v1, 0xB($s1)
/* 8F5F6F0 8008D1C0 4000A28F */  lw         $v0, 0x40($sp)
/* 8F5F6F4 8008D1C4 07002396 */  lhu        $v1, 0x7($s1)
/* 8F5F6F8 8008D1C8 40100200 */  sll        $v0, $v0, 1
/* 8F5F6FC 8008D1CC 23186200 */  subu       $v1, $v1, $v0
/* 8F5F700 8008D1D0 03350208 */  j          .Llevel_46_8008D40C
/* 8F5F704 8008D1D4 0D0023A6 */   sh        $v1, 0xD($s1)
.L8008D1D8_:
/* 8F5F708 8008D1D8 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5F70C 8008D1DC 00000000 */  nop
/* 8F5F710 8008D1E0 01004224 */  addiu      $v0, $v0, 0x1
/* 8F5F714 8008D1E4 010022A2 */  sb         $v0, 0x1($s1)
/* 8F5F718 8008D1E8 FF004230 */  andi       $v0, $v0, 0xFF
/* 8F5F71C 8008D1EC 2800422C */  sltiu      $v0, $v0, 0x28
/* 8F5F720 8008D1F0 71004010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5F724 8008D1F4 00000000 */   nop
/* 8F5F728 8008D1F8 02002292 */  lbu        $v0, 0x2($s1)
/* 8F5F72C 8008D1FC 00000000 */  nop
/* 8F5F730 8008D200 6D004010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5F734 8008D204 00000000 */   nop
/* 8F5F738 8008D208 03002296 */  lhu        $v0, 0x3($s1)
/* 8F5F73C 8008D20C 0F002396 */  lhu        $v1, 0xF($s1)
/* 8F5F740 8008D210 11002496 */  lhu        $a0, 0x11($s1)
/* 8F5F744 8008D214 13002596 */  lhu        $a1, 0x13($s1)
/* 8F5F748 8008D218 21104300 */  addu       $v0, $v0, $v1
/* 8F5F74C 8008D21C 030022A6 */  sh         $v0, 0x3($s1)
/* 8F5F750 8008D220 05002296 */  lhu        $v0, 0x5($s1)
/* 8F5F754 8008D224 07002396 */  lhu        $v1, 0x7($s1)
/* 8F5F758 8008D228 21104400 */  addu       $v0, $v0, $a0
/* 8F5F75C 8008D22C 21186500 */  addu       $v1, $v1, $a1
/* 8F5F760 8008D230 050022A6 */  sh         $v0, 0x5($s1)
/* 8F5F764 8008D234 9171010C */  jal        func_8005C644
/* 8F5F768 8008D238 070023A6 */   sh        $v1, 0x7($s1)
/* 8F5F76C 8008D23C 0F002396 */  lhu        $v1, 0xF($s1)
/* 8F5F770 8008D240 02004230 */  andi       $v0, $v0, 0x2
/* 8F5F774 8008D244 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 8F5F778 8008D248 21186200 */  addu       $v1, $v1, $v0
/* 8F5F77C 8008D24C 9171010C */  jal        func_8005C644
/* 8F5F780 8008D250 0F0023A6 */   sh        $v1, 0xF($s1)
/* 8F5F784 8008D254 11002396 */  lhu        $v1, 0x11($s1)
/* 8F5F788 8008D258 02004230 */  andi       $v0, $v0, 0x2
/* 8F5F78C 8008D25C FFFF6324 */  addiu      $v1, $v1, -0x1
/* 8F5F790 8008D260 21186200 */  addu       $v1, $v1, $v0
/* 8F5F794 8008D264 9171010C */  jal        func_8005C644
/* 8F5F798 8008D268 110023A6 */   sh        $v1, 0x11($s1)
/* 8F5F79C 8008D26C 13002396 */  lhu        $v1, 0x13($s1)
/* 8F5F7A0 8008D270 02004230 */  andi       $v0, $v0, 0x2
/* 8F5F7A4 8008D274 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 8F5F7A8 8008D278 21186200 */  addu       $v1, $v1, $v0
/* 8F5F7AC 8008D27C 130023A6 */  sh         $v1, 0x13($s1)
/* 8F5F7B0 8008D280 001C0300 */  sll        $v1, $v1, 16
/* 8F5F7B4 8008D284 031C0300 */  sra        $v1, $v1, 16
/* 8F5F7B8 8008D288 03006328 */  slti       $v1, $v1, 0x3
/* 8F5F7BC 8008D28C 02006014 */  bnez       $v1, .Llevel_46_8008D298
/* 8F5F7C0 8008D290 02000224 */   addiu     $v0, $zero, 0x2
/* 8F5F7C4 8008D294 130022A6 */  sh         $v0, 0x13($s1)
.Llevel_46_8008D298:
/* 8F5F7C8 8008D298 13002286 */  lh         $v0, 0x13($s1)
/* 8F5F7CC 8008D29C 00000000 */  nop
/* 8F5F7D0 8008D2A0 FCFF4228 */  slti       $v0, $v0, -0x4
/* 8F5F7D4 8008D2A4 02004010 */  beqz       $v0, .Llevel_46_8008D2B0
/* 8F5F7D8 8008D2A8 FCFF0224 */   addiu     $v0, $zero, -0x4
/* 8F5F7DC 8008D2AC 130022A6 */  sh         $v0, 0x13($s1)
.Llevel_46_8008D2B0:
/* 8F5F7E0 8008D2B0 0B002292 */  lbu        $v0, 0xB($s1)
/* 8F5F7E4 8008D2B4 0D002392 */  lbu        $v1, 0xD($s1)
/* 8F5F7E8 8008D2B8 FEFF4224 */  addiu      $v0, $v0, -0x2
/* 8F5F7EC 8008D2BC 0B0022A2 */  sb         $v0, 0xB($s1)
/* 8F5F7F0 8008D2C0 0C002292 */  lbu        $v0, 0xC($s1)
/* 8F5F7F4 8008D2C4 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 8F5F7F8 8008D2C8 0D0023A2 */  sb         $v1, 0xD($s1)
/* 8F5F7FC 8008D2CC FEFF4224 */  addiu      $v0, $v0, -0x2
/* 8F5F800 8008D2D0 03350208 */  j          .Llevel_46_8008D40C
/* 8F5F804 8008D2D4 0C0022A2 */   sb        $v0, 0xC($s1)
.L8008D2D8_:
/* 8F5F808 8008D2D8 09002486 */  lh         $a0, 0x9($s1)
/* 8F5F80C 8008D2DC 03002286 */  lh         $v0, 0x3($s1)
/* 8F5F810 8008D2E0 00000000 */  nop
/* 8F5F814 8008D2E4 23208200 */  subu       $a0, $a0, $v0
/* 8F5F818 8008D2E8 43200400 */  sra        $a0, $a0, 1
/* 8F5F81C 8008D2EC 2000A4A7 */  sh         $a0, 0x20($sp)
/* 8F5F820 8008D2F0 0B002286 */  lh         $v0, 0xB($s1)
/* 8F5F824 8008D2F4 05002386 */  lh         $v1, 0x5($s1)
/* 8F5F828 8008D2F8 00000000 */  nop
/* 8F5F82C 8008D2FC 23104300 */  subu       $v0, $v0, $v1
/* 8F5F830 8008D300 43100200 */  sra        $v0, $v0, 1
/* 8F5F834 8008D304 2200A2A7 */  sh         $v0, 0x22($sp)
/* 8F5F838 8008D308 0D002286 */  lh         $v0, 0xD($s1)
/* 8F5F83C 8008D30C 07002386 */  lh         $v1, 0x7($s1)
/* 8F5F840 8008D310 00000000 */  nop
/* 8F5F844 8008D314 23104300 */  subu       $v0, $v0, $v1
/* 8F5F848 8008D318 43100200 */  sra        $v0, $v0, 1
/* 8F5F84C 8008D31C 2400A2A7 */  sh         $v0, 0x24($sp)
/* 8F5F850 8008D320 03002296 */  lhu        $v0, 0x3($s1)
/* 8F5F854 8008D324 00000000 */  nop
/* 8F5F858 8008D328 21104400 */  addu       $v0, $v0, $a0
/* 8F5F85C 8008D32C 030022A6 */  sh         $v0, 0x3($s1)
/* 8F5F860 8008D330 05002296 */  lhu        $v0, 0x5($s1)
/* 8F5F864 8008D334 2200A397 */  lhu        $v1, 0x22($sp)
/* 8F5F868 8008D338 00000000 */  nop
/* 8F5F86C 8008D33C 21104300 */  addu       $v0, $v0, $v1
/* 8F5F870 8008D340 050022A6 */  sh         $v0, 0x5($s1)
/* 8F5F874 8008D344 07002296 */  lhu        $v0, 0x7($s1)
/* 8F5F878 8008D348 2400A397 */  lhu        $v1, 0x24($sp)
/* 8F5F87C 8008D34C 00000000 */  nop
/* 8F5F880 8008D350 21104300 */  addu       $v0, $v0, $v1
/* 8F5F884 8008D354 070022A6 */  sh         $v0, 0x7($s1)
/* 8F5F888 8008D358 09002296 */  lhu        $v0, 0x9($s1)
/* 8F5F88C 8008D35C 2000A397 */  lhu        $v1, 0x20($sp)
/* 8F5F890 8008D360 00000000 */  nop
/* 8F5F894 8008D364 21104300 */  addu       $v0, $v0, $v1
/* 8F5F898 8008D368 090022A6 */  sh         $v0, 0x9($s1)
/* 8F5F89C 8008D36C 0B002296 */  lhu        $v0, 0xB($s1)
/* 8F5F8A0 8008D370 2200A397 */  lhu        $v1, 0x22($sp)
/* 8F5F8A4 8008D374 00000000 */  nop
/* 8F5F8A8 8008D378 21104300 */  addu       $v0, $v0, $v1
/* 8F5F8AC 8008D37C 0D002396 */  lhu        $v1, 0xD($s1)
/* 8F5F8B0 8008D380 0B0022A6 */  sh         $v0, 0xB($s1)
/* 8F5F8B4 8008D384 01002292 */  lbu        $v0, 0x1($s1)
/* 8F5F8B8 8008D388 2400A497 */  lhu        $a0, 0x24($sp)
/* 8F5F8BC 8008D38C 01004224 */  addiu      $v0, $v0, 0x1
/* 8F5F8C0 8008D390 21186400 */  addu       $v1, $v1, $a0
/* 8F5F8C4 8008D394 010022A2 */  sb         $v0, 0x1($s1)
/* 8F5F8C8 8008D398 FF004230 */  andi       $v0, $v0, 0xFF
/* 8F5F8CC 8008D39C 1800422C */  sltiu      $v0, $v0, 0x18
/* 8F5F8D0 8008D3A0 05004010 */  beqz       $v0, .Llevel_46_8008D3B8
/* 8F5F8D4 8008D3A4 0D0023A6 */   sh        $v1, 0xD($s1)
/* 8F5F8D8 8008D3A8 02002292 */  lbu        $v0, 0x2($s1)
/* 8F5F8DC 8008D3AC 00000000 */  nop
/* 8F5F8E0 8008D3B0 05004014 */  bnez       $v0, .Llevel_46_8008D3C8
/* 8F5F8E4 8008D3B4 00000000 */   nop
.Llevel_46_8008D3B8:
/* 8F5F8E8 8008D3B8 4159010C */  jal        func_80056504
/* 8F5F8EC 8008D3BC 21204002 */   addu      $a0, $s2, $zero
/* 8F5F8F0 8008D3C0 04350208 */  j          .Llevel_46_8008D410
/* 8F5F8F4 8008D3C4 20003126 */   addiu     $s1, $s1, 0x20
.Llevel_46_8008D3C8:
/* 8F5F8F8 8008D3C8 11002292 */  lbu        $v0, 0x11($s1)
/* 8F5F8FC 8008D3CC 15002392 */  lbu        $v1, 0x15($s1)
/* 8F5F900 8008D3D0 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 8F5F904 8008D3D4 110022A2 */  sb         $v0, 0x11($s1)
/* 8F5F908 8008D3D8 10002292 */  lbu        $v0, 0x10($s1)
/* 8F5F90C 8008D3DC FDFF6324 */  addiu      $v1, $v1, -0x3
/* 8F5F910 8008D3E0 150023A2 */  sb         $v1, 0x15($s1)
/* 8F5F914 8008D3E4 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 8F5F918 8008D3E8 100022A2 */  sb         $v0, 0x10($s1)
/* 8F5F91C 8008D3EC 14002292 */  lbu        $v0, 0x14($s1)
/* 8F5F920 8008D3F0 13002392 */  lbu        $v1, 0x13($s1)
/* 8F5F924 8008D3F4 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 8F5F928 8008D3F8 140022A2 */  sb         $v0, 0x14($s1)
/* 8F5F92C 8008D3FC 0600622C */  sltiu      $v0, $v1, 0x6
/* 8F5F930 8008D400 02004014 */  bnez       $v0, .Llevel_46_8008D40C
/* 8F5F934 8008D404 FAFF6224 */   addiu     $v0, $v1, -0x6
/* 8F5F938 8008D408 130022A2 */  sb         $v0, 0x13($s1)
.Llevel_46_8008D40C:
/* 8F5F93C 8008D40C 20003126 */  addiu      $s1, $s1, 0x20
.Llevel_46_8008D410:
/* 8F5F940 8008D410 2000F726 */  addiu      $s7, $s7, 0x20
/* 8F5F944 8008D414 20007326 */  addiu      $s3, $s3, 0x20
/* 8F5F948 8008D418 00002492 */  lbu        $a0, 0x0($s1)
/* 8F5F94C 8008D41C FF000224 */  addiu      $v0, $zero, 0xFF
/* 8F5F950 8008D420 FF008330 */  andi       $v1, $a0, 0xFF
/* 8F5F954 8008D424 98FB6214 */  bne        $v1, $v0, .Llevel_46_8008C288
/* 8F5F958 8008D428 20005226 */   addiu     $s2, $s2, 0x20
/* 8F5F95C 8008D42C 21104002 */  addu       $v0, $s2, $zero
.Llevel_46_8008D430:
/* 8F5F960 8008D430 7400BF8F */  lw         $ra, 0x74($sp)
/* 8F5F964 8008D434 7000BE8F */  lw         $fp, 0x70($sp)
/* 8F5F968 8008D438 6C00B78F */  lw         $s7, 0x6C($sp)
/* 8F5F96C 8008D43C 6800B68F */  lw         $s6, 0x68($sp)
/* 8F5F970 8008D440 6400B58F */  lw         $s5, 0x64($sp)
/* 8F5F974 8008D444 6000B48F */  lw         $s4, 0x60($sp)
/* 8F5F978 8008D448 5C00B38F */  lw         $s3, 0x5C($sp)
/* 8F5F97C 8008D44C 5800B28F */  lw         $s2, 0x58($sp)
/* 8F5F980 8008D450 5400B18F */  lw         $s1, 0x54($sp)
/* 8F5F984 8008D454 5000B08F */  lw         $s0, 0x50($sp)
/* 8F5F988 8008D458 7800BD27 */  addiu      $sp, $sp, 0x78
/* 8F5F98C 8008D45C 0800E003 */  jr         $ra
/* 8F5F990 8008D460 00000000 */   nop
.size func_level_46_8008C224, . - func_level_46_8008C224
