.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_23_80074740
/* 5A90C70 80074740 20FD0780 */ .word .L8007FD20_
/* 5A90C74 80074744 20FD0780 */ .word .L8007FD20_
/* 5A90C78 80074748 D4000880 */ .word .L800800D4_
/* 5A90C7C 8007474C C0FF0780 */ .word .L8007FFC0_
/* 5A90C80 80074750 A8000880 */ .word .L800800A8_
/* 5A90C84 80074754 F8FF0780 */ .word .L8007FFF8_
/* 5A90C88 80074758 BC030880 */ .word .L800803BC_
/* 5A90C8C 8007475C 04060880 */ .word .L80080604_
/* 5A90C90 80074760 B0060880 */ .word .Llevel_23_800806B0
/* 5A90C94 80074764 B0060880 */ .word .Llevel_23_800806B0
/* 5A90C98 80074768 B0060880 */ .word .Llevel_23_800806B0
/* 5A90C9C 8007476C B0060880 */ .word .Llevel_23_800806B0
/* 5A90CA0 80074770 B0060880 */ .word .Llevel_23_800806B0
/* 5A90CA4 80074774 B0060880 */ .word .Llevel_23_800806B0
/* 5A90CA8 80074778 B0060880 */ .word .Llevel_23_800806B0
/* 5A90CAC 8007477C B0060880 */ .word .Llevel_23_800806B0
/* 5A90CB0 80074780 B0060880 */ .word .Llevel_23_800806B0
/* 5A90CB4 80074784 B0060880 */ .word .Llevel_23_800806B0
/* 5A90CB8 80074788 B0060880 */ .word .Llevel_23_800806B0
/* 5A90CBC 8007478C B0060880 */ .word .Llevel_23_800806B0
/* 5A90CC0 80074790 F0FD0780 */ .word .L8007FDF0_
/* 5A90CC4 80074794 FC020880 */ .word .L800802FC_
/* 5A90CC8 80074798 3CFE0780 */ .word .L8007FE3C_
/* 5A90CCC 8007479C 8CFE0780 */ .word .L8007FE8C_
/* 5A90CD0 800747A0 20040880 */ .word .L80080420_
/* 5A90CD4 800747A4 14050880 */ .word .L80080514_
.size jtbl_level_23_80074740, . - jtbl_level_23_80074740


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_23_8007FAD4
/* 5A9C004 8007FAD4 98FFBD27 */  addiu      $sp, $sp, -0x68
/* 5A9C008 8007FAD8 5400B1AF */  sw         $s1, 0x54($sp)
/* 5A9C00C 8007FADC 21888000 */  addu       $s1, $a0, $zero
/* 5A9C010 8007FAE0 6000B4AF */  sw         $s4, 0x60($sp)
/* 5A9C014 8007FAE4 6400BFAF */  sw         $ra, 0x64($sp)
/* 5A9C018 8007FAE8 5C00B3AF */  sw         $s3, 0x5C($sp)
/* 5A9C01C 8007FAEC 5800B2AF */  sw         $s2, 0x58($sp)
/* 5A9C020 8007FAF0 5000B0AF */  sw         $s0, 0x50($sp)
/* 5A9C024 8007FAF4 49002292 */  lbu        $v0, 0x49($s1)
/* 5A9C028 8007FAF8 0000338E */  lw         $s3, 0x0($s1)
/* 5A9C02C 8007FAFC 13004014 */  bnez       $v0, .Llevel_23_8007FB4C
/* 5A9C030 8007FB00 21A00000 */   addu      $s4, $zero, $zero
/* 5A9C034 8007FB04 01000224 */  addiu      $v0, $zero, 0x1
/* 5A9C038 8007FB08 490022A2 */  sb         $v0, 0x49($s1)
/* 5A9C03C 8007FB0C 1400648E */  lw         $a0, 0x14($s3)
/* 5A9C040 8007FB10 64000224 */  addiu      $v0, $zero, 0x64
/* 5A9C044 8007FB14 06008010 */  beqz       $a0, .Llevel_23_8007FB30
/* 5A9C048 8007FB18 0C0062A6 */   sh        $v0, 0xC($s3)
/* 5A9C04C 8007FB1C 01000324 */  addiu      $v1, $zero, 0x1
/* 5A9C050 8007FB20 0A0083A4 */  sh         $v1, 0xA($a0)
/* 5A9C054 8007FB24 1400628E */  lw         $v0, 0x14($s3)
/* 5A9C058 8007FB28 00000000 */  nop
/* 5A9C05C 8007FB2C 020043A4 */  sh         $v1, 0x2($v0)
.Llevel_23_8007FB30:
/* 5A9C060 8007FB30 0C002426 */  addiu      $a0, $s1, 0xC
/* 5A9C064 8007FB34 D668000C */  jal        func_8001A358
/* 5A9C068 8007FB38 00080524 */   addiu     $a1, $zero, 0x800
/* 5A9C06C 8007FB3C 03004010 */  beqz       $v0, .Llevel_23_8007FB4C
/* 5A9C070 8007FB40 00000000 */   nop
/* 5A9C074 8007FB44 080062AE */  sw         $v0, 0x8($s3)
/* 5A9C078 8007FB48 140022AE */  sw         $v0, 0x14($s1)
.Llevel_23_8007FB4C:
/* 5A9C07C 8007FB4C 2400658E */  lw         $a1, 0x24($s3)
/* 5A9C080 8007FB50 F0EF000C */  jal        func_8003BFC0
/* 5A9C084 8007FB54 21202002 */   addu      $a0, $s1, $zero
/* 5A9C088 8007FB58 05004014 */  bnez       $v0, .Llevel_23_8007FB70
/* 5A9C08C 8007FB5C 21202002 */   addu      $a0, $s1, $zero
/* 5A9C090 8007FB60 21280000 */  addu       $a1, $zero, $zero
/* 5A9C094 8007FB64 AFEE000C */  jal        func_8003BABC
/* 5A9C098 8007FB68 04000624 */   addiu     $a2, $zero, 0x4
/* 5A9C09C 8007FB6C 240062AE */  sw         $v0, 0x24($s3)
.Llevel_23_8007FB70:
/* 5A9C0A0 8007FB70 48002392 */  lbu        $v1, 0x48($s1)
/* 5A9C0A4 8007FB74 07000224 */  addiu      $v0, $zero, 0x7
/* 5A9C0A8 8007FB78 5C006210 */  beq        $v1, $v0, .Llevel_23_8007FCEC
/* 5A9C0AC 8007FB7C 21202002 */   addu      $a0, $s1, $zero
/* 5A9C0B0 8007FB80 1800228E */  lw         $v0, 0x18($s1)
/* 5A9C0B4 8007FB84 00000000 */  nop
/* 5A9C0B8 8007FB88 40004010 */  beqz       $v0, .Llevel_23_8007FC8C
/* 5A9C0BC 8007FB8C 0C002426 */   addiu     $a0, $s1, 0xC
/* 5A9C0C0 8007FB90 0780013C */  lui        $at, %hi(D_8006E160)
/* 5A9C0C4 8007FB94 60E120AC */  sw         $zero, %lo(D_8006E160)($at)
/* 5A9C0C8 8007FB98 0780013C */  lui        $at, %hi(D_8006E164)
/* 5A9C0CC 8007FB9C 64E120AC */  sw         $zero, %lo(D_8006E164)($at)
/* 5A9C0D0 8007FBA0 D668000C */  jal        func_8001A358
/* 5A9C0D4 8007FBA4 00100524 */   addiu     $a1, $zero, 0x1000
/* 5A9C0D8 8007FBA8 08004010 */  beqz       $v0, .Llevel_23_8007FBCC
/* 5A9C0DC 8007FBAC 00000000 */   nop
/* 5A9C0E0 8007FBB0 0780023C */  lui        $v0, %hi(D_80071934)
/* 5A9C0E4 8007FBB4 3419428C */  lw         $v0, %lo(D_80071934)($v0)
/* 5A9C0E8 8007FBB8 00000000 */  nop
/* 5A9C0EC 8007FBBC 03004010 */  beqz       $v0, .Llevel_23_8007FBCC
/* 5A9C0F0 8007FBC0 21202002 */   addu      $a0, $s1, $zero
/* 5A9C0F4 8007FBC4 FBFE0108 */  j          .Llevel_23_8007FBEC
/* 5A9C0F8 8007FBC8 10000524 */   addiu     $a1, $zero, 0x10
.Llevel_23_8007FBCC:
/* 5A9C0FC 8007FBCC 1800228E */  lw         $v0, 0x18($s1)
/* 5A9C100 8007FBD0 0100033C */  lui        $v1, (0x10000 >> 16)
/* 5A9C104 8007FBD4 24104300 */  and        $v0, $v0, $v1
/* 5A9C108 8007FBD8 03004010 */  beqz       $v0, .Llevel_23_8007FBE8
/* 5A9C10C 8007FBDC 21202002 */   addu      $a0, $s1, $zero
/* 5A9C110 8007FBE0 FBFE0108 */  j          .Llevel_23_8007FBEC
/* 5A9C114 8007FBE4 01000524 */   addiu     $a1, $zero, 0x1
.Llevel_23_8007FBE8:
/* 5A9C118 8007FBE8 21280000 */  addu       $a1, $zero, $zero
.Llevel_23_8007FBEC:
/* 5A9C11C 8007FBEC 21300000 */  addu       $a2, $zero, $zero
/* 5A9C120 8007FBF0 9ADA000C */  jal        func_80036A68
/* 5A9C124 8007FBF4 21380000 */   addu      $a3, $zero, $zero
/* 5A9C128 8007FBF8 21202002 */  addu       $a0, $s1, $zero
/* 5A9C12C 8007FBFC 80000524 */  addiu      $a1, $zero, 0x80
/* 5A9C130 8007FC00 21300000 */  addu       $a2, $zero, $zero
/* 5A9C134 8007FC04 CFD5000C */  jal        func_8003573C
/* 5A9C138 8007FC08 21380000 */   addu      $a3, $zero, $zero
/* 5A9C13C 8007FC0C 21202002 */  addu       $a0, $s1, $zero
/* 5A9C140 8007FC10 07000524 */  addiu      $a1, $zero, 0x7
/* 5A9C144 8007FC14 FF000224 */  addiu      $v0, $zero, 0xFF
/* 5A9C148 8007FC18 4A0022A2 */  sb         $v0, 0x4A($s1)
/* 5A9C14C 8007FC1C 07000224 */  addiu      $v0, $zero, 0x7
/* 5A9C150 8007FC20 D0D3000C */  jal        func_80034F40
/* 5A9C154 8007FC24 480022A2 */   sb        $v0, 0x48($s1)
/* 5A9C158 8007FC28 FA000224 */  addiu      $v0, $zero, 0xFA
/* 5A9C15C 8007FC2C 200062AE */  sw         $v0, 0x20($s3)
/* 5A9C160 8007FC30 C8000224 */  addiu      $v0, $zero, 0xC8
/* 5A9C164 8007FC34 1C0062AE */  sw         $v0, 0x1C($s3)
/* 5A9C168 8007FC38 51002292 */  lbu        $v0, 0x51($s1)
/* 5A9C16C 8007FC3C 00000000 */  nop
/* 5A9C170 8007FC40 10004014 */  bnez       $v0, .Llevel_23_8007FC84
/* 5A9C174 8007FC44 21300000 */   addu      $a2, $zero, $zero
/* 5A9C178 8007FC48 0C00238E */  lw         $v1, 0xC($s1)
/* 5A9C17C 8007FC4C 0780043C */  lui        $a0, %hi(D_80070328)
/* 5A9C180 8007FC50 2803848C */  lw         $a0, %lo(D_80070328)($a0)
/* 5A9C184 8007FC54 1000228E */  lw         $v0, 0x10($s1)
/* 5A9C188 8007FC58 0780053C */  lui        $a1, %hi(D_80070328 + 4)
/* 5A9C18C 8007FC5C 2C03A58C */  lw         $a1, %lo(D_80070328 + 4)($a1)
/* 5A9C190 8007FC60 23206400 */  subu       $a0, $v1, $a0
/* 5A9C194 8007FC64 203A010C */  jal        func_8004E880
/* 5A9C198 8007FC68 23284500 */   subu      $a1, $v0, $a1
/* 5A9C19C 8007FC6C 21204000 */  addu       $a0, $v0, $zero
/* 5A9C1A0 8007FC70 20000624 */  addiu      $a2, $zero, 0x20
/* 5A9C1A4 8007FC74 0780053C */  lui        $a1, %hi(D_80070328 + 0xE)
/* 5A9C1A8 8007FC78 3603A590 */  lbu        $a1, %lo(D_80070328 + 0xE)($a1)
/* 5A9C1AC 8007FC7C 3ED8000C */  jal        func_800360F8
/* 5A9C1B0 8007FC80 40000724 */   addiu     $a3, $zero, 0x40
.Llevel_23_8007FC84:
/* 5A9C1B4 8007FC84 CD010208 */  j          .Llevel_23_80080734
/* 5A9C1B8 8007FC88 180062AE */   sw        $v0, 0x18($s3)
.Llevel_23_8007FC8C:
/* 5A9C1BC 8007FC8C 0780043C */  lui        $a0, %hi(D_80070328)
/* 5A9C1C0 8007FC90 28038424 */  addiu      $a0, $a0, %lo(D_80070328)
/* 5A9C1C4 8007FC94 28006526 */  addiu      $a1, $s3, 0x28
/* 5A9C1C8 8007FC98 21300000 */  addu       $a2, $zero, $zero
/* 5A9C1CC 8007FC9C 88D8000C */  jal        func_80036220
/* 5A9C1D0 8007FCA0 00280724 */   addiu     $a3, $zero, 0x2800
/* 5A9C1D4 8007FCA4 0C004010 */  beqz       $v0, .Llevel_23_8007FCD8
/* 5A9C1D8 8007FCA8 00000000 */   nop
/* 5A9C1DC 8007FCAC 3000628E */  lw         $v0, 0x30($s3)
/* 5A9C1E0 8007FCB0 0780033C */  lui        $v1, %hi(D_80070328 + 8)
/* 5A9C1E4 8007FCB4 3003638C */  lw         $v1, %lo(D_80070328 + 8)($v1)
/* 5A9C1E8 8007FCB8 00000000 */  nop
/* 5A9C1EC 8007FCBC 2A104300 */  slt        $v0, $v0, $v1
/* 5A9C1F0 8007FCC0 05004010 */  beqz       $v0, .Llevel_23_8007FCD8
/* 5A9C1F4 8007FCC4 21202002 */   addu      $a0, $s1, $zero
/* 5A9C1F8 8007FCC8 B34E000C */  jal        func_80013ACC
/* 5A9C1FC 8007FCCC 0D000524 */   addiu     $a1, $zero, 0xD
/* 5A9C200 8007FCD0 3BFF0108 */  j          .Llevel_23_8007FCEC
/* 5A9C204 8007FCD4 21202002 */   addu      $a0, $s1, $zero
.Llevel_23_8007FCD8:
/* 5A9C208 8007FCD8 0780013C */  lui        $at, %hi(D_8006E160)
/* 5A9C20C 8007FCDC 60E120AC */  sw         $zero, %lo(D_8006E160)($at)
/* 5A9C210 8007FCE0 0780013C */  lui        $at, %hi(D_8006E164)
/* 5A9C214 8007FCE4 64E120AC */  sw         $zero, %lo(D_8006E164)($at)
/* 5A9C218 8007FCE8 21202002 */  addu       $a0, $s1, $zero
.Llevel_23_8007FCEC:
/* 5A9C21C 8007FCEC 4957010C */  jal        func_80055D24
/* 5A9C220 8007FCF0 05000524 */   addiu     $a1, $zero, 0x5
/* 5A9C224 8007FCF4 48002392 */  lbu        $v1, 0x48($s1)
/* 5A9C228 8007FCF8 00000000 */  nop
/* 5A9C22C 8007FCFC 1A00622C */  sltiu      $v0, $v1, 0x1A
/* 5A9C230 8007FD00 6B024010 */  beqz       $v0, .Llevel_23_800806B0
/* 5A9C234 8007FD04 80100300 */   sll       $v0, $v1, 2
/* 5A9C238 8007FD08 0780013C */  lui        $at, %hi(jtbl_level_23_80074740)
/* 5A9C23C 8007FD0C 21082200 */  addu       $at, $at, $v0
/* 5A9C240 8007FD10 4047228C */  lw         $v0, %lo(jtbl_level_23_80074740)($at)
/* 5A9C244 8007FD14 00000000 */  nop
/* 5A9C248 8007FD18 08004000 */  jr         $v0
/* 5A9C24C 8007FD1C 00000000 */   nop
.L8007FD20_:
/* 5A9C250 8007FD20 49002392 */  lbu        $v1, 0x49($s1)
/* 5A9C254 8007FD24 02000224 */  addiu      $v0, $zero, 0x2
/* 5A9C258 8007FD28 05006214 */  bne        $v1, $v0, .Llevel_23_8007FD40
/* 5A9C25C 8007FD2C 19000224 */   addiu     $v0, $zero, 0x19
/* 5A9C260 8007FD30 480022A2 */  sb         $v0, 0x48($s1)
/* 5A9C264 8007FD34 01000224 */  addiu      $v0, $zero, 0x1
/* 5A9C268 8007FD38 AC010208 */  j          .Llevel_23_800806B0
/* 5A9C26C 8007FD3C 490022A2 */   sb        $v0, 0x49($s1)
.Llevel_23_8007FD40:
/* 5A9C270 8007FD40 0780053C */  lui        $a1, %hi(D_80070328)
/* 5A9C274 8007FD44 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 5A9C278 8007FD48 CD3C010C */  jal        func_8004F334
/* 5A9C27C 8007FD4C 0C002426 */   addiu     $a0, $s1, 0xC
/* 5A9C280 8007FD50 0E006386 */  lh         $v1, 0xE($s3)
/* 5A9C284 8007FD54 00000000 */  nop
/* 5A9C288 8007FD58 2A104300 */  slt        $v0, $v0, $v1
/* 5A9C28C 8007FD5C 0C004010 */  beqz       $v0, .Llevel_23_8007FD90
/* 5A9C290 8007FD60 00000000 */   nop
/* 5A9C294 8007FD64 0780023C */  lui        $v0, %hi(D_80070328 + 8)
/* 5A9C298 8007FD68 3003428C */  lw         $v0, %lo(D_80070328 + 8)($v0)
/* 5A9C29C 8007FD6C 1400238E */  lw         $v1, 0x14($s1)
/* 5A9C2A0 8007FD70 00000000 */  nop
/* 5A9C2A4 8007FD74 23104300 */  subu       $v0, $v0, $v1
/* 5A9C2A8 8007FD78 02004104 */  bgez       $v0, .Llevel_23_8007FD84
/* 5A9C2AC 8007FD7C 00000000 */   nop
/* 5A9C2B0 8007FD80 23100200 */  negu       $v0, $v0
.Llevel_23_8007FD84:
/* 5A9C2B4 8007FD84 00104228 */  slti       $v0, $v0, 0x1000
/* 5A9C2B8 8007FD88 83004014 */  bnez       $v0, .Llevel_23_8007FF98
/* 5A9C2BC 8007FD8C 21202002 */   addu      $a0, $s1, $zero
.Llevel_23_8007FD90:
/* 5A9C2C0 8007FD90 0C006426 */  addiu      $a0, $s3, 0xC
/* 5A9C2C4 8007FD94 69D6000C */  jal        func_800359A4
/* 5A9C2C8 8007FD98 02000524 */   addiu     $a1, $zero, 0x2
/* 5A9C2CC 8007FD9C 06004010 */  beqz       $v0, .Llevel_23_8007FDB8
/* 5A9C2D0 8007FDA0 21202002 */   addu      $a0, $s1, $zero
/* 5A9C2D4 8007FDA4 D0D3000C */  jal        func_80034F40
/* 5A9C2D8 8007FDA8 01000524 */   addiu     $a1, $zero, 0x1
/* 5A9C2DC 8007FDAC F4010224 */  addiu      $v0, $zero, 0x1F4
/* 5A9C2E0 8007FDB0 AC010208 */  j          .Llevel_23_800806B0
/* 5A9C2E4 8007FDB4 0C0062A6 */   sh        $v0, 0xC($s3)
.Llevel_23_8007FDB8:
/* 5A9C2E8 8007FDB8 0780023C */  lui        $v0, %hi(D_8006C770)
/* 5A9C2EC 8007FDBC 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 5A9C2F0 8007FDC0 00000000 */  nop
/* 5A9C2F4 8007FDC4 3A024010 */  beqz       $v0, .Llevel_23_800806B0
/* 5A9C2F8 8007FDC8 00000000 */   nop
/* 5A9C2FC 8007FDCC 9171010C */  jal        func_8005C644
/* 5A9C300 8007FDD0 00000000 */   nop
/* 5A9C304 8007FDD4 03004230 */  andi       $v0, $v0, 0x3
/* 5A9C308 8007FDD8 00190200 */  sll        $v1, $v0, 4
/* 5A9C30C 8007FDDC 23186200 */  subu       $v1, $v1, $v0
/* 5A9C310 8007FDE0 80180300 */  sll        $v1, $v1, 2
/* 5A9C314 8007FDE4 64006324 */  addiu      $v1, $v1, 0x64
/* 5A9C318 8007FDE8 03010208 */  j          .Llevel_23_8008040C
/* 5A9C31C 8007FDEC 0C0063A6 */   sh        $v1, 0xC($s3)
.L8007FDF0_:
/* 5A9C320 8007FDF0 21202002 */  addu       $a0, $s1, $zero
/* 5A9C324 8007FDF4 04000524 */  addiu      $a1, $zero, 0x4
/* 5A9C328 8007FDF8 08000624 */  addiu      $a2, $zero, 0x8
/* 5A9C32C 8007FDFC CFD5000C */  jal        func_8003573C
/* 5A9C330 8007FE00 21380000 */   addu      $a3, $zero, $zero
/* 5A9C334 8007FE04 05004010 */  beqz       $v0, .Llevel_23_8007FE1C
/* 5A9C338 8007FE08 03000224 */   addiu     $v0, $zero, 0x3
/* 5A9C33C 8007FE0C 480022A2 */  sb         $v0, 0x48($s1)
/* 5A9C340 8007FE10 21202002 */  addu       $a0, $s1, $zero
/* 5A9C344 8007FE14 D0D3000C */  jal        func_80034F40
/* 5A9C348 8007FE18 03000524 */   addiu     $a1, $zero, 0x3
.Llevel_23_8007FE1C:
/* 5A9C34C 8007FE1C 1000A0AF */  sw         $zero, 0x10($sp)
/* 5A9C350 8007FE20 21202002 */  addu       $a0, $s1, $zero
/* 5A9C354 8007FE24 0A000524 */  addiu      $a1, $zero, 0xA
/* 5A9C358 8007FE28 21300000 */  addu       $a2, $zero, $zero
/* 5A9C35C 8007FE2C 77D7000C */  jal        func_80035DDC
/* 5A9C360 8007FE30 21380000 */   addu      $a3, $zero, $zero
/* 5A9C364 8007FE34 AC010208 */  j          .Llevel_23_800806B0
/* 5A9C368 8007FE38 01001424 */   addiu     $s4, $zero, 0x1
.L8007FE3C_:
/* 5A9C36C 8007FE3C 21202002 */  addu       $a0, $s1, $zero
/* 5A9C370 8007FE40 32000624 */  addiu      $a2, $zero, 0x32
/* 5A9C374 8007FE44 21380000 */  addu       $a3, $zero, $zero
/* 5A9C378 8007FE48 46002592 */  lbu        $a1, 0x46($s1)
/* 5A9C37C 8007FE4C 00040224 */  addiu      $v0, $zero, 0x400
/* 5A9C380 8007FE50 1000A0AF */  sw         $zero, 0x10($sp)
/* 5A9C384 8007FE54 1400A2AF */  sw         $v0, 0x14($sp)
/* 5A9C388 8007FE58 8000A524 */  addiu      $a1, $a1, 0x80
/* 5A9C38C 8007FE5C B8D7000C */  jal        func_80035EE0
/* 5A9C390 8007FE60 FF00A530 */   andi      $a1, $a1, 0xFF
/* 5A9C394 8007FE64 0780023C */  lui        $v0, %hi(D_8006C770)
/* 5A9C398 8007FE68 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 5A9C39C 8007FE6C 00000000 */  nop
/* 5A9C3A0 8007FE70 0F024010 */  beqz       $v0, .Llevel_23_800806B0
/* 5A9C3A4 8007FE74 21202002 */   addu      $a0, $s1, $zero
/* 5A9C3A8 8007FE78 D0D3000C */  jal        func_80034F40
/* 5A9C3AC 8007FE7C 21280000 */   addu      $a1, $zero, $zero
/* 5A9C3B0 8007FE80 17000224 */  addiu      $v0, $zero, 0x17
/* 5A9C3B4 8007FE84 AC010208 */  j          .Llevel_23_800806B0
/* 5A9C3B8 8007FE88 480022A2 */   sb        $v0, 0x48($s1)
.L8007FE8C_:
/* 5A9C3BC 8007FE8C 21300000 */  addu       $a2, $zero, $zero
/* 5A9C3C0 8007FE90 0000638E */  lw         $v1, 0x0($s3)
/* 5A9C3C4 8007FE94 0C00248E */  lw         $a0, 0xC($s1)
/* 5A9C3C8 8007FE98 0400628E */  lw         $v0, 0x4($s3)
/* 5A9C3CC 8007FE9C 1000258E */  lw         $a1, 0x10($s1)
/* 5A9C3D0 8007FEA0 23206400 */  subu       $a0, $v1, $a0
/* 5A9C3D4 8007FEA4 203A010C */  jal        func_8004E880
/* 5A9C3D8 8007FEA8 23284500 */   subu      $a1, $v0, $a1
/* 5A9C3DC 8007FEAC 21202002 */  addu       $a0, $s1, $zero
/* 5A9C3E0 8007FEB0 21284000 */  addu       $a1, $v0, $zero
/* 5A9C3E4 8007FEB4 08000624 */  addiu      $a2, $zero, 0x8
/* 5A9C3E8 8007FEB8 14000724 */  addiu      $a3, $zero, 0x14
/* 5A9C3EC 8007FEBC 1000A0AF */  sw         $zero, 0x10($sp)
/* 5A9C3F0 8007FEC0 17D6000C */  jal        func_8003585C
/* 5A9C3F4 8007FEC4 1400A0AF */   sw        $zero, 0x14($sp)
/* 5A9C3F8 8007FEC8 06004010 */  beqz       $v0, .Llevel_23_8007FEE4
/* 5A9C3FC 8007FECC 21202002 */   addu      $a0, $s1, $zero
/* 5A9C400 8007FED0 1000A0AF */  sw         $zero, 0x10($sp)
/* 5A9C404 8007FED4 3C000524 */  addiu      $a1, $zero, 0x3C
/* 5A9C408 8007FED8 21300000 */  addu       $a2, $zero, $zero
/* 5A9C40C 8007FEDC 77D7000C */  jal        func_80035DDC
/* 5A9C410 8007FEE0 21380000 */   addu      $a3, $zero, $zero
.Llevel_23_8007FEE4:
/* 5A9C414 8007FEE4 0C003026 */  addiu      $s0, $s1, 0xC
/* 5A9C418 8007FEE8 21200002 */  addu       $a0, $s0, $zero
/* 5A9C41C 8007FEEC CD3C010C */  jal        func_8004F334
/* 5A9C420 8007FEF0 21286002 */   addu      $a1, $s3, $zero
/* 5A9C424 8007FEF4 00024228 */  slti       $v0, $v0, 0x200
/* 5A9C428 8007FEF8 0F004010 */  beqz       $v0, .Llevel_23_8007FF38
/* 5A9C42C 8007FEFC 00000000 */   nop
/* 5A9C430 8007FF00 9171010C */  jal        func_8005C644
/* 5A9C434 8007FF04 00000000 */   nop
/* 5A9C438 8007FF08 21202002 */  addu       $a0, $s1, $zero
/* 5A9C43C 8007FF0C 21280000 */  addu       $a1, $zero, $zero
/* 5A9C440 8007FF10 03004230 */  andi       $v0, $v0, 0x3
/* 5A9C444 8007FF14 40180200 */  sll        $v1, $v0, 1
/* 5A9C448 8007FF18 21186200 */  addu       $v1, $v1, $v0
/* 5A9C44C 8007FF1C C0180300 */  sll        $v1, $v1, 3
/* 5A9C450 8007FF20 21186200 */  addu       $v1, $v1, $v0
/* 5A9C454 8007FF24 40180300 */  sll        $v1, $v1, 1
/* 5A9C458 8007FF28 3C006324 */  addiu      $v1, $v1, 0x3C
/* 5A9C45C 8007FF2C 0C0063A6 */  sh         $v1, 0xC($s3)
/* 5A9C460 8007FF30 D0D3000C */  jal        func_80034F40
/* 5A9C464 8007FF34 480020A2 */   sb        $zero, 0x48($s1)
.Llevel_23_8007FF38:
/* 5A9C468 8007FF38 0C006286 */  lh         $v0, 0xC($s3)
/* 5A9C46C 8007FF3C 00000000 */  nop
/* 5A9C470 8007FF40 1A004014 */  bnez       $v0, .Llevel_23_8007FFAC
/* 5A9C474 8007FF44 01001424 */   addiu     $s4, $zero, 0x1
/* 5A9C478 8007FF48 0780053C */  lui        $a1, %hi(D_80070328)
/* 5A9C47C 8007FF4C 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 5A9C480 8007FF50 CD3C010C */  jal        func_8004F334
/* 5A9C484 8007FF54 21200002 */   addu      $a0, $s0, $zero
/* 5A9C488 8007FF58 0E006386 */  lh         $v1, 0xE($s3)
/* 5A9C48C 8007FF5C 00000000 */  nop
/* 5A9C490 8007FF60 2A104300 */  slt        $v0, $v0, $v1
/* 5A9C494 8007FF64 D2014010 */  beqz       $v0, .Llevel_23_800806B0
/* 5A9C498 8007FF68 00000000 */   nop
/* 5A9C49C 8007FF6C 0780023C */  lui        $v0, %hi(D_80070328 + 8)
/* 5A9C4A0 8007FF70 3003428C */  lw         $v0, %lo(D_80070328 + 8)($v0)
/* 5A9C4A4 8007FF74 1400238E */  lw         $v1, 0x14($s1)
/* 5A9C4A8 8007FF78 00000000 */  nop
/* 5A9C4AC 8007FF7C 23104300 */  subu       $v0, $v0, $v1
/* 5A9C4B0 8007FF80 02004104 */  bgez       $v0, .Llevel_23_8007FF8C
/* 5A9C4B4 8007FF84 00000000 */   nop
/* 5A9C4B8 8007FF88 23100200 */  negu       $v0, $v0
.Llevel_23_8007FF8C:
/* 5A9C4BC 8007FF8C 00104228 */  slti       $v0, $v0, 0x1000
/* 5A9C4C0 8007FF90 C7014010 */  beqz       $v0, .Llevel_23_800806B0
/* 5A9C4C4 8007FF94 21202002 */   addu      $a0, $s1, $zero
.Llevel_23_8007FF98:
/* 5A9C4C8 8007FF98 D0D3000C */  jal        func_80034F40
/* 5A9C4CC 8007FF9C 21280000 */   addu      $a1, $zero, $zero
/* 5A9C4D0 8007FFA0 14000224 */  addiu      $v0, $zero, 0x14
/* 5A9C4D4 8007FFA4 AC010208 */  j          .Llevel_23_800806B0
/* 5A9C4D8 8007FFA8 480022A2 */   sb        $v0, 0x48($s1)
.Llevel_23_8007FFAC:
/* 5A9C4DC 8007FFAC 0C006426 */  addiu      $a0, $s3, 0xC
/* 5A9C4E0 8007FFB0 69D6000C */  jal        func_800359A4
/* 5A9C4E4 8007FFB4 02000524 */   addiu     $a1, $zero, 0x2
/* 5A9C4E8 8007FFB8 AC010208 */  j          .Llevel_23_800806B0
/* 5A9C4EC 8007FFBC 00000000 */   nop
.L8007FFC0_:
/* 5A9C4F0 8007FFC0 21202002 */  addu       $a0, $s1, $zero
/* 5A9C4F4 8007FFC4 03000524 */  addiu      $a1, $zero, 0x3
/* 5A9C4F8 8007FFC8 03000624 */  addiu      $a2, $zero, 0x3
/* 5A9C4FC 8007FFCC CFD5000C */  jal        func_8003573C
/* 5A9C500 8007FFD0 21380000 */   addu      $a3, $zero, $zero
/* 5A9C504 8007FFD4 0780023C */  lui        $v0, %hi(D_8006C770)
/* 5A9C508 8007FFD8 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 5A9C50C 8007FFDC 00000000 */  nop
/* 5A9C510 8007FFE0 B3014010 */  beqz       $v0, .Llevel_23_800806B0
/* 5A9C514 8007FFE4 21202002 */   addu      $a0, $s1, $zero
/* 5A9C518 8007FFE8 05000524 */  addiu      $a1, $zero, 0x5
/* 5A9C51C 8007FFEC 05000224 */  addiu      $v0, $zero, 0x5
/* 5A9C520 8007FFF0 1A000208 */  j          .Llevel_23_80080068
/* 5A9C524 8007FFF4 480022A2 */   sb        $v0, 0x48($s1)
.L8007FFF8_:
/* 5A9C528 8007FFF8 21202002 */  addu       $a0, $s1, $zero
/* 5A9C52C 8007FFFC 06000524 */  addiu      $a1, $zero, 0x6
/* 5A9C530 80080000 06000624 */  addiu      $a2, $zero, 0x6
/* 5A9C534 80080004 CFD5000C */  jal        func_8003573C
/* 5A9C538 80080008 21380000 */   addu      $a3, $zero, $zero
/* 5A9C53C 8008000C 0780053C */  lui        $a1, %hi(D_80070328)
/* 5A9C540 80080010 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 5A9C544 80080014 CD3C010C */  jal        func_8004F334
/* 5A9C548 80080018 0C002426 */   addiu     $a0, $s1, 0xC
/* 5A9C54C 8008001C 0E006386 */  lh         $v1, 0xE($s3)
/* 5A9C550 80080020 21204000 */  addu       $a0, $v0, $zero
/* 5A9C554 80080024 2A186400 */  slt        $v1, $v1, $a0
/* 5A9C558 80080028 0C006014 */  bnez       $v1, .Llevel_23_8008005C
/* 5A9C55C 8008002C 00000000 */   nop
/* 5A9C560 80080030 0780023C */  lui        $v0, %hi(D_80070328 + 8)
/* 5A9C564 80080034 3003428C */  lw         $v0, %lo(D_80070328 + 8)($v0)
/* 5A9C568 80080038 1400238E */  lw         $v1, 0x14($s1)
/* 5A9C56C 8008003C 00000000 */  nop
/* 5A9C570 80080040 23104300 */  subu       $v0, $v0, $v1
/* 5A9C574 80080044 02004104 */  bgez       $v0, .Llevel_23_80080050
/* 5A9C578 80080048 00000000 */   nop
/* 5A9C57C 8008004C 23100200 */  negu       $v0, $v0
.Llevel_23_80080050:
/* 5A9C580 80080050 010C4228 */  slti       $v0, $v0, 0xC01
/* 5A9C584 80080054 09004014 */  bnez       $v0, .Llevel_23_8008007C
/* 5A9C588 80080058 00000000 */   nop
.Llevel_23_8008005C:
/* 5A9C58C 8008005C 21202002 */  addu       $a0, $s1, $zero
/* 5A9C590 80080060 21280000 */  addu       $a1, $zero, $zero
/* 5A9C594 80080064 480020A2 */  sb         $zero, 0x48($s1)
.Llevel_23_80080068:
/* 5A9C598 80080068 D0D3000C */  jal        func_80034F40
/* 5A9C59C 8008006C 00000000 */   nop
/* 5A9C5A0 80080070 A0000224 */  addiu      $v0, $zero, 0xA0
/* 5A9C5A4 80080074 AC010208 */  j          .Llevel_23_800806B0
/* 5A9C5A8 80080078 400022A2 */   sb        $v0, 0x40($s1)
.Llevel_23_8008007C:
/* 5A9C5AC 8008007C 10006286 */  lh         $v0, 0x10($s3)
/* 5A9C5B0 80080080 00000000 */  nop
/* 5A9C5B4 80080084 2A108200 */  slt        $v0, $a0, $v0
/* 5A9C5B8 80080088 89014010 */  beqz       $v0, .Llevel_23_800806B0
/* 5A9C5BC 8008008C 04000224 */   addiu     $v0, $zero, 0x4
/* 5A9C5C0 80080090 480022A2 */  sb         $v0, 0x48($s1)
/* 5A9C5C4 80080094 21202002 */  addu       $a0, $s1, $zero
/* 5A9C5C8 80080098 D0D3000C */  jal        func_80034F40
/* 5A9C5CC 8008009C 04000524 */   addiu     $a1, $zero, 0x4
/* 5A9C5D0 800800A0 AC010208 */  j          .Llevel_23_800806B0
/* 5A9C5D4 800800A4 00000000 */   nop
.L800800A8_:
/* 5A9C5D8 800800A8 0780023C */  lui        $v0, %hi(D_8006C770)
/* 5A9C5DC 800800AC 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 5A9C5E0 800800B0 00000000 */  nop
/* 5A9C5E4 800800B4 7E014010 */  beqz       $v0, .Llevel_23_800806B0
/* 5A9C5E8 800800B8 02000224 */   addiu     $v0, $zero, 0x2
/* 5A9C5EC 800800BC 480022A2 */  sb         $v0, 0x48($s1)
/* 5A9C5F0 800800C0 21202002 */  addu       $a0, $s1, $zero
/* 5A9C5F4 800800C4 D0D3000C */  jal        func_80034F40
/* 5A9C5F8 800800C8 02000524 */   addiu     $a1, $zero, 0x2
/* 5A9C5FC 800800CC AC010208 */  j          .Llevel_23_800806B0
/* 5A9C600 800800D0 00000000 */   nop
.L800800D4_:
/* 5A9C604 800800D4 21202002 */  addu       $a0, $s1, $zero
/* 5A9C608 800800D8 01000524 */  addiu      $a1, $zero, 0x1
/* 5A9C60C 800800DC 02000624 */  addiu      $a2, $zero, 0x2
/* 5A9C610 800800E0 CFD5000C */  jal        func_8003573C
/* 5A9C614 800800E4 21380000 */   addu      $a3, $zero, $zero
/* 5A9C618 800800E8 21202002 */  addu       $a0, $s1, $zero
/* 5A9C61C 800800EC 2C010524 */  addiu      $a1, $zero, 0x12C
/* 5A9C620 800800F0 21300000 */  addu       $a2, $zero, $zero
/* 5A9C624 800800F4 1400228E */  lw         $v0, 0x14($s1)
/* 5A9C628 800800F8 21380000 */  addu       $a3, $zero, $zero
/* 5A9C62C 800800FC 00024224 */  addiu      $v0, $v0, 0x200
/* 5A9C630 80080100 140022AE */  sw         $v0, 0x14($s1)
/* 5A9C634 80080104 00040224 */  addiu      $v0, $zero, 0x400
/* 5A9C638 80080108 77D7000C */  jal        func_80035DDC
/* 5A9C63C 8008010C 1000A2AF */   sw        $v0, 0x10($sp)
/* 5A9C640 80080110 08004014 */  bnez       $v0, .Llevel_23_80080134
/* 5A9C644 80080114 21202002 */   addu      $a0, $s1, $zero
/* 5A9C648 80080118 0780103C */  lui        $s0, %hi(D_80070328 + 0x50)
/* 5A9C64C 8008011C 78031026 */  addiu      $s0, $s0, %lo(D_80070328 + 0x50)
/* 5A9C650 80080120 0000038E */  lw         $v1, 0x0($s0)
/* 5A9C654 80080124 07000224 */  addiu      $v0, $zero, 0x7
/* 5A9C658 80080128 0A006214 */  bne        $v1, $v0, .Llevel_23_80080154
/* 5A9C65C 8008012C 3000A427 */   addiu     $a0, $sp, 0x30
/* 5A9C660 80080130 21202002 */  addu       $a0, $s1, $zero
.Llevel_23_80080134:
/* 5A9C664 80080134 D0D3000C */  jal        func_80034F40
/* 5A9C668 80080138 06000524 */   addiu     $a1, $zero, 0x6
/* 5A9C66C 8008013C 1400228E */  lw         $v0, 0x14($s1)
/* 5A9C670 80080140 16000324 */  addiu      $v1, $zero, 0x16
/* 5A9C674 80080144 480023A2 */  sb         $v1, 0x48($s1)
/* 5A9C678 80080148 00FE4224 */  addiu      $v0, $v0, -0x200
/* 5A9C67C 8008014C AC010208 */  j          .Llevel_23_800806B0
/* 5A9C680 80080150 140022AE */   sw        $v0, 0x14($s1)
.Llevel_23_80080154:
/* 5A9C684 80080154 01001424 */  addiu      $s4, $zero, 0x1
/* 5A9C688 80080158 14050524 */  addiu      $a1, $zero, 0x514
/* 5A9C68C 8008015C 01000624 */  addiu      $a2, $zero, 0x1
/* 5A9C690 80080160 1400228E */  lw         $v0, 0x14($s1)
/* 5A9C694 80080164 21380000 */  addu       $a3, $zero, $zero
/* 5A9C698 80080168 00FE4224 */  addiu      $v0, $v0, -0x200
/* 5A9C69C 8008016C 140022AE */  sw         $v0, 0x14($s1)
/* 5A9C6A0 80080170 0100023C */  lui        $v0, (0x10000 >> 16)
/* 5A9C6A4 80080174 1000A2AF */  sw         $v0, 0x10($sp)
/* 5A9C6A8 80080178 8C6E000C */  jal        func_8001BA30
/* 5A9C6AC 8008017C 1400B1AF */   sw        $s1, 0x14($sp)
/* 5A9C6B0 80080180 0000038E */  lw         $v1, 0x0($s0)
/* 5A9C6B4 80080184 09000224 */  addiu      $v0, $zero, 0x9
/* 5A9C6B8 80080188 3E006210 */  beq        $v1, $v0, .Llevel_23_80080284
/* 5A9C6BC 8008018C 04000224 */   addiu     $v0, $zero, 0x4
/* 5A9C6C0 80080190 3D006210 */  beq        $v1, $v0, .Llevel_23_80080288
/* 5A9C6C4 80080194 20002426 */   addiu     $a0, $s1, 0x20
/* 5A9C6C8 80080198 0780023C */  lui        $v0, %hi(D_80070328 + 8)
/* 5A9C6CC 8008019C 3003428C */  lw         $v0, %lo(D_80070328 + 8)($v0)
/* 5A9C6D0 800801A0 1400238E */  lw         $v1, 0x14($s1)
/* 5A9C6D4 800801A4 00000000 */  nop
/* 5A9C6D8 800801A8 23104300 */  subu       $v0, $v0, $v1
/* 5A9C6DC 800801AC 02004104 */  bgez       $v0, .Llevel_23_800801B8
/* 5A9C6E0 800801B0 00000000 */   nop
/* 5A9C6E4 800801B4 23100200 */  negu       $v0, $v0
.Llevel_23_800801B8:
/* 5A9C6E8 800801B8 00044228 */  slti       $v0, $v0, 0x400
/* 5A9C6EC 800801BC 31004010 */  beqz       $v0, .Llevel_23_80080284
/* 5A9C6F0 800801C0 B0FF0426 */   addiu     $a0, $s0, -0x50
/* 5A9C6F4 800801C4 CD3C010C */  jal        func_8004F334
/* 5A9C6F8 800801C8 0C002526 */   addiu     $a1, $s1, 0xC
/* 5A9C6FC 800801CC 14054228 */  slti       $v0, $v0, 0x514
/* 5A9C700 800801D0 2C004010 */  beqz       $v0, .Llevel_23_80080284
/* 5A9C704 800801D4 00000000 */   nop
/* 5A9C708 800801D8 21300000 */  addu       $a2, $zero, $zero
/* 5A9C70C 800801DC B0FF038E */  lw         $v1, -0x50($s0)
/* 5A9C710 800801E0 0C00248E */  lw         $a0, 0xC($s1)
/* 5A9C714 800801E4 0780023C */  lui        $v0, %hi(D_80070328 + 4)
/* 5A9C718 800801E8 2C03428C */  lw         $v0, %lo(D_80070328 + 4)($v0)
/* 5A9C71C 800801EC 1000258E */  lw         $a1, 0x10($s1)
/* 5A9C720 800801F0 23206400 */  subu       $a0, $v1, $a0
/* 5A9C724 800801F4 203A010C */  jal        func_8004E880
/* 5A9C728 800801F8 23284500 */   subu      $a1, $v0, $a1
/* 5A9C72C 800801FC 46002592 */  lbu        $a1, 0x46($s1)
/* 5A9C730 80080200 993C010C */  jal        func_8004F264
/* 5A9C734 80080204 21204000 */   addu      $a0, $v0, $zero
/* 5A9C738 80080208 08004228 */  slti       $v0, $v0, 0x8
/* 5A9C73C 8008020C 1D004010 */  beqz       $v0, .Llevel_23_80080284
/* 5A9C740 80080210 00000000 */   nop
/* 5A9C744 80080214 21300000 */  addu       $a2, $zero, $zero
/* 5A9C748 80080218 0C00238E */  lw         $v1, 0xC($s1)
/* 5A9C74C 8008021C 0780043C */  lui        $a0, %hi(D_8006E020)
/* 5A9C750 80080220 20E0848C */  lw         $a0, %lo(D_8006E020)($a0)
/* 5A9C754 80080224 1000228E */  lw         $v0, 0x10($s1)
/* 5A9C758 80080228 0780053C */  lui        $a1, %hi(D_8006E024)
/* 5A9C75C 8008022C 24E0A58C */  lw         $a1, %lo(D_8006E024)($a1)
/* 5A9C760 80080230 23206400 */  subu       $a0, $v1, $a0
/* 5A9C764 80080234 203A010C */  jal        func_8004E880
/* 5A9C768 80080238 23284500 */   subu      $a1, $v0, $a1
/* 5A9C76C 8008023C 0780043C */  lui        $a0, %hi(D_8006E040)
/* 5A9C770 80080240 40E08494 */  lhu        $a0, %lo(D_8006E040)($a0)
/* 5A9C774 80080244 21284000 */  addu       $a1, $v0, $zero
/* 5A9C778 80080248 00240400 */  sll        $a0, $a0, 16
/* 5A9C77C 8008024C 993C010C */  jal        func_8004F264
/* 5A9C780 80080250 03250400 */   sra       $a0, $a0, 20
/* 5A9C784 80080254 1C004228 */  slti       $v0, $v0, 0x1C
/* 5A9C788 80080258 0A004010 */  beqz       $v0, .Llevel_23_80080284
/* 5A9C78C 8008025C 21202002 */   addu      $a0, $s1, $zero
/* 5A9C790 80080260 0780013C */  lui        $at, %hi(D_80070328 + 0x24)
/* 5A9C794 80080264 4C0334AC */  sw         $s4, %lo(D_80070328 + 0x24)($at)
/* 5A9C798 80080268 46002292 */  lbu        $v0, 0x46($s1)
/* 5A9C79C 8008026C 0780013C */  lui        $at, %hi(D_80070328 + 0x298)
/* 5A9C7A0 80080270 C00522AC */  sw         $v0, %lo(D_80070328 + 0x298)($at)
/* 5A9C7A4 80080274 D0D3000C */  jal        func_80034F40
/* 5A9C7A8 80080278 06000524 */   addiu     $a1, $zero, 0x6
/* 5A9C7AC 8008027C FE000208 */  j          .Llevel_23_800803F8
/* 5A9C7B0 80080280 16000224 */   addiu     $v0, $zero, 0x16
.Llevel_23_80080284:
/* 5A9C7B4 80080284 20002426 */  addiu      $a0, $s1, 0x20
.Llevel_23_80080288:
/* 5A9C7B8 80080288 3000A527 */  addiu      $a1, $sp, 0x30
/* 5A9C7BC 8008028C 4000A627 */  addiu      $a2, $sp, 0x40
/* 5A9C7C0 80080290 2C010224 */  addiu      $v0, $zero, 0x12C
/* 5A9C7C4 80080294 3000A2AF */  sw         $v0, 0x30($sp)
/* 5A9C7C8 80080298 3400A0AF */  sw         $zero, 0x34($sp)
/* 5A9C7CC 8008029C 5B3B010C */  jal        func_8004ED6C
/* 5A9C7D0 800802A0 3800A0AF */   sw        $zero, 0x38($sp)
/* 5A9C7D4 800802A4 2000A427 */  addiu      $a0, $sp, 0x20
/* 5A9C7D8 800802A8 0780053C */  lui        $a1, %hi(D_80070328)
/* 5A9C7DC 800802AC 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 5A9C7E0 800802B0 723C010C */  jal        func_8004F1C8
/* 5A9C7E4 800802B4 0C002626 */   addiu     $a2, $s1, 0xC
/* 5A9C7E8 800802B8 2000A38F */  lw         $v1, 0x20($sp)
/* 5A9C7EC 800802BC 4000A28F */  lw         $v0, 0x40($sp)
/* 5A9C7F0 800802C0 00000000 */  nop
/* 5A9C7F4 800802C4 18006200 */  mult       $v1, $v0
/* 5A9C7F8 800802C8 2400A38F */  lw         $v1, 0x24($sp)
/* 5A9C7FC 800802CC 12200000 */  mflo       $a0
/* 5A9C800 800802D0 4400A28F */  lw         $v0, 0x44($sp)
/* 5A9C804 800802D4 00000000 */  nop
/* 5A9C808 800802D8 18006200 */  mult       $v1, $v0
/* 5A9C80C 800802DC 12180000 */  mflo       $v1
/* 5A9C810 800802E0 21108300 */  addu       $v0, $a0, $v1
/* 5A9C814 800802E4 F2004104 */  bgez       $v0, .Llevel_23_800806B0
/* 5A9C818 800802E8 78000224 */   addiu     $v0, $zero, 0x78
/* 5A9C81C 800802EC 0C0062A6 */  sh         $v0, 0xC($s3)
/* 5A9C820 800802F0 15000224 */  addiu      $v0, $zero, 0x15
/* 5A9C824 800802F4 AC010208 */  j          .Llevel_23_800806B0
/* 5A9C828 800802F8 480022A2 */   sb        $v0, 0x48($s1)
.L800802FC_:
/* 5A9C82C 800802FC 01001424 */  addiu      $s4, $zero, 0x1
/* 5A9C830 80080300 21300000 */  addu       $a2, $zero, $zero
/* 5A9C834 80080304 1400228E */  lw         $v0, 0x14($s1)
/* 5A9C838 80080308 0C00248E */  lw         $a0, 0xC($s1)
/* 5A9C83C 8008030C 1000258E */  lw         $a1, 0x10($s1)
/* 5A9C840 80080310 64004224 */  addiu      $v0, $v0, 0x64
/* 5A9C844 80080314 140022AE */  sw         $v0, 0x14($s1)
/* 5A9C848 80080318 0000638E */  lw         $v1, 0x0($s3)
/* 5A9C84C 8008031C 0400628E */  lw         $v0, 0x4($s3)
/* 5A9C850 80080320 23206400 */  subu       $a0, $v1, $a0
/* 5A9C854 80080324 203A010C */  jal        func_8004E880
/* 5A9C858 80080328 23284500 */   subu      $a1, $v0, $a1
/* 5A9C85C 8008032C 21202002 */  addu       $a0, $s1, $zero
/* 5A9C860 80080330 21284000 */  addu       $a1, $v0, $zero
/* 5A9C864 80080334 08000624 */  addiu      $a2, $zero, 0x8
/* 5A9C868 80080338 08000724 */  addiu      $a3, $zero, 0x8
/* 5A9C86C 8008033C 1000A0AF */  sw         $zero, 0x10($sp)
/* 5A9C870 80080340 17D6000C */  jal        func_8003585C
/* 5A9C874 80080344 1400A0AF */   sw        $zero, 0x14($sp)
/* 5A9C878 80080348 21202002 */  addu       $a0, $s1, $zero
/* 5A9C87C 8008034C 2C010524 */  addiu      $a1, $zero, 0x12C
/* 5A9C880 80080350 21300000 */  addu       $a2, $zero, $zero
/* 5A9C884 80080354 21380000 */  addu       $a3, $zero, $zero
/* 5A9C888 80080358 00040224 */  addiu      $v0, $zero, 0x400
/* 5A9C88C 8008035C 77D7000C */  jal        func_80035DDC
/* 5A9C890 80080360 1000A2AF */   sw        $v0, 0x10($sp)
/* 5A9C894 80080364 0C002426 */  addiu      $a0, $s1, 0xC
/* 5A9C898 80080368 CD3C010C */  jal        func_8004F334
/* 5A9C89C 8008036C 21286002 */   addu      $a1, $s3, $zero
/* 5A9C8A0 80080370 00084228 */  slti       $v0, $v0, 0x800
/* 5A9C8A4 80080374 06004014 */  bnez       $v0, .Llevel_23_80080390
/* 5A9C8A8 80080378 06000224 */   addiu     $v0, $zero, 0x6
/* 5A9C8AC 8008037C 0C006426 */  addiu      $a0, $s3, 0xC
/* 5A9C8B0 80080380 69D6000C */  jal        func_800359A4
/* 5A9C8B4 80080384 02000524 */   addiu     $a1, $zero, 0x2
/* 5A9C8B8 80080388 07004010 */  beqz       $v0, .Llevel_23_800803A8
/* 5A9C8BC 8008038C 06000224 */   addiu     $v0, $zero, 0x6
.Llevel_23_80080390:
/* 5A9C8C0 80080390 480022A2 */  sb         $v0, 0x48($s1)
/* 5A9C8C4 80080394 21202002 */  addu       $a0, $s1, $zero
/* 5A9C8C8 80080398 D0D3000C */  jal        func_80034F40
/* 5A9C8CC 8008039C 06000524 */   addiu     $a1, $zero, 0x6
/* 5A9C8D0 800803A0 AC010208 */  j          .Llevel_23_800806B0
/* 5A9C8D4 800803A4 00000000 */   nop
.Llevel_23_800803A8:
/* 5A9C8D8 800803A8 1400228E */  lw         $v0, 0x14($s1)
/* 5A9C8DC 800803AC 00000000 */  nop
/* 5A9C8E0 800803B0 9CFF4224 */  addiu      $v0, $v0, -0x64
/* 5A9C8E4 800803B4 AC010208 */  j          .Llevel_23_800806B0
/* 5A9C8E8 800803B8 140022AE */   sw        $v0, 0x14($s1)
.L800803BC_:
/* 5A9C8EC 800803BC 0780023C */  lui        $v0, %hi(D_8006C770)
/* 5A9C8F0 800803C0 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 5A9C8F4 800803C4 00000000 */  nop
/* 5A9C8F8 800803C8 B9004010 */  beqz       $v0, .Llevel_23_800806B0
/* 5A9C8FC 800803CC 0C002426 */   addiu     $a0, $s1, 0xC
/* 5A9C900 800803D0 CD3C010C */  jal        func_8004F334
/* 5A9C904 800803D4 21286002 */   addu      $a1, $s3, $zero
/* 5A9C908 800803D8 12006386 */  lh         $v1, 0x12($s3)
/* 5A9C90C 800803DC 00000000 */  nop
/* 5A9C910 800803E0 2A186200 */  slt        $v1, $v1, $v0
/* 5A9C914 800803E4 08006010 */  beqz       $v1, .Llevel_23_80080408
/* 5A9C918 800803E8 21202002 */   addu      $a0, $s1, $zero
/* 5A9C91C 800803EC D0D3000C */  jal        func_80034F40
/* 5A9C920 800803F0 21280000 */   addu      $a1, $zero, $zero
/* 5A9C924 800803F4 17000224 */  addiu      $v0, $zero, 0x17
.Llevel_23_800803F8:
/* 5A9C928 800803F8 480022A2 */  sb         $v0, 0x48($s1)
/* 5A9C92C 800803FC C8000224 */  addiu      $v0, $zero, 0xC8
/* 5A9C930 80080400 AC010208 */  j          .Llevel_23_800806B0
/* 5A9C934 80080404 0C0062A6 */   sh        $v0, 0xC($s3)
.Llevel_23_80080408:
/* 5A9C938 80080408 480020A2 */  sb         $zero, 0x48($s1)
.Llevel_23_8008040C:
/* 5A9C93C 8008040C 21202002 */  addu       $a0, $s1, $zero
/* 5A9C940 80080410 D0D3000C */  jal        func_80034F40
/* 5A9C944 80080414 21280000 */   addu      $a1, $zero, $zero
/* 5A9C948 80080418 AC010208 */  j          .Llevel_23_800806B0
/* 5A9C94C 8008041C 00000000 */   nop
.L80080420_:
/* 5A9C950 80080420 21300000 */  addu       $a2, $zero, $zero
/* 5A9C954 80080424 1400638E */  lw         $v1, 0x14($s3)
/* 5A9C958 80080428 0C00248E */  lw         $a0, 0xC($s1)
/* 5A9C95C 8008042C 1000258E */  lw         $a1, 0x10($s1)
/* 5A9C960 80080430 02006284 */  lh         $v0, 0x2($v1)
/* 5A9C964 80080434 0C00708C */  lw         $s0, 0xC($v1)
/* 5A9C968 80080438 00110200 */  sll        $v0, $v0, 4
/* 5A9C96C 8008043C 21800202 */  addu       $s0, $s0, $v0
/* 5A9C970 80080440 0000038E */  lw         $v1, 0x0($s0)
/* 5A9C974 80080444 0400028E */  lw         $v0, 0x4($s0)
/* 5A9C978 80080448 23206400 */  subu       $a0, $v1, $a0
/* 5A9C97C 8008044C 203A010C */  jal        func_8004E880
/* 5A9C980 80080450 23284500 */   subu      $a1, $v0, $a1
/* 5A9C984 80080454 21202002 */  addu       $a0, $s1, $zero
/* 5A9C988 80080458 21284000 */  addu       $a1, $v0, $zero
/* 5A9C98C 8008045C 04000624 */  addiu      $a2, $zero, 0x4
/* 5A9C990 80080460 04000724 */  addiu      $a3, $zero, 0x4
/* 5A9C994 80080464 1000A0AF */  sw         $zero, 0x10($sp)
/* 5A9C998 80080468 17D6000C */  jal        func_8003585C
/* 5A9C99C 8008046C 1400A0AF */   sw        $zero, 0x14($sp)
/* 5A9C9A0 80080470 21202002 */  addu       $a0, $s1, $zero
/* 5A9C9A4 80080474 3C000524 */  addiu      $a1, $zero, 0x3C
/* 5A9C9A8 80080478 21300000 */  addu       $a2, $zero, $zero
/* 5A9C9AC 8008047C 21380000 */  addu       $a3, $zero, $zero
/* 5A9C9B0 80080480 77D7000C */  jal        func_80035DDC
/* 5A9C9B4 80080484 1000A0AF */   sw        $zero, 0x10($sp)
/* 5A9C9B8 80080488 0C003226 */  addiu      $s2, $s1, 0xC
/* 5A9C9BC 8008048C 21204002 */  addu       $a0, $s2, $zero
/* 5A9C9C0 80080490 CD3C010C */  jal        func_8004F334
/* 5A9C9C4 80080494 21280002 */   addu      $a1, $s0, $zero
/* 5A9C9C8 80080498 00024228 */  slti       $v0, $v0, 0x200
/* 5A9C9CC 8008049C 07004010 */  beqz       $v0, .Llevel_23_800804BC
/* 5A9C9D0 800804A0 19000224 */   addiu     $v0, $zero, 0x19
/* 5A9C9D4 800804A4 480022A2 */  sb         $v0, 0x48($s1)
/* 5A9C9D8 800804A8 21202002 */  addu       $a0, $s1, $zero
/* 5A9C9DC 800804AC D0D3000C */  jal        func_80034F40
/* 5A9C9E0 800804B0 01000524 */   addiu     $a1, $zero, 0x1
/* 5A9C9E4 800804B4 AC010208 */  j          .Llevel_23_800806B0
/* 5A9C9E8 800804B8 00000000 */   nop
.Llevel_23_800804BC:
/* 5A9C9EC 800804BC 0780053C */  lui        $a1, %hi(D_80070328)
/* 5A9C9F0 800804C0 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 5A9C9F4 800804C4 CD3C010C */  jal        func_8004F334
/* 5A9C9F8 800804C8 21204002 */   addu      $a0, $s2, $zero
/* 5A9C9FC 800804CC 0E006386 */  lh         $v1, 0xE($s3)
/* 5A9CA00 800804D0 00000000 */  nop
/* 5A9CA04 800804D4 2A104300 */  slt        $v0, $v0, $v1
/* 5A9CA08 800804D8 75004010 */  beqz       $v0, .Llevel_23_800806B0
/* 5A9CA0C 800804DC 00000000 */   nop
/* 5A9CA10 800804E0 0780023C */  lui        $v0, %hi(D_80070328 + 8)
/* 5A9CA14 800804E4 3003428C */  lw         $v0, %lo(D_80070328 + 8)($v0)
/* 5A9CA18 800804E8 1400238E */  lw         $v1, 0x14($s1)
/* 5A9CA1C 800804EC 00000000 */  nop
/* 5A9CA20 800804F0 23104300 */  subu       $v0, $v0, $v1
/* 5A9CA24 800804F4 02004104 */  bgez       $v0, .Llevel_23_80080500
/* 5A9CA28 800804F8 00000000 */   nop
/* 5A9CA2C 800804FC 23100200 */  negu       $v0, $v0
.Llevel_23_80080500:
/* 5A9CA30 80080500 00104228 */  slti       $v0, $v0, 0x1000
/* 5A9CA34 80080504 6A004010 */  beqz       $v0, .Llevel_23_800806B0
/* 5A9CA38 80080508 21202002 */   addu      $a0, $s1, $zero
/* 5A9CA3C 8008050C 59010208 */  j          .Llevel_23_80080564
/* 5A9CA40 80080510 00000000 */   nop
.L80080514_:
/* 5A9CA44 80080514 0780053C */  lui        $a1, %hi(D_80070328)
/* 5A9CA48 80080518 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 5A9CA4C 8008051C CD3C010C */  jal        func_8004F334
/* 5A9CA50 80080520 0C002426 */   addiu     $a0, $s1, 0xC
/* 5A9CA54 80080524 0E006386 */  lh         $v1, 0xE($s3)
/* 5A9CA58 80080528 00000000 */  nop
/* 5A9CA5C 8008052C 2A104300 */  slt        $v0, $v0, $v1
/* 5A9CA60 80080530 13004010 */  beqz       $v0, .Llevel_23_80080580
/* 5A9CA64 80080534 00000000 */   nop
/* 5A9CA68 80080538 0780023C */  lui        $v0, %hi(D_80070328 + 8)
/* 5A9CA6C 8008053C 3003428C */  lw         $v0, %lo(D_80070328 + 8)($v0)
/* 5A9CA70 80080540 1400238E */  lw         $v1, 0x14($s1)
/* 5A9CA74 80080544 00000000 */  nop
/* 5A9CA78 80080548 23104300 */  subu       $v0, $v0, $v1
/* 5A9CA7C 8008054C 02004104 */  bgez       $v0, .Llevel_23_80080558
/* 5A9CA80 80080550 00000000 */   nop
/* 5A9CA84 80080554 23100200 */  negu       $v0, $v0
.Llevel_23_80080558:
/* 5A9CA88 80080558 00104228 */  slti       $v0, $v0, 0x1000
/* 5A9CA8C 8008055C 08004010 */  beqz       $v0, .Llevel_23_80080580
/* 5A9CA90 80080560 21202002 */   addu      $a0, $s1, $zero
.Llevel_23_80080564:
/* 5A9CA94 80080564 D0D3000C */  jal        func_80034F40
/* 5A9CA98 80080568 21280000 */   addu      $a1, $zero, $zero
/* 5A9CA9C 8008056C 14000224 */  addiu      $v0, $zero, 0x14
/* 5A9CAA0 80080570 480022A2 */  sb         $v0, 0x48($s1)
/* 5A9CAA4 80080574 02000224 */  addiu      $v0, $zero, 0x2
/* 5A9CAA8 80080578 AC010208 */  j          .Llevel_23_800806B0
/* 5A9CAAC 8008057C 490022A2 */   sb        $v0, 0x49($s1)
.Llevel_23_80080580:
/* 5A9CAB0 80080580 0780023C */  lui        $v0, %hi(D_8006C770)
/* 5A9CAB4 80080584 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 5A9CAB8 80080588 00000000 */  nop
/* 5A9CABC 8008058C 48004010 */  beqz       $v0, .Llevel_23_800806B0
/* 5A9CAC0 80080590 01000424 */   addiu     $a0, $zero, 0x1
/* 5A9CAC4 80080594 1400628E */  lw         $v0, 0x14($s3)
/* 5A9CAC8 80080598 00000000 */  nop
/* 5A9CACC 8008059C 00005084 */  lh         $s0, 0x0($v0)
/* 5A9CAD0 800805A0 DBD8000C */  jal        func_8003636C
/* 5A9CAD4 800805A4 FFFF0526 */   addiu     $a1, $s0, -0x1
/* 5A9CAD8 800805A8 1400668E */  lw         $a2, 0x14($s3)
/* 5A9CADC 800805AC 00000000 */  nop
/* 5A9CAE0 800805B0 0200C384 */  lh         $v1, 0x2($a2)
/* 5A9CAE4 800805B4 00000000 */  nop
/* 5A9CAE8 800805B8 21186200 */  addu       $v1, $v1, $v0
/* 5A9CAEC 800805BC 1A007000 */  div        $zero, $v1, $s0
/* 5A9CAF0 800805C0 02000016 */  bnez       $s0, .Llevel_23_800805CC
/* 5A9CAF4 800805C4 00000000 */   nop
/* 5A9CAF8 800805C8 0D000700 */  break      7
.Llevel_23_800805CC:
/* 5A9CAFC 800805CC FFFF0124 */  addiu      $at, $zero, -0x1
/* 5A9CB00 800805D0 04000116 */  bne        $s0, $at, .Llevel_23_800805E4
/* 5A9CB04 800805D4 0080013C */   lui       $at, (0x80000000 >> 16)
/* 5A9CB08 800805D8 02006114 */  bne        $v1, $at, .Llevel_23_800805E4
/* 5A9CB0C 800805DC 00000000 */   nop
/* 5A9CB10 800805E0 0D000600 */  break      6
.Llevel_23_800805E4:
/* 5A9CB14 800805E4 10100000 */  mfhi       $v0
/* 5A9CB18 800805E8 21202002 */  addu       $a0, $s1, $zero
/* 5A9CB1C 800805EC 21280000 */  addu       $a1, $zero, $zero
/* 5A9CB20 800805F0 D0D3000C */  jal        func_80034F40
/* 5A9CB24 800805F4 0200C2A4 */   sh        $v0, 0x2($a2)
/* 5A9CB28 800805F8 18000224 */  addiu      $v0, $zero, 0x18
/* 5A9CB2C 800805FC AC010208 */  j          .Llevel_23_800806B0
/* 5A9CB30 80080600 480022A2 */   sb        $v0, 0x48($s1)
.L80080604_:
/* 5A9CB34 80080604 21202002 */  addu       $a0, $s1, $zero
/* 5A9CB38 80080608 20006526 */  addiu      $a1, $s3, 0x20
/* 5A9CB3C 8008060C 08000224 */  addiu      $v0, $zero, 0x8
/* 5A9CB40 80080610 1000A2AF */  sw         $v0, 0x10($sp)
/* 5A9CB44 80080614 10000224 */  addiu      $v0, $zero, 0x10
/* 5A9CB48 80080618 1400A2AF */  sw         $v0, 0x14($sp)
/* 5A9CB4C 8008061C 00020224 */  addiu      $v0, $zero, 0x200
/* 5A9CB50 80080620 1800A2AF */  sw         $v0, 0x18($sp)
/* 5A9CB54 80080624 23000224 */  addiu      $v0, $zero, 0x23
/* 5A9CB58 80080628 1C00A2AF */  sw         $v0, 0x1C($sp)
/* 5A9CB5C 8008062C 1800668E */  lw         $a2, 0x18($s3)
/* 5A9CB60 80080630 0CD4000C */  jal        func_80035030
/* 5A9CB64 80080634 1C006726 */   addiu     $a3, $s3, 0x1C
/* 5A9CB68 80080638 03000324 */  addiu      $v1, $zero, 0x3
/* 5A9CB6C 8008063C 06004310 */  beq        $v0, $v1, .Llevel_23_80080658
/* 5A9CB70 80080640 00000000 */   nop
/* 5A9CB74 80080644 0780023C */  lui        $v0, %hi(D_8006C770)
/* 5A9CB78 80080648 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 5A9CB7C 8008064C 00000000 */  nop
/* 5A9CB80 80080650 17004010 */  beqz       $v0, .Llevel_23_800806B0
/* 5A9CB84 80080654 00000000 */   nop
.Llevel_23_80080658:
/* 5A9CB88 80080658 2400658E */  lw         $a1, 0x24($s3)
/* 5A9CB8C 8008065C F0EF000C */  jal        func_8003BFC0
/* 5A9CB90 80080660 21202002 */   addu      $a0, $s1, $zero
/* 5A9CB94 80080664 05004010 */  beqz       $v0, .Llevel_23_8008067C
/* 5A9CB98 80080668 FFFF0224 */   addiu     $v0, $zero, -0x1
/* 5A9CB9C 8008066C 2400648E */  lw         $a0, 0x24($s3)
/* 5A9CBA0 80080670 9CEF000C */  jal        func_8003BE70
/* 5A9CBA4 80080674 00000000 */   nop
/* 5A9CBA8 80080678 FFFF0224 */  addiu      $v0, $zero, -0x1
.Llevel_23_8008067C:
/* 5A9CBAC 8008067C 240062AE */  sw         $v0, 0x24($s3)
/* 5A9CBB0 80080680 21202002 */  addu       $a0, $s1, $zero
/* 5A9CBB4 80080684 4957010C */  jal        func_80055D24
/* 5A9CBB8 80080688 04000524 */   addiu     $a1, $zero, 0x4
/* 5A9CBBC 8008068C 80EE000C */  jal        func_8003BA00
/* 5A9CBC0 80080690 21202002 */   addu      $a0, $s1, $zero
/* 5A9CBC4 80080694 21202002 */  addu       $a0, $s1, $zero
/* 5A9CBC8 80080698 6EDA000C */  jal        func_800369B8
/* 5A9CBCC 8008069C 28000524 */   addiu     $a1, $zero, 0x28
/* 5A9CBD0 800806A0 C656010C */  jal        func_80055B18
/* 5A9CBD4 800806A4 21202002 */   addu      $a0, $s1, $zero
/* 5A9CBD8 800806A8 CD010208 */  j          .Llevel_23_80080734
/* 5A9CBDC 800806AC 00000000 */   nop
.Llevel_23_800806B0:
/* 5A9CBE0 800806B0 20008012 */  beqz       $s4, .Llevel_23_80080734
/* 5A9CBE4 800806B4 4000B027 */   addiu     $s0, $sp, 0x40
/* 5A9CBE8 800806B8 21200002 */  addu       $a0, $s0, $zero
/* 5A9CBEC 800806BC 5E3C010C */  jal        func_8004F178
/* 5A9CBF0 800806C0 0C002526 */   addiu     $a1, $s1, 0xC
/* 5A9CBF4 800806C4 21200002 */  addu       $a0, $s0, $zero
/* 5A9CBF8 800806C8 4800A28F */  lw         $v0, 0x48($sp)
/* 5A9CBFC 800806CC 88130524 */  addiu      $a1, $zero, 0x1388
/* 5A9CC00 800806D0 00084224 */  addiu      $v0, $v0, 0x800
/* 5A9CC04 800806D4 D668000C */  jal        func_8001A358
/* 5A9CC08 800806D8 4800A2AF */   sw        $v0, 0x48($sp)
/* 5A9CC0C 800806DC 0800648E */  lw         $a0, 0x8($s3)
/* 5A9CC10 800806E0 21184000 */  addu       $v1, $v0, $zero
/* 5A9CC14 800806E4 2A108300 */  slt        $v0, $a0, $v1
/* 5A9CC18 800806E8 07004010 */  beqz       $v0, .Llevel_23_80080708
/* 5A9CC1C 800806EC 00000000 */   nop
/* 5A9CC20 800806F0 1400228E */  lw         $v0, 0x14($s1)
/* 5A9CC24 800806F4 00000000 */  nop
/* 5A9CC28 800806F8 64004224 */  addiu      $v0, $v0, 0x64
/* 5A9CC2C 800806FC 140022AE */  sw         $v0, 0x14($s1)
/* 5A9CC30 80080700 CA010208 */  j          .Llevel_23_80080728
/* 5A9CC34 80080704 2A106200 */   slt       $v0, $v1, $v0
.Llevel_23_80080708:
/* 5A9CC38 80080708 1400228E */  lw         $v0, 0x14($s1)
/* 5A9CC3C 8008070C 00000000 */  nop
/* 5A9CC40 80080710 08004410 */  beq        $v0, $a0, .Llevel_23_80080734
/* 5A9CC44 80080714 9CFF4224 */   addiu     $v0, $v0, -0x64
/* 5A9CC48 80080718 140022AE */  sw         $v0, 0x14($s1)
/* 5A9CC4C 8008071C 0800638E */  lw         $v1, 0x8($s3)
/* 5A9CC50 80080720 00000000 */  nop
/* 5A9CC54 80080724 2A104300 */  slt        $v0, $v0, $v1
.Llevel_23_80080728:
/* 5A9CC58 80080728 02004010 */  beqz       $v0, .Llevel_23_80080734
/* 5A9CC5C 8008072C 00000000 */   nop
/* 5A9CC60 80080730 140023AE */  sw         $v1, 0x14($s1)
.Llevel_23_80080734:
/* 5A9CC64 80080734 6400BF8F */  lw         $ra, 0x64($sp)
/* 5A9CC68 80080738 6000B48F */  lw         $s4, 0x60($sp)
/* 5A9CC6C 8008073C 5C00B38F */  lw         $s3, 0x5C($sp)
/* 5A9CC70 80080740 5800B28F */  lw         $s2, 0x58($sp)
/* 5A9CC74 80080744 5400B18F */  lw         $s1, 0x54($sp)
/* 5A9CC78 80080748 5000B08F */  lw         $s0, 0x50($sp)
/* 5A9CC7C 8008074C 6800BD27 */  addiu      $sp, $sp, 0x68
/* 5A9CC80 80080750 0800E003 */  jr         $ra
/* 5A9CC84 80080754 00000000 */   nop
.size func_level_23_8007FAD4, . - func_level_23_8007FAD4
