.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_23_80074C08
/* 5A91138 80074C08 A08B0880 */ .word .L80088BA0_
/* 5A9113C 80074C0C A08B0880 */ .word .L80088BA0_
/* 5A91140 80074C10 A08B0880 */ .word .L80088BA0_
/* 5A91144 80074C14 B48C0880 */ .word .L80088CB4_
/* 5A91148 80074C18 B48C0880 */ .word .L80088CB4_
/* 5A9114C 80074C1C F48B0880 */ .word .L80088BF4_
/* 5A91150 80074C20 148C0880 */ .word .L80088C14_
.size jtbl_level_23_80074C08, . - jtbl_level_23_80074C08


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_23_80088A6C
/* 5AA4F9C 80088A6C E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 5AA4FA0 80088A70 1000B0AF */  sw         $s0, 0x10($sp)
/* 5AA4FA4 80088A74 21808000 */  addu       $s0, $a0, $zero
/* 5AA4FA8 80088A78 1800BFAF */  sw         $ra, 0x18($sp)
/* 5AA4FAC 80088A7C 1400B1AF */  sw         $s1, 0x14($sp)
/* 5AA4FB0 80088A80 49000292 */  lbu        $v0, 0x49($s0)
/* 5AA4FB4 80088A84 0000118E */  lw         $s1, 0x0($s0)
/* 5AA4FB8 80088A88 0F004014 */  bnez       $v0, .Llevel_23_80088AC8
/* 5AA4FBC 80088A8C 0080053C */   lui       $a1, (0x80000800 >> 16)
/* 5AA4FC0 80088A90 0008A534 */  ori        $a1, $a1, (0x80000800 & 0xFFFF)
/* 5AA4FC4 80088A94 01000224 */  addiu      $v0, $zero, 0x1
/* 5AA4FC8 80088A98 490002A2 */  sb         $v0, 0x49($s0)
/* 5AA4FCC 80088A9C 1400028E */  lw         $v0, 0x14($s0)
/* 5AA4FD0 80088AA0 1400038E */  lw         $v1, 0x14($s0)
/* 5AA4FD4 80088AA4 470000A2 */  sb         $zero, 0x47($s0)
/* 5AA4FD8 80088AA8 21104500 */  addu       $v0, $v0, $a1
/* 5AA4FDC 80088AAC 540002AE */  sw         $v0, 0x54($s0)
/* 5AA4FE0 80088AB0 040023AE */  sw         $v1, 0x4($s1)
/* 5AA4FE4 80088AB4 1400028E */  lw         $v0, 0x14($s0)
/* 5AA4FE8 80088AB8 04000524 */  addiu      $a1, $zero, 0x4
/* 5AA4FEC 80088ABC 2C014224 */  addiu      $v0, $v0, 0x12C
/* 5AA4FF0 80088AC0 4957010C */  jal        func_80055D24
/* 5AA4FF4 80088AC4 140002AE */   sw        $v0, 0x14($s0)
.Llevel_23_80088AC8:
/* 5AA4FF8 80088AC8 49000392 */  lbu        $v1, 0x49($s0)
/* 5AA4FFC 80088ACC 0A000224 */  addiu      $v0, $zero, 0xA
/* 5AA5000 80088AD0 02006214 */  bne        $v1, $v0, .Llevel_23_80088ADC
/* 5AA5004 80088AD4 00000000 */   nop
/* 5AA5008 80088AD8 180000AE */  sw         $zero, 0x18($s0)
.Llevel_23_80088ADC:
/* 5AA500C 80088ADC 48000492 */  lbu        $a0, 0x48($s0)
/* 5AA5010 80088AE0 03000224 */  addiu      $v0, $zero, 0x3
/* 5AA5014 80088AE4 FF008330 */  andi       $v1, $a0, 0xFF
/* 5AA5018 80088AE8 06006210 */  beq        $v1, $v0, .Llevel_23_80088B04
/* 5AA501C 80088AEC 00000000 */   nop
/* 5AA5020 80088AF0 04006010 */  beqz       $v1, .Llevel_23_80088B04
/* 5AA5024 80088AF4 FBFF8224 */   addiu     $v0, $a0, -0x5
/* 5AA5028 80088AF8 0200422C */  sltiu      $v0, $v0, 0x2
/* 5AA502C 80088AFC 1C004010 */  beqz       $v0, .Llevel_23_80088B70
/* 5AA5030 80088B00 00000000 */   nop
.Llevel_23_80088B04:
/* 5AA5034 80088B04 1800028E */  lw         $v0, 0x18($s0)
/* 5AA5038 80088B08 0200033C */  lui        $v1, (0x20000 >> 16)
/* 5AA503C 80088B0C 24104300 */  and        $v0, $v0, $v1
/* 5AA5040 80088B10 17004010 */  beqz       $v0, .Llevel_23_80088B70
/* 5AA5044 80088B14 21200002 */   addu      $a0, $s0, $zero
/* 5AA5048 80088B18 21280000 */  addu       $a1, $zero, $zero
/* 5AA504C 80088B1C AFEE000C */  jal        func_8003BABC
/* 5AA5050 80088B20 21300000 */   addu      $a2, $zero, $zero
/* 5AA5054 80088B24 05000224 */  addiu      $v0, $zero, 0x5
/* 5AA5058 80088B28 480002A2 */  sb         $v0, 0x48($s0)
/* 5AA505C 80088B2C 02002392 */  lbu        $v1, 0x2($s1)
/* 5AA5060 80088B30 01000224 */  addiu      $v0, $zero, 0x1
/* 5AA5064 80088B34 030022A2 */  sb         $v0, 0x3($s1)
/* 5AA5068 80088B38 8C000224 */  addiu      $v0, $zero, 0x8C
/* 5AA506C 80088B3C 03006010 */  beqz       $v1, .Llevel_23_80088B4C
/* 5AA5070 80088B40 000022A2 */   sb        $v0, 0x0($s1)
/* 5AA5074 80088B44 FFFF6224 */  addiu      $v0, $v1, -0x1
/* 5AA5078 80088B48 020022A2 */  sb         $v0, 0x2($s1)
.Llevel_23_80088B4C:
/* 5AA507C 80088B4C 21200002 */  addu       $a0, $s0, $zero
/* 5AA5080 80088B50 04000524 */  addiu      $a1, $zero, 0x4
/* 5AA5084 80088B54 02002392 */  lbu        $v1, 0x2($s1)
/* 5AA5088 80088B58 0400228E */  lw         $v0, 0x4($s1)
/* 5AA508C 80088B5C 801A0300 */  sll        $v1, $v1, 10
/* 5AA5090 80088B60 21104300 */  addu       $v0, $v0, $v1
/* 5AA5094 80088B64 2C014224 */  addiu      $v0, $v0, 0x12C
/* 5AA5098 80088B68 4957010C */  jal        func_80055D24
/* 5AA509C 80088B6C 140002AE */   sw        $v0, 0x14($s0)
.Llevel_23_80088B70:
/* 5AA50A0 80088B70 48000392 */  lbu        $v1, 0x48($s0)
/* 5AA50A4 80088B74 00000000 */  nop
/* 5AA50A8 80088B78 0700622C */  sltiu      $v0, $v1, 0x7
/* 5AA50AC 80088B7C 79004010 */  beqz       $v0, .Llevel_23_80088D64
/* 5AA50B0 80088B80 180000AE */   sw        $zero, 0x18($s0)
/* 5AA50B4 80088B84 80100300 */  sll        $v0, $v1, 2
/* 5AA50B8 80088B88 0780013C */  lui        $at, %hi(jtbl_level_23_80074C08)
/* 5AA50BC 80088B8C 21082200 */  addu       $at, $at, $v0
/* 5AA50C0 80088B90 084C228C */  lw         $v0, %lo(jtbl_level_23_80074C08)($at)
/* 5AA50C4 80088B94 00000000 */  nop
/* 5AA50C8 80088B98 08004000 */  jr         $v0
/* 5AA50CC 80088B9C 00000000 */   nop
.L80088BA0_:
/* 5AA50D0 80088BA0 00002292 */  lbu        $v0, 0x0($s1)
/* 5AA50D4 80088BA4 00000000 */  nop
/* 5AA50D8 80088BA8 6E004010 */  beqz       $v0, .Llevel_23_80088D64
/* 5AA50DC 80088BAC 00000000 */   nop
/* 5AA50E0 80088BB0 0780023C */  lui        $v0, %hi(D_8006C7C4)
/* 5AA50E4 80088BB4 C4C7428C */  lw         $v0, %lo(D_8006C7C4)($v0)
/* 5AA50E8 80088BB8 00000000 */  nop
/* 5AA50EC 80088BBC 69004010 */  beqz       $v0, .Llevel_23_80088D64
/* 5AA50F0 80088BC0 21202002 */   addu      $a0, $s1, $zero
/* 5AA50F4 80088BC4 69D6000C */  jal        func_800359A4
/* 5AA50F8 80088BC8 01000524 */   addiu     $a1, $zero, 0x1
/* 5AA50FC 80088BCC 65004010 */  beqz       $v0, .Llevel_23_80088D64
/* 5AA5100 80088BD0 21200002 */   addu      $a0, $s0, $zero
/* 5AA5104 80088BD4 01000524 */  addiu      $a1, $zero, 0x1
/* 5AA5108 80088BD8 AFEE000C */  jal        func_8003BABC
/* 5AA510C 80088BDC 21300000 */   addu      $a2, $zero, $zero
/* 5AA5110 80088BE0 06000224 */  addiu      $v0, $zero, 0x6
/* 5AA5114 80088BE4 480002A2 */  sb         $v0, 0x48($s0)
/* 5AA5118 80088BE8 80000224 */  addiu      $v0, $zero, 0x80
/* 5AA511C 80088BEC 59230208 */  j          .Llevel_23_80088D64
/* 5AA5120 80088BF0 000022A2 */   sb        $v0, 0x0($s1)
.L80088BF4_:
/* 5AA5124 80088BF4 21202002 */  addu       $a0, $s1, $zero
/* 5AA5128 80088BF8 69D6000C */  jal        func_800359A4
/* 5AA512C 80088BFC 01000524 */   addiu     $a1, $zero, 0x1
/* 5AA5130 80088C00 58004010 */  beqz       $v0, .Llevel_23_80088D64
/* 5AA5134 80088C04 FA000224 */   addiu     $v0, $zero, 0xFA
/* 5AA5138 80088C08 000022A2 */  sb         $v0, 0x0($s1)
/* 5AA513C 80088C0C 59230208 */  j          .Llevel_23_80088D64
/* 5AA5140 80088C10 480000A2 */   sb        $zero, 0x48($s0)
.L80088C14_:
/* 5AA5144 80088C14 03002382 */  lb         $v1, 0x3($s1)
/* 5AA5148 80088C18 21202002 */  addu       $a0, $s1, $zero
/* 5AA514C 80088C1C 00110300 */  sll        $v0, $v1, 4
/* 5AA5150 80088C20 23104300 */  subu       $v0, $v0, $v1
/* 5AA5154 80088C24 1400038E */  lw         $v1, 0x14($s0)
/* 5AA5158 80088C28 40100200 */  sll        $v0, $v0, 1
/* 5AA515C 80088C2C 21186200 */  addu       $v1, $v1, $v0
/* 5AA5160 80088C30 140003AE */  sw         $v1, 0x14($s0)
/* 5AA5164 80088C34 03002292 */  lbu        $v0, 0x3($s1)
/* 5AA5168 80088C38 01000524 */  addiu      $a1, $zero, 0x1
/* 5AA516C 80088C3C 23100200 */  negu       $v0, $v0
/* 5AA5170 80088C40 69D6000C */  jal        func_800359A4
/* 5AA5174 80088C44 030022A2 */   sb        $v0, 0x3($s1)
/* 5AA5178 80088C48 44004010 */  beqz       $v0, .Llevel_23_80088D5C
/* 5AA517C 80088C4C 21200002 */   addu      $a0, $s0, $zero
/* 5AA5180 80088C50 01002292 */  lbu        $v0, 0x1($s1)
/* 5AA5184 80088C54 02002392 */  lbu        $v1, 0x2($s1)
/* 5AA5188 80088C58 0780043C */  lui        $a0, %hi(D_80070328 + 0x13C)
/* 5AA518C 80088C5C 6404848C */  lw         $a0, %lo(D_80070328 + 0x13C)($a0)
/* 5AA5190 80088C60 00000000 */  nop
/* 5AA5194 80088C64 08009014 */  bne        $a0, $s0, .Llevel_23_80088C88
/* 5AA5198 80088C68 23184300 */   subu      $v1, $v0, $v1
/* 5AA519C 80088C6C 0010023C */  lui        $v0, (0x10000080 >> 16)
/* 5AA51A0 80088C70 80004234 */  ori        $v0, $v0, (0x10000080 & 0xFFFF)
/* 5AA51A4 80088C74 0780013C */  lui        $at, %hi(D_80070328 + 0x20C)
/* 5AA51A8 80088C78 340522AC */  sw         $v0, %lo(D_80070328 + 0x20C)($at)
/* 5AA51AC 80088C7C 49000224 */  addiu      $v0, $zero, 0x49
/* 5AA51B0 80088C80 0780013C */  lui        $at, %hi(D_80070328 + 0x23C)
/* 5AA51B4 80088C84 640522AC */  sw         $v0, %lo(D_80070328 + 0x23C)($at)
.Llevel_23_80088C88:
/* 5AA51B8 80088C88 02002292 */  lbu        $v0, 0x2($s1)
/* 5AA51BC 80088C8C 00000000 */  nop
/* 5AA51C0 80088C90 21104300 */  addu       $v0, $v0, $v1
/* 5AA51C4 80088C94 020022A2 */  sb         $v0, 0x2($s1)
/* 5AA51C8 80088C98 02006224 */  addiu      $v0, $v1, 0x2
/* 5AA51CC 80088C9C 480002A2 */  sb         $v0, 0x48($s0)
/* 5AA51D0 80088CA0 04000224 */  addiu      $v0, $zero, 0x4
/* 5AA51D4 80088CA4 000022A2 */  sb         $v0, 0x0($s1)
/* 5AA51D8 80088CA8 01000224 */  addiu      $v0, $zero, 0x1
/* 5AA51DC 80088CAC 56230208 */  j          .Llevel_23_80088D58
/* 5AA51E0 80088CB0 030022A2 */   sb        $v0, 0x3($s1)
.L80088CB4_:
/* 5AA51E4 80088CB4 48000392 */  lbu        $v1, 0x48($s0)
/* 5AA51E8 80088CB8 03000224 */  addiu      $v0, $zero, 0x3
/* 5AA51EC 80088CBC 04006214 */  bne        $v1, $v0, .Llevel_23_80088CD0
/* 5AA51F0 80088CC0 00000000 */   nop
/* 5AA51F4 80088CC4 1400028E */  lw         $v0, 0x14($s0)
/* 5AA51F8 80088CC8 37230208 */  j          .Llevel_23_80088CDC
/* 5AA51FC 80088CCC 00014224 */   addiu     $v0, $v0, 0x100
.Llevel_23_80088CD0:
/* 5AA5200 80088CD0 1400028E */  lw         $v0, 0x14($s0)
/* 5AA5204 80088CD4 00000000 */  nop
/* 5AA5208 80088CD8 B5014224 */  addiu      $v0, $v0, 0x1B5
.Llevel_23_80088CDC:
/* 5AA520C 80088CDC 140002AE */  sw         $v0, 0x14($s0)
/* 5AA5210 80088CE0 0780023C */  lui        $v0, %hi(D_80070328 + 0x13C)
/* 5AA5214 80088CE4 6404428C */  lw         $v0, %lo(D_80070328 + 0x13C)($v0)
/* 5AA5218 80088CE8 00000000 */  nop
/* 5AA521C 80088CEC 07005014 */  bne        $v0, $s0, .Llevel_23_80088D0C
/* 5AA5220 80088CF0 0010023C */   lui       $v0, (0x10000080 >> 16)
/* 5AA5224 80088CF4 80004234 */  ori        $v0, $v0, (0x10000080 & 0xFFFF)
/* 5AA5228 80088CF8 0780013C */  lui        $at, %hi(D_80070328 + 0x20C)
/* 5AA522C 80088CFC 340522AC */  sw         $v0, %lo(D_80070328 + 0x20C)($at)
/* 5AA5230 80088D00 49000224 */  addiu      $v0, $zero, 0x49
/* 5AA5234 80088D04 0780013C */  lui        $at, %hi(D_80070328 + 0x23C)
/* 5AA5238 80088D08 640522AC */  sw         $v0, %lo(D_80070328 + 0x23C)($at)
.Llevel_23_80088D0C:
/* 5AA523C 80088D0C 00002292 */  lbu        $v0, 0x0($s1)
/* 5AA5240 80088D10 00000000 */  nop
/* 5AA5244 80088D14 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 5AA5248 80088D18 000022A2 */  sb         $v0, 0x0($s1)
/* 5AA524C 80088D1C FF004230 */  andi       $v0, $v0, 0xFF
/* 5AA5250 80088D20 0E004014 */  bnez       $v0, .Llevel_23_80088D5C
/* 5AA5254 80088D24 21200002 */   addu      $a0, $s0, $zero
/* 5AA5258 80088D28 02002292 */  lbu        $v0, 0x2($s1)
/* 5AA525C 80088D2C 0400238E */  lw         $v1, 0x4($s1)
/* 5AA5260 80088D30 80120200 */  sll        $v0, $v0, 10
/* 5AA5264 80088D34 21206200 */  addu       $a0, $v1, $v0
/* 5AA5268 80088D38 01002392 */  lbu        $v1, 0x1($s1)
/* 5AA526C 80088D3C 01000224 */  addiu      $v0, $zero, 0x1
/* 5AA5270 80088D40 02006214 */  bne        $v1, $v0, .Llevel_23_80088D4C
/* 5AA5274 80088D44 00000000 */   nop
/* 5AA5278 80088D48 2C018424 */  addiu      $a0, $a0, 0x12C
.Llevel_23_80088D4C:
/* 5AA527C 80088D4C 140004AE */  sw         $a0, 0x14($s0)
/* 5AA5280 80088D50 480000A2 */  sb         $zero, 0x48($s0)
/* 5AA5284 80088D54 000020A2 */  sb         $zero, 0x0($s1)
.Llevel_23_80088D58:
/* 5AA5288 80088D58 21200002 */  addu       $a0, $s0, $zero
.Llevel_23_80088D5C:
/* 5AA528C 80088D5C 4957010C */  jal        func_80055D24
/* 5AA5290 80088D60 04000524 */   addiu     $a1, $zero, 0x4
.Llevel_23_80088D64:
/* 5AA5294 80088D64 49000392 */  lbu        $v1, 0x49($s0)
/* 5AA5298 80088D68 0A000224 */  addiu      $v0, $zero, 0xA
/* 5AA529C 80088D6C 03006214 */  bne        $v1, $v0, .Llevel_23_80088D7C
/* 5AA52A0 80088D70 00000000 */   nop
/* 5AA52A4 80088D74 65230208 */  j          .Llevel_23_80088D94
/* 5AA52A8 80088D78 180000AE */   sw        $zero, 0x18($s0)
.Llevel_23_80088D7C:
/* 5AA52AC 80088D7C 02002292 */  lbu        $v0, 0x2($s1)
/* 5AA52B0 80088D80 00000000 */  nop
/* 5AA52B4 80088D84 02004014 */  bnez       $v0, .Llevel_23_80088D90
/* 5AA52B8 80088D88 02000224 */   addiu     $v0, $zero, 0x2
/* 5AA52BC 80088D8C 03000224 */  addiu      $v0, $zero, 0x3
.Llevel_23_80088D90:
/* 5AA52C0 80088D90 490002A2 */  sb         $v0, 0x49($s0)
.Llevel_23_80088D94:
/* 5AA52C4 80088D94 1800BF8F */  lw         $ra, 0x18($sp)
/* 5AA52C8 80088D98 1400B18F */  lw         $s1, 0x14($sp)
/* 5AA52CC 80088D9C 1000B08F */  lw         $s0, 0x10($sp)
/* 5AA52D0 80088DA0 2000BD27 */  addiu      $sp, $sp, 0x20
/* 5AA52D4 80088DA4 0800E003 */  jr         $ra
/* 5AA52D8 80088DA8 00000000 */   nop
.size func_level_23_80088A6C, . - func_level_23_80088A6C
