.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_40_80074620
/* 7E5FB50 80074620 08E40780 */ .word .L8007E408_
/* 7E5FB54 80074624 0CE60780 */ .word .L8007E60C_
/* 7E5FB58 80074628 24E60780 */ .word .L8007E624_
/* 7E5FB5C 8007462C D4E60780 */ .word .L8007E6D4_
/* 7E5FB60 80074630 08E70780 */ .word .L8007E708_
/* 7E5FB64 80074634 B4E80780 */ .word .L8007E8B4_
/* 7E5FB68 80074638 44E90780 */ .word .L8007E944_
/* 7E5FB6C 8007463C 04EA0780 */ .word .L8007EA04_
.size jtbl_level_40_80074620, . - jtbl_level_40_80074620


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_40_8007E3C0
/* 7E698F0 8007E3C0 98FFBD27 */  addiu      $sp, $sp, -0x68
/* 7E698F4 8007E3C4 5800B2AF */  sw         $s2, 0x58($sp)
/* 7E698F8 8007E3C8 21908000 */  addu       $s2, $a0, $zero
/* 7E698FC 8007E3CC 6000BFAF */  sw         $ra, 0x60($sp)
/* 7E69900 8007E3D0 5C00B3AF */  sw         $s3, 0x5C($sp)
/* 7E69904 8007E3D4 5400B1AF */  sw         $s1, 0x54($sp)
/* 7E69908 8007E3D8 5000B0AF */  sw         $s0, 0x50($sp)
/* 7E6990C 8007E3DC 48004392 */  lbu        $v1, 0x48($s2)
/* 7E69910 8007E3E0 0000538E */  lw         $s3, 0x0($s2)
/* 7E69914 8007E3E4 0800622C */  sltiu      $v0, $v1, 0x8
/* 7E69918 8007E3E8 CA014010 */  beqz       $v0, .Llevel_40_8007EB14
/* 7E6991C 8007E3EC 80100300 */   sll       $v0, $v1, 2
/* 7E69920 8007E3F0 0780013C */  lui        $at, %hi(jtbl_level_40_80074620)
/* 7E69924 8007E3F4 21082200 */  addu       $at, $at, $v0
/* 7E69928 8007E3F8 2046228C */  lw         $v0, %lo(jtbl_level_40_80074620)($at)
/* 7E6992C 8007E3FC 00000000 */  nop
/* 7E69930 8007E400 08004000 */  jr         $v0
/* 7E69934 8007E404 00000000 */   nop
.L8007E408_:
/* 7E69938 8007E408 49004392 */  lbu        $v1, 0x49($s2)
/* 7E6993C 8007E40C 00000000 */  nop
/* 7E69940 8007E410 05006010 */  beqz       $v1, .Llevel_40_8007E428
/* 7E69944 8007E414 01000224 */   addiu     $v0, $zero, 0x1
/* 7E69948 8007E418 73006210 */  beq        $v1, $v0, .Llevel_40_8007E5E8
/* 7E6994C 8007E41C 21204002 */   addu      $a0, $s2, $zero
/* 7E69950 8007E420 C5FA0108 */  j          .Llevel_40_8007EB14
/* 7E69954 8007E424 00000000 */   nop
.Llevel_40_8007E428:
/* 7E69958 8007E428 0780023C */  lui        $v0, %hi(D_80071588)
/* 7E6995C 8007E42C 88154290 */  lbu        $v0, %lo(D_80071588)($v0)
/* 7E69960 8007E430 00000000 */  nop
/* 7E69964 8007E434 0B004014 */  bnez       $v0, .Llevel_40_8007E464
/* 7E69968 8007E438 14000224 */   addiu     $v0, $zero, 0x14
/* 7E6996C 8007E43C 0780033C */  lui        $v1, %hi(D_8006C5BC)
/* 7E69970 8007E440 BCC5638C */  lw         $v1, %lo(D_8006C5BC)($v1)
/* 7E69974 8007E444 00000000 */  nop
/* 7E69978 8007E448 0A006210 */  beq        $v1, $v0, .Llevel_40_8007E474
/* 7E6997C 8007E44C 00000000 */   nop
/* 7E69980 8007E450 0780023C */  lui        $v0, %hi(D_80071587)
/* 7E69984 8007E454 87154290 */  lbu        $v0, %lo(D_80071587)($v0)
/* 7E69988 8007E458 00000000 */  nop
/* 7E6998C 8007E45C 05004014 */  bnez       $v0, .Llevel_40_8007E474
/* 7E69990 8007E460 00000000 */   nop
.Llevel_40_8007E464:
/* 7E69994 8007E464 C656010C */  jal        func_80055B18
/* 7E69998 8007E468 21204002 */   addu      $a0, $s2, $zero
/* 7E6999C 8007E46C E2FA0108 */  j          .Llevel_40_8007EB88
/* 7E699A0 8007E470 00000000 */   nop
.Llevel_40_8007E474:
/* 7E699A4 8007E474 0780043C */  lui        $a0, %hi(D_8006C73C)
/* 7E699A8 8007E478 3CC7848C */  lw         $a0, %lo(D_8006C73C)($a0)
/* 7E699AC 8007E47C 00000000 */  nop
/* 7E699B0 8007E480 53008010 */  beqz       $a0, .Llevel_40_8007E5D0
/* 7E699B4 8007E484 00000000 */   nop
/* 7E699B8 8007E488 0780023C */  lui        $v0, %hi(D_8006C5BC)
/* 7E699BC 8007E48C BCC5428C */  lw         $v0, %lo(D_8006C5BC)($v0)
/* 7E699C0 8007E490 00000000 */  nop
/* 7E699C4 8007E494 4E004410 */  beq        $v0, $a0, .Llevel_40_8007E5D0
/* 7E699C8 8007E498 6666023C */   lui       $v0, (0x66666667 >> 16)
/* 7E699CC 8007E49C 67664234 */  ori        $v0, $v0, (0x66666667 & 0xFFFF)
/* 7E699D0 8007E4A0 18008200 */  mult       $a0, $v0
/* 7E699D4 8007E4A4 C3170400 */  sra        $v0, $a0, 31
/* 7E699D8 8007E4A8 10480000 */  mfhi       $t1
/* 7E699DC 8007E4AC 83180900 */  sra        $v1, $t1, 2
/* 7E699E0 8007E4B0 23186200 */  subu       $v1, $v1, $v0
/* 7E699E4 8007E4B4 80100300 */  sll        $v0, $v1, 2
/* 7E699E8 8007E4B8 21104300 */  addu       $v0, $v0, $v1
/* 7E699EC 8007E4BC 40100200 */  sll        $v0, $v0, 1
/* 7E699F0 8007E4C0 23188200 */  subu       $v1, $a0, $v0
/* 7E699F4 8007E4C4 05006010 */  beqz       $v1, .Llevel_40_8007E4DC
/* 7E699F8 8007E4C8 07000224 */   addiu     $v0, $zero, 0x7
/* 7E699FC 8007E4CC 40006214 */  bne        $v1, $v0, .Llevel_40_8007E5D0
/* 7E69A00 8007E4D0 3C008228 */   slti      $v0, $a0, 0x3C
/* 7E69A04 8007E4D4 3E004010 */  beqz       $v0, .Llevel_40_8007E5D0
/* 7E69A08 8007E4D8 00000000 */   nop
.Llevel_40_8007E4DC:
/* 7E69A0C 8007E4DC 36004386 */  lh         $v1, 0x36($s2)
/* 7E69A10 8007E4E0 0780023C */  lui        $v0, %hi(D_8006C528)
/* 7E69A14 8007E4E4 28C5428C */  lw         $v0, %lo(D_8006C528)($v0)
/* 7E69A18 8007E4E8 00000000 */  nop
/* 7E69A1C 8007E4EC 38006214 */  bne        $v1, $v0, .Llevel_40_8007E5D0
/* 7E69A20 8007E4F0 0C005126 */   addiu     $s1, $s2, 0xC
/* 7E69A24 8007E4F4 0780103C */  lui        $s0, %hi(D_8006E168)
/* 7E69A28 8007E4F8 68E11026 */  addiu      $s0, $s0, %lo(D_8006E168)
/* 7E69A2C 8007E4FC 1400428E */  lw         $v0, 0x14($s2)
/* 7E69A30 8007E500 21200002 */  addu       $a0, $s0, $zero
/* 7E69A34 8007E504 000C4224 */  addiu      $v0, $v0, 0xC00
/* 7E69A38 8007E508 140042AE */  sw         $v0, 0x14($s2)
/* 7E69A3C 8007E50C 0800628E */  lw         $v0, 0x8($s3)
/* 7E69A40 8007E510 00000000 */  nop
/* 7E69A44 8007E514 0C00458C */  lw         $a1, 0xC($v0)
/* 7E69A48 8007E518 BC4D000C */  jal        func_800136F0
/* 7E69A4C 8007E51C 21302002 */   addu      $a2, $s1, $zero
/* 7E69A50 8007E520 0110063C */  lui        $a2, (0x10018000 >> 16)
/* 7E69A54 8007E524 0080C634 */  ori        $a2, $a2, (0x10018000 & 0xFFFF)
/* 7E69A58 8007E528 0780023C */  lui        $v0, %hi(D_80070328 + 0x64)
/* 7E69A5C 8007E52C 8C034224 */  addiu      $v0, $v0, %lo(D_80070328 + 0x64)
/* 7E69A60 8007E530 C8014424 */  addiu      $a0, $v0, 0x1C8
/* 7E69A64 8007E534 0000038E */  lw         $v1, 0x0($s0)
/* 7E69A68 8007E538 0000428C */  lw         $v0, 0x0($v0)
/* 7E69A6C 8007E53C 21282002 */  addu       $a1, $s1, $zero
/* 7E69A70 8007E540 0780013C */  lui        $at, %hi(D_8006E174)
/* 7E69A74 8007E544 74E120AC */  sw         $zero, %lo(D_8006E174)($at)
/* 7E69A78 8007E548 0780013C */  lui        $at, %hi(D_8006E178)
/* 7E69A7C 8007E54C 78E120AC */  sw         $zero, %lo(D_8006E178)($at)
/* 7E69A80 8007E550 0780013C */  lui        $at, %hi(D_80070328 + 0x20C)
/* 7E69A84 8007E554 340526AC */  sw         $a2, %lo(D_80070328 + 0x20C)($at)
/* 7E69A88 8007E558 0780013C */  lui        $at, %hi(D_80070328 + 0x23C)
/* 7E69A8C 8007E55C 640520AC */  sw         $zero, %lo(D_80070328 + 0x23C)($at)
/* 7E69A90 8007E560 23186200 */  subu       $v1, $v1, $v0
/* 7E69A94 8007E564 5E3C010C */  jal        func_8004F178
/* 7E69A98 8007E568 000003AE */   sw        $v1, 0x0($s0)
/* 7E69A9C 8007E56C 0780023C */  lui        $v0, %hi(D_80070328 + 0x234)
/* 7E69AA0 8007E570 5C05428C */  lw         $v0, %lo(D_80070328 + 0x234)($v0)
/* 7E69AA4 8007E574 0780033C */  lui        $v1, %hi(D_80070328 + 0x44)
/* 7E69AA8 8007E578 6C03638C */  lw         $v1, %lo(D_80070328 + 0x44)($v1)
/* 7E69AAC 8007E57C 33014224 */  addiu      $v0, $v0, 0x133
/* 7E69AB0 8007E580 21104300 */  addu       $v0, $v0, $v1
/* 7E69AB4 8007E584 0780013C */  lui        $at, %hi(D_80070328 + 0x234)
/* 7E69AB8 8007E588 5C0522AC */  sw         $v0, %lo(D_80070328 + 0x234)($at)
/* 7E69ABC 8007E58C 44004292 */  lbu        $v0, 0x44($s2)
/* 7E69AC0 8007E590 0780013C */  lui        $at, %hi(D_80070328 + 0x228)
/* 7E69AC4 8007E594 500522A0 */  sb         $v0, %lo(D_80070328 + 0x228)($at)
/* 7E69AC8 8007E598 45004292 */  lbu        $v0, 0x45($s2)
/* 7E69ACC 8007E59C 0780013C */  lui        $at, %hi(D_80070328 + 0x229)
/* 7E69AD0 8007E5A0 510522A0 */  sb         $v0, %lo(D_80070328 + 0x229)($at)
/* 7E69AD4 8007E5A4 46004292 */  lbu        $v0, 0x46($s2)
/* 7E69AD8 8007E5A8 0780013C */  lui        $at, %hi(D_80070328 + 0x22A)
/* 7E69ADC 8007E5AC 520522A0 */  sb         $v0, %lo(D_80070328 + 0x22A)($at)
/* 7E69AE0 8007E5B0 EA4A000C */  jal        func_80012BA8
/* 7E69AE4 8007E5B4 21200002 */   addu      $a0, $s0, $zero
/* 7E69AE8 8007E5B8 14000426 */  addiu      $a0, $s0, 0x14
/* 7E69AEC 8007E5BC 5E3C010C */  jal        func_8004F178
/* 7E69AF0 8007E5C0 F0FE0526 */   addiu     $a1, $s0, -0x110
/* 7E69AF4 8007E5C4 07000224 */  addiu      $v0, $zero, 0x7
/* 7E69AF8 8007E5C8 C5FA0108 */  j          .Llevel_40_8007EB14
/* 7E69AFC 8007E5CC 480042A2 */   sb        $v0, 0x48($s2)
.Llevel_40_8007E5D0:
/* 7E69B00 8007E5D0 48004292 */  lbu        $v0, 0x48($s2)
/* 7E69B04 8007E5D4 00000000 */  nop
/* 7E69B08 8007E5D8 4E014014 */  bnez       $v0, .Llevel_40_8007EB14
/* 7E69B0C 8007E5DC 01000224 */   addiu     $v0, $zero, 0x1
/* 7E69B10 8007E5E0 7FFA0108 */  j          .Llevel_40_8007E9FC
/* 7E69B14 8007E5E4 00000000 */   nop
.Llevel_40_8007E5E8:
/* 7E69B18 8007E5E8 1400428E */  lw         $v0, 0x14($s2)
/* 7E69B1C 8007E5EC 02000524 */  addiu      $a1, $zero, 0x2
/* 7E69B20 8007E5F0 000F4224 */  addiu      $v0, $v0, 0xF00
/* 7E69B24 8007E5F4 4957010C */  jal        func_80055D24
/* 7E69B28 8007E5F8 140042AE */   sw        $v0, 0x14($s2)
/* 7E69B2C 8007E5FC 08000224 */  addiu      $v0, $zero, 0x8
/* 7E69B30 8007E600 0C0060AE */  sw         $zero, 0xC($s3)
/* 7E69B34 8007E604 C5FA0108 */  j          .Llevel_40_8007EB14
/* 7E69B38 8007E608 480042A2 */   sb        $v0, 0x48($s2)
.L8007E60C_:
/* 7E69B3C 8007E60C 0780023C */  lui        $v0, %hi(D_80070328 + 0x13C)
/* 7E69B40 8007E610 6404428C */  lw         $v0, %lo(D_80070328 + 0x13C)($v0)
/* 7E69B44 8007E614 00000000 */  nop
/* 7E69B48 8007E618 3E015214 */  bne        $v0, $s2, .Llevel_40_8007EB14
/* 7E69B4C 8007E61C 02000224 */   addiu     $v0, $zero, 0x2
/* 7E69B50 8007E620 480042A2 */  sb         $v0, 0x48($s2)
.L8007E624_:
/* 7E69B54 8007E624 0780023C */  lui        $v0, %hi(D_80070328 + 0x13C)
/* 7E69B58 8007E628 6404428C */  lw         $v0, %lo(D_80070328 + 0x13C)($v0)
/* 7E69B5C 8007E62C 00000000 */  nop
/* 7E69B60 8007E630 05005210 */  beq        $v0, $s2, .Llevel_40_8007E648
/* 7E69B64 8007E634 01000224 */   addiu     $v0, $zero, 0x1
/* 7E69B68 8007E638 0780013C */  lui        $at, %hi(D_8006E160)
/* 7E69B6C 8007E63C 60E120AC */  sw         $zero, %lo(D_8006E160)($at)
/* 7E69B70 8007E640 C5FA0108 */  j          .Llevel_40_8007EB14
/* 7E69B74 8007E644 480042A2 */   sb        $v0, 0x48($s2)
.Llevel_40_8007E648:
/* 7E69B78 8007E648 0C005126 */  addiu      $s1, $s2, 0xC
/* 7E69B7C 8007E64C 21202002 */  addu       $a0, $s1, $zero
/* 7E69B80 8007E650 46004592 */  lbu        $a1, 0x46($s2)
/* 7E69B84 8007E654 0780023C */  lui        $v0, %hi(unk_ovlheader_80074330)
/* 7E69B88 8007E658 3043428C */  lw         $v0, %lo(unk_ovlheader_80074330)($v0)
/* 7E69B8C 8007E65C 00000000 */  nop
/* 7E69B90 8007E660 09F84000 */  jalr       $v0
/* 7E69B94 8007E664 21300000 */   addu      $a2, $zero, $zero
/* 7E69B98 8007E668 07004010 */  beqz       $v0, .Llevel_40_8007E688
/* 7E69B9C 8007E66C 01000224 */   addiu     $v0, $zero, 0x1
/* 7E69BA0 8007E670 0780013C */  lui        $at, %hi(D_80070148)
/* 7E69BA4 8007E674 480122AC */  sw         $v0, %lo(D_80070148)($at)
/* 7E69BA8 8007E678 8F59010C */  jal        func_8005663C
/* 7E69BAC 8007E67C 00000000 */   nop
/* 7E69BB0 8007E680 03000224 */  addiu      $v0, $zero, 0x3
/* 7E69BB4 8007E684 480042A2 */  sb         $v0, 0x48($s2)
.Llevel_40_8007E688:
/* 7E69BB8 8007E688 0780103C */  lui        $s0, %hi(D_8006E17C)
/* 7E69BBC 8007E68C 7CE11026 */  addiu      $s0, $s0, %lo(D_8006E17C)
/* 7E69BC0 8007E690 21200002 */  addu       $a0, $s0, $zero
/* 7E69BC4 8007E694 5E3C010C */  jal        func_8004F178
/* 7E69BC8 8007E698 21282002 */   addu      $a1, $s1, $zero
/* 7E69BCC 8007E69C 0800628E */  lw         $v0, 0x8($s3)
/* 7E69BD0 8007E6A0 ECFF0426 */  addiu      $a0, $s0, -0x14
/* 7E69BD4 8007E6A4 0C00458C */  lw         $a1, 0xC($v0)
/* 7E69BD8 8007E6A8 BC4D000C */  jal        func_800136F0
/* 7E69BDC 8007E6AC 21302002 */   addu      $a2, $s1, $zero
/* 7E69BE0 8007E6B0 11000224 */  addiu      $v0, $zero, 0x11
/* 7E69BE4 8007E6B4 0780013C */  lui        $at, %hi(D_8006E174)
/* 7E69BE8 8007E6B8 74E120AC */  sw         $zero, %lo(D_8006E174)($at)
/* 7E69BEC 8007E6BC 0780013C */  lui        $at, %hi(D_8006E178)
/* 7E69BF0 8007E6C0 78E120AC */  sw         $zero, %lo(D_8006E178)($at)
/* 7E69BF4 8007E6C4 0780013C */  lui        $at, %hi(D_8006E160)
/* 7E69BF8 8007E6C8 60E122AC */  sw         $v0, %lo(D_8006E160)($at)
/* 7E69BFC 8007E6CC C5FA0108 */  j          .Llevel_40_8007EB14
/* 7E69C00 8007E6D0 00000000 */   nop
.L8007E6D4_:
/* 7E69C04 8007E6D4 0780023C */  lui        $v0, %hi(D_8007015A)
/* 7E69C08 8007E6D8 5A014284 */  lh         $v0, %lo(D_8007015A)($v0)
/* 7E69C0C 8007E6DC 0780013C */  lui        $at, %hi(D_8006E160)
/* 7E69C10 8007E6E0 60E120AC */  sw         $zero, %lo(D_8006E160)($at)
/* 7E69C14 8007E6E4 05004010 */  beqz       $v0, .Llevel_40_8007E6FC
/* 7E69C18 8007E6E8 78000224 */   addiu     $v0, $zero, 0x78
/* 7E69C1C 8007E6EC 0C0062AE */  sw         $v0, 0xC($s3)
/* 7E69C20 8007E6F0 04000224 */  addiu      $v0, $zero, 0x4
/* 7E69C24 8007E6F4 C5FA0108 */  j          .Llevel_40_8007EB14
/* 7E69C28 8007E6F8 480042A2 */   sb        $v0, 0x48($s2)
.Llevel_40_8007E6FC:
/* 7E69C2C 8007E6FC 05000224 */  addiu      $v0, $zero, 0x5
/* 7E69C30 8007E700 C5FA0108 */  j          .Llevel_40_8007EB14
/* 7E69C34 8007E704 480042A2 */   sb        $v0, 0x48($s2)
.L8007E708_:
/* 7E69C38 8007E708 21204002 */  addu       $a0, $s2, $zero
/* 7E69C3C 8007E70C D0D3000C */  jal        func_80034F40
/* 7E69C40 8007E710 01000524 */   addiu     $a1, $zero, 0x1
/* 7E69C44 8007E714 0010063C */  lui        $a2, (0x10008000 >> 16)
/* 7E69C48 8007E718 0080C634 */  ori        $a2, $a2, (0x10008000 & 0xFFFF)
/* 7E69C4C 8007E71C 0780033C */  lui        $v1, %hi(D_80070328 + 0x20C)
/* 7E69C50 8007E720 34056324 */  addiu      $v1, $v1, %lo(D_80070328 + 0x20C)
/* 7E69C54 8007E724 20006424 */  addiu      $a0, $v1, 0x20
/* 7E69C58 8007E728 0C005026 */  addiu      $s0, $s2, 0xC
/* 7E69C5C 8007E72C 1400428E */  lw         $v0, 0x14($s2)
/* 7E69C60 8007E730 00000000 */  nop
/* 7E69C64 8007E734 40004224 */  addiu      $v0, $v0, 0x40
/* 7E69C68 8007E738 140042AE */  sw         $v0, 0x14($s2)
/* 7E69C6C 8007E73C 000066AC */  sw         $a2, 0x0($v1)
/* 7E69C70 8007E740 0780013C */  lui        $at, %hi(D_80070328 + 0x23C)
/* 7E69C74 8007E744 640520AC */  sw         $zero, %lo(D_80070328 + 0x23C)($at)
/* 7E69C78 8007E748 5E3C010C */  jal        func_8004F178
/* 7E69C7C 8007E74C 21280002 */   addu      $a1, $s0, $zero
/* 7E69C80 8007E750 0780113C */  lui        $s1, %hi(D_8006E17C)
/* 7E69C84 8007E754 7CE13126 */  addiu      $s1, $s1, %lo(D_8006E17C)
/* 7E69C88 8007E758 21202002 */  addu       $a0, $s1, $zero
/* 7E69C8C 8007E75C 0780023C */  lui        $v0, %hi(D_80070328 + 0x234)
/* 7E69C90 8007E760 5C05428C */  lw         $v0, %lo(D_80070328 + 0x234)($v0)
/* 7E69C94 8007E764 0780033C */  lui        $v1, %hi(D_80070328 + 0x44)
/* 7E69C98 8007E768 6C03638C */  lw         $v1, %lo(D_80070328 + 0x44)($v1)
/* 7E69C9C 8007E76C 0780063C */  lui        $a2, %hi(D_80070328 + 0xC)
/* 7E69CA0 8007E770 3403C690 */  lbu        $a2, %lo(D_80070328 + 0xC)($a2)
/* 7E69CA4 8007E774 0780073C */  lui        $a3, %hi(D_80070328 + 0xD)
/* 7E69CA8 8007E778 3503E790 */  lbu        $a3, %lo(D_80070328 + 0xD)($a3)
/* 7E69CAC 8007E77C 0780083C */  lui        $t0, %hi(D_80070328 + 0xE)
/* 7E69CB0 8007E780 36030891 */  lbu        $t0, %lo(D_80070328 + 0xE)($t0)
/* 7E69CB4 8007E784 33014224 */  addiu      $v0, $v0, 0x133
/* 7E69CB8 8007E788 21104300 */  addu       $v0, $v0, $v1
/* 7E69CBC 8007E78C 0780013C */  lui        $at, %hi(D_80070328 + 0x234)
/* 7E69CC0 8007E790 5C0522AC */  sw         $v0, %lo(D_80070328 + 0x234)($at)
/* 7E69CC4 8007E794 0780013C */  lui        $at, %hi(D_80070328 + 0x228)
/* 7E69CC8 8007E798 500526A0 */  sb         $a2, %lo(D_80070328 + 0x228)($at)
/* 7E69CCC 8007E79C 0780013C */  lui        $at, %hi(D_80070328 + 0x229)
/* 7E69CD0 8007E7A0 510527A0 */  sb         $a3, %lo(D_80070328 + 0x229)($at)
/* 7E69CD4 8007E7A4 0780013C */  lui        $at, %hi(D_80070328 + 0x22A)
/* 7E69CD8 8007E7A8 520528A0 */  sb         $t0, %lo(D_80070328 + 0x22A)($at)
/* 7E69CDC 8007E7AC 5E3C010C */  jal        func_8004F178
/* 7E69CE0 8007E7B0 21280002 */   addu      $a1, $s0, $zero
/* 7E69CE4 8007E7B4 0800628E */  lw         $v0, 0x8($s3)
/* 7E69CE8 8007E7B8 ECFF2426 */  addiu      $a0, $s1, -0x14
/* 7E69CEC 8007E7BC 0C00458C */  lw         $a1, 0xC($v0)
/* 7E69CF0 8007E7C0 BC4D000C */  jal        func_800136F0
/* 7E69CF4 8007E7C4 21300002 */   addu      $a2, $s0, $zero
/* 7E69CF8 8007E7C8 0C006426 */  addiu      $a0, $s3, 0xC
/* 7E69CFC 8007E7CC 11000224 */  addiu      $v0, $zero, 0x11
/* 7E69D00 8007E7D0 0780013C */  lui        $at, %hi(D_8006E174)
/* 7E69D04 8007E7D4 74E120AC */  sw         $zero, %lo(D_8006E174)($at)
/* 7E69D08 8007E7D8 0780013C */  lui        $at, %hi(D_8006E178)
/* 7E69D0C 8007E7DC 78E120AC */  sw         $zero, %lo(D_8006E178)($at)
/* 7E69D10 8007E7E0 0780013C */  lui        $at, %hi(D_8006E160)
/* 7E69D14 8007E7E4 60E122AC */  sw         $v0, %lo(D_8006E160)($at)
/* 7E69D18 8007E7E8 69D6000C */  jal        func_800359A4
/* 7E69D1C 8007E7EC 04000524 */   addiu     $a1, $zero, 0x4
/* 7E69D20 8007E7F0 C6004010 */  beqz       $v0, .Llevel_40_8007EB0C
/* 7E69D24 8007E7F4 21204002 */   addu      $a0, $s2, $zero
/* 7E69D28 8007E7F8 0780023C */  lui        $v0, %hi(D_8006C598)
/* 7E69D2C 8007E7FC 98C5428C */  lw         $v0, %lo(D_8006C598)($v0)
/* 7E69D30 8007E800 00000000 */  nop
/* 7E69D34 8007E804 10004224 */  addiu      $v0, $v0, 0x10
/* 7E69D38 8007E808 0780013C */  lui        $at, %hi(D_8006C598)
/* 7E69D3C 8007E80C 98C522AC */  sw         $v0, %lo(D_8006C598)($at)
/* 7E69D40 8007E810 FF004228 */  slti       $v0, $v0, 0xFF
/* 7E69D44 8007E814 BD004014 */  bnez       $v0, .Llevel_40_8007EB0C
/* 7E69D48 8007E818 FF000224 */   addiu     $v0, $zero, 0xFF
/* 7E69D4C 8007E81C 0780043C */  lui        $a0, %hi(D_8007015A)
/* 7E69D50 8007E820 5A018424 */  addiu      $a0, $a0, %lo(D_8007015A)
/* 7E69D54 8007E824 00008384 */  lh         $v1, 0x0($a0)
/* 7E69D58 8007E828 0780013C */  lui        $at, %hi(D_8006C598)
/* 7E69D5C 8007E82C 98C522AC */  sw         $v0, %lo(D_8006C598)($at)
/* 7E69D60 8007E830 1E000224 */  addiu      $v0, $zero, 0x1E
/* 7E69D64 8007E834 0A006214 */  bne        $v1, $v0, .Llevel_40_8007E860
/* 7E69D68 8007E838 00000000 */   nop
/* 7E69D6C 8007E83C 0680023C */  lui        $v0, %hi(D_80066FCC + 0x1B)
/* 7E69D70 8007E840 E76F4290 */  lbu        $v0, %lo(D_80066FCC + 0x1B)($v0)
/* 7E69D74 8007E844 0780013C */  lui        $at, %hi(D_80070300)
/* 7E69D78 8007E848 21082200 */  addu       $at, $at, $v0
/* 7E69D7C 8007E84C 00032290 */  lbu        $v0, %lo(D_80070300)($at)
/* 7E69D80 8007E850 00000000 */  nop
/* 7E69D84 8007E854 02004014 */  bnez       $v0, .Llevel_40_8007E860
/* 7E69D88 8007E858 1B000224 */   addiu     $v0, $zero, 0x1B
/* 7E69D8C 8007E85C 000082A4 */  sh         $v0, 0x0($a0)
.Llevel_40_8007E860:
/* 7E69D90 8007E860 0780043C */  lui        $a0, %hi(D_8007015A)
/* 7E69D94 8007E864 5A018484 */  lh         $a0, %lo(D_8007015A)($a0)
/* 7E69D98 8007E868 1B000224 */  addiu      $v0, $zero, 0x1B
/* 7E69D9C 8007E86C 06008214 */  bne        $a0, $v0, .Llevel_40_8007E888
/* 7E69DA0 8007E870 00000000 */   nop
/* 7E69DA4 8007E874 0780023C */  lui        $v0, %hi(D_800715B4)
/* 7E69DA8 8007E878 B4154290 */  lbu        $v0, %lo(D_800715B4)($v0)
/* 7E69DAC 8007E87C 00000000 */  nop
/* 7E69DB0 8007E880 05004010 */  beqz       $v0, .Llevel_40_8007E898
/* 7E69DB4 8007E884 01000224 */   addiu     $v0, $zero, 0x1
.Llevel_40_8007E888:
/* 7E69DB8 8007E888 E553010C */  jal        func_80054F94
/* 7E69DBC 8007E88C 21284002 */   addu      $a1, $s2, $zero
/* 7E69DC0 8007E890 C3FA0108 */  j          .Llevel_40_8007EB0C
/* 7E69DC4 8007E894 21204002 */   addu      $a0, $s2, $zero
.Llevel_40_8007E898:
/* 7E69DC8 8007E898 0780013C */  lui        $at, %hi(D_800715B5)
/* 7E69DCC 8007E89C B51522A0 */  sb         $v0, %lo(D_800715B5)($at)
/* 7E69DD0 8007E8A0 06000424 */  addiu      $a0, $zero, 0x6
/* 7E69DD4 8007E8A4 2F61010C */  jal        func_800584BC
/* 7E69DD8 8007E8A8 41000524 */   addiu     $a1, $zero, 0x41
/* 7E69DDC 8007E8AC C3FA0108 */  j          .Llevel_40_8007EB0C
/* 7E69DE0 8007E8B0 21204002 */   addu      $a0, $s2, $zero
.L8007E8B4_:
/* 7E69DE4 8007E8B4 46004292 */  lbu        $v0, 0x46($s2)
/* 7E69DE8 8007E8B8 00000000 */  nop
/* 7E69DEC 8007E8BC 40100200 */  sll        $v0, $v0, 1
/* 7E69DF0 8007E8C0 0680013C */  lui        $at, %hi(D_80065920)
/* 7E69DF4 8007E8C4 21082200 */  addu       $at, $at, $v0
/* 7E69DF8 8007E8C8 20592284 */  lh         $v0, %lo(D_80065920)($at)
/* 7E69DFC 8007E8CC 1000A427 */  addiu      $a0, $sp, 0x10
/* 7E69E00 8007E8D0 1000A2AF */  sw         $v0, 0x10($sp)
/* 7E69E04 8007E8D4 46004292 */  lbu        $v0, 0x46($s2)
/* 7E69E08 8007E8D8 21288000 */  addu       $a1, $a0, $zero
/* 7E69E0C 8007E8DC 40100200 */  sll        $v0, $v0, 1
/* 7E69E10 8007E8E0 0680013C */  lui        $at, %hi(D_800658A0)
/* 7E69E14 8007E8E4 21082200 */  addu       $at, $at, $v0
/* 7E69E18 8007E8E8 A0582284 */  lh         $v0, %lo(D_800658A0)($at)
/* 7E69E1C 8007E8EC 0C004626 */  addiu      $a2, $s2, 0xC
/* 7E69E20 8007E8F0 1800A0AF */  sw         $zero, 0x18($sp)
/* 7E69E24 8007E8F4 653C010C */  jal        func_8004F194
/* 7E69E28 8007E8F8 1400A2AF */   sw        $v0, 0x14($sp)
/* 7E69E2C 8007E8FC 0780023C */  lui        $v0, %hi(unk_ovlheader_80074334)
/* 7E69E30 8007E900 3443428C */  lw         $v0, %lo(unk_ovlheader_80074334)($v0)
/* 7E69E34 8007E904 00000000 */  nop
/* 7E69E38 8007E908 09F84000 */  jalr       $v0
/* 7E69E3C 8007E90C 1000A427 */   addiu     $a0, $sp, 0x10
/* 7E69E40 8007E910 80004010 */  beqz       $v0, .Llevel_40_8007EB14
/* 7E69E44 8007E914 1000A427 */   addiu     $a0, $sp, 0x10
/* 7E69E48 8007E918 0780013C */  lui        $at, %hi(D_80070328 + 0x214)
/* 7E69E4C 8007E91C 3C0520AC */  sw         $zero, %lo(D_80070328 + 0x214)($at)
/* 7E69E50 8007E920 46004592 */  lbu        $a1, 0x46($s2)
/* 7E69E54 8007E924 0780023C */  lui        $v0, %hi(unk_ovlheader_80074330)
/* 7E69E58 8007E928 3043428C */  lw         $v0, %lo(unk_ovlheader_80074330)($v0)
/* 7E69E5C 8007E92C 00000000 */  nop
/* 7E69E60 8007E930 09F84000 */  jalr       $v0
/* 7E69E64 8007E934 21300000 */   addu      $a2, $zero, $zero
/* 7E69E68 8007E938 06000224 */  addiu      $v0, $zero, 0x6
/* 7E69E6C 8007E93C C5FA0108 */  j          .Llevel_40_8007EB14
/* 7E69E70 8007E940 480042A2 */   sb        $v0, 0x48($s2)
.L8007E944_:
/* 7E69E74 8007E944 46004292 */  lbu        $v0, 0x46($s2)
/* 7E69E78 8007E948 2000B027 */  addiu      $s0, $sp, 0x20
/* 7E69E7C 8007E94C 40100200 */  sll        $v0, $v0, 1
/* 7E69E80 8007E950 0680013C */  lui        $at, %hi(D_80065920)
/* 7E69E84 8007E954 21082200 */  addu       $at, $at, $v0
/* 7E69E88 8007E958 20592284 */  lh         $v0, %lo(D_80065920)($at)
/* 7E69E8C 8007E95C 21200002 */  addu       $a0, $s0, $zero
/* 7E69E90 8007E960 2000A2AF */  sw         $v0, 0x20($sp)
/* 7E69E94 8007E964 46004292 */  lbu        $v0, 0x46($s2)
/* 7E69E98 8007E968 21280002 */  addu       $a1, $s0, $zero
/* 7E69E9C 8007E96C 40100200 */  sll        $v0, $v0, 1
/* 7E69EA0 8007E970 0680013C */  lui        $at, %hi(D_800658A0)
/* 7E69EA4 8007E974 21082200 */  addu       $at, $at, $v0
/* 7E69EA8 8007E978 A0582284 */  lh         $v0, %lo(D_800658A0)($at)
/* 7E69EAC 8007E97C 0C004626 */  addiu      $a2, $s2, 0xC
/* 7E69EB0 8007E980 2800A0AF */  sw         $zero, 0x28($sp)
/* 7E69EB4 8007E984 653C010C */  jal        func_8004F194
/* 7E69EB8 8007E988 2400A2AF */   sw        $v0, 0x24($sp)
/* 7E69EBC 8007E98C 21200002 */  addu       $a0, $s0, $zero
/* 7E69EC0 8007E990 46004592 */  lbu        $a1, 0x46($s2)
/* 7E69EC4 8007E994 0780023C */  lui        $v0, %hi(unk_ovlheader_80074330)
/* 7E69EC8 8007E998 3043428C */  lw         $v0, %lo(unk_ovlheader_80074330)($v0)
/* 7E69ECC 8007E99C 00000000 */  nop
/* 7E69ED0 8007E9A0 09F84000 */  jalr       $v0
/* 7E69ED4 8007E9A4 21300000 */   addu      $a2, $zero, $zero
/* 7E69ED8 8007E9A8 5A004010 */  beqz       $v0, .Llevel_40_8007EB14
/* 7E69EDC 8007E9AC 3000B027 */   addiu     $s0, $sp, 0x30
/* 7E69EE0 8007E9B0 0780053C */  lui        $a1, %hi(D_80070328)
/* 7E69EE4 8007E9B4 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 7E69EE8 8007E9B8 5E3C010C */  jal        func_8004F178
/* 7E69EEC 8007E9BC 21200002 */   addu      $a0, $s0, $zero
/* 7E69EF0 8007E9C0 0780043C */  lui        $a0, %hi(D_8006D088)
/* 7E69EF4 8007E9C4 88D08424 */  addiu      $a0, $a0, %lo(D_8006D088)
/* 7E69EF8 8007E9C8 21280002 */  addu       $a1, $s0, $zero
/* 7E69EFC 8007E9CC 3800A28F */  lw         $v0, 0x38($sp)
/* 7E69F00 8007E9D0 0780033C */  lui        $v1, %hi(D_80070328 + 0x44)
/* 7E69F04 8007E9D4 6C03638C */  lw         $v1, %lo(D_80070328 + 0x44)($v1)
/* 7E69F08 8007E9D8 0780063C */  lui        $a2, %hi(D_80070328 + 0xE)
/* 7E69F0C 8007E9DC 3603C690 */  lbu        $a2, %lo(D_80070328 + 0xE)($a2)
/* 7E69F10 8007E9E0 23104300 */  subu       $v0, $v0, $v1
/* 7E69F14 8007E9E4 8DED000C */  jal        func_8003B634
/* 7E69F18 8007E9E8 3800A2AF */   sw        $v0, 0x38($sp)
/* 7E69F1C 8007E9EC 21204002 */  addu       $a0, $s2, $zero
/* 7E69F20 8007E9F0 D0D3000C */  jal        func_80034F40
/* 7E69F24 8007E9F4 21280000 */   addu      $a1, $zero, $zero
/* 7E69F28 8007E9F8 01000224 */  addiu      $v0, $zero, 0x1
.Llevel_40_8007E9FC:
/* 7E69F2C 8007E9FC C5FA0108 */  j          .Llevel_40_8007EB14
/* 7E69F30 8007EA00 480042A2 */   sb        $v0, 0x48($s2)
.L8007EA04_:
/* 7E69F34 8007EA04 21204002 */  addu       $a0, $s2, $zero
/* 7E69F38 8007EA08 D0D3000C */  jal        func_80034F40
/* 7E69F3C 8007EA0C 01000524 */   addiu     $a1, $zero, 0x1
/* 7E69F40 8007EA10 0110033C */  lui        $v1, (0x10018000 >> 16)
/* 7E69F44 8007EA14 00806334 */  ori        $v1, $v1, (0x10018000 & 0xFFFF)
/* 7E69F48 8007EA18 0780103C */  lui        $s0, %hi(D_80070328 + 0x20C)
/* 7E69F4C 8007EA1C 34051026 */  addiu      $s0, $s0, %lo(D_80070328 + 0x20C)
/* 7E69F50 8007EA20 20000426 */  addiu      $a0, $s0, 0x20
/* 7E69F54 8007EA24 0C005126 */  addiu      $s1, $s2, 0xC
/* 7E69F58 8007EA28 1400428E */  lw         $v0, 0x14($s2)
/* 7E69F5C 8007EA2C 00000000 */  nop
/* 7E69F60 8007EA30 C0FF4224 */  addiu      $v0, $v0, -0x40
/* 7E69F64 8007EA34 140042AE */  sw         $v0, 0x14($s2)
/* 7E69F68 8007EA38 000003AE */  sw         $v1, 0x0($s0)
/* 7E69F6C 8007EA3C 0780013C */  lui        $at, %hi(D_80070328 + 0x23C)
/* 7E69F70 8007EA40 640520AC */  sw         $zero, %lo(D_80070328 + 0x23C)($at)
/* 7E69F74 8007EA44 5E3C010C */  jal        func_8004F178
/* 7E69F78 8007EA48 21282002 */   addu      $a1, $s1, $zero
/* 7E69F7C 8007EA4C 0780023C */  lui        $v0, %hi(D_80070328 + 0x234)
/* 7E69F80 8007EA50 5C05428C */  lw         $v0, %lo(D_80070328 + 0x234)($v0)
/* 7E69F84 8007EA54 0780033C */  lui        $v1, %hi(D_80070328 + 0x44)
/* 7E69F88 8007EA58 6C03638C */  lw         $v1, %lo(D_80070328 + 0x44)($v1)
/* 7E69F8C 8007EA5C 33014224 */  addiu      $v0, $v0, 0x133
/* 7E69F90 8007EA60 21104300 */  addu       $v0, $v0, $v1
/* 7E69F94 8007EA64 0780013C */  lui        $at, %hi(D_80070328 + 0x234)
/* 7E69F98 8007EA68 5C0522AC */  sw         $v0, %lo(D_80070328 + 0x234)($at)
/* 7E69F9C 8007EA6C 44004292 */  lbu        $v0, 0x44($s2)
/* 7E69FA0 8007EA70 0780013C */  lui        $at, %hi(D_80070328 + 0x228)
/* 7E69FA4 8007EA74 500522A0 */  sb         $v0, %lo(D_80070328 + 0x228)($at)
/* 7E69FA8 8007EA78 45004292 */  lbu        $v0, 0x45($s2)
/* 7E69FAC 8007EA7C 0780013C */  lui        $at, %hi(D_80070328 + 0x229)
/* 7E69FB0 8007EA80 510522A0 */  sb         $v0, %lo(D_80070328 + 0x229)($at)
/* 7E69FB4 8007EA84 46004292 */  lbu        $v0, 0x46($s2)
/* 7E69FB8 8007EA88 0780013C */  lui        $at, %hi(D_80070328 + 0x22A)
/* 7E69FBC 8007EA8C 520522A0 */  sb         $v0, %lo(D_80070328 + 0x22A)($at)
/* 7E69FC0 8007EA90 0800628E */  lw         $v0, 0x8($s3)
/* 7E69FC4 8007EA94 00000000 */  nop
/* 7E69FC8 8007EA98 0C00448C */  lw         $a0, 0xC($v0)
/* 7E69FCC 8007EA9C B94E000C */  jal        func_80013AE4
/* 7E69FD0 8007EAA0 F4FD0526 */   addiu     $a1, $s0, -0x20C
/* 7E69FD4 8007EAA4 4000B027 */  addiu      $s0, $sp, 0x40
/* 7E69FD8 8007EAA8 21200002 */  addu       $a0, $s0, $zero
/* 7E69FDC 8007EAAC 5E3C010C */  jal        func_8004F178
/* 7E69FE0 8007EAB0 21282002 */   addu      $a1, $s1, $zero
/* 7E69FE4 8007EAB4 1400428E */  lw         $v0, 0x14($s2)
/* 7E69FE8 8007EAB8 21200002 */  addu       $a0, $s0, $zero
/* 7E69FEC 8007EABC 00044224 */  addiu      $v0, $v0, 0x400
/* 7E69FF0 8007EAC0 140042AE */  sw         $v0, 0x14($s2)
/* 7E69FF4 8007EAC4 4800A28F */  lw         $v0, 0x48($sp)
/* 7E69FF8 8007EAC8 00020524 */  addiu      $a1, $zero, 0x200
/* 7E69FFC 8007EACC 00024224 */  addiu      $v0, $v0, 0x200
/* 7E6A000 8007EAD0 D668000C */  jal        func_8001A358
/* 7E6A004 8007EAD4 4800A2AF */   sw        $v0, 0x48($sp)
/* 7E6A008 8007EAD8 07004010 */  beqz       $v0, .Llevel_40_8007EAF8
/* 7E6A00C 8007EADC 4800A2AF */   sw        $v0, 0x48($sp)
/* 7E6A010 8007EAE0 21200000 */  addu       $a0, $zero, $zero
/* 7E6A014 8007EAE4 DF4E000C */  jal        func_80013B7C
/* 7E6A018 8007EAE8 140042AE */   sw        $v0, 0x14($s2)
/* 7E6A01C 8007EAEC 05000224 */  addiu      $v0, $zero, 0x5
/* 7E6A020 8007EAF0 C2FA0108 */  j          .Llevel_40_8007EB08
/* 7E6A024 8007EAF4 480042A2 */   sb        $v0, 0x48($s2)
.Llevel_40_8007EAF8:
/* 7E6A028 8007EAF8 1400428E */  lw         $v0, 0x14($s2)
/* 7E6A02C 8007EAFC 00000000 */  nop
/* 7E6A030 8007EB00 00FC4224 */  addiu      $v0, $v0, -0x400
/* 7E6A034 8007EB04 140042AE */  sw         $v0, 0x14($s2)
.Llevel_40_8007EB08:
/* 7E6A038 8007EB08 21204002 */  addu       $a0, $s2, $zero
.Llevel_40_8007EB0C:
/* 7E6A03C 8007EB0C 4957010C */  jal        func_80055D24
/* 7E6A040 8007EB10 02000524 */   addiu     $a1, $zero, 0x2
.Llevel_40_8007EB14:
/* 7E6A044 8007EB14 0780023C */  lui        $v0, %hi(D_8006E344)
/* 7E6A048 8007EB18 44E3428C */  lw         $v0, %lo(D_8006E344)($v0)
/* 7E6A04C 8007EB1C 00000000 */  nop
/* 7E6A050 8007EB20 0F004014 */  bnez       $v0, .Llevel_40_8007EB60
/* 7E6A054 8007EB24 01000224 */   addiu     $v0, $zero, 0x1
/* 7E6A058 8007EB28 3D004392 */  lbu        $v1, 0x3D($s2)
/* 7E6A05C 8007EB2C 00000000 */  nop
/* 7E6A060 8007EB30 0B006214 */  bne        $v1, $v0, .Llevel_40_8007EB60
/* 7E6A064 8007EB34 00000000 */   nop
/* 7E6A068 8007EB38 1000658E */  lw         $a1, 0x10($s3)
/* 7E6A06C 8007EB3C F0EF000C */  jal        func_8003BFC0
/* 7E6A070 8007EB40 21204002 */   addu      $a0, $s2, $zero
/* 7E6A074 8007EB44 10004014 */  bnez       $v0, .Llevel_40_8007EB88
/* 7E6A078 8007EB48 21204002 */   addu      $a0, $s2, $zero
/* 7E6A07C 8007EB4C 21280000 */  addu       $a1, $zero, $zero
/* 7E6A080 8007EB50 AFEE000C */  jal        func_8003BABC
/* 7E6A084 8007EB54 04000624 */   addiu     $a2, $zero, 0x4
/* 7E6A088 8007EB58 E2FA0108 */  j          .Llevel_40_8007EB88
/* 7E6A08C 8007EB5C 100062AE */   sw        $v0, 0x10($s3)
.Llevel_40_8007EB60:
/* 7E6A090 8007EB60 1000658E */  lw         $a1, 0x10($s3)
/* 7E6A094 8007EB64 F0EF000C */  jal        func_8003BFC0
/* 7E6A098 8007EB68 21204002 */   addu      $a0, $s2, $zero
/* 7E6A09C 8007EB6C 05004010 */  beqz       $v0, .Llevel_40_8007EB84
/* 7E6A0A0 8007EB70 FFFF0224 */   addiu     $v0, $zero, -0x1
/* 7E6A0A4 8007EB74 1000648E */  lw         $a0, 0x10($s3)
/* 7E6A0A8 8007EB78 9CEF000C */  jal        func_8003BE70
/* 7E6A0AC 8007EB7C 00000000 */   nop
/* 7E6A0B0 8007EB80 FFFF0224 */  addiu      $v0, $zero, -0x1
.Llevel_40_8007EB84:
/* 7E6A0B4 8007EB84 100062AE */  sw         $v0, 0x10($s3)
.Llevel_40_8007EB88:
/* 7E6A0B8 8007EB88 6000BF8F */  lw         $ra, 0x60($sp)
/* 7E6A0BC 8007EB8C 5C00B38F */  lw         $s3, 0x5C($sp)
/* 7E6A0C0 8007EB90 5800B28F */  lw         $s2, 0x58($sp)
/* 7E6A0C4 8007EB94 5400B18F */  lw         $s1, 0x54($sp)
/* 7E6A0C8 8007EB98 5000B08F */  lw         $s0, 0x50($sp)
/* 7E6A0CC 8007EB9C 6800BD27 */  addiu      $sp, $sp, 0x68
/* 7E6A0D0 8007EBA0 0800E003 */  jr         $ra
/* 7E6A0D4 8007EBA4 00000000 */   nop
.size func_level_40_8007E3C0, . - func_level_40_8007E3C0
