.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_32_80075A04
/* 6DDCF34 80075A04 20C30980 */ .word .L8009C320_
/* 6DDCF38 80075A08 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF3C 80075A0C ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF40 80075A10 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF44 80075A14 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF48 80075A18 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF4C 80075A1C ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF50 80075A20 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF54 80075A24 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF58 80075A28 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF5C 80075A2C 54C40980 */ .word .L8009C454_
/* 6DDCF60 80075A30 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF64 80075A34 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF68 80075A38 30C50980 */ .word .L8009C530_
/* 6DDCF6C 80075A3C ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF70 80075A40 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF74 80075A44 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF78 80075A48 2CC60980 */ .word .L8009C62C_
/* 6DDCF7C 80075A4C ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF80 80075A50 48C70980 */ .word .L8009C748_
/* 6DDCF84 80075A54 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF88 80075A58 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF8C 80075A5C ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF90 80075A60 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF94 80075A64 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF98 80075A68 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCF9C 80075A6C ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCFA0 80075A70 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCFA4 80075A74 70C80980 */ .word .L8009C870_
/* 6DDCFA8 80075A78 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCFAC 80075A7C ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCFB0 80075A80 ACCB0980 */ .word .Llevel_32_8009CBAC
/* 6DDCFB4 80075A84 10CA0980 */ .word .L8009CA10_
/* 6DDCFB8 80075A88 00000000 */ .word 0x00000000
.size jtbl_level_32_80075A04, . - jtbl_level_32_80075A04


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_32_8009C2B8
/* 6E037E8 8009C2B8 0780023C */  lui        $v0, %hi(D_8006E130)
/* 6E037EC 8009C2BC 30E1428C */  lw         $v0, %lo(D_8006E130)($v0)
/* 6E037F0 8009C2C0 D8FFBD27 */  addiu      $sp, $sp, -0x28
/* 6E037F4 8009C2C4 2000BFAF */  sw         $ra, 0x20($sp)
/* 6E037F8 8009C2C8 1C00B3AF */  sw         $s3, 0x1C($sp)
/* 6E037FC 8009C2CC 1800B2AF */  sw         $s2, 0x18($sp)
/* 6E03800 8009C2D0 1400B1AF */  sw         $s1, 0x14($sp)
/* 6E03804 8009C2D4 02004224 */  addiu      $v0, $v0, 0x2
/* 6E03808 8009C2D8 83900200 */  sra        $s2, $v0, 2
/* 6E0380C 8009C2DC 0500422A */  slti       $v0, $s2, 0x5
/* 6E03810 8009C2E0 02004014 */  bnez       $v0, .Llevel_32_8009C2EC
/* 6E03814 8009C2E4 1000B0AF */   sw        $s0, 0x10($sp)
/* 6E03818 8009C2E8 04001224 */  addiu      $s2, $zero, 0x4
.Llevel_32_8009C2EC:
/* 6E0381C 8009C2EC 0780023C */  lui        $v0, %hi(D_8006E044)
/* 6E03820 8009C2F0 44E0428C */  lw         $v0, %lo(D_8006E044)($v0)
/* 6E03824 8009C2F4 00000000 */  nop
/* 6E03828 8009C2F8 FCFF4324 */  addiu      $v1, $v0, -0x4
/* 6E0382C 8009C2FC 2100622C */  sltiu      $v0, $v1, 0x21
/* 6E03830 8009C300 2A024010 */  beqz       $v0, .Llevel_32_8009CBAC
/* 6E03834 8009C304 80100300 */   sll       $v0, $v1, 2
/* 6E03838 8009C308 0780013C */  lui        $at, %hi(jtbl_level_32_80075A04)
/* 6E0383C 8009C30C 21082200 */  addu       $at, $at, $v0
/* 6E03840 8009C310 045A228C */  lw         $v0, %lo(jtbl_level_32_80075A04)($at)
/* 6E03844 8009C314 00000000 */  nop
/* 6E03848 8009C318 08004000 */  jr         $v0
/* 6E0384C 8009C31C 00000000 */   nop
.L8009C320_:
/* 6E03850 8009C320 0780043C */  lui        $a0, %hi(D_8006E12C)
/* 6E03854 8009C324 2CE18424 */  addiu      $a0, $a0, %lo(D_8006E12C)
/* 6E03858 8009C328 0000828C */  lw         $v0, 0x0($a0)
/* 6E0385C 8009C32C 00000000 */  nop
/* 6E03860 8009C330 34004014 */  bnez       $v0, .Llevel_32_8009C404
/* 6E03864 8009C334 07000224 */   addiu     $v0, $zero, 0x7
/* 6E03868 8009C338 0780033C */  lui        $v1, %hi(D_8006E344)
/* 6E0386C 8009C33C 44E3638C */  lw         $v1, %lo(D_8006E344)($v1)
/* 6E03870 8009C340 00000000 */  nop
/* 6E03874 8009C344 2F006210 */  beq        $v1, $v0, .Llevel_32_8009C404
/* 6E03878 8009C348 00000000 */   nop
/* 6E0387C 8009C34C 0780063C */  lui        $a2, %hi(D_8006E064)
/* 6E03880 8009C350 64E0C68C */  lw         $a2, %lo(D_8006E064)($a2)
/* 6E03884 8009C354 0780053C */  lui        $a1, %hi(D_80069008)
/* 6E03888 8009C358 0890A524 */  addiu      $a1, $a1, %lo(D_80069008)
/* 6E0388C 8009C35C 694D000C */  jal        func_800135A4
/* 6E03890 8009C360 5CFF8424 */   addiu     $a0, $a0, -0xA4
/* 6E03894 8009C364 0780023C */  lui        $v0, %hi(D_80070328 + 0x60)
/* 6E03898 8009C368 8803428C */  lw         $v0, %lo(D_80070328 + 0x60)($v0)
/* 6E0389C 8009C36C 0780033C */  lui        $v1, %hi(D_8006E078)
/* 6E038A0 8009C370 78E0638C */  lw         $v1, %lo(D_8006E078)($v1)
/* 6E038A4 8009C374 23100200 */  negu       $v0, $v0
/* 6E038A8 8009C378 23184300 */  subu       $v1, $v0, $v1
/* 6E038AC 8009C37C 83180300 */  sra        $v1, $v1, 2
/* 6E038B0 8009C380 0780013C */  lui        $at, %hi(D_8006E08C)
/* 6E038B4 8009C384 8CE022AC */  sw         $v0, %lo(D_8006E08C)($at)
/* 6E038B8 8009C388 C1006228 */  slti       $v0, $v1, 0xC1
/* 6E038BC 8009C38C 03004014 */  bnez       $v0, .Llevel_32_8009C39C
/* 6E038C0 8009C390 40FF6228 */   slti      $v0, $v1, -0xC0
/* 6E038C4 8009C394 C0000324 */  addiu      $v1, $zero, 0xC0
/* 6E038C8 8009C398 40FF6228 */  slti       $v0, $v1, -0xC0
.Llevel_32_8009C39C:
/* 6E038CC 8009C39C 02004010 */  beqz       $v0, .Llevel_32_8009C3A8
/* 6E038D0 8009C3A0 00000000 */   nop
/* 6E038D4 8009C3A4 40FF0324 */  addiu      $v1, $zero, -0xC0
.Llevel_32_8009C3A8:
/* 6E038D8 8009C3A8 02006104 */  bgez       $v1, .Llevel_32_8009C3B4
/* 6E038DC 8009C3AC 21106000 */   addu      $v0, $v1, $zero
/* 6E038E0 8009C3B0 23100200 */  negu       $v0, $v0
.Llevel_32_8009C3B4:
/* 6E038E4 8009C3B4 09004228 */  slti       $v0, $v0, 0x9
/* 6E038E8 8009C3B8 05004014 */  bnez       $v0, .Llevel_32_8009C3D0
/* 6E038EC 8009C3BC 00000000 */   nop
/* 6E038F0 8009C3C0 0780013C */  lui        $at, %hi(D_8006E094)
/* 6E038F4 8009C3C4 94E023AC */  sw         $v1, %lo(D_8006E094)($at)
/* 6E038F8 8009C3C8 F6700208 */  j          .Llevel_32_8009C3D8
/* 6E038FC 8009C3CC 00000000 */   nop
.Llevel_32_8009C3D0:
/* 6E03900 8009C3D0 0780013C */  lui        $at, %hi(D_8006E094)
/* 6E03904 8009C3D4 94E020AC */  sw         $zero, %lo(D_8006E094)($at)
.Llevel_32_8009C3D8:
/* 6E03908 8009C3D8 0780023C */  lui        $v0, %hi(D_80070328 + 0x5C)
/* 6E0390C 8009C3DC 8403428C */  lw         $v0, %lo(D_80070328 + 0x5C)($v0)
/* 6E03910 8009C3E0 00000000 */  nop
/* 6E03914 8009C3E4 23100200 */  negu       $v0, $v0
/* 6E03918 8009C3E8 83100200 */  sra        $v0, $v0, 2
/* 6E0391C 8009C3EC 0780013C */  lui        $at, %hi(D_8006E098)
/* 6E03920 8009C3F0 98E022AC */  sw         $v0, %lo(D_8006E098)($at)
/* 6E03924 8009C3F4 464E000C */  jal        func_80013918
/* 6E03928 8009C3F8 80010424 */   addiu     $a0, $zero, 0x180
/* 6E0392C 8009C3FC 694E000C */  jal        func_800139A4
/* 6E03930 8009C400 00000000 */   nop
.Llevel_32_8009C404:
/* 6E03934 8009C404 B850000C */  jal        func_800142E0
/* 6E03938 8009C408 00000000 */   nop
/* 6E0393C 8009C40C 0780103C */  lui        $s0, %hi(D_8006E0D8)
/* 6E03940 8009C410 D8E01026 */  addiu      $s0, $s0, %lo(D_8006E0D8)
/* 6E03944 8009C414 21200002 */  addu       $a0, $s0, $zero
/* 6E03948 8009C418 80101200 */  sll        $v0, $s2, 2
/* 6E0394C 8009C41C 21105200 */  addu       $v0, $v0, $s2
/* 6E03950 8009C420 80880200 */  sll        $s1, $v0, 2
/* 6E03954 8009C424 0780053C */  lui        $a1, %hi(D_8006929C)
/* 6E03958 8009C428 9C92A524 */  addiu      $a1, $a1, %lo(D_8006929C)
/* 6E0395C 8009C42C 21282502 */  addu       $a1, $s1, $a1
/* 6E03960 8009C430 694D000C */  jal        func_800135A4
/* 6E03964 8009C434 21300000 */   addu      $a2, $zero, $zero
/* 6E03968 8009C438 0000028E */  lw         $v0, 0x0($s0)
/* 6E0396C 8009C43C 00000000 */  nop
/* 6E03970 8009C440 80004228 */  slti       $v0, $v0, 0x80
/* 6E03974 8009C444 50014010 */  beqz       $v0, .Llevel_32_8009C988
/* 6E03978 8009C448 80000224 */   addiu     $v0, $zero, 0x80
/* 6E0397C 8009C44C 62720208 */  j          .Llevel_32_8009C988
/* 6E03980 8009C450 000002AE */   sw        $v0, 0x0($s0)
.L8009C454_:
/* 6E03984 8009C454 0780043C */  lui        $a0, %hi(D_8006E12C)
/* 6E03988 8009C458 2CE18424 */  addiu      $a0, $a0, %lo(D_8006E12C)
/* 6E0398C 8009C45C 0000828C */  lw         $v0, 0x0($a0)
/* 6E03990 8009C460 00000000 */  nop
/* 6E03994 8009C464 13004014 */  bnez       $v0, .Llevel_32_8009C4B4
/* 6E03998 8009C468 2F000224 */   addiu     $v0, $zero, 0x2F
/* 6E0399C 8009C46C 0780033C */  lui        $v1, %hi(D_8006C5BC)
/* 6E039A0 8009C470 BCC5638C */  lw         $v1, %lo(D_8006C5BC)($v1)
/* 6E039A4 8009C474 00000000 */  nop
/* 6E039A8 8009C478 07006214 */  bne        $v1, $v0, .Llevel_32_8009C498
/* 6E039AC 8009C47C 00000000 */   nop
/* 6E039B0 8009C480 0780063C */  lui        $a2, %hi(D_8006E064)
/* 6E039B4 8009C484 64E0C68C */  lw         $a2, %lo(D_8006E064)($a2)
/* 6E039B8 8009C488 0780053C */  lui        $a1, %hi(D_80069030)
/* 6E039BC 8009C48C 3090A524 */  addiu      $a1, $a1, %lo(D_80069030)
/* 6E039C0 8009C490 2B710208 */  j          .Llevel_32_8009C4AC
/* 6E039C4 8009C494 5CFF8424 */   addiu     $a0, $a0, -0xA4
.Llevel_32_8009C498:
/* 6E039C8 8009C498 5CFF8424 */  addiu      $a0, $a0, -0xA4
/* 6E039CC 8009C49C 0780063C */  lui        $a2, %hi(D_8006E064)
/* 6E039D0 8009C4A0 64E0C68C */  lw         $a2, %lo(D_8006E064)($a2)
/* 6E039D4 8009C4A4 0780053C */  lui        $a1, %hi(D_8006901C)
/* 6E039D8 8009C4A8 1C90A524 */  addiu      $a1, $a1, %lo(D_8006901C)
.Llevel_32_8009C4AC:
/* 6E039DC 8009C4AC 694D000C */  jal        func_800135A4
/* 6E039E0 8009C4B0 00000000 */   nop
.Llevel_32_8009C4B4:
/* 6E039E4 8009C4B4 B850000C */  jal        func_800142E0
/* 6E039E8 8009C4B8 00000000 */   nop
/* 6E039EC 8009C4BC 0780103C */  lui        $s0, %hi(D_8006E164)
/* 6E039F0 8009C4C0 64E11026 */  addiu      $s0, $s0, %lo(D_8006E164)
/* 6E039F4 8009C4C4 0000028E */  lw         $v0, 0x0($s0)
/* 6E039F8 8009C4C8 00000000 */  nop
/* 6E039FC 8009C4CC B7014010 */  beqz       $v0, .Llevel_32_8009CBAC
/* 6E03A00 8009C4D0 74FF0426 */   addiu     $a0, $s0, -0x8C
/* 6E03A04 8009C4D4 0780023C */  lui        $v0, %hi(D_8006E164)
/* 6E03A08 8009C4D8 64E1428C */  lw         $v0, %lo(D_8006E164)($v0)
/* 6E03A0C 8009C4DC 0780053C */  lui        $a1, %hi(D_80069300)
/* 6E03A10 8009C4E0 0093A524 */  addiu      $a1, $a1, %lo(D_80069300)
/* 6E03A14 8009C4E4 46004290 */  lbu        $v0, 0x46($v0)
/* 6E03A18 8009C4E8 00000000 */  nop
/* 6E03A1C 8009C4EC 00110200 */  sll        $v0, $v0, 4
/* 6E03A20 8009C4F0 0780013C */  lui        $at, %hi(D_8006E064)
/* 6E03A24 8009C4F4 64E022AC */  sw         $v0, %lo(D_8006E064)($at)
/* 6E03A28 8009C4F8 694D000C */  jal        func_800135A4
/* 6E03A2C 8009C4FC 21300000 */   addu      $a2, $zero, $zero
/* 6E03A30 8009C500 88FF0426 */  addiu      $a0, $s0, -0x78
/* 6E03A34 8009C504 0780053C */  lui        $a1, %hi(D_8006938C)
/* 6E03A38 8009C508 8C93A524 */  addiu      $a1, $a1, %lo(D_8006938C)
/* 6E03A3C 8009C50C 694D000C */  jal        func_800135A4
/* 6E03A40 8009C510 21300000 */   addu      $a2, $zero, $zero
/* 6E03A44 8009C514 9CFF0426 */  addiu      $a0, $s0, -0x64
/* 6E03A48 8009C518 0780053C */  lui        $a1, %hi(D_800693C8)
/* 6E03A4C 8009C51C C893A524 */  addiu      $a1, $a1, %lo(D_800693C8)
/* 6E03A50 8009C520 694D000C */  jal        func_800135A4
/* 6E03A54 8009C524 21300000 */   addu      $a2, $zero, $zero
/* 6E03A58 8009C528 7E720208 */  j          .Llevel_32_8009C9F8
/* 6E03A5C 8009C52C B0FF0426 */   addiu     $a0, $s0, -0x50
.L8009C530_:
/* 6E03A60 8009C530 0780113C */  lui        $s1, %hi(D_8006E160)
/* 6E03A64 8009C534 60E13126 */  addiu      $s1, $s1, %lo(D_8006E160)
/* 6E03A68 8009C538 0000238E */  lw         $v1, 0x0($s1)
/* 6E03A6C 8009C53C 0780023C */  lui        $v0, %hi(D_8006E044)
/* 6E03A70 8009C540 44E0428C */  lw         $v0, %lo(D_8006E044)($v0)
/* 6E03A74 8009C544 00000000 */  nop
/* 6E03A78 8009C548 98016214 */  bne        $v1, $v0, .Llevel_32_8009CBAC
/* 6E03A7C 8009C54C 00000000 */   nop
/* 6E03A80 8009C550 0780023C */  lui        $v0, %hi(D_8006E12C)
/* 6E03A84 8009C554 2CE1428C */  lw         $v0, %lo(D_8006E12C)($v0)
/* 6E03A88 8009C558 00000000 */  nop
/* 6E03A8C 8009C55C 07004014 */  bnez       $v0, .Llevel_32_8009C57C
/* 6E03A90 8009C560 F8FE3326 */   addiu     $s3, $s1, -0x108
/* 6E03A94 8009C564 28FF2426 */  addiu      $a0, $s1, -0xD8
/* 6E03A98 8009C568 0780063C */  lui        $a2, %hi(D_8006E064)
/* 6E03A9C 8009C56C 64E0C68C */  lw         $a2, %lo(D_8006E064)($a2)
/* 6E03AA0 8009C570 694D000C */  jal        func_800135A4
/* 6E03AA4 8009C574 08002526 */   addiu     $a1, $s1, 0x8
/* 6E03AA8 8009C578 F8FE3326 */  addiu      $s3, $s1, -0x108
.Llevel_32_8009C57C:
/* 6E03AAC 8009C57C 21206002 */  addu       $a0, $s3, $zero
/* 6E03AB0 8009C580 5E3C010C */  jal        func_8004F178
/* 6E03AB4 8009C584 1C002526 */   addiu     $a1, $s1, 0x1C
/* 6E03AB8 8009C588 78FF2426 */  addiu      $a0, $s1, -0x88
/* 6E03ABC 8009C58C 80801200 */  sll        $s0, $s2, 2
/* 6E03AC0 8009C590 21801202 */  addu       $s0, $s0, $s2
/* 6E03AC4 8009C594 80801000 */  sll        $s0, $s0, 2
/* 6E03AC8 8009C598 0780053C */  lui        $a1, %hi(D_8006929C)
/* 6E03ACC 8009C59C 9C92A524 */  addiu      $a1, $a1, %lo(D_8006929C)
/* 6E03AD0 8009C5A0 21280502 */  addu       $a1, $s0, $a1
/* 6E03AD4 8009C5A4 0780013C */  lui        $at, %hi(D_8006E064)
/* 6E03AD8 8009C5A8 64E020AC */  sw         $zero, %lo(D_8006E064)($at)
/* 6E03ADC 8009C5AC 694D000C */  jal        func_800135A4
/* 6E03AE0 8009C5B0 21300000 */   addu      $a2, $zero, $zero
/* 6E03AE4 8009C5B4 8CFF2426 */  addiu      $a0, $s1, -0x74
/* 6E03AE8 8009C5B8 0780053C */  lui        $a1, %hi(D_80069328)
/* 6E03AEC 8009C5BC 2893A524 */  addiu      $a1, $a1, %lo(D_80069328)
/* 6E03AF0 8009C5C0 21280502 */  addu       $a1, $s0, $a1
/* 6E03AF4 8009C5C4 694D000C */  jal        func_800135A4
/* 6E03AF8 8009C5C8 21300000 */   addu      $a2, $zero, $zero
/* 6E03AFC 8009C5CC B4FF2426 */  addiu      $a0, $s1, -0x4C
/* 6E03B00 8009C5D0 0780053C */  lui        $a1, %hi(D_800693B4)
/* 6E03B04 8009C5D4 B493A524 */  addiu      $a1, $a1, %lo(D_800693B4)
/* 6E03B08 8009C5D8 694D000C */  jal        func_800135A4
/* 6E03B0C 8009C5DC 21300000 */   addu      $a2, $zero, $zero
/* 6E03B10 8009C5E0 A0FF2426 */  addiu      $a0, $s1, -0x60
/* 6E03B14 8009C5E4 0780053C */  lui        $a1, %hi(D_800693C8)
/* 6E03B18 8009C5E8 C893A524 */  addiu      $a1, $a1, %lo(D_800693C8)
/* 6E03B1C 8009C5EC 694D000C */  jal        func_800135A4
/* 6E03B20 8009C5F0 21300000 */   addu      $a2, $zero, $zero
/* 6E03B24 8009C5F4 0780023C */  lui        $v0, %hi(D_8006E050)
/* 6E03B28 8009C5F8 50E0428C */  lw         $v0, %lo(D_8006E050)($v0)
/* 6E03B2C 8009C5FC 00000000 */  nop
/* 6E03B30 8009C600 02004230 */  andi       $v0, $v0, 0x2
/* 6E03B34 8009C604 69014014 */  bnez       $v0, .Llevel_32_8009CBAC
/* 6E03B38 8009C608 14FF2426 */   addiu     $a0, $s1, -0xEC
/* 6E03B3C 8009C60C C0FE2526 */  addiu      $a1, $s1, -0x140
/* 6E03B40 8009C610 BC4D000C */  jal        func_800136F0
/* 6E03B44 8009C614 21306002 */   addu      $a2, $s3, $zero
/* 6E03B48 8009C618 14FF228E */  lw         $v0, -0xEC($s1)
/* 6E03B4C 8009C61C 0780013C */  lui        $at, %hi(D_8006E09C)
/* 6E03B50 8009C620 9CE022AC */  sw         $v0, %lo(D_8006E09C)($at)
/* 6E03B54 8009C624 EB720208 */  j          .Llevel_32_8009CBAC
/* 6E03B58 8009C628 00000000 */   nop
.L8009C62C_:
/* 6E03B5C 8009C62C 464E000C */  jal        func_80013918
/* 6E03B60 8009C630 00040424 */   addiu     $a0, $zero, 0x400
/* 6E03B64 8009C634 0780023C */  lui        $v0, %hi(D_8006E148)
/* 6E03B68 8009C638 48E1428C */  lw         $v0, %lo(D_8006E148)($v0)
/* 6E03B6C 8009C63C 00000000 */  nop
/* 6E03B70 8009C640 05004010 */  beqz       $v0, .Llevel_32_8009C658
/* 6E03B74 8009C644 01000224 */   addiu     $v0, $zero, 0x1
/* 6E03B78 8009C648 0780013C */  lui        $at, %hi(D_8006E13A)
/* 6E03B7C 8009C64C 3AE122A0 */  sb         $v0, %lo(D_8006E13A)($at)
/* 6E03B80 8009C650 98710208 */  j          .Llevel_32_8009C660
/* 6E03B84 8009C654 00000000 */   nop
.Llevel_32_8009C658:
/* 6E03B88 8009C658 0780013C */  lui        $at, %hi(D_8006E13A)
/* 6E03B8C 8009C65C 3AE120A0 */  sb         $zero, %lo(D_8006E13A)($at)
.Llevel_32_8009C660:
/* 6E03B90 8009C660 0780043C */  lui        $a0, %hi(D_8006E12C)
/* 6E03B94 8009C664 2CE18424 */  addiu      $a0, $a0, %lo(D_8006E12C)
/* 6E03B98 8009C668 0000828C */  lw         $v0, 0x0($a0)
/* 6E03B9C 8009C66C 00000000 */  nop
/* 6E03BA0 8009C670 09004014 */  bnez       $v0, .Llevel_32_8009C698
/* 6E03BA4 8009C674 00000000 */   nop
/* 6E03BA8 8009C678 0780063C */  lui        $a2, %hi(D_8006E064)
/* 6E03BAC 8009C67C 64E0C68C */  lw         $a2, %lo(D_8006E064)($a2)
/* 6E03BB0 8009C680 0780053C */  lui        $a1, %hi(D_80069184)
/* 6E03BB4 8009C684 8491A524 */  addiu      $a1, $a1, %lo(D_80069184)
/* 6E03BB8 8009C688 694D000C */  jal        func_800135A4
/* 6E03BBC 8009C68C 5CFF8424 */   addiu     $a0, $a0, -0xA4
/* 6E03BC0 8009C690 A8710208 */  j          .Llevel_32_8009C6A0
/* 6E03BC4 8009C694 00000000 */   nop
.Llevel_32_8009C698:
/* 6E03BC8 8009C698 0780013C */  lui        $at, %hi(D_8006E148)
/* 6E03BCC 8009C69C 48E120AC */  sw         $zero, %lo(D_8006E148)($at)
.Llevel_32_8009C6A0:
/* 6E03BD0 8009C6A0 B850000C */  jal        func_800142E0
/* 6E03BD4 8009C6A4 80801200 */   sll       $s0, $s2, 2
/* 6E03BD8 8009C6A8 0780113C */  lui        $s1, %hi(D_8006E0D8)
/* 6E03BDC 8009C6AC D8E03126 */  addiu      $s1, $s1, %lo(D_8006E0D8)
/* 6E03BE0 8009C6B0 21202002 */  addu       $a0, $s1, $zero
/* 6E03BE4 8009C6B4 21801202 */  addu       $s0, $s0, $s2
/* 6E03BE8 8009C6B8 80801000 */  sll        $s0, $s0, 2
/* 6E03BEC 8009C6BC 0780053C */  lui        $a1, %hi(D_8006929C)
/* 6E03BF0 8009C6C0 9C92A524 */  addiu      $a1, $a1, %lo(D_8006929C)
/* 6E03BF4 8009C6C4 21280502 */  addu       $a1, $s0, $a1
/* 6E03BF8 8009C6C8 694D000C */  jal        func_800135A4
/* 6E03BFC 8009C6CC 21300000 */   addu      $a2, $zero, $zero
/* 6E03C00 8009C6D0 14002426 */  addiu      $a0, $s1, 0x14
/* 6E03C04 8009C6D4 0780053C */  lui        $a1, %hi(D_80069328)
/* 6E03C08 8009C6D8 2893A524 */  addiu      $a1, $a1, %lo(D_80069328)
/* 6E03C0C 8009C6DC 21280502 */  addu       $a1, $s0, $a1
/* 6E03C10 8009C6E0 694D000C */  jal        func_800135A4
/* 6E03C14 8009C6E4 21300000 */   addu      $a2, $zero, $zero
/* 6E03C18 8009C6E8 3C002426 */  addiu      $a0, $s1, 0x3C
/* 6E03C1C 8009C6EC 0780053C */  lui        $a1, %hi(D_800693B4)
/* 6E03C20 8009C6F0 B493A524 */  addiu      $a1, $a1, %lo(D_800693B4)
/* 6E03C24 8009C6F4 694D000C */  jal        func_800135A4
/* 6E03C28 8009C6F8 21300000 */   addu      $a2, $zero, $zero
/* 6E03C2C 8009C6FC 28002426 */  addiu      $a0, $s1, 0x28
/* 6E03C30 8009C700 0780053C */  lui        $a1, %hi(D_800693C8)
/* 6E03C34 8009C704 C893A524 */  addiu      $a1, $a1, %lo(D_800693C8)
/* 6E03C38 8009C708 694D000C */  jal        func_800135A4
/* 6E03C3C 8009C70C 21300000 */   addu      $a2, $zero, $zero
/* 6E03C40 8009C710 0780023C */  lui        $v0, %hi(D_8006E050)
/* 6E03C44 8009C714 50E0428C */  lw         $v0, %lo(D_8006E050)($v0)
/* 6E03C48 8009C718 00000000 */  nop
/* 6E03C4C 8009C71C 02004230 */  andi       $v0, $v0, 0x2
/* 6E03C50 8009C720 22014014 */  bnez       $v0, .Llevel_32_8009CBAC
/* 6E03C54 8009C724 9CFF2426 */   addiu     $a0, $s1, -0x64
/* 6E03C58 8009C728 48FF2526 */  addiu      $a1, $s1, -0xB8
/* 6E03C5C 8009C72C BC4D000C */  jal        func_800136F0
/* 6E03C60 8009C730 80FF2626 */   addiu     $a2, $s1, -0x80
/* 6E03C64 8009C734 9CFF228E */  lw         $v0, -0x64($s1)
/* 6E03C68 8009C738 0780013C */  lui        $at, %hi(D_8006E09C)
/* 6E03C6C 8009C73C 9CE022AC */  sw         $v0, %lo(D_8006E09C)($at)
/* 6E03C70 8009C740 EB720208 */  j          .Llevel_32_8009CBAC
/* 6E03C74 8009C744 00000000 */   nop
.L8009C748_:
/* 6E03C78 8009C748 0780043C */  lui        $a0, %hi(D_8006E12C)
/* 6E03C7C 8009C74C 2CE18424 */  addiu      $a0, $a0, %lo(D_8006E12C)
/* 6E03C80 8009C750 0000828C */  lw         $v0, 0x0($a0)
/* 6E03C84 8009C754 00000000 */  nop
/* 6E03C88 8009C758 16004014 */  bnez       $v0, .Llevel_32_8009C7B4
/* 6E03C8C 8009C75C 00000000 */   nop
/* 6E03C90 8009C760 0780023C */  lui        $v0, %hi(D_80070328 + 0x16C)
/* 6E03C94 8009C764 9404428C */  lw         $v0, %lo(D_80070328 + 0x16C)($v0)
/* 6E03C98 8009C768 00000000 */  nop
/* 6E03C9C 8009C76C 80004230 */  andi       $v0, $v0, 0x80
/* 6E03CA0 8009C770 09004010 */  beqz       $v0, .Llevel_32_8009C798
/* 6E03CA4 8009C774 00000000 */   nop
/* 6E03CA8 8009C778 0780063C */  lui        $a2, %hi(D_8006E064)
/* 6E03CAC 8009C77C 64E0C68C */  lw         $a2, %lo(D_8006E064)($a2)
/* 6E03CB0 8009C780 0780053C */  lui        $a1, %hi(D_80069260)
/* 6E03CB4 8009C784 6092A524 */  addiu      $a1, $a1, %lo(D_80069260)
/* 6E03CB8 8009C788 694D000C */  jal        func_800135A4
/* 6E03CBC 8009C78C 5CFF8424 */   addiu     $a0, $a0, -0xA4
/* 6E03CC0 8009C790 ED710208 */  j          .Llevel_32_8009C7B4
/* 6E03CC4 8009C794 00000000 */   nop
.Llevel_32_8009C798:
/* 6E03CC8 8009C798 D550000C */  jal        func_80014354
/* 6E03CCC 8009C79C 00000000 */   nop
/* 6E03CD0 8009C7A0 464E000C */  jal        func_80013918
/* 6E03CD4 8009C7A4 00040424 */   addiu     $a0, $zero, 0x400
/* 6E03CD8 8009C7A8 00060224 */  addiu      $v0, $zero, 0x600
/* 6E03CDC 8009C7AC 0780013C */  lui        $at, %hi(D_8006E090)
/* 6E03CE0 8009C7B0 90E022AC */  sw         $v0, %lo(D_8006E090)($at)
.Llevel_32_8009C7B4:
/* 6E03CE4 8009C7B4 B850000C */  jal        func_800142E0
/* 6E03CE8 8009C7B8 80801200 */   sll       $s0, $s2, 2
/* 6E03CEC 8009C7BC 0780113C */  lui        $s1, %hi(D_8006E064)
/* 6E03CF0 8009C7C0 64E03126 */  addiu      $s1, $s1, %lo(D_8006E064)
/* 6E03CF4 8009C7C4 74002426 */  addiu      $a0, $s1, 0x74
/* 6E03CF8 8009C7C8 21801202 */  addu       $s0, $s0, $s2
/* 6E03CFC 8009C7CC 80801000 */  sll        $s0, $s0, 2
/* 6E03D00 8009C7D0 0780053C */  lui        $a1, %hi(D_8006929C)
/* 6E03D04 8009C7D4 9C92A524 */  addiu      $a1, $a1, %lo(D_8006929C)
/* 6E03D08 8009C7D8 0780023C */  lui        $v0, %hi(D_80070328 + 0x218)
/* 6E03D0C 8009C7DC 4005428C */  lw         $v0, %lo(D_80070328 + 0x218)($v0)
/* 6E03D10 8009C7E0 21280502 */  addu       $a1, $s0, $a1
/* 6E03D14 8009C7E4 46004290 */  lbu        $v0, 0x46($v0)
/* 6E03D18 8009C7E8 21300000 */  addu       $a2, $zero, $zero
/* 6E03D1C 8009C7EC 00110200 */  sll        $v0, $v0, 4
/* 6E03D20 8009C7F0 694D000C */  jal        func_800135A4
/* 6E03D24 8009C7F4 000022AE */   sw        $v0, 0x0($s1)
/* 6E03D28 8009C7F8 88002426 */  addiu      $a0, $s1, 0x88
/* 6E03D2C 8009C7FC 0780053C */  lui        $a1, %hi(D_80069328)
/* 6E03D30 8009C800 2893A524 */  addiu      $a1, $a1, %lo(D_80069328)
/* 6E03D34 8009C804 21280502 */  addu       $a1, $s0, $a1
/* 6E03D38 8009C808 694D000C */  jal        func_800135A4
/* 6E03D3C 8009C80C 21300000 */   addu      $a2, $zero, $zero
/* 6E03D40 8009C810 9C002426 */  addiu      $a0, $s1, 0x9C
/* 6E03D44 8009C814 0780053C */  lui        $a1, %hi(D_800693C8)
/* 6E03D48 8009C818 C893A524 */  addiu      $a1, $a1, %lo(D_800693C8)
/* 6E03D4C 8009C81C 694D000C */  jal        func_800135A4
/* 6E03D50 8009C820 21300000 */   addu      $a2, $zero, $zero
/* 6E03D54 8009C824 B0002426 */  addiu      $a0, $s1, 0xB0
/* 6E03D58 8009C828 0780053C */  lui        $a1, %hi(D_800693B4)
/* 6E03D5C 8009C82C B493A524 */  addiu      $a1, $a1, %lo(D_800693B4)
/* 6E03D60 8009C830 694D000C */  jal        func_800135A4
/* 6E03D64 8009C834 21300000 */   addu      $a2, $zero, $zero
/* 6E03D68 8009C838 0780023C */  lui        $v0, %hi(D_8006E050)
/* 6E03D6C 8009C83C 50E0428C */  lw         $v0, %lo(D_8006E050)($v0)
/* 6E03D70 8009C840 00000000 */  nop
/* 6E03D74 8009C844 02004230 */  andi       $v0, $v0, 0x2
/* 6E03D78 8009C848 D8004014 */  bnez       $v0, .Llevel_32_8009CBAC
/* 6E03D7C 8009C84C 10002426 */   addiu     $a0, $s1, 0x10
/* 6E03D80 8009C850 BCFF2526 */  addiu      $a1, $s1, -0x44
/* 6E03D84 8009C854 BC4D000C */  jal        func_800136F0
/* 6E03D88 8009C858 F4FF2626 */   addiu     $a2, $s1, -0xC
/* 6E03D8C 8009C85C 1000228E */  lw         $v0, 0x10($s1)
/* 6E03D90 8009C860 0780013C */  lui        $at, %hi(D_8006E09C)
/* 6E03D94 8009C864 9CE022AC */  sw         $v0, %lo(D_8006E09C)($at)
/* 6E03D98 8009C868 EB720208 */  j          .Llevel_32_8009CBAC
/* 6E03D9C 8009C86C 00000000 */   nop
.L8009C870_:
/* 6E03DA0 8009C870 0780043C */  lui        $a0, %hi(D_8006E12C)
/* 6E03DA4 8009C874 2CE18424 */  addiu      $a0, $a0, %lo(D_8006E12C)
/* 6E03DA8 8009C878 0000828C */  lw         $v0, 0x0($a0)
/* 6E03DAC 8009C87C 00000000 */  nop
/* 6E03DB0 8009C880 2E004014 */  bnez       $v0, .Llevel_32_8009C93C
/* 6E03DB4 8009C884 00000000 */   nop
/* 6E03DB8 8009C888 0780063C */  lui        $a2, %hi(D_8006E064)
/* 6E03DBC 8009C88C 64E0C68C */  lw         $a2, %lo(D_8006E064)($a2)
/* 6E03DC0 8009C890 0780053C */  lui        $a1, %hi(D_80069210)
/* 6E03DC4 8009C894 1092A524 */  addiu      $a1, $a1, %lo(D_80069210)
/* 6E03DC8 8009C898 694D000C */  jal        func_800135A4
/* 6E03DCC 8009C89C 5CFF8424 */   addiu     $a0, $a0, -0xA4
/* 6E03DD0 8009C8A0 0780023C */  lui        $v0, %hi(D_8006E08C)
/* 6E03DD4 8009C8A4 8CE0428C */  lw         $v0, %lo(D_8006E08C)($v0)
/* 6E03DD8 8009C8A8 0780043C */  lui        $a0, %hi(D_80070328 + 0x60)
/* 6E03DDC 8009C8AC 8803848C */  lw         $a0, %lo(D_80070328 + 0x60)($a0)
/* 6E03DE0 8009C8B0 0780033C */  lui        $v1, %hi(D_80070328 + 0x5C)
/* 6E03DE4 8009C8B4 8403638C */  lw         $v1, %lo(D_80070328 + 0x5C)($v1)
/* 6E03DE8 8009C8B8 23104400 */  subu       $v0, $v0, $a0
/* 6E03DEC 8009C8BC 0780043C */  lui        $a0, %hi(D_80070328 + 0xB0)
/* 6E03DF0 8009C8C0 D803848C */  lw         $a0, %lo(D_80070328 + 0xB0)($a0)
/* 6E03DF4 8009C8C4 23180300 */  negu       $v1, $v1
/* 6E03DF8 8009C8C8 0780013C */  lui        $at, %hi(D_8006E08C)
/* 6E03DFC 8009C8CC 8CE022AC */  sw         $v0, %lo(D_8006E08C)($at)
/* 6E03E00 8009C8D0 0780023C */  lui        $v0, %hi(D_8006E090)
/* 6E03E04 8009C8D4 90E0428C */  lw         $v0, %lo(D_8006E090)($v0)
/* 6E03E08 8009C8D8 83180300 */  sra        $v1, $v1, 2
/* 6E03E0C 8009C8DC 0780013C */  lui        $at, %hi(D_8006E098)
/* 6E03E10 8009C8E0 98E023AC */  sw         $v1, %lo(D_8006E098)($at)
/* 6E03E14 8009C8E4 C0FB8424 */  addiu      $a0, $a0, -0x440
/* 6E03E18 8009C8E8 83200400 */  sra        $a0, $a0, 2
/* 6E03E1C 8009C8EC 21104400 */  addu       $v0, $v0, $a0
/* 6E03E20 8009C8F0 0780013C */  lui        $at, %hi(D_8006E090)
/* 6E03E24 8009C8F4 90E022AC */  sw         $v0, %lo(D_8006E090)($at)
/* 6E03E28 8009C8F8 00064228 */  slti       $v0, $v0, 0x600
/* 6E03E2C 8009C8FC 03004010 */  beqz       $v0, .Llevel_32_8009C90C
/* 6E03E30 8009C900 00060224 */   addiu     $v0, $zero, 0x600
/* 6E03E34 8009C904 0780013C */  lui        $at, %hi(D_8006E090)
/* 6E03E38 8009C908 90E022AC */  sw         $v0, %lo(D_8006E090)($at)
.Llevel_32_8009C90C:
/* 6E03E3C 8009C90C 0780023C */  lui        $v0, %hi(D_8006E090)
/* 6E03E40 8009C910 90E0428C */  lw         $v0, %lo(D_8006E090)($v0)
/* 6E03E44 8009C914 00000000 */  nop
/* 6E03E48 8009C918 010E4228 */  slti       $v0, $v0, 0xE01
/* 6E03E4C 8009C91C 03004014 */  bnez       $v0, .Llevel_32_8009C92C
/* 6E03E50 8009C920 000E0224 */   addiu     $v0, $zero, 0xE00
/* 6E03E54 8009C924 0780013C */  lui        $at, %hi(D_8006E090)
/* 6E03E58 8009C928 90E022AC */  sw         $v0, %lo(D_8006E090)($at)
.Llevel_32_8009C92C:
/* 6E03E5C 8009C92C 464E000C */  jal        func_80013918
/* 6E03E60 8009C930 C0000424 */   addiu     $a0, $zero, 0xC0
/* 6E03E64 8009C934 694E000C */  jal        func_800139A4
/* 6E03E68 8009C938 00000000 */   nop
.Llevel_32_8009C93C:
/* 6E03E6C 8009C93C B850000C */  jal        func_800142E0
/* 6E03E70 8009C940 00000000 */   nop
/* 6E03E74 8009C944 0780103C */  lui        $s0, %hi(D_8006E0D8)
/* 6E03E78 8009C948 D8E01026 */  addiu      $s0, $s0, %lo(D_8006E0D8)
/* 6E03E7C 8009C94C 21200002 */  addu       $a0, $s0, $zero
/* 6E03E80 8009C950 80101200 */  sll        $v0, $s2, 2
/* 6E03E84 8009C954 21105200 */  addu       $v0, $v0, $s2
/* 6E03E88 8009C958 80880200 */  sll        $s1, $v0, 2
/* 6E03E8C 8009C95C 0780053C */  lui        $a1, %hi(D_8006929C)
/* 6E03E90 8009C960 9C92A524 */  addiu      $a1, $a1, %lo(D_8006929C)
/* 6E03E94 8009C964 21282502 */  addu       $a1, $s1, $a1
/* 6E03E98 8009C968 694D000C */  jal        func_800135A4
/* 6E03E9C 8009C96C 21300000 */   addu      $a2, $zero, $zero
/* 6E03EA0 8009C970 0000028E */  lw         $v0, 0x0($s0)
/* 6E03EA4 8009C974 00000000 */  nop
/* 6E03EA8 8009C978 00014228 */  slti       $v0, $v0, 0x100
/* 6E03EAC 8009C97C 02004010 */  beqz       $v0, .Llevel_32_8009C988
/* 6E03EB0 8009C980 00010224 */   addiu     $v0, $zero, 0x100
/* 6E03EB4 8009C984 000002AE */  sw         $v0, 0x0($s0)
.Llevel_32_8009C988:
/* 6E03EB8 8009C988 0780023C */  lui        $v0, %hi(D_8006E0DC)
/* 6E03EBC 8009C98C DCE0428C */  lw         $v0, %lo(D_8006E0DC)($v0)
/* 6E03EC0 8009C990 00000000 */  nop
/* 6E03EC4 8009C994 60004228 */  slti       $v0, $v0, 0x60
/* 6E03EC8 8009C998 03004010 */  beqz       $v0, .Llevel_32_8009C9A8
/* 6E03ECC 8009C99C 60000224 */   addiu     $v0, $zero, 0x60
/* 6E03ED0 8009C9A0 0780013C */  lui        $at, %hi(D_8006E0DC)
/* 6E03ED4 8009C9A4 DCE022AC */  sw         $v0, %lo(D_8006E0DC)($at)
.Llevel_32_8009C9A8:
/* 6E03ED8 8009C9A8 0780023C */  lui        $v0, %hi(D_8006E0E8)
/* 6E03EDC 8009C9AC E8E0428C */  lw         $v0, %lo(D_8006E0E8)($v0)
/* 6E03EE0 8009C9B0 00000000 */  nop
/* 6E03EE4 8009C9B4 40004228 */  slti       $v0, $v0, 0x40
/* 6E03EE8 8009C9B8 03004010 */  beqz       $v0, .Llevel_32_8009C9C8
/* 6E03EEC 8009C9BC 40000224 */   addiu     $v0, $zero, 0x40
/* 6E03EF0 8009C9C0 0780013C */  lui        $at, %hi(D_8006E0E8)
/* 6E03EF4 8009C9C4 E8E022AC */  sw         $v0, %lo(D_8006E0E8)($at)
.Llevel_32_8009C9C8:
/* 6E03EF8 8009C9C8 14000426 */  addiu      $a0, $s0, 0x14
/* 6E03EFC 8009C9CC 0780053C */  lui        $a1, %hi(D_80069328)
/* 6E03F00 8009C9D0 2893A524 */  addiu      $a1, $a1, %lo(D_80069328)
/* 6E03F04 8009C9D4 21282502 */  addu       $a1, $s1, $a1
/* 6E03F08 8009C9D8 694D000C */  jal        func_800135A4
/* 6E03F0C 8009C9DC 21300000 */   addu      $a2, $zero, $zero
/* 6E03F10 8009C9E0 28000426 */  addiu      $a0, $s0, 0x28
/* 6E03F14 8009C9E4 0780053C */  lui        $a1, %hi(D_800693C8)
/* 6E03F18 8009C9E8 C893A524 */  addiu      $a1, $a1, %lo(D_800693C8)
/* 6E03F1C 8009C9EC 694D000C */  jal        func_800135A4
/* 6E03F20 8009C9F0 21300000 */   addu      $a2, $zero, $zero
/* 6E03F24 8009C9F4 3C000426 */  addiu      $a0, $s0, 0x3C
.Llevel_32_8009C9F8:
/* 6E03F28 8009C9F8 0780053C */  lui        $a1, %hi(D_800693B4)
/* 6E03F2C 8009C9FC B493A524 */  addiu      $a1, $a1, %lo(D_800693B4)
/* 6E03F30 8009CA00 694D000C */  jal        func_800135A4
/* 6E03F34 8009CA04 21300000 */   addu      $a2, $zero, $zero
/* 6E03F38 8009CA08 EB720208 */  j          .Llevel_32_8009CBAC
/* 6E03F3C 8009CA0C 00000000 */   nop
.L8009CA10_:
/* 6E03F40 8009CA10 0780103C */  lui        $s0, %hi(D_80070328 + 0x4C)
/* 6E03F44 8009CA14 74031026 */  addiu      $s0, $s0, %lo(D_80070328 + 0x4C)
/* 6E03F48 8009CA18 0000038E */  lw         $v1, 0x0($s0)
/* 6E03F4C 8009CA1C 05000224 */  addiu      $v0, $zero, 0x5
/* 6E03F50 8009CA20 16006214 */  bne        $v1, $v0, .Llevel_32_8009CA7C
/* 6E03F54 8009CA24 00000000 */   nop
/* 6E03F58 8009CA28 0780113C */  lui        $s1, %hi(D_8006E058)
/* 6E03F5C 8009CA2C 58E03126 */  addiu      $s1, $s1, %lo(D_8006E058)
/* 6E03F60 8009CA30 21202002 */  addu       $a0, $s1, $zero
/* 6E03F64 8009CA34 5E3C010C */  jal        func_8004F178
/* 6E03F68 8009CA38 B4FF0526 */   addiu     $a1, $s0, -0x4C
/* 6E03F6C 8009CA3C 0780023C */  lui        $v0, %hi(D_8006E12C)
/* 6E03F70 8009CA40 2CE1428C */  lw         $v0, %lo(D_8006E12C)($v0)
/* 6E03F74 8009CA44 00000000 */  nop
/* 6E03F78 8009CA48 27004014 */  bnez       $v0, .Llevel_32_8009CAE8
/* 6E03F7C 8009CA4C 30002426 */   addiu     $a0, $s1, 0x30
/* 6E03F80 8009CA50 0780063C */  lui        $a2, %hi(D_8006E064)
/* 6E03F84 8009CA54 64E0C68C */  lw         $a2, %lo(D_8006E064)($a2)
/* 6E03F88 8009CA58 0780053C */  lui        $a1, %hi(D_80068F7C)
/* 6E03F8C 8009CA5C 7C8FA524 */  addiu      $a1, $a1, %lo(D_80068F7C)
/* 6E03F90 8009CA60 694D000C */  jal        func_800135A4
/* 6E03F94 8009CA64 0008C624 */   addiu     $a2, $a2, 0x800
/* 6E03F98 8009CA68 20030224 */  addiu      $v0, $zero, 0x320
/* 6E03F9C 8009CA6C 0780013C */  lui        $at, %hi(D_8006E08C)
/* 6E03FA0 8009CA70 8CE022AC */  sw         $v0, %lo(D_8006E08C)($at)
/* 6E03FA4 8009CA74 BA720208 */  j          .Llevel_32_8009CAE8
/* 6E03FA8 8009CA78 00000000 */   nop
.Llevel_32_8009CA7C:
/* 6E03FAC 8009CA7C B850000C */  jal        func_800142E0
/* 6E03FB0 8009CA80 00000000 */   nop
/* 6E03FB4 8009CA84 40000426 */  addiu      $a0, $s0, 0x40
/* 6E03FB8 8009CA88 7A3B010C */  jal        func_8004EDE8
/* 6E03FBC 8009CA8C 21280000 */   addu      $a1, $zero, $zero
/* 6E03FC0 8009CA90 80014228 */  slti       $v0, $v0, 0x180
/* 6E03FC4 8009CA94 08004014 */  bnez       $v0, .Llevel_32_8009CAB8
/* 6E03FC8 8009CA98 00000000 */   nop
/* 6E03FCC 8009CA9C 4000048E */  lw         $a0, 0x40($s0)
/* 6E03FD0 8009CAA0 0780053C */  lui        $a1, %hi(D_80070328 + 0x90)
/* 6E03FD4 8009CAA4 B803A58C */  lw         $a1, %lo(D_80070328 + 0x90)($a1)
/* 6E03FD8 8009CAA8 203A010C */  jal        func_8004E880
/* 6E03FDC 8009CAAC 01000624 */   addiu     $a2, $zero, 0x1
/* 6E03FE0 8009CAB0 0780013C */  lui        $at, %hi(D_8006E064)
/* 6E03FE4 8009CAB4 64E022AC */  sw         $v0, %lo(D_8006E064)($at)
.Llevel_32_8009CAB8:
/* 6E03FE8 8009CAB8 0780043C */  lui        $a0, %hi(D_8006E12C)
/* 6E03FEC 8009CABC 2CE18424 */  addiu      $a0, $a0, %lo(D_8006E12C)
/* 6E03FF0 8009CAC0 0000828C */  lw         $v0, 0x0($a0)
/* 6E03FF4 8009CAC4 00000000 */  nop
/* 6E03FF8 8009CAC8 07004014 */  bnez       $v0, .Llevel_32_8009CAE8
/* 6E03FFC 8009CACC 00000000 */   nop
/* 6E04000 8009CAD0 0780063C */  lui        $a2, %hi(D_8006E064)
/* 6E04004 8009CAD4 64E0C68C */  lw         $a2, %lo(D_8006E064)($a2)
/* 6E04008 8009CAD8 0780053C */  lui        $a1, %hi(D_80068F7C)
/* 6E0400C 8009CADC 7C8FA524 */  addiu      $a1, $a1, %lo(D_80068F7C)
/* 6E04010 8009CAE0 694D000C */  jal        func_800135A4
/* 6E04014 8009CAE4 5CFF8424 */   addiu     $a0, $a0, -0xA4
.Llevel_32_8009CAE8:
/* 6E04018 8009CAE8 0780103C */  lui        $s0, %hi(D_8006E0D8)
/* 6E0401C 8009CAEC D8E01026 */  addiu      $s0, $s0, %lo(D_8006E0D8)
/* 6E04020 8009CAF0 21200002 */  addu       $a0, $s0, $zero
/* 6E04024 8009CAF4 80281200 */  sll        $a1, $s2, 2
/* 6E04028 8009CAF8 2128B200 */  addu       $a1, $a1, $s2
/* 6E0402C 8009CAFC 80280500 */  sll        $a1, $a1, 2
/* 6E04030 8009CB00 0780023C */  lui        $v0, %hi(D_8006929C)
/* 6E04034 8009CB04 9C924224 */  addiu      $v0, $v0, %lo(D_8006929C)
/* 6E04038 8009CB08 2128A200 */  addu       $a1, $a1, $v0
/* 6E0403C 8009CB0C 694D000C */  jal        func_800135A4
/* 6E04040 8009CB10 21300000 */   addu      $a2, $zero, $zero
/* 6E04044 8009CB14 0780033C */  lui        $v1, %hi(D_80070328 + 0x4C)
/* 6E04048 8009CB18 7403638C */  lw         $v1, %lo(D_80070328 + 0x4C)($v1)
/* 6E0404C 8009CB1C 05000224 */  addiu      $v0, $zero, 0x5
/* 6E04050 8009CB20 07006210 */  beq        $v1, $v0, .Llevel_32_8009CB40
/* 6E04054 8009CB24 00000000 */   nop
/* 6E04058 8009CB28 0000028E */  lw         $v0, 0x0($s0)
/* 6E0405C 8009CB2C 00000000 */  nop
/* 6E04060 8009CB30 00014228 */  slti       $v0, $v0, 0x100
/* 6E04064 8009CB34 02004010 */  beqz       $v0, .Llevel_32_8009CB40
/* 6E04068 8009CB38 00010224 */   addiu     $v0, $zero, 0x100
/* 6E0406C 8009CB3C 000002AE */  sw         $v0, 0x0($s0)
.Llevel_32_8009CB40:
/* 6E04070 8009CB40 0780103C */  lui        $s0, %hi(D_8006E0EC)
/* 6E04074 8009CB44 ECE01026 */  addiu      $s0, $s0, %lo(D_8006E0EC)
/* 6E04078 8009CB48 21200002 */  addu       $a0, $s0, $zero
/* 6E0407C 8009CB4C 80281200 */  sll        $a1, $s2, 2
/* 6E04080 8009CB50 2128B200 */  addu       $a1, $a1, $s2
/* 6E04084 8009CB54 80280500 */  sll        $a1, $a1, 2
/* 6E04088 8009CB58 0780023C */  lui        $v0, %hi(D_80069328)
/* 6E0408C 8009CB5C 28934224 */  addiu      $v0, $v0, %lo(D_80069328)
/* 6E04090 8009CB60 2128A200 */  addu       $a1, $a1, $v0
/* 6E04094 8009CB64 694D000C */  jal        func_800135A4
/* 6E04098 8009CB68 21300000 */   addu      $a2, $zero, $zero
/* 6E0409C 8009CB6C 14000426 */  addiu      $a0, $s0, 0x14
/* 6E040A0 8009CB70 0780053C */  lui        $a1, %hi(D_800693C8)
/* 6E040A4 8009CB74 C893A524 */  addiu      $a1, $a1, %lo(D_800693C8)
/* 6E040A8 8009CB78 694D000C */  jal        func_800135A4
/* 6E040AC 8009CB7C 21300000 */   addu      $a2, $zero, $zero
/* 6E040B0 8009CB80 28000426 */  addiu      $a0, $s0, 0x28
/* 6E040B4 8009CB84 0780053C */  lui        $a1, %hi(D_800693B4)
/* 6E040B8 8009CB88 B493A524 */  addiu      $a1, $a1, %lo(D_800693B4)
/* 6E040BC 8009CB8C 694D000C */  jal        func_800135A4
/* 6E040C0 8009CB90 21300000 */   addu      $a2, $zero, $zero
/* 6E040C4 8009CB94 0780023C */  lui        $v0, %hi(D_80070328 + 0x168)
/* 6E040C8 8009CB98 9004428C */  lw         $v0, %lo(D_80070328 + 0x168)($v0)
/* 6E040CC 8009CB9C 00000000 */  nop
/* 6E040D0 8009CBA0 23100200 */  negu       $v0, $v0
/* 6E040D4 8009CBA4 0780013C */  lui        $at, %hi(D_8006E1D0)
/* 6E040D8 8009CBA8 D0E122AC */  sw         $v0, %lo(D_8006E1D0)($at)
.Llevel_32_8009CBAC:
/* 6E040DC 8009CBAC 2000BF8F */  lw         $ra, 0x20($sp)
/* 6E040E0 8009CBB0 1C00B38F */  lw         $s3, 0x1C($sp)
/* 6E040E4 8009CBB4 1800B28F */  lw         $s2, 0x18($sp)
/* 6E040E8 8009CBB8 1400B18F */  lw         $s1, 0x14($sp)
/* 6E040EC 8009CBBC 1000B08F */  lw         $s0, 0x10($sp)
/* 6E040F0 8009CBC0 2800BD27 */  addiu      $sp, $sp, 0x28
/* 6E040F4 8009CBC4 0800E003 */  jr         $ra
/* 6E040F8 8009CBC8 00000000 */   nop
.size func_level_32_8009C2B8, . - func_level_32_8009C2B8
