.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
dlabel D_level_50_80074AC4
/* 95C8FF4 80074AC4 */ .asciz "%d:%02d.%02d"
.align 2
.size D_level_50_80074AC4, . - D_level_50_80074AC4

.align 2
dlabel D_level_50_80074AD4
/* 95C9004 80074AD4 */ .asciz "%d.%02d"
.align 2
.size D_level_50_80074AD4, . - D_level_50_80074AD4


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_50_8009669C
/* 95EABCC 8009669C B0FFBD27 */  addiu      $sp, $sp, -0x50
/* 95EABD0 800966A0 70000424 */  addiu      $a0, $zero, 0x70
/* 95EABD4 800966A4 90010524 */  addiu      $a1, $zero, 0x190
/* 95EABD8 800966A8 48000624 */  addiu      $a2, $zero, 0x48
/* 95EABDC 800966AC 4800BFAF */  sw         $ra, 0x48($sp)
/* 95EABE0 800966B0 407F000C */  jal        func_8001FD00
/* 95EABE4 800966B4 B0000724 */   addiu     $a3, $zero, 0xB0
/* 95EABE8 800966B8 90000424 */  addiu      $a0, $zero, 0x90
/* 95EABEC 800966BC 5E000524 */  addiu      $a1, $zero, 0x5E
/* 95EABF0 800966C0 70010624 */  addiu      $a2, $zero, 0x170
/* 95EABF4 800966C4 DD7E000C */  jal        func_8001FB74
/* 95EABF8 800966C8 5E000724 */   addiu     $a3, $zero, 0x5E
/* 95EABFC 800966CC 90000424 */  addiu      $a0, $zero, 0x90
/* 95EAC00 800966D0 8C000524 */  addiu      $a1, $zero, 0x8C
/* 95EAC04 800966D4 70010624 */  addiu      $a2, $zero, 0x170
/* 95EAC08 800966D8 DD7E000C */  jal        func_8001FB74
/* 95EAC0C 800966DC 8C000724 */   addiu     $a3, $zero, 0x8C
/* 95EAC10 800966E0 0780023C */  lui        $v0, %hi(D_8006FBC8)
/* 95EAC14 800966E4 C8FB428C */  lw         $v0, %lo(D_8006FBC8)($v0)
/* 95EAC18 800966E8 00000000 */  nop
/* 95EAC1C 800966EC 4C004018 */  blez       $v0, .Llevel_50_80096820
/* 95EAC20 800966F0 C0000524 */   addiu     $a1, $zero, 0xC0
/* 95EAC24 800966F4 0780023C */  lui        $v0, %hi(D_8006C76C)
/* 95EAC28 800966F8 6CC7428C */  lw         $v0, %lo(D_8006C76C)($v0)
/* 95EAC2C 800966FC 68000624 */  addiu      $a2, $zero, 0x68
/* 95EAC30 80096700 80100200 */  sll        $v0, $v0, 2
/* 95EAC34 80096704 0780013C */  lui        $at, %hi(D_8006C440)
/* 95EAC38 80096708 21082200 */  addu       $at, $at, $v0
/* 95EAC3C 8009670C 40C4248C */  lw         $a0, %lo(D_8006C440)($at)
/* 95EAC40 80096710 B780000C */  jal        func_800202DC
/* 95EAC44 80096714 02000724 */   addiu     $a3, $zero, 0x2
/* 95EAC48 80096718 0780023C */  lui        $v0, %hi(D_8006C76C)
/* 95EAC4C 8009671C 6CC7428C */  lw         $v0, %lo(D_8006C76C)($v0)
/* 95EAC50 80096720 00000000 */  nop
/* 95EAC54 80096724 80100200 */  sll        $v0, $v0, 2
/* 95EAC58 80096728 0780013C */  lui        $at, %hi(D_8006C440)
/* 95EAC5C 8009672C 21082200 */  addu       $at, $at, $v0
/* 95EAC60 80096730 40C4248C */  lw         $a0, %lo(D_8006C440)($at)
/* 95EAC64 80096734 ECBA000C */  jal        func_8002EBB0
/* 95EAC68 80096738 00000000 */   nop
/* 95EAC6C 8009673C 8888073C */  lui        $a3, (0x88888889 >> 16)
/* 95EAC70 80096740 0780043C */  lui        $a0, %hi(D_8006FA70)
/* 95EAC74 80096744 70FA848C */  lw         $a0, %lo(D_8006FA70)($a0)
/* 95EAC78 80096748 8988E734 */  ori        $a3, $a3, (0x88888889 & 0xFFFF)
/* 95EAC7C 8009674C 18008700 */  mult       $a0, $a3
/* 95EAC80 80096750 10180000 */  mfhi       $v1
/* 95EAC84 80096754 A291023C */  lui        $v0, (0x91A2B3C5 >> 16)
/* 95EAC88 80096758 C5B34234 */  ori        $v0, $v0, (0x91A2B3C5 & 0xFFFF)
/* 95EAC8C 8009675C 18008200 */  mult       $a0, $v0
/* 95EAC90 80096760 C3370400 */  sra        $a2, $a0, 31
/* 95EAC94 80096764 21286400 */  addu       $a1, $v1, $a0
/* 95EAC98 80096768 43290500 */  sra        $a1, $a1, 5
/* 95EAC9C 8009676C 2328A600 */  subu       $a1, $a1, $a2
/* 95EACA0 80096770 00110500 */  sll        $v0, $a1, 4
/* 95EACA4 80096774 23104500 */  subu       $v0, $v0, $a1
/* 95EACA8 80096778 80100200 */  sll        $v0, $v0, 2
/* 95EACAC 8009677C 23108200 */  subu       $v0, $a0, $v0
/* 95EACB0 80096780 40180200 */  sll        $v1, $v0, 1
/* 95EACB4 80096784 21186200 */  addu       $v1, $v1, $v0
/* 95EACB8 80096788 C0180300 */  sll        $v1, $v1, 3
/* 95EACBC 8009678C 10400000 */  mfhi       $t0
/* 95EACC0 80096790 21186200 */  addu       $v1, $v1, $v0
/* 95EACC4 80096794 80180300 */  sll        $v1, $v1, 2
/* 95EACC8 80096798 18006700 */  mult       $v1, $a3
/* 95EACCC 8009679C 21200401 */  addu       $a0, $t0, $a0
/* 95EACD0 800967A0 C3220400 */  sra        $a0, $a0, 11
/* 95EACD4 800967A4 23308600 */  subu       $a2, $a0, $a2
/* 95EACD8 800967A8 00110600 */  sll        $v0, $a2, 4
/* 95EACDC 800967AC 23104600 */  subu       $v0, $v0, $a2
/* 95EACE0 800967B0 80100200 */  sll        $v0, $v0, 2
/* 95EACE4 800967B4 2338A200 */  subu       $a3, $a1, $v0
/* 95EACE8 800967B8 10500000 */  mfhi       $t2
/* 95EACEC 800967BC 21104301 */  addu       $v0, $t2, $v1
/* 95EACF0 800967C0 43110200 */  sra        $v0, $v0, 5
/* 95EACF4 800967C4 C31F0300 */  sra        $v1, $v1, 31
/* 95EACF8 800967C8 0800C010 */  beqz       $a2, .Llevel_50_800967EC
/* 95EACFC 800967CC 23104300 */   subu      $v0, $v0, $v1
/* 95EAD00 800967D0 1000A2AF */  sw         $v0, 0x10($sp)
/* 95EAD04 800967D4 0780053C */  lui        $a1, %hi(D_level_50_80074AC4)
/* 95EAD08 800967D8 C44AA524 */  addiu      $a1, $a1, %lo(D_level_50_80074AC4)
/* 95EAD0C 800967DC DF65010C */  jal        func_8005977C
/* 95EAD10 800967E0 1800A427 */   addiu     $a0, $sp, 0x18
/* 95EAD14 800967E4 025A0208 */  j          .Llevel_50_80096808
/* 95EAD18 800967E8 1800A427 */   addiu     $a0, $sp, 0x18
.Llevel_50_800967EC:
/* 95EAD1C 800967EC 1800A427 */  addiu      $a0, $sp, 0x18
/* 95EAD20 800967F0 0780053C */  lui        $a1, %hi(D_level_50_80074AD4)
/* 95EAD24 800967F4 D44AA524 */  addiu      $a1, $a1, %lo(D_level_50_80074AD4)
/* 95EAD28 800967F8 2130E000 */  addu       $a2, $a3, $zero
/* 95EAD2C 800967FC DF65010C */  jal        func_8005977C
/* 95EAD30 80096800 21384000 */   addu      $a3, $v0, $zero
/* 95EAD34 80096804 1800A427 */  addiu      $a0, $sp, 0x18
.Llevel_50_80096808:
/* 95EAD38 80096808 C0000524 */  addiu      $a1, $zero, 0xC0
/* 95EAD3C 8009680C 79000624 */  addiu      $a2, $zero, 0x79
/* 95EAD40 80096810 B780000C */  jal        func_800202DC
/* 95EAD44 80096814 02000724 */   addiu     $a3, $zero, 0x2
/* 95EAD48 80096818 0780023C */  lui        $v0, %hi(D_8006FBC8)
/* 95EAD4C 8009681C C8FB428C */  lw         $v0, %lo(D_8006FBC8)($v0)
.Llevel_50_80096820:
/* 95EAD50 80096820 00000000 */  nop
/* 95EAD54 80096824 02004228 */  slti       $v0, $v0, 0x2
/* 95EAD58 80096828 4A004014 */  bnez       $v0, .Llevel_50_80096954
/* 95EAD5C 8009682C 40010524 */   addiu     $a1, $zero, 0x140
/* 95EAD60 80096830 0780023C */  lui        $v0, %hi(D_8006C76C)
/* 95EAD64 80096834 6CC7428C */  lw         $v0, %lo(D_8006C76C)($v0)
/* 95EAD68 80096838 68000624 */  addiu      $a2, $zero, 0x68
/* 95EAD6C 8009683C 80100200 */  sll        $v0, $v0, 2
/* 95EAD70 80096840 0780013C */  lui        $at, %hi(D_8006C454)
/* 95EAD74 80096844 21082200 */  addu       $at, $at, $v0
/* 95EAD78 80096848 54C4248C */  lw         $a0, %lo(D_8006C454)($at)
/* 95EAD7C 8009684C B780000C */  jal        func_800202DC
/* 95EAD80 80096850 02000724 */   addiu     $a3, $zero, 0x2
/* 95EAD84 80096854 0780023C */  lui        $v0, %hi(D_8006C76C)
/* 95EAD88 80096858 6CC7428C */  lw         $v0, %lo(D_8006C76C)($v0)
/* 95EAD8C 8009685C 00000000 */  nop
/* 95EAD90 80096860 80100200 */  sll        $v0, $v0, 2
/* 95EAD94 80096864 0780013C */  lui        $at, %hi(D_8006C454)
/* 95EAD98 80096868 21082200 */  addu       $at, $at, $v0
/* 95EAD9C 8009686C 54C4248C */  lw         $a0, %lo(D_8006C454)($at)
/* 95EADA0 80096870 ECBA000C */  jal        func_8002EBB0
/* 95EADA4 80096874 00000000 */   nop
/* 95EADA8 80096878 8888073C */  lui        $a3, (0x88888889 >> 16)
/* 95EADAC 8009687C 0780043C */  lui        $a0, %hi(D_800718D8)
/* 95EADB0 80096880 D818848C */  lw         $a0, %lo(D_800718D8)($a0)
/* 95EADB4 80096884 8988E734 */  ori        $a3, $a3, (0x88888889 & 0xFFFF)
/* 95EADB8 80096888 18008700 */  mult       $a0, $a3
/* 95EADBC 8009688C 10180000 */  mfhi       $v1
/* 95EADC0 80096890 A291023C */  lui        $v0, (0x91A2B3C5 >> 16)
/* 95EADC4 80096894 C5B34234 */  ori        $v0, $v0, (0x91A2B3C5 & 0xFFFF)
/* 95EADC8 80096898 18008200 */  mult       $a0, $v0
/* 95EADCC 8009689C C3370400 */  sra        $a2, $a0, 31
/* 95EADD0 800968A0 21286400 */  addu       $a1, $v1, $a0
/* 95EADD4 800968A4 43290500 */  sra        $a1, $a1, 5
/* 95EADD8 800968A8 2328A600 */  subu       $a1, $a1, $a2
/* 95EADDC 800968AC 00110500 */  sll        $v0, $a1, 4
/* 95EADE0 800968B0 23104500 */  subu       $v0, $v0, $a1
/* 95EADE4 800968B4 80100200 */  sll        $v0, $v0, 2
/* 95EADE8 800968B8 23108200 */  subu       $v0, $a0, $v0
/* 95EADEC 800968BC 40180200 */  sll        $v1, $v0, 1
/* 95EADF0 800968C0 21186200 */  addu       $v1, $v1, $v0
/* 95EADF4 800968C4 C0180300 */  sll        $v1, $v1, 3
/* 95EADF8 800968C8 10400000 */  mfhi       $t0
/* 95EADFC 800968CC 21186200 */  addu       $v1, $v1, $v0
/* 95EAE00 800968D0 80180300 */  sll        $v1, $v1, 2
/* 95EAE04 800968D4 18006700 */  mult       $v1, $a3
/* 95EAE08 800968D8 21200401 */  addu       $a0, $t0, $a0
/* 95EAE0C 800968DC C3220400 */  sra        $a0, $a0, 11
/* 95EAE10 800968E0 23308600 */  subu       $a2, $a0, $a2
/* 95EAE14 800968E4 00110600 */  sll        $v0, $a2, 4
/* 95EAE18 800968E8 23104600 */  subu       $v0, $v0, $a2
/* 95EAE1C 800968EC 80100200 */  sll        $v0, $v0, 2
/* 95EAE20 800968F0 2338A200 */  subu       $a3, $a1, $v0
/* 95EAE24 800968F4 10500000 */  mfhi       $t2
/* 95EAE28 800968F8 21104301 */  addu       $v0, $t2, $v1
/* 95EAE2C 800968FC 43110200 */  sra        $v0, $v0, 5
/* 95EAE30 80096900 C31F0300 */  sra        $v1, $v1, 31
/* 95EAE34 80096904 0800C010 */  beqz       $a2, .Llevel_50_80096928
/* 95EAE38 80096908 23104300 */   subu      $v0, $v0, $v1
/* 95EAE3C 8009690C 1000A2AF */  sw         $v0, 0x10($sp)
/* 95EAE40 80096910 0780053C */  lui        $a1, %hi(D_level_50_80074AC4)
/* 95EAE44 80096914 C44AA524 */  addiu      $a1, $a1, %lo(D_level_50_80074AC4)
/* 95EAE48 80096918 DF65010C */  jal        func_8005977C
/* 95EAE4C 8009691C 2800A427 */   addiu     $a0, $sp, 0x28
/* 95EAE50 80096920 515A0208 */  j          .Llevel_50_80096944
/* 95EAE54 80096924 2800A427 */   addiu     $a0, $sp, 0x28
.Llevel_50_80096928:
/* 95EAE58 80096928 2800A427 */  addiu      $a0, $sp, 0x28
/* 95EAE5C 8009692C 0780053C */  lui        $a1, %hi(D_level_50_80074AD4)
/* 95EAE60 80096930 D44AA524 */  addiu      $a1, $a1, %lo(D_level_50_80074AD4)
/* 95EAE64 80096934 2130E000 */  addu       $a2, $a3, $zero
/* 95EAE68 80096938 DF65010C */  jal        func_8005977C
/* 95EAE6C 8009693C 21384000 */   addu      $a3, $v0, $zero
/* 95EAE70 80096940 2800A427 */  addiu      $a0, $sp, 0x28
.Llevel_50_80096944:
/* 95EAE74 80096944 40010524 */  addiu      $a1, $zero, 0x140
/* 95EAE78 80096948 79000624 */  addiu      $a2, $zero, 0x79
/* 95EAE7C 8009694C B780000C */  jal        func_800202DC
/* 95EAE80 80096950 02000724 */   addiu     $a3, $zero, 0x2
.Llevel_50_80096954:
/* 95EAE84 80096954 0780023C */  lui        $v0, %hi(D_8006FBC8)
/* 95EAE88 80096958 C8FB428C */  lw         $v0, %lo(D_8006FBC8)($v0)
/* 95EAE8C 8009695C 00000000 */  nop
/* 95EAE90 80096960 03004228 */  slti       $v0, $v0, 0x3
/* 95EAE94 80096964 23004014 */  bnez       $v0, .Llevel_50_800969F4
/* 95EAE98 80096968 00000000 */   nop
/* 95EAE9C 8009696C 0780023C */  lui        $v0, %hi(D_8006FA70)
/* 95EAEA0 80096970 70FA428C */  lw         $v0, %lo(D_8006FA70)($v0)
/* 95EAEA4 80096974 0780033C */  lui        $v1, %hi(D_800718D8)
/* 95EAEA8 80096978 D818638C */  lw         $v1, %lo(D_800718D8)($v1)
/* 95EAEAC 8009697C 00000000 */  nop
/* 95EAEB0 80096980 2A104300 */  slt        $v0, $v0, $v1
/* 95EAEB4 80096984 11004010 */  beqz       $v0, .Llevel_50_800969CC
/* 95EAEB8 80096988 02000724 */   addiu     $a3, $zero, 0x2
/* 95EAEBC 8009698C 0780043C */  lui        $a0, %hi(D_8006C458)
/* 95EAEC0 80096990 58C48424 */  addiu      $a0, $a0, %lo(D_8006C458)
/* 95EAEC4 80096994 0780023C */  lui        $v0, %hi(D_8006C76C)
/* 95EAEC8 80096998 6CC7428C */  lw         $v0, %lo(D_8006C76C)($v0)
/* 95EAECC 8009699C 0780033C */  lui        $v1, %hi(D_8006FBC4)
/* 95EAED0 800969A0 C4FB638C */  lw         $v1, %lo(D_8006FBC4)($v1)
/* 95EAED4 800969A4 80100200 */  sll        $v0, $v0, 2
/* 95EAED8 800969A8 1F006330 */  andi       $v1, $v1, 0x1F
/* 95EAEDC 800969AC 16006328 */  slti       $v1, $v1, 0x16
/* 95EAEE0 800969B0 02006010 */  beqz       $v1, .Llevel_50_800969BC
/* 95EAEE4 800969B4 21104400 */   addu      $v0, $v0, $a0
/* 95EAEE8 800969B8 03000724 */  addiu      $a3, $zero, 0x3
.Llevel_50_800969BC:
/* 95EAEEC 800969BC 0000448C */  lw         $a0, 0x0($v0)
/* 95EAEF0 800969C0 00010524 */  addiu      $a1, $zero, 0x100
/* 95EAEF4 800969C4 7B5A0208 */  j          .Llevel_50_800969EC
/* 95EAEF8 800969C8 50000624 */   addiu     $a2, $zero, 0x50
.Llevel_50_800969CC:
/* 95EAEFC 800969CC 00010524 */  addiu      $a1, $zero, 0x100
/* 95EAF00 800969D0 0780023C */  lui        $v0, %hi(D_8006C76C)
/* 95EAF04 800969D4 6CC7428C */  lw         $v0, %lo(D_8006C76C)($v0)
/* 95EAF08 800969D8 50000624 */  addiu      $a2, $zero, 0x50
/* 95EAF0C 800969DC 80100200 */  sll        $v0, $v0, 2
/* 95EAF10 800969E0 0780013C */  lui        $at, %hi(D_8006C45C)
/* 95EAF14 800969E4 21082200 */  addu       $at, $at, $v0
/* 95EAF18 800969E8 5CC4248C */  lw         $a0, %lo(D_8006C45C)($at)
.Llevel_50_800969EC:
/* 95EAF1C 800969EC B780000C */  jal        func_800202DC
/* 95EAF20 800969F0 00000000 */   nop
.Llevel_50_800969F4:
/* 95EAF24 800969F4 0780033C */  lui        $v1, %hi(D_8006FBC8)
/* 95EAF28 800969F8 C8FB638C */  lw         $v1, %lo(D_8006FBC8)($v1)
/* 95EAF2C 800969FC 05000224 */  addiu      $v0, $zero, 0x5
/* 95EAF30 80096A00 11006214 */  bne        $v1, $v0, .Llevel_50_80096A48
/* 95EAF34 80096A04 02000724 */   addiu     $a3, $zero, 0x2
/* 95EAF38 80096A08 0780043C */  lui        $a0, %hi(D_8006C43C)
/* 95EAF3C 80096A0C 3CC48424 */  addiu      $a0, $a0, %lo(D_8006C43C)
/* 95EAF40 80096A10 0780023C */  lui        $v0, %hi(D_8006C76C)
/* 95EAF44 80096A14 6CC7428C */  lw         $v0, %lo(D_8006C76C)($v0)
/* 95EAF48 80096A18 0780033C */  lui        $v1, %hi(D_8006FBC4)
/* 95EAF4C 80096A1C C4FB638C */  lw         $v1, %lo(D_8006FBC4)($v1)
/* 95EAF50 80096A20 80100200 */  sll        $v0, $v0, 2
/* 95EAF54 80096A24 1F006330 */  andi       $v1, $v1, 0x1F
/* 95EAF58 80096A28 16006328 */  slti       $v1, $v1, 0x16
/* 95EAF5C 80096A2C 02006010 */  beqz       $v1, .Llevel_50_80096A38
/* 95EAF60 80096A30 21104400 */   addu      $v0, $v0, $a0
/* 95EAF64 80096A34 03000724 */  addiu      $a3, $zero, 0x3
.Llevel_50_80096A38:
/* 95EAF68 80096A38 0000448C */  lw         $a0, 0x0($v0)
/* 95EAF6C 80096A3C 00010524 */  addiu      $a1, $zero, 0x100
/* 95EAF70 80096A40 B780000C */  jal        func_800202DC
/* 95EAF74 80096A44 9A000624 */   addiu     $a2, $zero, 0x9A
.Llevel_50_80096A48:
/* 95EAF78 80096A48 4800BF8F */  lw         $ra, 0x48($sp)
/* 95EAF7C 80096A4C 5000BD27 */  addiu      $sp, $sp, 0x50
/* 95EAF80 80096A50 0800E003 */  jr         $ra
/* 95EAF84 80096A54 00000000 */   nop
.size func_level_50_8009669C, . - func_level_50_8009669C
