.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_37_800746A0
/* 7AA03D0 800746A0 E00B0880 */ .word .Llevel_37_80080BE0
/* 7AA03D4 800746A4 B80B0880 */ .word .Llevel_37_80080BB8
/* 7AA03D8 800746A8 E00B0880 */ .word .Llevel_37_80080BE0
/* 7AA03DC 800746AC 400B0880 */ .word .L80080B40_
/* 7AA03E0 800746B0 28050880 */ .word .L80080528_
/* 7AA03E4 800746B4 E00B0880 */ .word .Llevel_37_80080BE0
/* 7AA03E8 800746B8 E00B0880 */ .word .Llevel_37_80080BE0
/* 7AA03EC 800746BC E00B0880 */ .word .Llevel_37_80080BE0
/* 7AA03F0 800746C0 E00B0880 */ .word .Llevel_37_80080BE0
/* 7AA03F4 800746C4 E00B0880 */ .word .Llevel_37_80080BE0
/* 7AA03F8 800746C8 E00B0880 */ .word .Llevel_37_80080BE0
/* 7AA03FC 800746CC E00B0880 */ .word .Llevel_37_80080BE0
/* 7AA0400 800746D0 E00B0880 */ .word .Llevel_37_80080BE0
/* 7AA0404 800746D4 E00B0880 */ .word .Llevel_37_80080BE0
/* 7AA0408 800746D8 E00B0880 */ .word .Llevel_37_80080BE0
/* 7AA040C 800746DC E00B0880 */ .word .Llevel_37_80080BE0
/* 7AA0410 800746E0 E00B0880 */ .word .Llevel_37_80080BE0
/* 7AA0414 800746E4 E00B0880 */ .word .Llevel_37_80080BE0
/* 7AA0418 800746E8 E00B0880 */ .word .Llevel_37_80080BE0
/* 7AA041C 800746EC E00B0880 */ .word .Llevel_37_80080BE0
/* 7AA0420 800746F0 F0050880 */ .word .L800805F0_
/* 7AA0424 800746F4 A0FC0780 */ .word .L8007FCA0_
/* 7AA0428 800746F8 5CFF0780 */ .word .L8007FF5C_
/* 7AA042C 800746FC 5CFF0780 */ .word .L8007FF5C_
/* 7AA0430 80074700 C4030880 */ .word .L800803C4_
/* 7AA0434 80074704 00000000 */ .word 0x00000000
.size jtbl_level_37_800746A0, . - jtbl_level_37_800746A0


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_37_8007FC30
/* 7AAB960 8007FC30 18FFBD27 */  addiu      $sp, $sp, -0xE8
/* 7AAB964 8007FC34 C800B2AF */  sw         $s2, 0xC8($sp)
/* 7AAB968 8007FC38 21908000 */  addu       $s2, $a0, $zero
/* 7AAB96C 8007FC3C 02000224 */  addiu      $v0, $zero, 0x2
/* 7AAB970 8007FC40 E000BFAF */  sw         $ra, 0xE0($sp)
/* 7AAB974 8007FC44 DC00B7AF */  sw         $s7, 0xDC($sp)
/* 7AAB978 8007FC48 D800B6AF */  sw         $s6, 0xD8($sp)
/* 7AAB97C 8007FC4C D400B5AF */  sw         $s5, 0xD4($sp)
/* 7AAB980 8007FC50 D000B4AF */  sw         $s4, 0xD0($sp)
/* 7AAB984 8007FC54 CC00B3AF */  sw         $s3, 0xCC($sp)
/* 7AAB988 8007FC58 C400B1AF */  sw         $s1, 0xC4($sp)
/* 7AAB98C 8007FC5C C000B0AF */  sw         $s0, 0xC0($sp)
/* 7AAB990 8007FC60 0000538E */  lw         $s3, 0x0($s2)
/* 7AAB994 8007FC64 0780103C */  lui        $s0, %hi(D_8006C550)
/* 7AAB998 8007FC68 50C5108E */  lw         $s0, %lo(D_8006C550)($s0)
/* 7AAB99C 8007FC6C 48004392 */  lbu        $v1, 0x48($s2)
/* 7AAB9A0 8007FC70 0000178E */  lw         $s7, 0x0($s0)
/* 7AAB9A4 8007FC74 C6046210 */  beq        $v1, $v0, .Llevel_37_80080F90
/* 7AAB9A8 8007FC78 21A86002 */   addu      $s5, $s3, $zero
/* 7AAB9AC 8007FC7C 1900622C */  sltiu      $v0, $v1, 0x19
/* 7AAB9B0 8007FC80 D8034010 */  beqz       $v0, .Llevel_37_80080BE4
/* 7AAB9B4 8007FC84 80100300 */   sll       $v0, $v1, 2
/* 7AAB9B8 8007FC88 0780013C */  lui        $at, %hi(jtbl_level_37_800746A0)
/* 7AAB9BC 8007FC8C 21082200 */  addu       $at, $at, $v0
/* 7AAB9C0 8007FC90 A046228C */  lw         $v0, %lo(jtbl_level_37_800746A0)($at)
/* 7AAB9C4 8007FC94 00000000 */  nop
/* 7AAB9C8 8007FC98 08004000 */  jr         $v0
/* 7AAB9CC 8007FC9C 00000000 */   nop
.L8007FCA0_:
/* 7AAB9D0 8007FCA0 20000224 */  addiu      $v0, $zero, 0x20
/* 7AAB9D4 8007FCA4 4F0042A2 */  sb         $v0, 0x4F($s2)
/* 7AAB9D8 8007FCA8 50000224 */  addiu      $v0, $zero, 0x50
/* 7AAB9DC 8007FCAC 01000324 */  addiu      $v1, $zero, 0x1
/* 7AAB9E0 8007FCB0 4C0042A2 */  sb         $v0, 0x4C($s2)
/* 7AAB9E4 8007FCB4 3F000224 */  addiu      $v0, $zero, 0x3F
/* 7AAB9E8 8007FCB8 450040A2 */  sb         $zero, 0x45($s2)
/* 7AAB9EC 8007FCBC 4D0043A2 */  sb         $v1, 0x4D($s2)
/* 7AAB9F0 8007FCC0 410043A2 */  sb         $v1, 0x41($s2)
/* 7AAB9F4 8007FCC4 4C0042A2 */  sb         $v0, 0x4C($s2)
/* 7AAB9F8 8007FCC8 4D0043A2 */  sb         $v1, 0x4D($s2)
/* 7AAB9FC 8007FCCC 6C00E28E */  lw         $v0, 0x6C($s7)
/* 7AABA00 8007FCD0 00000000 */  nop
/* 7AABA04 8007FCD4 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 7AABA08 8007FCD8 02004104 */  bgez       $v0, .Llevel_37_8007FCE4
/* 7AABA0C 8007FCDC 6C00E2AE */   sw        $v0, 0x6C($s7)
/* 7AABA10 8007FCE0 6C00E0AE */  sw         $zero, 0x6C($s7)
.Llevel_37_8007FCE4:
/* 7AABA14 8007FCE4 0780033C */  lui        $v1, %hi(D_8006E044)
/* 7AABA18 8007FCE8 44E0638C */  lw         $v1, %lo(D_8006E044)($v1)
/* 7AABA1C 8007FCEC 07000224 */  addiu      $v0, $zero, 0x7
/* 7AABA20 8007FCF0 05006214 */  bne        $v1, $v0, .Llevel_37_8007FD08
/* 7AABA24 8007FCF4 0C004426 */   addiu     $a0, $s2, 0xC
/* 7AABA28 8007FCF8 2125010C */  jal        func_80049484
/* 7AABA2C 8007FCFC 0C004426 */   addiu     $a0, $s2, 0xC
/* 7AABA30 8007FD00 61FF0108 */  j          .Llevel_37_8007FD84
/* 7AABA34 8007FD04 FFFF0224 */   addiu     $v0, $zero, -0x1
.Llevel_37_8007FD08:
/* 7AABA38 8007FD08 0780063C */  lui        $a2, %hi(D_80070328 + 0xE)
/* 7AABA3C 8007FD0C 3603C624 */  addiu      $a2, $a2, %lo(D_80070328 + 0xE)
/* 7AABA40 8007FD10 0000C290 */  lbu        $v0, 0x0($a2)
/* 7AABA44 8007FD14 00000000 */  nop
/* 7AABA48 8007FD18 40100200 */  sll        $v0, $v0, 1
/* 7AABA4C 8007FD1C 0680013C */  lui        $at, %hi(D_80065920)
/* 7AABA50 8007FD20 21082200 */  addu       $at, $at, $v0
/* 7AABA54 8007FD24 20592284 */  lh         $v0, %lo(D_80065920)($at)
/* 7AABA58 8007FD28 21288000 */  addu       $a1, $a0, $zero
/* 7AABA5C 8007FD2C 80180200 */  sll        $v1, $v0, 2
/* 7AABA60 8007FD30 21186200 */  addu       $v1, $v1, $v0
/* 7AABA64 8007FD34 00110300 */  sll        $v0, $v1, 4
/* 7AABA68 8007FD38 23104300 */  subu       $v0, $v0, $v1
/* 7AABA6C 8007FD3C 43120200 */  sra        $v0, $v0, 9
/* 7AABA70 8007FD40 0C0042AE */  sw         $v0, 0xC($s2)
/* 7AABA74 8007FD44 0000C290 */  lbu        $v0, 0x0($a2)
/* 7AABA78 8007FD48 F2FFC624 */  addiu      $a2, $a2, -0xE
/* 7AABA7C 8007FD4C 40100200 */  sll        $v0, $v0, 1
/* 7AABA80 8007FD50 0680013C */  lui        $at, %hi(D_800658A0)
/* 7AABA84 8007FD54 21082200 */  addu       $at, $at, $v0
/* 7AABA88 8007FD58 A0582784 */  lh         $a3, %lo(D_800658A0)($at)
/* 7AABA8C 8007FD5C C8000224 */  addiu      $v0, $zero, 0xC8
/* 7AABA90 8007FD60 140042AE */  sw         $v0, 0x14($s2)
/* 7AABA94 8007FD64 80180700 */  sll        $v1, $a3, 2
/* 7AABA98 8007FD68 21186700 */  addu       $v1, $v1, $a3
/* 7AABA9C 8007FD6C 00110300 */  sll        $v0, $v1, 4
/* 7AABAA0 8007FD70 23104300 */  subu       $v0, $v0, $v1
/* 7AABAA4 8007FD74 43120200 */  sra        $v0, $v0, 9
/* 7AABAA8 8007FD78 653C010C */  jal        func_8004F194
/* 7AABAAC 8007FD7C 100042AE */   sw        $v0, 0x10($s2)
/* 7AABAB0 8007FD80 FFFF0224 */  addiu      $v0, $zero, -0x1
.Llevel_37_8007FD84:
/* 7AABAB4 8007FD84 1600A2A6 */  sh         $v0, 0x16($s5)
/* 7AABAB8 8007FD88 1000A0A2 */  sb         $zero, 0x10($s5)
/* 7AABABC 8007FD8C 0780023C */  lui        $v0, %hi(D_80070328 + 0xE)
/* 7AABAC0 8007FD90 36034290 */  lbu        $v0, %lo(D_80070328 + 0xE)($v0)
/* 7AABAC4 8007FD94 0780033C */  lui        $v1, %hi(D_80070328 + 0x12)
/* 7AABAC8 8007FD98 3A036390 */  lbu        $v1, %lo(D_80070328 + 0x12)($v1)
/* 7AABACC 8007FD9C 00000000 */  nop
/* 7AABAD0 8007FDA0 21104300 */  addu       $v0, $v0, $v1
/* 7AABAD4 8007FDA4 1200A2A2 */  sb         $v0, 0x12($s5)
/* 7AABAD8 8007FDA8 0780033C */  lui        $v1, %hi(D_8006E044)
/* 7AABADC 8007FDAC 44E0638C */  lw         $v1, %lo(D_8006E044)($v1)
/* 7AABAE0 8007FDB0 07000224 */  addiu      $v0, $zero, 0x7
/* 7AABAE4 8007FDB4 0E006214 */  bne        $v1, $v0, .Llevel_37_8007FDF0
/* 7AABAE8 8007FDB8 04000324 */   addiu     $v1, $zero, 0x4
/* 7AABAEC 8007FDBC 0780023C */  lui        $v0, %hi(D_8006E03E)
/* 7AABAF0 8007FDC0 3EE04294 */  lhu        $v0, %lo(D_8006E03E)($v0)
/* 7AABAF4 8007FDC4 00000000 */  nop
/* 7AABAF8 8007FDC8 00140200 */  sll        $v0, $v0, 16
/* 7AABAFC 8007FDCC 03150200 */  sra        $v0, $v0, 20
/* 7AABB00 8007FDD0 23186200 */  subu       $v1, $v1, $v0
/* 7AABB04 8007FDD4 1100A3A2 */  sb         $v1, 0x11($s5)
/* 7AABB08 8007FDD8 0780023C */  lui        $v0, %hi(D_8006E040)
/* 7AABB0C 8007FDDC 40E04294 */  lhu        $v0, %lo(D_8006E040)($v0)
/* 7AABB10 8007FDE0 00000000 */  nop
/* 7AABB14 8007FDE4 02110200 */  srl        $v0, $v0, 4
/* 7AABB18 8007FDE8 83FF0108 */  j          .Llevel_37_8007FE0C
/* 7AABB1C 8007FDEC 1200A2A2 */   sb        $v0, 0x12($s5)
.Llevel_37_8007FDF0:
/* 7AABB20 8007FDF0 7000E292 */  lbu        $v0, 0x70($s7)
/* 7AABB24 8007FDF4 00000000 */  nop
/* 7AABB28 8007FDF8 03004010 */  beqz       $v0, .Llevel_37_8007FE08
/* 7AABB2C 8007FDFC 04000224 */   addiu     $v0, $zero, 0x4
/* 7AABB30 8007FE00 83FF0108 */  j          .Llevel_37_8007FE0C
/* 7AABB34 8007FE04 1100A2A2 */   sb        $v0, 0x11($s5)
.Llevel_37_8007FE08:
/* 7AABB38 8007FE08 1100A0A2 */  sb         $zero, 0x11($s5)
.Llevel_37_8007FE0C:
/* 7AABB3C 8007FE0C 1000A292 */  lbu        $v0, 0x10($s5)
/* 7AABB40 8007FE10 00000000 */  nop
/* 7AABB44 8007FE14 440042A2 */  sb         $v0, 0x44($s2)
/* 7AABB48 8007FE18 1100A292 */  lbu        $v0, 0x11($s5)
/* 7AABB4C 8007FE1C 00000000 */  nop
/* 7AABB50 8007FE20 450042A2 */  sb         $v0, 0x45($s2)
/* 7AABB54 8007FE24 1200A292 */  lbu        $v0, 0x12($s5)
/* 7AABB58 8007FE28 00000000 */  nop
/* 7AABB5C 8007FE2C 460042A2 */  sb         $v0, 0x46($s2)
/* 7AABB60 8007FE30 B4000224 */  addiu      $v0, $zero, 0xB4
/* 7AABB64 8007FE34 0800A2A6 */  sh         $v0, 0x8($s5)
/* 7AABB68 8007FE38 FFFF0224 */  addiu      $v0, $zero, -0x1
/* 7AABB6C 8007FE3C 0E00A2A6 */  sh         $v0, 0xE($s5)
/* 7AABB70 8007FE40 90010224 */  addiu      $v0, $zero, 0x190
/* 7AABB74 8007FE44 0A00A2A6 */  sh         $v0, 0xA($s5)
/* 7AABB78 8007FE48 7000E292 */  lbu        $v0, 0x70($s7)
/* 7AABB7C 8007FE4C 00000000 */  nop
/* 7AABB80 8007FE50 22004010 */  beqz       $v0, .Llevel_37_8007FEDC
/* 7AABB84 8007FE54 21300000 */   addu      $a2, $zero, $zero
/* 7AABB88 8007FE58 0C00038E */  lw         $v1, 0xC($s0)
/* 7AABB8C 8007FE5C 0C00448E */  lw         $a0, 0xC($s2)
/* 7AABB90 8007FE60 1000028E */  lw         $v0, 0x10($s0)
/* 7AABB94 8007FE64 1000458E */  lw         $a1, 0x10($s2)
/* 7AABB98 8007FE68 23206400 */  subu       $a0, $v1, $a0
/* 7AABB9C 8007FE6C 203A010C */  jal        func_8004E880
/* 7AABBA0 8007FE70 23284500 */   subu      $a1, $v0, $a1
/* 7AABBA4 8007FE74 46004592 */  lbu        $a1, 0x46($s2)
/* 7AABBA8 8007FE78 993C010C */  jal        func_8004F264
/* 7AABBAC 8007FE7C 21204000 */   addu      $a0, $v0, $zero
/* 7AABBB0 8007FE80 10004228 */  slti       $v0, $v0, 0x10
/* 7AABBB4 8007FE84 02004010 */  beqz       $v0, .Llevel_37_8007FE90
/* 7AABBB8 8007FE88 00000000 */   nop
/* 7AABBBC 8007FE8C 0E00A0A6 */  sh         $zero, 0xE($s5)
.Llevel_37_8007FE90:
/* 7AABBC0 8007FE90 3C004392 */  lbu        $v1, 0x3C($s2)
/* 7AABBC4 8007FE94 17000224 */  addiu      $v0, $zero, 0x17
/* 7AABBC8 8007FE98 480042A2 */  sb         $v0, 0x48($s2)
/* 7AABBCC 8007FE9C 04000224 */  addiu      $v0, $zero, 0x4
/* 7AABBD0 8007FEA0 29006210 */  beq        $v1, $v0, .Llevel_37_8007FF48
/* 7AABBD4 8007FEA4 04000324 */   addiu     $v1, $zero, 0x4
/* 7AABBD8 8007FEA8 36004286 */  lh         $v0, 0x36($s2)
/* 7AABBDC 8007FEAC 00000000 */  nop
/* 7AABBE0 8007FEB0 80100200 */  sll        $v0, $v0, 2
/* 7AABBE4 8007FEB4 0780013C */  lui        $at, %hi(D_8006EE2C)
/* 7AABBE8 8007FEB8 21082200 */  addu       $at, $at, $v0
/* 7AABBEC 8007FEBC 2CEE228C */  lw         $v0, %lo(D_8006EE2C)($at)
/* 7AABBF0 8007FEC0 00000000 */  nop
/* 7AABBF4 8007FEC4 4C00428C */  lw         $v0, 0x4C($v0)
/* 7AABBF8 8007FEC8 0780013C */  lui        $at, %hi(D_8006C770)
/* 7AABBFC 8007FECC 70C720AC */  sw         $zero, %lo(D_8006C770)($at)
/* 7AABC00 8007FED0 00004290 */  lbu        $v0, 0x0($v0)
/* 7AABC04 8007FED4 C9FF0108 */  j          .Llevel_37_8007FF24
/* 7AABC08 8007FED8 3C0043A2 */   sb        $v1, 0x3C($s2)
.Llevel_37_8007FEDC:
/* 7AABC0C 8007FEDC 3C004392 */  lbu        $v1, 0x3C($s2)
/* 7AABC10 8007FEE0 16000224 */  addiu      $v0, $zero, 0x16
/* 7AABC14 8007FEE4 480042A2 */  sb         $v0, 0x48($s2)
/* 7AABC18 8007FEE8 03000224 */  addiu      $v0, $zero, 0x3
/* 7AABC1C 8007FEEC 16006210 */  beq        $v1, $v0, .Llevel_37_8007FF48
/* 7AABC20 8007FEF0 03000324 */   addiu     $v1, $zero, 0x3
/* 7AABC24 8007FEF4 36004286 */  lh         $v0, 0x36($s2)
/* 7AABC28 8007FEF8 00000000 */  nop
/* 7AABC2C 8007FEFC 80100200 */  sll        $v0, $v0, 2
/* 7AABC30 8007FF00 0780013C */  lui        $at, %hi(D_8006EE2C)
/* 7AABC34 8007FF04 21082200 */  addu       $at, $at, $v0
/* 7AABC38 8007FF08 2CEE228C */  lw         $v0, %lo(D_8006EE2C)($at)
/* 7AABC3C 8007FF0C 00000000 */  nop
/* 7AABC40 8007FF10 4800428C */  lw         $v0, 0x48($v0)
/* 7AABC44 8007FF14 0780013C */  lui        $at, %hi(D_8006C770)
/* 7AABC48 8007FF18 70C720AC */  sw         $zero, %lo(D_8006C770)($at)
/* 7AABC4C 8007FF1C 00004290 */  lbu        $v0, 0x0($v0)
/* 7AABC50 8007FF20 3C0043A2 */  sb         $v1, 0x3C($s2)
.Llevel_37_8007FF24:
/* 7AABC54 8007FF24 3D0043A2 */  sb         $v1, 0x3D($s2)
/* 7AABC58 8007FF28 01000324 */  addiu      $v1, $zero, 0x1
/* 7AABC5C 8007FF2C 3E0040A2 */  sb         $zero, 0x3E($s2)
/* 7AABC60 8007FF30 3F0043A2 */  sb         $v1, 0x3F($s2)
/* 7AABC64 8007FF34 0200422C */  sltiu      $v0, $v0, 0x2
/* 7AABC68 8007FF38 01004238 */  xori       $v0, $v0, 0x1
/* 7AABC6C 8007FF3C 23100200 */  negu       $v0, $v0
/* 7AABC70 8007FF40 30004230 */  andi       $v0, $v0, 0x30
/* 7AABC74 8007FF44 400042A2 */  sb         $v0, 0x40($s2)
.Llevel_37_8007FF48:
/* 7AABC78 8007FF48 01000324 */  addiu      $v1, $zero, 0x1
/* 7AABC7C 8007FF4C 50000224 */  addiu      $v0, $zero, 0x50
/* 7AABC80 8007FF50 410043A2 */  sb         $v1, 0x41($s2)
/* 7AABC84 8007FF54 4C0042A2 */  sb         $v0, 0x4C($s2)
/* 7AABC88 8007FF58 4D0043A2 */  sb         $v1, 0x4D($s2)
.L8007FF5C_:
/* 7AABC8C 8007FF5C 1600A586 */  lh         $a1, 0x16($s5)
/* 7AABC90 8007FF60 F0EF000C */  jal        func_8003BFC0
/* 7AABC94 8007FF64 21204002 */   addu      $a0, $s2, $zero
/* 7AABC98 8007FF68 05004014 */  bnez       $v0, .Llevel_37_8007FF80
/* 7AABC9C 8007FF6C 21204002 */   addu      $a0, $s2, $zero
/* 7AABCA0 8007FF70 03000524 */  addiu      $a1, $zero, 0x3
/* 7AABCA4 8007FF74 AFEE000C */  jal        func_8003BABC
/* 7AABCA8 8007FF78 04000624 */   addiu     $a2, $zero, 0x4
/* 7AABCAC 8007FF7C 1600A2A6 */  sh         $v0, 0x16($s5)
.Llevel_37_8007FF80:
/* 7AABCB0 8007FF80 48004392 */  lbu        $v1, 0x48($s2)
/* 7AABCB4 8007FF84 17000224 */  addiu      $v0, $zero, 0x17
/* 7AABCB8 8007FF88 79006214 */  bne        $v1, $v0, .Llevel_37_80080170
/* 7AABCBC 8007FF8C 1000A426 */   addiu     $a0, $s5, 0x10
/* 7AABCC0 8007FF90 4000B027 */  addiu      $s0, $sp, 0x40
/* 7AABCC4 8007FF94 21280002 */  addu       $a1, $s0, $zero
/* 7AABCC8 8007FF98 0600A286 */  lh         $v0, 0x6($s5)
/* 7AABCCC 8007FF9C 21300000 */  addu       $a2, $zero, $zero
/* 7AABCD0 8007FFA0 40180200 */  sll        $v1, $v0, 1
/* 7AABCD4 8007FFA4 10004224 */  addiu      $v0, $v0, 0x10
/* 7AABCD8 8007FFA8 0680013C */  lui        $at, %hi(D_80065920)
/* 7AABCDC 8007FFAC 21082300 */  addu       $at, $at, $v1
/* 7AABCE0 8007FFB0 20592784 */  lh         $a3, %lo(D_80065920)($at)
/* 7AABCE4 8007FFB4 0680013C */  lui        $at, %hi(D_800658A0)
/* 7AABCE8 8007FFB8 21082300 */  addu       $at, $at, $v1
/* 7AABCEC 8007FFBC A0582384 */  lh         $v1, %lo(D_800658A0)($at)
/* 7AABCF0 8007FFC0 FF004230 */  andi       $v0, $v0, 0xFF
/* 7AABCF4 8007FFC4 0600A2A6 */  sh         $v0, 0x6($s5)
/* 7AABCF8 8007FFC8 90010224 */  addiu      $v0, $zero, 0x190
/* 7AABCFC 8007FFCC 3000A2AF */  sw         $v0, 0x30($sp)
/* 7AABD00 8007FFD0 40100700 */  sll        $v0, $a3, 1
/* 7AABD04 8007FFD4 21104700 */  addu       $v0, $v0, $a3
/* 7AABD08 8007FFD8 C0100200 */  sll        $v0, $v0, 3
/* 7AABD0C 8007FFDC 21104700 */  addu       $v0, $v0, $a3
/* 7AABD10 8007FFE0 C3120200 */  sra        $v0, $v0, 11
/* 7AABD14 8007FFE4 3400A2AF */  sw         $v0, 0x34($sp)
/* 7AABD18 8007FFE8 40100300 */  sll        $v0, $v1, 1
/* 7AABD1C 8007FFEC 21104300 */  addu       $v0, $v0, $v1
/* 7AABD20 8007FFF0 C0100200 */  sll        $v0, $v0, 3
/* 7AABD24 8007FFF4 21104300 */  addu       $v0, $v0, $v1
/* 7AABD28 8007FFF8 C3120200 */  sra        $v0, $v0, 11
/* 7AABD2C 8007FFFC A43A010C */  jal        func_8004EA90
/* 7AABD30 80080000 3800A2AF */   sw        $v0, 0x38($sp)
/* 7AABD34 80080004 21200002 */  addu       $a0, $s0, $zero
/* 7AABD38 80080008 3000B027 */  addiu      $s0, $sp, 0x30
/* 7AABD3C 8008000C 21280002 */  addu       $a1, $s0, $zero
/* 7AABD40 80080010 5B3B010C */  jal        func_8004ED6C
/* 7AABD44 80080014 21300002 */   addu      $a2, $s0, $zero
/* 7AABD48 80080018 3000A28F */  lw         $v0, 0x30($sp)
/* 7AABD4C 8008001C 00000000 */  nop
/* 7AABD50 80080020 0000A2A6 */  sh         $v0, 0x0($s5)
/* 7AABD54 80080024 3400A28F */  lw         $v0, 0x34($sp)
/* 7AABD58 80080028 21200002 */  addu       $a0, $s0, $zero
/* 7AABD5C 8008002C 0200A2A6 */  sh         $v0, 0x2($s5)
/* 7AABD60 80080030 3800A28F */  lw         $v0, 0x38($sp)
/* 7AABD64 80080034 21280000 */  addu       $a1, $zero, $zero
/* 7AABD68 80080038 7A3B010C */  jal        func_8004EDE8
/* 7AABD6C 8008003C 0400A2A6 */   sh        $v0, 0x4($s5)
/* 7AABD70 80080040 21204000 */  addu       $a0, $v0, $zero
/* 7AABD74 80080044 3800A58F */  lw         $a1, 0x38($sp)
/* 7AABD78 80080048 203A010C */  jal        func_8004E880
/* 7AABD7C 8008004C 21300000 */   addu      $a2, $zero, $zero
/* 7AABD80 80080050 450042A2 */  sb         $v0, 0x45($s2)
/* 7AABD84 80080054 3000A48F */  lw         $a0, 0x30($sp)
/* 7AABD88 80080058 3400A58F */  lw         $a1, 0x34($sp)
/* 7AABD8C 8008005C 203A010C */  jal        func_8004E880
/* 7AABD90 80080060 21300000 */   addu      $a2, $zero, $zero
/* 7AABD94 80080064 460042A2 */  sb         $v0, 0x46($s2)
/* 7AABD98 80080068 0E00A386 */  lh         $v1, 0xE($s5)
/* 7AABD9C 8008006C FFFF0224 */  addiu      $v0, $zero, -0x1
/* 7AABDA0 80080070 66006210 */  beq        $v1, $v0, .Llevel_37_8008020C
/* 7AABDA4 80080074 5800B027 */   addiu     $s0, $sp, 0x58
/* 7AABDA8 80080078 21200002 */  addu       $a0, $s0, $zero
/* 7AABDAC 8008007C 40100300 */  sll        $v0, $v1, 1
/* 7AABDB0 80080080 21104300 */  addu       $v0, $v0, $v1
/* 7AABDB4 80080084 80100200 */  sll        $v0, $v0, 2
/* 7AABDB8 80080088 23104300 */  subu       $v0, $v0, $v1
/* 7AABDBC 8008008C 0780053C */  lui        $a1, %hi(D_8006C550)
/* 7AABDC0 80080090 50C5A58C */  lw         $a1, %lo(D_8006C550)($a1)
/* 7AABDC4 80080094 C0100200 */  sll        $v0, $v0, 3
/* 7AABDC8 80080098 2128A200 */  addu       $a1, $a1, $v0
/* 7AABDCC 8008009C 5E3C010C */  jal        func_8004F178
/* 7AABDD0 800800A0 0C00A524 */   addiu     $a1, $a1, 0xC
/* 7AABDD4 800800A4 21300000 */  addu       $a2, $zero, $zero
/* 7AABDD8 800800A8 6000A28F */  lw         $v0, 0x60($sp)
/* 7AABDDC 800800AC 5800A38F */  lw         $v1, 0x58($sp)
/* 7AABDE0 800800B0 3A074224 */  addiu      $v0, $v0, 0x73A
/* 7AABDE4 800800B4 6000A2AF */  sw         $v0, 0x60($sp)
/* 7AABDE8 800800B8 0C00448E */  lw         $a0, 0xC($s2)
/* 7AABDEC 800800BC 5C00A28F */  lw         $v0, 0x5C($sp)
/* 7AABDF0 800800C0 1000458E */  lw         $a1, 0x10($s2)
/* 7AABDF4 800800C4 23206400 */  subu       $a0, $v1, $a0
/* 7AABDF8 800800C8 203A010C */  jal        func_8004E880
/* 7AABDFC 800800CC 23284500 */   subu      $a1, $v0, $a1
/* 7AABE00 800800D0 1200A492 */  lbu        $a0, 0x12($s5)
/* 7AABE04 800800D4 4FD8000C */  jal        func_8003613C
/* 7AABE08 800800D8 21284000 */   addu      $a1, $v0, $zero
/* 7AABE0C 800800DC 21184000 */  addu       $v1, $v0, $zero
/* 7AABE10 800800E0 03006228 */  slti       $v0, $v1, 0x3
/* 7AABE14 800800E4 03004014 */  bnez       $v0, .Llevel_37_800800F4
/* 7AABE18 800800E8 FEFF6228 */   slti      $v0, $v1, -0x2
/* 7AABE1C 800800EC 02000324 */  addiu      $v1, $zero, 0x2
/* 7AABE20 800800F0 FEFF6228 */  slti       $v0, $v1, -0x2
.Llevel_37_800800F4:
/* 7AABE24 800800F4 02004010 */  beqz       $v0, .Llevel_37_80080100
/* 7AABE28 800800F8 0C004426 */   addiu     $a0, $s2, 0xC
/* 7AABE2C 800800FC FEFF0324 */  addiu      $v1, $zero, -0x2
.Llevel_37_80080100:
/* 7AABE30 80080100 1200A292 */  lbu        $v0, 0x12($s5)
/* 7AABE34 80080104 21280002 */  addu       $a1, $s0, $zero
/* 7AABE38 80080108 21104300 */  addu       $v0, $v0, $v1
/* 7AABE3C 8008010C CD3C010C */  jal        func_8004F334
/* 7AABE40 80080110 1200A2A2 */   sb        $v0, 0x12($s5)
/* 7AABE44 80080114 21204000 */  addu       $a0, $v0, $zero
/* 7AABE48 80080118 6000A28F */  lw         $v0, 0x60($sp)
/* 7AABE4C 8008011C 1400458E */  lw         $a1, 0x14($s2)
/* 7AABE50 80080120 21300000 */  addu       $a2, $zero, $zero
/* 7AABE54 80080124 203A010C */  jal        func_8004E880
/* 7AABE58 80080128 23284500 */   subu      $a1, $v0, $a1
/* 7AABE5C 8008012C 1100A492 */  lbu        $a0, 0x11($s5)
/* 7AABE60 80080130 4FD8000C */  jal        func_8003613C
/* 7AABE64 80080134 21284000 */   addu      $a1, $v0, $zero
/* 7AABE68 80080138 21184000 */  addu       $v1, $v0, $zero
/* 7AABE6C 8008013C 03006228 */  slti       $v0, $v1, 0x3
/* 7AABE70 80080140 03004014 */  bnez       $v0, .Llevel_37_80080150
/* 7AABE74 80080144 FEFF6228 */   slti      $v0, $v1, -0x2
/* 7AABE78 80080148 02000324 */  addiu      $v1, $zero, 0x2
/* 7AABE7C 8008014C FEFF6228 */  slti       $v0, $v1, -0x2
.Llevel_37_80080150:
/* 7AABE80 80080150 02004010 */  beqz       $v0, .Llevel_37_8008015C
/* 7AABE84 80080154 00000000 */   nop
/* 7AABE88 80080158 FEFF0324 */  addiu      $v1, $zero, -0x2
.Llevel_37_8008015C:
/* 7AABE8C 8008015C 1100A292 */  lbu        $v0, 0x11($s5)
/* 7AABE90 80080160 00000000 */  nop
/* 7AABE94 80080164 21104300 */  addu       $v0, $v0, $v1
/* 7AABE98 80080168 83000208 */  j          .Llevel_37_8008020C
/* 7AABE9C 8008016C 1100A2A2 */   sb        $v0, 0x11($s5)
.Llevel_37_80080170:
/* 7AABEA0 80080170 6800B027 */  addiu      $s0, $sp, 0x68
/* 7AABEA4 80080174 21280002 */  addu       $a1, $s0, $zero
/* 7AABEA8 80080178 0600A286 */  lh         $v0, 0x6($s5)
/* 7AABEAC 8008017C 21300000 */  addu       $a2, $zero, $zero
/* 7AABEB0 80080180 40180200 */  sll        $v1, $v0, 1
/* 7AABEB4 80080184 0E004224 */  addiu      $v0, $v0, 0xE
/* 7AABEB8 80080188 0680013C */  lui        $at, %hi(D_80065920)
/* 7AABEBC 8008018C 21082300 */  addu       $at, $at, $v1
/* 7AABEC0 80080190 20592384 */  lh         $v1, %lo(D_80065920)($at)
/* 7AABEC4 80080194 FF004230 */  andi       $v0, $v0, 0xFF
/* 7AABEC8 80080198 0600A2A6 */  sh         $v0, 0x6($s5)
/* 7AABECC 8008019C 90010224 */  addiu      $v0, $zero, 0x190
/* 7AABED0 800801A0 3000A2AF */  sw         $v0, 0x30($sp)
/* 7AABED4 800801A4 3800A0AF */  sw         $zero, 0x38($sp)
/* 7AABED8 800801A8 40100300 */  sll        $v0, $v1, 1
/* 7AABEDC 800801AC 21104300 */  addu       $v0, $v0, $v1
/* 7AABEE0 800801B0 C0100200 */  sll        $v0, $v0, 3
/* 7AABEE4 800801B4 21104300 */  addu       $v0, $v0, $v1
/* 7AABEE8 800801B8 C3120200 */  sra        $v0, $v0, 11
/* 7AABEEC 800801BC A43A010C */  jal        func_8004EA90
/* 7AABEF0 800801C0 3400A2AF */   sw        $v0, 0x34($sp)
/* 7AABEF4 800801C4 21200002 */  addu       $a0, $s0, $zero
/* 7AABEF8 800801C8 3000A527 */  addiu      $a1, $sp, 0x30
/* 7AABEFC 800801CC 5B3B010C */  jal        func_8004ED6C
/* 7AABF00 800801D0 2130A000 */   addu      $a2, $a1, $zero
/* 7AABF04 800801D4 3000A28F */  lw         $v0, 0x30($sp)
/* 7AABF08 800801D8 00000000 */  nop
/* 7AABF0C 800801DC 0000A2A6 */  sh         $v0, 0x0($s5)
/* 7AABF10 800801E0 3400A28F */  lw         $v0, 0x34($sp)
/* 7AABF14 800801E4 00000000 */  nop
/* 7AABF18 800801E8 0200A2A6 */  sh         $v0, 0x2($s5)
/* 7AABF1C 800801EC 3800A28F */  lw         $v0, 0x38($sp)
/* 7AABF20 800801F0 00000000 */  nop
/* 7AABF24 800801F4 0400A2A6 */  sh         $v0, 0x4($s5)
/* 7AABF28 800801F8 3000A48F */  lw         $a0, 0x30($sp)
/* 7AABF2C 800801FC 3400A58F */  lw         $a1, 0x34($sp)
/* 7AABF30 80080200 203A010C */  jal        func_8004E880
/* 7AABF34 80080204 21300000 */   addu      $a2, $zero, $zero
/* 7AABF38 80080208 460042A2 */  sb         $v0, 0x46($s2)
.Llevel_37_8008020C:
/* 7AABF3C 8008020C 2000A427 */  addiu      $a0, $sp, 0x20
/* 7AABF40 80080210 0C005126 */  addiu      $s1, $s2, 0xC
/* 7AABF44 80080214 5E3C010C */  jal        func_8004F178
/* 7AABF48 80080218 21282002 */   addu      $a1, $s1, $zero
/* 7AABF4C 8008021C 21202002 */  addu       $a0, $s1, $zero
/* 7AABF50 80080220 21282002 */  addu       $a1, $s1, $zero
/* 7AABF54 80080224 3000B027 */  addiu      $s0, $sp, 0x30
/* 7AABF58 80080228 653C010C */  jal        func_8004F194
/* 7AABF5C 8008022C 21300002 */   addu      $a2, $s0, $zero
/* 7AABF60 80080230 21200002 */  addu       $a0, $s0, $zero
/* 7AABF64 80080234 7A3B010C */  jal        func_8004EDE8
/* 7AABF68 80080238 01000524 */   addiu     $a1, $zero, 0x1
/* 7AABF6C 8008023C 2C011424 */  addiu      $s4, $zero, 0x12C
/* 7AABF70 80080240 08004324 */  addiu      $v1, $v0, 0x8
/* 7AABF74 80080244 2A108302 */  slt        $v0, $s4, $v1
/* 7AABF78 80080248 02004010 */  beqz       $v0, .Llevel_37_80080254
/* 7AABF7C 8008024C 00000000 */   nop
/* 7AABF80 80080250 21A06000 */  addu       $s4, $v1, $zero
.Llevel_37_80080254:
/* 7AABF84 80080254 48004392 */  lbu        $v1, 0x48($s2)
/* 7AABF88 80080258 17000224 */  addiu      $v0, $zero, 0x17
/* 7AABF8C 8008025C 0A006214 */  bne        $v1, $v0, .Llevel_37_80080288
/* 7AABF90 80080260 21200000 */   addu      $a0, $zero, $zero
/* 7AABF94 80080264 F7D8000C */  jal        func_800363DC
/* 7AABF98 80080268 07000524 */   addiu     $a1, $zero, 0x7
/* 7AABF9C 8008026C 21200000 */  addu       $a0, $zero, $zero
/* 7AABFA0 80080270 07000524 */  addiu      $a1, $zero, 0x7
/* 7AABFA4 80080274 F7D8000C */  jal        func_800363DC
/* 7AABFA8 80080278 8000A2AF */   sw        $v0, 0x80($sp)
/* 7AABFAC 8008027C 01000424 */  addiu      $a0, $zero, 0x1
/* 7AABFB0 80080280 AA000208 */  j          .Llevel_37_800802A8
/* 7AABFB4 80080284 3A000524 */   addiu     $a1, $zero, 0x3A
.Llevel_37_80080288:
/* 7AABFB8 80080288 F7D8000C */  jal        func_800363DC
/* 7AABFBC 8008028C 07000524 */   addiu     $a1, $zero, 0x7
/* 7AABFC0 80080290 21200000 */  addu       $a0, $zero, $zero
/* 7AABFC4 80080294 07000524 */  addiu      $a1, $zero, 0x7
/* 7AABFC8 80080298 F7D8000C */  jal        func_800363DC
/* 7AABFCC 8008029C 8000A2AF */   sw        $v0, 0x80($sp)
/* 7AABFD0 800802A0 01000424 */  addiu      $a0, $zero, 0x1
/* 7AABFD4 800802A4 0D000524 */  addiu      $a1, $zero, 0xD
.Llevel_37_800802A8:
/* 7AABFD8 800802A8 21302002 */  addu       $a2, $s1, $zero
/* 7AABFDC 800802AC 0780033C */  lui        $v1, %hi(SpawnParticle)
/* 7AABFE0 800802B0 E442638C */  lw         $v1, %lo(SpawnParticle)($v1)
/* 7AABFE4 800802B4 8000A727 */  addiu      $a3, $sp, 0x80
/* 7AABFE8 800802B8 8400A2AF */  sw         $v0, 0x84($sp)
/* 7AABFEC 800802BC 0F000224 */  addiu      $v0, $zero, 0xF
/* 7AABFF0 800802C0 09F86000 */  jalr       $v1
/* 7AABFF4 800802C4 8800A2AF */   sw        $v0, 0x88($sp)
/* 7AABFF8 800802C8 0800A426 */  addiu      $a0, $s5, 0x8
/* 7AABFFC 800802CC 69D6000C */  jal        func_800359A4
/* 7AAC000 800802D0 02000524 */   addiu     $a1, $zero, 0x2
/* 7AAC004 800802D4 02004010 */  beqz       $v0, .Llevel_37_800802E0
/* 7AAC008 800802D8 18000224 */   addiu     $v0, $zero, 0x18
/* 7AAC00C 800802DC 480042A2 */  sb         $v0, 0x48($s2)
.Llevel_37_800802E0:
/* 7AAC010 800802E0 0C00428E */  lw         $v0, 0xC($s2)
/* 7AAC014 800802E4 00000000 */  nop
/* 7AAC018 800802E8 00044228 */  slti       $v0, $v0, 0x400
/* 7AAC01C 800802EC 0B004014 */  bnez       $v0, .Llevel_37_8008031C
/* 7AAC020 800802F0 18000224 */   addiu     $v0, $zero, 0x18
/* 7AAC024 800802F4 1000428E */  lw         $v0, 0x10($s2)
/* 7AAC028 800802F8 00000000 */  nop
/* 7AAC02C 800802FC 00044228 */  slti       $v0, $v0, 0x400
/* 7AAC030 80080300 06004014 */  bnez       $v0, .Llevel_37_8008031C
/* 7AAC034 80080304 18000224 */   addiu     $v0, $zero, 0x18
/* 7AAC038 80080308 1400428E */  lw         $v0, 0x14($s2)
/* 7AAC03C 8008030C 00000000 */  nop
/* 7AAC040 80080310 00044228 */  slti       $v0, $v0, 0x400
/* 7AAC044 80080314 02004010 */  beqz       $v0, .Llevel_37_80080320
/* 7AAC048 80080318 18000224 */   addiu     $v0, $zero, 0x18
.Llevel_37_8008031C:
/* 7AAC04C 8008031C 480042A2 */  sb         $v0, 0x48($s2)
.Llevel_37_80080320:
/* 7AAC050 80080320 2000A427 */  addiu      $a0, $sp, 0x20
/* 7AAC054 80080324 0C005026 */  addiu      $s0, $s2, 0xC
/* 7AAC058 80080328 DA60000C */  jal        func_80018368
/* 7AAC05C 8008032C 21280002 */   addu      $a1, $s0, $zero
/* 7AAC060 80080330 06004010 */  beqz       $v0, .Llevel_37_8008034C
/* 7AAC064 80080334 21200002 */   addu      $a0, $s0, $zero
/* 7AAC068 80080338 21280002 */  addu       $a1, $s0, $zero
/* 7AAC06C 8008033C 723C010C */  jal        func_8004F1C8
/* 7AAC070 80080340 3000A627 */   addiu     $a2, $sp, 0x30
/* 7AAC074 80080344 18000224 */  addiu      $v0, $zero, 0x18
/* 7AAC078 80080348 480042A2 */  sb         $v0, 0x48($s2)
.Llevel_37_8008034C:
/* 7AAC07C 8008034C 21200002 */  addu       $a0, $s0, $zero
/* 7AAC080 80080350 2C010524 */  addiu      $a1, $zero, 0x12C
/* 7AAC084 80080354 21300000 */  addu       $a2, $zero, $zero
/* 7AAC088 80080358 21380000 */  addu       $a3, $zero, $zero
/* 7AAC08C 8008035C 1000023C */  lui        $v0, (0x100000 >> 16)
/* 7AAC090 80080360 1000A2AF */  sw         $v0, 0x10($sp)
/* 7AAC094 80080364 8C6E000C */  jal        func_8001BA30
/* 7AAC098 80080368 1400B2AF */   sw        $s2, 0x14($sp)
/* 7AAC09C 8008036C 21804000 */  addu       $s0, $v0, $zero
/* 7AAC0A0 80080370 0E000012 */  beqz       $s0, .Llevel_37_800803AC
/* 7AAC0A4 80080374 0C004426 */   addiu     $a0, $s2, 0xC
/* 7AAC0A8 80080378 0000A486 */  lh         $a0, 0x0($s5)
/* 7AAC0AC 8008037C 0200A586 */  lh         $a1, 0x2($s5)
/* 7AAC0B0 80080380 203A010C */  jal        func_8004E880
/* 7AAC0B4 80080384 21300000 */   addu      $a2, $zero, $zero
/* 7AAC0B8 80080388 510002A2 */  sb         $v0, 0x51($s0)
/* 7AAC0BC 8008038C FF004230 */  andi       $v0, $v0, 0xFF
/* 7AAC0C0 80080390 04004014 */  bnez       $v0, .Llevel_37_800803A4
/* 7AAC0C4 80080394 18000224 */   addiu     $v0, $zero, 0x18
/* 7AAC0C8 80080398 01000224 */  addiu      $v0, $zero, 0x1
/* 7AAC0CC 8008039C 510002A2 */  sb         $v0, 0x51($s0)
/* 7AAC0D0 800803A0 18000224 */  addiu      $v0, $zero, 0x18
.Llevel_37_800803A4:
/* 7AAC0D4 800803A4 480042A2 */  sb         $v0, 0x48($s2)
/* 7AAC0D8 800803A8 0C004426 */  addiu      $a0, $s2, 0xC
.Llevel_37_800803AC:
/* 7AAC0DC 800803AC 6564000C */  jal        func_80019194
/* 7AAC0E0 800803B0 21288002 */   addu      $a1, $s4, $zero
/* 7AAC0E4 800803B4 0A024010 */  beqz       $v0, .Llevel_37_80080BE0
/* 7AAC0E8 800803B8 18000224 */   addiu     $v0, $zero, 0x18
/* 7AAC0EC 800803BC F8020208 */  j          .Llevel_37_80080BE0
/* 7AAC0F0 800803C0 480042A2 */   sb        $v0, 0x48($s2)
.L800803C4_:
/* 7AAC0F4 800803C4 21A00000 */  addu       $s4, $zero, $zero
/* 7AAC0F8 800803C8 02001624 */  addiu      $s6, $zero, 0x2
/* 7AAC0FC 800803CC 40981400 */  sll        $s3, $s4, 1
.Llevel_37_800803D0:
/* 7AAC100 800803D0 B800E28E */  lw         $v0, 0xB8($s7)
/* 7AAC104 800803D4 46004592 */  lbu        $a1, 0x46($s2)
/* 7AAC108 800803D8 21106202 */  addu       $v0, $s3, $v0
/* 7AAC10C 800803DC 00004490 */  lbu        $a0, 0x0($v0)
/* 7AAC110 800803E0 993C010C */  jal        func_8004F264
/* 7AAC114 800803E4 00000000 */   nop
/* 7AAC118 800803E8 3C004228 */  slti       $v0, $v0, 0x3C
/* 7AAC11C 800803EC 3A004010 */  beqz       $v0, .Llevel_37_800804D8
/* 7AAC120 800803F0 69010424 */   addiu     $a0, $zero, 0x169
/* 7AAC124 800803F4 0780023C */  lui        $v0, %hi(SpawnMoby)
/* 7AAC128 800803F8 E042428C */  lw         $v0, %lo(SpawnMoby)($v0)
/* 7AAC12C 800803FC 00000000 */  nop
/* 7AAC130 80080400 09F84000 */  jalr       $v0
/* 7AAC134 80080404 21284002 */   addu      $a1, $s2, $zero
/* 7AAC138 80080408 21804000 */  addu       $s0, $v0, $zero
/* 7AAC13C 8008040C 32000012 */  beqz       $s0, .Llevel_37_800804D8
/* 7AAC140 80080410 00000000 */   nop
/* 7AAC144 80080414 3C000292 */  lbu        $v0, 0x3C($s0)
/* 7AAC148 80080418 0000118E */  lw         $s1, 0x0($s0)
/* 7AAC14C 8008041C 14005610 */  beq        $v0, $s6, .Llevel_37_80080470
/* 7AAC150 80080420 01000324 */   addiu     $v1, $zero, 0x1
/* 7AAC154 80080424 36000286 */  lh         $v0, 0x36($s0)
/* 7AAC158 80080428 420000A2 */  sb         $zero, 0x42($s0)
/* 7AAC15C 8008042C 80100200 */  sll        $v0, $v0, 2
/* 7AAC160 80080430 0780013C */  lui        $at, %hi(D_8006EE2C)
/* 7AAC164 80080434 21082200 */  addu       $at, $at, $v0
/* 7AAC168 80080438 2CEE228C */  lw         $v0, %lo(D_8006EE2C)($at)
/* 7AAC16C 8008043C 00000000 */  nop
/* 7AAC170 80080440 4400428C */  lw         $v0, 0x44($v0)
/* 7AAC174 80080444 00000000 */  nop
/* 7AAC178 80080448 00004290 */  lbu        $v0, 0x0($v0)
/* 7AAC17C 8008044C 3C0016A2 */  sb         $s6, 0x3C($s0)
/* 7AAC180 80080450 3D0016A2 */  sb         $s6, 0x3D($s0)
/* 7AAC184 80080454 3E0000A2 */  sb         $zero, 0x3E($s0)
/* 7AAC188 80080458 3F0003A2 */  sb         $v1, 0x3F($s0)
/* 7AAC18C 8008045C 0200422C */  sltiu      $v0, $v0, 0x2
/* 7AAC190 80080460 01004238 */  xori       $v0, $v0, 0x1
/* 7AAC194 80080464 23100200 */  negu       $v0, $v0
/* 7AAC198 80080468 30004230 */  andi       $v0, $v0, 0x30
/* 7AAC19C 8008046C 400002A2 */  sb         $v0, 0x40($s0)
.Llevel_37_80080470:
/* 7AAC1A0 80080470 0C000426 */  addiu      $a0, $s0, 0xC
/* 7AAC1A4 80080474 07000524 */  addiu      $a1, $zero, 0x7
/* 7AAC1A8 80080478 0A000624 */  addiu      $a2, $zero, 0xA
/* 7AAC1AC 8008047C 4000073C */  lui        $a3, (0x40E080 >> 16)
/* 7AAC1B0 80080480 1142010C */  jal        func_80050844
/* 7AAC1B4 80080484 80E0E734 */   ori       $a3, $a3, (0x40E080 & 0xFFFF)
/* 7AAC1B8 80080488 080022AE */  sw         $v0, 0x8($s1)
/* 7AAC1BC 8008048C B800E28E */  lw         $v0, 0xB8($s7)
/* 7AAC1C0 80080490 00000000 */  nop
/* 7AAC1C4 80080494 21106202 */  addu       $v0, $s3, $v0
/* 7AAC1C8 80080498 00004290 */  lbu        $v0, 0x0($v0)
/* 7AAC1CC 8008049C 00000000 */  nop
/* 7AAC1D0 800804A0 80004224 */  addiu      $v0, $v0, 0x80
/* 7AAC1D4 800804A4 010022A2 */  sb         $v0, 0x1($s1)
/* 7AAC1D8 800804A8 B800E28E */  lw         $v0, 0xB8($s7)
/* 7AAC1DC 800804AC 00000000 */  nop
/* 7AAC1E0 800804B0 21106202 */  addu       $v0, $s3, $v0
/* 7AAC1E4 800804B4 01004390 */  lbu        $v1, 0x1($v0)
/* 7AAC1E8 800804B8 32000224 */  addiu      $v0, $zero, 0x32
/* 7AAC1EC 800804BC 040022AE */  sw         $v0, 0x4($s1)
/* 7AAC1F0 800804C0 2C010224 */  addiu      $v0, $zero, 0x12C
/* 7AAC1F4 800804C4 020022A6 */  sh         $v0, 0x2($s1)
/* 7AAC1F8 800804C8 9171010C */  jal        func_8005C644
/* 7AAC1FC 800804CC 000023A2 */   sb        $v1, 0x0($s1)
/* 7AAC200 800804D0 440002A2 */  sb         $v0, 0x44($s0)
/* 7AAC204 800804D4 480016A2 */  sb         $s6, 0x48($s0)
.Llevel_37_800804D8:
/* 7AAC208 800804D8 01009426 */  addiu      $s4, $s4, 0x1
/* 7AAC20C 800804DC 2000822A */  slti       $v0, $s4, 0x20
/* 7AAC210 800804E0 BBFF4014 */  bnez       $v0, .Llevel_37_800803D0
/* 7AAC214 800804E4 40981400 */   sll       $s3, $s4, 1
/* 7AAC218 800804E8 1600A586 */  lh         $a1, 0x16($s5)
/* 7AAC21C 800804EC F0EF000C */  jal        func_8003BFC0
/* 7AAC220 800804F0 21204002 */   addu      $a0, $s2, $zero
/* 7AAC224 800804F4 05004010 */  beqz       $v0, .Llevel_37_8008050C
/* 7AAC228 800804F8 FFFF0224 */   addiu     $v0, $zero, -0x1
/* 7AAC22C 800804FC 1600A486 */  lh         $a0, 0x16($s5)
/* 7AAC230 80080500 9CEF000C */  jal        func_8003BE70
/* 7AAC234 80080504 00000000 */   nop
/* 7AAC238 80080508 FFFF0224 */  addiu      $v0, $zero, -0x1
.Llevel_37_8008050C:
/* 7AAC23C 8008050C 1600A2A6 */  sh         $v0, 0x16($s5)
/* 7AAC240 80080510 21204002 */  addu       $a0, $s2, $zero
/* 7AAC244 80080514 02000524 */  addiu      $a1, $zero, 0x2
/* 7AAC248 80080518 AFEE000C */  jal        func_8003BABC
/* 7AAC24C 8008051C 21300000 */   addu      $a2, $zero, $zero
/* 7AAC250 80080520 F4020208 */  j          .Llevel_37_80080BD0
/* 7AAC254 80080524 00000000 */   nop
.L80080528_:
/* 7AAC258 80080528 1000628E */  lw         $v0, 0x10($s3)
/* 7AAC25C 8008052C 00000000 */  nop
/* 7AAC260 80080530 F4014224 */  addiu      $v0, $v0, 0x1F4
/* 7AAC264 80080534 100062AE */  sw         $v0, 0x10($s3)
/* 7AAC268 80080538 DC054228 */  slti       $v0, $v0, 0x5DC
/* 7AAC26C 8008053C 02004010 */  beqz       $v0, .Llevel_37_80080548
/* 7AAC270 80080540 DC050224 */   addiu     $v0, $zero, 0x5DC
/* 7AAC274 80080544 100062AE */  sw         $v0, 0x10($s3)
.Llevel_37_80080548:
/* 7AAC278 80080548 1000628E */  lw         $v0, 0x10($s3)
/* 7AAC27C 8008054C 00000000 */  nop
/* 7AAC280 80080550 01704228 */  slti       $v0, $v0, 0x7001
/* 7AAC284 80080554 9E014010 */  beqz       $v0, .Llevel_37_80080BD0
/* 7AAC288 80080558 00000000 */   nop
/* 7AAC28C 8008055C 0780113C */  lui        $s1, %hi(D_8006E788)
/* 7AAC290 80080560 88E73126 */  addiu      $s1, $s1, %lo(D_8006E788)
/* 7AAC294 80080564 0000308E */  lw         $s0, 0x0($s1)
/* 7AAC298 80080568 00000000 */  nop
/* 7AAC29C 8008056C 9C010012 */  beqz       $s0, .Llevel_37_80080BE0
/* 7AAC2A0 80080570 04003126 */   addiu     $s1, $s1, 0x4
.Llevel_37_80080574:
/* 7AAC2A4 80080574 36000386 */  lh         $v1, 0x36($s0)
/* 7AAC2A8 80080578 9F010224 */  addiu      $v0, $zero, 0x19F
/* 7AAC2AC 8008057C 16006210 */  beq        $v1, $v0, .Llevel_37_800805D8
/* 7AAC2B0 80080580 0C004426 */   addiu     $a0, $s2, 0xC
/* 7AAC2B4 80080584 CD3C010C */  jal        func_8004F334
/* 7AAC2B8 80080588 0C000526 */   addiu     $a1, $s0, 0xC
/* 7AAC2BC 8008058C 1000638E */  lw         $v1, 0x10($s3)
/* 7AAC2C0 80080590 00000000 */  nop
/* 7AAC2C4 80080594 2A104300 */  slt        $v0, $v0, $v1
/* 7AAC2C8 80080598 0F004010 */  beqz       $v0, .Llevel_37_800805D8
/* 7AAC2CC 8008059C 21300000 */   addu      $a2, $zero, $zero
/* 7AAC2D0 800805A0 0C00038E */  lw         $v1, 0xC($s0)
/* 7AAC2D4 800805A4 1000023C */  lui        $v0, (0x100000 >> 16)
/* 7AAC2D8 800805A8 180002AE */  sw         $v0, 0x18($s0)
/* 7AAC2DC 800805AC 0C00448E */  lw         $a0, 0xC($s2)
/* 7AAC2E0 800805B0 1000028E */  lw         $v0, 0x10($s0)
/* 7AAC2E4 800805B4 1000458E */  lw         $a1, 0x10($s2)
/* 7AAC2E8 800805B8 23206400 */  subu       $a0, $v1, $a0
/* 7AAC2EC 800805BC 203A010C */  jal        func_8004E880
/* 7AAC2F0 800805C0 23284500 */   subu      $a1, $v0, $a1
/* 7AAC2F4 800805C4 510002A2 */  sb         $v0, 0x51($s0)
/* 7AAC2F8 800805C8 FF004230 */  andi       $v0, $v0, 0xFF
/* 7AAC2FC 800805CC 02004014 */  bnez       $v0, .Llevel_37_800805D8
/* 7AAC300 800805D0 01000224 */   addiu     $v0, $zero, 0x1
/* 7AAC304 800805D4 510002A2 */  sb         $v0, 0x51($s0)
.Llevel_37_800805D8:
/* 7AAC308 800805D8 0000308E */  lw         $s0, 0x0($s1)
/* 7AAC30C 800805DC 00000000 */  nop
/* 7AAC310 800805E0 E4FF0016 */  bnez       $s0, .Llevel_37_80080574
/* 7AAC314 800805E4 04003126 */   addiu     $s1, $s1, 0x4
/* 7AAC318 800805E8 F8020208 */  j          .Llevel_37_80080BE0
/* 7AAC31C 800805EC 00000000 */   nop
.L800805F0_:
/* 7AAC320 800805F0 1400438E */  lw         $v1, 0x14($s2)
/* 7AAC324 800805F4 00000000 */  nop
/* 7AAC328 800805F8 01786228 */  slti       $v0, $v1, 0x7801
/* 7AAC32C 800805FC 63024010 */  beqz       $v0, .Llevel_37_80080F8C
/* 7AAC330 80080600 01000224 */   addiu     $v0, $zero, 0x1
/* 7AAC334 80080604 0C00428E */  lw         $v0, 0xC($s2)
/* 7AAC338 80080608 00000000 */  nop
/* 7AAC33C 8008060C 00044228 */  slti       $v0, $v0, 0x400
/* 7AAC340 80080610 5E024014 */  bnez       $v0, .Llevel_37_80080F8C
/* 7AAC344 80080614 01000224 */   addiu     $v0, $zero, 0x1
/* 7AAC348 80080618 1000428E */  lw         $v0, 0x10($s2)
/* 7AAC34C 8008061C 00000000 */  nop
/* 7AAC350 80080620 00044228 */  slti       $v0, $v0, 0x400
/* 7AAC354 80080624 59024014 */  bnez       $v0, .Llevel_37_80080F8C
/* 7AAC358 80080628 01000224 */   addiu     $v0, $zero, 0x1
/* 7AAC35C 8008062C 00046228 */  slti       $v0, $v1, 0x400
/* 7AAC360 80080630 56024014 */  bnez       $v0, .Llevel_37_80080F8C
/* 7AAC364 80080634 01000224 */   addiu     $v0, $zero, 0x1
/* 7AAC368 80080638 0C00628E */  lw         $v0, 0xC($s3)
/* 7AAC36C 8008063C 00000000 */  nop
/* 7AAC370 80080640 85004014 */  bnez       $v0, .Llevel_37_80080858
/* 7AAC374 80080644 05000224 */   addiu     $v0, $zero, 0x5
/* 7AAC378 80080648 49004392 */  lbu        $v1, 0x49($s2)
/* 7AAC37C 8008064C 00000000 */  nop
/* 7AAC380 80080650 35006214 */  bne        $v1, $v0, .Llevel_37_80080728
/* 7AAC384 80080654 BF010424 */   addiu     $a0, $zero, 0x1BF
/* 7AAC388 80080658 0780023C */  lui        $v0, %hi(SpawnMoby)
/* 7AAC38C 8008065C E042428C */  lw         $v0, %lo(SpawnMoby)($v0)
/* 7AAC390 80080660 00000000 */  nop
/* 7AAC394 80080664 09F84000 */  jalr       $v0
/* 7AAC398 80080668 21284002 */   addu      $a1, $s2, $zero
/* 7AAC39C 8008066C 21204000 */  addu       $a0, $v0, $zero
/* 7AAC3A0 80080670 79008010 */  beqz       $a0, .Llevel_37_80080858
/* 7AAC3A4 80080674 0C0064AE */   sw        $a0, 0xC($s3)
/* 7AAC3A8 80080678 3C008390 */  lbu        $v1, 0x3C($a0)
/* 7AAC3AC 8008067C 01000224 */  addiu      $v0, $zero, 0x1
/* 7AAC3B0 80080680 20006210 */  beq        $v1, $v0, .Llevel_37_80080704
/* 7AAC3B4 80080684 00000000 */   nop
/* 7AAC3B8 80080688 420080A0 */  sb         $zero, 0x42($a0)
/* 7AAC3BC 8008068C 0C00638E */  lw         $v1, 0xC($s3)
/* 7AAC3C0 80080690 00000000 */  nop
/* 7AAC3C4 80080694 36006284 */  lh         $v0, 0x36($v1)
/* 7AAC3C8 80080698 00000000 */  nop
/* 7AAC3CC 8008069C 80100200 */  sll        $v0, $v0, 2
/* 7AAC3D0 800806A0 0780013C */  lui        $at, %hi(D_8006EE2C)
/* 7AAC3D4 800806A4 21082200 */  addu       $at, $at, $v0
/* 7AAC3D8 800806A8 2CEE228C */  lw         $v0, %lo(D_8006EE2C)($at)
/* 7AAC3DC 800806AC 00000000 */  nop
/* 7AAC3E0 800806B0 4000428C */  lw         $v0, 0x40($v0)
/* 7AAC3E4 800806B4 00000000 */  nop
/* 7AAC3E8 800806B8 00004290 */  lbu        $v0, 0x0($v0)
/* 7AAC3EC 800806BC 00000000 */  nop
/* 7AAC3F0 800806C0 0200422C */  sltiu      $v0, $v0, 0x2
/* 7AAC3F4 800806C4 01004238 */  xori       $v0, $v0, 0x1
/* 7AAC3F8 800806C8 23100200 */  negu       $v0, $v0
/* 7AAC3FC 800806CC 30004230 */  andi       $v0, $v0, 0x30
/* 7AAC400 800806D0 400062A0 */  sb         $v0, 0x40($v1)
/* 7AAC404 800806D4 0C00628E */  lw         $v0, 0xC($s3)
/* 7AAC408 800806D8 01000324 */  addiu      $v1, $zero, 0x1
/* 7AAC40C 800806DC 3C0043A0 */  sb         $v1, 0x3C($v0)
/* 7AAC410 800806E0 0C00628E */  lw         $v0, 0xC($s3)
/* 7AAC414 800806E4 00000000 */  nop
/* 7AAC418 800806E8 3D0043A0 */  sb         $v1, 0x3D($v0)
/* 7AAC41C 800806EC 0C00628E */  lw         $v0, 0xC($s3)
/* 7AAC420 800806F0 00000000 */  nop
/* 7AAC424 800806F4 3E0040A0 */  sb         $zero, 0x3E($v0)
/* 7AAC428 800806F8 0C00628E */  lw         $v0, 0xC($s3)
/* 7AAC42C 800806FC 00000000 */  nop
/* 7AAC430 80080700 3F0043A0 */  sb         $v1, 0x3F($v0)
.Llevel_37_80080704:
/* 7AAC434 80080704 0C00638E */  lw         $v1, 0xC($s3)
/* 7AAC438 80080708 63000224 */  addiu      $v0, $zero, 0x63
/* 7AAC43C 8008070C 480062A0 */  sb         $v0, 0x48($v1)
/* 7AAC440 80080710 0C00628E */  lw         $v0, 0xC($s3)
/* 7AAC444 80080714 50000324 */  addiu      $v1, $zero, 0x50
/* 7AAC448 80080718 4C0043A0 */  sb         $v1, 0x4C($v0)
/* 7AAC44C 8008071C 0C00628E */  lw         $v0, 0xC($s3)
/* 7AAC450 80080720 16020208 */  j          .Llevel_37_80080858
/* 7AAC454 80080724 4E0043A0 */   sb        $v1, 0x4E($v0)
.Llevel_37_80080728:
/* 7AAC458 80080728 36004486 */  lh         $a0, 0x36($s2)
/* 7AAC45C 8008072C 0780023C */  lui        $v0, %hi(SpawnMoby)
/* 7AAC460 80080730 E042428C */  lw         $v0, %lo(SpawnMoby)($v0)
/* 7AAC464 80080734 00000000 */  nop
/* 7AAC468 80080738 09F84000 */  jalr       $v0
/* 7AAC46C 8008073C 21284002 */   addu      $a1, $s2, $zero
/* 7AAC470 80080740 21184000 */  addu       $v1, $v0, $zero
/* 7AAC474 80080744 44006010 */  beqz       $v1, .Llevel_37_80080858
/* 7AAC478 80080748 0C0063AE */   sw        $v1, 0xC($s3)
/* 7AAC47C 8008074C 02000224 */  addiu      $v0, $zero, 0x2
/* 7AAC480 80080750 480062A0 */  sb         $v0, 0x48($v1)
/* 7AAC484 80080754 0C00648E */  lw         $a0, 0xC($s3)
/* 7AAC488 80080758 49004292 */  lbu        $v0, 0x49($s2)
/* 7AAC48C 8008075C 3C008390 */  lbu        $v1, 0x3C($a0)
/* 7AAC490 80080760 00000000 */  nop
/* 7AAC494 80080764 23006210 */  beq        $v1, $v0, .Llevel_37_800807F4
/* 7AAC498 80080768 00000000 */   nop
/* 7AAC49C 8008076C 420080A0 */  sb         $zero, 0x42($a0)
/* 7AAC4A0 80080770 0C00648E */  lw         $a0, 0xC($s3)
/* 7AAC4A4 80080774 00000000 */  nop
/* 7AAC4A8 80080778 36008384 */  lh         $v1, 0x36($a0)
/* 7AAC4AC 8008077C 49004292 */  lbu        $v0, 0x49($s2)
/* 7AAC4B0 80080780 80180300 */  sll        $v1, $v1, 2
/* 7AAC4B4 80080784 0780013C */  lui        $at, %hi(D_8006EE2C)
/* 7AAC4B8 80080788 21082300 */  addu       $at, $at, $v1
/* 7AAC4BC 8008078C 2CEE238C */  lw         $v1, %lo(D_8006EE2C)($at)
/* 7AAC4C0 80080790 80100200 */  sll        $v0, $v0, 2
/* 7AAC4C4 80080794 21104300 */  addu       $v0, $v0, $v1
/* 7AAC4C8 80080798 3C00428C */  lw         $v0, 0x3C($v0)
/* 7AAC4CC 8008079C 00000000 */  nop
/* 7AAC4D0 800807A0 00004290 */  lbu        $v0, 0x0($v0)
/* 7AAC4D4 800807A4 00000000 */  nop
/* 7AAC4D8 800807A8 0200422C */  sltiu      $v0, $v0, 0x2
/* 7AAC4DC 800807AC 01004238 */  xori       $v0, $v0, 0x1
/* 7AAC4E0 800807B0 23100200 */  negu       $v0, $v0
/* 7AAC4E4 800807B4 30004230 */  andi       $v0, $v0, 0x30
/* 7AAC4E8 800807B8 400082A0 */  sb         $v0, 0x40($a0)
/* 7AAC4EC 800807BC 0C00638E */  lw         $v1, 0xC($s3)
/* 7AAC4F0 800807C0 49004292 */  lbu        $v0, 0x49($s2)
/* 7AAC4F4 800807C4 00000000 */  nop
/* 7AAC4F8 800807C8 3C0062A0 */  sb         $v0, 0x3C($v1)
/* 7AAC4FC 800807CC 0C00638E */  lw         $v1, 0xC($s3)
/* 7AAC500 800807D0 49004292 */  lbu        $v0, 0x49($s2)
/* 7AAC504 800807D4 00000000 */  nop
/* 7AAC508 800807D8 3D0062A0 */  sb         $v0, 0x3D($v1)
/* 7AAC50C 800807DC 0C00628E */  lw         $v0, 0xC($s3)
/* 7AAC510 800807E0 00000000 */  nop
/* 7AAC514 800807E4 3E0040A0 */  sb         $zero, 0x3E($v0)
/* 7AAC518 800807E8 0C00638E */  lw         $v1, 0xC($s3)
/* 7AAC51C 800807EC 01000224 */  addiu      $v0, $zero, 0x1
/* 7AAC520 800807F0 3F0062A0 */  sb         $v0, 0x3F($v1)
.Llevel_37_800807F4:
/* 7AAC524 800807F4 0C00628E */  lw         $v0, 0xC($s3)
/* 7AAC528 800807F8 50000324 */  addiu      $v1, $zero, 0x50
/* 7AAC52C 800807FC 4C0043A0 */  sb         $v1, 0x4C($v0)
/* 7AAC530 80080800 0C00628E */  lw         $v0, 0xC($s3)
/* 7AAC534 80080804 00000000 */  nop
/* 7AAC538 80080808 4E0043A0 */  sb         $v1, 0x4E($v0)
/* 7AAC53C 8008080C 49004392 */  lbu        $v1, 0x49($s2)
/* 7AAC540 80080810 01000224 */  addiu      $v0, $zero, 0x1
/* 7AAC544 80080814 04006214 */  bne        $v1, $v0, .Llevel_37_80080828
/* 7AAC548 80080818 602A033C */   lui       $v1, (0x2A606060 >> 16)
/* 7AAC54C 8008081C 0C00628E */  lw         $v0, 0xC($s3)
/* 7AAC550 80080820 60606334 */  ori        $v1, $v1, (0x2A606060 & 0xFFFF)
/* 7AAC554 80080824 540043AC */  sw         $v1, 0x54($v0)
.Llevel_37_80080828:
/* 7AAC558 80080828 49004292 */  lbu        $v0, 0x49($s2)
/* 7AAC55C 8008082C 00000000 */  nop
/* 7AAC560 80080830 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 7AAC564 80080834 0200422C */  sltiu      $v0, $v0, 0x2
/* 7AAC568 80080838 07004010 */  beqz       $v0, .Llevel_37_80080858
/* 7AAC56C 8008083C 602A033C */   lui       $v1, (0x2A606060 >> 16)
/* 7AAC570 80080840 0C00628E */  lw         $v0, 0xC($s3)
/* 7AAC574 80080844 60606334 */  ori        $v1, $v1, (0x2A606060 & 0xFFFF)
/* 7AAC578 80080848 540043AC */  sw         $v1, 0x54($v0)
/* 7AAC57C 8008084C 0C00638E */  lw         $v1, 0xC($s3)
/* 7AAC580 80080850 20000224 */  addiu      $v0, $zero, 0x20
/* 7AAC584 80080854 450062A0 */  sb         $v0, 0x45($v1)
.Llevel_37_80080858:
/* 7AAC588 80080858 04006286 */  lh         $v0, 0x4($s3)
/* 7AAC58C 8008085C 00000000 */  nop
/* 7AAC590 80080860 40100200 */  sll        $v0, $v0, 1
/* 7AAC594 80080864 0680013C */  lui        $at, %hi(D_80065920)
/* 7AAC598 80080868 21082200 */  addu       $at, $at, $v0
/* 7AAC59C 8008086C 20592384 */  lh         $v1, %lo(D_80065920)($at)
/* 7AAC5A0 80080870 00006286 */  lh         $v0, 0x0($s3)
/* 7AAC5A4 80080874 00000000 */  nop
/* 7AAC5A8 80080878 18006200 */  mult       $v1, $v0
/* 7AAC5AC 8008087C 12400000 */  mflo       $t0
/* 7AAC5B0 80080880 03130800 */  sra        $v0, $t0, 12
/* 7AAC5B4 80080884 9000A2AF */  sw         $v0, 0x90($sp)
/* 7AAC5B8 80080888 04006286 */  lh         $v0, 0x4($s3)
/* 7AAC5BC 8008088C 00000000 */  nop
/* 7AAC5C0 80080890 40100200 */  sll        $v0, $v0, 1
/* 7AAC5C4 80080894 0680013C */  lui        $at, %hi(D_800658A0)
/* 7AAC5C8 80080898 21082200 */  addu       $at, $at, $v0
/* 7AAC5CC 8008089C A0582384 */  lh         $v1, %lo(D_800658A0)($at)
/* 7AAC5D0 800808A0 00006286 */  lh         $v0, 0x0($s3)
/* 7AAC5D4 800808A4 00000000 */  nop
/* 7AAC5D8 800808A8 18006200 */  mult       $v1, $v0
/* 7AAC5DC 800808AC 5800A427 */  addiu      $a0, $sp, 0x58
/* 7AAC5E0 800808B0 0C005126 */  addiu      $s1, $s2, 0xC
/* 7AAC5E4 800808B4 21282002 */  addu       $a1, $s1, $zero
/* 7AAC5E8 800808B8 9800A0AF */  sw         $zero, 0x98($sp)
/* 7AAC5EC 800808BC 12400000 */  mflo       $t0
/* 7AAC5F0 800808C0 03130800 */  sra        $v0, $t0, 12
/* 7AAC5F4 800808C4 9400A2AF */  sw         $v0, 0x94($sp)
/* 7AAC5F8 800808C8 02006286 */  lh         $v0, 0x2($s3)
/* 7AAC5FC 800808CC 2C011424 */  addiu      $s4, $zero, 0x12C
/* 7AAC600 800808D0 5E3C010C */  jal        func_8004F178
/* 7AAC604 800808D4 9800A2AF */   sw        $v0, 0x98($sp)
/* 7AAC608 800808D8 21202002 */  addu       $a0, $s1, $zero
/* 7AAC60C 800808DC 21282002 */  addu       $a1, $s1, $zero
/* 7AAC610 800808E0 9000B027 */  addiu      $s0, $sp, 0x90
/* 7AAC614 800808E4 653C010C */  jal        func_8004F194
/* 7AAC618 800808E8 21300002 */   addu      $a2, $s0, $zero
/* 7AAC61C 800808EC 21200002 */  addu       $a0, $s0, $zero
/* 7AAC620 800808F0 02006296 */  lhu        $v0, 0x2($s3)
/* 7AAC624 800808F4 06006396 */  lhu        $v1, 0x6($s3)
/* 7AAC628 800808F8 01000524 */  addiu      $a1, $zero, 0x1
/* 7AAC62C 800808FC 21104300 */  addu       $v0, $v0, $v1
/* 7AAC630 80080900 7A3B010C */  jal        func_8004EDE8
/* 7AAC634 80080904 020062A6 */   sh        $v0, 0x2($s3)
/* 7AAC638 80080908 08004324 */  addiu      $v1, $v0, 0x8
/* 7AAC63C 8008090C 2A108302 */  slt        $v0, $s4, $v1
/* 7AAC640 80080910 02004010 */  beqz       $v0, .Llevel_37_8008091C
/* 7AAC644 80080914 21204002 */   addu      $a0, $s2, $zero
/* 7AAC648 80080918 21A06000 */  addu       $s4, $v1, $zero
.Llevel_37_8008091C:
/* 7AAC64C 8008091C 4957010C */  jal        func_80055D24
/* 7AAC650 80080920 02000524 */   addiu     $a1, $zero, 0x2
/* 7AAC654 80080924 21202002 */  addu       $a0, $s1, $zero
/* 7AAC658 80080928 6564000C */  jal        func_80019194
/* 7AAC65C 8008092C 21288002 */   addu      $a1, $s4, $zero
/* 7AAC660 80080930 7D004010 */  beqz       $v0, .Llevel_37_80080B28
/* 7AAC664 80080934 00000000 */   nop
/* 7AAC668 80080938 0C00648E */  lw         $a0, 0xC($s3)
/* 7AAC66C 8008093C 00000000 */  nop
/* 7AAC670 80080940 1F008010 */  beqz       $a0, .Llevel_37_800809C0
/* 7AAC674 80080944 BF010224 */   addiu     $v0, $zero, 0x1BF
/* 7AAC678 80080948 36008384 */  lh         $v1, 0x36($a0)
/* 7AAC67C 8008094C 00000000 */  nop
/* 7AAC680 80080950 1B006214 */  bne        $v1, $v0, .Llevel_37_800809C0
/* 7AAC684 80080954 00000000 */   nop
/* 7AAC688 80080958 48008290 */  lbu        $v0, 0x48($a0)
/* 7AAC68C 8008095C 00000000 */  nop
/* 7AAC690 80080960 8000422C */  sltiu      $v0, $v0, 0x80
/* 7AAC694 80080964 89014010 */  beqz       $v0, .Llevel_37_80080F8C
/* 7AAC698 80080968 03000224 */   addiu     $v0, $zero, 0x3
/* 7AAC69C 8008096C 0000908C */  lw         $s0, 0x0($a0)
/* 7AAC6A0 80080970 05DC000C */  jal        func_80037014
/* 7AAC6A4 80080974 00000000 */   nop
/* 7AAC6A8 80080978 0C00648E */  lw         $a0, 0xC($s3)
/* 7AAC6AC 8008097C 00000000 */  nop
/* 7AAC6B0 80080980 1C00828C */  lw         $v0, 0x1C($a0)
/* 7AAC6B4 80080984 0080033C */  lui        $v1, (0x80000000 >> 16)
/* 7AAC6B8 80080988 25104300 */  or         $v0, $v0, $v1
/* 7AAC6BC 8008098C 1C0082AC */  sw         $v0, 0x1C($a0)
/* 7AAC6C0 80080990 0C00658E */  lw         $a1, 0xC($s3)
/* 7AAC6C4 80080994 21200002 */  addu       $a0, $s0, $zero
/* 7AAC6C8 80080998 5E3C010C */  jal        func_8004F178
/* 7AAC6CC 8008099C 0C00A524 */   addiu     $a1, $a1, 0xC
/* 7AAC6D0 800809A0 0C00648E */  lw         $a0, 0xC($s3)
/* 7AAC6D4 800809A4 4957010C */  jal        func_80055D24
/* 7AAC6D8 800809A8 03000524 */   addiu     $a1, $zero, 0x3
/* 7AAC6DC 800809AC 0C00628E */  lw         $v0, 0xC($s3)
/* 7AAC6E0 800809B0 00000000 */  nop
/* 7AAC6E4 800809B4 480040A0 */  sb         $zero, 0x48($v0)
/* 7AAC6E8 800809B8 E2030208 */  j          .Llevel_37_80080F88
/* 7AAC6EC 800809BC 0C0060AE */   sw        $zero, 0xC($s3)
.Llevel_37_800809C0:
/* 7AAC6F0 800809C0 0780113C */  lui        $s1, %hi(D_80071920)
/* 7AAC6F4 800809C4 20193126 */  addiu      $s1, $s1, %lo(D_80071920)
/* 7AAC6F8 800809C8 F8FF3426 */  addiu      $s4, $s1, -0x8
/* 7AAC6FC 800809CC 21208002 */  addu       $a0, $s4, $zero
/* 7AAC700 800809D0 0000308E */  lw         $s0, 0x0($s1)
/* 7AAC704 800809D4 00000000 */  nop
/* 7AAC708 800809D8 02000106 */  bgez       $s0, .Llevel_37_800809E4
/* 7AAC70C 800809DC 00000000 */   nop
/* 7AAC710 800809E0 23801000 */  negu       $s0, $s0
.Llevel_37_800809E4:
/* 7AAC714 800809E4 7A3B010C */  jal        func_8004EDE8
/* 7AAC718 800809E8 21280000 */   addu      $a1, $zero, $zero
/* 7AAC71C 800809EC 2A800202 */  slt        $s0, $s0, $v0
/* 7AAC720 800809F0 20000012 */  beqz       $s0, .Llevel_37_80080A74
/* 7AAC724 800809F4 A000B027 */   addiu     $s0, $sp, 0xA0
/* 7AAC728 800809F8 21200002 */  addu       $a0, $s0, $zero
/* 7AAC72C 800809FC 5E3C010C */  jal        func_8004F178
/* 7AAC730 80080A00 21288002 */   addu      $a1, $s4, $zero
/* 7AAC734 80080A04 9000A427 */  addiu      $a0, $sp, 0x90
/* 7AAC738 80080A08 21280002 */  addu       $a1, $s0, $zero
/* 7AAC73C 80080A0C DD3B010C */  jal        func_8004EF74
/* 7AAC740 80080A10 21308000 */   addu      $a2, $a0, $zero
/* 7AAC744 80080A14 44004010 */  beqz       $v0, .Llevel_37_80080B28
/* 7AAC748 80080A18 21204002 */   addu      $a0, $s2, $zero
/* 7AAC74C 80080A1C 21280000 */  addu       $a1, $zero, $zero
/* 7AAC750 80080A20 02006386 */  lh         $v1, 0x2($s3)
/* 7AAC754 80080A24 21300000 */  addu       $a2, $zero, $zero
/* 7AAC758 80080A28 40100300 */  sll        $v0, $v1, 1
/* 7AAC75C 80080A2C 21104300 */  addu       $v0, $v0, $v1
/* 7AAC760 80080A30 83100200 */  sra        $v0, $v0, 2
/* 7AAC764 80080A34 AFEE000C */  jal        func_8003BABC
/* 7AAC768 80080A38 020062A6 */   sh        $v0, 0x2($s3)
/* 7AAC76C 80080A3C 21204000 */  addu       $a0, $v0, $zero
/* 7AAC770 80080A40 39008004 */  bltz       $a0, .Llevel_37_80080B28
/* 7AAC774 80080A44 00000000 */   nop
/* 7AAC778 80080A48 02006286 */  lh         $v0, 0x2($s3)
/* 7AAC77C 80080A4C 00000000 */  nop
/* 7AAC780 80080A50 02004104 */  bgez       $v0, .Llevel_37_80080A5C
/* 7AAC784 80080A54 00000000 */   nop
/* 7AAC788 80080A58 23100200 */  negu       $v0, $v0
.Llevel_37_80080A5C:
/* 7AAC78C 80080A5C 80280200 */  sll        $a1, $v0, 2
/* 7AAC790 80080A60 2128A200 */  addu       $a1, $a1, $v0
/* 7AAC794 80080A64 50F0000C */  jal        func_8003C140
/* 7AAC798 80080A68 C0280500 */   sll       $a1, $a1, 3
/* 7AAC79C 80080A6C CA020208 */  j          .Llevel_37_80080B28
/* 7AAC7A0 80080A70 00000000 */   nop
.Llevel_37_80080A74:
/* 7AAC7A4 80080A74 0000308E */  lw         $s0, 0x0($s1)
/* 7AAC7A8 80080A78 00000000 */  nop
/* 7AAC7AC 80080A7C 05000106 */  bgez       $s0, .Llevel_37_80080A94
/* 7AAC7B0 80080A80 00000000 */   nop
/* 7AAC7B4 80080A84 9800A28F */  lw         $v0, 0x98($sp)
/* 7AAC7B8 80080A88 00000000 */  nop
/* 7AAC7BC 80080A8C 0700401C */  bgtz       $v0, .Llevel_37_80080AAC
/* 7AAC7C0 80080A90 21204002 */   addu      $a0, $s2, $zero
.Llevel_37_80080A94:
/* 7AAC7C4 80080A94 2400001A */  blez       $s0, .Llevel_37_80080B28
/* 7AAC7C8 80080A98 00000000 */   nop
/* 7AAC7CC 80080A9C 9800A28F */  lw         $v0, 0x98($sp)
/* 7AAC7D0 80080AA0 00000000 */  nop
/* 7AAC7D4 80080AA4 20004104 */  bgez       $v0, .Llevel_37_80080B28
/* 7AAC7D8 80080AA8 21204002 */   addu      $a0, $s2, $zero
.Llevel_37_80080AAC:
/* 7AAC7DC 80080AAC 21280000 */  addu       $a1, $zero, $zero
/* 7AAC7E0 80080AB0 02006286 */  lh         $v0, 0x2($s3)
/* 7AAC7E4 80080AB4 21300000 */  addu       $a2, $zero, $zero
/* 7AAC7E8 80080AB8 000060A6 */  sh         $zero, 0x0($s3)
/* 7AAC7EC 80080ABC 23100200 */  negu       $v0, $v0
/* 7AAC7F0 80080AC0 43100200 */  sra        $v0, $v0, 1
/* 7AAC7F4 80080AC4 AFEE000C */  jal        func_8003BABC
/* 7AAC7F8 80080AC8 020062A6 */   sh        $v0, 0x2($s3)
/* 7AAC7FC 80080ACC 21204000 */  addu       $a0, $v0, $zero
/* 7AAC800 80080AD0 0A008004 */  bltz       $a0, .Llevel_37_80080AFC
/* 7AAC804 80080AD4 00000000 */   nop
/* 7AAC808 80080AD8 02006286 */  lh         $v0, 0x2($s3)
/* 7AAC80C 80080ADC 00000000 */  nop
/* 7AAC810 80080AE0 02004104 */  bgez       $v0, .Llevel_37_80080AEC
/* 7AAC814 80080AE4 00000000 */   nop
/* 7AAC818 80080AE8 23100200 */  negu       $v0, $v0
.Llevel_37_80080AEC:
/* 7AAC81C 80080AEC 80280200 */  sll        $a1, $v0, 2
/* 7AAC820 80080AF0 2128A200 */  addu       $a1, $a1, $v0
/* 7AAC824 80080AF4 50F0000C */  jal        func_8003C140
/* 7AAC828 80080AF8 C0280500 */   sll       $a1, $a1, 3
.Llevel_37_80080AFC:
/* 7AAC82C 80080AFC 02006286 */  lh         $v0, 0x2($s3)
/* 7AAC830 80080B00 00000000 */  nop
/* 7AAC834 80080B04 28004228 */  slti       $v0, $v0, 0x28
/* 7AAC838 80080B08 07004010 */  beqz       $v0, .Llevel_37_80080B28
/* 7AAC83C 80080B0C 00000000 */   nop
/* 7AAC840 80080B10 4ED7000C */  jal        func_80035D38
/* 7AAC844 80080B14 21204002 */   addu      $a0, $s2, $zero
/* 7AAC848 80080B18 2C014224 */  addiu      $v0, $v0, 0x12C
/* 7AAC84C 80080B1C 140042AE */  sw         $v0, 0x14($s2)
/* 7AAC850 80080B20 080060AE */  sw         $zero, 0x8($s3)
/* 7AAC854 80080B24 480040A2 */  sb         $zero, 0x48($s2)
.Llevel_37_80080B28:
/* 7AAC858 80080B28 4ED7000C */  jal        func_80035D38
/* 7AAC85C 80080B2C 21204002 */   addu      $a0, $s2, $zero
/* 7AAC860 80080B30 A758010C */  jal        func_8005629C
/* 7AAC864 80080B34 21204002 */   addu      $a0, $s2, $zero
/* 7AAC868 80080B38 F8020208 */  j          .Llevel_37_80080BE0
/* 7AAC86C 80080B3C 00000000 */   nop
.L80080B40_:
/* 7AAC870 80080B40 0A000424 */  addiu      $a0, $zero, 0xA
/* 7AAC874 80080B44 6B000524 */  addiu      $a1, $zero, 0x6B
/* 7AAC878 80080B48 21304002 */  addu       $a2, $s2, $zero
/* 7AAC87C 80080B4C 21380000 */  addu       $a3, $zero, $zero
/* 7AAC880 80080B50 05000224 */  addiu      $v0, $zero, 0x5
/* 7AAC884 80080B54 1000A2AF */  sw         $v0, 0x10($sp)
/* 7AAC888 80080B58 6E000224 */  addiu      $v0, $zero, 0x6E
/* 7AAC88C 80080B5C 1400A2AF */  sw         $v0, 0x14($sp)
/* 7AAC890 80080B60 C8000224 */  addiu      $v0, $zero, 0xC8
/* 7AAC894 80080B64 7AE4000C */  jal        func_800391E8
/* 7AAC898 80080B68 1800A2AF */   sw        $v0, 0x18($sp)
/* 7AAC89C 80080B6C 21204002 */  addu       $a0, $s2, $zero
/* 7AAC8A0 80080B70 01000524 */  addiu      $a1, $zero, 0x1
/* 7AAC8A4 80080B74 AFEE000C */  jal        func_8003BABC
/* 7AAC8A8 80080B78 21300000 */   addu      $a2, $zero, $zero
/* 7AAC8AC 80080B7C 49004392 */  lbu        $v1, 0x49($s2)
/* 7AAC8B0 80080B80 02000224 */  addiu      $v0, $zero, 0x2
/* 7AAC8B4 80080B84 0C006214 */  bne        $v1, $v0, .Llevel_37_80080BB8
/* 7AAC8B8 80080B88 04000224 */   addiu     $v0, $zero, 0x4
/* 7AAC8BC 80080B8C 480042A2 */  sb         $v0, 0x48($s2)
/* 7AAC8C0 80080B90 0C00648E */  lw         $a0, 0xC($s3)
/* 7AAC8C4 80080B94 00000000 */  nop
/* 7AAC8C8 80080B98 03008010 */  beqz       $a0, .Llevel_37_80080BA8
/* 7AAC8CC 80080B9C 00000000 */   nop
/* 7AAC8D0 80080BA0 C656010C */  jal        func_80055B18
/* 7AAC8D4 80080BA4 00000000 */   nop
.Llevel_37_80080BA8:
/* 7AAC8D8 80080BA8 410040A2 */  sb         $zero, 0x41($s2)
/* 7AAC8DC 80080BAC 4C0040A2 */  sb         $zero, 0x4C($s2)
/* 7AAC8E0 80080BB0 E4030208 */  j          .Llevel_37_80080F90
/* 7AAC8E4 80080BB4 4D0040A2 */   sb        $zero, 0x4D($s2)
.Llevel_37_80080BB8:
/* 7AAC8E8 80080BB8 0C00648E */  lw         $a0, 0xC($s3)
/* 7AAC8EC 80080BBC 00000000 */  nop
/* 7AAC8F0 80080BC0 03008010 */  beqz       $a0, .Llevel_37_80080BD0
/* 7AAC8F4 80080BC4 00000000 */   nop
/* 7AAC8F8 80080BC8 C656010C */  jal        func_80055B18
/* 7AAC8FC 80080BCC 00000000 */   nop
.Llevel_37_80080BD0:
/* 7AAC900 80080BD0 C656010C */  jal        func_80055B18
/* 7AAC904 80080BD4 21204002 */   addu      $a0, $s2, $zero
/* 7AAC908 80080BD8 E4030208 */  j          .Llevel_37_80080F90
/* 7AAC90C 80080BDC 00000000 */   nop
.Llevel_37_80080BE0:
/* 7AAC910 80080BE0 48004392 */  lbu        $v1, 0x48($s2)
.Llevel_37_80080BE4:
/* 7AAC914 80080BE4 00000000 */  nop
/* 7AAC918 80080BE8 03006010 */  beqz       $v1, .Llevel_37_80080BF8
/* 7AAC91C 80080BEC 14000224 */   addiu     $v0, $zero, 0x14
/* 7AAC920 80080BF0 E7006214 */  bne        $v1, $v0, .Llevel_37_80080F90
/* 7AAC924 80080BF4 00000000 */   nop
.Llevel_37_80080BF8:
/* 7AAC928 80080BF8 0C00648E */  lw         $a0, 0xC($s3)
/* 7AAC92C 80080BFC 00000000 */  nop
/* 7AAC930 80080C00 12008010 */  beqz       $a0, .Llevel_37_80080C4C
/* 7AAC934 80080C04 0C008424 */   addiu     $a0, $a0, 0xC
/* 7AAC938 80080C08 5E3C010C */  jal        func_8004F178
/* 7AAC93C 80080C0C 0C004526 */   addiu     $a1, $s2, 0xC
/* 7AAC940 80080C10 0C00648E */  lw         $a0, 0xC($s3)
/* 7AAC944 80080C14 00000000 */  nop
/* 7AAC948 80080C18 36008384 */  lh         $v1, 0x36($a0)
/* 7AAC94C 80080C1C BF010224 */  addiu      $v0, $zero, 0x1BF
/* 7AAC950 80080C20 06006214 */  bne        $v1, $v0, .Llevel_37_80080C3C
/* 7AAC954 80080C24 00000000 */   nop
/* 7AAC958 80080C28 1400828C */  lw         $v0, 0x14($a0)
/* 7AAC95C 80080C2C 00000000 */  nop
/* 7AAC960 80080C30 D4FE4224 */  addiu      $v0, $v0, -0x12C
/* 7AAC964 80080C34 13030208 */  j          .Llevel_37_80080C4C
/* 7AAC968 80080C38 140082AC */   sw        $v0, 0x14($a0)
.Llevel_37_80080C3C:
/* 7AAC96C 80080C3C 46008290 */  lbu        $v0, 0x46($a0)
/* 7AAC970 80080C40 00000000 */  nop
/* 7AAC974 80080C44 07004224 */  addiu      $v0, $v0, 0x7
/* 7AAC978 80080C48 460082A0 */  sb         $v0, 0x46($a0)
.Llevel_37_80080C4C:
/* 7AAC97C 80080C4C 0780133C */  lui        $s3, %hi(D_8006E788)
/* 7AAC980 80080C50 88E77326 */  addiu      $s3, $s3, %lo(D_8006E788)
/* 7AAC984 80080C54 21880000 */  addu       $s1, $zero, $zero
/* 7AAC988 80080C58 5A3C010C */  jal        func_8004F168
/* 7AAC98C 80080C5C A000A427 */   addiu     $a0, $sp, 0xA0
/* 7AAC990 80080C60 55030208 */  j          .Llevel_37_80080D54
/* 7AAC994 80080C64 00000000 */   nop
.Llevel_37_80080C68:
/* 7AAC998 80080C68 3A001212 */  beq        $s0, $s2, .Llevel_37_80080D54
/* 7AAC99C 80080C6C 02000224 */   addiu     $v0, $zero, 0x2
/* 7AAC9A0 80080C70 48000392 */  lbu        $v1, 0x48($s0)
/* 7AAC9A4 80080C74 00000000 */  nop
/* 7AAC9A8 80080C78 36006210 */  beq        $v1, $v0, .Llevel_37_80080D54
/* 7AAC9AC 80080C7C C3020224 */   addiu     $v0, $zero, 0x2C3
/* 7AAC9B0 80080C80 36000386 */  lh         $v1, 0x36($s0)
/* 7AAC9B4 80080C84 00000000 */  nop
/* 7AAC9B8 80080C88 32006214 */  bne        $v1, $v0, .Llevel_37_80080D54
/* 7AAC9BC 80080C8C 0C000426 */   addiu     $a0, $s0, 0xC
/* 7AAC9C0 80080C90 CD3C010C */  jal        func_8004F334
/* 7AAC9C4 80080C94 0C004526 */   addiu     $a1, $s2, 0xC
/* 7AAC9C8 80080C98 58024228 */  slti       $v0, $v0, 0x258
/* 7AAC9CC 80080C9C 2D004010 */  beqz       $v0, .Llevel_37_80080D54
/* 7AAC9D0 80080CA0 58021424 */   addiu     $s4, $zero, 0x258
/* 7AAC9D4 80080CA4 38004386 */  lh         $v1, 0x38($s2)
/* 7AAC9D8 80080CA8 1400428E */  lw         $v0, 0x14($s2)
/* 7AAC9DC 80080CAC 1400048E */  lw         $a0, 0x14($s0)
/* 7AAC9E0 80080CB0 23184300 */  subu       $v1, $v0, $v1
/* 7AAC9E4 80080CB4 23106400 */  subu       $v0, $v1, $a0
/* 7AAC9E8 80080CB8 05004004 */  bltz       $v0, .Llevel_37_80080CD0
/* 7AAC9EC 80080CBC F4014228 */   slti      $v0, $v0, 0x1F4
/* 7AAC9F0 80080CC0 07004014 */  bnez       $v0, .Llevel_37_80080CE0
/* 7AAC9F4 80080CC4 21300000 */   addu      $a2, $zero, $zero
/* 7AAC9F8 80080CC8 55030208 */  j          .Llevel_37_80080D54
/* 7AAC9FC 80080CCC 00000000 */   nop
.Llevel_37_80080CD0:
/* 7AACA00 80080CD0 23108300 */  subu       $v0, $a0, $v1
/* 7AACA04 80080CD4 F4014228 */  slti       $v0, $v0, 0x1F4
/* 7AACA08 80080CD8 1E004010 */  beqz       $v0, .Llevel_37_80080D54
/* 7AACA0C 80080CDC 21300000 */   addu      $a2, $zero, $zero
.Llevel_37_80080CE0:
/* 7AACA10 80080CE0 0C00438E */  lw         $v1, 0xC($s2)
/* 7AACA14 80080CE4 0C00048E */  lw         $a0, 0xC($s0)
/* 7AACA18 80080CE8 1000428E */  lw         $v0, 0x10($s2)
/* 7AACA1C 80080CEC 1000058E */  lw         $a1, 0x10($s0)
/* 7AACA20 80080CF0 23206400 */  subu       $a0, $v1, $a0
/* 7AACA24 80080CF4 203A010C */  jal        func_8004E880
/* 7AACA28 80080CF8 23284500 */   subu      $a1, $v0, $a1
/* 7AACA2C 80080CFC 40100200 */  sll        $v0, $v0, 1
/* 7AACA30 80080D00 0680013C */  lui        $at, %hi(D_80065920)
/* 7AACA34 80080D04 21082200 */  addu       $at, $at, $v0
/* 7AACA38 80080D08 20592384 */  lh         $v1, %lo(D_80065920)($at)
/* 7AACA3C 80080D0C 00000000 */  nop
/* 7AACA40 80080D10 18007400 */  mult       $v1, $s4
/* 7AACA44 80080D14 A000A38F */  lw         $v1, 0xA0($sp)
/* 7AACA48 80080D18 12400000 */  mflo       $t0
/* 7AACA4C 80080D1C 03230800 */  sra        $a0, $t0, 12
/* 7AACA50 80080D20 21186400 */  addu       $v1, $v1, $a0
/* 7AACA54 80080D24 A000A3AF */  sw         $v1, 0xA0($sp)
/* 7AACA58 80080D28 0680013C */  lui        $at, %hi(D_800658A0)
/* 7AACA5C 80080D2C 21082200 */  addu       $at, $at, $v0
/* 7AACA60 80080D30 A0582284 */  lh         $v0, %lo(D_800658A0)($at)
/* 7AACA64 80080D34 00000000 */  nop
/* 7AACA68 80080D38 18005400 */  mult       $v0, $s4
/* 7AACA6C 80080D3C 01003126 */  addiu      $s1, $s1, 0x1
/* 7AACA70 80080D40 A400A28F */  lw         $v0, 0xA4($sp)
/* 7AACA74 80080D44 12400000 */  mflo       $t0
/* 7AACA78 80080D48 031B0800 */  sra        $v1, $t0, 12
/* 7AACA7C 80080D4C 21104300 */  addu       $v0, $v0, $v1
/* 7AACA80 80080D50 A400A2AF */  sw         $v0, 0xA4($sp)
.Llevel_37_80080D54:
/* 7AACA84 80080D54 0000708E */  lw         $s0, 0x0($s3)
/* 7AACA88 80080D58 00000000 */  nop
/* 7AACA8C 80080D5C C2FF0016 */  bnez       $s0, .Llevel_37_80080C68
/* 7AACA90 80080D60 04007326 */   addiu     $s3, $s3, 0x4
/* 7AACA94 80080D64 3D002012 */  beqz       $s1, .Llevel_37_80080E5C
/* 7AACA98 80080D68 A000B027 */   addiu     $s0, $sp, 0xA0
/* 7AACA9C 80080D6C A000A68F */  lw         $a2, 0xA0($sp)
/* 7AACAA0 80080D70 00000000 */  nop
/* 7AACAA4 80080D74 1A00D100 */  div        $zero, $a2, $s1
/* 7AACAA8 80080D78 02002016 */  bnez       $s1, .Llevel_37_80080D84
/* 7AACAAC 80080D7C 00000000 */   nop
/* 7AACAB0 80080D80 0D000700 */  break      7
.Llevel_37_80080D84:
/* 7AACAB4 80080D84 FFFF0124 */  addiu      $at, $zero, -0x1
/* 7AACAB8 80080D88 04002116 */  bne        $s1, $at, .Llevel_37_80080D9C
/* 7AACABC 80080D8C 0080013C */   lui       $at, (0x80000000 >> 16)
/* 7AACAC0 80080D90 0200C114 */  bne        $a2, $at, .Llevel_37_80080D9C
/* 7AACAC4 80080D94 00000000 */   nop
/* 7AACAC8 80080D98 0D000600 */  break      6
.Llevel_37_80080D9C:
/* 7AACACC 80080D9C 12300000 */  mflo       $a2
/* 7AACAD0 80080DA0 A400A38F */  lw         $v1, 0xA4($sp)
/* 7AACAD4 80080DA4 00000000 */  nop
/* 7AACAD8 80080DA8 1A007100 */  div        $zero, $v1, $s1
/* 7AACADC 80080DAC 02002016 */  bnez       $s1, .Llevel_37_80080DB8
/* 7AACAE0 80080DB0 00000000 */   nop
/* 7AACAE4 80080DB4 0D000700 */  break      7
.Llevel_37_80080DB8:
/* 7AACAE8 80080DB8 FFFF0124 */  addiu      $at, $zero, -0x1
/* 7AACAEC 80080DBC 04002116 */  bne        $s1, $at, .Llevel_37_80080DD0
/* 7AACAF0 80080DC0 0080013C */   lui       $at, (0x80000000 >> 16)
/* 7AACAF4 80080DC4 02006114 */  bne        $v1, $at, .Llevel_37_80080DD0
/* 7AACAF8 80080DC8 00000000 */   nop
/* 7AACAFC 80080DCC 0D000600 */  break      6
.Llevel_37_80080DD0:
/* 7AACB00 80080DD0 12180000 */  mflo       $v1
/* 7AACB04 80080DD4 A800A28F */  lw         $v0, 0xA8($sp)
/* 7AACB08 80080DD8 00000000 */  nop
/* 7AACB0C 80080DDC 1A005100 */  div        $zero, $v0, $s1
/* 7AACB10 80080DE0 02002016 */  bnez       $s1, .Llevel_37_80080DEC
/* 7AACB14 80080DE4 00000000 */   nop
/* 7AACB18 80080DE8 0D000700 */  break      7
.Llevel_37_80080DEC:
/* 7AACB1C 80080DEC FFFF0124 */  addiu      $at, $zero, -0x1
/* 7AACB20 80080DF0 04002116 */  bne        $s1, $at, .Llevel_37_80080E04
/* 7AACB24 80080DF4 0080013C */   lui       $at, (0x80000000 >> 16)
/* 7AACB28 80080DF8 02004114 */  bne        $v0, $at, .Llevel_37_80080E04
/* 7AACB2C 80080DFC 00000000 */   nop
/* 7AACB30 80080E00 0D000600 */  break      6
.Llevel_37_80080E04:
/* 7AACB34 80080E04 12100000 */  mflo       $v0
/* 7AACB38 80080E08 01000524 */  addiu      $a1, $zero, 0x1
/* 7AACB3C 80080E0C 21200002 */  addu       $a0, $s0, $zero
/* 7AACB40 80080E10 A000A6AF */  sw         $a2, 0xA0($sp)
/* 7AACB44 80080E14 A400A3AF */  sw         $v1, 0xA4($sp)
/* 7AACB48 80080E18 7A3B010C */  jal        func_8004EDE8
/* 7AACB4C 80080E1C A800A2AF */   sw        $v0, 0xA8($sp)
/* 7AACB50 80080E20 21200002 */  addu       $a0, $s0, $zero
/* 7AACB54 80080E24 21284000 */  addu       $a1, $v0, $zero
/* 7AACB58 80080E28 233C010C */  jal        func_8004F08C
/* 7AACB5C 80080E2C 64000624 */   addiu     $a2, $zero, 0x64
/* 7AACB60 80080E30 21200002 */  addu       $a0, $s0, $zero
/* 7AACB64 80080E34 0C004526 */  addiu      $a1, $s2, 0xC
/* 7AACB68 80080E38 653C010C */  jal        func_8004F194
/* 7AACB6C 80080E3C 21300002 */   addu      $a2, $s0, $zero
/* 7AACB70 80080E40 21204002 */  addu       $a0, $s2, $zero
/* 7AACB74 80080E44 21280002 */  addu       $a1, $s0, $zero
/* 7AACB78 80080E48 2C010624 */  addiu      $a2, $zero, 0x12C
/* 7AACB7C 80080E4C 21380000 */  addu       $a3, $zero, $zero
/* 7AACB80 80080E50 21000224 */  addiu      $v0, $zero, 0x21
/* 7AACB84 80080E54 00E0000C */  jal        func_80038000
/* 7AACB88 80080E58 1000A2AF */   sw        $v0, 0x10($sp)
.Llevel_37_80080E5C:
/* 7AACB8C 80080E5C 0C004426 */  addiu      $a0, $s2, 0xC
/* 7AACB90 80080E60 0780103C */  lui        $s0, %hi(D_80070328)
/* 7AACB94 80080E64 28031026 */  addiu      $s0, $s0, %lo(D_80070328)
/* 7AACB98 80080E68 CD3C010C */  jal        func_8004F334
/* 7AACB9C 80080E6C 21280002 */   addu      $a1, $s0, $zero
/* 7AACBA0 80080E70 BC024228 */  slti       $v0, $v0, 0x2BC
/* 7AACBA4 80080E74 46004010 */  beqz       $v0, .Llevel_37_80080F90
/* 7AACBA8 80080E78 00000000 */   nop
/* 7AACBAC 80080E7C 38004386 */  lh         $v1, 0x38($s2)
/* 7AACBB0 80080E80 1400428E */  lw         $v0, 0x14($s2)
/* 7AACBB4 80080E84 00000000 */  nop
/* 7AACBB8 80080E88 23104300 */  subu       $v0, $v0, $v1
/* 7AACBBC 80080E8C 0780033C */  lui        $v1, %hi(D_80070328 + 8)
/* 7AACBC0 80080E90 3003638C */  lw         $v1, %lo(D_80070328 + 8)($v1)
/* 7AACBC4 80080E94 0780043C */  lui        $a0, %hi(D_80070328 + 0x44)
/* 7AACBC8 80080E98 6C03848C */  lw         $a0, %lo(D_80070328 + 0x44)($a0)
/* 7AACBCC 80080E9C 23104300 */  subu       $v0, $v0, $v1
/* 7AACBD0 80080EA0 21104400 */  addu       $v0, $v0, $a0
/* 7AACBD4 80080EA4 02004104 */  bgez       $v0, .Llevel_37_80080EB0
/* 7AACBD8 80080EA8 00000000 */   nop
/* 7AACBDC 80080EAC 23100200 */  negu       $v0, $v0
.Llevel_37_80080EB0:
/* 7AACBE0 80080EB0 F4014228 */  slti       $v0, $v0, 0x1F4
/* 7AACBE4 80080EB4 36004010 */  beqz       $v0, .Llevel_37_80080F90
/* 7AACBE8 80080EB8 02000224 */   addiu     $v0, $zero, 0x2
/* 7AACBEC 80080EBC 49004392 */  lbu        $v1, 0x49($s2)
/* 7AACBF0 80080EC0 00000000 */  nop
/* 7AACBF4 80080EC4 30006210 */  beq        $v1, $v0, .Llevel_37_80080F88
/* 7AACBF8 80080EC8 03006228 */   slti      $v0, $v1, 0x3
/* 7AACBFC 80080ECC 05004010 */  beqz       $v0, .Llevel_37_80080EE4
/* 7AACC00 80080ED0 01000224 */   addiu     $v0, $zero, 0x1
/* 7AACC04 80080ED4 0A006210 */  beq        $v1, $v0, .Llevel_37_80080F00
/* 7AACC08 80080ED8 04000424 */   addiu     $a0, $zero, 0x4
/* 7AACC0C 80080EDC E3030208 */  j          .Llevel_37_80080F8C
/* 7AACC10 80080EE0 03000224 */   addiu     $v0, $zero, 0x3
.Llevel_37_80080EE4:
/* 7AACC14 80080EE4 03000224 */  addiu      $v0, $zero, 0x3
/* 7AACC18 80080EE8 15006210 */  beq        $v1, $v0, .Llevel_37_80080F40
/* 7AACC1C 80080EEC 04000224 */   addiu     $v0, $zero, 0x4
/* 7AACC20 80080EF0 21006210 */  beq        $v1, $v0, .Llevel_37_80080F78
/* 7AACC24 80080EF4 01000324 */   addiu     $v1, $zero, 0x1
/* 7AACC28 80080EF8 E3030208 */  j          .Llevel_37_80080F8C
/* 7AACC2C 80080EFC 03000224 */   addiu     $v0, $zero, 0x3
.Llevel_37_80080F00:
/* 7AACC30 80080F00 A4010324 */  addiu      $v1, $zero, 0x1A4
/* 7AACC34 80080F04 0780063C */  lui        $a2, %hi(unk_ovlheader_800743B8)
/* 7AACC38 80080F08 B843C68C */  lw         $a2, %lo(unk_ovlheader_800743B8)($a2)
/* 7AACC3C 80080F0C 0780073C */  lui        $a3, %hi(unk_ovlheader_800743C0)
/* 7AACC40 80080F10 C043E78C */  lw         $a3, %lo(unk_ovlheader_800743C0)($a3)
/* 7AACC44 80080F14 CC010226 */  addiu      $v0, $s0, 0x1CC
/* 7AACC48 80080F18 CC0103AE */  sw         $v1, 0x1CC($s0)
/* 7AACC4C 80080F1C 1400A2AF */  sw         $v0, 0x14($sp)
/* 7AACC50 80080F20 0780023C */  lui        $v0, %hi(unk_ovlheader_800743BC)
/* 7AACC54 80080F24 BC43428C */  lw         $v0, %lo(unk_ovlheader_800743BC)($v0)
/* 7AACC58 80080F28 08000524 */  addiu      $a1, $zero, 0x8
/* 7AACC5C 80080F2C 1800A3AF */  sw         $v1, 0x18($sp)
/* 7AACC60 80080F30 0FA0000C */  jal        func_8002803C
/* 7AACC64 80080F34 1000A2AF */   sw        $v0, 0x10($sp)
/* 7AACC68 80080F38 E3030208 */  j          .Llevel_37_80080F8C
/* 7AACC6C 80080F3C 03000224 */   addiu     $v0, $zero, 0x3
.Llevel_37_80080F40:
/* 7AACC70 80080F40 0780023C */  lui        $v0, %hi(D_80070328 + 0x1E8)
/* 7AACC74 80080F44 1005428C */  lw         $v0, %lo(D_80070328 + 0x1E8)($v0)
/* 7AACC78 80080F48 00000000 */  nop
/* 7AACC7C 80080F4C 32004224 */  addiu      $v0, $v0, 0x32
/* 7AACC80 80080F50 0780013C */  lui        $at, %hi(D_80070328 + 0x1E8)
/* 7AACC84 80080F54 100522AC */  sw         $v0, %lo(D_80070328 + 0x1E8)($at)
/* 7AACC88 80080F58 C9004228 */  slti       $v0, $v0, 0xC9
/* 7AACC8C 80080F5C 0B004014 */  bnez       $v0, .Llevel_37_80080F8C
/* 7AACC90 80080F60 03000224 */   addiu     $v0, $zero, 0x3
/* 7AACC94 80080F64 C8000224 */  addiu      $v0, $zero, 0xC8
/* 7AACC98 80080F68 0780013C */  lui        $at, %hi(D_80070328 + 0x1E8)
/* 7AACC9C 80080F6C 100522AC */  sw         $v0, %lo(D_80070328 + 0x1E8)($at)
/* 7AACCA0 80080F70 E3030208 */  j          .Llevel_37_80080F8C
/* 7AACCA4 80080F74 03000224 */   addiu     $v0, $zero, 0x3
.Llevel_37_80080F78:
/* 7AACCA8 80080F78 6C00E28E */  lw         $v0, 0x6C($s7)
/* 7AACCAC 80080F7C 7000E3A2 */  sb         $v1, 0x70($s7)
/* 7AACCB0 80080F80 01004224 */  addiu      $v0, $v0, 0x1
/* 7AACCB4 80080F84 6C00E2AE */  sw         $v0, 0x6C($s7)
.Llevel_37_80080F88:
/* 7AACCB8 80080F88 03000224 */  addiu      $v0, $zero, 0x3
.Llevel_37_80080F8C:
/* 7AACCBC 80080F8C 480042A2 */  sb         $v0, 0x48($s2)
.Llevel_37_80080F90:
/* 7AACCC0 80080F90 E000BF8F */  lw         $ra, 0xE0($sp)
/* 7AACCC4 80080F94 DC00B78F */  lw         $s7, 0xDC($sp)
/* 7AACCC8 80080F98 D800B68F */  lw         $s6, 0xD8($sp)
/* 7AACCCC 80080F9C D400B58F */  lw         $s5, 0xD4($sp)
/* 7AACCD0 80080FA0 D000B48F */  lw         $s4, 0xD0($sp)
/* 7AACCD4 80080FA4 CC00B38F */  lw         $s3, 0xCC($sp)
/* 7AACCD8 80080FA8 C800B28F */  lw         $s2, 0xC8($sp)
/* 7AACCDC 80080FAC C400B18F */  lw         $s1, 0xC4($sp)
/* 7AACCE0 80080FB0 C000B08F */  lw         $s0, 0xC0($sp)
/* 7AACCE4 80080FB4 E800BD27 */  addiu      $sp, $sp, 0xE8
/* 7AACCE8 80080FB8 0800E003 */  jr         $ra
/* 7AACCEC 80080FBC 00000000 */   nop
.size func_level_37_8007FC30, . - func_level_37_8007FC30
