.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_37_80074730
/* 7AA0460 80074730 44190880 */ .word .L80081944_
/* 7AA0464 80074734 E81B0880 */ .word .L80081BE8_
/* 7AA0468 80074738 081D0880 */ .word .L80081D08_
/* 7AA046C 8007473C 6C1E0880 */ .word .L80081E6C_
/* 7AA0470 80074740 181F0880 */ .word .L80081F18_
/* 7AA0474 80074744 E81F0880 */ .word .L80081FE8_
/* 7AA0478 80074748 3C210880 */ .word .L8008213C_
/* 7AA047C 8007474C CC210880 */ .word .L800821CC_
/* 7AA0480 80074750 98220880 */ .word .L80082298_
/* 7AA0484 80074754 FC230880 */ .word .L800823FC_
/* 7AA0488 80074758 B8240880 */ .word .L800824B8_
/* 7AA048C 8007475C 6C250880 */ .word .L8008256C_
.size jtbl_level_37_80074730, . - jtbl_level_37_80074730


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_37_800818EC
/* 7AAD61C 800818EC 68FFBD27 */  addiu      $sp, $sp, -0x98
/* 7AAD620 800818F0 7800B2AF */  sw         $s2, 0x78($sp)
/* 7AAD624 800818F4 21908000 */  addu       $s2, $a0, $zero
/* 7AAD628 800818F8 9000BFAF */  sw         $ra, 0x90($sp)
/* 7AAD62C 800818FC 8C00B7AF */  sw         $s7, 0x8C($sp)
/* 7AAD630 80081900 8800B6AF */  sw         $s6, 0x88($sp)
/* 7AAD634 80081904 8400B5AF */  sw         $s5, 0x84($sp)
/* 7AAD638 80081908 8000B4AF */  sw         $s4, 0x80($sp)
/* 7AAD63C 8008190C 7C00B3AF */  sw         $s3, 0x7C($sp)
/* 7AAD640 80081910 7400B1AF */  sw         $s1, 0x74($sp)
/* 7AAD644 80081914 7000B0AF */  sw         $s0, 0x70($sp)
/* 7AAD648 80081918 48004392 */  lbu        $v1, 0x48($s2)
/* 7AAD64C 8008191C 0000548E */  lw         $s4, 0x0($s2)
/* 7AAD650 80081920 0C00622C */  sltiu      $v0, $v1, 0xC
/* 7AAD654 80081924 42034010 */  beqz       $v0, .Llevel_37_80082630
/* 7AAD658 80081928 80100300 */   sll       $v0, $v1, 2
/* 7AAD65C 8008192C 0780013C */  lui        $at, %hi(jtbl_level_37_80074730)
/* 7AAD660 80081930 21082200 */  addu       $at, $at, $v0
/* 7AAD664 80081934 3047228C */  lw         $v0, %lo(jtbl_level_37_80074730)($at)
/* 7AAD668 80081938 00000000 */  nop
/* 7AAD66C 8008193C 08004000 */  jr         $v0
/* 7AAD670 80081940 00000000 */   nop
.L80081944_:
/* 7AAD674 80081944 49004392 */  lbu        $v1, 0x49($s2)
/* 7AAD678 80081948 00000000 */  nop
/* 7AAD67C 8008194C 05006010 */  beqz       $v1, .Llevel_37_80081964
/* 7AAD680 80081950 01000224 */   addiu     $v0, $zero, 0x1
/* 7AAD684 80081954 98006210 */  beq        $v1, $v0, .Llevel_37_80081BB8
/* 7AAD688 80081958 21204002 */   addu      $a0, $s2, $zero
/* 7AAD68C 8008195C 8C090208 */  j          .Llevel_37_80082630
/* 7AAD690 80081960 00000000 */   nop
.Llevel_37_80081964:
/* 7AAD694 80081964 0780033C */  lui        $v1, %hi(D_8006C5BC)
/* 7AAD698 80081968 BCC5638C */  lw         $v1, %lo(D_8006C5BC)($v1)
/* 7AAD69C 8008196C 1E000224 */  addiu      $v0, $zero, 0x1E
/* 7AAD6A0 80081970 0A006210 */  beq        $v1, $v0, .Llevel_37_8008199C
/* 7AAD6A4 80081974 21204002 */   addu      $a0, $s2, $zero
/* 7AAD6A8 80081978 0780023C */  lui        $v0, %hi(D_80071588)
/* 7AAD6AC 8008197C 88154290 */  lbu        $v0, %lo(D_80071588)($v0)
/* 7AAD6B0 80081980 00000000 */  nop
/* 7AAD6B4 80081984 05004014 */  bnez       $v0, .Llevel_37_8008199C
/* 7AAD6B8 80081988 00000000 */   nop
/* 7AAD6BC 8008198C C656010C */  jal        func_80055B18
/* 7AAD6C0 80081990 21204002 */   addu      $a0, $s2, $zero
/* 7AAD6C4 80081994 8F090208 */  j          .Llevel_37_8008263C
/* 7AAD6C8 80081998 00000000 */   nop
.Llevel_37_8008199C:
/* 7AAD6CC 8008199C E0D3000C */  jal        func_80034F80
/* 7AAD6D0 800819A0 02000524 */   addiu     $a1, $zero, 0x2
/* 7AAD6D4 800819A4 1400448E */  lw         $a0, 0x14($s2)
/* 7AAD6D8 800819A8 0780033C */  lui        $v1, %hi(D_8006C5BC)
/* 7AAD6DC 800819AC BCC5638C */  lw         $v1, %lo(D_8006C5BC)($v1)
/* 7AAD6E0 800819B0 00108224 */  addiu      $v0, $a0, 0x1000
/* 7AAD6E4 800819B4 140042AE */  sw         $v0, 0x14($s2)
/* 7AAD6E8 800819B8 25000224 */  addiu      $v0, $zero, 0x25
/* 7AAD6EC 800819BC 03006214 */  bne        $v1, $v0, .Llevel_37_800819CC
/* 7AAD6F0 800819C0 0110153C */   lui       $s5, (0x1001A000 >> 16)
/* 7AAD6F4 800819C4 00188224 */  addiu      $v0, $a0, 0x1800
/* 7AAD6F8 800819C8 140042AE */  sw         $v0, 0x14($s2)
.Llevel_37_800819CC:
/* 7AAD6FC 800819CC 00A0B536 */  ori        $s5, $s5, (0x1001A000 & 0xFFFF)
/* 7AAD700 800819D0 0780113C */  lui        $s1, %hi(D_80070328 + 0x20C)
/* 7AAD704 800819D4 34053126 */  addiu      $s1, $s1, %lo(D_80070328 + 0x20C)
/* 7AAD708 800819D8 20003726 */  addiu      $s7, $s1, 0x20
/* 7AAD70C 800819DC 2120E002 */  addu       $a0, $s7, $zero
/* 7AAD710 800819E0 0C005326 */  addiu      $s3, $s2, 0xC
/* 7AAD714 800819E4 21286002 */  addu       $a1, $s3, $zero
/* 7AAD718 800819E8 000035AE */  sw         $s5, 0x0($s1)
/* 7AAD71C 800819EC 5E3C010C */  jal        func_8004F178
/* 7AAD720 800819F0 300020AE */   sw        $zero, 0x30($s1)
/* 7AAD724 800819F4 49005026 */  addiu      $s0, $s2, 0x49
/* 7AAD728 800819F8 2800228E */  lw         $v0, 0x28($s1)
/* 7AAD72C 800819FC 38FE238E */  lw         $v1, -0x1C8($s1)
/* 7AAD730 80081A00 04064224 */  addiu      $v0, $v0, 0x604
/* 7AAD734 80081A04 21104300 */  addu       $v0, $v0, $v1
/* 7AAD738 80081A08 280022AE */  sw         $v0, 0x28($s1)
/* 7AAD73C 80081A0C 44004292 */  lbu        $v0, 0x44($s2)
/* 7AAD740 80081A10 21200002 */  addu       $a0, $s0, $zero
/* 7AAD744 80081A14 1C0022A2 */  sb         $v0, 0x1C($s1)
/* 7AAD748 80081A18 45004292 */  lbu        $v0, 0x45($s2)
/* 7AAD74C 80081A1C 01000524 */  addiu      $a1, $zero, 0x1
/* 7AAD750 80081A20 1D0022A2 */  sb         $v0, 0x1D($s1)
/* 7AAD754 80081A24 46004292 */  lbu        $v0, 0x46($s2)
/* 7AAD758 80081A28 0780063C */  lui        $a2, %hi(D_8006D088)
/* 7AAD75C 80081A2C 88D0C624 */  addiu      $a2, $a2, %lo(D_8006D088)
/* 7AAD760 80081A30 1E0022A2 */  sb         $v0, 0x1E($s1)
/* 7AAD764 80081A34 01000224 */  addiu      $v0, $zero, 0x1
/* 7AAD768 80081A38 EDED000C */  jal        func_8003B7B4
/* 7AAD76C 80081A3C 490042A2 */   sb        $v0, 0x49($s2)
/* 7AAD770 80081A40 21200002 */  addu       $a0, $s0, $zero
/* 7AAD774 80081A44 0780063C */  lui        $a2, %hi(D_8006C7F8)
/* 7AAD778 80081A48 F8C7C624 */  addiu      $a2, $a2, %lo(D_8006C7F8)
/* 7AAD77C 80081A4C EDED000C */  jal        func_8003B7B4
/* 7AAD780 80081A50 01000524 */   addiu     $a1, $zero, 0x1
/* 7AAD784 80081A54 08001624 */  addiu      $s6, $zero, 0x8
/* 7AAD788 80081A58 480056A2 */  sb         $s6, 0x48($s2)
/* 7AAD78C 80081A5C 0780043C */  lui        $a0, %hi(D_8006C73C)
/* 7AAD790 80081A60 3CC7848C */  lw         $a0, %lo(D_8006C73C)($a0)
/* 7AAD794 80081A64 00000000 */  nop
/* 7AAD798 80081A68 4C008010 */  beqz       $a0, .Llevel_37_80081B9C
/* 7AAD79C 80081A6C 00000000 */   nop
/* 7AAD7A0 80081A70 0780023C */  lui        $v0, %hi(D_8006C5BC)
/* 7AAD7A4 80081A74 BCC5428C */  lw         $v0, %lo(D_8006C5BC)($v0)
/* 7AAD7A8 80081A78 00000000 */  nop
/* 7AAD7AC 80081A7C 47004410 */  beq        $v0, $a0, .Llevel_37_80081B9C
/* 7AAD7B0 80081A80 6666023C */   lui       $v0, (0x66666667 >> 16)
/* 7AAD7B4 80081A84 67664234 */  ori        $v0, $v0, (0x66666667 & 0xFFFF)
/* 7AAD7B8 80081A88 18008200 */  mult       $a0, $v0
/* 7AAD7BC 80081A8C C3170400 */  sra        $v0, $a0, 31
/* 7AAD7C0 80081A90 10480000 */  mfhi       $t1
/* 7AAD7C4 80081A94 83180900 */  sra        $v1, $t1, 2
/* 7AAD7C8 80081A98 23186200 */  subu       $v1, $v1, $v0
/* 7AAD7CC 80081A9C 80100300 */  sll        $v0, $v1, 2
/* 7AAD7D0 80081AA0 21104300 */  addu       $v0, $v0, $v1
/* 7AAD7D4 80081AA4 40100200 */  sll        $v0, $v0, 1
/* 7AAD7D8 80081AA8 23188200 */  subu       $v1, $a0, $v0
/* 7AAD7DC 80081AAC 05006010 */  beqz       $v1, .Llevel_37_80081AC4
/* 7AAD7E0 80081AB0 07000224 */   addiu     $v0, $zero, 0x7
/* 7AAD7E4 80081AB4 39006214 */  bne        $v1, $v0, .Llevel_37_80081B9C
/* 7AAD7E8 80081AB8 3C008228 */   slti      $v0, $a0, 0x3C
/* 7AAD7EC 80081ABC 37004010 */  beqz       $v0, .Llevel_37_80081B9C
/* 7AAD7F0 80081AC0 00000000 */   nop
.Llevel_37_80081AC4:
/* 7AAD7F4 80081AC4 36004386 */  lh         $v1, 0x36($s2)
/* 7AAD7F8 80081AC8 0780023C */  lui        $v0, %hi(D_8006C528)
/* 7AAD7FC 80081ACC 28C5428C */  lw         $v0, %lo(D_8006C528)($v0)
/* 7AAD800 80081AD0 00000000 */  nop
/* 7AAD804 80081AD4 31006214 */  bne        $v1, $v0, .Llevel_37_80081B9C
/* 7AAD808 80081AD8 2F000224 */   addiu     $v0, $zero, 0x2F
/* 7AAD80C 80081ADC 2F008210 */  beq        $a0, $v0, .Llevel_37_80081B9C
/* 7AAD810 80081AE0 21204002 */   addu      $a0, $s2, $zero
/* 7AAD814 80081AE4 E0D3000C */  jal        func_80034F80
/* 7AAD818 80081AE8 02000524 */   addiu     $a1, $zero, 0x2
/* 7AAD81C 80081AEC 1400428E */  lw         $v0, 0x14($s2)
/* 7AAD820 80081AF0 0780103C */  lui        $s0, %hi(D_8006E168)
/* 7AAD824 80081AF4 68E11026 */  addiu      $s0, $s0, %lo(D_8006E168)
/* 7AAD828 80081AF8 000C4224 */  addiu      $v0, $v0, 0xC00
/* 7AAD82C 80081AFC 140042AE */  sw         $v0, 0x14($s2)
/* 7AAD830 80081B00 0400828E */  lw         $v0, 0x4($s4)
/* 7AAD834 80081B04 21200002 */  addu       $a0, $s0, $zero
/* 7AAD838 80081B08 0C00458C */  lw         $a1, 0xC($v0)
/* 7AAD83C 80081B0C BC4D000C */  jal        func_800136F0
/* 7AAD840 80081B10 21306002 */   addu      $a2, $s3, $zero
/* 7AAD844 80081B14 2120E002 */  addu       $a0, $s7, $zero
/* 7AAD848 80081B18 0000028E */  lw         $v0, 0x0($s0)
/* 7AAD84C 80081B1C 0780033C */  lui        $v1, %hi(D_80070328 + 0x64)
/* 7AAD850 80081B20 8C03638C */  lw         $v1, %lo(D_80070328 + 0x64)($v1)
/* 7AAD854 80081B24 21286002 */  addu       $a1, $s3, $zero
/* 7AAD858 80081B28 0780013C */  lui        $at, %hi(D_8006E174)
/* 7AAD85C 80081B2C 74E120AC */  sw         $zero, %lo(D_8006E174)($at)
/* 7AAD860 80081B30 0780013C */  lui        $at, %hi(D_8006E178)
/* 7AAD864 80081B34 78E120AC */  sw         $zero, %lo(D_8006E178)($at)
/* 7AAD868 80081B38 000035AE */  sw         $s5, 0x0($s1)
/* 7AAD86C 80081B3C 300020AE */  sw         $zero, 0x30($s1)
/* 7AAD870 80081B40 23104300 */  subu       $v0, $v0, $v1
/* 7AAD874 80081B44 5E3C010C */  jal        func_8004F178
/* 7AAD878 80081B48 000002AE */   sw        $v0, 0x0($s0)
/* 7AAD87C 80081B4C 2800228E */  lw         $v0, 0x28($s1)
/* 7AAD880 80081B50 38FE238E */  lw         $v1, -0x1C8($s1)
/* 7AAD884 80081B54 04064224 */  addiu      $v0, $v0, 0x604
/* 7AAD888 80081B58 21104300 */  addu       $v0, $v0, $v1
/* 7AAD88C 80081B5C 280022AE */  sw         $v0, 0x28($s1)
/* 7AAD890 80081B60 44004292 */  lbu        $v0, 0x44($s2)
/* 7AAD894 80081B64 00000000 */  nop
/* 7AAD898 80081B68 1C0022A2 */  sb         $v0, 0x1C($s1)
/* 7AAD89C 80081B6C 45004292 */  lbu        $v0, 0x45($s2)
/* 7AAD8A0 80081B70 00000000 */  nop
/* 7AAD8A4 80081B74 1D0022A2 */  sb         $v0, 0x1D($s1)
/* 7AAD8A8 80081B78 46004292 */  lbu        $v0, 0x46($s2)
/* 7AAD8AC 80081B7C 21200002 */  addu       $a0, $s0, $zero
/* 7AAD8B0 80081B80 EA4A000C */  jal        func_80012BA8
/* 7AAD8B4 80081B84 1E0022A2 */   sb        $v0, 0x1E($s1)
/* 7AAD8B8 80081B88 14000426 */  addiu      $a0, $s0, 0x14
/* 7AAD8BC 80081B8C 5E3C010C */  jal        func_8004F178
/* 7AAD8C0 80081B90 F0FE0526 */   addiu     $a1, $s0, -0x110
/* 7AAD8C4 80081B94 8C090208 */  j          .Llevel_37_80082630
/* 7AAD8C8 80081B98 480056A2 */   sb        $s6, 0x48($s2)
.Llevel_37_80081B9C:
/* 7AAD8CC 80081B9C 48004292 */  lbu        $v0, 0x48($s2)
/* 7AAD8D0 80081BA0 00000000 */  nop
/* 7AAD8D4 80081BA4 A3024014 */  bnez       $v0, .Llevel_37_80082634
/* 7AAD8D8 80081BA8 21204002 */   addu      $a0, $s2, $zero
/* 7AAD8DC 80081BAC 01000224 */  addiu      $v0, $zero, 0x1
/* 7AAD8E0 80081BB0 8D090208 */  j          .Llevel_37_80082634
/* 7AAD8E4 80081BB4 480042A2 */   sb        $v0, 0x48($s2)
.Llevel_37_80081BB8:
/* 7AAD8E8 80081BB8 E0D3000C */  jal        func_80034F80
/* 7AAD8EC 80081BBC 02000524 */   addiu     $a1, $zero, 0x2
/* 7AAD8F0 80081BC0 21204002 */  addu       $a0, $s2, $zero
/* 7AAD8F4 80081BC4 1400428E */  lw         $v0, 0x14($s2)
/* 7AAD8F8 80081BC8 02000524 */  addiu      $a1, $zero, 0x2
/* 7AAD8FC 80081BCC 000F4224 */  addiu      $v0, $v0, 0xF00
/* 7AAD900 80081BD0 4957010C */  jal        func_80055D24
/* 7AAD904 80081BD4 140042AE */   sw        $v0, 0x14($s2)
/* 7AAD908 80081BD8 0A000224 */  addiu      $v0, $zero, 0xA
/* 7AAD90C 80081BDC 080080AE */  sw         $zero, 0x8($s4)
/* 7AAD910 80081BE0 8C090208 */  j          .Llevel_37_80082630
/* 7AAD914 80081BE4 480042A2 */   sb        $v0, 0x48($s2)
.L80081BE8_:
/* 7AAD918 80081BE8 49004392 */  lbu        $v1, 0x49($s2)
/* 7AAD91C 80081BEC 00000000 */  nop
/* 7AAD920 80081BF0 05006010 */  beqz       $v1, .Llevel_37_80081C08
/* 7AAD924 80081BF4 01000224 */   addiu     $v0, $zero, 0x1
/* 7AAD928 80081BF8 33006210 */  beq        $v1, $v0, .Llevel_37_80081CC8
/* 7AAD92C 80081BFC 1000A427 */   addiu     $a0, $sp, 0x10
/* 7AAD930 80081C00 3B070208 */  j          .Llevel_37_80081CEC
/* 7AAD934 80081C04 00000000 */   nop
.Llevel_37_80081C08:
/* 7AAD938 80081C08 46004292 */  lbu        $v0, 0x46($s2)
/* 7AAD93C 80081C0C 1000A427 */  addiu      $a0, $sp, 0x10
/* 7AAD940 80081C10 40100200 */  sll        $v0, $v0, 1
/* 7AAD944 80081C14 0680013C */  lui        $at, %hi(D_80065920)
/* 7AAD948 80081C18 21082200 */  addu       $at, $at, $v0
/* 7AAD94C 80081C1C 20592384 */  lh         $v1, %lo(D_80065920)($at)
/* 7AAD950 80081C20 21288000 */  addu       $a1, $a0, $zero
/* 7AAD954 80081C24 40100300 */  sll        $v0, $v1, 1
/* 7AAD958 80081C28 21104300 */  addu       $v0, $v0, $v1
/* 7AAD95C 80081C2C C3100200 */  sra        $v0, $v0, 3
/* 7AAD960 80081C30 1000A2AF */  sw         $v0, 0x10($sp)
/* 7AAD964 80081C34 46004292 */  lbu        $v0, 0x46($s2)
/* 7AAD968 80081C38 0C005026 */  addiu      $s0, $s2, 0xC
/* 7AAD96C 80081C3C 40100200 */  sll        $v0, $v0, 1
/* 7AAD970 80081C40 0680013C */  lui        $at, %hi(D_800658A0)
/* 7AAD974 80081C44 21082200 */  addu       $at, $at, $v0
/* 7AAD978 80081C48 A0582384 */  lh         $v1, %lo(D_800658A0)($at)
/* 7AAD97C 80081C4C 21300002 */  addu       $a2, $s0, $zero
/* 7AAD980 80081C50 1800A0AF */  sw         $zero, 0x18($sp)
/* 7AAD984 80081C54 40100300 */  sll        $v0, $v1, 1
/* 7AAD988 80081C58 21104300 */  addu       $v0, $v0, $v1
/* 7AAD98C 80081C5C C3100200 */  sra        $v0, $v0, 3
/* 7AAD990 80081C60 653C010C */  jal        func_8004F194
/* 7AAD994 80081C64 1400A2AF */   sw        $v0, 0x14($sp)
/* 7AAD998 80081C68 1000A427 */  addiu      $a0, $sp, 0x10
/* 7AAD99C 80081C6C 21300000 */  addu       $a2, $zero, $zero
/* 7AAD9A0 80081C70 46004592 */  lbu        $a1, 0x46($s2)
/* 7AAD9A4 80081C74 0780023C */  lui        $v0, %hi(unk_ovlheader_80074330)
/* 7AAD9A8 80081C78 3043428C */  lw         $v0, %lo(unk_ovlheader_80074330)($v0)
/* 7AAD9AC 80081C7C 00000000 */  nop
/* 7AAD9B0 80081C80 09F84000 */  jalr       $v0
/* 7AAD9B4 80081C84 8000A524 */   addiu     $a1, $a1, 0x80
/* 7AAD9B8 80081C88 18004010 */  beqz       $v0, .Llevel_37_80081CEC
/* 7AAD9BC 80081C8C 1000A427 */   addiu     $a0, $sp, 0x10
/* 7AAD9C0 80081C90 0780013C */  lui        $at, %hi(D_80070328 + 0x214)
/* 7AAD9C4 80081C94 3C0520AC */  sw         $zero, %lo(D_80070328 + 0x214)($at)
/* 7AAD9C8 80081C98 5E3C010C */  jal        func_8004F178
/* 7AAD9CC 80081C9C 21280002 */   addu      $a1, $s0, $zero
/* 7AAD9D0 80081CA0 1000A427 */  addiu      $a0, $sp, 0x10
/* 7AAD9D4 80081CA4 1800A28F */  lw         $v0, 0x18($sp)
/* 7AAD9D8 80081CA8 0780033C */  lui        $v1, %hi(unk_ovlheader_80074334)
/* 7AAD9DC 80081CAC 3443638C */  lw         $v1, %lo(unk_ovlheader_80074334)($v1)
/* 7AAD9E0 80081CB0 80024224 */  addiu      $v0, $v0, 0x280
/* 7AAD9E4 80081CB4 09F86000 */  jalr       $v1
/* 7AAD9E8 80081CB8 1800A2AF */   sw        $v0, 0x18($sp)
/* 7AAD9EC 80081CBC 01000224 */  addiu      $v0, $zero, 0x1
/* 7AAD9F0 80081CC0 3B070208 */  j          .Llevel_37_80081CEC
/* 7AAD9F4 80081CC4 490042A2 */   sb        $v0, 0x49($s2)
.Llevel_37_80081CC8:
/* 7AAD9F8 80081CC8 5E3C010C */  jal        func_8004F178
/* 7AAD9FC 80081CCC 0C004526 */   addiu     $a1, $s2, 0xC
/* 7AADA00 80081CD0 1000A427 */  addiu      $a0, $sp, 0x10
/* 7AADA04 80081CD4 1800A28F */  lw         $v0, 0x18($sp)
/* 7AADA08 80081CD8 0780033C */  lui        $v1, %hi(unk_ovlheader_80074334)
/* 7AADA0C 80081CDC 3443638C */  lw         $v1, %lo(unk_ovlheader_80074334)($v1)
/* 7AADA10 80081CE0 80024224 */  addiu      $v0, $v0, 0x280
/* 7AADA14 80081CE4 09F86000 */  jalr       $v1
/* 7AADA18 80081CE8 1800A2AF */   sw        $v0, 0x18($sp)
.Llevel_37_80081CEC:
/* 7AADA1C 80081CEC 0780023C */  lui        $v0, %hi(D_80070328 + 0x13C)
/* 7AADA20 80081CF0 6404428C */  lw         $v0, %lo(D_80070328 + 0x13C)($v0)
/* 7AADA24 80081CF4 00000000 */  nop
/* 7AADA28 80081CF8 4E025214 */  bne        $v0, $s2, .Llevel_37_80082634
/* 7AADA2C 80081CFC 21204002 */   addu      $a0, $s2, $zero
/* 7AADA30 80081D00 02000224 */  addiu      $v0, $zero, 0x2
/* 7AADA34 80081D04 480042A2 */  sb         $v0, 0x48($s2)
.L80081D08_:
/* 7AADA38 80081D08 0780103C */  lui        $s0, %hi(D_80070328 + 0x13C)
/* 7AADA3C 80081D0C 64041026 */  addiu      $s0, $s0, %lo(D_80070328 + 0x13C)
/* 7AADA40 80081D10 0000028E */  lw         $v0, 0x0($s0)
/* 7AADA44 80081D14 00000000 */  nop
/* 7AADA48 80081D18 05005210 */  beq        $v0, $s2, .Llevel_37_80081D30
/* 7AADA4C 80081D1C 01000224 */   addiu     $v0, $zero, 0x1
/* 7AADA50 80081D20 0780013C */  lui        $at, %hi(D_8006E160)
/* 7AADA54 80081D24 60E120AC */  sw         $zero, %lo(D_8006E160)($at)
/* 7AADA58 80081D28 8C090208 */  j          .Llevel_37_80082630
/* 7AADA5C 80081D2C 480042A2 */   sb        $v0, 0x48($s2)
.Llevel_37_80081D30:
/* 7AADA60 80081D30 0C005126 */  addiu      $s1, $s2, 0xC
/* 7AADA64 80081D34 21202002 */  addu       $a0, $s1, $zero
/* 7AADA68 80081D38 46004592 */  lbu        $a1, 0x46($s2)
/* 7AADA6C 80081D3C 0780023C */  lui        $v0, %hi(unk_ovlheader_80074330)
/* 7AADA70 80081D40 3043428C */  lw         $v0, %lo(unk_ovlheader_80074330)($v0)
/* 7AADA74 80081D44 00000000 */  nop
/* 7AADA78 80081D48 09F84000 */  jalr       $v0
/* 7AADA7C 80081D4C 21300000 */   addu      $a2, $zero, $zero
/* 7AADA80 80081D50 33004010 */  beqz       $v0, .Llevel_37_80081E20
/* 7AADA84 80081D54 6666033C */   lui       $v1, (0x66666667 >> 16)
/* 7AADA88 80081D58 0780023C */  lui        $v0, %hi(D_8006C5BC)
/* 7AADA8C 80081D5C BCC5428C */  lw         $v0, %lo(D_8006C5BC)($v0)
/* 7AADA90 80081D60 67666334 */  ori        $v1, $v1, (0x66666667 & 0xFFFF)
/* 7AADA94 80081D64 18004300 */  mult       $v0, $v1
/* 7AADA98 80081D68 21204002 */  addu       $a0, $s2, $zero
/* 7AADA9C 80081D6C C3170200 */  sra        $v0, $v0, 31
/* 7AADAA0 80081D70 10480000 */  mfhi       $t1
/* 7AADAA4 80081D74 83180900 */  sra        $v1, $t1, 2
/* 7AADAA8 80081D78 23186200 */  subu       $v1, $v1, $v0
/* 7AADAAC 80081D7C 01006324 */  addiu      $v1, $v1, 0x1
/* 7AADAB0 80081D80 80100300 */  sll        $v0, $v1, 2
/* 7AADAB4 80081D84 21104300 */  addu       $v0, $v0, $v1
/* 7AADAB8 80081D88 40100200 */  sll        $v0, $v0, 1
/* 7AADABC 80081D8C 0780013C */  lui        $at, %hi(D_8007015A)
/* 7AADAC0 80081D90 5A0122A4 */  sh         $v0, %lo(D_8007015A)($at)
/* 7AADAC4 80081D94 D0D3000C */  jal        func_80034F40
/* 7AADAC8 80081D98 01000524 */   addiu     $a1, $zero, 0x1
/* 7AADACC 80081D9C 0110023C */  lui        $v0, (0x10018000 >> 16)
/* 7AADAD0 80081DA0 00804234 */  ori        $v0, $v0, (0x10018000 & 0xFFFF)
/* 7AADAD4 80081DA4 F0001026 */  addiu      $s0, $s0, 0xF0
/* 7AADAD8 80081DA8 21200002 */  addu       $a0, $s0, $zero
/* 7AADADC 80081DAC 0780013C */  lui        $at, %hi(D_80070328 + 0x20C)
/* 7AADAE0 80081DB0 340522AC */  sw         $v0, %lo(D_80070328 + 0x20C)($at)
/* 7AADAE4 80081DB4 5E3C010C */  jal        func_8004F178
/* 7AADAE8 80081DB8 21282002 */   addu      $a1, $s1, $zero
/* 7AADAEC 80081DBC 21200002 */  addu       $a0, $s0, $zero
/* 7AADAF0 80081DC0 0780023C */  lui        $v0, %hi(D_80070328 + 0x234)
/* 7AADAF4 80081DC4 5C05428C */  lw         $v0, %lo(D_80070328 + 0x234)($v0)
/* 7AADAF8 80081DC8 00000000 */  nop
/* 7AADAFC 80081DCC 00044224 */  addiu      $v0, $v0, 0x400
/* 7AADB00 80081DD0 0780013C */  lui        $at, %hi(D_80070328 + 0x234)
/* 7AADB04 80081DD4 5C0522AC */  sw         $v0, %lo(D_80070328 + 0x234)($at)
/* 7AADB08 80081DD8 D668000C */  jal        func_8001A358
/* 7AADB0C 80081DDC 00080524 */   addiu     $a1, $zero, 0x800
/* 7AADB10 80081DE0 0780033C */  lui        $v1, %hi(D_80070328 + 0x44)
/* 7AADB14 80081DE4 6C03638C */  lw         $v1, %lo(D_80070328 + 0x44)($v1)
/* 7AADB18 80081DE8 0780013C */  lui        $at, %hi(D_80070328 + 0x23C)
/* 7AADB1C 80081DEC 640520AC */  sw         $zero, %lo(D_80070328 + 0x23C)($at)
/* 7AADB20 80081DF0 0780013C */  lui        $at, %hi(D_80070328 + 0x228)
/* 7AADB24 80081DF4 500520A0 */  sb         $zero, %lo(D_80070328 + 0x228)($at)
/* 7AADB28 80081DF8 0780013C */  lui        $at, %hi(D_80070328 + 0x229)
/* 7AADB2C 80081DFC 510520A0 */  sb         $zero, %lo(D_80070328 + 0x229)($at)
/* 7AADB30 80081E00 21104300 */  addu       $v0, $v0, $v1
/* 7AADB34 80081E04 0780013C */  lui        $at, %hi(D_80070328 + 0x234)
/* 7AADB38 80081E08 5C0522AC */  sw         $v0, %lo(D_80070328 + 0x234)($at)
/* 7AADB3C 80081E0C 46004292 */  lbu        $v0, 0x46($s2)
/* 7AADB40 80081E10 0780013C */  lui        $at, %hi(D_80070328 + 0x22A)
/* 7AADB44 80081E14 520522A0 */  sb         $v0, %lo(D_80070328 + 0x22A)($at)
/* 7AADB48 80081E18 04000224 */  addiu      $v0, $zero, 0x4
/* 7AADB4C 80081E1C 480042A2 */  sb         $v0, 0x48($s2)
.Llevel_37_80081E20:
/* 7AADB50 80081E20 0780103C */  lui        $s0, %hi(D_8006E17C)
/* 7AADB54 80081E24 7CE11026 */  addiu      $s0, $s0, %lo(D_8006E17C)
/* 7AADB58 80081E28 21200002 */  addu       $a0, $s0, $zero
/* 7AADB5C 80081E2C 5E3C010C */  jal        func_8004F178
/* 7AADB60 80081E30 21282002 */   addu      $a1, $s1, $zero
/* 7AADB64 80081E34 0400828E */  lw         $v0, 0x4($s4)
/* 7AADB68 80081E38 ECFF0426 */  addiu      $a0, $s0, -0x14
/* 7AADB6C 80081E3C 0C00458C */  lw         $a1, 0xC($v0)
/* 7AADB70 80081E40 BC4D000C */  jal        func_800136F0
/* 7AADB74 80081E44 21302002 */   addu      $a2, $s1, $zero
/* 7AADB78 80081E48 11000224 */  addiu      $v0, $zero, 0x11
/* 7AADB7C 80081E4C 0780013C */  lui        $at, %hi(D_8006E174)
/* 7AADB80 80081E50 74E120AC */  sw         $zero, %lo(D_8006E174)($at)
/* 7AADB84 80081E54 0780013C */  lui        $at, %hi(D_8006E178)
/* 7AADB88 80081E58 78E120AC */  sw         $zero, %lo(D_8006E178)($at)
/* 7AADB8C 80081E5C 0780013C */  lui        $at, %hi(D_8006E160)
/* 7AADB90 80081E60 60E122AC */  sw         $v0, %lo(D_8006E160)($at)
/* 7AADB94 80081E64 8D090208 */  j          .Llevel_37_80082634
/* 7AADB98 80081E68 21204002 */   addu      $a0, $s2, $zero
.L80081E6C_:
/* 7AADB9C 80081E6C 0780023C */  lui        $v0, %hi(D_8007015A)
/* 7AADBA0 80081E70 5A014284 */  lh         $v0, %lo(D_8007015A)($v0)
/* 7AADBA4 80081E74 0780013C */  lui        $at, %hi(D_8006E160)
/* 7AADBA8 80081E78 60E120AC */  sw         $zero, %lo(D_8006E160)($at)
/* 7AADBAC 80081E7C 8B014010 */  beqz       $v0, .Llevel_37_800824AC
/* 7AADBB0 80081E80 21204002 */   addu      $a0, $s2, $zero
/* 7AADBB4 80081E84 D0D3000C */  jal        func_80034F40
/* 7AADBB8 80081E88 01000524 */   addiu     $a1, $zero, 0x1
/* 7AADBBC 80081E8C 0110033C */  lui        $v1, (0x10018000 >> 16)
/* 7AADBC0 80081E90 00806334 */  ori        $v1, $v1, (0x10018000 & 0xFFFF)
/* 7AADBC4 80081E94 0780023C */  lui        $v0, %hi(D_80070328 + 0x20C)
/* 7AADBC8 80081E98 34054224 */  addiu      $v0, $v0, %lo(D_80070328 + 0x20C)
/* 7AADBCC 80081E9C 20005024 */  addiu      $s0, $v0, 0x20
/* 7AADBD0 80081EA0 21200002 */  addu       $a0, $s0, $zero
/* 7AADBD4 80081EA4 0C004526 */  addiu      $a1, $s2, 0xC
/* 7AADBD8 80081EA8 5E3C010C */  jal        func_8004F178
/* 7AADBDC 80081EAC 000043AC */   sw        $v1, 0x0($v0)
/* 7AADBE0 80081EB0 21200002 */  addu       $a0, $s0, $zero
/* 7AADBE4 80081EB4 0780023C */  lui        $v0, %hi(D_80070328 + 0x234)
/* 7AADBE8 80081EB8 5C05428C */  lw         $v0, %lo(D_80070328 + 0x234)($v0)
/* 7AADBEC 80081EBC 00000000 */  nop
/* 7AADBF0 80081EC0 00044224 */  addiu      $v0, $v0, 0x400
/* 7AADBF4 80081EC4 0780013C */  lui        $at, %hi(D_80070328 + 0x234)
/* 7AADBF8 80081EC8 5C0522AC */  sw         $v0, %lo(D_80070328 + 0x234)($at)
/* 7AADBFC 80081ECC D668000C */  jal        func_8001A358
/* 7AADC00 80081ED0 00080524 */   addiu     $a1, $zero, 0x800
/* 7AADC04 80081ED4 0780033C */  lui        $v1, %hi(D_80070328 + 0x44)
/* 7AADC08 80081ED8 6C03638C */  lw         $v1, %lo(D_80070328 + 0x44)($v1)
/* 7AADC0C 80081EDC 0780013C */  lui        $at, %hi(D_80070328 + 0x23C)
/* 7AADC10 80081EE0 640520AC */  sw         $zero, %lo(D_80070328 + 0x23C)($at)
/* 7AADC14 80081EE4 0780013C */  lui        $at, %hi(D_80070328 + 0x228)
/* 7AADC18 80081EE8 500520A0 */  sb         $zero, %lo(D_80070328 + 0x228)($at)
/* 7AADC1C 80081EEC 0780013C */  lui        $at, %hi(D_80070328 + 0x229)
/* 7AADC20 80081EF0 510520A0 */  sb         $zero, %lo(D_80070328 + 0x229)($at)
/* 7AADC24 80081EF4 21104300 */  addu       $v0, $v0, $v1
/* 7AADC28 80081EF8 0780013C */  lui        $at, %hi(D_80070328 + 0x234)
/* 7AADC2C 80081EFC 5C0522AC */  sw         $v0, %lo(D_80070328 + 0x234)($at)
/* 7AADC30 80081F00 46004292 */  lbu        $v0, 0x46($s2)
/* 7AADC34 80081F04 0780013C */  lui        $at, %hi(D_80070328 + 0x22A)
/* 7AADC38 80081F08 520522A0 */  sb         $v0, %lo(D_80070328 + 0x22A)($at)
/* 7AADC3C 80081F0C 04000224 */  addiu      $v0, $zero, 0x4
/* 7AADC40 80081F10 8C090208 */  j          .Llevel_37_80082630
/* 7AADC44 80081F14 480042A2 */   sb        $v0, 0x48($s2)
.L80081F18_:
/* 7AADC48 80081F18 0110023C */  lui        $v0, (0x10018000 >> 16)
/* 7AADC4C 80081F1C 00804234 */  ori        $v0, $v0, (0x10018000 & 0xFFFF)
/* 7AADC50 80081F20 0780103C */  lui        $s0, %hi(D_80070328 + 0x20C)
/* 7AADC54 80081F24 34051026 */  addiu      $s0, $s0, %lo(D_80070328 + 0x20C)
/* 7AADC58 80081F28 20000426 */  addiu      $a0, $s0, 0x20
/* 7AADC5C 80081F2C 000002AE */  sw         $v0, 0x0($s0)
/* 7AADC60 80081F30 0780023C */  lui        $v0, %hi(D_80070328 + 0x234)
/* 7AADC64 80081F34 5C05428C */  lw         $v0, %lo(D_80070328 + 0x234)($v0)
/* 7AADC68 80081F38 0780033C */  lui        $v1, %hi(D_80070328 + 0x44)
/* 7AADC6C 80081F3C 6C03638C */  lw         $v1, %lo(D_80070328 + 0x44)($v1)
/* 7AADC70 80081F40 00014224 */  addiu      $v0, $v0, 0x100
/* 7AADC74 80081F44 23104300 */  subu       $v0, $v0, $v1
/* 7AADC78 80081F48 0780013C */  lui        $at, %hi(D_80070328 + 0x234)
/* 7AADC7C 80081F4C 5C0522AC */  sw         $v0, %lo(D_80070328 + 0x234)($at)
/* 7AADC80 80081F50 D668000C */  jal        func_8001A358
/* 7AADC84 80081F54 00020524 */   addiu     $a1, $zero, 0x200
/* 7AADC88 80081F58 0780033C */  lui        $v1, %hi(D_80070328 + 0x44)
/* 7AADC8C 80081F5C 6C03638C */  lw         $v1, %lo(D_80070328 + 0x44)($v1)
/* 7AADC90 80081F60 0780013C */  lui        $at, %hi(D_80070328 + 0x23C)
/* 7AADC94 80081F64 640520AC */  sw         $zero, %lo(D_80070328 + 0x23C)($at)
/* 7AADC98 80081F68 0780013C */  lui        $at, %hi(D_80070328 + 0x228)
/* 7AADC9C 80081F6C 500520A0 */  sb         $zero, %lo(D_80070328 + 0x228)($at)
/* 7AADCA0 80081F70 0780013C */  lui        $at, %hi(D_80070328 + 0x229)
/* 7AADCA4 80081F74 510520A0 */  sb         $zero, %lo(D_80070328 + 0x229)($at)
/* 7AADCA8 80081F78 21104300 */  addu       $v0, $v0, $v1
/* 7AADCAC 80081F7C 0780013C */  lui        $at, %hi(D_80070328 + 0x234)
/* 7AADCB0 80081F80 5C0522AC */  sw         $v0, %lo(D_80070328 + 0x234)($at)
/* 7AADCB4 80081F84 46004292 */  lbu        $v0, 0x46($s2)
/* 7AADCB8 80081F88 0780033C */  lui        $v1, %hi(D_8006C770)
/* 7AADCBC 80081F8C 70C7638C */  lw         $v1, %lo(D_8006C770)($v1)
/* 7AADCC0 80081F90 0780013C */  lui        $at, %hi(D_80070328 + 0x22A)
/* 7AADCC4 80081F94 520522A0 */  sb         $v0, %lo(D_80070328 + 0x22A)($at)
/* 7AADCC8 80081F98 A5016010 */  beqz       $v1, .Llevel_37_80082630
/* 7AADCCC 80081F9C 21204002 */   addu      $a0, $s2, $zero
/* 7AADCD0 80081FA0 E0D3000C */  jal        func_80034F80
/* 7AADCD4 80081FA4 02000524 */   addiu     $a1, $zero, 0x2
/* 7AADCD8 80081FA8 0000028E */  lw         $v0, 0x0($s0)
/* 7AADCDC 80081FAC 0780033C */  lui        $v1, %hi(D_8006C65C)
/* 7AADCE0 80081FB0 5CC6638C */  lw         $v1, %lo(D_8006C65C)($v1)
/* 7AADCE4 80081FB4 00204234 */  ori        $v0, $v0, 0x2000
/* 7AADCE8 80081FB8 06006010 */  beqz       $v1, .Llevel_37_80081FD4
/* 7AADCEC 80081FBC 000002AE */   sw        $v0, 0x0($s0)
/* 7AADCF0 80081FC0 4C0060A0 */  sb         $zero, 0x4C($v1)
/* 7AADCF4 80081FC4 0780023C */  lui        $v0, %hi(D_8006C65C)
/* 7AADCF8 80081FC8 5CC6428C */  lw         $v0, %lo(D_8006C65C)($v0)
/* 7AADCFC 80081FCC 00000000 */  nop
/* 7AADD00 80081FD0 4D0040A0 */  sb         $zero, 0x4D($v0)
.Llevel_37_80081FD4:
/* 7AADD04 80081FD4 78000224 */  addiu      $v0, $zero, 0x78
/* 7AADD08 80081FD8 080082AE */  sw         $v0, 0x8($s4)
/* 7AADD0C 80081FDC 05000224 */  addiu      $v0, $zero, 0x5
/* 7AADD10 80081FE0 8C090208 */  j          .Llevel_37_80082630
/* 7AADD14 80081FE4 480042A2 */   sb        $v0, 0x48($s2)
.L80081FE8_:
/* 7AADD18 80081FE8 0110063C */  lui        $a2, (0x1001A000 >> 16)
/* 7AADD1C 80081FEC 00A0C634 */  ori        $a2, $a2, (0x1001A000 & 0xFFFF)
/* 7AADD20 80081FF0 0780033C */  lui        $v1, %hi(D_80070328 + 0x20C)
/* 7AADD24 80081FF4 34056324 */  addiu      $v1, $v1, %lo(D_80070328 + 0x20C)
/* 7AADD28 80081FF8 20006424 */  addiu      $a0, $v1, 0x20
/* 7AADD2C 80081FFC 0C005026 */  addiu      $s0, $s2, 0xC
/* 7AADD30 80082000 1400428E */  lw         $v0, 0x14($s2)
/* 7AADD34 80082004 00000000 */  nop
/* 7AADD38 80082008 40004224 */  addiu      $v0, $v0, 0x40
/* 7AADD3C 8008200C 140042AE */  sw         $v0, 0x14($s2)
/* 7AADD40 80082010 000066AC */  sw         $a2, 0x0($v1)
/* 7AADD44 80082014 0780013C */  lui        $at, %hi(D_80070328 + 0x23C)
/* 7AADD48 80082018 640520AC */  sw         $zero, %lo(D_80070328 + 0x23C)($at)
/* 7AADD4C 8008201C 5E3C010C */  jal        func_8004F178
/* 7AADD50 80082020 21280002 */   addu      $a1, $s0, $zero
/* 7AADD54 80082024 0780113C */  lui        $s1, %hi(D_8006E17C)
/* 7AADD58 80082028 7CE13126 */  addiu      $s1, $s1, %lo(D_8006E17C)
/* 7AADD5C 8008202C 21202002 */  addu       $a0, $s1, $zero
/* 7AADD60 80082030 0780023C */  lui        $v0, %hi(D_80070328 + 0x234)
/* 7AADD64 80082034 5C05428C */  lw         $v0, %lo(D_80070328 + 0x234)($v0)
/* 7AADD68 80082038 0780033C */  lui        $v1, %hi(D_80070328 + 0x44)
/* 7AADD6C 8008203C 6C03638C */  lw         $v1, %lo(D_80070328 + 0x44)($v1)
/* 7AADD70 80082040 0780063C */  lui        $a2, %hi(D_80070328 + 0xC)
/* 7AADD74 80082044 3403C690 */  lbu        $a2, %lo(D_80070328 + 0xC)($a2)
/* 7AADD78 80082048 0780073C */  lui        $a3, %hi(D_80070328 + 0xD)
/* 7AADD7C 8008204C 3503E790 */  lbu        $a3, %lo(D_80070328 + 0xD)($a3)
/* 7AADD80 80082050 0780083C */  lui        $t0, %hi(D_80070328 + 0xE)
/* 7AADD84 80082054 36030891 */  lbu        $t0, %lo(D_80070328 + 0xE)($t0)
/* 7AADD88 80082058 04064224 */  addiu      $v0, $v0, 0x604
/* 7AADD8C 8008205C 21104300 */  addu       $v0, $v0, $v1
/* 7AADD90 80082060 0780013C */  lui        $at, %hi(D_80070328 + 0x234)
/* 7AADD94 80082064 5C0522AC */  sw         $v0, %lo(D_80070328 + 0x234)($at)
/* 7AADD98 80082068 0780013C */  lui        $at, %hi(D_80070328 + 0x228)
/* 7AADD9C 8008206C 500526A0 */  sb         $a2, %lo(D_80070328 + 0x228)($at)
/* 7AADDA0 80082070 0780013C */  lui        $at, %hi(D_80070328 + 0x229)
/* 7AADDA4 80082074 510527A0 */  sb         $a3, %lo(D_80070328 + 0x229)($at)
/* 7AADDA8 80082078 0780013C */  lui        $at, %hi(D_80070328 + 0x22A)
/* 7AADDAC 8008207C 520528A0 */  sb         $t0, %lo(D_80070328 + 0x22A)($at)
/* 7AADDB0 80082080 5E3C010C */  jal        func_8004F178
/* 7AADDB4 80082084 21280002 */   addu      $a1, $s0, $zero
/* 7AADDB8 80082088 0400828E */  lw         $v0, 0x4($s4)
/* 7AADDBC 8008208C ECFF2426 */  addiu      $a0, $s1, -0x14
/* 7AADDC0 80082090 0C00458C */  lw         $a1, 0xC($v0)
/* 7AADDC4 80082094 BC4D000C */  jal        func_800136F0
/* 7AADDC8 80082098 21300002 */   addu      $a2, $s0, $zero
/* 7AADDCC 8008209C 08008426 */  addiu      $a0, $s4, 0x8
/* 7AADDD0 800820A0 11000224 */  addiu      $v0, $zero, 0x11
/* 7AADDD4 800820A4 0780013C */  lui        $at, %hi(D_8006E174)
/* 7AADDD8 800820A8 74E120AC */  sw         $zero, %lo(D_8006E174)($at)
/* 7AADDDC 800820AC 0780013C */  lui        $at, %hi(D_8006E178)
/* 7AADDE0 800820B0 78E120AC */  sw         $zero, %lo(D_8006E178)($at)
/* 7AADDE4 800820B4 0780013C */  lui        $at, %hi(D_8006E160)
/* 7AADDE8 800820B8 60E122AC */  sw         $v0, %lo(D_8006E160)($at)
/* 7AADDEC 800820BC 69D6000C */  jal        func_800359A4
/* 7AADDF0 800820C0 04000524 */   addiu     $a1, $zero, 0x4
/* 7AADDF4 800820C4 58014010 */  beqz       $v0, .Llevel_37_80082628
/* 7AADDF8 800820C8 21204002 */   addu      $a0, $s2, $zero
/* 7AADDFC 800820CC 0780023C */  lui        $v0, %hi(D_8006C598)
/* 7AADE00 800820D0 98C5428C */  lw         $v0, %lo(D_8006C598)($v0)
/* 7AADE04 800820D4 00000000 */  nop
/* 7AADE08 800820D8 10004224 */  addiu      $v0, $v0, 0x10
/* 7AADE0C 800820DC 0780013C */  lui        $at, %hi(D_8006C598)
/* 7AADE10 800820E0 98C522AC */  sw         $v0, %lo(D_8006C598)($at)
/* 7AADE14 800820E4 FF004228 */  slti       $v0, $v0, 0xFF
/* 7AADE18 800820E8 4F014014 */  bnez       $v0, .Llevel_37_80082628
/* 7AADE1C 800820EC FF000224 */   addiu     $v0, $zero, 0xFF
/* 7AADE20 800820F0 0780043C */  lui        $a0, %hi(D_800715BA)
/* 7AADE24 800820F4 BA158424 */  addiu      $a0, $a0, %lo(D_800715BA)
/* 7AADE28 800820F8 00008390 */  lbu        $v1, 0x0($a0)
/* 7AADE2C 800820FC 0780013C */  lui        $at, %hi(D_8006C598)
/* 7AADE30 80082100 98C522AC */  sw         $v0, %lo(D_8006C598)($at)
/* 7AADE34 80082104 07006010 */  beqz       $v1, .Llevel_37_80082124
/* 7AADE38 80082108 01000224 */   addiu     $v0, $zero, 0x1
/* 7AADE3C 8008210C 0780043C */  lui        $a0, %hi(D_8007015A)
/* 7AADE40 80082110 5A018484 */  lh         $a0, %lo(D_8007015A)($a0)
/* 7AADE44 80082114 E553010C */  jal        func_80054F94
/* 7AADE48 80082118 21284002 */   addu      $a1, $s2, $zero
/* 7AADE4C 8008211C 8A090208 */  j          .Llevel_37_80082628
/* 7AADE50 80082120 21204002 */   addu      $a0, $s2, $zero
.Llevel_37_80082124:
/* 7AADE54 80082124 000082A0 */  sb         $v0, 0x0($a0)
/* 7AADE58 80082128 06000424 */  addiu      $a0, $zero, 0x6
/* 7AADE5C 8008212C 2F61010C */  jal        func_800584BC
/* 7AADE60 80082130 44000524 */   addiu     $a1, $zero, 0x44
/* 7AADE64 80082134 8A090208 */  j          .Llevel_37_80082628
/* 7AADE68 80082138 21204002 */   addu      $a0, $s2, $zero
.L8008213C_:
/* 7AADE6C 8008213C 46004292 */  lbu        $v0, 0x46($s2)
/* 7AADE70 80082140 2000B027 */  addiu      $s0, $sp, 0x20
/* 7AADE74 80082144 40100200 */  sll        $v0, $v0, 1
/* 7AADE78 80082148 0680013C */  lui        $at, %hi(D_80065920)
/* 7AADE7C 8008214C 21082200 */  addu       $at, $at, $v0
/* 7AADE80 80082150 20592284 */  lh         $v0, %lo(D_80065920)($at)
/* 7AADE84 80082154 21200002 */  addu       $a0, $s0, $zero
/* 7AADE88 80082158 2000A2AF */  sw         $v0, 0x20($sp)
/* 7AADE8C 8008215C 46004292 */  lbu        $v0, 0x46($s2)
/* 7AADE90 80082160 21280002 */  addu       $a1, $s0, $zero
/* 7AADE94 80082164 40100200 */  sll        $v0, $v0, 1
/* 7AADE98 80082168 0680013C */  lui        $at, %hi(D_800658A0)
/* 7AADE9C 8008216C 21082200 */  addu       $at, $at, $v0
/* 7AADEA0 80082170 A0582284 */  lh         $v0, %lo(D_800658A0)($at)
/* 7AADEA4 80082174 0C004626 */  addiu      $a2, $s2, 0xC
/* 7AADEA8 80082178 2800A0AF */  sw         $zero, 0x28($sp)
/* 7AADEAC 8008217C 653C010C */  jal        func_8004F194
/* 7AADEB0 80082180 2400A2AF */   sw        $v0, 0x24($sp)
/* 7AADEB4 80082184 0780023C */  lui        $v0, %hi(unk_ovlheader_80074334)
/* 7AADEB8 80082188 3443428C */  lw         $v0, %lo(unk_ovlheader_80074334)($v0)
/* 7AADEBC 8008218C 00000000 */  nop
/* 7AADEC0 80082190 09F84000 */  jalr       $v0
/* 7AADEC4 80082194 21200002 */   addu      $a0, $s0, $zero
/* 7AADEC8 80082198 25014010 */  beqz       $v0, .Llevel_37_80082630
/* 7AADECC 8008219C 21200002 */   addu      $a0, $s0, $zero
/* 7AADED0 800821A0 0780013C */  lui        $at, %hi(D_80070328 + 0x214)
/* 7AADED4 800821A4 3C0520AC */  sw         $zero, %lo(D_80070328 + 0x214)($at)
/* 7AADED8 800821A8 46004592 */  lbu        $a1, 0x46($s2)
/* 7AADEDC 800821AC 0780023C */  lui        $v0, %hi(unk_ovlheader_80074330)
/* 7AADEE0 800821B0 3043428C */  lw         $v0, %lo(unk_ovlheader_80074330)($v0)
/* 7AADEE4 800821B4 00000000 */  nop
/* 7AADEE8 800821B8 09F84000 */  jalr       $v0
/* 7AADEEC 800821BC 21300000 */   addu      $a2, $zero, $zero
/* 7AADEF0 800821C0 07000224 */  addiu      $v0, $zero, 0x7
/* 7AADEF4 800821C4 8C090208 */  j          .Llevel_37_80082630
/* 7AADEF8 800821C8 480042A2 */   sb        $v0, 0x48($s2)
.L800821CC_:
/* 7AADEFC 800821CC 46004292 */  lbu        $v0, 0x46($s2)
/* 7AADF00 800821D0 3000B027 */  addiu      $s0, $sp, 0x30
/* 7AADF04 800821D4 40100200 */  sll        $v0, $v0, 1
/* 7AADF08 800821D8 0680013C */  lui        $at, %hi(D_80065920)
/* 7AADF0C 800821DC 21082200 */  addu       $at, $at, $v0
/* 7AADF10 800821E0 20592284 */  lh         $v0, %lo(D_80065920)($at)
/* 7AADF14 800821E4 21200002 */  addu       $a0, $s0, $zero
/* 7AADF18 800821E8 3000A2AF */  sw         $v0, 0x30($sp)
/* 7AADF1C 800821EC 46004292 */  lbu        $v0, 0x46($s2)
/* 7AADF20 800821F0 21280002 */  addu       $a1, $s0, $zero
/* 7AADF24 800821F4 40100200 */  sll        $v0, $v0, 1
/* 7AADF28 800821F8 0680013C */  lui        $at, %hi(D_800658A0)
/* 7AADF2C 800821FC 21082200 */  addu       $at, $at, $v0
/* 7AADF30 80082200 A0582284 */  lh         $v0, %lo(D_800658A0)($at)
/* 7AADF34 80082204 0C004626 */  addiu      $a2, $s2, 0xC
/* 7AADF38 80082208 3800A0AF */  sw         $zero, 0x38($sp)
/* 7AADF3C 8008220C 653C010C */  jal        func_8004F194
/* 7AADF40 80082210 3400A2AF */   sw        $v0, 0x34($sp)
/* 7AADF44 80082214 21200002 */  addu       $a0, $s0, $zero
/* 7AADF48 80082218 46004592 */  lbu        $a1, 0x46($s2)
/* 7AADF4C 8008221C 0780023C */  lui        $v0, %hi(unk_ovlheader_80074330)
/* 7AADF50 80082220 3043428C */  lw         $v0, %lo(unk_ovlheader_80074330)($v0)
/* 7AADF54 80082224 00000000 */  nop
/* 7AADF58 80082228 09F84000 */  jalr       $v0
/* 7AADF5C 8008222C 21300000 */   addu      $a2, $zero, $zero
/* 7AADF60 80082230 FF004010 */  beqz       $v0, .Llevel_37_80082630
/* 7AADF64 80082234 4000B027 */   addiu     $s0, $sp, 0x40
/* 7AADF68 80082238 0780053C */  lui        $a1, %hi(D_80070328)
/* 7AADF6C 8008223C 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 7AADF70 80082240 5E3C010C */  jal        func_8004F178
/* 7AADF74 80082244 21200002 */   addu      $a0, $s0, $zero
/* 7AADF78 80082248 0780043C */  lui        $a0, %hi(D_8006D088)
/* 7AADF7C 8008224C 88D08424 */  addiu      $a0, $a0, %lo(D_8006D088)
/* 7AADF80 80082250 21280002 */  addu       $a1, $s0, $zero
/* 7AADF84 80082254 4800A28F */  lw         $v0, 0x48($sp)
/* 7AADF88 80082258 0780033C */  lui        $v1, %hi(D_80070328 + 0x44)
/* 7AADF8C 8008225C 6C03638C */  lw         $v1, %lo(D_80070328 + 0x44)($v1)
/* 7AADF90 80082260 0780063C */  lui        $a2, %hi(D_80070328 + 0xE)
/* 7AADF94 80082264 3603C690 */  lbu        $a2, %lo(D_80070328 + 0xE)($a2)
/* 7AADF98 80082268 23104300 */  subu       $v0, $v0, $v1
/* 7AADF9C 8008226C 8DED000C */  jal        func_8003B634
/* 7AADFA0 80082270 4800A2AF */   sw        $v0, 0x48($sp)
/* 7AADFA4 80082274 21204002 */  addu       $a0, $s2, $zero
/* 7AADFA8 80082278 01000524 */  addiu      $a1, $zero, 0x1
/* 7AADFAC 8008227C 78000224 */  addiu      $v0, $zero, 0x78
/* 7AADFB0 80082280 080082AE */  sw         $v0, 0x8($s4)
/* 7AADFB4 80082284 D0D3000C */  jal        func_80034F40
/* 7AADFB8 80082288 490040A2 */   sb        $zero, 0x49($s2)
/* 7AADFBC 8008228C 0A000224 */  addiu      $v0, $zero, 0xA
/* 7AADFC0 80082290 8C090208 */  j          .Llevel_37_80082630
/* 7AADFC4 80082294 480042A2 */   sb        $v0, 0x48($s2)
.L80082298_:
/* 7AADFC8 80082298 0110033C */  lui        $v1, (0x1001A000 >> 16)
/* 7AADFCC 8008229C 00A06334 */  ori        $v1, $v1, (0x1001A000 & 0xFFFF)
/* 7AADFD0 800822A0 0780133C */  lui        $s3, %hi(D_80070328 + 0x20C)
/* 7AADFD4 800822A4 34057326 */  addiu      $s3, $s3, %lo(D_80070328 + 0x20C)
/* 7AADFD8 800822A8 20007526 */  addiu      $s5, $s3, 0x20
/* 7AADFDC 800822AC 2120A002 */  addu       $a0, $s5, $zero
/* 7AADFE0 800822B0 0C005126 */  addiu      $s1, $s2, 0xC
/* 7AADFE4 800822B4 1400428E */  lw         $v0, 0x14($s2)
/* 7AADFE8 800822B8 00000000 */  nop
/* 7AADFEC 800822BC C0FF4224 */  addiu      $v0, $v0, -0x40
/* 7AADFF0 800822C0 140042AE */  sw         $v0, 0x14($s2)
/* 7AADFF4 800822C4 000063AE */  sw         $v1, 0x0($s3)
/* 7AADFF8 800822C8 0780013C */  lui        $at, %hi(D_80070328 + 0x23C)
/* 7AADFFC 800822CC 640520AC */  sw         $zero, %lo(D_80070328 + 0x23C)($at)
/* 7AAE000 800822D0 5E3C010C */  jal        func_8004F178
/* 7AAE004 800822D4 21282002 */   addu      $a1, $s1, $zero
/* 7AAE008 800822D8 0780023C */  lui        $v0, %hi(D_80070328 + 0x234)
/* 7AAE00C 800822DC 5C05428C */  lw         $v0, %lo(D_80070328 + 0x234)($v0)
/* 7AAE010 800822E0 0780033C */  lui        $v1, %hi(D_80070328 + 0x44)
/* 7AAE014 800822E4 6C03638C */  lw         $v1, %lo(D_80070328 + 0x44)($v1)
/* 7AAE018 800822E8 04064224 */  addiu      $v0, $v0, 0x604
/* 7AAE01C 800822EC 21104300 */  addu       $v0, $v0, $v1
/* 7AAE020 800822F0 0780013C */  lui        $at, %hi(D_80070328 + 0x234)
/* 7AAE024 800822F4 5C0522AC */  sw         $v0, %lo(D_80070328 + 0x234)($at)
/* 7AAE028 800822F8 44004292 */  lbu        $v0, 0x44($s2)
/* 7AAE02C 800822FC 0780013C */  lui        $at, %hi(D_80070328 + 0x228)
/* 7AAE030 80082300 500522A0 */  sb         $v0, %lo(D_80070328 + 0x228)($at)
/* 7AAE034 80082304 45004292 */  lbu        $v0, 0x45($s2)
/* 7AAE038 80082308 0780013C */  lui        $at, %hi(D_80070328 + 0x229)
/* 7AAE03C 8008230C 510522A0 */  sb         $v0, %lo(D_80070328 + 0x229)($at)
/* 7AAE040 80082310 46004292 */  lbu        $v0, 0x46($s2)
/* 7AAE044 80082314 0780013C */  lui        $at, %hi(D_80070328 + 0x22A)
/* 7AAE048 80082318 520522A0 */  sb         $v0, %lo(D_80070328 + 0x22A)($at)
/* 7AAE04C 8008231C 0400828E */  lw         $v0, 0x4($s4)
/* 7AAE050 80082320 00000000 */  nop
/* 7AAE054 80082324 0C00448C */  lw         $a0, 0xC($v0)
/* 7AAE058 80082328 B94E000C */  jal        func_80013AE4
/* 7AAE05C 8008232C F4FD6526 */   addiu     $a1, $s3, -0x20C
/* 7AAE060 80082330 5000B027 */  addiu      $s0, $sp, 0x50
/* 7AAE064 80082334 21200002 */  addu       $a0, $s0, $zero
/* 7AAE068 80082338 5E3C010C */  jal        func_8004F178
/* 7AAE06C 8008233C 21282002 */   addu      $a1, $s1, $zero
/* 7AAE070 80082340 1400428E */  lw         $v0, 0x14($s2)
/* 7AAE074 80082344 21200002 */  addu       $a0, $s0, $zero
/* 7AAE078 80082348 00044224 */  addiu      $v0, $v0, 0x400
/* 7AAE07C 8008234C 140042AE */  sw         $v0, 0x14($s2)
/* 7AAE080 80082350 5800A28F */  lw         $v0, 0x58($sp)
/* 7AAE084 80082354 00020524 */  addiu      $a1, $zero, 0x200
/* 7AAE088 80082358 00024224 */  addiu      $v0, $v0, 0x200
/* 7AAE08C 8008235C D668000C */  jal        func_8001A358
/* 7AAE090 80082360 5800A2AF */   sw        $v0, 0x58($sp)
/* 7AAE094 80082364 AB004010 */  beqz       $v0, .Llevel_37_80082614
/* 7AAE098 80082368 5800A2AF */   sw        $v0, 0x58($sp)
/* 7AAE09C 8008236C 21204002 */  addu       $a0, $s2, $zero
/* 7AAE0A0 80082370 03000524 */  addiu      $a1, $zero, 0x3
/* 7AAE0A4 80082374 D0D3000C */  jal        func_80034F40
/* 7AAE0A8 80082378 140042AE */   sw        $v0, 0x14($s2)
/* 7AAE0AC 8008237C 0110023C */  lui        $v0, (0x10018000 >> 16)
/* 7AAE0B0 80082380 00804234 */  ori        $v0, $v0, (0x10018000 & 0xFFFF)
/* 7AAE0B4 80082384 2120A002 */  addu       $a0, $s5, $zero
/* 7AAE0B8 80082388 21282002 */  addu       $a1, $s1, $zero
/* 7AAE0BC 8008238C 5E3C010C */  jal        func_8004F178
/* 7AAE0C0 80082390 000062AE */   sw        $v0, 0x0($s3)
/* 7AAE0C4 80082394 2120A002 */  addu       $a0, $s5, $zero
/* 7AAE0C8 80082398 0780023C */  lui        $v0, %hi(D_80070328 + 0x234)
/* 7AAE0CC 8008239C 5C05428C */  lw         $v0, %lo(D_80070328 + 0x234)($v0)
/* 7AAE0D0 800823A0 00000000 */  nop
/* 7AAE0D4 800823A4 000E4224 */  addiu      $v0, $v0, 0xE00
/* 7AAE0D8 800823A8 0780013C */  lui        $at, %hi(D_80070328 + 0x234)
/* 7AAE0DC 800823AC 5C0522AC */  sw         $v0, %lo(D_80070328 + 0x234)($at)
/* 7AAE0E0 800823B0 D668000C */  jal        func_8001A358
/* 7AAE0E4 800823B4 00080524 */   addiu     $a1, $zero, 0x800
/* 7AAE0E8 800823B8 0780033C */  lui        $v1, %hi(D_80070328 + 0x44)
/* 7AAE0EC 800823BC 6C03638C */  lw         $v1, %lo(D_80070328 + 0x44)($v1)
/* 7AAE0F0 800823C0 0780013C */  lui        $at, %hi(D_80070328 + 0x23C)
/* 7AAE0F4 800823C4 640520AC */  sw         $zero, %lo(D_80070328 + 0x23C)($at)
/* 7AAE0F8 800823C8 0780013C */  lui        $at, %hi(D_80070328 + 0x228)
/* 7AAE0FC 800823CC 500520A0 */  sb         $zero, %lo(D_80070328 + 0x228)($at)
/* 7AAE100 800823D0 0780013C */  lui        $at, %hi(D_80070328 + 0x229)
/* 7AAE104 800823D4 510520A0 */  sb         $zero, %lo(D_80070328 + 0x229)($at)
/* 7AAE108 800823D8 21104300 */  addu       $v0, $v0, $v1
/* 7AAE10C 800823DC 0780013C */  lui        $at, %hi(D_80070328 + 0x234)
/* 7AAE110 800823E0 5C0522AC */  sw         $v0, %lo(D_80070328 + 0x234)($at)
/* 7AAE114 800823E4 46004292 */  lbu        $v0, 0x46($s2)
/* 7AAE118 800823E8 0780013C */  lui        $at, %hi(D_80070328 + 0x22A)
/* 7AAE11C 800823EC 520522A0 */  sb         $v0, %lo(D_80070328 + 0x22A)($at)
/* 7AAE120 800823F0 09000224 */  addiu      $v0, $zero, 0x9
/* 7AAE124 800823F4 89090208 */  j          .Llevel_37_80082624
/* 7AAE128 800823F8 480042A2 */   sb        $v0, 0x48($s2)
.L800823FC_:
/* 7AAE12C 800823FC 0110023C */  lui        $v0, (0x10018000 >> 16)
/* 7AAE130 80082400 00804234 */  ori        $v0, $v0, (0x10018000 & 0xFFFF)
/* 7AAE134 80082404 0780103C */  lui        $s0, %hi(D_80070328 + 0x20C)
/* 7AAE138 80082408 34051026 */  addiu      $s0, $s0, %lo(D_80070328 + 0x20C)
/* 7AAE13C 8008240C 20000426 */  addiu      $a0, $s0, 0x20
/* 7AAE140 80082410 000002AE */  sw         $v0, 0x0($s0)
/* 7AAE144 80082414 0780023C */  lui        $v0, %hi(D_80070328 + 0x234)
/* 7AAE148 80082418 5C05428C */  lw         $v0, %lo(D_80070328 + 0x234)($v0)
/* 7AAE14C 8008241C 0780033C */  lui        $v1, %hi(D_80070328 + 0x44)
/* 7AAE150 80082420 6C03638C */  lw         $v1, %lo(D_80070328 + 0x44)($v1)
/* 7AAE154 80082424 00014224 */  addiu      $v0, $v0, 0x100
/* 7AAE158 80082428 23104300 */  subu       $v0, $v0, $v1
/* 7AAE15C 8008242C 0780013C */  lui        $at, %hi(D_80070328 + 0x234)
/* 7AAE160 80082430 5C0522AC */  sw         $v0, %lo(D_80070328 + 0x234)($at)
/* 7AAE164 80082434 D668000C */  jal        func_8001A358
/* 7AAE168 80082438 00020524 */   addiu     $a1, $zero, 0x200
/* 7AAE16C 8008243C 0780033C */  lui        $v1, %hi(D_80070328 + 0x44)
/* 7AAE170 80082440 6C03638C */  lw         $v1, %lo(D_80070328 + 0x44)($v1)
/* 7AAE174 80082444 0780013C */  lui        $at, %hi(D_80070328 + 0x23C)
/* 7AAE178 80082448 640520AC */  sw         $zero, %lo(D_80070328 + 0x23C)($at)
/* 7AAE17C 8008244C 0780013C */  lui        $at, %hi(D_80070328 + 0x228)
/* 7AAE180 80082450 500520A0 */  sb         $zero, %lo(D_80070328 + 0x228)($at)
/* 7AAE184 80082454 0780013C */  lui        $at, %hi(D_80070328 + 0x229)
/* 7AAE188 80082458 510520A0 */  sb         $zero, %lo(D_80070328 + 0x229)($at)
/* 7AAE18C 8008245C 21104300 */  addu       $v0, $v0, $v1
/* 7AAE190 80082460 0780013C */  lui        $at, %hi(D_80070328 + 0x234)
/* 7AAE194 80082464 5C0522AC */  sw         $v0, %lo(D_80070328 + 0x234)($at)
/* 7AAE198 80082468 46004292 */  lbu        $v0, 0x46($s2)
/* 7AAE19C 8008246C 0780013C */  lui        $at, %hi(D_80070328 + 0x22A)
/* 7AAE1A0 80082470 520522A0 */  sb         $v0, %lo(D_80070328 + 0x22A)($at)
/* 7AAE1A4 80082474 0400828E */  lw         $v0, 0x4($s4)
/* 7AAE1A8 80082478 00000000 */  nop
/* 7AAE1AC 8008247C 0C00448C */  lw         $a0, 0xC($v0)
/* 7AAE1B0 80082480 B94E000C */  jal        func_80013AE4
/* 7AAE1B4 80082484 F4FD0526 */   addiu     $a1, $s0, -0x20C
/* 7AAE1B8 80082488 0780023C */  lui        $v0, %hi(D_8006C770)
/* 7AAE1BC 8008248C 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 7AAE1C0 80082490 00000000 */  nop
/* 7AAE1C4 80082494 66004010 */  beqz       $v0, .Llevel_37_80082630
/* 7AAE1C8 80082498 21204002 */   addu      $a0, $s2, $zero
/* 7AAE1CC 8008249C E0D3000C */  jal        func_80034F80
/* 7AAE1D0 800824A0 21280000 */   addu      $a1, $zero, $zero
/* 7AAE1D4 800824A4 DF4E000C */  jal        func_80013B7C
/* 7AAE1D8 800824A8 21200000 */   addu      $a0, $zero, $zero
.Llevel_37_800824AC:
/* 7AAE1DC 800824AC 06000224 */  addiu      $v0, $zero, 0x6
/* 7AAE1E0 800824B0 8C090208 */  j          .Llevel_37_80082630
/* 7AAE1E4 800824B4 480042A2 */   sb        $v0, 0x48($s2)
.L800824B8_:
/* 7AAE1E8 800824B8 0800828E */  lw         $v0, 0x8($s4)
/* 7AAE1EC 800824BC 00000000 */  nop
/* 7AAE1F0 800824C0 12004010 */  beqz       $v0, .Llevel_37_8008250C
/* 7AAE1F4 800824C4 08008426 */   addiu     $a0, $s4, 0x8
/* 7AAE1F8 800824C8 1400428E */  lw         $v0, 0x14($s2)
/* 7AAE1FC 800824CC 04000524 */  addiu      $a1, $zero, 0x4
/* 7AAE200 800824D0 40004224 */  addiu      $v0, $v0, 0x40
/* 7AAE204 800824D4 69D6000C */  jal        func_800359A4
/* 7AAE208 800824D8 140042AE */   sw        $v0, 0x14($s2)
/* 7AAE20C 800824DC 49004292 */  lbu        $v0, 0x49($s2)
/* 7AAE210 800824E0 00000000 */  nop
/* 7AAE214 800824E4 09004014 */  bnez       $v0, .Llevel_37_8008250C
/* 7AAE218 800824E8 0010023C */   lui       $v0, (0x10000002 >> 16)
/* 7AAE21C 800824EC 0780033C */  lui        $v1, %hi(D_80070328 + 0x50)
/* 7AAE220 800824F0 7803638C */  lw         $v1, %lo(D_80070328 + 0x50)($v1)
/* 7AAE224 800824F4 02004234 */  ori        $v0, $v0, (0x10000002 & 0xFFFF)
/* 7AAE228 800824F8 0780013C */  lui        $at, %hi(D_80070328 + 0x20C)
/* 7AAE22C 800824FC 340522AC */  sw         $v0, %lo(D_80070328 + 0x20C)($at)
/* 7AAE230 80082500 02006014 */  bnez       $v1, .Llevel_37_8008250C
/* 7AAE234 80082504 01000224 */   addiu     $v0, $zero, 0x1
/* 7AAE238 80082508 490042A2 */  sb         $v0, 0x49($s2)
.Llevel_37_8008250C:
/* 7AAE23C 8008250C 0780023C */  lui        $v0, %hi(D_8006C7B4)
/* 7AAE240 80082510 B4C74290 */  lbu        $v0, %lo(D_8006C7B4)($v0)
/* 7AAE244 80082514 00000000 */  nop
/* 7AAE248 80082518 01004230 */  andi       $v0, $v0, 0x1
/* 7AAE24C 8008251C 06004010 */  beqz       $v0, .Llevel_37_80082538
/* 7AAE250 80082520 21204002 */   addu      $a0, $s2, $zero
/* 7AAE254 80082524 D0D3000C */  jal        func_80034F40
/* 7AAE258 80082528 03000524 */   addiu     $a1, $zero, 0x3
/* 7AAE25C 8008252C 0B000224 */  addiu      $v0, $zero, 0xB
/* 7AAE260 80082530 8C090208 */  j          .Llevel_37_80082630
/* 7AAE264 80082534 480042A2 */   sb        $v0, 0x48($s2)
.Llevel_37_80082538:
/* 7AAE268 80082538 3C004392 */  lbu        $v1, 0x3C($s2)
/* 7AAE26C 8008253C 01000224 */  addiu      $v0, $zero, 0x1
/* 7AAE270 80082540 3C006214 */  bne        $v1, $v0, .Llevel_37_80082634
/* 7AAE274 80082544 00000000 */   nop
/* 7AAE278 80082548 0780023C */  lui        $v0, %hi(D_8006C770)
/* 7AAE27C 8008254C 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 7AAE280 80082550 00000000 */  nop
/* 7AAE284 80082554 37004010 */  beqz       $v0, .Llevel_37_80082634
/* 7AAE288 80082558 00000000 */   nop
/* 7AAE28C 8008255C E0D3000C */  jal        func_80034F80
/* 7AAE290 80082560 02000524 */   addiu     $a1, $zero, 0x2
/* 7AAE294 80082564 8D090208 */  j          .Llevel_37_80082634
/* 7AAE298 80082568 21204002 */   addu      $a0, $s2, $zero
.L8008256C_:
/* 7AAE29C 8008256C 3C004392 */  lbu        $v1, 0x3C($s2)
/* 7AAE2A0 80082570 03000224 */  addiu      $v0, $zero, 0x3
/* 7AAE2A4 80082574 09006214 */  bne        $v1, $v0, .Llevel_37_8008259C
/* 7AAE2A8 80082578 0010023C */   lui       $v0, (0x10000002 >> 16)
/* 7AAE2AC 8008257C 0780023C */  lui        $v0, %hi(D_8006C770)
/* 7AAE2B0 80082580 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 7AAE2B4 80082584 00000000 */  nop
/* 7AAE2B8 80082588 03004010 */  beqz       $v0, .Llevel_37_80082598
/* 7AAE2BC 8008258C 21204002 */   addu      $a0, $s2, $zero
/* 7AAE2C0 80082590 E0D3000C */  jal        func_80034F80
/* 7AAE2C4 80082594 21280000 */   addu      $a1, $zero, $zero
.Llevel_37_80082598:
/* 7AAE2C8 80082598 0010023C */  lui        $v0, (0x10000002 >> 16)
.Llevel_37_8008259C:
/* 7AAE2CC 8008259C 02004234 */  ori        $v0, $v0, (0x10000002 & 0xFFFF)
/* 7AAE2D0 800825A0 6000B027 */  addiu      $s0, $sp, 0x60
/* 7AAE2D4 800825A4 21200002 */  addu       $a0, $s0, $zero
/* 7AAE2D8 800825A8 0780013C */  lui        $at, %hi(D_80070328 + 0x20C)
/* 7AAE2DC 800825AC 340522AC */  sw         $v0, %lo(D_80070328 + 0x20C)($at)
/* 7AAE2E0 800825B0 1400428E */  lw         $v0, 0x14($s2)
/* 7AAE2E4 800825B4 0C004526 */  addiu      $a1, $s2, 0xC
/* 7AAE2E8 800825B8 C0FF4224 */  addiu      $v0, $v0, -0x40
/* 7AAE2EC 800825BC 5E3C010C */  jal        func_8004F178
/* 7AAE2F0 800825C0 140042AE */   sw        $v0, 0x14($s2)
/* 7AAE2F4 800825C4 1400428E */  lw         $v0, 0x14($s2)
/* 7AAE2F8 800825C8 21200002 */  addu       $a0, $s0, $zero
/* 7AAE2FC 800825CC 00044224 */  addiu      $v0, $v0, 0x400
/* 7AAE300 800825D0 140042AE */  sw         $v0, 0x14($s2)
/* 7AAE304 800825D4 6800A28F */  lw         $v0, 0x68($sp)
/* 7AAE308 800825D8 00020524 */  addiu      $a1, $zero, 0x200
/* 7AAE30C 800825DC 00024224 */  addiu      $v0, $v0, 0x200
/* 7AAE310 800825E0 D668000C */  jal        func_8001A358
/* 7AAE314 800825E4 6800A2AF */   sw        $v0, 0x68($sp)
/* 7AAE318 800825E8 21184000 */  addu       $v1, $v0, $zero
/* 7AAE31C 800825EC 09006010 */  beqz       $v1, .Llevel_37_80082614
/* 7AAE320 800825F0 6800A3AF */   sw        $v1, 0x68($sp)
/* 7AAE324 800825F4 3C004292 */  lbu        $v0, 0x3C($s2)
/* 7AAE328 800825F8 00000000 */  nop
/* 7AAE32C 800825FC 09004014 */  bnez       $v0, .Llevel_37_80082624
/* 7AAE330 80082600 140043AE */   sw        $v1, 0x14($s2)
/* 7AAE334 80082604 01000224 */  addiu      $v0, $zero, 0x1
/* 7AAE338 80082608 490040A2 */  sb         $zero, 0x49($s2)
/* 7AAE33C 8008260C 89090208 */  j          .Llevel_37_80082624
/* 7AAE340 80082610 480042A2 */   sb        $v0, 0x48($s2)
.Llevel_37_80082614:
/* 7AAE344 80082614 1400428E */  lw         $v0, 0x14($s2)
/* 7AAE348 80082618 00000000 */  nop
/* 7AAE34C 8008261C 00FC4224 */  addiu      $v0, $v0, -0x400
/* 7AAE350 80082620 140042AE */  sw         $v0, 0x14($s2)
.Llevel_37_80082624:
/* 7AAE354 80082624 21204002 */  addu       $a0, $s2, $zero
.Llevel_37_80082628:
/* 7AAE358 80082628 4957010C */  jal        func_80055D24
/* 7AAE35C 8008262C 02000524 */   addiu     $a1, $zero, 0x2
.Llevel_37_80082630:
/* 7AAE360 80082630 21204002 */  addu       $a0, $s2, $zero
.Llevel_37_80082634:
/* 7AAE364 80082634 4957010C */  jal        func_80055D24
/* 7AAE368 80082638 01000524 */   addiu     $a1, $zero, 0x1
.Llevel_37_8008263C:
/* 7AAE36C 8008263C 9000BF8F */  lw         $ra, 0x90($sp)
/* 7AAE370 80082640 8C00B78F */  lw         $s7, 0x8C($sp)
/* 7AAE374 80082644 8800B68F */  lw         $s6, 0x88($sp)
/* 7AAE378 80082648 8400B58F */  lw         $s5, 0x84($sp)
/* 7AAE37C 8008264C 8000B48F */  lw         $s4, 0x80($sp)
/* 7AAE380 80082650 7C00B38F */  lw         $s3, 0x7C($sp)
/* 7AAE384 80082654 7800B28F */  lw         $s2, 0x78($sp)
/* 7AAE388 80082658 7400B18F */  lw         $s1, 0x74($sp)
/* 7AAE38C 8008265C 7000B08F */  lw         $s0, 0x70($sp)
/* 7AAE390 80082660 9800BD27 */  addiu      $sp, $sp, 0x98
/* 7AAE394 80082664 0800E003 */  jr         $ra
/* 7AAE398 80082668 00000000 */   nop
.size func_level_37_800818EC, . - func_level_37_800818EC
