.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_32_80074558
/* 6DDBA88 80074558 08950780 */ .word .L80079508_
/* 6DDBA8C 8007455C 3C960780 */ .word .L8007963C_
/* 6DDBA90 80074560 CC960780 */ .word .L800796CC_
/* 6DDBA94 80074564 6C970780 */ .word .L8007976C_
/* 6DDBA98 80074568 54980780 */ .word .L80079854_
/* 6DDBA9C 8007456C 6C970780 */ .word .L8007976C_
/* 6DDBAA0 80074570 D89A0780 */ .word .L80079AD8_
/* 6DDBAA4 80074574 EC9A0780 */ .word .L80079AEC_
.size jtbl_level_32_80074558, . - jtbl_level_32_80074558


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_32_8007945C
/* 6DE098C 8007945C 0780023C */  lui        $v0, %hi(D_8006C704)
/* 6DE0990 80079460 04C7428C */  lw         $v0, %lo(D_8006C704)($v0)
/* 6DE0994 80079464 90FFBD27 */  addiu      $sp, $sp, -0x70
/* 6DE0998 80079468 6000B2AF */  sw         $s2, 0x60($sp)
/* 6DE099C 8007946C 21908000 */  addu       $s2, $a0, $zero
/* 6DE09A0 80079470 6C00BFAF */  sw         $ra, 0x6C($sp)
/* 6DE09A4 80079474 6800B4AF */  sw         $s4, 0x68($sp)
/* 6DE09A8 80079478 6400B3AF */  sw         $s3, 0x64($sp)
/* 6DE09AC 8007947C 5C00B1AF */  sw         $s1, 0x5C($sp)
/* 6DE09B0 80079480 2B104202 */  sltu       $v0, $s2, $v0
/* 6DE09B4 80079484 04004014 */  bnez       $v0, .Llevel_32_80079498
/* 6DE09B8 80079488 5800B0AF */   sw        $s0, 0x58($sp)
/* 6DE09BC 8007948C 0000538E */  lw         $s3, 0x0($s2)
/* 6DE09C0 80079490 29E50108 */  j          .Llevel_32_800794A4
/* 6DE09C4 80079494 21880000 */   addu      $s1, $zero, $zero
.Llevel_32_80079498:
/* 6DE09C8 80079498 0000518E */  lw         $s1, 0x0($s2)
/* 6DE09CC 8007949C 00000000 */  nop
/* 6DE09D0 800794A0 2C003326 */  addiu      $s3, $s1, 0x2C
.Llevel_32_800794A4:
/* 6DE09D4 800794A4 0C005026 */  addiu      $s0, $s2, 0xC
/* 6DE09D8 800794A8 0780053C */  lui        $a1, %hi(D_80070328)
/* 6DE09DC 800794AC 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 6DE09E0 800794B0 CD3C010C */  jal        func_8004F334
/* 6DE09E4 800794B4 21200002 */   addu      $a0, $s0, $zero
/* 6DE09E8 800794B8 48004392 */  lbu        $v1, 0x48($s2)
/* 6DE09EC 800794BC 00000000 */  nop
/* 6DE09F0 800794C0 06006010 */  beqz       $v1, .Llevel_32_800794DC
/* 6DE09F4 800794C4 21A04000 */   addu      $s4, $v0, $zero
/* 6DE09F8 800794C8 01000224 */  addiu      $v0, $zero, 0x1
/* 6DE09FC 800794CC 95016210 */  beq        $v1, $v0, .Llevel_32_80079B24
/* 6DE0A00 800794D0 00000000 */   nop
/* 6DE0A04 800794D4 A7E70108 */  j          .Llevel_32_80079E9C
/* 6DE0A08 800794D8 00000000 */   nop
.Llevel_32_800794DC:
/* 6DE0A0C 800794DC 49004392 */  lbu        $v1, 0x49($s2)
/* 6DE0A10 800794E0 00000000 */  nop
/* 6DE0A14 800794E4 0800622C */  sltiu      $v0, $v1, 0x8
/* 6DE0A18 800794E8 87014010 */  beqz       $v0, .Llevel_32_80079B08
/* 6DE0A1C 800794EC 80100300 */   sll       $v0, $v1, 2
/* 6DE0A20 800794F0 0780013C */  lui        $at, %hi(jtbl_level_32_80074558)
/* 6DE0A24 800794F4 21082200 */  addu       $at, $at, $v0
/* 6DE0A28 800794F8 5845228C */  lw         $v0, %lo(jtbl_level_32_80074558)($at)
/* 6DE0A2C 800794FC 00000000 */  nop
/* 6DE0A30 80079500 08004000 */  jr         $v0
/* 6DE0A34 80079504 00000000 */   nop
.L80079508_:
/* 6DE0A38 80079508 02006392 */  lbu        $v1, 0x2($s3)
/* 6DE0A3C 8007950C 02000224 */  addiu      $v0, $zero, 0x2
/* 6DE0A40 80079510 45006210 */  beq        $v1, $v0, .Llevel_32_80079628
/* 6DE0A44 80079514 01000224 */   addiu     $v0, $zero, 0x1
/* 6DE0A48 80079518 0780043C */  lui        $a0, %hi(D_8006C550)
/* 6DE0A4C 8007951C 50C5848C */  lw         $a0, %lo(D_8006C550)($a0)
/* 6DE0A50 80079520 00000000 */  nop
/* 6DE0A54 80079524 23204402 */  subu       $a0, $s2, $a0
/* 6DE0A58 80079528 40110400 */  sll        $v0, $a0, 5
/* 6DE0A5C 8007952C 23104400 */  subu       $v0, $v0, $a0
/* 6DE0A60 80079530 40110200 */  sll        $v0, $v0, 5
/* 6DE0A64 80079534 21104400 */  addu       $v0, $v0, $a0
/* 6DE0A68 80079538 C0180200 */  sll        $v1, $v0, 3
/* 6DE0A6C 8007953C 21104300 */  addu       $v0, $v0, $v1
/* 6DE0A70 80079540 C01B0200 */  sll        $v1, $v0, 15
/* 6DE0A74 80079544 23186200 */  subu       $v1, $v1, $v0
/* 6DE0A78 80079548 80180300 */  sll        $v1, $v1, 2
/* 6DE0A7C 8007954C 21186400 */  addu       $v1, $v1, $a0
/* 6DE0A80 80079550 23180300 */  negu       $v1, $v1
/* 6DE0A84 80079554 C3180300 */  sra        $v1, $v1, 3
/* 6DE0A88 80079558 0780023C */  lui        $v0, %hi(D_8006C79C)
/* 6DE0A8C 8007955C 9CC7428C */  lw         $v0, %lo(D_8006C79C)($v0)
/* 6DE0A90 80079560 04006492 */  lbu        $a0, 0x4($s3)
/* 6DE0A94 80079564 00000000 */  nop
/* 6DE0A98 80079568 04008014 */  bnez       $a0, .Llevel_32_8007957C
/* 6DE0A9C 8007956C 21286200 */   addu      $a1, $v1, $v0
/* 6DE0AA0 80079570 46004292 */  lbu        $v0, 0x46($s2)
/* 6DE0AA4 80079574 00000000 */  nop
/* 6DE0AA8 80079578 040062A2 */  sb         $v0, 0x4($s3)
.Llevel_32_8007957C:
/* 6DE0AAC 8007957C 0780033C */  lui        $v1, %hi(D_8006C58C)
/* 6DE0AB0 80079580 8CC5638C */  lw         $v1, %lo(D_8006C58C)($v1)
/* 6DE0AB4 80079584 0780023C */  lui        $v0, %hi(D_80071AB0)
/* 6DE0AB8 80079588 B01A4224 */  addiu      $v0, $v0, %lo(D_80071AB0)
/* 6DE0ABC 8007958C 40190300 */  sll        $v1, $v1, 5
/* 6DE0AC0 80079590 21186200 */  addu       $v1, $v1, $v0
/* 6DE0AC4 80079594 43110500 */  sra        $v0, $a1, 5
/* 6DE0AC8 80079598 80100200 */  sll        $v0, $v0, 2
/* 6DE0ACC 8007959C 21104300 */  addu       $v0, $v0, $v1
/* 6DE0AD0 800795A0 0000428C */  lw         $v0, 0x0($v0)
/* 6DE0AD4 800795A4 1F00A330 */  andi       $v1, $a1, 0x1F
/* 6DE0AD8 800795A8 07106200 */  srav       $v0, $v0, $v1
/* 6DE0ADC 800795AC 01004230 */  andi       $v0, $v0, 0x1
/* 6DE0AE0 800795B0 02004010 */  beqz       $v0, .Llevel_32_800795BC
/* 6DE0AE4 800795B4 00000000 */   nop
/* 6DE0AE8 800795B8 020060A2 */  sb         $zero, 0x2($s3)
.Llevel_32_800795BC:
/* 6DE0AEC 800795BC 02006392 */  lbu        $v1, 0x2($s3)
/* 6DE0AF0 800795C0 01000224 */  addiu      $v0, $zero, 0x1
/* 6DE0AF4 800795C4 09006214 */  bne        $v1, $v0, .Llevel_32_800795EC
/* 6DE0AF8 800795C8 01000224 */   addiu     $v0, $zero, 0x1
/* 6DE0AFC 800795CC 050022A2 */  sb         $v0, 0x5($s1)
/* 6DE0B00 800795D0 80FD0224 */  addiu      $v0, $zero, -0x280
/* 6DE0B04 800795D4 060062A6 */  sh         $v0, 0x6($s3)
/* 6DE0B08 800795D8 1400428E */  lw         $v0, 0x14($s2)
/* 6DE0B0C 800795DC 00000000 */  nop
/* 6DE0B10 800795E0 80FD4224 */  addiu      $v0, $v0, -0x280
/* 6DE0B14 800795E4 7CE50108 */  j          .Llevel_32_800795F0
/* 6DE0B18 800795E8 140042AE */   sw        $v0, 0x14($s2)
.Llevel_32_800795EC:
/* 6DE0B1C 800795EC 050020A2 */  sb         $zero, 0x5($s1)
.Llevel_32_800795F0:
/* 6DE0B20 800795F0 46004292 */  lbu        $v0, 0x46($s2)
/* 6DE0B24 800795F4 02006392 */  lbu        $v1, 0x2($s3)
/* 6DE0B28 800795F8 030062A2 */  sb         $v0, 0x3($s3)
/* 6DE0B2C 800795FC 01000224 */  addiu      $v0, $zero, 0x1
/* 6DE0B30 80079600 06006214 */  bne        $v1, $v0, .Llevel_32_8007961C
/* 6DE0B34 80079604 0010822A */   slti      $v0, $s4, 0x1000
/* 6DE0B38 80079608 05002292 */  lbu        $v0, 0x5($s1)
/* 6DE0B3C 8007960C 00000000 */  nop
/* 6DE0B40 80079610 05004014 */  bnez       $v0, .Llevel_32_80079628
/* 6DE0B44 80079614 01000224 */   addiu     $v0, $zero, 0x1
/* 6DE0B48 80079618 0010822A */  slti       $v0, $s4, 0x1000
.Llevel_32_8007961C:
/* 6DE0B4C 8007961C 02004014 */  bnez       $v0, .Llevel_32_80079628
/* 6DE0B50 80079620 05000224 */   addiu     $v0, $zero, 0x5
/* 6DE0B54 80079624 01000224 */  addiu      $v0, $zero, 0x1
.Llevel_32_80079628:
/* 6DE0B58 80079628 490042A2 */  sb         $v0, 0x49($s2)
/* 6DE0B5C 8007962C 410040A2 */  sb         $zero, 0x41($s2)
/* 6DE0B60 80079630 4C0040A2 */  sb         $zero, 0x4C($s2)
/* 6DE0B64 80079634 C2E60108 */  j          .Llevel_32_80079B08
/* 6DE0B68 80079638 4D0040A2 */   sb        $zero, 0x4D($s2)
.L8007963C_:
/* 6DE0B6C 8007963C 0024822A */  slti       $v0, $s4, 0x2400
/* 6DE0B70 80079640 05004014 */  bnez       $v0, .Llevel_32_80079658
/* 6DE0B74 80079644 01000324 */   addiu     $v1, $zero, 0x1
/* 6DE0B78 80079648 02006392 */  lbu        $v1, 0x2($s3)
/* 6DE0B7C 8007964C 02000224 */  addiu      $v0, $zero, 0x2
/* 6DE0B80 80079650 2D016214 */  bne        $v1, $v0, .Llevel_32_80079B08
/* 6DE0B84 80079654 01000324 */   addiu     $v1, $zero, 0x1
.Llevel_32_80079658:
/* 6DE0B88 80079658 18000224 */  addiu      $v0, $zero, 0x18
/* 6DE0B8C 8007965C 4C0042A2 */  sb         $v0, 0x4C($s2)
/* 6DE0B90 80079660 7F000224 */  addiu      $v0, $zero, 0x7F
/* 6DE0B94 80079664 410043A2 */  sb         $v1, 0x41($s2)
/* 6DE0B98 80079668 4D0043A2 */  sb         $v1, 0x4D($s2)
/* 6DE0B9C 8007966C 4F0042A2 */  sb         $v0, 0x4F($s2)
/* 6DE0BA0 80079670 02006392 */  lbu        $v1, 0x2($s3)
/* 6DE0BA4 80079674 01000224 */  addiu      $v0, $zero, 0x1
/* 6DE0BA8 80079678 04006214 */  bne        $v1, $v0, .Llevel_32_8007968C
/* 6DE0BAC 8007967C 21300000 */   addu      $a2, $zero, $zero
/* 6DE0BB0 80079680 03006292 */  lbu        $v0, 0x3($s3)
/* 6DE0BB4 80079684 ADE50108 */  j          .Llevel_32_800796B4
/* 6DE0BB8 80079688 460042A2 */   sb        $v0, 0x46($s2)
.Llevel_32_8007968C:
/* 6DE0BBC 8007968C 0780033C */  lui        $v1, %hi(D_80070328)
/* 6DE0BC0 80079690 2803638C */  lw         $v1, %lo(D_80070328)($v1)
/* 6DE0BC4 80079694 0C00448E */  lw         $a0, 0xC($s2)
/* 6DE0BC8 80079698 0780023C */  lui        $v0, %hi(D_80070328 + 4)
/* 6DE0BCC 8007969C 2C03428C */  lw         $v0, %lo(D_80070328 + 4)($v0)
/* 6DE0BD0 800796A0 1000458E */  lw         $a1, 0x10($s2)
/* 6DE0BD4 800796A4 23206400 */  subu       $a0, $v1, $a0
/* 6DE0BD8 800796A8 203A010C */  jal        func_8004E880
/* 6DE0BDC 800796AC 23284500 */   subu      $a1, $v0, $a1
/* 6DE0BE0 800796B0 460042A2 */  sb         $v0, 0x46($s2)
.Llevel_32_800796B4:
/* 6DE0BE4 800796B4 46004292 */  lbu        $v0, 0x46($s2)
/* 6DE0BE8 800796B8 02000324 */  addiu      $v1, $zero, 0x2
/* 6DE0BEC 800796BC 490043A2 */  sb         $v1, 0x49($s2)
/* 6DE0BF0 800796C0 67004224 */  addiu      $v0, $v0, 0x67
/* 6DE0BF4 800796C4 C2E60108 */  j          .Llevel_32_80079B08
/* 6DE0BF8 800796C8 460042A2 */   sb        $v0, 0x46($s2)
.L800796CC_:
/* 6DE0BFC 800796CC 46004292 */  lbu        $v0, 0x46($s2)
/* 6DE0C00 800796D0 4F004392 */  lbu        $v1, 0x4F($s2)
/* 6DE0C04 800796D4 08004224 */  addiu      $v0, $v0, 0x8
/* 6DE0C08 800796D8 FBFF6324 */  addiu      $v1, $v1, -0x5
/* 6DE0C0C 800796DC 460042A2 */  sb         $v0, 0x46($s2)
/* 6DE0C10 800796E0 4F0043A2 */  sb         $v1, 0x4F($s2)
/* 6DE0C14 800796E4 0780023C */  lui        $v0, %hi(D_80070328 + 0xB4)
/* 6DE0C18 800796E8 DC03428C */  lw         $v0, %lo(D_80070328 + 0xB4)($v0)
/* 6DE0C1C 800796EC 00000000 */  nop
/* 6DE0C20 800796F0 00144228 */  slti       $v0, $v0, 0x1400
/* 6DE0C24 800796F4 05004010 */  beqz       $v0, .Llevel_32_8007970C
/* 6DE0C28 800796F8 02000224 */   addiu     $v0, $zero, 0x2
/* 6DE0C2C 800796FC 02006392 */  lbu        $v1, 0x2($s3)
/* 6DE0C30 80079700 00000000 */  nop
/* 6DE0C34 80079704 08006214 */  bne        $v1, $v0, .Llevel_32_80079728
/* 6DE0C38 80079708 21204002 */   addu      $a0, $s2, $zero
.Llevel_32_8007970C:
/* 6DE0C3C 8007970C 46004292 */  lbu        $v0, 0x46($s2)
/* 6DE0C40 80079710 4F004392 */  lbu        $v1, 0x4F($s2)
/* 6DE0C44 80079714 08004224 */  addiu      $v0, $v0, 0x8
/* 6DE0C48 80079718 FBFF6324 */  addiu      $v1, $v1, -0x5
/* 6DE0C4C 8007971C 460042A2 */  sb         $v0, 0x46($s2)
/* 6DE0C50 80079720 4F0043A2 */  sb         $v1, 0x4F($s2)
/* 6DE0C54 80079724 21204002 */  addu       $a0, $s2, $zero
.Llevel_32_80079728:
/* 6DE0C58 80079728 4957010C */  jal        func_80055D24
/* 6DE0C5C 8007972C 04000524 */   addiu     $a1, $zero, 0x4
/* 6DE0C60 80079730 01000424 */  addiu      $a0, $zero, 0x1
/* 6DE0C64 80079734 0C000524 */  addiu      $a1, $zero, 0xC
/* 6DE0C68 80079738 21304002 */  addu       $a2, $s2, $zero
/* 6DE0C6C 8007973C 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 6DE0C70 80079740 E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 6DE0C74 80079744 00000000 */  nop
/* 6DE0C78 80079748 09F84000 */  jalr       $v0
/* 6DE0C7C 8007974C 05000724 */   addiu     $a3, $zero, 0x5
/* 6DE0C80 80079750 4F004292 */  lbu        $v0, 0x4F($s2)
/* 6DE0C84 80079754 00000000 */  nop
/* 6DE0C88 80079758 2100422C */  sltiu      $v0, $v0, 0x21
/* 6DE0C8C 8007975C EA004010 */  beqz       $v0, .Llevel_32_80079B08
/* 6DE0C90 80079760 20000224 */   addiu     $v0, $zero, 0x20
/* 6DE0C94 80079764 C0E60108 */  j          .Llevel_32_80079B00
/* 6DE0C98 80079768 4F0042A2 */   sb        $v0, 0x4F($s2)
.L8007976C_:
/* 6DE0C9C 8007976C 4F004292 */  lbu        $v0, 0x4F($s2)
/* 6DE0CA0 80079770 00000000 */  nop
/* 6DE0CA4 80079774 03004014 */  bnez       $v0, .Llevel_32_80079784
/* 6DE0CA8 80079778 21204002 */   addu      $a0, $s2, $zero
/* 6DE0CAC 8007977C 20000224 */  addiu      $v0, $zero, 0x20
/* 6DE0CB0 80079780 4F0042A2 */  sb         $v0, 0x4F($s2)
.Llevel_32_80079784:
/* 6DE0CB4 80079784 04000524 */  addiu      $a1, $zero, 0x4
/* 6DE0CB8 80079788 46004292 */  lbu        $v0, 0x46($s2)
/* 6DE0CBC 8007978C 4F004392 */  lbu        $v1, 0x4F($s2)
/* 6DE0CC0 80079790 F8FF4224 */  addiu      $v0, $v0, -0x8
/* 6DE0CC4 80079794 05006324 */  addiu      $v1, $v1, 0x5
/* 6DE0CC8 80079798 460042A2 */  sb         $v0, 0x46($s2)
/* 6DE0CCC 8007979C 4957010C */  jal        func_80055D24
/* 6DE0CD0 800797A0 4F0043A2 */   sb        $v1, 0x4F($s2)
/* 6DE0CD4 800797A4 4F004292 */  lbu        $v0, 0x4F($s2)
/* 6DE0CD8 800797A8 00000000 */  nop
/* 6DE0CDC 800797AC 7F00422C */  sltiu      $v0, $v0, 0x7F
/* 6DE0CE0 800797B0 1F004014 */  bnez       $v0, .Llevel_32_80079830
/* 6DE0CE4 800797B4 01000424 */   addiu     $a0, $zero, 0x1
/* 6DE0CE8 800797B8 06000424 */  addiu      $a0, $zero, 0x6
/* 6DE0CEC 800797BC 0C000524 */  addiu      $a1, $zero, 0xC
/* 6DE0CF0 800797C0 21304002 */  addu       $a2, $s2, $zero
/* 6DE0CF4 800797C4 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 6DE0CF8 800797C8 E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 6DE0CFC 800797CC 00000000 */  nop
/* 6DE0D00 800797D0 09F84000 */  jalr       $v0
/* 6DE0D04 800797D4 05000724 */   addiu     $a3, $zero, 0x5
/* 6DE0D08 800797D8 02006392 */  lbu        $v1, 0x2($s3)
/* 6DE0D0C 800797DC 02000224 */  addiu      $v0, $zero, 0x2
/* 6DE0D10 800797E0 0A006214 */  bne        $v1, $v0, .Llevel_32_8007980C
/* 6DE0D14 800797E4 05000224 */   addiu     $v0, $zero, 0x5
/* 6DE0D18 800797E8 0800628E */  lw         $v0, 0x8($s3)
/* 6DE0D1C 800797EC 00000000 */  nop
/* 6DE0D20 800797F0 02004010 */  beqz       $v0, .Llevel_32_800797FC
/* 6DE0D24 800797F4 00000000 */   nop
/* 6DE0D28 800797F8 100040A0 */  sb         $zero, 0x10($v0)
.Llevel_32_800797FC:
/* 6DE0D2C 800797FC C656010C */  jal        func_80055B18
/* 6DE0D30 80079800 21204002 */   addu      $a0, $s2, $zero
/* 6DE0D34 80079804 EBE70108 */  j          .Llevel_32_80079FAC
/* 6DE0D38 80079808 00000000 */   nop
.Llevel_32_8007980C:
/* 6DE0D3C 8007980C 49004392 */  lbu        $v1, 0x49($s2)
/* 6DE0D40 80079810 410040A2 */  sb         $zero, 0x41($s2)
/* 6DE0D44 80079814 4C0040A2 */  sb         $zero, 0x4C($s2)
/* 6DE0D48 80079818 03006214 */  bne        $v1, $v0, .Llevel_32_80079828
/* 6DE0D4C 8007981C 4D0040A2 */   sb        $zero, 0x4D($s2)
/* 6DE0D50 80079820 C1E60108 */  j          .Llevel_32_80079B04
/* 6DE0D54 80079824 06000224 */   addiu     $v0, $zero, 0x6
.Llevel_32_80079828:
/* 6DE0D58 80079828 C1E60108 */  j          .Llevel_32_80079B04
/* 6DE0D5C 8007982C 01000224 */   addiu     $v0, $zero, 0x1
.Llevel_32_80079830:
/* 6DE0D60 80079830 0C000524 */  addiu      $a1, $zero, 0xC
/* 6DE0D64 80079834 21304002 */  addu       $a2, $s2, $zero
/* 6DE0D68 80079838 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 6DE0D6C 8007983C E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 6DE0D70 80079840 00000000 */  nop
/* 6DE0D74 80079844 09F84000 */  jalr       $v0
/* 6DE0D78 80079848 03000724 */   addiu     $a3, $zero, 0x3
/* 6DE0D7C 8007984C C2E60108 */  j          .Llevel_32_80079B08
/* 6DE0D80 80079850 00000000 */   nop
.L80079854_:
/* 6DE0D84 80079854 02007092 */  lbu        $s0, 0x2($s3)
/* 6DE0D88 80079858 02000224 */  addiu      $v0, $zero, 0x2
/* 6DE0D8C 8007985C 7D000212 */  beq        $s0, $v0, .Llevel_32_80079A54
/* 6DE0D90 80079860 01000224 */   addiu     $v0, $zero, 0x1
/* 6DE0D94 80079864 2D000216 */  bne        $s0, $v0, .Llevel_32_8007991C
/* 6DE0D98 80079868 21204002 */   addu      $a0, $s2, $zero
/* 6DE0D9C 8007986C EFDE000C */  jal        func_80037BBC
/* 6DE0DA0 80079870 0C000524 */   addiu     $a1, $zero, 0xC
/* 6DE0DA4 80079874 7C004010 */  beqz       $v0, .Llevel_32_80079A68
/* 6DE0DA8 80079878 21204002 */   addu      $a0, $s2, $zero
/* 6DE0DAC 8007987C 21280000 */  addu       $a1, $zero, $zero
/* 6DE0DB0 80079880 B944010C */  jal        func_800512E4
/* 6DE0DB4 80079884 21300000 */   addu      $a2, $zero, $zero
/* 6DE0DB8 80079888 0780043C */  lui        $a0, %hi(D_8006C550)
/* 6DE0DBC 8007988C 50C5848C */  lw         $a0, %lo(D_8006C550)($a0)
/* 6DE0DC0 80079890 00000000 */  nop
/* 6DE0DC4 80079894 23204402 */  subu       $a0, $s2, $a0
/* 6DE0DC8 80079898 40110400 */  sll        $v0, $a0, 5
/* 6DE0DCC 8007989C 23104400 */  subu       $v0, $v0, $a0
/* 6DE0DD0 800798A0 40110200 */  sll        $v0, $v0, 5
/* 6DE0DD4 800798A4 21104400 */  addu       $v0, $v0, $a0
/* 6DE0DD8 800798A8 C0180200 */  sll        $v1, $v0, 3
/* 6DE0DDC 800798AC 21104300 */  addu       $v0, $v0, $v1
/* 6DE0DE0 800798B0 C01B0200 */  sll        $v1, $v0, 15
/* 6DE0DE4 800798B4 23186200 */  subu       $v1, $v1, $v0
/* 6DE0DE8 800798B8 80180300 */  sll        $v1, $v1, 2
/* 6DE0DEC 800798BC 21186400 */  addu       $v1, $v1, $a0
/* 6DE0DF0 800798C0 23180300 */  negu       $v1, $v1
/* 6DE0DF4 800798C4 0780023C */  lui        $v0, %hi(D_8006C79C)
/* 6DE0DF8 800798C8 9CC7428C */  lw         $v0, %lo(D_8006C79C)($v0)
/* 6DE0DFC 800798CC C3180300 */  sra        $v1, $v1, 3
/* 6DE0E00 800798D0 21186200 */  addu       $v1, $v1, $v0
/* 6DE0E04 800798D4 0780023C */  lui        $v0, %hi(D_8006C58C)
/* 6DE0E08 800798D8 8CC5428C */  lw         $v0, %lo(D_8006C58C)($v0)
/* 6DE0E0C 800798DC 0780043C */  lui        $a0, %hi(D_80071AB0)
/* 6DE0E10 800798E0 B01A8424 */  addiu      $a0, $a0, %lo(D_80071AB0)
/* 6DE0E14 800798E4 40110200 */  sll        $v0, $v0, 5
/* 6DE0E18 800798E8 21104400 */  addu       $v0, $v0, $a0
/* 6DE0E1C 800798EC 43210300 */  sra        $a0, $v1, 5
/* 6DE0E20 800798F0 80200400 */  sll        $a0, $a0, 2
/* 6DE0E24 800798F4 21208200 */  addu       $a0, $a0, $v0
/* 6DE0E28 800798F8 1F006330 */  andi       $v1, $v1, 0x1F
/* 6DE0E2C 800798FC 0000828C */  lw         $v0, 0x0($a0)
/* 6DE0E30 80079900 04187000 */  sllv       $v1, $s0, $v1
/* 6DE0E34 80079904 25104300 */  or         $v0, $v0, $v1
/* 6DE0E38 80079908 000082AC */  sw         $v0, 0x0($a0)
/* 6DE0E3C 8007990C 07000224 */  addiu      $v0, $zero, 0x7
/* 6DE0E40 80079910 020060A2 */  sb         $zero, 0x2($s3)
/* 6DE0E44 80079914 9AE60108 */  j          .Llevel_32_80079A68
/* 6DE0E48 80079918 490042A2 */   sb        $v0, 0x49($s2)
.Llevel_32_8007991C:
/* 6DE0E4C 8007991C 04000524 */  addiu      $a1, $zero, 0x4
/* 6DE0E50 80079920 21300000 */  addu       $a2, $zero, $zero
/* 6DE0E54 80079924 CFD5000C */  jal        func_8003573C
/* 6DE0E58 80079928 21380000 */   addu      $a3, $zero, $zero
/* 6DE0E5C 8007992C 21204002 */  addu       $a0, $s2, $zero
/* 6DE0E60 80079930 4957010C */  jal        func_80055D24
/* 6DE0E64 80079934 04000524 */   addiu     $a1, $zero, 0x4
/* 6DE0E68 80079938 0128822A */  slti       $v0, $s4, 0x2801
/* 6DE0E6C 8007993C 04004014 */  bnez       $v0, .Llevel_32_80079950
/* 6DE0E70 80079940 0010822A */   slti      $v0, $s4, 0x1000
/* 6DE0E74 80079944 03000224 */  addiu      $v0, $zero, 0x3
/* 6DE0E78 80079948 9AE60108 */  j          .Llevel_32_80079A68
/* 6DE0E7C 8007994C 490042A2 */   sb        $v0, 0x49($s2)
.Llevel_32_80079950:
/* 6DE0E80 80079950 45004010 */  beqz       $v0, .Llevel_32_80079A68
/* 6DE0E84 80079954 00000000 */   nop
/* 6DE0E88 80079958 38004386 */  lh         $v1, 0x38($s2)
/* 6DE0E8C 8007995C 1400428E */  lw         $v0, 0x14($s2)
/* 6DE0E90 80079960 0780043C */  lui        $a0, %hi(D_80070328 + 8)
/* 6DE0E94 80079964 3003848C */  lw         $a0, %lo(D_80070328 + 8)($a0)
/* 6DE0E98 80079968 23184300 */  subu       $v1, $v0, $v1
/* 6DE0E9C 8007996C 23106400 */  subu       $v0, $v1, $a0
/* 6DE0EA0 80079970 05004004 */  bltz       $v0, .Llevel_32_80079988
/* 6DE0EA4 80079974 00084228 */   slti      $v0, $v0, 0x800
/* 6DE0EA8 80079978 3B004010 */  beqz       $v0, .Llevel_32_80079A68
/* 6DE0EAC 8007997C 00000000 */   nop
/* 6DE0EB0 80079980 66E60108 */  j          .Llevel_32_80079998
/* 6DE0EB4 80079984 00000000 */   nop
.Llevel_32_80079988:
/* 6DE0EB8 80079988 23108300 */  subu       $v0, $a0, $v1
/* 6DE0EBC 8007998C 00084228 */  slti       $v0, $v0, 0x800
/* 6DE0EC0 80079990 35004010 */  beqz       $v0, .Llevel_32_80079A68
/* 6DE0EC4 80079994 00000000 */   nop
.Llevel_32_80079998:
/* 6DE0EC8 80079998 0780103C */  lui        $s0, %hi(D_80070328 + 8)
/* 6DE0ECC 8007999C 30031026 */  addiu      $s0, $s0, %lo(D_80070328 + 8)
/* 6DE0ED0 800799A0 38004286 */  lh         $v0, 0x38($s2)
/* 6DE0ED4 800799A4 1400438E */  lw         $v1, 0x14($s2)
/* 6DE0ED8 800799A8 0000048E */  lw         $a0, 0x0($s0)
/* 6DE0EDC 800799AC 23186200 */  subu       $v1, $v1, $v0
/* 6DE0EE0 800799B0 23186400 */  subu       $v1, $v1, $a0
/* 6DE0EE4 800799B4 0DFE6328 */  slti       $v1, $v1, -0x1F3
/* 6DE0EE8 800799B8 2B006014 */  bnez       $v1, .Llevel_32_80079A68
/* 6DE0EEC 800799BC 00000000 */   nop
/* 6DE0EF0 800799C0 0780033C */  lui        $v1, %hi(D_80070328 + 0x50)
/* 6DE0EF4 800799C4 7803638C */  lw         $v1, %lo(D_80070328 + 0x50)($v1)
/* 6DE0EF8 800799C8 00000000 */  nop
/* 6DE0EFC 800799CC 05006228 */  slti       $v0, $v1, 0x5
/* 6DE0F00 800799D0 04004014 */  bnez       $v0, .Llevel_32_800799E4
/* 6DE0F04 800799D4 F5FF6224 */   addiu     $v0, $v1, -0xB
/* 6DE0F08 800799D8 0200422C */  sltiu      $v0, $v0, 0x2
/* 6DE0F0C 800799DC 22004010 */  beqz       $v0, .Llevel_32_80079A68
/* 6DE0F10 800799E0 00000000 */   nop
.Llevel_32_800799E4:
/* 6DE0F14 800799E4 1800A427 */  addiu      $a0, $sp, 0x18
/* 6DE0F18 800799E8 5E3C010C */  jal        func_8004F178
/* 6DE0F1C 800799EC 90000526 */   addiu     $a1, $s0, 0x90
/* 6DE0F20 800799F0 1800A427 */  addiu      $a0, $sp, 0x18
/* 6DE0F24 800799F4 06000524 */  addiu      $a1, $zero, 0x6
/* 6DE0F28 800799F8 1800A28F */  lw         $v0, 0x18($sp)
/* 6DE0F2C 800799FC 2000A38F */  lw         $v1, 0x20($sp)
/* 6DE0F30 80079A00 40110200 */  sll        $v0, $v0, 5
/* 6DE0F34 80079A04 1800A2AF */  sw         $v0, 0x18($sp)
/* 6DE0F38 80079A08 1C00A28F */  lw         $v0, 0x1C($sp)
/* 6DE0F3C 80079A0C 40190300 */  sll        $v1, $v1, 5
/* 6DE0F40 80079A10 2000A3AF */  sw         $v1, 0x20($sp)
/* 6DE0F44 80079A14 40110200 */  sll        $v0, $v0, 5
/* 6DE0F48 80079A18 443C010C */  jal        func_8004F110
/* 6DE0F4C 80079A1C 1C00A2AF */   sw        $v0, 0x1C($sp)
/* 6DE0F50 80079A20 1800A427 */  addiu      $a0, $sp, 0x18
/* 6DE0F54 80079A24 21288000 */  addu       $a1, $a0, $zero
/* 6DE0F58 80079A28 653C010C */  jal        func_8004F194
/* 6DE0F5C 80079A2C F8FF0626 */   addiu     $a2, $s0, -0x8
/* 6DE0F60 80079A30 0008822A */  slti       $v0, $s4, 0x800
/* 6DE0F64 80079A34 08004014 */  bnez       $v0, .Llevel_32_80079A58
/* 6DE0F68 80079A38 01000224 */   addiu     $v0, $zero, 0x1
/* 6DE0F6C 80079A3C 0C004426 */  addiu      $a0, $s2, 0xC
/* 6DE0F70 80079A40 CD3C010C */  jal        func_8004F334
/* 6DE0F74 80079A44 1800A527 */   addiu     $a1, $sp, 0x18
/* 6DE0F78 80079A48 00084228 */  slti       $v0, $v0, 0x800
/* 6DE0F7C 80079A4C 06004010 */  beqz       $v0, .Llevel_32_80079A68
/* 6DE0F80 80079A50 00000000 */   nop
.Llevel_32_80079A54:
/* 6DE0F84 80079A54 01000224 */  addiu      $v0, $zero, 0x1
.Llevel_32_80079A58:
/* 6DE0F88 80079A58 480042A2 */  sb         $v0, 0x48($s2)
/* 6DE0F8C 80079A5C 21204002 */  addu       $a0, $s2, $zero
/* 6DE0F90 80079A60 D0D3000C */  jal        func_80034F40
/* 6DE0F94 80079A64 01000524 */   addiu     $a1, $zero, 0x1
.Llevel_32_80079A68:
/* 6DE0F98 80079A68 0780023C */  lui        $v0, %hi(D_8006C644)
/* 6DE0F9C 80079A6C 44C6428C */  lw         $v0, %lo(D_8006C644)($v0)
/* 6DE0FA0 80079A70 00000000 */  nop
/* 6DE0FA4 80079A74 0F004230 */  andi       $v0, $v0, 0xF
/* 6DE0FA8 80079A78 02004228 */  slti       $v0, $v0, 0x2
/* 6DE0FAC 80079A7C 22004010 */  beqz       $v0, .Llevel_32_80079B08
/* 6DE0FB0 80079A80 2800B127 */   addiu     $s1, $sp, 0x28
/* 6DE0FB4 80079A84 21202002 */  addu       $a0, $s1, $zero
/* 6DE0FB8 80079A88 0C005026 */  addiu      $s0, $s2, 0xC
/* 6DE0FBC 80079A8C 5E3C010C */  jal        func_8004F178
/* 6DE0FC0 80079A90 21280002 */   addu      $a1, $s0, $zero
/* 6DE0FC4 80079A94 21204002 */  addu       $a0, $s2, $zero
/* 6DE0FC8 80079A98 21280000 */  addu       $a1, $zero, $zero
/* 6DE0FCC 80079A9C C557010C */  jal        func_80055F14
/* 6DE0FD0 80079AA0 21300002 */   addu      $a2, $s0, $zero
/* 6DE0FD4 80079AA4 01000424 */  addiu      $a0, $zero, 0x1
/* 6DE0FD8 80079AA8 0C000524 */  addiu      $a1, $zero, 0xC
/* 6DE0FDC 80079AAC 21304002 */  addu       $a2, $s2, $zero
/* 6DE0FE0 80079AB0 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 6DE0FE4 80079AB4 E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 6DE0FE8 80079AB8 00000000 */  nop
/* 6DE0FEC 80079ABC 09F84000 */  jalr       $v0
/* 6DE0FF0 80079AC0 03000724 */   addiu     $a3, $zero, 0x3
/* 6DE0FF4 80079AC4 21200002 */  addu       $a0, $s0, $zero
/* 6DE0FF8 80079AC8 5E3C010C */  jal        func_8004F178
/* 6DE0FFC 80079ACC 21282002 */   addu      $a1, $s1, $zero
/* 6DE1000 80079AD0 C2E60108 */  j          .Llevel_32_80079B08
/* 6DE1004 80079AD4 00000000 */   nop
.L80079AD8_:
/* 6DE1008 80079AD8 0128822A */  slti       $v0, $s4, 0x2801
/* 6DE100C 80079ADC 0A004014 */  bnez       $v0, .Llevel_32_80079B08
/* 6DE1010 80079AE0 01000224 */   addiu     $v0, $zero, 0x1
/* 6DE1014 80079AE4 C2E60108 */  j          .Llevel_32_80079B08
/* 6DE1018 80079AE8 490042A2 */   sb        $v0, 0x49($s2)
.L80079AEC_:
/* 6DE101C 80079AEC 0780033C */  lui        $v1, %hi(D_8006E344)
/* 6DE1020 80079AF0 44E3638C */  lw         $v1, %lo(D_8006E344)($v1)
/* 6DE1024 80079AF4 01000224 */  addiu      $v0, $zero, 0x1
/* 6DE1028 80079AF8 03006210 */  beq        $v1, $v0, .Llevel_32_80079B08
/* 6DE102C 80079AFC 00000000 */   nop
.Llevel_32_80079B00:
/* 6DE1030 80079B00 04000224 */  addiu      $v0, $zero, 0x4
.Llevel_32_80079B04:
/* 6DE1034 80079B04 490042A2 */  sb         $v0, 0x49($s2)
.Llevel_32_80079B08:
/* 6DE1038 80079B08 0C00628E */  lw         $v0, 0xC($s3)
/* 6DE103C 80079B0C 00000000 */  nop
/* 6DE1040 80079B10 E2004010 */  beqz       $v0, .Llevel_32_80079E9C
/* 6DE1044 80079B14 00000000 */   nop
/* 6DE1048 80079B18 1C0040A0 */  sb         $zero, 0x1C($v0)
/* 6DE104C 80079B1C A7E70108 */  j          .Llevel_32_80079E9C
/* 6DE1050 80079B20 0C0060AE */   sw        $zero, 0xC($s3)
.Llevel_32_80079B24:
/* 6DE1054 80079B24 02006292 */  lbu        $v0, 0x2($s3)
/* 6DE1058 80079B28 00000000 */  nop
/* 6DE105C 80079B2C 06004314 */  bne        $v0, $v1, .Llevel_32_80079B48
/* 6DE1060 80079B30 0010023C */   lui       $v0, (0x10000002 >> 16)
/* 6DE1064 80079B34 02004234 */  ori        $v0, $v0, (0x10000002 & 0xFFFF)
/* 6DE1068 80079B38 0780013C */  lui        $at, %hi(D_80070328 + 0x20C)
/* 6DE106C 80079B3C 340522AC */  sw         $v0, %lo(D_80070328 + 0x20C)($at)
/* 6DE1070 80079B40 B724010C */  jal        func_800492DC
/* 6DE1074 80079B44 21200002 */   addu      $a0, $s0, $zero
.Llevel_32_80079B48:
/* 6DE1078 80079B48 A157010C */  jal        func_80055E84
/* 6DE107C 80079B4C 21204002 */   addu      $a0, $s2, $zero
/* 6DE1080 80079B50 1000638E */  lw         $v1, 0x10($s3)
/* 6DE1084 80079B54 00000000 */  nop
/* 6DE1088 80079B58 1A006004 */  bltz       $v1, .Llevel_32_80079BC4
/* 6DE108C 80079B5C 21804000 */   addu      $s0, $v0, $zero
/* 6DE1090 80079B60 21300000 */  addu       $a2, $zero, $zero
/* 6DE1094 80079B64 40100300 */  sll        $v0, $v1, 1
/* 6DE1098 80079B68 21104300 */  addu       $v0, $v0, $v1
/* 6DE109C 80079B6C 80100200 */  sll        $v0, $v0, 2
/* 6DE10A0 80079B70 23104300 */  subu       $v0, $v0, $v1
/* 6DE10A4 80079B74 C0100200 */  sll        $v0, $v0, 3
/* 6DE10A8 80079B78 0780033C */  lui        $v1, %hi(D_8006C550)
/* 6DE10AC 80079B7C 50C5638C */  lw         $v1, %lo(D_8006C550)($v1)
/* 6DE10B0 80079B80 0C00448E */  lw         $a0, 0xC($s2)
/* 6DE10B4 80079B84 1000458E */  lw         $a1, 0x10($s2)
/* 6DE10B8 80079B88 21104300 */  addu       $v0, $v0, $v1
/* 6DE10BC 80079B8C 0C00438C */  lw         $v1, 0xC($v0)
/* 6DE10C0 80079B90 1000428C */  lw         $v0, 0x10($v0)
/* 6DE10C4 80079B94 23206400 */  subu       $a0, $v1, $a0
/* 6DE10C8 80079B98 203A010C */  jal        func_8004E880
/* 6DE10CC 80079B9C 23284500 */   subu      $a1, $v0, $a1
/* 6DE10D0 80079BA0 21204002 */  addu       $a0, $s2, $zero
/* 6DE10D4 80079BA4 21284000 */  addu       $a1, $v0, $zero
/* 6DE10D8 80079BA8 06000624 */  addiu      $a2, $zero, 0x6
/* 6DE10DC 80079BAC 21380000 */  addu       $a3, $zero, $zero
/* 6DE10E0 80079BB0 1000A0AF */  sw         $zero, 0x10($sp)
/* 6DE10E4 80079BB4 17D6000C */  jal        func_8003585C
/* 6DE10E8 80079BB8 1400A0AF */   sw        $zero, 0x14($sp)
/* 6DE10EC 80079BBC F7E60108 */  j          .Llevel_32_80079BDC
/* 6DE10F0 80079BC0 21204002 */   addu      $a0, $s2, $zero
.Llevel_32_80079BC4:
/* 6DE10F4 80079BC4 21204002 */  addu       $a0, $s2, $zero
/* 6DE10F8 80079BC8 06000524 */  addiu      $a1, $zero, 0x6
/* 6DE10FC 80079BCC 21300000 */  addu       $a2, $zero, $zero
/* 6DE1100 80079BD0 CFD5000C */  jal        func_8003573C
/* 6DE1104 80079BD4 21380000 */   addu      $a3, $zero, $zero
/* 6DE1108 80079BD8 21204002 */  addu       $a0, $s2, $zero
.Llevel_32_80079BDC:
/* 6DE110C 80079BDC 4957010C */  jal        func_80055D24
/* 6DE1110 80079BE0 04000524 */   addiu     $a1, $zero, 0x4
/* 6DE1114 80079BE4 1400022A */  slti       $v0, $s0, 0x14
/* 6DE1118 80079BE8 0C004010 */  beqz       $v0, .Llevel_32_80079C1C
/* 6DE111C 80079BEC 02000224 */   addiu     $v0, $zero, 0x2
/* 6DE1120 80079BF0 02006392 */  lbu        $v1, 0x2($s3)
/* 6DE1124 80079BF4 00000000 */  nop
/* 6DE1128 80079BF8 7E006210 */  beq        $v1, $v0, .Llevel_32_80079DF4
/* 6DE112C 80079BFC 0110822A */   slti      $v0, $s4, 0x1001
/* 6DE1130 80079C00 7C004014 */  bnez       $v0, .Llevel_32_80079DF4
/* 6DE1134 80079C04 21204002 */   addu      $a0, $s2, $zero
/* 6DE1138 80079C08 480040A2 */  sb         $zero, 0x48($s2)
/* 6DE113C 80079C0C D0D3000C */  jal        func_80034F40
/* 6DE1140 80079C10 21280000 */   addu      $a1, $zero, $zero
/* 6DE1144 80079C14 7DE70108 */  j          .Llevel_32_80079DF4
/* 6DE1148 80079C18 00000000 */   nop
.Llevel_32_80079C1C:
/* 6DE114C 80079C1C 1F00022A */  slti       $v0, $s0, 0x1F
/* 6DE1150 80079C20 6C004010 */  beqz       $v0, .Llevel_32_80079DD4
/* 6DE1154 80079C24 05000224 */   addiu     $v0, $zero, 0x5
/* 6DE1158 80079C28 49004392 */  lbu        $v1, 0x49($s2)
/* 6DE115C 80079C2C 00000000 */  nop
/* 6DE1160 80079C30 19006210 */  beq        $v1, $v0, .Llevel_32_80079C98
/* 6DE1164 80079C34 2800B027 */   addiu     $s0, $sp, 0x28
/* 6DE1168 80079C38 21200002 */  addu       $a0, $s0, $zero
/* 6DE116C 80079C3C 5E3C010C */  jal        func_8004F178
/* 6DE1170 80079C40 0C004526 */   addiu     $a1, $s2, 0xC
/* 6DE1174 80079C44 21200002 */  addu       $a0, $s0, $zero
/* 6DE1178 80079C48 04007192 */  lbu        $s1, 0x4($s3)
/* 6DE117C 80079C4C D668000C */  jal        func_8001A358
/* 6DE1180 80079C50 00080524 */   addiu     $a1, $zero, 0x800
/* 6DE1184 80079C54 05004014 */  bnez       $v0, .Llevel_32_80079C6C
/* 6DE1188 80079C58 3000A2AF */   sw        $v0, 0x30($sp)
/* 6DE118C 80079C5C 0780023C */  lui        $v0, %hi(D_80070328 + 8)
/* 6DE1190 80079C60 3003428C */  lw         $v0, %lo(D_80070328 + 8)($v0)
/* 6DE1194 80079C64 00000000 */  nop
/* 6DE1198 80079C68 3000A2AF */  sw         $v0, 0x30($sp)
.Llevel_32_80079C6C:
/* 6DE119C 80079C6C 0780043C */  lui        $a0, %hi(D_8006D088)
/* 6DE11A0 80079C70 88D08424 */  addiu      $a0, $a0, %lo(D_8006D088)
/* 6DE11A4 80079C74 21280002 */  addu       $a1, $s0, $zero
/* 6DE11A8 80079C78 8DED000C */  jal        func_8003B634
/* 6DE11AC 80079C7C 21302002 */   addu      $a2, $s1, $zero
/* 6DE11B0 80079C80 21204002 */  addu       $a0, $s2, $zero
/* 6DE11B4 80079C84 21280000 */  addu       $a1, $zero, $zero
/* 6DE11B8 80079C88 AFEE000C */  jal        func_8003BABC
/* 6DE11BC 80079C8C 80000624 */   addiu     $a2, $zero, 0x80
/* 6DE11C0 80079C90 05000224 */  addiu      $v0, $zero, 0x5
/* 6DE11C4 80079C94 490042A2 */  sb         $v0, 0x49($s2)
.Llevel_32_80079C98:
/* 6DE11C8 80079C98 0C00628E */  lw         $v0, 0xC($s3)
/* 6DE11CC 80079C9C 00000000 */  nop
/* 6DE11D0 80079CA0 0D004014 */  bnez       $v0, .Llevel_32_80079CD8
/* 6DE11D4 80079CA4 21204002 */   addu      $a0, $s2, $zero
/* 6DE11D8 80079CA8 0010822A */  slti       $v0, $s4, 0x1000
/* 6DE11DC 80079CAC 06004010 */  beqz       $v0, .Llevel_32_80079CC8
/* 6DE11E0 80079CB0 04000424 */   addiu     $a0, $zero, 0x4
/* 6DE11E4 80079CB4 01000524 */  addiu      $a1, $zero, 0x1
/* 6DE11E8 80079CB8 6000063C */  lui        $a2, (0x608080 >> 16)
/* 6DE11EC 80079CBC 50BD000C */  jal        func_8002F540
/* 6DE11F0 80079CC0 8080C634 */   ori       $a2, $a2, (0x608080 & 0xFFFF)
/* 6DE11F4 80079CC4 0C0062AE */  sw         $v0, 0xC($s3)
.Llevel_32_80079CC8:
/* 6DE11F8 80079CC8 0C00628E */  lw         $v0, 0xC($s3)
/* 6DE11FC 80079CCC 00000000 */  nop
/* 6DE1200 80079CD0 1D004010 */  beqz       $v0, .Llevel_32_80079D48
/* 6DE1204 80079CD4 21204002 */   addu      $a0, $s2, $zero
.Llevel_32_80079CD8:
/* 6DE1208 80079CD8 21280000 */  addu       $a1, $zero, $zero
/* 6DE120C 80079CDC 3800B027 */  addiu      $s0, $sp, 0x38
/* 6DE1210 80079CE0 C557010C */  jal        func_80055F14
/* 6DE1214 80079CE4 21300002 */   addu      $a2, $s0, $zero
/* 6DE1218 80079CE8 0C00648E */  lw         $a0, 0xC($s3)
/* 6DE121C 80079CEC 5E3C010C */  jal        func_8004F178
/* 6DE1220 80079CF0 21280002 */   addu      $a1, $s0, $zero
/* 6DE1224 80079CF4 1000638E */  lw         $v1, 0x10($s3)
/* 6DE1228 80079CF8 00000000 */  nop
/* 6DE122C 80079CFC 0C006004 */  bltz       $v1, .Llevel_32_80079D30
/* 6DE1230 80079D00 40100300 */   sll       $v0, $v1, 1
/* 6DE1234 80079D04 21104300 */  addu       $v0, $v0, $v1
/* 6DE1238 80079D08 80100200 */  sll        $v0, $v0, 2
/* 6DE123C 80079D0C 23104300 */  subu       $v0, $v0, $v1
/* 6DE1240 80079D10 C0100200 */  sll        $v0, $v0, 3
/* 6DE1244 80079D14 0C00648E */  lw         $a0, 0xC($s3)
/* 6DE1248 80079D18 0780053C */  lui        $a1, %hi(D_8006C550)
/* 6DE124C 80079D1C 50C5A58C */  lw         $a1, %lo(D_8006C550)($a1)
/* 6DE1250 80079D20 0C008424 */  addiu      $a0, $a0, 0xC
/* 6DE1254 80079D24 2128A200 */  addu       $a1, $a1, $v0
/* 6DE1258 80079D28 50E70108 */  j          .Llevel_32_80079D40
/* 6DE125C 80079D2C 0C00A524 */   addiu     $a1, $a1, 0xC
.Llevel_32_80079D30:
/* 6DE1260 80079D30 0C00648E */  lw         $a0, 0xC($s3)
/* 6DE1264 80079D34 0780053C */  lui        $a1, %hi(D_80070328)
/* 6DE1268 80079D38 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 6DE126C 80079D3C 0C008424 */  addiu      $a0, $a0, 0xC
.Llevel_32_80079D40:
/* 6DE1270 80079D40 5E3C010C */  jal        func_8004F178
/* 6DE1274 80079D44 00000000 */   nop
.Llevel_32_80079D48:
/* 6DE1278 80079D48 4800A427 */  addiu      $a0, $sp, 0x48
/* 6DE127C 80079D4C 0C005026 */  addiu      $s0, $s2, 0xC
/* 6DE1280 80079D50 5E3C010C */  jal        func_8004F178
/* 6DE1284 80079D54 21280002 */   addu      $a1, $s0, $zero
/* 6DE1288 80079D58 1000638E */  lw         $v1, 0x10($s3)
/* 6DE128C 80079D5C 00000000 */  nop
/* 6DE1290 80079D60 0B006004 */  bltz       $v1, .Llevel_32_80079D90
/* 6DE1294 80079D64 21200002 */   addu      $a0, $s0, $zero
/* 6DE1298 80079D68 40100300 */  sll        $v0, $v1, 1
/* 6DE129C 80079D6C 21104300 */  addu       $v0, $v0, $v1
/* 6DE12A0 80079D70 80100200 */  sll        $v0, $v0, 2
/* 6DE12A4 80079D74 23104300 */  subu       $v0, $v0, $v1
/* 6DE12A8 80079D78 0780053C */  lui        $a1, %hi(D_8006C550)
/* 6DE12AC 80079D7C 50C5A58C */  lw         $a1, %lo(D_8006C550)($a1)
/* 6DE12B0 80079D80 C0100200 */  sll        $v0, $v0, 3
/* 6DE12B4 80079D84 2128A200 */  addu       $a1, $a1, $v0
/* 6DE12B8 80079D88 66E70108 */  j          .Llevel_32_80079D98
/* 6DE12BC 80079D8C 0C00A524 */   addiu     $a1, $a1, 0xC
.Llevel_32_80079D90:
/* 6DE12C0 80079D90 0780053C */  lui        $a1, %hi(D_80070328)
/* 6DE12C4 80079D94 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
.Llevel_32_80079D98:
/* 6DE12C8 80079D98 5E3C010C */  jal        func_8004F178
/* 6DE12CC 80079D9C 00000000 */   nop
/* 6DE12D0 80079DA0 01000424 */  addiu      $a0, $zero, 0x1
/* 6DE12D4 80079DA4 0C000524 */  addiu      $a1, $zero, 0xC
/* 6DE12D8 80079DA8 21304002 */  addu       $a2, $s2, $zero
/* 6DE12DC 80079DAC 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 6DE12E0 80079DB0 E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 6DE12E4 80079DB4 00000000 */  nop
/* 6DE12E8 80079DB8 09F84000 */  jalr       $v0
/* 6DE12EC 80079DBC 03000724 */   addiu     $a3, $zero, 0x3
/* 6DE12F0 80079DC0 0C004426 */  addiu      $a0, $s2, 0xC
/* 6DE12F4 80079DC4 5E3C010C */  jal        func_8004F178
/* 6DE12F8 80079DC8 4800A527 */   addiu     $a1, $sp, 0x48
/* 6DE12FC 80079DCC 7DE70108 */  j          .Llevel_32_80079DF4
/* 6DE1300 80079DD0 00000000 */   nop
.Llevel_32_80079DD4:
/* 6DE1304 80079DD4 0C00628E */  lw         $v0, 0xC($s3)
/* 6DE1308 80079DD8 00000000 */  nop
/* 6DE130C 80079DDC 05004010 */  beqz       $v0, .Llevel_32_80079DF4
/* 6DE1310 80079DE0 00000000 */   nop
/* 6DE1314 80079DE4 1C0040A0 */  sb         $zero, 0x1C($v0)
/* 6DE1318 80079DE8 FFFF0224 */  addiu      $v0, $zero, -0x1
/* 6DE131C 80079DEC 0C0060AE */  sw         $zero, 0xC($s3)
/* 6DE1320 80079DF0 100062AE */  sw         $v0, 0x10($s3)
.Llevel_32_80079DF4:
/* 6DE1324 80079DF4 06006286 */  lh         $v0, 0x6($s3)
/* 6DE1328 80079DF8 00000000 */  nop
/* 6DE132C 80079DFC 0D004104 */  bgez       $v0, .Llevel_32_80079E34
/* 6DE1330 80079E00 01000224 */   addiu     $v0, $zero, 0x1
/* 6DE1334 80079E04 02006392 */  lbu        $v1, 0x2($s3)
/* 6DE1338 80079E08 00000000 */  nop
/* 6DE133C 80079E0C 09006210 */  beq        $v1, $v0, .Llevel_32_80079E34
/* 6DE1340 80079E10 00000000 */   nop
/* 6DE1344 80079E14 1400428E */  lw         $v0, 0x14($s2)
/* 6DE1348 80079E18 00000000 */  nop
/* 6DE134C 80079E1C 20004224 */  addiu      $v0, $v0, 0x20
/* 6DE1350 80079E20 140042AE */  sw         $v0, 0x14($s2)
/* 6DE1354 80079E24 06006296 */  lhu        $v0, 0x6($s3)
/* 6DE1358 80079E28 00000000 */  nop
/* 6DE135C 80079E2C 20004224 */  addiu      $v0, $v0, 0x20
/* 6DE1360 80079E30 060062A6 */  sh         $v0, 0x6($s3)
.Llevel_32_80079E34:
/* 6DE1364 80079E34 0780023C */  lui        $v0, %hi(D_8006C770)
/* 6DE1368 80079E38 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 6DE136C 80079E3C 00000000 */  nop
/* 6DE1370 80079E40 16004010 */  beqz       $v0, .Llevel_32_80079E9C
/* 6DE1374 80079E44 01000224 */   addiu     $v0, $zero, 0x1
/* 6DE1378 80079E48 02006392 */  lbu        $v1, 0x2($s3)
/* 6DE137C 80079E4C 00000000 */  nop
/* 6DE1380 80079E50 0E006214 */  bne        $v1, $v0, .Llevel_32_80079E8C
/* 6DE1384 80079E54 04000224 */   addiu     $v0, $zero, 0x4
/* 6DE1388 80079E58 490042A2 */  sb         $v0, 0x49($s2)
/* 6DE138C 80079E5C 1400628E */  lw         $v0, 0x14($s3)
/* 6DE1390 80079E60 00000000 */  nop
/* 6DE1394 80079E64 09004010 */  beqz       $v0, .Llevel_32_80079E8C
/* 6DE1398 80079E68 11000224 */   addiu     $v0, $zero, 0x11
/* 6DE139C 80079E6C 0780033C */  lui        $v1, %hi(D_8006E044)
/* 6DE13A0 80079E70 44E0638C */  lw         $v1, %lo(D_8006E044)($v1)
/* 6DE13A4 80079E74 00000000 */  nop
/* 6DE13A8 80079E78 04006214 */  bne        $v1, $v0, .Llevel_32_80079E8C
/* 6DE13AC 80079E7C 00000000 */   nop
/* 6DE13B0 80079E80 0780013C */  lui        $at, %hi(D_8006E160)
/* 6DE13B4 80079E84 60E120AC */  sw         $zero, %lo(D_8006E160)($at)
/* 6DE13B8 80079E88 140060AE */  sw         $zero, 0x14($s3)
.Llevel_32_80079E8C:
/* 6DE13BC 80079E8C 480040A2 */  sb         $zero, 0x48($s2)
/* 6DE13C0 80079E90 21204002 */  addu       $a0, $s2, $zero
/* 6DE13C4 80079E94 D0D3000C */  jal        func_80034F40
/* 6DE13C8 80079E98 21280000 */   addu      $a1, $zero, $zero
.Llevel_32_80079E9C:
/* 6DE13CC 80079E9C 0800628E */  lw         $v0, 0x8($s3)
/* 6DE13D0 80079EA0 00000000 */  nop
/* 6DE13D4 80079EA4 08004014 */  bnez       $v0, .Llevel_32_80079EC8
/* 6DE13D8 80079EA8 83191400 */   sra       $v1, $s4, 6
/* 6DE13DC 80079EAC 04000424 */  addiu      $a0, $zero, 0x4
/* 6DE13E0 80079EB0 40000524 */  addiu      $a1, $zero, 0x40
/* 6DE13E4 80079EB4 14BB000C */  jal        func_8002EC50
/* 6DE13E8 80079EB8 21300000 */   addu      $a2, $zero, $zero
/* 6DE13EC 80079EBC 3B004010 */  beqz       $v0, .Llevel_32_80079FAC
/* 6DE13F0 80079EC0 080062AE */   sw        $v0, 0x8($s3)
/* 6DE13F4 80079EC4 83191400 */  sra        $v1, $s4, 6
.Llevel_32_80079EC8:
/* 6DE13F8 80079EC8 50006228 */  slti       $v0, $v1, 0x50
/* 6DE13FC 80079ECC 03004010 */  beqz       $v0, .Llevel_32_80079EDC
/* 6DE1400 80079ED0 A1006228 */   slti      $v0, $v1, 0xA1
/* 6DE1404 80079ED4 50000324 */  addiu      $v1, $zero, 0x50
/* 6DE1408 80079ED8 A1006228 */  slti       $v0, $v1, 0xA1
.Llevel_32_80079EDC:
/* 6DE140C 80079EDC 02004014 */  bnez       $v0, .Llevel_32_80079EE8
/* 6DE1410 80079EE0 00000000 */   nop
/* 6DE1414 80079EE4 A0000324 */  addiu      $v1, $zero, 0xA0
.Llevel_32_80079EE8:
/* 6DE1418 80079EE8 0800628E */  lw         $v0, 0x8($s3)
/* 6DE141C 80079EEC 00000000 */  nop
/* 6DE1420 80079EF0 110043A0 */  sb         $v1, 0x11($v0)
/* 6DE1424 80079EF4 0780023C */  lui        $v0, %hi(D_8006C644)
/* 6DE1428 80079EF8 44C6428C */  lw         $v0, %lo(D_8006C644)($v0)
/* 6DE142C 80079EFC 00000000 */  nop
/* 6DE1430 80079F00 C0100200 */  sll        $v0, $v0, 3
/* 6DE1434 80079F04 F8014230 */  andi       $v0, $v0, 0x1F8
/* 6DE1438 80079F08 0680013C */  lui        $at, %hi(D_80065920)
/* 6DE143C 80079F0C 21082200 */  addu       $at, $at, $v0
/* 6DE1440 80079F10 20592294 */  lhu        $v0, %lo(D_80065920)($at)
/* 6DE1444 80079F14 0800648E */  lw         $a0, 0x8($s3)
/* 6DE1448 80079F18 00140200 */  sll        $v0, $v0, 16
/* 6DE144C 80079F1C C3150200 */  sra        $v0, $v0, 23
/* 6DE1450 80079F20 70004224 */  addiu      $v0, $v0, 0x70
/* 6DE1454 80079F24 001A0200 */  sll        $v1, $v0, 8
/* 6DE1458 80079F28 21184300 */  addu       $v1, $v0, $v1
/* 6DE145C 80079F2C 43100200 */  sra        $v0, $v0, 1
/* 6DE1460 80079F30 00140200 */  sll        $v0, $v0, 16
/* 6DE1464 80079F34 21186200 */  addu       $v1, $v1, $v0
/* 6DE1468 80079F38 0C0083AC */  sw         $v1, 0xC($a0)
/* 6DE146C 80079F3C 4D004292 */  lbu        $v0, 0x4D($s2)
/* 6DE1470 80079F40 00000000 */  nop
/* 6DE1474 80079F44 16004010 */  beqz       $v0, .Llevel_32_80079FA0
/* 6DE1478 80079F48 21204002 */   addu      $a0, $s2, $zero
/* 6DE147C 80079F4C 21280000 */  addu       $a1, $zero, $zero
/* 6DE1480 80079F50 C557010C */  jal        func_80055F14
/* 6DE1484 80079F54 1800A627 */   addiu     $a2, $sp, 0x18
/* 6DE1488 80079F58 1800A427 */  addiu      $a0, $sp, 0x18
/* 6DE148C 80079F5C 21288000 */  addu       $a1, $a0, $zero
/* 6DE1490 80079F60 0C005026 */  addiu      $s0, $s2, 0xC
/* 6DE1494 80079F64 723C010C */  jal        func_8004F1C8
/* 6DE1498 80079F68 21300002 */   addu      $a2, $s0, $zero
/* 6DE149C 80079F6C 1800A427 */  addiu      $a0, $sp, 0x18
/* 6DE14A0 80079F70 3A3C010C */  jal        func_8004F0E8
/* 6DE14A4 80079F74 05000524 */   addiu     $a1, $zero, 0x5
/* 6DE14A8 80079F78 1800A427 */  addiu      $a0, $sp, 0x18
/* 6DE14AC 80079F7C 4F004692 */  lbu        $a2, 0x4F($s2)
/* 6DE14B0 80079F80 8A3C010C */  jal        func_8004F228
/* 6DE14B4 80079F84 21288000 */   addu      $a1, $a0, $zero
/* 6DE14B8 80079F88 21280002 */  addu       $a1, $s0, $zero
/* 6DE14BC 80079F8C 0800648E */  lw         $a0, 0x8($s3)
/* 6DE14C0 80079F90 653C010C */  jal        func_8004F194
/* 6DE14C4 80079F94 1800A627 */   addiu     $a2, $sp, 0x18
/* 6DE14C8 80079F98 EBE70108 */  j          .Llevel_32_80079FAC
/* 6DE14CC 80079F9C 00000000 */   nop
.Llevel_32_80079FA0:
/* 6DE14D0 80079FA0 0800648E */  lw         $a0, 0x8($s3)
/* 6DE14D4 80079FA4 5E3C010C */  jal        func_8004F178
/* 6DE14D8 80079FA8 0C004526 */   addiu     $a1, $s2, 0xC
.Llevel_32_80079FAC:
/* 6DE14DC 80079FAC 6C00BF8F */  lw         $ra, 0x6C($sp)
/* 6DE14E0 80079FB0 6800B48F */  lw         $s4, 0x68($sp)
/* 6DE14E4 80079FB4 6400B38F */  lw         $s3, 0x64($sp)
/* 6DE14E8 80079FB8 6000B28F */  lw         $s2, 0x60($sp)
/* 6DE14EC 80079FBC 5C00B18F */  lw         $s1, 0x5C($sp)
/* 6DE14F0 80079FC0 5800B08F */  lw         $s0, 0x58($sp)
/* 6DE14F4 80079FC4 7000BD27 */  addiu      $sp, $sp, 0x70
/* 6DE14F8 80079FC8 0800E003 */  jr         $ra
/* 6DE14FC 80079FCC 00000000 */   nop
.size func_level_32_8007945C, . - func_level_32_8007945C
