.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_27_800746E8
/* 63E8C18 800746E8 C4E70780 */ .word .L8007E7C4_
/* 63E8C1C 800746EC 38EA0780 */ .word .L8007EA38_
/* 63E8C20 800746F0 54EB0780 */ .word .L8007EB54_
/* 63E8C24 800746F4 2CEC0780 */ .word .L8007EC2C_
/* 63E8C28 800746F8 60EC0780 */ .word .L8007EC60_
/* 63E8C2C 800746FC 0CEE0780 */ .word .L8007EE0C_
/* 63E8C30 80074700 9CEE0780 */ .word .L8007EE9C_
/* 63E8C34 80074704 5CEF0780 */ .word .L8007EF5C_
/* 63E8C38 80074708 50F00780 */ .word .L8007F050_
/* 63E8C3C 8007470C D0F00780 */ .word .L8007F0D0_
.size jtbl_level_27_800746E8, . - jtbl_level_27_800746E8


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_27_8007E76C
/* 63F2C9C 8007E76C 68FFBD27 */  addiu      $sp, $sp, -0x98
/* 63F2CA0 8007E770 7800B2AF */  sw         $s2, 0x78($sp)
/* 63F2CA4 8007E774 21908000 */  addu       $s2, $a0, $zero
/* 63F2CA8 8007E778 9000BFAF */  sw         $ra, 0x90($sp)
/* 63F2CAC 8007E77C 8C00B7AF */  sw         $s7, 0x8C($sp)
/* 63F2CB0 8007E780 8800B6AF */  sw         $s6, 0x88($sp)
/* 63F2CB4 8007E784 8400B5AF */  sw         $s5, 0x84($sp)
/* 63F2CB8 8007E788 8000B4AF */  sw         $s4, 0x80($sp)
/* 63F2CBC 8007E78C 7C00B3AF */  sw         $s3, 0x7C($sp)
/* 63F2CC0 8007E790 7400B1AF */  sw         $s1, 0x74($sp)
/* 63F2CC4 8007E794 7000B0AF */  sw         $s0, 0x70($sp)
/* 63F2CC8 8007E798 48004392 */  lbu        $v1, 0x48($s2)
/* 63F2CCC 8007E79C 0000538E */  lw         $s3, 0x0($s2)
/* 63F2CD0 8007E7A0 0A00622C */  sltiu      $v0, $v1, 0xA
/* 63F2CD4 8007E7A4 6F024010 */  beqz       $v0, .Llevel_27_8007F164
/* 63F2CD8 8007E7A8 80100300 */   sll       $v0, $v1, 2
/* 63F2CDC 8007E7AC 0780013C */  lui        $at, %hi(jtbl_level_27_800746E8)
/* 63F2CE0 8007E7B0 21082200 */  addu       $at, $at, $v0
/* 63F2CE4 8007E7B4 E846228C */  lw         $v0, %lo(jtbl_level_27_800746E8)($at)
/* 63F2CE8 8007E7B8 00000000 */  nop
/* 63F2CEC 8007E7BC 08004000 */  jr         $v0
/* 63F2CF0 8007E7C0 00000000 */   nop
.L8007E7C4_:
/* 63F2CF4 8007E7C4 49004392 */  lbu        $v1, 0x49($s2)
/* 63F2CF8 8007E7C8 00000000 */  nop
/* 63F2CFC 8007E7CC 05006010 */  beqz       $v1, .Llevel_27_8007E7E4
/* 63F2D00 8007E7D0 01000224 */   addiu     $v0, $zero, 0x1
/* 63F2D04 8007E7D4 8F006210 */  beq        $v1, $v0, .Llevel_27_8007EA14
/* 63F2D08 8007E7D8 21204002 */   addu      $a0, $s2, $zero
/* 63F2D0C 8007E7DC 59FC0108 */  j          .Llevel_27_8007F164
/* 63F2D10 8007E7E0 00000000 */   nop
.Llevel_27_8007E7E4:
/* 63F2D14 8007E7E4 0780023C */  lui        $v0, %hi(D_80071588)
/* 63F2D18 8007E7E8 88154290 */  lbu        $v0, %lo(D_80071588)($v0)
/* 63F2D1C 8007E7EC 00000000 */  nop
/* 63F2D20 8007E7F0 0B004014 */  bnez       $v0, .Llevel_27_8007E820
/* 63F2D24 8007E7F4 14000224 */   addiu     $v0, $zero, 0x14
/* 63F2D28 8007E7F8 0780033C */  lui        $v1, %hi(D_8006C5BC)
/* 63F2D2C 8007E7FC BCC5638C */  lw         $v1, %lo(D_8006C5BC)($v1)
/* 63F2D30 8007E800 00000000 */  nop
/* 63F2D34 8007E804 0A006210 */  beq        $v1, $v0, .Llevel_27_8007E830
/* 63F2D38 8007E808 0110153C */   lui       $s5, (0x10018000 >> 16)
/* 63F2D3C 8007E80C 0780023C */  lui        $v0, %hi(D_80071587)
/* 63F2D40 8007E810 87154290 */  lbu        $v0, %lo(D_80071587)($v0)
/* 63F2D44 8007E814 00000000 */  nop
/* 63F2D48 8007E818 06004014 */  bnez       $v0, .Llevel_27_8007E834
/* 63F2D4C 8007E81C 0080B536 */   ori       $s5, $s5, (0x10018000 & 0xFFFF)
.Llevel_27_8007E820:
/* 63F2D50 8007E820 C656010C */  jal        func_80055B18
/* 63F2D54 8007E824 21204002 */   addu      $a0, $s2, $zero
/* 63F2D58 8007E828 76FC0108 */  j          .Llevel_27_8007F1D8
/* 63F2D5C 8007E82C 00000000 */   nop
.Llevel_27_8007E830:
/* 63F2D60 8007E830 0080B536 */  ori        $s5, $s5, (0x10018000 & 0xFFFF)
.Llevel_27_8007E834:
/* 63F2D64 8007E834 0780113C */  lui        $s1, %hi(D_80070328 + 0x20C)
/* 63F2D68 8007E838 34053126 */  addiu      $s1, $s1, %lo(D_80070328 + 0x20C)
/* 63F2D6C 8007E83C 20003726 */  addiu      $s7, $s1, 0x20
/* 63F2D70 8007E840 2120E002 */  addu       $a0, $s7, $zero
/* 63F2D74 8007E844 0C005426 */  addiu      $s4, $s2, 0xC
/* 63F2D78 8007E848 1400428E */  lw         $v0, 0x14($s2)
/* 63F2D7C 8007E84C 21288002 */  addu       $a1, $s4, $zero
/* 63F2D80 8007E850 00104224 */  addiu      $v0, $v0, 0x1000
/* 63F2D84 8007E854 140042AE */  sw         $v0, 0x14($s2)
/* 63F2D88 8007E858 000035AE */  sw         $s5, 0x0($s1)
/* 63F2D8C 8007E85C 5E3C010C */  jal        func_8004F178
/* 63F2D90 8007E860 300020AE */   sw        $zero, 0x30($s1)
/* 63F2D94 8007E864 49005026 */  addiu      $s0, $s2, 0x49
/* 63F2D98 8007E868 2800228E */  lw         $v0, 0x28($s1)
/* 63F2D9C 8007E86C 38FE238E */  lw         $v1, -0x1C8($s1)
/* 63F2DA0 8007E870 33014224 */  addiu      $v0, $v0, 0x133
/* 63F2DA4 8007E874 21104300 */  addu       $v0, $v0, $v1
/* 63F2DA8 8007E878 280022AE */  sw         $v0, 0x28($s1)
/* 63F2DAC 8007E87C 44004292 */  lbu        $v0, 0x44($s2)
/* 63F2DB0 8007E880 21200002 */  addu       $a0, $s0, $zero
/* 63F2DB4 8007E884 1C0022A2 */  sb         $v0, 0x1C($s1)
/* 63F2DB8 8007E888 45004292 */  lbu        $v0, 0x45($s2)
/* 63F2DBC 8007E88C 01000524 */  addiu      $a1, $zero, 0x1
/* 63F2DC0 8007E890 1D0022A2 */  sb         $v0, 0x1D($s1)
/* 63F2DC4 8007E894 46004292 */  lbu        $v0, 0x46($s2)
/* 63F2DC8 8007E898 0780063C */  lui        $a2, %hi(D_8006D088)
/* 63F2DCC 8007E89C 88D0C624 */  addiu      $a2, $a2, %lo(D_8006D088)
/* 63F2DD0 8007E8A0 1E0022A2 */  sb         $v0, 0x1E($s1)
/* 63F2DD4 8007E8A4 01000224 */  addiu      $v0, $zero, 0x1
/* 63F2DD8 8007E8A8 EDED000C */  jal        func_8003B7B4
/* 63F2DDC 8007E8AC 490042A2 */   sb        $v0, 0x49($s2)
/* 63F2DE0 8007E8B0 21200002 */  addu       $a0, $s0, $zero
/* 63F2DE4 8007E8B4 0780063C */  lui        $a2, %hi(D_8006C7F8)
/* 63F2DE8 8007E8B8 F8C7C624 */  addiu      $a2, $a2, %lo(D_8006C7F8)
/* 63F2DEC 8007E8BC EDED000C */  jal        func_8003B7B4
/* 63F2DF0 8007E8C0 01000524 */   addiu     $a1, $zero, 0x1
/* 63F2DF4 8007E8C4 07001624 */  addiu      $s6, $zero, 0x7
/* 63F2DF8 8007E8C8 480056A2 */  sb         $s6, 0x48($s2)
/* 63F2DFC 8007E8CC 0780043C */  lui        $a0, %hi(D_8006C73C)
/* 63F2E00 8007E8D0 3CC7848C */  lw         $a0, %lo(D_8006C73C)($a0)
/* 63F2E04 8007E8D4 00000000 */  nop
/* 63F2E08 8007E8D8 48008010 */  beqz       $a0, .Llevel_27_8007E9FC
/* 63F2E0C 8007E8DC 00000000 */   nop
/* 63F2E10 8007E8E0 0780023C */  lui        $v0, %hi(D_8006C5BC)
/* 63F2E14 8007E8E4 BCC5428C */  lw         $v0, %lo(D_8006C5BC)($v0)
/* 63F2E18 8007E8E8 00000000 */  nop
/* 63F2E1C 8007E8EC 43004410 */  beq        $v0, $a0, .Llevel_27_8007E9FC
/* 63F2E20 8007E8F0 6666023C */   lui       $v0, (0x66666667 >> 16)
/* 63F2E24 8007E8F4 67664234 */  ori        $v0, $v0, (0x66666667 & 0xFFFF)
/* 63F2E28 8007E8F8 18008200 */  mult       $a0, $v0
/* 63F2E2C 8007E8FC C3170400 */  sra        $v0, $a0, 31
/* 63F2E30 8007E900 10480000 */  mfhi       $t1
/* 63F2E34 8007E904 83180900 */  sra        $v1, $t1, 2
/* 63F2E38 8007E908 23186200 */  subu       $v1, $v1, $v0
/* 63F2E3C 8007E90C 80100300 */  sll        $v0, $v1, 2
/* 63F2E40 8007E910 21104300 */  addu       $v0, $v0, $v1
/* 63F2E44 8007E914 40100200 */  sll        $v0, $v0, 1
/* 63F2E48 8007E918 23188200 */  subu       $v1, $a0, $v0
/* 63F2E4C 8007E91C 05006010 */  beqz       $v1, .Llevel_27_8007E934
/* 63F2E50 8007E920 07000224 */   addiu     $v0, $zero, 0x7
/* 63F2E54 8007E924 35006214 */  bne        $v1, $v0, .Llevel_27_8007E9FC
/* 63F2E58 8007E928 3C008228 */   slti      $v0, $a0, 0x3C
/* 63F2E5C 8007E92C 33004010 */  beqz       $v0, .Llevel_27_8007E9FC
/* 63F2E60 8007E930 00000000 */   nop
.Llevel_27_8007E934:
/* 63F2E64 8007E934 36004386 */  lh         $v1, 0x36($s2)
/* 63F2E68 8007E938 0780023C */  lui        $v0, %hi(D_8006C528)
/* 63F2E6C 8007E93C 28C5428C */  lw         $v0, %lo(D_8006C528)($v0)
/* 63F2E70 8007E940 00000000 */  nop
/* 63F2E74 8007E944 2D006214 */  bne        $v1, $v0, .Llevel_27_8007E9FC
/* 63F2E78 8007E948 00000000 */   nop
/* 63F2E7C 8007E94C 1400428E */  lw         $v0, 0x14($s2)
/* 63F2E80 8007E950 0780103C */  lui        $s0, %hi(D_8006E168)
/* 63F2E84 8007E954 68E11026 */  addiu      $s0, $s0, %lo(D_8006E168)
/* 63F2E88 8007E958 000C4224 */  addiu      $v0, $v0, 0xC00
/* 63F2E8C 8007E95C 140042AE */  sw         $v0, 0x14($s2)
/* 63F2E90 8007E960 0800628E */  lw         $v0, 0x8($s3)
/* 63F2E94 8007E964 21200002 */  addu       $a0, $s0, $zero
/* 63F2E98 8007E968 0C00458C */  lw         $a1, 0xC($v0)
/* 63F2E9C 8007E96C BC4D000C */  jal        func_800136F0
/* 63F2EA0 8007E970 21308002 */   addu      $a2, $s4, $zero
/* 63F2EA4 8007E974 2120E002 */  addu       $a0, $s7, $zero
/* 63F2EA8 8007E978 0000028E */  lw         $v0, 0x0($s0)
/* 63F2EAC 8007E97C 0780033C */  lui        $v1, %hi(D_80070328 + 0x64)
/* 63F2EB0 8007E980 8C03638C */  lw         $v1, %lo(D_80070328 + 0x64)($v1)
/* 63F2EB4 8007E984 21288002 */  addu       $a1, $s4, $zero
/* 63F2EB8 8007E988 0780013C */  lui        $at, %hi(D_8006E174)
/* 63F2EBC 8007E98C 74E120AC */  sw         $zero, %lo(D_8006E174)($at)
/* 63F2EC0 8007E990 0780013C */  lui        $at, %hi(D_8006E178)
/* 63F2EC4 8007E994 78E120AC */  sw         $zero, %lo(D_8006E178)($at)
/* 63F2EC8 8007E998 000035AE */  sw         $s5, 0x0($s1)
/* 63F2ECC 8007E99C 300020AE */  sw         $zero, 0x30($s1)
/* 63F2ED0 8007E9A0 23104300 */  subu       $v0, $v0, $v1
/* 63F2ED4 8007E9A4 5E3C010C */  jal        func_8004F178
/* 63F2ED8 8007E9A8 000002AE */   sw        $v0, 0x0($s0)
/* 63F2EDC 8007E9AC 2800228E */  lw         $v0, 0x28($s1)
/* 63F2EE0 8007E9B0 38FE238E */  lw         $v1, -0x1C8($s1)
/* 63F2EE4 8007E9B4 33014224 */  addiu      $v0, $v0, 0x133
/* 63F2EE8 8007E9B8 21104300 */  addu       $v0, $v0, $v1
/* 63F2EEC 8007E9BC 280022AE */  sw         $v0, 0x28($s1)
/* 63F2EF0 8007E9C0 44004292 */  lbu        $v0, 0x44($s2)
/* 63F2EF4 8007E9C4 00000000 */  nop
/* 63F2EF8 8007E9C8 1C0022A2 */  sb         $v0, 0x1C($s1)
/* 63F2EFC 8007E9CC 45004292 */  lbu        $v0, 0x45($s2)
/* 63F2F00 8007E9D0 00000000 */  nop
/* 63F2F04 8007E9D4 1D0022A2 */  sb         $v0, 0x1D($s1)
/* 63F2F08 8007E9D8 46004292 */  lbu        $v0, 0x46($s2)
/* 63F2F0C 8007E9DC 21200002 */  addu       $a0, $s0, $zero
/* 63F2F10 8007E9E0 EA4A000C */  jal        func_80012BA8
/* 63F2F14 8007E9E4 1E0022A2 */   sb        $v0, 0x1E($s1)
/* 63F2F18 8007E9E8 14000426 */  addiu      $a0, $s0, 0x14
/* 63F2F1C 8007E9EC 5E3C010C */  jal        func_8004F178
/* 63F2F20 8007E9F0 F0FE0526 */   addiu     $a1, $s0, -0x110
/* 63F2F24 8007E9F4 59FC0108 */  j          .Llevel_27_8007F164
/* 63F2F28 8007E9F8 480056A2 */   sb        $s6, 0x48($s2)
.Llevel_27_8007E9FC:
/* 63F2F2C 8007E9FC 48004292 */  lbu        $v0, 0x48($s2)
/* 63F2F30 8007EA00 00000000 */  nop
/* 63F2F34 8007EA04 D7014014 */  bnez       $v0, .Llevel_27_8007F164
/* 63F2F38 8007EA08 01000224 */   addiu     $v0, $zero, 0x1
/* 63F2F3C 8007EA0C 59FC0108 */  j          .Llevel_27_8007F164
/* 63F2F40 8007EA10 480042A2 */   sb        $v0, 0x48($s2)
.Llevel_27_8007EA14:
/* 63F2F44 8007EA14 1400428E */  lw         $v0, 0x14($s2)
/* 63F2F48 8007EA18 02000524 */  addiu      $a1, $zero, 0x2
/* 63F2F4C 8007EA1C 000F4224 */  addiu      $v0, $v0, 0xF00
/* 63F2F50 8007EA20 4957010C */  jal        func_80055D24
/* 63F2F54 8007EA24 140042AE */   sw        $v0, 0x14($s2)
/* 63F2F58 8007EA28 08000224 */  addiu      $v0, $zero, 0x8
/* 63F2F5C 8007EA2C 0C0060AE */  sw         $zero, 0xC($s3)
/* 63F2F60 8007EA30 59FC0108 */  j          .Llevel_27_8007F164
/* 63F2F64 8007EA34 480042A2 */   sb        $v0, 0x48($s2)
.L8007EA38_:
/* 63F2F68 8007EA38 49004392 */  lbu        $v1, 0x49($s2)
/* 63F2F6C 8007EA3C 00000000 */  nop
/* 63F2F70 8007EA40 05006010 */  beqz       $v1, .Llevel_27_8007EA58
/* 63F2F74 8007EA44 01000224 */   addiu     $v0, $zero, 0x1
/* 63F2F78 8007EA48 33006210 */  beq        $v1, $v0, .Llevel_27_8007EB18
/* 63F2F7C 8007EA4C 1000A427 */   addiu     $a0, $sp, 0x10
/* 63F2F80 8007EA50 CFFA0108 */  j          .Llevel_27_8007EB3C
/* 63F2F84 8007EA54 00000000 */   nop
.Llevel_27_8007EA58:
/* 63F2F88 8007EA58 46004292 */  lbu        $v0, 0x46($s2)
/* 63F2F8C 8007EA5C 1000A427 */  addiu      $a0, $sp, 0x10
/* 63F2F90 8007EA60 40100200 */  sll        $v0, $v0, 1
/* 63F2F94 8007EA64 0680013C */  lui        $at, %hi(D_80065920)
/* 63F2F98 8007EA68 21082200 */  addu       $at, $at, $v0
/* 63F2F9C 8007EA6C 20592384 */  lh         $v1, %lo(D_80065920)($at)
/* 63F2FA0 8007EA70 21288000 */  addu       $a1, $a0, $zero
/* 63F2FA4 8007EA74 40100300 */  sll        $v0, $v1, 1
/* 63F2FA8 8007EA78 21104300 */  addu       $v0, $v0, $v1
/* 63F2FAC 8007EA7C C3100200 */  sra        $v0, $v0, 3
/* 63F2FB0 8007EA80 1000A2AF */  sw         $v0, 0x10($sp)
/* 63F2FB4 8007EA84 46004292 */  lbu        $v0, 0x46($s2)
/* 63F2FB8 8007EA88 0C005026 */  addiu      $s0, $s2, 0xC
/* 63F2FBC 8007EA8C 40100200 */  sll        $v0, $v0, 1
/* 63F2FC0 8007EA90 0680013C */  lui        $at, %hi(D_800658A0)
/* 63F2FC4 8007EA94 21082200 */  addu       $at, $at, $v0
/* 63F2FC8 8007EA98 A0582384 */  lh         $v1, %lo(D_800658A0)($at)
/* 63F2FCC 8007EA9C 21300002 */  addu       $a2, $s0, $zero
/* 63F2FD0 8007EAA0 1800A0AF */  sw         $zero, 0x18($sp)
/* 63F2FD4 8007EAA4 40100300 */  sll        $v0, $v1, 1
/* 63F2FD8 8007EAA8 21104300 */  addu       $v0, $v0, $v1
/* 63F2FDC 8007EAAC C3100200 */  sra        $v0, $v0, 3
/* 63F2FE0 8007EAB0 653C010C */  jal        func_8004F194
/* 63F2FE4 8007EAB4 1400A2AF */   sw        $v0, 0x14($sp)
/* 63F2FE8 8007EAB8 1000A427 */  addiu      $a0, $sp, 0x10
/* 63F2FEC 8007EABC 21300000 */  addu       $a2, $zero, $zero
/* 63F2FF0 8007EAC0 46004592 */  lbu        $a1, 0x46($s2)
/* 63F2FF4 8007EAC4 0780023C */  lui        $v0, %hi(unk_ovlheader_80074330)
/* 63F2FF8 8007EAC8 3043428C */  lw         $v0, %lo(unk_ovlheader_80074330)($v0)
/* 63F2FFC 8007EACC 00000000 */  nop
/* 63F3000 8007EAD0 09F84000 */  jalr       $v0
/* 63F3004 8007EAD4 8000A524 */   addiu     $a1, $a1, 0x80
/* 63F3008 8007EAD8 18004010 */  beqz       $v0, .Llevel_27_8007EB3C
/* 63F300C 8007EADC 1000A427 */   addiu     $a0, $sp, 0x10
/* 63F3010 8007EAE0 0780013C */  lui        $at, %hi(D_80070328 + 0x214)
/* 63F3014 8007EAE4 3C0520AC */  sw         $zero, %lo(D_80070328 + 0x214)($at)
/* 63F3018 8007EAE8 5E3C010C */  jal        func_8004F178
/* 63F301C 8007EAEC 21280002 */   addu      $a1, $s0, $zero
/* 63F3020 8007EAF0 1000A427 */  addiu      $a0, $sp, 0x10
/* 63F3024 8007EAF4 1800A28F */  lw         $v0, 0x18($sp)
/* 63F3028 8007EAF8 0780033C */  lui        $v1, %hi(unk_ovlheader_80074334)
/* 63F302C 8007EAFC 3443638C */  lw         $v1, %lo(unk_ovlheader_80074334)($v1)
/* 63F3030 8007EB00 80024224 */  addiu      $v0, $v0, 0x280
/* 63F3034 8007EB04 09F86000 */  jalr       $v1
/* 63F3038 8007EB08 1800A2AF */   sw        $v0, 0x18($sp)
/* 63F303C 8007EB0C 01000224 */  addiu      $v0, $zero, 0x1
/* 63F3040 8007EB10 CFFA0108 */  j          .Llevel_27_8007EB3C
/* 63F3044 8007EB14 490042A2 */   sb        $v0, 0x49($s2)
.Llevel_27_8007EB18:
/* 63F3048 8007EB18 5E3C010C */  jal        func_8004F178
/* 63F304C 8007EB1C 0C004526 */   addiu     $a1, $s2, 0xC
/* 63F3050 8007EB20 1000A427 */  addiu      $a0, $sp, 0x10
/* 63F3054 8007EB24 1800A28F */  lw         $v0, 0x18($sp)
/* 63F3058 8007EB28 0780033C */  lui        $v1, %hi(unk_ovlheader_80074334)
/* 63F305C 8007EB2C 3443638C */  lw         $v1, %lo(unk_ovlheader_80074334)($v1)
/* 63F3060 8007EB30 80024224 */  addiu      $v0, $v0, 0x280
/* 63F3064 8007EB34 09F86000 */  jalr       $v1
/* 63F3068 8007EB38 1800A2AF */   sw        $v0, 0x18($sp)
.Llevel_27_8007EB3C:
/* 63F306C 8007EB3C 0780023C */  lui        $v0, %hi(D_80070328 + 0x13C)
/* 63F3070 8007EB40 6404428C */  lw         $v0, %lo(D_80070328 + 0x13C)($v0)
/* 63F3074 8007EB44 00000000 */  nop
/* 63F3078 8007EB48 86015214 */  bne        $v0, $s2, .Llevel_27_8007F164
/* 63F307C 8007EB4C 02000224 */   addiu     $v0, $zero, 0x2
/* 63F3080 8007EB50 480042A2 */  sb         $v0, 0x48($s2)
.L8007EB54_:
/* 63F3084 8007EB54 0780023C */  lui        $v0, %hi(D_80070328 + 0x13C)
/* 63F3088 8007EB58 6404428C */  lw         $v0, %lo(D_80070328 + 0x13C)($v0)
/* 63F308C 8007EB5C 00000000 */  nop
/* 63F3090 8007EB60 05005210 */  beq        $v0, $s2, .Llevel_27_8007EB78
/* 63F3094 8007EB64 01000224 */   addiu     $v0, $zero, 0x1
/* 63F3098 8007EB68 0780013C */  lui        $at, %hi(D_8006E160)
/* 63F309C 8007EB6C 60E120AC */  sw         $zero, %lo(D_8006E160)($at)
/* 63F30A0 8007EB70 59FC0108 */  j          .Llevel_27_8007F164
/* 63F30A4 8007EB74 480042A2 */   sb        $v0, 0x48($s2)
.Llevel_27_8007EB78:
/* 63F30A8 8007EB78 0C005126 */  addiu      $s1, $s2, 0xC
/* 63F30AC 8007EB7C 21202002 */  addu       $a0, $s1, $zero
/* 63F30B0 8007EB80 46004592 */  lbu        $a1, 0x46($s2)
/* 63F30B4 8007EB84 0780023C */  lui        $v0, %hi(unk_ovlheader_80074330)
/* 63F30B8 8007EB88 3043428C */  lw         $v0, %lo(unk_ovlheader_80074330)($v0)
/* 63F30BC 8007EB8C 00000000 */  nop
/* 63F30C0 8007EB90 09F84000 */  jalr       $v0
/* 63F30C4 8007EB94 21300000 */   addu      $a2, $zero, $zero
/* 63F30C8 8007EB98 11004010 */  beqz       $v0, .Llevel_27_8007EBE0
/* 63F30CC 8007EB9C 6666033C */   lui       $v1, (0x66666667 >> 16)
/* 63F30D0 8007EBA0 0780023C */  lui        $v0, %hi(D_8006C5BC)
/* 63F30D4 8007EBA4 BCC5428C */  lw         $v0, %lo(D_8006C5BC)($v0)
/* 63F30D8 8007EBA8 67666334 */  ori        $v1, $v1, (0x66666667 & 0xFFFF)
/* 63F30DC 8007EBAC 18004300 */  mult       $v0, $v1
/* 63F30E0 8007EBB0 C3170200 */  sra        $v0, $v0, 31
/* 63F30E4 8007EBB4 10480000 */  mfhi       $t1
/* 63F30E8 8007EBB8 83180900 */  sra        $v1, $t1, 2
/* 63F30EC 8007EBBC 23186200 */  subu       $v1, $v1, $v0
/* 63F30F0 8007EBC0 01006324 */  addiu      $v1, $v1, 0x1
/* 63F30F4 8007EBC4 80100300 */  sll        $v0, $v1, 2
/* 63F30F8 8007EBC8 21104300 */  addu       $v0, $v0, $v1
/* 63F30FC 8007EBCC 40100200 */  sll        $v0, $v0, 1
/* 63F3100 8007EBD0 0780013C */  lui        $at, %hi(D_8007015A)
/* 63F3104 8007EBD4 5A0122A4 */  sh         $v0, %lo(D_8007015A)($at)
/* 63F3108 8007EBD8 04000224 */  addiu      $v0, $zero, 0x4
/* 63F310C 8007EBDC 480042A2 */  sb         $v0, 0x48($s2)
.Llevel_27_8007EBE0:
/* 63F3110 8007EBE0 0780103C */  lui        $s0, %hi(D_8006E17C)
/* 63F3114 8007EBE4 7CE11026 */  addiu      $s0, $s0, %lo(D_8006E17C)
/* 63F3118 8007EBE8 21200002 */  addu       $a0, $s0, $zero
/* 63F311C 8007EBEC 5E3C010C */  jal        func_8004F178
/* 63F3120 8007EBF0 21282002 */   addu      $a1, $s1, $zero
/* 63F3124 8007EBF4 0800628E */  lw         $v0, 0x8($s3)
/* 63F3128 8007EBF8 ECFF0426 */  addiu      $a0, $s0, -0x14
/* 63F312C 8007EBFC 0C00458C */  lw         $a1, 0xC($v0)
/* 63F3130 8007EC00 BC4D000C */  jal        func_800136F0
/* 63F3134 8007EC04 21302002 */   addu      $a2, $s1, $zero
/* 63F3138 8007EC08 11000224 */  addiu      $v0, $zero, 0x11
/* 63F313C 8007EC0C 0780013C */  lui        $at, %hi(D_8006E174)
/* 63F3140 8007EC10 74E120AC */  sw         $zero, %lo(D_8006E174)($at)
/* 63F3144 8007EC14 0780013C */  lui        $at, %hi(D_8006E178)
/* 63F3148 8007EC18 78E120AC */  sw         $zero, %lo(D_8006E178)($at)
/* 63F314C 8007EC1C 0780013C */  lui        $at, %hi(D_8006E160)
/* 63F3150 8007EC20 60E122AC */  sw         $v0, %lo(D_8006E160)($at)
/* 63F3154 8007EC24 59FC0108 */  j          .Llevel_27_8007F164
/* 63F3158 8007EC28 00000000 */   nop
.L8007EC2C_:
/* 63F315C 8007EC2C 0780023C */  lui        $v0, %hi(D_8007015A)
/* 63F3160 8007EC30 5A014284 */  lh         $v0, %lo(D_8007015A)($v0)
/* 63F3164 8007EC34 0780013C */  lui        $at, %hi(D_8006E160)
/* 63F3168 8007EC38 60E120AC */  sw         $zero, %lo(D_8006E160)($at)
/* 63F316C 8007EC3C 05004010 */  beqz       $v0, .Llevel_27_8007EC54
/* 63F3170 8007EC40 78000224 */   addiu     $v0, $zero, 0x78
/* 63F3174 8007EC44 0C0062AE */  sw         $v0, 0xC($s3)
/* 63F3178 8007EC48 04000224 */  addiu      $v0, $zero, 0x4
/* 63F317C 8007EC4C 59FC0108 */  j          .Llevel_27_8007F164
/* 63F3180 8007EC50 480042A2 */   sb        $v0, 0x48($s2)
.Llevel_27_8007EC54:
/* 63F3184 8007EC54 05000224 */  addiu      $v0, $zero, 0x5
/* 63F3188 8007EC58 59FC0108 */  j          .Llevel_27_8007F164
/* 63F318C 8007EC5C 480042A2 */   sb        $v0, 0x48($s2)
.L8007EC60_:
/* 63F3190 8007EC60 21204002 */  addu       $a0, $s2, $zero
/* 63F3194 8007EC64 D0D3000C */  jal        func_80034F40
/* 63F3198 8007EC68 01000524 */   addiu     $a1, $zero, 0x1
/* 63F319C 8007EC6C 0010063C */  lui        $a2, (0x10008000 >> 16)
/* 63F31A0 8007EC70 0080C634 */  ori        $a2, $a2, (0x10008000 & 0xFFFF)
/* 63F31A4 8007EC74 0780033C */  lui        $v1, %hi(D_80070328 + 0x20C)
/* 63F31A8 8007EC78 34056324 */  addiu      $v1, $v1, %lo(D_80070328 + 0x20C)
/* 63F31AC 8007EC7C 20006424 */  addiu      $a0, $v1, 0x20
/* 63F31B0 8007EC80 0C005026 */  addiu      $s0, $s2, 0xC
/* 63F31B4 8007EC84 1400428E */  lw         $v0, 0x14($s2)
/* 63F31B8 8007EC88 00000000 */  nop
/* 63F31BC 8007EC8C 40004224 */  addiu      $v0, $v0, 0x40
/* 63F31C0 8007EC90 140042AE */  sw         $v0, 0x14($s2)
/* 63F31C4 8007EC94 000066AC */  sw         $a2, 0x0($v1)
/* 63F31C8 8007EC98 0780013C */  lui        $at, %hi(D_80070328 + 0x23C)
/* 63F31CC 8007EC9C 640520AC */  sw         $zero, %lo(D_80070328 + 0x23C)($at)
/* 63F31D0 8007ECA0 5E3C010C */  jal        func_8004F178
/* 63F31D4 8007ECA4 21280002 */   addu      $a1, $s0, $zero
/* 63F31D8 8007ECA8 0780113C */  lui        $s1, %hi(D_8006E17C)
/* 63F31DC 8007ECAC 7CE13126 */  addiu      $s1, $s1, %lo(D_8006E17C)
/* 63F31E0 8007ECB0 21202002 */  addu       $a0, $s1, $zero
/* 63F31E4 8007ECB4 0780023C */  lui        $v0, %hi(D_80070328 + 0x234)
/* 63F31E8 8007ECB8 5C05428C */  lw         $v0, %lo(D_80070328 + 0x234)($v0)
/* 63F31EC 8007ECBC 0780033C */  lui        $v1, %hi(D_80070328 + 0x44)
/* 63F31F0 8007ECC0 6C03638C */  lw         $v1, %lo(D_80070328 + 0x44)($v1)
/* 63F31F4 8007ECC4 0780063C */  lui        $a2, %hi(D_80070328 + 0xC)
/* 63F31F8 8007ECC8 3403C690 */  lbu        $a2, %lo(D_80070328 + 0xC)($a2)
/* 63F31FC 8007ECCC 0780073C */  lui        $a3, %hi(D_80070328 + 0xD)
/* 63F3200 8007ECD0 3503E790 */  lbu        $a3, %lo(D_80070328 + 0xD)($a3)
/* 63F3204 8007ECD4 0780083C */  lui        $t0, %hi(D_80070328 + 0xE)
/* 63F3208 8007ECD8 36030891 */  lbu        $t0, %lo(D_80070328 + 0xE)($t0)
/* 63F320C 8007ECDC 33014224 */  addiu      $v0, $v0, 0x133
/* 63F3210 8007ECE0 21104300 */  addu       $v0, $v0, $v1
/* 63F3214 8007ECE4 0780013C */  lui        $at, %hi(D_80070328 + 0x234)
/* 63F3218 8007ECE8 5C0522AC */  sw         $v0, %lo(D_80070328 + 0x234)($at)
/* 63F321C 8007ECEC 0780013C */  lui        $at, %hi(D_80070328 + 0x228)
/* 63F3220 8007ECF0 500526A0 */  sb         $a2, %lo(D_80070328 + 0x228)($at)
/* 63F3224 8007ECF4 0780013C */  lui        $at, %hi(D_80070328 + 0x229)
/* 63F3228 8007ECF8 510527A0 */  sb         $a3, %lo(D_80070328 + 0x229)($at)
/* 63F322C 8007ECFC 0780013C */  lui        $at, %hi(D_80070328 + 0x22A)
/* 63F3230 8007ED00 520528A0 */  sb         $t0, %lo(D_80070328 + 0x22A)($at)
/* 63F3234 8007ED04 5E3C010C */  jal        func_8004F178
/* 63F3238 8007ED08 21280002 */   addu      $a1, $s0, $zero
/* 63F323C 8007ED0C 0800628E */  lw         $v0, 0x8($s3)
/* 63F3240 8007ED10 ECFF2426 */  addiu      $a0, $s1, -0x14
/* 63F3244 8007ED14 0C00458C */  lw         $a1, 0xC($v0)
/* 63F3248 8007ED18 BC4D000C */  jal        func_800136F0
/* 63F324C 8007ED1C 21300002 */   addu      $a2, $s0, $zero
/* 63F3250 8007ED20 0C006426 */  addiu      $a0, $s3, 0xC
/* 63F3254 8007ED24 11000224 */  addiu      $v0, $zero, 0x11
/* 63F3258 8007ED28 0780013C */  lui        $at, %hi(D_8006E174)
/* 63F325C 8007ED2C 74E120AC */  sw         $zero, %lo(D_8006E174)($at)
/* 63F3260 8007ED30 0780013C */  lui        $at, %hi(D_8006E178)
/* 63F3264 8007ED34 78E120AC */  sw         $zero, %lo(D_8006E178)($at)
/* 63F3268 8007ED38 0780013C */  lui        $at, %hi(D_8006E160)
/* 63F326C 8007ED3C 60E122AC */  sw         $v0, %lo(D_8006E160)($at)
/* 63F3270 8007ED40 69D6000C */  jal        func_800359A4
/* 63F3274 8007ED44 04000524 */   addiu     $a1, $zero, 0x4
/* 63F3278 8007ED48 04014010 */  beqz       $v0, .Llevel_27_8007F15C
/* 63F327C 8007ED4C 21204002 */   addu      $a0, $s2, $zero
/* 63F3280 8007ED50 0780023C */  lui        $v0, %hi(D_8006C598)
/* 63F3284 8007ED54 98C5428C */  lw         $v0, %lo(D_8006C598)($v0)
/* 63F3288 8007ED58 00000000 */  nop
/* 63F328C 8007ED5C 10004224 */  addiu      $v0, $v0, 0x10
/* 63F3290 8007ED60 0780013C */  lui        $at, %hi(D_8006C598)
/* 63F3294 8007ED64 98C522AC */  sw         $v0, %lo(D_8006C598)($at)
/* 63F3298 8007ED68 FF004228 */  slti       $v0, $v0, 0xFF
/* 63F329C 8007ED6C FB004014 */  bnez       $v0, .Llevel_27_8007F15C
/* 63F32A0 8007ED70 FF000224 */   addiu     $v0, $zero, 0xFF
/* 63F32A4 8007ED74 0780043C */  lui        $a0, %hi(D_8007015A)
/* 63F32A8 8007ED78 5A018424 */  addiu      $a0, $a0, %lo(D_8007015A)
/* 63F32AC 8007ED7C 00008384 */  lh         $v1, 0x0($a0)
/* 63F32B0 8007ED80 0780013C */  lui        $at, %hi(D_8006C598)
/* 63F32B4 8007ED84 98C522AC */  sw         $v0, %lo(D_8006C598)($at)
/* 63F32B8 8007ED88 1E000224 */  addiu      $v0, $zero, 0x1E
/* 63F32BC 8007ED8C 0A006214 */  bne        $v1, $v0, .Llevel_27_8007EDB8
/* 63F32C0 8007ED90 00000000 */   nop
/* 63F32C4 8007ED94 0680023C */  lui        $v0, %hi(D_80066FCC + 0x1B)
/* 63F32C8 8007ED98 E76F4290 */  lbu        $v0, %lo(D_80066FCC + 0x1B)($v0)
/* 63F32CC 8007ED9C 0780013C */  lui        $at, %hi(D_80070300)
/* 63F32D0 8007EDA0 21082200 */  addu       $at, $at, $v0
/* 63F32D4 8007EDA4 00032290 */  lbu        $v0, %lo(D_80070300)($at)
/* 63F32D8 8007EDA8 00000000 */  nop
/* 63F32DC 8007EDAC 02004014 */  bnez       $v0, .Llevel_27_8007EDB8
/* 63F32E0 8007EDB0 1B000224 */   addiu     $v0, $zero, 0x1B
/* 63F32E4 8007EDB4 000082A4 */  sh         $v0, 0x0($a0)
.Llevel_27_8007EDB8:
/* 63F32E8 8007EDB8 0780043C */  lui        $a0, %hi(D_8007015A)
/* 63F32EC 8007EDBC 5A018484 */  lh         $a0, %lo(D_8007015A)($a0)
/* 63F32F0 8007EDC0 1B000224 */  addiu      $v0, $zero, 0x1B
/* 63F32F4 8007EDC4 06008214 */  bne        $a0, $v0, .Llevel_27_8007EDE0
/* 63F32F8 8007EDC8 00000000 */   nop
/* 63F32FC 8007EDCC 0780023C */  lui        $v0, %hi(D_800715B4)
/* 63F3300 8007EDD0 B4154290 */  lbu        $v0, %lo(D_800715B4)($v0)
/* 63F3304 8007EDD4 00000000 */  nop
/* 63F3308 8007EDD8 05004010 */  beqz       $v0, .Llevel_27_8007EDF0
/* 63F330C 8007EDDC 01000224 */   addiu     $v0, $zero, 0x1
.Llevel_27_8007EDE0:
/* 63F3310 8007EDE0 E553010C */  jal        func_80054F94
/* 63F3314 8007EDE4 21284002 */   addu      $a1, $s2, $zero
/* 63F3318 8007EDE8 57FC0108 */  j          .Llevel_27_8007F15C
/* 63F331C 8007EDEC 21204002 */   addu      $a0, $s2, $zero
.Llevel_27_8007EDF0:
/* 63F3320 8007EDF0 0780013C */  lui        $at, %hi(D_800715B5)
/* 63F3324 8007EDF4 B51522A0 */  sb         $v0, %lo(D_800715B5)($at)
/* 63F3328 8007EDF8 06000424 */  addiu      $a0, $zero, 0x6
/* 63F332C 8007EDFC 2F61010C */  jal        func_800584BC
/* 63F3330 8007EE00 41000524 */   addiu     $a1, $zero, 0x41
/* 63F3334 8007EE04 57FC0108 */  j          .Llevel_27_8007F15C
/* 63F3338 8007EE08 21204002 */   addu      $a0, $s2, $zero
.L8007EE0C_:
/* 63F333C 8007EE0C 46004292 */  lbu        $v0, 0x46($s2)
/* 63F3340 8007EE10 2000B027 */  addiu      $s0, $sp, 0x20
/* 63F3344 8007EE14 40100200 */  sll        $v0, $v0, 1
/* 63F3348 8007EE18 0680013C */  lui        $at, %hi(D_80065920)
/* 63F334C 8007EE1C 21082200 */  addu       $at, $at, $v0
/* 63F3350 8007EE20 20592284 */  lh         $v0, %lo(D_80065920)($at)
/* 63F3354 8007EE24 21200002 */  addu       $a0, $s0, $zero
/* 63F3358 8007EE28 2000A2AF */  sw         $v0, 0x20($sp)
/* 63F335C 8007EE2C 46004292 */  lbu        $v0, 0x46($s2)
/* 63F3360 8007EE30 21280002 */  addu       $a1, $s0, $zero
/* 63F3364 8007EE34 40100200 */  sll        $v0, $v0, 1
/* 63F3368 8007EE38 0680013C */  lui        $at, %hi(D_800658A0)
/* 63F336C 8007EE3C 21082200 */  addu       $at, $at, $v0
/* 63F3370 8007EE40 A0582284 */  lh         $v0, %lo(D_800658A0)($at)
/* 63F3374 8007EE44 0C004626 */  addiu      $a2, $s2, 0xC
/* 63F3378 8007EE48 2800A0AF */  sw         $zero, 0x28($sp)
/* 63F337C 8007EE4C 653C010C */  jal        func_8004F194
/* 63F3380 8007EE50 2400A2AF */   sw        $v0, 0x24($sp)
/* 63F3384 8007EE54 0780023C */  lui        $v0, %hi(unk_ovlheader_80074334)
/* 63F3388 8007EE58 3443428C */  lw         $v0, %lo(unk_ovlheader_80074334)($v0)
/* 63F338C 8007EE5C 00000000 */  nop
/* 63F3390 8007EE60 09F84000 */  jalr       $v0
/* 63F3394 8007EE64 21200002 */   addu      $a0, $s0, $zero
/* 63F3398 8007EE68 BE004010 */  beqz       $v0, .Llevel_27_8007F164
/* 63F339C 8007EE6C 21200002 */   addu      $a0, $s0, $zero
/* 63F33A0 8007EE70 0780013C */  lui        $at, %hi(D_80070328 + 0x214)
/* 63F33A4 8007EE74 3C0520AC */  sw         $zero, %lo(D_80070328 + 0x214)($at)
/* 63F33A8 8007EE78 46004592 */  lbu        $a1, 0x46($s2)
/* 63F33AC 8007EE7C 0780023C */  lui        $v0, %hi(unk_ovlheader_80074330)
/* 63F33B0 8007EE80 3043428C */  lw         $v0, %lo(unk_ovlheader_80074330)($v0)
/* 63F33B4 8007EE84 00000000 */  nop
/* 63F33B8 8007EE88 09F84000 */  jalr       $v0
/* 63F33BC 8007EE8C 21300000 */   addu      $a2, $zero, $zero
/* 63F33C0 8007EE90 06000224 */  addiu      $v0, $zero, 0x6
/* 63F33C4 8007EE94 59FC0108 */  j          .Llevel_27_8007F164
/* 63F33C8 8007EE98 480042A2 */   sb        $v0, 0x48($s2)
.L8007EE9C_:
/* 63F33CC 8007EE9C 46004292 */  lbu        $v0, 0x46($s2)
/* 63F33D0 8007EEA0 3000B027 */  addiu      $s0, $sp, 0x30
/* 63F33D4 8007EEA4 40100200 */  sll        $v0, $v0, 1
/* 63F33D8 8007EEA8 0680013C */  lui        $at, %hi(D_80065920)
/* 63F33DC 8007EEAC 21082200 */  addu       $at, $at, $v0
/* 63F33E0 8007EEB0 20592284 */  lh         $v0, %lo(D_80065920)($at)
/* 63F33E4 8007EEB4 21200002 */  addu       $a0, $s0, $zero
/* 63F33E8 8007EEB8 3000A2AF */  sw         $v0, 0x30($sp)
/* 63F33EC 8007EEBC 46004292 */  lbu        $v0, 0x46($s2)
/* 63F33F0 8007EEC0 21280002 */  addu       $a1, $s0, $zero
/* 63F33F4 8007EEC4 40100200 */  sll        $v0, $v0, 1
/* 63F33F8 8007EEC8 0680013C */  lui        $at, %hi(D_800658A0)
/* 63F33FC 8007EECC 21082200 */  addu       $at, $at, $v0
/* 63F3400 8007EED0 A0582284 */  lh         $v0, %lo(D_800658A0)($at)
/* 63F3404 8007EED4 0C004626 */  addiu      $a2, $s2, 0xC
/* 63F3408 8007EED8 3800A0AF */  sw         $zero, 0x38($sp)
/* 63F340C 8007EEDC 653C010C */  jal        func_8004F194
/* 63F3410 8007EEE0 3400A2AF */   sw        $v0, 0x34($sp)
/* 63F3414 8007EEE4 21200002 */  addu       $a0, $s0, $zero
/* 63F3418 8007EEE8 46004592 */  lbu        $a1, 0x46($s2)
/* 63F341C 8007EEEC 0780023C */  lui        $v0, %hi(unk_ovlheader_80074330)
/* 63F3420 8007EEF0 3043428C */  lw         $v0, %lo(unk_ovlheader_80074330)($v0)
/* 63F3424 8007EEF4 00000000 */  nop
/* 63F3428 8007EEF8 09F84000 */  jalr       $v0
/* 63F342C 8007EEFC 21300000 */   addu      $a2, $zero, $zero
/* 63F3430 8007EF00 98004010 */  beqz       $v0, .Llevel_27_8007F164
/* 63F3434 8007EF04 4000B027 */   addiu     $s0, $sp, 0x40
/* 63F3438 8007EF08 0780053C */  lui        $a1, %hi(D_80070328)
/* 63F343C 8007EF0C 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 63F3440 8007EF10 5E3C010C */  jal        func_8004F178
/* 63F3444 8007EF14 21200002 */   addu      $a0, $s0, $zero
/* 63F3448 8007EF18 0780043C */  lui        $a0, %hi(D_8006D088)
/* 63F344C 8007EF1C 88D08424 */  addiu      $a0, $a0, %lo(D_8006D088)
/* 63F3450 8007EF20 21280002 */  addu       $a1, $s0, $zero
/* 63F3454 8007EF24 4800A28F */  lw         $v0, 0x48($sp)
/* 63F3458 8007EF28 0780033C */  lui        $v1, %hi(D_80070328 + 0x44)
/* 63F345C 8007EF2C 6C03638C */  lw         $v1, %lo(D_80070328 + 0x44)($v1)
/* 63F3460 8007EF30 0780063C */  lui        $a2, %hi(D_80070328 + 0xE)
/* 63F3464 8007EF34 3603C690 */  lbu        $a2, %lo(D_80070328 + 0xE)($a2)
/* 63F3468 8007EF38 23104300 */  subu       $v0, $v0, $v1
/* 63F346C 8007EF3C 8DED000C */  jal        func_8003B634
/* 63F3470 8007EF40 4800A2AF */   sw        $v0, 0x48($sp)
/* 63F3474 8007EF44 78000224 */  addiu      $v0, $zero, 0x78
/* 63F3478 8007EF48 0C0062AE */  sw         $v0, 0xC($s3)
/* 63F347C 8007EF4C 08000224 */  addiu      $v0, $zero, 0x8
/* 63F3480 8007EF50 490040A2 */  sb         $zero, 0x49($s2)
/* 63F3484 8007EF54 59FC0108 */  j          .Llevel_27_8007F164
/* 63F3488 8007EF58 480042A2 */   sb        $v0, 0x48($s2)
.L8007EF5C_:
/* 63F348C 8007EF5C 21204002 */  addu       $a0, $s2, $zero
/* 63F3490 8007EF60 D0D3000C */  jal        func_80034F40
/* 63F3494 8007EF64 01000524 */   addiu     $a1, $zero, 0x1
/* 63F3498 8007EF68 0110033C */  lui        $v1, (0x10018000 >> 16)
/* 63F349C 8007EF6C 00806334 */  ori        $v1, $v1, (0x10018000 & 0xFFFF)
/* 63F34A0 8007EF70 0780103C */  lui        $s0, %hi(D_80070328 + 0x20C)
/* 63F34A4 8007EF74 34051026 */  addiu      $s0, $s0, %lo(D_80070328 + 0x20C)
/* 63F34A8 8007EF78 20000426 */  addiu      $a0, $s0, 0x20
/* 63F34AC 8007EF7C 0C005126 */  addiu      $s1, $s2, 0xC
/* 63F34B0 8007EF80 1400428E */  lw         $v0, 0x14($s2)
/* 63F34B4 8007EF84 00000000 */  nop
/* 63F34B8 8007EF88 C0FF4224 */  addiu      $v0, $v0, -0x40
/* 63F34BC 8007EF8C 140042AE */  sw         $v0, 0x14($s2)
/* 63F34C0 8007EF90 000003AE */  sw         $v1, 0x0($s0)
/* 63F34C4 8007EF94 0780013C */  lui        $at, %hi(D_80070328 + 0x23C)
/* 63F34C8 8007EF98 640520AC */  sw         $zero, %lo(D_80070328 + 0x23C)($at)
/* 63F34CC 8007EF9C 5E3C010C */  jal        func_8004F178
/* 63F34D0 8007EFA0 21282002 */   addu      $a1, $s1, $zero
/* 63F34D4 8007EFA4 0780023C */  lui        $v0, %hi(D_80070328 + 0x234)
/* 63F34D8 8007EFA8 5C05428C */  lw         $v0, %lo(D_80070328 + 0x234)($v0)
/* 63F34DC 8007EFAC 0780033C */  lui        $v1, %hi(D_80070328 + 0x44)
/* 63F34E0 8007EFB0 6C03638C */  lw         $v1, %lo(D_80070328 + 0x44)($v1)
/* 63F34E4 8007EFB4 33014224 */  addiu      $v0, $v0, 0x133
/* 63F34E8 8007EFB8 21104300 */  addu       $v0, $v0, $v1
/* 63F34EC 8007EFBC 0780013C */  lui        $at, %hi(D_80070328 + 0x234)
/* 63F34F0 8007EFC0 5C0522AC */  sw         $v0, %lo(D_80070328 + 0x234)($at)
/* 63F34F4 8007EFC4 44004292 */  lbu        $v0, 0x44($s2)
/* 63F34F8 8007EFC8 0780013C */  lui        $at, %hi(D_80070328 + 0x228)
/* 63F34FC 8007EFCC 500522A0 */  sb         $v0, %lo(D_80070328 + 0x228)($at)
/* 63F3500 8007EFD0 45004292 */  lbu        $v0, 0x45($s2)
/* 63F3504 8007EFD4 0780013C */  lui        $at, %hi(D_80070328 + 0x229)
/* 63F3508 8007EFD8 510522A0 */  sb         $v0, %lo(D_80070328 + 0x229)($at)
/* 63F350C 8007EFDC 46004292 */  lbu        $v0, 0x46($s2)
/* 63F3510 8007EFE0 0780013C */  lui        $at, %hi(D_80070328 + 0x22A)
/* 63F3514 8007EFE4 520522A0 */  sb         $v0, %lo(D_80070328 + 0x22A)($at)
/* 63F3518 8007EFE8 0800628E */  lw         $v0, 0x8($s3)
/* 63F351C 8007EFEC 00000000 */  nop
/* 63F3520 8007EFF0 0C00448C */  lw         $a0, 0xC($v0)
/* 63F3524 8007EFF4 B94E000C */  jal        func_80013AE4
/* 63F3528 8007EFF8 F4FD0526 */   addiu     $a1, $s0, -0x20C
/* 63F352C 8007EFFC 5000B027 */  addiu      $s0, $sp, 0x50
/* 63F3530 8007F000 21200002 */  addu       $a0, $s0, $zero
/* 63F3534 8007F004 5E3C010C */  jal        func_8004F178
/* 63F3538 8007F008 21282002 */   addu      $a1, $s1, $zero
/* 63F353C 8007F00C 1400428E */  lw         $v0, 0x14($s2)
/* 63F3540 8007F010 21200002 */  addu       $a0, $s0, $zero
/* 63F3544 8007F014 00044224 */  addiu      $v0, $v0, 0x400
/* 63F3548 8007F018 140042AE */  sw         $v0, 0x14($s2)
/* 63F354C 8007F01C 5800A28F */  lw         $v0, 0x58($sp)
/* 63F3550 8007F020 00020524 */  addiu      $a1, $zero, 0x200
/* 63F3554 8007F024 00024224 */  addiu      $v0, $v0, 0x200
/* 63F3558 8007F028 D668000C */  jal        func_8001A358
/* 63F355C 8007F02C 5800A2AF */   sw        $v0, 0x58($sp)
/* 63F3560 8007F030 45004010 */  beqz       $v0, .Llevel_27_8007F148
/* 63F3564 8007F034 5800A2AF */   sw        $v0, 0x58($sp)
/* 63F3568 8007F038 21200000 */  addu       $a0, $zero, $zero
/* 63F356C 8007F03C DF4E000C */  jal        func_80013B7C
/* 63F3570 8007F040 140042AE */   sw        $v0, 0x14($s2)
/* 63F3574 8007F044 05000224 */  addiu      $v0, $zero, 0x5
/* 63F3578 8007F048 56FC0108 */  j          .Llevel_27_8007F158
/* 63F357C 8007F04C 480042A2 */   sb        $v0, 0x48($s2)
.L8007F050_:
/* 63F3580 8007F050 21204002 */  addu       $a0, $s2, $zero
/* 63F3584 8007F054 D0D3000C */  jal        func_80034F40
/* 63F3588 8007F058 01000524 */   addiu     $a1, $zero, 0x1
/* 63F358C 8007F05C 0C00628E */  lw         $v0, 0xC($s3)
/* 63F3590 8007F060 00000000 */  nop
/* 63F3594 8007F064 12004010 */  beqz       $v0, .Llevel_27_8007F0B0
/* 63F3598 8007F068 0C006426 */   addiu     $a0, $s3, 0xC
/* 63F359C 8007F06C 1400428E */  lw         $v0, 0x14($s2)
/* 63F35A0 8007F070 04000524 */  addiu      $a1, $zero, 0x4
/* 63F35A4 8007F074 40004224 */  addiu      $v0, $v0, 0x40
/* 63F35A8 8007F078 69D6000C */  jal        func_800359A4
/* 63F35AC 8007F07C 140042AE */   sw        $v0, 0x14($s2)
/* 63F35B0 8007F080 49004292 */  lbu        $v0, 0x49($s2)
/* 63F35B4 8007F084 00000000 */  nop
/* 63F35B8 8007F088 09004014 */  bnez       $v0, .Llevel_27_8007F0B0
/* 63F35BC 8007F08C 0010023C */   lui       $v0, (0x10000002 >> 16)
/* 63F35C0 8007F090 0780033C */  lui        $v1, %hi(D_80070328 + 0x50)
/* 63F35C4 8007F094 7803638C */  lw         $v1, %lo(D_80070328 + 0x50)($v1)
/* 63F35C8 8007F098 02004234 */  ori        $v0, $v0, (0x10000002 & 0xFFFF)
/* 63F35CC 8007F09C 0780013C */  lui        $at, %hi(D_80070328 + 0x20C)
/* 63F35D0 8007F0A0 340522AC */  sw         $v0, %lo(D_80070328 + 0x20C)($at)
/* 63F35D4 8007F0A4 02006014 */  bnez       $v1, .Llevel_27_8007F0B0
/* 63F35D8 8007F0A8 01000224 */   addiu     $v0, $zero, 0x1
/* 63F35DC 8007F0AC 490042A2 */  sb         $v0, 0x49($s2)
.Llevel_27_8007F0B0:
/* 63F35E0 8007F0B0 0780023C */  lui        $v0, %hi(D_8006C7B4)
/* 63F35E4 8007F0B4 B4C74290 */  lbu        $v0, %lo(D_8006C7B4)($v0)
/* 63F35E8 8007F0B8 00000000 */  nop
/* 63F35EC 8007F0BC 01004230 */  andi       $v0, $v0, 0x1
/* 63F35F0 8007F0C0 28004010 */  beqz       $v0, .Llevel_27_8007F164
/* 63F35F4 8007F0C4 09000224 */   addiu     $v0, $zero, 0x9
/* 63F35F8 8007F0C8 59FC0108 */  j          .Llevel_27_8007F164
/* 63F35FC 8007F0CC 480042A2 */   sb        $v0, 0x48($s2)
.L8007F0D0_:
/* 63F3600 8007F0D0 0010023C */  lui        $v0, (0x10000002 >> 16)
/* 63F3604 8007F0D4 02004234 */  ori        $v0, $v0, (0x10000002 & 0xFFFF)
/* 63F3608 8007F0D8 21204002 */  addu       $a0, $s2, $zero
/* 63F360C 8007F0DC 0780013C */  lui        $at, %hi(D_80070328 + 0x20C)
/* 63F3610 8007F0E0 340522AC */  sw         $v0, %lo(D_80070328 + 0x20C)($at)
/* 63F3614 8007F0E4 D0D3000C */  jal        func_80034F40
/* 63F3618 8007F0E8 01000524 */   addiu     $a1, $zero, 0x1
/* 63F361C 8007F0EC 6000B027 */  addiu      $s0, $sp, 0x60
/* 63F3620 8007F0F0 21200002 */  addu       $a0, $s0, $zero
/* 63F3624 8007F0F4 1400428E */  lw         $v0, 0x14($s2)
/* 63F3628 8007F0F8 0C004526 */  addiu      $a1, $s2, 0xC
/* 63F362C 8007F0FC C0FF4224 */  addiu      $v0, $v0, -0x40
/* 63F3630 8007F100 5E3C010C */  jal        func_8004F178
/* 63F3634 8007F104 140042AE */   sw        $v0, 0x14($s2)
/* 63F3638 8007F108 1400428E */  lw         $v0, 0x14($s2)
/* 63F363C 8007F10C 21200002 */  addu       $a0, $s0, $zero
/* 63F3640 8007F110 00044224 */  addiu      $v0, $v0, 0x400
/* 63F3644 8007F114 140042AE */  sw         $v0, 0x14($s2)
/* 63F3648 8007F118 6800A28F */  lw         $v0, 0x68($sp)
/* 63F364C 8007F11C 00020524 */  addiu      $a1, $zero, 0x200
/* 63F3650 8007F120 00024224 */  addiu      $v0, $v0, 0x200
/* 63F3654 8007F124 D668000C */  jal        func_8001A358
/* 63F3658 8007F128 6800A2AF */   sw        $v0, 0x68($sp)
/* 63F365C 8007F12C 06004010 */  beqz       $v0, .Llevel_27_8007F148
/* 63F3660 8007F130 6800A2AF */   sw        $v0, 0x68($sp)
/* 63F3664 8007F134 140042AE */  sw         $v0, 0x14($s2)
/* 63F3668 8007F138 01000224 */  addiu      $v0, $zero, 0x1
/* 63F366C 8007F13C 490040A2 */  sb         $zero, 0x49($s2)
/* 63F3670 8007F140 56FC0108 */  j          .Llevel_27_8007F158
/* 63F3674 8007F144 480042A2 */   sb        $v0, 0x48($s2)
.Llevel_27_8007F148:
/* 63F3678 8007F148 1400428E */  lw         $v0, 0x14($s2)
/* 63F367C 8007F14C 00000000 */  nop
/* 63F3680 8007F150 00FC4224 */  addiu      $v0, $v0, -0x400
/* 63F3684 8007F154 140042AE */  sw         $v0, 0x14($s2)
.Llevel_27_8007F158:
/* 63F3688 8007F158 21204002 */  addu       $a0, $s2, $zero
.Llevel_27_8007F15C:
/* 63F368C 8007F15C 4957010C */  jal        func_80055D24
/* 63F3690 8007F160 02000524 */   addiu     $a1, $zero, 0x2
.Llevel_27_8007F164:
/* 63F3694 8007F164 0780023C */  lui        $v0, %hi(D_8006E344)
/* 63F3698 8007F168 44E3428C */  lw         $v0, %lo(D_8006E344)($v0)
/* 63F369C 8007F16C 00000000 */  nop
/* 63F36A0 8007F170 0F004014 */  bnez       $v0, .Llevel_27_8007F1B0
/* 63F36A4 8007F174 01000224 */   addiu     $v0, $zero, 0x1
/* 63F36A8 8007F178 3D004392 */  lbu        $v1, 0x3D($s2)
/* 63F36AC 8007F17C 00000000 */  nop
/* 63F36B0 8007F180 0B006214 */  bne        $v1, $v0, .Llevel_27_8007F1B0
/* 63F36B4 8007F184 00000000 */   nop
/* 63F36B8 8007F188 1000658E */  lw         $a1, 0x10($s3)
/* 63F36BC 8007F18C F0EF000C */  jal        func_8003BFC0
/* 63F36C0 8007F190 21204002 */   addu      $a0, $s2, $zero
/* 63F36C4 8007F194 10004014 */  bnez       $v0, .Llevel_27_8007F1D8
/* 63F36C8 8007F198 21204002 */   addu      $a0, $s2, $zero
/* 63F36CC 8007F19C 21280000 */  addu       $a1, $zero, $zero
/* 63F36D0 8007F1A0 AFEE000C */  jal        func_8003BABC
/* 63F36D4 8007F1A4 04000624 */   addiu     $a2, $zero, 0x4
/* 63F36D8 8007F1A8 76FC0108 */  j          .Llevel_27_8007F1D8
/* 63F36DC 8007F1AC 100062AE */   sw        $v0, 0x10($s3)
.Llevel_27_8007F1B0:
/* 63F36E0 8007F1B0 1000658E */  lw         $a1, 0x10($s3)
/* 63F36E4 8007F1B4 F0EF000C */  jal        func_8003BFC0
/* 63F36E8 8007F1B8 21204002 */   addu      $a0, $s2, $zero
/* 63F36EC 8007F1BC 05004010 */  beqz       $v0, .Llevel_27_8007F1D4
/* 63F36F0 8007F1C0 FFFF0224 */   addiu     $v0, $zero, -0x1
/* 63F36F4 8007F1C4 1000648E */  lw         $a0, 0x10($s3)
/* 63F36F8 8007F1C8 9CEF000C */  jal        func_8003BE70
/* 63F36FC 8007F1CC 00000000 */   nop
/* 63F3700 8007F1D0 FFFF0224 */  addiu      $v0, $zero, -0x1
.Llevel_27_8007F1D4:
/* 63F3704 8007F1D4 100062AE */  sw         $v0, 0x10($s3)
.Llevel_27_8007F1D8:
/* 63F3708 8007F1D8 9000BF8F */  lw         $ra, 0x90($sp)
/* 63F370C 8007F1DC 8C00B78F */  lw         $s7, 0x8C($sp)
/* 63F3710 8007F1E0 8800B68F */  lw         $s6, 0x88($sp)
/* 63F3714 8007F1E4 8400B58F */  lw         $s5, 0x84($sp)
/* 63F3718 8007F1E8 8000B48F */  lw         $s4, 0x80($sp)
/* 63F371C 8007F1EC 7C00B38F */  lw         $s3, 0x7C($sp)
/* 63F3720 8007F1F0 7800B28F */  lw         $s2, 0x78($sp)
/* 63F3724 8007F1F4 7400B18F */  lw         $s1, 0x74($sp)
/* 63F3728 8007F1F8 7000B08F */  lw         $s0, 0x70($sp)
/* 63F372C 8007F1FC 9800BD27 */  addiu      $sp, $sp, 0x98
/* 63F3730 8007F200 0800E003 */  jr         $ra
/* 63F3734 8007F204 00000000 */   nop
.size func_level_27_8007E76C, . - func_level_27_8007E76C
