.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_22_80075630
/* 5765360 80075630 E0AB0980 */ .word .L8009ABE0_
/* 5765364 80075634 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 5765368 80075638 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 576536C 8007563C C4AC0980 */ .word .Llevel_22_8009ACC4
/* 5765370 80075640 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 5765374 80075644 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 5765378 80075648 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 576537C 8007564C C4AC0980 */ .word .Llevel_22_8009ACC4
/* 5765380 80075650 E0AB0980 */ .word .L8009ABE0_
/* 5765384 80075654 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 5765388 80075658 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 576538C 8007565C C4AC0980 */ .word .Llevel_22_8009ACC4
/* 5765390 80075660 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 5765394 80075664 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 5765398 80075668 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 576539C 8007566C C4AC0980 */ .word .Llevel_22_8009ACC4
/* 57653A0 80075670 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 57653A4 80075674 20AC0980 */ .word .L8009AC20_
/* 57653A8 80075678 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 57653AC 8007567C E0AB0980 */ .word .L8009ABE0_
/* 57653B0 80075680 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 57653B4 80075684 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 57653B8 80075688 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 57653BC 8007568C C4AC0980 */ .word .Llevel_22_8009ACC4
/* 57653C0 80075690 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 57653C4 80075694 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 57653C8 80075698 60AC0980 */ .word .L8009AC60_
/* 57653CC 8007569C C4AC0980 */ .word .Llevel_22_8009ACC4
/* 57653D0 800756A0 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 57653D4 800756A4 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 57653D8 800756A8 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 57653DC 800756AC C4AC0980 */ .word .Llevel_22_8009ACC4
/* 57653E0 800756B0 E0AB0980 */ .word .L8009ABE0_
/* 57653E4 800756B4 C4AC0980 */ .word .Llevel_22_8009ACC4
/* 57653E8 800756B8 60AC0980 */ .word .L8009AC60_
/* 57653EC 800756BC 00000000 */ .word 0x00000000
.size jtbl_level_22_80075630, . - jtbl_level_22_80075630


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_22_8009ABA8
/* 578A8D8 8009ABA8 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 578A8DC 8009ABAC FCFF8424 */  addiu      $a0, $a0, -0x4
/* 578A8E0 8009ABB0 2300822C */  sltiu      $v0, $a0, 0x23
/* 578A8E4 8009ABB4 1800BFAF */  sw         $ra, 0x18($sp)
/* 578A8E8 8009ABB8 1400B1AF */  sw         $s1, 0x14($sp)
/* 578A8EC 8009ABBC 41004010 */  beqz       $v0, .Llevel_22_8009ACC4
/* 578A8F0 8009ABC0 1000B0AF */   sw        $s0, 0x10($sp)
/* 578A8F4 8009ABC4 80100400 */  sll        $v0, $a0, 2
/* 578A8F8 8009ABC8 0780013C */  lui        $at, %hi(jtbl_level_22_80075630)
/* 578A8FC 8009ABCC 21082200 */  addu       $at, $at, $v0
/* 578A900 8009ABD0 3056228C */  lw         $v0, %lo(jtbl_level_22_80075630)($at)
/* 578A904 8009ABD4 00000000 */  nop
/* 578A908 8009ABD8 08004000 */  jr         $v0
/* 578A90C 8009ABDC 00000000 */   nop
.L8009ABE0_:
/* 578A910 8009ABE0 0780103C */  lui        $s0, %hi(D_8006E048)
/* 578A914 8009ABE4 48E01026 */  addiu      $s0, $s0, %lo(D_8006E048)
/* 578A918 8009ABE8 01000224 */  addiu      $v0, $zero, 0x1
/* 578A91C 8009ABEC 000000AE */  sw         $zero, 0x0($s0)
/* 578A920 8009ABF0 0780013C */  lui        $at, %hi(D_8006E138)
/* 578A924 8009ABF4 38E120A0 */  sb         $zero, %lo(D_8006E138)($at)
/* 578A928 8009ABF8 0780013C */  lui        $at, %hi(D_8006E139)
/* 578A92C 8009ABFC 39E120A0 */  sb         $zero, %lo(D_8006E139)($at)
/* 578A930 8009AC00 0780013C */  lui        $at, %hi(D_8006E13A)
/* 578A934 8009AC04 3AE122A0 */  sb         $v0, %lo(D_8006E13A)($at)
/* 578A938 8009AC08 0780013C */  lui        $at, %hi(D_8006E13D)
/* 578A93C 8009AC0C 3DE120A0 */  sb         $zero, %lo(D_8006E13D)($at)
/* 578A940 8009AC10 0780013C */  lui        $at, %hi(D_8006E054)
/* 578A944 8009AC14 54E020A0 */  sb         $zero, %lo(D_8006E054)($at)
/* 578A948 8009AC18 246B0208 */  j          .Llevel_22_8009AC90
/* 578A94C 8009AC1C 00000000 */   nop
.L8009AC20_:
/* 578A950 8009AC20 0780103C */  lui        $s0, %hi(D_8006E048)
/* 578A954 8009AC24 48E01026 */  addiu      $s0, $s0, %lo(D_8006E048)
/* 578A958 8009AC28 01000224 */  addiu      $v0, $zero, 0x1
/* 578A95C 8009AC2C 000000AE */  sw         $zero, 0x0($s0)
/* 578A960 8009AC30 0780013C */  lui        $at, %hi(D_8006E138)
/* 578A964 8009AC34 38E120A0 */  sb         $zero, %lo(D_8006E138)($at)
/* 578A968 8009AC38 0780013C */  lui        $at, %hi(D_8006E139)
/* 578A96C 8009AC3C 39E122A0 */  sb         $v0, %lo(D_8006E139)($at)
/* 578A970 8009AC40 0780013C */  lui        $at, %hi(D_8006E13A)
/* 578A974 8009AC44 3AE122A0 */  sb         $v0, %lo(D_8006E13A)($at)
/* 578A978 8009AC48 0780013C */  lui        $at, %hi(D_8006E13D)
/* 578A97C 8009AC4C 3DE120A0 */  sb         $zero, %lo(D_8006E13D)($at)
/* 578A980 8009AC50 0780013C */  lui        $at, %hi(D_8006E054)
/* 578A984 8009AC54 54E020A0 */  sb         $zero, %lo(D_8006E054)($at)
/* 578A988 8009AC58 246B0208 */  j          .Llevel_22_8009AC90
/* 578A98C 8009AC5C 00000000 */   nop
.L8009AC60_:
/* 578A990 8009AC60 0780103C */  lui        $s0, %hi(D_8006E048)
/* 578A994 8009AC64 48E01026 */  addiu      $s0, $s0, %lo(D_8006E048)
/* 578A998 8009AC68 01000224 */  addiu      $v0, $zero, 0x1
/* 578A99C 8009AC6C 000000AE */  sw         $zero, 0x0($s0)
/* 578A9A0 8009AC70 0780013C */  lui        $at, %hi(D_8006E138)
/* 578A9A4 8009AC74 38E120A0 */  sb         $zero, %lo(D_8006E138)($at)
/* 578A9A8 8009AC78 0780013C */  lui        $at, %hi(D_8006E139)
/* 578A9AC 8009AC7C 39E120A0 */  sb         $zero, %lo(D_8006E139)($at)
/* 578A9B0 8009AC80 0780013C */  lui        $at, %hi(D_8006E13A)
/* 578A9B4 8009AC84 3AE122A0 */  sb         $v0, %lo(D_8006E13A)($at)
/* 578A9B8 8009AC88 0780013C */  lui        $at, %hi(D_8006E13D)
/* 578A9BC 8009AC8C 3DE120A0 */  sb         $zero, %lo(D_8006E13D)($at)
.Llevel_22_8009AC90:
/* 578A9C0 8009AC90 B850000C */  jal        func_800142E0
/* 578A9C4 8009AC94 2C001126 */   addiu     $s1, $s0, 0x2C
/* 578A9C8 8009AC98 21202002 */  addu       $a0, $s1, $zero
/* 578A9CC 8009AC9C D8FF0526 */  addiu      $a1, $s0, -0x28
/* 578A9D0 8009ACA0 BC4D000C */  jal        func_800136F0
/* 578A9D4 8009ACA4 10000626 */   addiu     $a2, $s0, 0x10
/* 578A9D8 8009ACA8 21202002 */  addu       $a0, $s1, $zero
/* 578A9DC 8009ACAC 284E000C */  jal        func_800138A0
/* 578A9E0 8009ACB0 21282002 */   addu      $a1, $s1, $zero
/* 578A9E4 8009ACB4 54000426 */  addiu      $a0, $s0, 0x54
/* 578A9E8 8009ACB8 21282002 */  addu       $a1, $s1, $zero
/* 578A9EC 8009ACBC 694D000C */  jal        func_800135A4
/* 578A9F0 8009ACC0 21300000 */   addu      $a2, $zero, $zero
.Llevel_22_8009ACC4:
/* 578A9F4 8009ACC4 1800BF8F */  lw         $ra, 0x18($sp)
/* 578A9F8 8009ACC8 1400B18F */  lw         $s1, 0x14($sp)
/* 578A9FC 8009ACCC 1000B08F */  lw         $s0, 0x10($sp)
/* 578AA00 8009ACD0 2000BD27 */  addiu      $sp, $sp, 0x20
/* 578AA04 8009ACD4 0800E003 */  jr         $ra
/* 578AA08 8009ACD8 00000000 */   nop
.size func_level_22_8009ABA8, . - func_level_22_8009ABA8
