.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_27_80074C5C
/* 63E918C 80074C5C 688B0880 */ .word .L80088B68_
/* 63E9190 80074C60 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E9194 80074C64 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E9198 80074C68 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E919C 80074C6C F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91A0 80074C70 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91A4 80074C74 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91A8 80074C78 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91AC 80074C7C F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91B0 80074C80 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91B4 80074C84 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91B8 80074C88 208B0880 */ .word .L80088B20_
/* 63E91BC 80074C8C F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91C0 80074C90 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91C4 80074C94 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91C8 80074C98 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91CC 80074C9C F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91D0 80074CA0 F48C0880 */ .word .L80088CF4_
/* 63E91D4 80074CA4 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91D8 80074CA8 7C8D0880 */ .word .L80088D7C_
/* 63E91DC 80074CAC F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91E0 80074CB0 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91E4 80074CB4 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91E8 80074CB8 588E0880 */ .word .L80088E58_
/* 63E91EC 80074CBC F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91F0 80074CC0 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91F4 80074CC4 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91F8 80074CC8 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E91FC 80074CCC F48E0880 */ .word .Llevel_27_80088EF4
/* 63E9200 80074CD0 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E9204 80074CD4 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E9208 80074CD8 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E920C 80074CDC F48E0880 */ .word .Llevel_27_80088EF4
/* 63E9210 80074CE0 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E9214 80074CE4 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E9218 80074CE8 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E921C 80074CEC F48E0880 */ .word .Llevel_27_80088EF4
/* 63E9220 80074CF0 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E9224 80074CF4 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E9228 80074CF8 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E922C 80074CFC F48E0880 */ .word .Llevel_27_80088EF4
/* 63E9230 80074D00 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E9234 80074D04 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E9238 80074D08 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E923C 80074D0C C08E0880 */ .word .L80088EC0_
/* 63E9240 80074D10 C08E0880 */ .word .L80088EC0_
/* 63E9244 80074D14 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E9248 80074D18 F48E0880 */ .word .Llevel_27_80088EF4
/* 63E924C 80074D1C F48E0880 */ .word .Llevel_27_80088EF4
/* 63E9250 80074D20 588E0880 */ .word .L80088E58_
.size jtbl_level_27_80074C5C, . - jtbl_level_27_80074C5C


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_27_80088AE4
/* 63FD014 80088AE4 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 63FD018 80088AE8 1000B0AF */  sw         $s0, 0x10($sp)
/* 63FD01C 80088AEC 21808000 */  addu       $s0, $a0, $zero
/* 63FD020 80088AF0 F7FF0326 */  addiu      $v1, $s0, -0x9
/* 63FD024 80088AF4 3200622C */  sltiu      $v0, $v1, 0x32
/* 63FD028 80088AF8 1800BFAF */  sw         $ra, 0x18($sp)
/* 63FD02C 80088AFC FD004010 */  beqz       $v0, .Llevel_27_80088EF4
/* 63FD030 80088B00 1400B1AF */   sw        $s1, 0x14($sp)
/* 63FD034 80088B04 80100300 */  sll        $v0, $v1, 2
/* 63FD038 80088B08 0780013C */  lui        $at, %hi(jtbl_level_27_80074C5C)
/* 63FD03C 80088B0C 21082200 */  addu       $at, $at, $v0
/* 63FD040 80088B10 5C4C228C */  lw         $v0, %lo(jtbl_level_27_80074C5C)($at)
/* 63FD044 80088B14 00000000 */  nop
/* 63FD048 80088B18 08004000 */  jr         $v0
/* 63FD04C 80088B1C 00000000 */   nop
.L80088B20_:
/* 63FD050 80088B20 0780013C */  lui        $at, %hi(D_80070328 + 0x50)
/* 63FD054 80088B24 780320AC */  sw         $zero, %lo(D_80070328 + 0x50)($at)
/* 63FD058 80088B28 0780013C */  lui        $at, %hi(D_80070328 + 0x4C)
/* 63FD05C 80088B2C 740320AC */  sw         $zero, %lo(D_80070328 + 0x4C)($at)
/* 63FD060 80088B30 7C10010C */  jal        func_800441F0
/* 63FD064 80088B34 00000000 */   nop
/* 63FD068 80088B38 01000424 */  addiu      $a0, $zero, 0x1
/* 63FD06C 80088B3C 01000224 */  addiu      $v0, $zero, 0x1
/* 63FD070 80088B40 0780013C */  lui        $at, %hi(D_80070328 + 0x1B4)
/* 63FD074 80088B44 DC0422A0 */  sb         $v0, %lo(D_80070328 + 0x1B4)($at)
/* 63FD078 80088B48 DBD8000C */  jal        func_8003636C
/* 63FD07C 80088B4C 03000524 */   addiu     $a1, $zero, 0x3
/* 63FD080 80088B50 0780013C */  lui        $at, %hi(D_80070328 + 0x144)
/* 63FD084 80088B54 6C0422AC */  sw         $v0, %lo(D_80070328 + 0x144)($at)
/* 63FD088 80088B58 0780013C */  lui        $at, %hi(D_80070328 + 0x148)
/* 63FD08C 80088B5C 700420AC */  sw         $zero, %lo(D_80070328 + 0x148)($at)
/* 63FD090 80088B60 B9230208 */  j          .Llevel_27_80088EE4
/* 63FD094 80088B64 00000000 */   nop
.L80088B68_:
/* 63FD098 80088B68 0780113C */  lui        $s1, %hi(D_80070328 + 0x10C)
/* 63FD09C 80088B6C 34043126 */  addiu      $s1, $s1, %lo(D_80070328 + 0x10C)
/* 63FD0A0 80088B70 0000248E */  lw         $a0, 0x0($s1)
/* 63FD0A4 80088B74 5502010C */  jal        func_80040954
/* 63FD0A8 80088B78 00000000 */   nop
/* 63FD0AC 80088B7C 07000624 */  addiu      $a2, $zero, 0x7
/* 63FD0B0 80088B80 19004614 */  bne        $v0, $a2, .Llevel_27_80088BE8
/* 63FD0B4 80088B84 80FF2426 */   addiu     $a0, $s1, -0x80
/* 63FD0B8 80088B88 8CFF3026 */  addiu      $s0, $s1, -0x74
/* 63FD0BC 80088B8C 0780033C */  lui        $v1, %hi(D_80070328 + 0x50)
/* 63FD0C0 80088B90 7803638C */  lw         $v1, %lo(D_80070328 + 0x50)($v1)
/* 63FD0C4 80088B94 01000224 */  addiu      $v0, $zero, 0x1
/* 63FD0C8 80088B98 0780013C */  lui        $at, %hi(D_80070328 + 0x50)
/* 63FD0CC 80088B9C 780326AC */  sw         $a2, %lo(D_80070328 + 0x50)($at)
/* 63FD0D0 80088BA0 0780013C */  lui        $at, %hi(D_80070328 + 0x4C)
/* 63FD0D4 80088BA4 740322AC */  sw         $v0, %lo(D_80070328 + 0x4C)($at)
/* 63FD0D8 80088BA8 0780013C */  lui        $at, %hi(D_80070328 + 0x144)
/* 63FD0DC 80088BAC 6C0423AC */  sw         $v1, %lo(D_80070328 + 0x144)($at)
/* 63FD0E0 80088BB0 5E3C010C */  jal        func_8004F178
/* 63FD0E4 80088BB4 21280002 */   addu      $a1, $s0, $zero
/* 63FD0E8 80088BB8 21200002 */  addu       $a0, $s0, $zero
/* 63FD0EC 80088BBC 7A3B010C */  jal        func_8004EDE8
/* 63FD0F0 80088BC0 21280000 */   addu      $a1, $zero, $zero
/* 63FD0F4 80088BC4 0780013C */  lui        $at, %hi(D_80070328 + 0xB0)
/* 63FD0F8 80088BC8 D80322AC */  sw         $v0, %lo(D_80070328 + 0xB0)($at)
/* 63FD0FC 80088BCC C00D0224 */  addiu      $v0, $zero, 0xDC0
/* 63FD100 80088BD0 0780013C */  lui        $at, %hi(D_80070328 + 0x94)
/* 63FD104 80088BD4 BC0322AC */  sw         $v0, %lo(D_80070328 + 0x94)($at)
/* 63FD108 80088BD8 0780013C */  lui        $at, %hi(D_80070328 + 0x1B4)
/* 63FD10C 80088BDC DC0420A0 */  sb         $zero, %lo(D_80070328 + 0x1B4)($at)
/* 63FD110 80088BE0 30230208 */  j          .Llevel_27_80088CC0
/* 63FD114 80088BE4 00000000 */   nop
.Llevel_27_80088BE8:
/* 63FD118 80088BE8 0780033C */  lui        $v1, %hi(D_80070328 + 0x50)
/* 63FD11C 80088BEC 7803638C */  lw         $v1, %lo(D_80070328 + 0x50)($v1)
/* 63FD120 80088BF0 0780023C */  lui        $v0, %hi(D_80070328 + 0x20C)
/* 63FD124 80088BF4 3405428C */  lw         $v0, %lo(D_80070328 + 0x20C)($v0)
/* 63FD128 80088BF8 0780013C */  lui        $at, %hi(D_80070328 + 0x50)
/* 63FD12C 80088BFC 780326AC */  sw         $a2, %lo(D_80070328 + 0x50)($at)
/* 63FD130 80088C00 0780013C */  lui        $at, %hi(D_80070328 + 0x4C)
/* 63FD134 80088C04 740320AC */  sw         $zero, %lo(D_80070328 + 0x4C)($at)
/* 63FD138 80088C08 00044230 */  andi       $v0, $v0, 0x400
/* 63FD13C 80088C0C 0780013C */  lui        $at, %hi(D_80070328 + 0x144)
/* 63FD140 80088C10 6C0423AC */  sw         $v1, %lo(D_80070328 + 0x144)($at)
/* 63FD144 80088C14 09004010 */  beqz       $v0, .Llevel_27_80088C3C
/* 63FD148 80088C18 80FF3026 */   addiu     $s0, $s1, -0x80
/* 63FD14C 80088C1C 21200002 */  addu       $a0, $s0, $zero
/* 63FD150 80088C20 5E3C010C */  jal        func_8004F178
/* 63FD154 80088C24 10012526 */   addiu     $a1, $s1, 0x110
/* 63FD158 80088C28 21200002 */  addu       $a0, $s0, $zero
/* 63FD15C 80088C2C 3A3C010C */  jal        func_8004F0E8
/* 63FD160 80088C30 06000524 */   addiu     $a1, $zero, 0x6
/* 63FD164 80088C34 27230208 */  j          .Llevel_27_80088C9C
/* 63FD168 80088C38 00000000 */   nop
.Llevel_27_80088C3C:
/* 63FD16C 80088C3C 0780023C */  lui        $v0, %hi(D_80070328 + 0x298)
/* 63FD170 80088C40 C005428C */  lw         $v0, %lo(D_80070328 + 0x298)($v0)
/* 63FD174 80088C44 00000000 */  nop
/* 63FD178 80088C48 12004004 */  bltz       $v0, .Llevel_27_80088C94
/* 63FD17C 80088C4C 40100200 */   sll       $v0, $v0, 1
/* 63FD180 80088C50 0680013C */  lui        $at, %hi(D_80065920)
/* 63FD184 80088C54 21082200 */  addu       $at, $at, $v0
/* 63FD188 80088C58 20592384 */  lh         $v1, %lo(D_80065920)($at)
/* 63FD18C 80088C5C 00000000 */  nop
/* 63FD190 80088C60 43180300 */  sra        $v1, $v1, 1
/* 63FD194 80088C64 0780013C */  lui        $at, %hi(D_80070328 + 0x8C)
/* 63FD198 80088C68 B40323AC */  sw         $v1, %lo(D_80070328 + 0x8C)($at)
/* 63FD19C 80088C6C 0680013C */  lui        $at, %hi(D_800658A0)
/* 63FD1A0 80088C70 21082200 */  addu       $at, $at, $v0
/* 63FD1A4 80088C74 A0582284 */  lh         $v0, %lo(D_800658A0)($at)
/* 63FD1A8 80088C78 0780013C */  lui        $at, %hi(D_80070328 + 0x94)
/* 63FD1AC 80088C7C BC0320AC */  sw         $zero, %lo(D_80070328 + 0x94)($at)
/* 63FD1B0 80088C80 43100200 */  sra        $v0, $v0, 1
/* 63FD1B4 80088C84 0780013C */  lui        $at, %hi(D_80070328 + 0x90)
/* 63FD1B8 80088C88 B80322AC */  sw         $v0, %lo(D_80070328 + 0x90)($at)
/* 63FD1BC 80088C8C 27230208 */  j          .Llevel_27_80088C9C
/* 63FD1C0 80088C90 00000000 */   nop
.Llevel_27_80088C94:
/* 63FD1C4 80088C94 5A3C010C */  jal        func_8004F168
/* 63FD1C8 80088C98 80FF2426 */   addiu     $a0, $s1, -0x80
.Llevel_27_80088C9C:
/* 63FD1CC 80088C9C 0780043C */  lui        $a0, %hi(D_80070328 + 0x80)
/* 63FD1D0 80088CA0 A8038424 */  addiu      $a0, $a0, %lo(D_80070328 + 0x80)
/* 63FD1D4 80088CA4 5E3C010C */  jal        func_8004F178
/* 63FD1D8 80088CA8 0C008524 */   addiu     $a1, $a0, 0xC
/* 63FD1DC 80088CAC 8E0E010C */  jal        func_80043A38
/* 63FD1E0 80088CB0 000C0424 */   addiu     $a0, $zero, 0xC00
/* 63FD1E4 80088CB4 01000224 */  addiu      $v0, $zero, 0x1
/* 63FD1E8 80088CB8 0780013C */  lui        $at, %hi(D_80070328 + 0x1B4)
/* 63FD1EC 80088CBC DC0422A0 */  sb         $v0, %lo(D_80070328 + 0x1B4)($at)
.Llevel_27_80088CC0:
/* 63FD1F0 80088CC0 0780033C */  lui        $v1, %hi(SpawnParticle)
/* 63FD1F4 80088CC4 E442638C */  lw         $v1, %lo(SpawnParticle)($v1)
/* 63FD1F8 80088CC8 2D000224 */  addiu      $v0, $zero, 0x2D
/* 63FD1FC 80088CCC 0780013C */  lui        $at, %hi(D_8006E528)
/* 63FD200 80088CD0 28E522AC */  sw         $v0, %lo(D_8006E528)($at)
/* 63FD204 80088CD4 83006010 */  beqz       $v1, .Llevel_27_80088EE4
/* 63FD208 80088CD8 05000424 */   addiu     $a0, $zero, 0x5
/* 63FD20C 80088CDC 0A000524 */  addiu      $a1, $zero, 0xA
/* 63FD210 80088CE0 21300000 */  addu       $a2, $zero, $zero
/* 63FD214 80088CE4 09F86000 */  jalr       $v1
/* 63FD218 80088CE8 21380000 */   addu      $a3, $zero, $zero
/* 63FD21C 80088CEC B9230208 */  j          .Llevel_27_80088EE4
/* 63FD220 80088CF0 00000000 */   nop
.L80088CF4_:
/* 63FD224 80088CF4 0780033C */  lui        $v1, %hi(D_80070328 + 0x144)
/* 63FD228 80088CF8 6C046324 */  addiu      $v1, $v1, %lo(D_80070328 + 0x144)
/* 63FD22C 80088CFC 48FF6424 */  addiu      $a0, $v1, -0xB8
/* 63FD230 80088D00 0780053C */  lui        $a1, %hi(D_80070328 + 0x50)
/* 63FD234 80088D04 7803A58C */  lw         $a1, %lo(D_80070328 + 0x50)($a1)
/* 63FD238 80088D08 07000224 */  addiu      $v0, $zero, 0x7
/* 63FD23C 80088D0C 0780013C */  lui        $at, %hi(D_80070328 + 0x50)
/* 63FD240 80088D10 780322AC */  sw         $v0, %lo(D_80070328 + 0x50)($at)
/* 63FD244 80088D14 0780013C */  lui        $at, %hi(D_80070328 + 0x4C)
/* 63FD248 80088D18 740320AC */  sw         $zero, %lo(D_80070328 + 0x4C)($at)
/* 63FD24C 80088D1C 5A3C010C */  jal        func_8004F168
/* 63FD250 80088D20 000065AC */   sw        $a1, 0x0($v1)
/* 63FD254 80088D24 0780033C */  lui        $v1, %hi(SpawnParticle)
/* 63FD258 80088D28 E442638C */  lw         $v1, %lo(SpawnParticle)($v1)
/* 63FD25C 80088D2C 01000224 */  addiu      $v0, $zero, 0x1
/* 63FD260 80088D30 0780013C */  lui        $at, %hi(D_80070328 + 0x1B4)
/* 63FD264 80088D34 DC0422A0 */  sb         $v0, %lo(D_80070328 + 0x1B4)($at)
/* 63FD268 80088D38 0F000224 */  addiu      $v0, $zero, 0xF
/* 63FD26C 80088D3C 0780013C */  lui        $at, %hi(D_8006E524)
/* 63FD270 80088D40 24E522AC */  sw         $v0, %lo(D_8006E524)($at)
/* 63FD274 80088D44 05006010 */  beqz       $v1, .Llevel_27_80088D5C
/* 63FD278 80088D48 05000424 */   addiu     $a0, $zero, 0x5
/* 63FD27C 80088D4C 0A000524 */  addiu      $a1, $zero, 0xA
/* 63FD280 80088D50 21300000 */  addu       $a2, $zero, $zero
/* 63FD284 80088D54 09F86000 */  jalr       $v1
/* 63FD288 80088D58 21380000 */   addu      $a3, $zero, $zero
.Llevel_27_80088D5C:
/* 63FD28C 80088D5C 0780023C */  lui        $v0, %hi(D_8006C654)
/* 63FD290 80088D60 54C6428C */  lw         $v0, %lo(D_8006C654)($v0)
/* 63FD294 80088D64 21280000 */  addu       $a1, $zero, $zero
/* 63FD298 80088D68 09004490 */  lbu        $a0, 0x9($v0)
/* 63FD29C 80088D6C D4EE000C */  jal        func_8003BB50
/* 63FD2A0 80088D70 21300000 */   addu      $a2, $zero, $zero
/* 63FD2A4 80088D74 B9230208 */  j          .Llevel_27_80088EE4
/* 63FD2A8 80088D78 00000000 */   nop
.L80088D7C_:
/* 63FD2AC 80088D7C 0780033C */  lui        $v1, %hi(D_80070328 + 0x144)
/* 63FD2B0 80088D80 6C046324 */  addiu      $v1, $v1, %lo(D_80070328 + 0x144)
/* 63FD2B4 80088D84 48FF6424 */  addiu      $a0, $v1, -0xB8
/* 63FD2B8 80088D88 54FF7024 */  addiu      $s0, $v1, -0xAC
/* 63FD2BC 80088D8C 21280002 */  addu       $a1, $s0, $zero
/* 63FD2C0 80088D90 0780063C */  lui        $a2, %hi(D_80070328 + 0x50)
/* 63FD2C4 80088D94 7803C68C */  lw         $a2, %lo(D_80070328 + 0x50)($a2)
/* 63FD2C8 80088D98 07000224 */  addiu      $v0, $zero, 0x7
/* 63FD2CC 80088D9C 0780013C */  lui        $at, %hi(D_80070328 + 0x50)
/* 63FD2D0 80088DA0 780322AC */  sw         $v0, %lo(D_80070328 + 0x50)($at)
/* 63FD2D4 80088DA4 0780013C */  lui        $at, %hi(D_80070328 + 0x4C)
/* 63FD2D8 80088DA8 740320AC */  sw         $zero, %lo(D_80070328 + 0x4C)($at)
/* 63FD2DC 80088DAC 5E3C010C */  jal        func_8004F178
/* 63FD2E0 80088DB0 000066AC */   sw        $a2, 0x0($v1)
/* 63FD2E4 80088DB4 21200002 */  addu       $a0, $s0, $zero
/* 63FD2E8 80088DB8 7A3B010C */  jal        func_8004EDE8
/* 63FD2EC 80088DBC 21280000 */   addu      $a1, $zero, $zero
/* 63FD2F0 80088DC0 0780033C */  lui        $v1, %hi(SpawnParticle)
/* 63FD2F4 80088DC4 E442638C */  lw         $v1, %lo(SpawnParticle)($v1)
/* 63FD2F8 80088DC8 0780013C */  lui        $at, %hi(D_80070328 + 0xB0)
/* 63FD2FC 80088DCC D80322AC */  sw         $v0, %lo(D_80070328 + 0xB0)($at)
/* 63FD300 80088DD0 C00D0224 */  addiu      $v0, $zero, 0xDC0
/* 63FD304 80088DD4 0780013C */  lui        $at, %hi(D_80070328 + 0x94)
/* 63FD308 80088DD8 BC0322AC */  sw         $v0, %lo(D_80070328 + 0x94)($at)
/* 63FD30C 80088DDC 0F000224 */  addiu      $v0, $zero, 0xF
/* 63FD310 80088DE0 0780013C */  lui        $at, %hi(D_80070328 + 0x1B4)
/* 63FD314 80088DE4 DC0420A0 */  sb         $zero, %lo(D_80070328 + 0x1B4)($at)
/* 63FD318 80088DE8 0780013C */  lui        $at, %hi(D_8006E524)
/* 63FD31C 80088DEC 24E522AC */  sw         $v0, %lo(D_8006E524)($at)
/* 63FD320 80088DF0 05006010 */  beqz       $v1, .Llevel_27_80088E08
/* 63FD324 80088DF4 05000424 */   addiu     $a0, $zero, 0x5
/* 63FD328 80088DF8 0A000524 */  addiu      $a1, $zero, 0xA
/* 63FD32C 80088DFC 21300000 */  addu       $a2, $zero, $zero
/* 63FD330 80088E00 09F86000 */  jalr       $v1
/* 63FD334 80088E04 21380000 */   addu      $a3, $zero, $zero
.Llevel_27_80088E08:
/* 63FD338 80088E08 0780023C */  lui        $v0, %hi(D_80070328 + 0x24)
/* 63FD33C 80088E0C 4C03428C */  lw         $v0, %lo(D_80070328 + 0x24)($v0)
/* 63FD340 80088E10 00000000 */  nop
/* 63FD344 80088E14 00024230 */  andi       $v0, $v0, 0x200
/* 63FD348 80088E18 05004010 */  beqz       $v0, .Llevel_27_80088E30
/* 63FD34C 80088E1C 21280000 */   addu      $a1, $zero, $zero
/* 63FD350 80088E20 0780013C */  lui        $at, %hi(D_80070328 + 0x148)
/* 63FD354 80088E24 700420AC */  sw         $zero, %lo(D_80070328 + 0x148)($at)
/* 63FD358 80088E28 B9230208 */  j          .Llevel_27_80088EE4
/* 63FD35C 80088E2C 00000000 */   nop
.Llevel_27_80088E30:
/* 63FD360 80088E30 0780033C */  lui        $v1, %hi(D_8006C654)
/* 63FD364 80088E34 54C6638C */  lw         $v1, %lo(D_8006C654)($v1)
/* 63FD368 80088E38 01000224 */  addiu      $v0, $zero, 0x1
/* 63FD36C 80088E3C 0780013C */  lui        $at, %hi(D_80070328 + 0x148)
/* 63FD370 80088E40 700422AC */  sw         $v0, %lo(D_80070328 + 0x148)($at)
/* 63FD374 80088E44 0C006490 */  lbu        $a0, 0xC($v1)
/* 63FD378 80088E48 D4EE000C */  jal        func_8003BB50
/* 63FD37C 80088E4C 21300000 */   addu      $a2, $zero, $zero
/* 63FD380 80088E50 B9230208 */  j          .Llevel_27_80088EE4
/* 63FD384 80088E54 00000000 */   nop
.L80088E58_:
/* 63FD388 80088E58 08000224 */  addiu      $v0, $zero, 0x8
/* 63FD38C 80088E5C 0780013C */  lui        $at, %hi(D_80070328 + 0x50)
/* 63FD390 80088E60 780322AC */  sw         $v0, %lo(D_80070328 + 0x50)($at)
/* 63FD394 80088E64 0780013C */  lui        $at, %hi(D_80070328 + 0x4C)
/* 63FD398 80088E68 740320AC */  sw         $zero, %lo(D_80070328 + 0x4C)($at)
/* 63FD39C 80088E6C 8E0E010C */  jal        func_80043A38
/* 63FD3A0 80088E70 000C0424 */   addiu     $a0, $zero, 0xC00
/* 63FD3A4 80088E74 01000224 */  addiu      $v0, $zero, 0x1
/* 63FD3A8 80088E78 0780013C */  lui        $at, %hi(D_80070328 + 0x1B4)
/* 63FD3AC 80088E7C DC0422A0 */  sb         $v0, %lo(D_80070328 + 0x1B4)($at)
/* 63FD3B0 80088E80 3A000224 */  addiu      $v0, $zero, 0x3A
/* 63FD3B4 80088E84 03000212 */  beq        $s0, $v0, .Llevel_27_80088E94
/* 63FD3B8 80088E88 6C000224 */   addiu     $v0, $zero, 0x6C
/* 63FD3BC 80088E8C 08000216 */  bne        $s0, $v0, .Llevel_27_80088EB0
/* 63FD3C0 80088E90 0F000224 */   addiu     $v0, $zero, 0xF
.Llevel_27_80088E94:
/* 63FD3C4 80088E94 0780023C */  lui        $v0, %hi(D_8006C654)
/* 63FD3C8 80088E98 54C6428C */  lw         $v0, %lo(D_8006C654)($v0)
/* 63FD3CC 80088E9C 21280000 */  addu       $a1, $zero, $zero
/* 63FD3D0 80088EA0 0C004490 */  lbu        $a0, 0xC($v0)
/* 63FD3D4 80088EA4 D4EE000C */  jal        func_8003BB50
/* 63FD3D8 80088EA8 21300000 */   addu      $a2, $zero, $zero
/* 63FD3DC 80088EAC 0F000224 */  addiu      $v0, $zero, 0xF
.Llevel_27_80088EB0:
/* 63FD3E0 80088EB0 0780013C */  lui        $at, %hi(D_8006E524)
/* 63FD3E4 80088EB4 24E522AC */  sw         $v0, %lo(D_8006E524)($at)
/* 63FD3E8 80088EB8 B9230208 */  j          .Llevel_27_80088EE4
/* 63FD3EC 80088EBC 00000000 */   nop
.L80088EC0_:
/* 63FD3F0 80088EC0 0780013C */  lui        $at, %hi(D_80070328 + 0x50)
/* 63FD3F4 80088EC4 780320AC */  sw         $zero, %lo(D_80070328 + 0x50)($at)
/* 63FD3F8 80088EC8 0780013C */  lui        $at, %hi(D_80070328 + 0x4C)
/* 63FD3FC 80088ECC 740320AC */  sw         $zero, %lo(D_80070328 + 0x4C)($at)
/* 63FD400 80088ED0 7C10010C */  jal        func_800441F0
/* 63FD404 80088ED4 00000000 */   nop
/* 63FD408 80088ED8 01000224 */  addiu      $v0, $zero, 0x1
/* 63FD40C 80088EDC 0780013C */  lui        $at, %hi(D_80070328 + 0x1B4)
/* 63FD410 80088EE0 DC0422A0 */  sb         $v0, %lo(D_80070328 + 0x1B4)($at)
.Llevel_27_80088EE4:
/* 63FD414 80088EE4 0780013C */  lui        $at, %hi(D_80070328 + 0x244)
/* 63FD418 80088EE8 6C0520AC */  sw         $zero, %lo(D_80070328 + 0x244)($at)
/* 63FD41C 80088EEC 0780013C */  lui        $at, %hi(D_80070328 + 0x250)
/* 63FD420 80088EF0 780520AC */  sw         $zero, %lo(D_80070328 + 0x250)($at)
.Llevel_27_80088EF4:
/* 63FD424 80088EF4 1800BF8F */  lw         $ra, 0x18($sp)
/* 63FD428 80088EF8 1400B18F */  lw         $s1, 0x14($sp)
/* 63FD42C 80088EFC 1000B08F */  lw         $s0, 0x10($sp)
/* 63FD430 80088F00 2000BD27 */  addiu      $sp, $sp, 0x20
/* 63FD434 80088F04 0800E003 */  jr         $ra
/* 63FD438 80088F08 00000000 */   nop
.size func_level_27_80088AE4, . - func_level_27_80088AE4
