.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_34_800746B0
/* 74D03E0 800746B0 B0450880 */ .word .L800845B0_
/* 74D03E4 800746B4 7C450880 */ .word .L8008457C_
/* 74D03E8 800746B8 244D0880 */ .word .Llevel_34_80084D24
/* 74D03EC 800746BC 244D0880 */ .word .Llevel_34_80084D24
/* 74D03F0 800746C0 244D0880 */ .word .Llevel_34_80084D24
/* 74D03F4 800746C4 244D0880 */ .word .Llevel_34_80084D24
/* 74D03F8 800746C8 244D0880 */ .word .Llevel_34_80084D24
/* 74D03FC 800746CC 244D0880 */ .word .Llevel_34_80084D24
/* 74D0400 800746D0 244D0880 */ .word .Llevel_34_80084D24
/* 74D0404 800746D4 244D0880 */ .word .Llevel_34_80084D24
/* 74D0408 800746D8 244D0880 */ .word .Llevel_34_80084D24
/* 74D040C 800746DC 244D0880 */ .word .Llevel_34_80084D24
/* 74D0410 800746E0 244D0880 */ .word .Llevel_34_80084D24
/* 74D0414 800746E4 244D0880 */ .word .Llevel_34_80084D24
/* 74D0418 800746E8 244D0880 */ .word .Llevel_34_80084D24
/* 74D041C 800746EC 244D0880 */ .word .Llevel_34_80084D24
/* 74D0420 800746F0 244D0880 */ .word .Llevel_34_80084D24
/* 74D0424 800746F4 244D0880 */ .word .Llevel_34_80084D24
/* 74D0428 800746F8 684C0880 */ .word .L80084C68_
/* 74D042C 800746FC 843E0880 */ .word .L80083E84_
/* 74D0430 80074700 083B0880 */ .word .L80083B08_
/* 74D0434 80074704 643A0880 */ .word .L80083A64_
/* 74D0438 80074708 84400880 */ .word .L80084084_
/* 74D043C 8007470C 00000000 */ .word 0x00000000
.size jtbl_level_34_800746B0, . - jtbl_level_34_800746B0


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_34_80083834
/* 74DF564 80083834 00FFBD27 */  addiu      $sp, $sp, -0x100
/* 74DF568 80083838 E000B2AF */  sw         $s2, 0xE0($sp)
/* 74DF56C 8008383C 21908000 */  addu       $s2, $a0, $zero
/* 74DF570 80083840 14000224 */  addiu      $v0, $zero, 0x14
/* 74DF574 80083844 F800BFAF */  sw         $ra, 0xF8($sp)
/* 74DF578 80083848 F400B7AF */  sw         $s7, 0xF4($sp)
/* 74DF57C 8008384C F000B6AF */  sw         $s6, 0xF0($sp)
/* 74DF580 80083850 EC00B5AF */  sw         $s5, 0xEC($sp)
/* 74DF584 80083854 E800B4AF */  sw         $s4, 0xE8($sp)
/* 74DF588 80083858 E400B3AF */  sw         $s3, 0xE4($sp)
/* 74DF58C 8008385C DC00B1AF */  sw         $s1, 0xDC($sp)
/* 74DF590 80083860 D800B0AF */  sw         $s0, 0xD8($sp)
/* 74DF594 80083864 48004492 */  lbu        $a0, 0x48($s2)
/* 74DF598 80083868 0000578E */  lw         $s7, 0x0($s2)
/* 74DF59C 8008386C 71008210 */  beq        $a0, $v0, .Llevel_34_80083A34
/* 74DF5A0 80083870 8B00033C */   lui       $v1, (0x8B0000 >> 16)
/* 74DF5A4 80083874 1800428E */  lw         $v0, 0x18($s2)
/* 74DF5A8 80083878 00000000 */  nop
/* 74DF5AC 8008387C 24104300 */  and        $v0, $v0, $v1
/* 74DF5B0 80083880 6C004010 */  beqz       $v0, .Llevel_34_80083A34
/* 74DF5B4 80083884 18000224 */   addiu     $v0, $zero, 0x18
/* 74DF5B8 80083888 03008210 */  beq        $a0, $v0, .Llevel_34_80083898
/* 74DF5BC 8008388C 02000224 */   addiu     $v0, $zero, 0x2
/* 74DF5C0 80083890 21008214 */  bne        $a0, $v0, .Llevel_34_80083918
/* 74DF5C4 80083894 5E010224 */   addiu     $v0, $zero, 0x15E
.Llevel_34_80083898:
/* 74DF5C8 80083898 3A004292 */  lbu        $v0, 0x3A($s2)
/* 74DF5CC 8008389C 00000000 */  nop
/* 74DF5D0 800838A0 40180200 */  sll        $v1, $v0, 1
/* 74DF5D4 800838A4 21186200 */  addu       $v1, $v1, $v0
/* 74DF5D8 800838A8 80180300 */  sll        $v1, $v1, 2
/* 74DF5DC 800838AC 23186200 */  subu       $v1, $v1, $v0
/* 74DF5E0 800838B0 0780023C */  lui        $v0, %hi(D_8006C550)
/* 74DF5E4 800838B4 50C5428C */  lw         $v0, %lo(D_8006C550)($v0)
/* 74DF5E8 800838B8 C0180300 */  sll        $v1, $v1, 3
/* 74DF5EC 800838BC 21104300 */  addu       $v0, $v0, $v1
/* 74DF5F0 800838C0 0000508C */  lw         $s0, 0x0($v0)
/* 74DF5F4 800838C4 00000000 */  nop
/* 74DF5F8 800838C8 5000028E */  lw         $v0, 0x50($s0)
/* 74DF5FC 800838CC 00000000 */  nop
/* 74DF600 800838D0 03004010 */  beqz       $v0, .Llevel_34_800838E0
/* 74DF604 800838D4 060000A6 */   sh        $zero, 0x6($s0)
/* 74DF608 800838D8 100040A0 */  sb         $zero, 0x10($v0)
/* 74DF60C 800838DC 500000AE */  sw         $zero, 0x50($s0)
.Llevel_34_800838E0:
/* 74DF610 800838E0 5400028E */  lw         $v0, 0x54($s0)
/* 74DF614 800838E4 00000000 */  nop
/* 74DF618 800838E8 03004010 */  beqz       $v0, .Llevel_34_800838F8
/* 74DF61C 800838EC 00000000 */   nop
/* 74DF620 800838F0 100040A0 */  sb         $zero, 0x10($v0)
/* 74DF624 800838F4 540000AE */  sw         $zero, 0x54($s0)
.Llevel_34_800838F8:
/* 74DF628 800838F8 5800048E */  lw         $a0, 0x58($s0)
/* 74DF62C 800838FC 00000000 */  nop
/* 74DF630 80083900 05008010 */  beqz       $a0, .Llevel_34_80083918
/* 74DF634 80083904 5E010224 */   addiu     $v0, $zero, 0x15E
/* 74DF638 80083908 C656010C */  jal        func_80055B18
/* 74DF63C 8008390C 00000000 */   nop
/* 74DF640 80083910 580000AE */  sw         $zero, 0x58($s0)
/* 74DF644 80083914 5E010224 */  addiu      $v0, $zero, 0x15E
.Llevel_34_80083918:
/* 74DF648 80083918 9171010C */  jal        func_8005C644
/* 74DF64C 8008391C 0400E2A6 */   sh        $v0, 0x4($s7)
/* 74DF650 80083920 01004230 */  andi       $v0, $v0, 0x1
/* 74DF654 80083924 02004010 */  beqz       $v0, .Llevel_34_80083930
/* 74DF658 80083928 A6FF1024 */   addiu     $s0, $zero, -0x5A
/* 74DF65C 8008392C 5A001024 */  addiu      $s0, $zero, 0x5A
.Llevel_34_80083930:
/* 74DF660 80083930 21300000 */  addu       $a2, $zero, $zero
/* 74DF664 80083934 0780033C */  lui        $v1, %hi(D_8006E020)
/* 74DF668 80083938 20E0638C */  lw         $v1, %lo(D_8006E020)($v1)
/* 74DF66C 8008393C 0C00448E */  lw         $a0, 0xC($s2)
/* 74DF670 80083940 0780023C */  lui        $v0, %hi(D_8006E024)
/* 74DF674 80083944 24E0428C */  lw         $v0, %lo(D_8006E024)($v0)
/* 74DF678 80083948 1000458E */  lw         $a1, 0x10($s2)
/* 74DF67C 8008394C 23206400 */  subu       $a0, $v1, $a0
/* 74DF680 80083950 203A010C */  jal        func_8004E880
/* 74DF684 80083954 23284500 */   subu      $a1, $v0, $a1
/* 74DF688 80083958 21204002 */  addu       $a0, $s2, $zero
/* 74DF68C 8008395C 01000524 */  addiu      $a1, $zero, 0x1
/* 74DF690 80083960 21105000 */  addu       $v0, $v0, $s0
/* 74DF694 80083964 FF004230 */  andi       $v0, $v0, 0xFF
/* 74DF698 80083968 B4001124 */  addiu      $s1, $zero, 0xB4
/* 74DF69C 8008396C FF001324 */  addiu      $s3, $zero, 0xFF
/* 74DF6A0 80083970 0200E2A6 */  sh         $v0, 0x2($s7)
/* 74DF6A4 80083974 0000F1A6 */  sh         $s1, 0x0($s7)
/* 74DF6A8 80083978 4A0053A2 */  sb         $s3, 0x4A($s2)
/* 74DF6AC 8008397C 440040A2 */  sb         $zero, 0x44($s2)
/* 74DF6B0 80083980 E0D3000C */  jal        func_80034F80
/* 74DF6B4 80083984 450040A2 */   sb        $zero, 0x45($s2)
/* 74DF6B8 80083988 21204002 */  addu       $a0, $s2, $zero
/* 74DF6BC 8008398C 02000524 */  addiu      $a1, $zero, 0x2
/* 74DF6C0 80083990 21300000 */  addu       $a2, $zero, $zero
/* 74DF6C4 80083994 14001424 */  addiu      $s4, $zero, 0x14
/* 74DF6C8 80083998 AFEE000C */  jal        func_8003BABC
/* 74DF6CC 8008399C 480054A2 */   sb        $s4, 0x48($s2)
/* 74DF6D0 800839A0 1400E58E */  lw         $a1, 0x14($s7)
/* 74DF6D4 800839A4 F0EF000C */  jal        func_8003BFC0
/* 74DF6D8 800839A8 21204002 */   addu      $a0, $s2, $zero
/* 74DF6DC 800839AC 05004010 */  beqz       $v0, .Llevel_34_800839C4
/* 74DF6E0 800839B0 6F010424 */   addiu     $a0, $zero, 0x16F
/* 74DF6E4 800839B4 1400E48E */  lw         $a0, 0x14($s7)
/* 74DF6E8 800839B8 9CEF000C */  jal        func_8003BE70
/* 74DF6EC 800839BC 00000000 */   nop
/* 74DF6F0 800839C0 6F010424 */  addiu      $a0, $zero, 0x16F
.Llevel_34_800839C4:
/* 74DF6F4 800839C4 0780023C */  lui        $v0, %hi(SpawnMoby)
/* 74DF6F8 800839C8 E042428C */  lw         $v0, %lo(SpawnMoby)($v0)
/* 74DF6FC 800839CC 00000000 */  nop
/* 74DF700 800839D0 09F84000 */  jalr       $v0
/* 74DF704 800839D4 21284002 */   addu      $a1, $s2, $zero
/* 74DF708 800839D8 21804000 */  addu       $s0, $v0, $zero
/* 74DF70C 800839DC 15000012 */  beqz       $s0, .Llevel_34_80083A34
/* 74DF710 800839E0 2C010224 */   addiu     $v0, $zero, 0x12C
/* 74DF714 800839E4 0000038E */  lw         $v1, 0x0($s0)
/* 74DF718 800839E8 00000000 */  nop
/* 74DF71C 800839EC 040062A4 */  sh         $v0, 0x4($v1)
/* 74DF720 800839F0 0200E296 */  lhu        $v0, 0x2($s7)
/* 74DF724 800839F4 21200002 */  addu       $a0, $s0, $zero
/* 74DF728 800839F8 000071A4 */  sh         $s1, 0x0($v1)
/* 74DF72C 800839FC 80004224 */  addiu      $v0, $v0, 0x80
/* 74DF730 80083A00 FF004230 */  andi       $v0, $v0, 0xFF
/* 74DF734 80083A04 020062A4 */  sh         $v0, 0x2($v1)
/* 74DF738 80083A08 20000224 */  addiu      $v0, $zero, 0x20
/* 74DF73C 80083A0C 4A0013A2 */  sb         $s3, 0x4A($s0)
/* 74DF740 80083A10 4C0002A2 */  sb         $v0, 0x4C($s0)
/* 74DF744 80083A14 4E0002A2 */  sb         $v0, 0x4E($s0)
/* 74DF748 80083A18 440000A2 */  sb         $zero, 0x44($s0)
/* 74DF74C 80083A1C 450000A2 */  sb         $zero, 0x45($s0)
/* 74DF750 80083A20 46004292 */  lbu        $v0, 0x46($s2)
/* 74DF754 80083A24 04000524 */  addiu      $a1, $zero, 0x4
/* 74DF758 80083A28 E0D3000C */  jal        func_80034F80
/* 74DF75C 80083A2C 460002A2 */   sb        $v0, 0x46($s0)
/* 74DF760 80083A30 480014A2 */  sb         $s4, 0x48($s0)
.Llevel_34_80083A34:
/* 74DF764 80083A34 48004292 */  lbu        $v0, 0x48($s2)
/* 74DF768 80083A38 00000000 */  nop
/* 74DF76C 80083A3C FEFF4324 */  addiu      $v1, $v0, -0x2
/* 74DF770 80083A40 1700622C */  sltiu      $v0, $v1, 0x17
/* 74DF774 80083A44 B7044010 */  beqz       $v0, .Llevel_34_80084D24
/* 74DF778 80083A48 80100300 */   sll       $v0, $v1, 2
/* 74DF77C 80083A4C 0780013C */  lui        $at, %hi(jtbl_level_34_800746B0)
/* 74DF780 80083A50 21082200 */  addu       $at, $at, $v0
/* 74DF784 80083A54 B046228C */  lw         $v0, %lo(jtbl_level_34_800746B0)($at)
/* 74DF788 80083A58 00000000 */  nop
/* 74DF78C 80083A5C 08004000 */  jr         $v0
/* 74DF790 80083A60 00000000 */   nop
.L80083A64_:
/* 74DF794 80083A64 49004292 */  lbu        $v0, 0x49($s2)
/* 74DF798 80083A68 0800F08E */  lw         $s0, 0x8($s7)
/* 74DF79C 80083A6C 07004014 */  bnez       $v0, .Llevel_34_80083A8C
/* 74DF7A0 80083A70 21204002 */   addu      $a0, $s2, $zero
/* 74DF7A4 80083A74 21280000 */  addu       $a1, $zero, $zero
/* 74DF7A8 80083A78 AFEE000C */  jal        func_8003BABC
/* 74DF7AC 80083A7C 21300000 */   addu      $a2, $zero, $zero
/* 74DF7B0 80083A80 02000224 */  addiu      $v0, $zero, 0x2
/* 74DF7B4 80083A84 490042A2 */  sb         $v0, 0x49($s2)
/* 74DF7B8 80083A88 21204002 */  addu       $a0, $s2, $zero
.Llevel_34_80083A8C:
/* 74DF7BC 80083A8C C8000524 */  addiu      $a1, $zero, 0xC8
/* 74DF7C0 80083A90 21300000 */  addu       $a2, $zero, $zero
/* 74DF7C4 80083A94 21380000 */  addu       $a3, $zero, $zero
/* 74DF7C8 80083A98 FFFF0224 */  addiu      $v0, $zero, -0x1
/* 74DF7CC 80083A9C 1400E2AE */  sw         $v0, 0x14($s7)
/* 74DF7D0 80083AA0 77D7000C */  jal        func_80035DDC
/* 74DF7D4 80083AA4 1000A0AF */   sw        $zero, 0x10($sp)
/* 74DF7D8 80083AA8 0C00E296 */  lhu        $v0, 0xC($s7)
/* 74DF7DC 80083AAC 0C00038E */  lw         $v1, 0xC($s0)
/* 74DF7E0 80083AB0 020002A6 */  sh         $v0, 0x2($s0)
/* 74DF7E4 80083AB4 0E00E296 */  lhu        $v0, 0xE($s7)
/* 74DF7E8 80083AB8 21300000 */  addu       $a2, $zero, $zero
/* 74DF7EC 80083ABC 0A0002A6 */  sh         $v0, 0xA($s0)
/* 74DF7F0 80083AC0 02000286 */  lh         $v0, 0x2($s0)
/* 74DF7F4 80083AC4 0C00448E */  lw         $a0, 0xC($s2)
/* 74DF7F8 80083AC8 1000458E */  lw         $a1, 0x10($s2)
/* 74DF7FC 80083ACC 00110200 */  sll        $v0, $v0, 4
/* 74DF800 80083AD0 21104300 */  addu       $v0, $v0, $v1
/* 74DF804 80083AD4 0000438C */  lw         $v1, 0x0($v0)
/* 74DF808 80083AD8 0400428C */  lw         $v0, 0x4($v0)
/* 74DF80C 80083ADC 23206400 */  subu       $a0, $v1, $a0
/* 74DF810 80083AE0 203A010C */  jal        func_8004E880
/* 74DF814 80083AE4 23284500 */   subu      $a1, $v0, $a1
/* 74DF818 80083AE8 46004492 */  lbu        $a0, 0x46($s2)
/* 74DF81C 80083AEC 993C010C */  jal        func_8004F264
/* 74DF820 80083AF0 21284000 */   addu      $a1, $v0, $zero
/* 74DF824 80083AF4 29004228 */  slti       $v0, $v0, 0x29
/* 74DF828 80083AF8 8A044014 */  bnez       $v0, .Llevel_34_80084D24
/* 74DF82C 80083AFC 16000224 */   addiu     $v0, $zero, 0x16
/* 74DF830 80083B00 9F0F0208 */  j          .Llevel_34_80083E7C
/* 74DF834 80083B04 480042A2 */   sb        $v0, 0x48($s2)
.L80083B08_:
/* 74DF838 80083B08 1400E58E */  lw         $a1, 0x14($s7)
/* 74DF83C 80083B0C 0800F08E */  lw         $s0, 0x8($s7)
/* 74DF840 80083B10 F0EF000C */  jal        func_8003BFC0
/* 74DF844 80083B14 21204002 */   addu      $a0, $s2, $zero
/* 74DF848 80083B18 06004014 */  bnez       $v0, .Llevel_34_80083B34
/* 74DF84C 80083B1C 00000000 */   nop
/* 74DF850 80083B20 21204002 */  addu       $a0, $s2, $zero
/* 74DF854 80083B24 01000524 */  addiu      $a1, $zero, 0x1
/* 74DF858 80083B28 AFEE000C */  jal        func_8003BABC
/* 74DF85C 80083B2C 04000624 */   addiu     $a2, $zero, 0x4
/* 74DF860 80083B30 1400E2AE */  sw         $v0, 0x14($s7)
.Llevel_34_80083B34:
/* 74DF864 80083B34 21204002 */  addu       $a0, $s2, $zero
/* 74DF868 80083B38 4957010C */  jal        func_80055D24
/* 74DF86C 80083B3C 05000524 */   addiu     $a1, $zero, 0x5
/* 74DF870 80083B40 02000386 */  lh         $v1, 0x2($s0)
/* 74DF874 80083B44 0A000286 */  lh         $v0, 0xA($s0)
/* 74DF878 80083B48 00000486 */  lh         $a0, 0x0($s0)
/* 74DF87C 80083B4C 21106200 */  addu       $v0, $v1, $v0
/* 74DF880 80083B50 1A004400 */  div        $zero, $v0, $a0
/* 74DF884 80083B54 02008014 */  bnez       $a0, .Llevel_34_80083B60
/* 74DF888 80083B58 00000000 */   nop
/* 74DF88C 80083B5C 0D000700 */  break      7
.Llevel_34_80083B60:
/* 74DF890 80083B60 FFFF0124 */  addiu      $at, $zero, -0x1
/* 74DF894 80083B64 04008114 */  bne        $a0, $at, .Llevel_34_80083B78
/* 74DF898 80083B68 0080013C */   lui       $at, (0x80000000 >> 16)
/* 74DF89C 80083B6C 02004114 */  bne        $v0, $at, .Llevel_34_80083B78
/* 74DF8A0 80083B70 00000000 */   nop
/* 74DF8A4 80083B74 0D000600 */  break      6
.Llevel_34_80083B78:
/* 74DF8A8 80083B78 10280000 */  mfhi       $a1
/* 74DF8AC 80083B7C 21300000 */  addu       $a2, $zero, $zero
/* 74DF8B0 80083B80 0C00028E */  lw         $v0, 0xC($s0)
/* 74DF8B4 80083B84 00190300 */  sll        $v1, $v1, 4
/* 74DF8B8 80083B88 21186200 */  addu       $v1, $v1, $v0
/* 74DF8BC 80083B8C 0000648C */  lw         $a0, 0x0($v1)
/* 74DF8C0 80083B90 00290500 */  sll        $a1, $a1, 4
/* 74DF8C4 80083B94 2128A200 */  addu       $a1, $a1, $v0
/* 74DF8C8 80083B98 0000A78C */  lw         $a3, 0x0($a1)
/* 74DF8CC 80083B9C 0400A28C */  lw         $v0, 0x4($a1)
/* 74DF8D0 80083BA0 0400658C */  lw         $a1, 0x4($v1)
/* 74DF8D4 80083BA4 2320E400 */  subu       $a0, $a3, $a0
/* 74DF8D8 80083BA8 203A010C */  jal        func_8004E880
/* 74DF8DC 80083BAC 23284500 */   subu      $a1, $v0, $a1
/* 74DF8E0 80083BB0 46004592 */  lbu        $a1, 0x46($s2)
/* 74DF8E4 80083BB4 993C010C */  jal        func_8004F264
/* 74DF8E8 80083BB8 21204000 */   addu      $a0, $v0, $zero
/* 74DF8EC 80083BBC 0600E486 */  lh         $a0, 0x6($s7)
/* 74DF8F0 80083BC0 41005528 */  slti       $s5, $v0, 0x41
/* 74DF8F4 80083BC4 2C00A0AF */  sw         $zero, 0x2C($sp)
/* 74DF8F8 80083BC8 3000A0AF */  sw         $zero, 0x30($sp)
/* 74DF8FC 80083BCC 0900A016 */  bnez       $s5, .Llevel_34_80083BF4
/* 74DF900 80083BD0 2800A4AF */   sw        $a0, 0x28($sp)
/* 74DF904 80083BD4 5555033C */  lui        $v1, (0x55555556 >> 16)
/* 74DF908 80083BD8 56556334 */  ori        $v1, $v1, (0x55555556 & 0xFFFF)
/* 74DF90C 80083BDC 40100400 */  sll        $v0, $a0, 1
/* 74DF910 80083BE0 18004300 */  mult       $v0, $v1
/* 74DF914 80083BE4 C3170200 */  sra        $v0, $v0, 31
/* 74DF918 80083BE8 10400000 */  mfhi       $t0
/* 74DF91C 80083BEC 23100201 */  subu       $v0, $t0, $v0
/* 74DF920 80083BF0 2800A2AF */  sw         $v0, 0x28($sp)
.Llevel_34_80083BF4:
/* 74DF924 80083BF4 20004426 */  addiu      $a0, $s2, 0x20
/* 74DF928 80083BF8 2800A527 */  addiu      $a1, $sp, 0x28
/* 74DF92C 80083BFC 5B3B010C */  jal        func_8004ED6C
/* 74DF930 80083C00 2130A000 */   addu      $a2, $a1, $zero
/* 74DF934 80083C04 0C005326 */  addiu      $s3, $s2, 0xC
/* 74DF938 80083C08 21206002 */  addu       $a0, $s3, $zero
/* 74DF93C 80083C0C 21286002 */  addu       $a1, $s3, $zero
/* 74DF940 80083C10 653C010C */  jal        func_8004F194
/* 74DF944 80083C14 2800A627 */   addiu     $a2, $sp, 0x28
/* 74DF948 80083C18 45005492 */  lbu        $s4, 0x45($s2)
/* 74DF94C 80083C1C 00000000 */  nop
/* 74DF950 80083C20 8100822A */  slti       $v0, $s4, 0x81
/* 74DF954 80083C24 02004014 */  bnez       $v0, .Llevel_34_80083C30
/* 74DF958 80083C28 3800B127 */   addiu     $s1, $sp, 0x38
/* 74DF95C 80083C2C 00FF9426 */  addiu      $s4, $s4, -0x100
.Llevel_34_80083C30:
/* 74DF960 80083C30 21202002 */  addu       $a0, $s1, $zero
/* 74DF964 80083C34 5E3C010C */  jal        func_8004F178
/* 74DF968 80083C38 21286002 */   addu      $a1, $s3, $zero
/* 74DF96C 80083C3C 21202002 */  addu       $a0, $s1, $zero
/* 74DF970 80083C40 4000A28F */  lw         $v0, 0x40($sp)
/* 74DF974 80083C44 20030524 */  addiu      $a1, $zero, 0x320
/* 74DF978 80083C48 F4014224 */  addiu      $v0, $v0, 0x1F4
/* 74DF97C 80083C4C 6564000C */  jal        func_80019194
/* 74DF980 80083C50 4000A2AF */   sw        $v0, 0x40($sp)
/* 74DF984 80083C54 0A004010 */  beqz       $v0, .Llevel_34_80083C80
/* 74DF988 80083C58 21202002 */   addu      $a0, $s1, $zero
/* 74DF98C 80083C5C 0780053C */  lui        $a1, %hi(D_8007190C)
/* 74DF990 80083C60 0C19A524 */  addiu      $a1, $a1, %lo(D_8007190C)
/* 74DF994 80083C64 5E3C010C */  jal        func_8004F178
/* 74DF998 80083C68 21206002 */   addu      $a0, $s3, $zero
/* 74DF99C 80083C6C 1400428E */  lw         $v0, 0x14($s2)
/* 74DF9A0 80083C70 00000000 */  nop
/* 74DF9A4 80083C74 0CFE4224 */  addiu      $v0, $v0, -0x1F4
/* 74DF9A8 80083C78 140042AE */  sw         $v0, 0x14($s2)
/* 74DF9AC 80083C7C 21202002 */  addu       $a0, $s1, $zero
.Llevel_34_80083C80:
/* 74DF9B0 80083C80 0C00E586 */  lh         $a1, 0xC($s7)
/* 74DF9B4 80083C84 0C00028E */  lw         $v0, 0xC($s0)
/* 74DF9B8 80083C88 00290500 */  sll        $a1, $a1, 4
/* 74DF9BC 80083C8C 5E3C010C */  jal        func_8004F178
/* 74DF9C0 80083C90 21284500 */   addu      $a1, $v0, $a1
/* 74DF9C4 80083C94 21206002 */  addu       $a0, $s3, $zero
/* 74DF9C8 80083C98 1000E386 */  lh         $v1, 0x10($s7)
/* 74DF9CC 80083C9C 4000A28F */  lw         $v0, 0x40($sp)
/* 74DF9D0 80083CA0 21282002 */  addu       $a1, $s1, $zero
/* 74DF9D4 80083CA4 21104300 */  addu       $v0, $v0, $v1
/* 74DF9D8 80083CA8 CD3C010C */  jal        func_8004F334
/* 74DF9DC 80083CAC 4000A2AF */   sw        $v0, 0x40($sp)
/* 74DF9E0 80083CB0 21204000 */  addu       $a0, $v0, $zero
/* 74DF9E4 80083CB4 4000A28F */  lw         $v0, 0x40($sp)
/* 74DF9E8 80083CB8 1400458E */  lw         $a1, 0x14($s2)
/* 74DF9EC 80083CBC 21300000 */  addu       $a2, $zero, $zero
/* 74DF9F0 80083CC0 203A010C */  jal        func_8004E880
/* 74DF9F4 80083CC4 23284500 */   subu      $a1, $v0, $a1
/* 74DF9F8 80083CC8 23185400 */  subu       $v1, $v0, $s4
/* 74DF9FC 80083CCC 81006228 */  slti       $v0, $v1, 0x81
/* 74DFA00 80083CD0 03004014 */  bnez       $v0, .Llevel_34_80083CE0
/* 74DFA04 80083CD4 09006228 */   slti      $v0, $v1, 0x9
/* 74DFA08 80083CD8 00FF6324 */  addiu      $v1, $v1, -0x100
/* 74DFA0C 80083CDC 09006228 */  slti       $v0, $v1, 0x9
.Llevel_34_80083CE0:
/* 74DFA10 80083CE0 03004014 */  bnez       $v0, .Llevel_34_80083CF0
/* 74DFA14 80083CE4 F8FF6228 */   slti      $v0, $v1, -0x8
/* 74DFA18 80083CE8 08000324 */  addiu      $v1, $zero, 0x8
/* 74DFA1C 80083CEC F8FF6228 */  slti       $v0, $v1, -0x8
.Llevel_34_80083CF0:
/* 74DFA20 80083CF0 02004010 */  beqz       $v0, .Llevel_34_80083CFC
/* 74DFA24 80083CF4 00000000 */   nop
/* 74DFA28 80083CF8 F8FF0324 */  addiu      $v1, $zero, -0x8
.Llevel_34_80083CFC:
/* 74DFA2C 80083CFC 45004292 */  lbu        $v0, 0x45($s2)
/* 74DFA30 80083D00 00000000 */  nop
/* 74DFA34 80083D04 21104300 */  addu       $v0, $v0, $v1
/* 74DFA38 80083D08 450042A2 */  sb         $v0, 0x45($s2)
/* 74DFA3C 80083D0C 0C00E296 */  lhu        $v0, 0xC($s7)
/* 74DFA40 80083D10 00000000 */  nop
/* 74DFA44 80083D14 020002A6 */  sh         $v0, 0x2($s0)
/* 74DFA48 80083D18 0E00E296 */  lhu        $v0, 0xE($s7)
/* 74DFA4C 80083D1C 1100A016 */  bnez       $s5, .Llevel_34_80083D64
/* 74DFA50 80083D20 0A0002A6 */   sh        $v0, 0xA($s0)
/* 74DFA54 80083D24 21300000 */  addu       $a2, $zero, $zero
/* 74DFA58 80083D28 02000286 */  lh         $v0, 0x2($s0)
/* 74DFA5C 80083D2C 0C00038E */  lw         $v1, 0xC($s0)
/* 74DFA60 80083D30 0C00448E */  lw         $a0, 0xC($s2)
/* 74DFA64 80083D34 1000458E */  lw         $a1, 0x10($s2)
/* 74DFA68 80083D38 00110200 */  sll        $v0, $v0, 4
/* 74DFA6C 80083D3C 21104300 */  addu       $v0, $v0, $v1
/* 74DFA70 80083D40 0000438C */  lw         $v1, 0x0($v0)
/* 74DFA74 80083D44 0400428C */  lw         $v0, 0x4($v0)
/* 74DFA78 80083D48 23206400 */  subu       $a0, $v1, $a0
/* 74DFA7C 80083D4C 203A010C */  jal        func_8004E880
/* 74DFA80 80083D50 23284500 */   subu      $a1, $v0, $a1
/* 74DFA84 80083D54 21204002 */  addu       $a0, $s2, $zero
/* 74DFA88 80083D58 21284000 */  addu       $a1, $v0, $zero
/* 74DFA8C 80083D5C 680F0208 */  j          .Llevel_34_80083DA0
/* 74DFA90 80083D60 06000624 */   addiu     $a2, $zero, 0x6
.Llevel_34_80083D64:
/* 74DFA94 80083D64 21300000 */  addu       $a2, $zero, $zero
/* 74DFA98 80083D68 02000286 */  lh         $v0, 0x2($s0)
/* 74DFA9C 80083D6C 0C00038E */  lw         $v1, 0xC($s0)
/* 74DFAA0 80083D70 0C00448E */  lw         $a0, 0xC($s2)
/* 74DFAA4 80083D74 1000458E */  lw         $a1, 0x10($s2)
/* 74DFAA8 80083D78 00110200 */  sll        $v0, $v0, 4
/* 74DFAAC 80083D7C 21104300 */  addu       $v0, $v0, $v1
/* 74DFAB0 80083D80 0000438C */  lw         $v1, 0x0($v0)
/* 74DFAB4 80083D84 0400428C */  lw         $v0, 0x4($v0)
/* 74DFAB8 80083D88 23206400 */  subu       $a0, $v1, $a0
/* 74DFABC 80083D8C 203A010C */  jal        func_8004E880
/* 74DFAC0 80083D90 23284500 */   subu      $a1, $v0, $a1
/* 74DFAC4 80083D94 21204002 */  addu       $a0, $s2, $zero
/* 74DFAC8 80083D98 21284000 */  addu       $a1, $v0, $zero
/* 74DFACC 80083D9C 04000624 */  addiu      $a2, $zero, 0x4
.Llevel_34_80083DA0:
/* 74DFAD0 80083DA0 02000724 */  addiu      $a3, $zero, 0x2
/* 74DFAD4 80083DA4 01000224 */  addiu      $v0, $zero, 0x1
/* 74DFAD8 80083DA8 1000A2AF */  sw         $v0, 0x10($sp)
/* 74DFADC 80083DAC 17D6000C */  jal        func_8003585C
/* 74DFAE0 80083DB0 1400A0AF */   sw        $zero, 0x14($sp)
/* 74DFAE4 80083DB4 49004392 */  lbu        $v1, 0x49($s2)
/* 74DFAE8 80083DB8 01000224 */  addiu      $v0, $zero, 0x1
/* 74DFAEC 80083DBC 26006214 */  bne        $v1, $v0, .Llevel_34_80083E58
/* 74DFAF0 80083DC0 0C004426 */   addiu     $a0, $s2, 0xC
/* 74DFAF4 80083DC4 21300000 */  addu       $a2, $zero, $zero
/* 74DFAF8 80083DC8 02000286 */  lh         $v0, 0x2($s0)
/* 74DFAFC 80083DCC 0C00038E */  lw         $v1, 0xC($s0)
/* 74DFB00 80083DD0 0C00448E */  lw         $a0, 0xC($s2)
/* 74DFB04 80083DD4 1000458E */  lw         $a1, 0x10($s2)
/* 74DFB08 80083DD8 00110200 */  sll        $v0, $v0, 4
/* 74DFB0C 80083DDC 21104300 */  addu       $v0, $v0, $v1
/* 74DFB10 80083DE0 0000438C */  lw         $v1, 0x0($v0)
/* 74DFB14 80083DE4 0400428C */  lw         $v0, 0x4($v0)
/* 74DFB18 80083DE8 23206400 */  subu       $a0, $v1, $a0
/* 74DFB1C 80083DEC 203A010C */  jal        func_8004E880
/* 74DFB20 80083DF0 23284500 */   subu      $a1, $v0, $a1
/* 74DFB24 80083DF4 46004492 */  lbu        $a0, 0x46($s2)
/* 74DFB28 80083DF8 993C010C */  jal        func_8004F264
/* 74DFB2C 80083DFC 21284000 */   addu      $a1, $v0, $zero
/* 74DFB30 80083E00 41004228 */  slti       $v0, $v0, 0x41
/* 74DFB34 80083E04 14004014 */  bnez       $v0, .Llevel_34_80083E58
/* 74DFB38 80083E08 0C004426 */   addiu     $a0, $s2, 0xC
/* 74DFB3C 80083E0C 02000286 */  lh         $v0, 0x2($s0)
/* 74DFB40 80083E10 0A000486 */  lh         $a0, 0xA($s0)
/* 74DFB44 80083E14 00000386 */  lh         $v1, 0x0($s0)
/* 74DFB48 80083E18 21104400 */  addu       $v0, $v0, $a0
/* 74DFB4C 80083E1C 21104300 */  addu       $v0, $v0, $v1
/* 74DFB50 80083E20 1A004300 */  div        $zero, $v0, $v1
/* 74DFB54 80083E24 02006014 */  bnez       $v1, .Llevel_34_80083E30
/* 74DFB58 80083E28 00000000 */   nop
/* 74DFB5C 80083E2C 0D000700 */  break      7
.Llevel_34_80083E30:
/* 74DFB60 80083E30 FFFF0124 */  addiu      $at, $zero, -0x1
/* 74DFB64 80083E34 04006114 */  bne        $v1, $at, .Llevel_34_80083E48
/* 74DFB68 80083E38 0080013C */   lui       $at, (0x80000000 >> 16)
/* 74DFB6C 80083E3C 02004114 */  bne        $v0, $at, .Llevel_34_80083E48
/* 74DFB70 80083E40 00000000 */   nop
/* 74DFB74 80083E44 0D000600 */  break      6
.Llevel_34_80083E48:
/* 74DFB78 80083E48 10180000 */  mfhi       $v1
/* 74DFB7C 80083E4C 00000000 */  nop
/* 74DFB80 80083E50 020003A6 */  sh         $v1, 0x2($s0)
/* 74DFB84 80083E54 0C004426 */  addiu      $a0, $s2, 0xC
.Llevel_34_80083E58:
/* 74DFB88 80083E58 02000586 */  lh         $a1, 0x2($s0)
/* 74DFB8C 80083E5C 0C00028E */  lw         $v0, 0xC($s0)
/* 74DFB90 80083E60 00290500 */  sll        $a1, $a1, 4
/* 74DFB94 80083E64 CD3C010C */  jal        func_8004F334
/* 74DFB98 80083E68 21284500 */   addu      $a1, $v0, $a1
/* 74DFB9C 80083E6C 00024228 */  slti       $v0, $v0, 0x200
/* 74DFBA0 80083E70 AC034010 */  beqz       $v0, .Llevel_34_80084D24
/* 74DFBA4 80083E74 15000224 */   addiu     $v0, $zero, 0x15
/* 74DFBA8 80083E78 480042A2 */  sb         $v0, 0x48($s2)
.Llevel_34_80083E7C:
/* 74DFBAC 80083E7C 49130208 */  j          .Llevel_34_80084D24
/* 74DFBB0 80083E80 490040A2 */   sb        $zero, 0x49($s2)
.L80083E84_:
/* 74DFBB4 80083E84 1400E58E */  lw         $a1, 0x14($s7)
/* 74DFBB8 80083E88 0800F38E */  lw         $s3, 0x8($s7)
/* 74DFBBC 80083E8C F0EF000C */  jal        func_8003BFC0
/* 74DFBC0 80083E90 21204002 */   addu      $a0, $s2, $zero
/* 74DFBC4 80083E94 05004014 */  bnez       $v0, .Llevel_34_80083EAC
/* 74DFBC8 80083E98 21204002 */   addu      $a0, $s2, $zero
/* 74DFBCC 80083E9C 01000524 */  addiu      $a1, $zero, 0x1
/* 74DFBD0 80083EA0 AFEE000C */  jal        func_8003BABC
/* 74DFBD4 80083EA4 04000624 */   addiu     $a2, $zero, 0x4
/* 74DFBD8 80083EA8 1400E2AE */  sw         $v0, 0x14($s7)
.Llevel_34_80083EAC:
/* 74DFBDC 80083EAC 3A004392 */  lbu        $v1, 0x3A($s2)
/* 74DFBE0 80083EB0 FF000224 */  addiu      $v0, $zero, 0xFF
/* 74DFBE4 80083EB4 3B006210 */  beq        $v1, $v0, .Llevel_34_80083FA4
/* 74DFBE8 80083EB8 40100300 */   sll       $v0, $v1, 1
/* 74DFBEC 80083EBC 21104300 */  addu       $v0, $v0, $v1
/* 74DFBF0 80083EC0 80100200 */  sll        $v0, $v0, 2
/* 74DFBF4 80083EC4 23104300 */  subu       $v0, $v0, $v1
/* 74DFBF8 80083EC8 0780033C */  lui        $v1, %hi(D_8006C550)
/* 74DFBFC 80083ECC 50C5638C */  lw         $v1, %lo(D_8006C550)($v1)
/* 74DFC00 80083ED0 C0100200 */  sll        $v0, $v0, 3
/* 74DFC04 80083ED4 21186200 */  addu       $v1, $v1, $v0
/* 74DFC08 80083ED8 0000718C */  lw         $s1, 0x0($v1)
/* 74DFC0C 80083EDC 00000000 */  nop
/* 74DFC10 80083EE0 06002286 */  lh         $v0, 0x6($s1)
/* 74DFC14 80083EE4 00000000 */  nop
/* 74DFC18 80083EE8 2E004014 */  bnez       $v0, .Llevel_34_80083FA4
/* 74DFC1C 80083EEC 0C005026 */   addiu     $s0, $s2, 0xC
/* 74DFC20 80083EF0 21200002 */  addu       $a0, $s0, $zero
/* 74DFC24 80083EF4 0780143C */  lui        $s4, %hi(D_80070328)
/* 74DFC28 80083EF8 28039426 */  addiu      $s4, $s4, %lo(D_80070328)
/* 74DFC2C 80083EFC CD3C010C */  jal        func_8004F334
/* 74DFC30 80083F00 21288002 */   addu      $a1, $s4, $zero
/* 74DFC34 80083F04 01304228 */  slti       $v0, $v0, 0x3001
/* 74DFC38 80083F08 26004014 */  bnez       $v0, .Llevel_34_80083FA4
/* 74DFC3C 80083F0C 21300000 */   addu      $a2, $zero, $zero
/* 74DFC40 80083F10 0C00438E */  lw         $v1, 0xC($s2)
/* 74DFC44 80083F14 0780043C */  lui        $a0, %hi(D_8006E020)
/* 74DFC48 80083F18 20E0848C */  lw         $a0, %lo(D_8006E020)($a0)
/* 74DFC4C 80083F1C 1000428E */  lw         $v0, 0x10($s2)
/* 74DFC50 80083F20 0780053C */  lui        $a1, %hi(D_8006E024)
/* 74DFC54 80083F24 24E0A58C */  lw         $a1, %lo(D_8006E024)($a1)
/* 74DFC58 80083F28 23206400 */  subu       $a0, $v1, $a0
/* 74DFC5C 80083F2C 203A010C */  jal        func_8004E880
/* 74DFC60 80083F30 23284500 */   subu      $a1, $v0, $a1
/* 74DFC64 80083F34 0780043C */  lui        $a0, %hi(D_8006E040)
/* 74DFC68 80083F38 40E08494 */  lhu        $a0, %lo(D_8006E040)($a0)
/* 74DFC6C 80083F3C 21284000 */  addu       $a1, $v0, $zero
/* 74DFC70 80083F40 00240400 */  sll        $a0, $a0, 16
/* 74DFC74 80083F44 993C010C */  jal        func_8004F264
/* 74DFC78 80083F48 03250400 */   sra       $a0, $a0, 20
/* 74DFC7C 80083F4C 10004228 */  slti       $v0, $v0, 0x10
/* 74DFC80 80083F50 14004010 */  beqz       $v0, .Llevel_34_80083FA4
/* 74DFC84 80083F54 21200002 */   addu      $a0, $s0, $zero
/* 74DFC88 80083F58 CD3C010C */  jal        func_8004F334
/* 74DFC8C 80083F5C 21288002 */   addu      $a1, $s4, $zero
/* 74DFC90 80083F60 21204000 */  addu       $a0, $v0, $zero
/* 74DFC94 80083F64 0780023C */  lui        $v0, %hi(D_80070328 + 8)
/* 74DFC98 80083F68 3003428C */  lw         $v0, %lo(D_80070328 + 8)($v0)
/* 74DFC9C 80083F6C 1400458E */  lw         $a1, 0x14($s2)
/* 74DFCA0 80083F70 21300000 */  addu       $a2, $zero, $zero
/* 74DFCA4 80083F74 203A010C */  jal        func_8004E880
/* 74DFCA8 80083F78 23284500 */   subu      $a1, $v0, $a1
/* 74DFCAC 80083F7C 45004592 */  lbu        $a1, 0x45($s2)
/* 74DFCB0 80083F80 993C010C */  jal        func_8004F264
/* 74DFCB4 80083F84 21204000 */   addu      $a0, $v0, $zero
/* 74DFCB8 80083F88 10004228 */  slti       $v0, $v0, 0x10
/* 74DFCBC 80083F8C 05004010 */  beqz       $v0, .Llevel_34_80083FA4
/* 74DFCC0 80083F90 01000224 */   addiu     $v0, $zero, 0x1
/* 74DFCC4 80083F94 060022A6 */  sh         $v0, 0x6($s1)
/* 74DFCC8 80083F98 18000224 */  addiu      $v0, $zero, 0x18
/* 74DFCCC 80083F9C 49130208 */  j          .Llevel_34_80084D24
/* 74DFCD0 80083FA0 480042A2 */   sb        $v0, 0x48($s2)
.Llevel_34_80083FA4:
/* 74DFCD4 80083FA4 45004292 */  lbu        $v0, 0x45($s2)
/* 74DFCD8 80083FA8 00000000 */  nop
/* 74DFCDC 80083FAC 0D004010 */  beqz       $v0, .Llevel_34_80083FE4
/* 74DFCE0 80083FB0 21184000 */   addu      $v1, $v0, $zero
/* 74DFCE4 80083FB4 81006228 */  slti       $v0, $v1, 0x81
/* 74DFCE8 80083FB8 06004014 */  bnez       $v0, .Llevel_34_80083FD4
/* 74DFCEC 80083FBC 05006228 */   slti      $v0, $v1, 0x5
/* 74DFCF0 80083FC0 FC006228 */  slti       $v0, $v1, 0xFC
/* 74DFCF4 80083FC4 05004010 */  beqz       $v0, .Llevel_34_80083FDC
/* 74DFCF8 80083FC8 04006324 */   addiu     $v1, $v1, 0x4
/* 74DFCFC 80083FCC F90F0208 */  j          .Llevel_34_80083FE4
/* 74DFD00 80083FD0 450043A2 */   sb        $v1, 0x45($s2)
.Llevel_34_80083FD4:
/* 74DFD04 80083FD4 02004010 */  beqz       $v0, .Llevel_34_80083FE0
/* 74DFD08 80083FD8 FCFF6324 */   addiu     $v1, $v1, -0x4
.Llevel_34_80083FDC:
/* 74DFD0C 80083FDC 21180000 */  addu       $v1, $zero, $zero
.Llevel_34_80083FE0:
/* 74DFD10 80083FE0 450043A2 */  sb         $v1, 0x45($s2)
.Llevel_34_80083FE4:
/* 74DFD14 80083FE4 21204002 */  addu       $a0, $s2, $zero
/* 74DFD18 80083FE8 0C00E296 */  lhu        $v0, 0xC($s7)
/* 74DFD1C 80083FEC 21286002 */  addu       $a1, $s3, $zero
/* 74DFD20 80083FF0 020062A6 */  sh         $v0, 0x2($s3)
/* 74DFD24 80083FF4 0E00E296 */  lhu        $v0, 0xE($s7)
/* 74DFD28 80083FF8 00020624 */  addiu      $a2, $zero, 0x200
/* 74DFD2C 80083FFC 0A0062A6 */  sh         $v0, 0xA($s3)
/* 74DFD30 80084000 0600E786 */  lh         $a3, 0x6($s7)
/* 74DFD34 80084004 05000224 */  addiu      $v0, $zero, 0x5
/* 74DFD38 80084008 1400A2AF */  sw         $v0, 0x14($sp)
/* 74DFD3C 8008400C 40000224 */  addiu      $v0, $zero, 0x40
/* 74DFD40 80084010 1800A2AF */  sw         $v0, 0x18($sp)
/* 74DFD44 80084014 0200023C */  lui        $v0, (0x20000 >> 16)
/* 74DFD48 80084018 1000A0AF */  sw         $zero, 0x10($sp)
/* 74DFD4C 8008401C A0D6000C */  jal        func_80035A80
/* 74DFD50 80084020 1C00A2AF */   sw        $v0, 0x1C($sp)
/* 74DFD54 80084024 4800B027 */  addiu      $s0, $sp, 0x48
/* 74DFD58 80084028 21200002 */  addu       $a0, $s0, $zero
/* 74DFD5C 8008402C 0C005126 */  addiu      $s1, $s2, 0xC
/* 74DFD60 80084030 02006296 */  lhu        $v0, 0x2($s3)
/* 74DFD64 80084034 21282002 */  addu       $a1, $s1, $zero
/* 74DFD68 80084038 5E3C010C */  jal        func_8004F178
/* 74DFD6C 8008403C 0C00E2A6 */   sh        $v0, 0xC($s7)
/* 74DFD70 80084040 21200002 */  addu       $a0, $s0, $zero
/* 74DFD74 80084044 5000A28F */  lw         $v0, 0x50($sp)
/* 74DFD78 80084048 20030524 */  addiu      $a1, $zero, 0x320
/* 74DFD7C 8008404C F4014224 */  addiu      $v0, $v0, 0x1F4
/* 74DFD80 80084050 6564000C */  jal        func_80019194
/* 74DFD84 80084054 5000A2AF */   sw        $v0, 0x50($sp)
/* 74DFD88 80084058 32034010 */  beqz       $v0, .Llevel_34_80084D24
/* 74DFD8C 8008405C 00000000 */   nop
/* 74DFD90 80084060 0780053C */  lui        $a1, %hi(D_8007190C)
/* 74DFD94 80084064 0C19A524 */  addiu      $a1, $a1, %lo(D_8007190C)
/* 74DFD98 80084068 5E3C010C */  jal        func_8004F178
/* 74DFD9C 8008406C 21202002 */   addu      $a0, $s1, $zero
/* 74DFDA0 80084070 1400428E */  lw         $v0, 0x14($s2)
/* 74DFDA4 80084074 00000000 */  nop
/* 74DFDA8 80084078 0CFE4224 */  addiu      $v0, $v0, -0x1F4
/* 74DFDAC 8008407C 49130208 */  j          .Llevel_34_80084D24
/* 74DFDB0 80084080 140042AE */   sw        $v0, 0x14($s2)
.L80084084_:
/* 74DFDB4 80084084 1400E58E */  lw         $a1, 0x14($s7)
/* 74DFDB8 80084088 F0EF000C */  jal        func_8003BFC0
/* 74DFDBC 8008408C 21204002 */   addu      $a0, $s2, $zero
/* 74DFDC0 80084090 06004014 */  bnez       $v0, .Llevel_34_800840AC
/* 74DFDC4 80084094 21204002 */   addu      $a0, $s2, $zero
/* 74DFDC8 80084098 01000524 */  addiu      $a1, $zero, 0x1
/* 74DFDCC 8008409C AFEE000C */  jal        func_8003BABC
/* 74DFDD0 800840A0 04000624 */   addiu     $a2, $zero, 0x4
/* 74DFDD4 800840A4 1400E2AE */  sw         $v0, 0x14($s7)
/* 74DFDD8 800840A8 21204002 */  addu       $a0, $s2, $zero
.Llevel_34_800840AC:
/* 74DFDDC 800840AC 4957010C */  jal        func_80055D24
/* 74DFDE0 800840B0 07000524 */   addiu     $a1, $zero, 0x7
/* 74DFDE4 800840B4 20004426 */  addiu      $a0, $s2, 0x20
/* 74DFDE8 800840B8 5800B027 */  addiu      $s0, $sp, 0x58
/* 74DFDEC 800840BC 21280002 */  addu       $a1, $s0, $zero
/* 74DFDF0 800840C0 0600E286 */  lh         $v0, 0x6($s7)
/* 74DFDF4 800840C4 21300002 */  addu       $a2, $s0, $zero
/* 74DFDF8 800840C8 5C00A0AF */  sw         $zero, 0x5C($sp)
/* 74DFDFC 800840CC 6000A0AF */  sw         $zero, 0x60($sp)
/* 74DFE00 800840D0 5B3B010C */  jal        func_8004ED6C
/* 74DFE04 800840D4 5800A2AF */   sw        $v0, 0x58($sp)
/* 74DFE08 800840D8 0C004426 */  addiu      $a0, $s2, 0xC
/* 74DFE0C 800840DC 21288000 */  addu       $a1, $a0, $zero
/* 74DFE10 800840E0 653C010C */  jal        func_8004F194
/* 74DFE14 800840E4 21300002 */   addu      $a2, $s0, $zero
/* 74DFE18 800840E8 45005092 */  lbu        $s0, 0x45($s2)
/* 74DFE1C 800840EC 00000000 */  nop
/* 74DFE20 800840F0 8100022A */  slti       $v0, $s0, 0x81
/* 74DFE24 800840F4 02004014 */  bnez       $v0, .Llevel_34_80084100
/* 74DFE28 800840F8 00000000 */   nop
/* 74DFE2C 800840FC 00FF1026 */  addiu      $s0, $s0, -0x100
.Llevel_34_80084100:
/* 74DFE30 80084100 0780053C */  lui        $a1, %hi(D_80070328)
/* 74DFE34 80084104 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 74DFE38 80084108 5E3C010C */  jal        func_8004F178
/* 74DFE3C 8008410C 6800A427 */   addiu     $a0, $sp, 0x68
/* 74DFE40 80084110 7000A48F */  lw         $a0, 0x70($sp)
/* 74DFE44 80084114 00000000 */  nop
/* 74DFE48 80084118 80FF8224 */  addiu      $v0, $a0, -0x80
/* 74DFE4C 8008411C 7000A2AF */  sw         $v0, 0x70($sp)
/* 74DFE50 80084120 1400438E */  lw         $v1, 0x14($s2)
/* 74DFE54 80084124 00000000 */  nop
/* 74DFE58 80084128 23184300 */  subu       $v1, $v0, $v1
/* 74DFE5C 8008412C F5016228 */  slti       $v0, $v1, 0x1F5
/* 74DFE60 80084130 03004014 */  bnez       $v0, .Llevel_34_80084140
/* 74DFE64 80084134 0CFE6228 */   slti      $v0, $v1, -0x1F4
/* 74DFE68 80084138 52100208 */  j          .Llevel_34_80084148
/* 74DFE6C 8008413C F0168224 */   addiu     $v0, $a0, 0x16F0
.Llevel_34_80084140:
/* 74DFE70 80084140 02004010 */  beqz       $v0, .Llevel_34_8008414C
/* 74DFE74 80084144 10E88224 */   addiu     $v0, $a0, -0x17F0
.Llevel_34_80084148:
/* 74DFE78 80084148 7000A2AF */  sw         $v0, 0x70($sp)
.Llevel_34_8008414C:
/* 74DFE7C 8008414C 0C005326 */  addiu      $s3, $s2, 0xC
/* 74DFE80 80084150 21206002 */  addu       $a0, $s3, $zero
/* 74DFE84 80084154 6800B127 */  addiu      $s1, $sp, 0x68
/* 74DFE88 80084158 CD3C010C */  jal        func_8004F334
/* 74DFE8C 8008415C 21282002 */   addu      $a1, $s1, $zero
/* 74DFE90 80084160 21204000 */  addu       $a0, $v0, $zero
/* 74DFE94 80084164 7000A28F */  lw         $v0, 0x70($sp)
/* 74DFE98 80084168 1400458E */  lw         $a1, 0x14($s2)
/* 74DFE9C 8008416C 21300000 */  addu       $a2, $zero, $zero
/* 74DFEA0 80084170 203A010C */  jal        func_8004E880
/* 74DFEA4 80084174 23284500 */   subu      $a1, $v0, $a1
/* 74DFEA8 80084178 23185000 */  subu       $v1, $v0, $s0
/* 74DFEAC 8008417C 81006228 */  slti       $v0, $v1, 0x81
/* 74DFEB0 80084180 03004014 */  bnez       $v0, .Llevel_34_80084190
/* 74DFEB4 80084184 03006228 */   slti      $v0, $v1, 0x3
/* 74DFEB8 80084188 00FF6324 */  addiu      $v1, $v1, -0x100
/* 74DFEBC 8008418C 03006228 */  slti       $v0, $v1, 0x3
.Llevel_34_80084190:
/* 74DFEC0 80084190 03004014 */  bnez       $v0, .Llevel_34_800841A0
/* 74DFEC4 80084194 FEFF6228 */   slti      $v0, $v1, -0x2
/* 74DFEC8 80084198 02000324 */  addiu      $v1, $zero, 0x2
/* 74DFECC 8008419C FEFF6228 */  slti       $v0, $v1, -0x2
.Llevel_34_800841A0:
/* 74DFED0 800841A0 02004010 */  beqz       $v0, .Llevel_34_800841AC
/* 74DFED4 800841A4 21300000 */   addu      $a2, $zero, $zero
/* 74DFED8 800841A8 FEFF0324 */  addiu      $v1, $zero, -0x2
.Llevel_34_800841AC:
/* 74DFEDC 800841AC 0780143C */  lui        $s4, %hi(D_80070328)
/* 74DFEE0 800841B0 28039426 */  addiu      $s4, $s4, %lo(D_80070328)
/* 74DFEE4 800841B4 45004292 */  lbu        $v0, 0x45($s2)
/* 74DFEE8 800841B8 0C00448E */  lw         $a0, 0xC($s2)
/* 74DFEEC 800841BC 1000458E */  lw         $a1, 0x10($s2)
/* 74DFEF0 800841C0 21104300 */  addu       $v0, $v0, $v1
/* 74DFEF4 800841C4 450042A2 */  sb         $v0, 0x45($s2)
/* 74DFEF8 800841C8 0000838E */  lw         $v1, 0x0($s4)
/* 74DFEFC 800841CC 0400828E */  lw         $v0, 0x4($s4)
/* 74DFF00 800841D0 23206400 */  subu       $a0, $v1, $a0
/* 74DFF04 800841D4 203A010C */  jal        func_8004E880
/* 74DFF08 800841D8 23284500 */   subu      $a1, $v0, $a1
/* 74DFF0C 800841DC 21204002 */  addu       $a0, $s2, $zero
/* 74DFF10 800841E0 21284000 */  addu       $a1, $v0, $zero
/* 74DFF14 800841E4 04000624 */  addiu      $a2, $zero, 0x4
/* 74DFF18 800841E8 01000724 */  addiu      $a3, $zero, 0x1
/* 74DFF1C 800841EC 01001524 */  addiu      $s5, $zero, 0x1
/* 74DFF20 800841F0 1000B5AF */  sw         $s5, 0x10($sp)
/* 74DFF24 800841F4 17D6000C */  jal        func_8003585C
/* 74DFF28 800841F8 1400A0AF */   sw        $zero, 0x14($sp)
/* 74DFF2C 800841FC 21202002 */  addu       $a0, $s1, $zero
/* 74DFF30 80084200 5E3C010C */  jal        func_8004F178
/* 74DFF34 80084204 21286002 */   addu      $a1, $s3, $zero
/* 74DFF38 80084208 21202002 */  addu       $a0, $s1, $zero
/* 74DFF3C 8008420C 7000A28F */  lw         $v0, 0x70($sp)
/* 74DFF40 80084210 20030524 */  addiu      $a1, $zero, 0x320
/* 74DFF44 80084214 F4014224 */  addiu      $v0, $v0, 0x1F4
/* 74DFF48 80084218 6564000C */  jal        func_80019194
/* 74DFF4C 8008421C 7000A2AF */   sw        $v0, 0x70($sp)
/* 74DFF50 80084220 0A004010 */  beqz       $v0, .Llevel_34_8008424C
/* 74DFF54 80084224 21206002 */   addu      $a0, $s3, $zero
/* 74DFF58 80084228 0780053C */  lui        $a1, %hi(D_8007190C)
/* 74DFF5C 8008422C 0C19A524 */  addiu      $a1, $a1, %lo(D_8007190C)
/* 74DFF60 80084230 5E3C010C */  jal        func_8004F178
/* 74DFF64 80084234 21206002 */   addu      $a0, $s3, $zero
/* 74DFF68 80084238 1400428E */  lw         $v0, 0x14($s2)
/* 74DFF6C 8008423C 00000000 */  nop
/* 74DFF70 80084240 0CFE4224 */  addiu      $v0, $v0, -0x1F4
/* 74DFF74 80084244 140042AE */  sw         $v0, 0x14($s2)
/* 74DFF78 80084248 21206002 */  addu       $a0, $s3, $zero
.Llevel_34_8008424C:
/* 74DFF7C 8008424C CD3C010C */  jal        func_8004F334
/* 74DFF80 80084250 21288002 */   addu      $a1, $s4, $zero
/* 74DFF84 80084254 21884000 */  addu       $s1, $v0, $zero
/* 74DFF88 80084258 0008302A */  slti       $s0, $s1, 0x800
/* 74DFF8C 8008425C 13000016 */  bnez       $s0, .Llevel_34_800842AC
/* 74DFF90 80084260 21300000 */   addu      $a2, $zero, $zero
/* 74DFF94 80084264 0C00438E */  lw         $v1, 0xC($s2)
/* 74DFF98 80084268 0780043C */  lui        $a0, %hi(D_8006E020)
/* 74DFF9C 8008426C 20E0848C */  lw         $a0, %lo(D_8006E020)($a0)
/* 74DFFA0 80084270 1000428E */  lw         $v0, 0x10($s2)
/* 74DFFA4 80084274 0780053C */  lui        $a1, %hi(D_8006E024)
/* 74DFFA8 80084278 24E0A58C */  lw         $a1, %lo(D_8006E024)($a1)
/* 74DFFAC 8008427C 23206400 */  subu       $a0, $v1, $a0
/* 74DFFB0 80084280 203A010C */  jal        func_8004E880
/* 74DFFB4 80084284 23284500 */   subu      $a1, $v0, $a1
/* 74DFFB8 80084288 0780043C */  lui        $a0, %hi(D_8006E040)
/* 74DFFBC 8008428C 40E08494 */  lhu        $a0, %lo(D_8006E040)($a0)
/* 74DFFC0 80084290 21284000 */  addu       $a1, $v0, $zero
/* 74DFFC4 80084294 00240400 */  sll        $a0, $a0, 16
/* 74DFFC8 80084298 993C010C */  jal        func_8004F264
/* 74DFFCC 8008429C 03250400 */   sra       $a0, $a0, 20
/* 74DFFD0 800842A0 18004228 */  slti       $v0, $v0, 0x18
/* 74DFFD4 800842A4 61004014 */  bnez       $v0, .Llevel_34_8008442C
/* 74DFFD8 800842A8 00000000 */   nop
.Llevel_34_800842AC:
/* 74DFFDC 800842AC 3A004392 */  lbu        $v1, 0x3A($s2)
/* 74DFFE0 800842B0 16000224 */  addiu      $v0, $zero, 0x16
/* 74DFFE4 800842B4 480042A2 */  sb         $v0, 0x48($s2)
/* 74DFFE8 800842B8 01000224 */  addiu      $v0, $zero, 0x1
/* 74DFFEC 800842BC 490042A2 */  sb         $v0, 0x49($s2)
/* 74DFFF0 800842C0 40100300 */  sll        $v0, $v1, 1
/* 74DFFF4 800842C4 21104300 */  addu       $v0, $v0, $v1
/* 74DFFF8 800842C8 80100200 */  sll        $v0, $v0, 2
/* 74DFFFC 800842CC 23104300 */  subu       $v0, $v0, $v1
/* 74E0000 800842D0 0780033C */  lui        $v1, %hi(D_8006C550)
/* 74E0004 800842D4 50C5638C */  lw         $v1, %lo(D_8006C550)($v1)
/* 74E0008 800842D8 C0100200 */  sll        $v0, $v0, 3
/* 74E000C 800842DC 21104300 */  addu       $v0, $v0, $v1
/* 74E0010 800842E0 0000428C */  lw         $v0, 0x0($v0)
/* 74E0014 800842E4 4B000012 */  beqz       $s0, .Llevel_34_80084414
/* 74E0018 800842E8 060040A4 */   sh        $zero, 0x6($v0)
/* 74E001C 800842EC 21300000 */  addu       $a2, $zero, $zero
/* 74E0020 800842F0 0C00438E */  lw         $v1, 0xC($s2)
/* 74E0024 800842F4 0780043C */  lui        $a0, %hi(D_8006E020)
/* 74E0028 800842F8 20E0848C */  lw         $a0, %lo(D_8006E020)($a0)
/* 74E002C 800842FC 1000428E */  lw         $v0, 0x10($s2)
/* 74E0030 80084300 0780053C */  lui        $a1, %hi(D_8006E024)
/* 74E0034 80084304 24E0A58C */  lw         $a1, %lo(D_8006E024)($a1)
/* 74E0038 80084308 23206400 */  subu       $a0, $v1, $a0
/* 74E003C 8008430C 203A010C */  jal        func_8004E880
/* 74E0040 80084310 23284500 */   subu      $a1, $v0, $a1
/* 74E0044 80084314 0780043C */  lui        $a0, %hi(D_8006E040)
/* 74E0048 80084318 40E08494 */  lhu        $a0, %lo(D_8006E040)($a0)
/* 74E004C 8008431C 21284000 */  addu       $a1, $v0, $zero
/* 74E0050 80084320 00240400 */  sll        $a0, $a0, 16
/* 74E0054 80084324 993C010C */  jal        func_8004F264
/* 74E0058 80084328 03250400 */   sra       $a0, $a0, 20
/* 74E005C 8008432C 10004228 */  slti       $v0, $v0, 0x10
/* 74E0060 80084330 38004010 */  beqz       $v0, .Llevel_34_80084414
/* 74E0064 80084334 00000000 */   nop
/* 74E0068 80084338 1400428E */  lw         $v0, 0x14($s2)
/* 74E006C 8008433C 0780033C */  lui        $v1, %hi(D_80070328 + 8)
/* 74E0070 80084340 3003638C */  lw         $v1, %lo(D_80070328 + 8)($v1)
/* 74E0074 80084344 00000000 */  nop
/* 74E0078 80084348 23104300 */  subu       $v0, $v0, $v1
/* 74E007C 8008434C 02004104 */  bgez       $v0, .Llevel_34_80084358
/* 74E0080 80084350 00000000 */   nop
/* 74E0084 80084354 23100200 */  negu       $v0, $v0
.Llevel_34_80084358:
/* 74E0088 80084358 00024228 */  slti       $v0, $v0, 0x200
/* 74E008C 8008435C 2D004010 */  beqz       $v0, .Llevel_34_80084414
/* 74E0090 80084360 21300000 */   addu      $a2, $zero, $zero
/* 74E0094 80084364 0000838E */  lw         $v1, 0x0($s4)
/* 74E0098 80084368 0C00448E */  lw         $a0, 0xC($s2)
/* 74E009C 8008436C 0780023C */  lui        $v0, %hi(D_80070328 + 4)
/* 74E00A0 80084370 2C03428C */  lw         $v0, %lo(D_80070328 + 4)($v0)
/* 74E00A4 80084374 1000458E */  lw         $a1, 0x10($s2)
/* 74E00A8 80084378 23206400 */  subu       $a0, $v1, $a0
/* 74E00AC 8008437C 203A010C */  jal        func_8004E880
/* 74E00B0 80084380 23284500 */   subu      $a1, $v0, $a1
/* 74E00B4 80084384 46004492 */  lbu        $a0, 0x46($s2)
/* 74E00B8 80084388 993C010C */  jal        func_8004F264
/* 74E00BC 8008438C 21284000 */   addu      $a1, $v0, $zero
/* 74E00C0 80084390 08004228 */  slti       $v0, $v0, 0x8
/* 74E00C4 80084394 1F004010 */  beqz       $v0, .Llevel_34_80084414
/* 74E00C8 80084398 0010023C */   lui       $v0, (0x10000400 >> 16)
/* 74E00CC 8008439C 00044234 */  ori        $v0, $v0, (0x10000400 & 0xFFFF)
/* 74E00D0 800843A0 20004426 */  addiu      $a0, $s2, 0x20
/* 74E00D4 800843A4 7800A527 */  addiu      $a1, $sp, 0x78
/* 74E00D8 800843A8 46004392 */  lbu        $v1, 0x46($s2)
/* 74E00DC 800843AC 0780013C */  lui        $at, %hi(D_80070328 + 0x20C)
/* 74E00E0 800843B0 340522AC */  sw         $v0, %lo(D_80070328 + 0x20C)($at)
/* 74E00E4 800843B4 64000224 */  addiu      $v0, $zero, 0x64
/* 74E00E8 800843B8 0780013C */  lui        $at, %hi(D_80070328 + 0x24)
/* 74E00EC 800843BC 4C0335AC */  sw         $s5, %lo(D_80070328 + 0x24)($at)
/* 74E00F0 800843C0 7800A2AF */  sw         $v0, 0x78($sp)
/* 74E00F4 800843C4 7C00A0AF */  sw         $zero, 0x7C($sp)
/* 74E00F8 800843C8 8000A0AF */  sw         $zero, 0x80($sp)
/* 74E00FC 800843CC 0780013C */  lui        $at, %hi(D_80070328 + 0x298)
/* 74E0100 800843D0 C00523AC */  sw         $v1, %lo(D_80070328 + 0x298)($at)
/* 74E0104 800843D4 5B3B010C */  jal        func_8004ED6C
/* 74E0108 800843D8 2130A000 */   addu      $a2, $a1, $zero
/* 74E010C 800843DC 21204002 */  addu       $a0, $s2, $zero
/* 74E0110 800843E0 7800A38F */  lw         $v1, 0x78($sp)
/* 74E0114 800843E4 7C00A68F */  lw         $a2, 0x7C($sp)
/* 74E0118 800843E8 4B000224 */  addiu      $v0, $zero, 0x4B
/* 74E011C 800843EC 0780013C */  lui        $at, %hi(D_80070328 + 0x224)
/* 74E0120 800843F0 4C0522AC */  sw         $v0, %lo(D_80070328 + 0x224)($at)
/* 74E0124 800843F4 0780013C */  lui        $at, %hi(D_80070328 + 0x21C)
/* 74E0128 800843F8 440523AC */  sw         $v1, %lo(D_80070328 + 0x21C)($at)
/* 74E012C 800843FC 0780013C */  lui        $at, %hi(D_80070328 + 0x220)
/* 74E0130 80084400 480526AC */  sw         $a2, %lo(D_80070328 + 0x220)($at)
/* 74E0134 80084404 E0D3000C */  jal        func_80034F80
/* 74E0138 80084408 03000524 */   addiu     $a1, $zero, 0x3
/* 74E013C 8008440C 03000224 */  addiu      $v0, $zero, 0x3
/* 74E0140 80084410 480042A2 */  sb         $v0, 0x48($s2)
.Llevel_34_80084414:
/* 74E0144 80084414 1200E386 */  lh         $v1, 0x12($s7)
/* 74E0148 80084418 02000224 */  addiu      $v0, $zero, 0x2
/* 74E014C 8008441C 41026214 */  bne        $v1, $v0, .Llevel_34_80084D24
/* 74E0150 80084420 01000224 */   addiu     $v0, $zero, 0x1
/* 74E0154 80084424 49130208 */  j          .Llevel_34_80084D24
/* 74E0158 80084428 1200E2A6 */   sh        $v0, 0x12($s7)
.Llevel_34_8008442C:
/* 74E015C 8008442C 1200E286 */  lh         $v0, 0x12($s7)
/* 74E0160 80084430 00000000 */  nop
/* 74E0164 80084434 3B025514 */  bne        $v0, $s5, .Llevel_34_80084D24
/* 74E0168 80084438 21300000 */   addu      $a2, $zero, $zero
/* 74E016C 8008443C 0000838E */  lw         $v1, 0x0($s4)
/* 74E0170 80084440 0C00448E */  lw         $a0, 0xC($s2)
/* 74E0174 80084444 0780023C */  lui        $v0, %hi(D_80070328 + 4)
/* 74E0178 80084448 2C03428C */  lw         $v0, %lo(D_80070328 + 4)($v0)
/* 74E017C 8008444C 1000458E */  lw         $a1, 0x10($s2)
/* 74E0180 80084450 23206400 */  subu       $a0, $v1, $a0
/* 74E0184 80084454 203A010C */  jal        func_8004E880
/* 74E0188 80084458 23284500 */   subu      $a1, $v0, $a1
/* 74E018C 8008445C 46004592 */  lbu        $a1, 0x46($s2)
/* 74E0190 80084460 993C010C */  jal        func_8004F264
/* 74E0194 80084464 21204000 */   addu      $a0, $v0, $zero
/* 74E0198 80084468 40004228 */  slti       $v0, $v0, 0x40
/* 74E019C 8008446C 2D024010 */  beqz       $v0, .Llevel_34_80084D24
/* 74E01A0 80084470 FFD72226 */   addiu     $v0, $s1, -0x2801
/* 74E01A4 80084474 FF17422C */  sltiu      $v0, $v0, 0x17FF
/* 74E01A8 80084478 2A024010 */  beqz       $v0, .Llevel_34_80084D24
/* 74E01AC 8008447C 00000000 */   nop
/* 74E01B0 80084480 3A004392 */  lbu        $v1, 0x3A($s2)
/* 74E01B4 80084484 0780043C */  lui        $a0, %hi(D_8006C550)
/* 74E01B8 80084488 50C5848C */  lw         $a0, %lo(D_8006C550)($a0)
/* 74E01BC 8008448C 40100300 */  sll        $v0, $v1, 1
/* 74E01C0 80084490 21104300 */  addu       $v0, $v0, $v1
/* 74E01C4 80084494 80100200 */  sll        $v0, $v0, 2
/* 74E01C8 80084498 23104300 */  subu       $v0, $v0, $v1
/* 74E01CC 8008449C C0100200 */  sll        $v0, $v0, 3
/* 74E01D0 800844A0 21208200 */  addu       $a0, $a0, $v0
/* 74E01D4 800844A4 FF000224 */  addiu      $v0, $zero, 0xFF
/* 74E01D8 800844A8 0000908C */  lw         $s0, 0x0($a0)
/* 74E01DC 800844AC 0F026210 */  beq        $v1, $v0, .Llevel_34_80084CEC
/* 74E01E0 800844B0 D9030224 */   addiu     $v0, $zero, 0x3D9
/* 74E01E4 800844B4 36008384 */  lh         $v1, 0x36($a0)
/* 74E01E8 800844B8 00000000 */  nop
/* 74E01EC 800844BC 0B026214 */  bne        $v1, $v0, .Llevel_34_80084CEC
/* 74E01F0 800844C0 00000000 */   nop
/* 74E01F4 800844C4 48008290 */  lbu        $v0, 0x48($a0)
/* 74E01F8 800844C8 00000000 */  nop
/* 74E01FC 800844CC 80004230 */  andi       $v0, $v0, 0x80
/* 74E0200 800844D0 06024014 */  bnez       $v0, .Llevel_34_80084CEC
/* 74E0204 800844D4 00000000 */   nop
/* 74E0208 800844D8 03000292 */  lbu        $v0, 0x3($s0)
/* 74E020C 800844DC 00000000 */  nop
/* 74E0210 800844E0 08004014 */  bnez       $v0, .Llevel_34_80084504
/* 74E0214 800844E4 02000224 */   addiu     $v0, $zero, 0x2
/* 74E0218 800844E8 02000224 */  addiu      $v0, $zero, 0x2
/* 74E021C 800844EC 480042A2 */  sb         $v0, 0x48($s2)
/* 74E0220 800844F0 21204002 */  addu       $a0, $s2, $zero
/* 74E0224 800844F4 D0D3000C */  jal        func_80034F40
/* 74E0228 800844F8 02000524 */   addiu     $a1, $zero, 0x2
/* 74E022C 800844FC 42110208 */  j          .Llevel_34_80084508
/* 74E0230 80084500 00000000 */   nop
.Llevel_34_80084504:
/* 74E0234 80084504 1200E2A6 */  sh         $v0, 0x12($s7)
.Llevel_34_80084508:
/* 74E0238 80084508 0780033C */  lui        $v1, %hi(D_8006C7C4)
/* 74E023C 8008450C C4C7638C */  lw         $v1, %lo(D_8006C7C4)($v1)
/* 74E0240 80084510 02000224 */  addiu      $v0, $zero, 0x2
/* 74E0244 80084514 03006214 */  bne        $v1, $v0, .Llevel_34_80084524
/* 74E0248 80084518 01000224 */   addiu     $v0, $zero, 0x1
/* 74E024C 8008451C 49130208 */  j          .Llevel_34_80084D24
/* 74E0250 80084520 030000A2 */   sb        $zero, 0x3($s0)
.Llevel_34_80084524:
/* 74E0254 80084524 07006214 */  bne        $v1, $v0, .Llevel_34_80084544
/* 74E0258 80084528 6666023C */   lui       $v0, (0x66666667 >> 16)
/* 74E025C 8008452C 03000292 */  lbu        $v0, 0x3($s0)
/* 74E0260 80084530 00000000 */  nop
/* 74E0264 80084534 01004224 */  addiu      $v0, $v0, 0x1
/* 74E0268 80084538 01004230 */  andi       $v0, $v0, 0x1
/* 74E026C 8008453C 49130208 */  j          .Llevel_34_80084D24
/* 74E0270 80084540 030002A2 */   sb        $v0, 0x3($s0)
.Llevel_34_80084544:
/* 74E0274 80084544 03000492 */  lbu        $a0, 0x3($s0)
/* 74E0278 80084548 67664234 */  ori        $v0, $v0, (0x66666667 & 0xFFFF)
/* 74E027C 8008454C 01008424 */  addiu      $a0, $a0, 0x1
/* 74E0280 80084550 18008200 */  mult       $a0, $v0
/* 74E0284 80084554 C3170400 */  sra        $v0, $a0, 31
/* 74E0288 80084558 10400000 */  mfhi       $t0
/* 74E028C 8008455C 83180800 */  sra        $v1, $t0, 2
/* 74E0290 80084560 23186200 */  subu       $v1, $v1, $v0
/* 74E0294 80084564 80100300 */  sll        $v0, $v1, 2
/* 74E0298 80084568 21104300 */  addu       $v0, $v0, $v1
/* 74E029C 8008456C 40100200 */  sll        $v0, $v0, 1
/* 74E02A0 80084570 23208200 */  subu       $a0, $a0, $v0
/* 74E02A4 80084574 49130208 */  j          .Llevel_34_80084D24
/* 74E02A8 80084578 030004A2 */   sb        $a0, 0x3($s0)
.L8008457C_:
/* 74E02AC 8008457C 0780023C */  lui        $v0, %hi(D_8006C770)
/* 74E02B0 80084580 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 74E02B4 80084584 00000000 */  nop
/* 74E02B8 80084588 E6014010 */  beqz       $v0, .Llevel_34_80084D24
/* 74E02BC 8008458C 21204002 */   addu      $a0, $s2, $zero
/* 74E02C0 80084590 21280000 */  addu       $a1, $zero, $zero
/* 74E02C4 80084594 16000224 */  addiu      $v0, $zero, 0x16
/* 74E02C8 80084598 480082A0 */  sb         $v0, 0x48($a0)
/* 74E02CC 8008459C 01000224 */  addiu      $v0, $zero, 0x1
/* 74E02D0 800845A0 D0D3000C */  jal        func_80034F40
/* 74E02D4 800845A4 490082A0 */   sb        $v0, 0x49($a0)
/* 74E02D8 800845A8 49130208 */  j          .Llevel_34_80084D24
/* 74E02DC 800845AC 00000000 */   nop
.L800845B0_:
/* 74E02E0 800845B0 A157010C */  jal        func_80055E84
/* 74E02E4 800845B4 21204002 */   addu      $a0, $s2, $zero
/* 74E02E8 800845B8 21204002 */  addu       $a0, $s2, $zero
/* 74E02EC 800845BC 3A004392 */  lbu        $v1, 0x3A($s2)
/* 74E02F0 800845C0 21A04000 */  addu       $s4, $v0, $zero
/* 74E02F4 800845C4 40100300 */  sll        $v0, $v1, 1
/* 74E02F8 800845C8 21104300 */  addu       $v0, $v0, $v1
/* 74E02FC 800845CC 80100200 */  sll        $v0, $v0, 2
/* 74E0300 800845D0 23104300 */  subu       $v0, $v0, $v1
/* 74E0304 800845D4 0780033C */  lui        $v1, %hi(D_8006C550)
/* 74E0308 800845D8 50C5638C */  lw         $v1, %lo(D_8006C550)($v1)
/* 74E030C 800845DC C0100200 */  sll        $v0, $v0, 3
/* 74E0310 800845E0 21186200 */  addu       $v1, $v1, $v0
/* 74E0314 800845E4 0000758C */  lw         $s5, 0x0($v1)
/* 74E0318 800845E8 4957010C */  jal        func_80055D24
/* 74E031C 800845EC 07000524 */   addiu     $a1, $zero, 0x7
/* 74E0320 800845F0 20004426 */  addiu      $a0, $s2, 0x20
/* 74E0324 800845F4 7800B027 */  addiu      $s0, $sp, 0x78
/* 74E0328 800845F8 21280002 */  addu       $a1, $s0, $zero
/* 74E032C 800845FC 0600E286 */  lh         $v0, 0x6($s7)
/* 74E0330 80084600 21300002 */  addu       $a2, $s0, $zero
/* 74E0334 80084604 7C00A0AF */  sw         $zero, 0x7C($sp)
/* 74E0338 80084608 8000A0AF */  sw         $zero, 0x80($sp)
/* 74E033C 8008460C 5B3B010C */  jal        func_8004ED6C
/* 74E0340 80084610 7800A2AF */   sw        $v0, 0x78($sp)
/* 74E0344 80084614 0C004426 */  addiu      $a0, $s2, 0xC
/* 74E0348 80084618 21288000 */  addu       $a1, $a0, $zero
/* 74E034C 8008461C 653C010C */  jal        func_8004F194
/* 74E0350 80084620 21300002 */   addu      $a2, $s0, $zero
/* 74E0354 80084624 45005092 */  lbu        $s0, 0x45($s2)
/* 74E0358 80084628 00000000 */  nop
/* 74E035C 8008462C 8100022A */  slti       $v0, $s0, 0x81
/* 74E0360 80084630 02004014 */  bnez       $v0, .Llevel_34_8008463C
/* 74E0364 80084634 00000000 */   nop
/* 74E0368 80084638 00FF1026 */  addiu      $s0, $s0, -0x100
.Llevel_34_8008463C:
/* 74E036C 8008463C 0780053C */  lui        $a1, %hi(D_80070328)
/* 74E0370 80084640 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 74E0374 80084644 5E3C010C */  jal        func_8004F178
/* 74E0378 80084648 8800A427 */   addiu     $a0, $sp, 0x88
/* 74E037C 8008464C 9000A48F */  lw         $a0, 0x90($sp)
/* 74E0380 80084650 00000000 */  nop
/* 74E0384 80084654 80FF8224 */  addiu      $v0, $a0, -0x80
/* 74E0388 80084658 9000A2AF */  sw         $v0, 0x90($sp)
/* 74E038C 8008465C 1400438E */  lw         $v1, 0x14($s2)
/* 74E0390 80084660 00000000 */  nop
/* 74E0394 80084664 23184300 */  subu       $v1, $v0, $v1
/* 74E0398 80084668 F5016228 */  slti       $v0, $v1, 0x1F5
/* 74E039C 8008466C 03004014 */  bnez       $v0, .Llevel_34_8008467C
/* 74E03A0 80084670 0CFE6228 */   slti      $v0, $v1, -0x1F4
/* 74E03A4 80084674 A1110208 */  j          .Llevel_34_80084684
/* 74E03A8 80084678 F0168224 */   addiu     $v0, $a0, 0x16F0
.Llevel_34_8008467C:
/* 74E03AC 8008467C 02004010 */  beqz       $v0, .Llevel_34_80084688
/* 74E03B0 80084680 10E88224 */   addiu     $v0, $a0, -0x17F0
.Llevel_34_80084684:
/* 74E03B4 80084684 9000A2AF */  sw         $v0, 0x90($sp)
.Llevel_34_80084688:
/* 74E03B8 80084688 0C005126 */  addiu      $s1, $s2, 0xC
/* 74E03BC 8008468C 21202002 */  addu       $a0, $s1, $zero
/* 74E03C0 80084690 8800B327 */  addiu      $s3, $sp, 0x88
/* 74E03C4 80084694 CD3C010C */  jal        func_8004F334
/* 74E03C8 80084698 21286002 */   addu      $a1, $s3, $zero
/* 74E03CC 8008469C 21204000 */  addu       $a0, $v0, $zero
/* 74E03D0 800846A0 9000A28F */  lw         $v0, 0x90($sp)
/* 74E03D4 800846A4 1400458E */  lw         $a1, 0x14($s2)
/* 74E03D8 800846A8 21300000 */  addu       $a2, $zero, $zero
/* 74E03DC 800846AC 203A010C */  jal        func_8004E880
/* 74E03E0 800846B0 23284500 */   subu      $a1, $v0, $a1
/* 74E03E4 800846B4 23185000 */  subu       $v1, $v0, $s0
/* 74E03E8 800846B8 81006228 */  slti       $v0, $v1, 0x81
/* 74E03EC 800846BC 03004014 */  bnez       $v0, .Llevel_34_800846CC
/* 74E03F0 800846C0 03006228 */   slti      $v0, $v1, 0x3
/* 74E03F4 800846C4 00FF6324 */  addiu      $v1, $v1, -0x100
/* 74E03F8 800846C8 03006228 */  slti       $v0, $v1, 0x3
.Llevel_34_800846CC:
/* 74E03FC 800846CC 03004014 */  bnez       $v0, .Llevel_34_800846DC
/* 74E0400 800846D0 FEFF6228 */   slti      $v0, $v1, -0x2
/* 74E0404 800846D4 02000324 */  addiu      $v1, $zero, 0x2
/* 74E0408 800846D8 FEFF6228 */  slti       $v0, $v1, -0x2
.Llevel_34_800846DC:
/* 74E040C 800846DC 02004010 */  beqz       $v0, .Llevel_34_800846E8
/* 74E0410 800846E0 21300000 */   addu      $a2, $zero, $zero
/* 74E0414 800846E4 FEFF0324 */  addiu      $v1, $zero, -0x2
.Llevel_34_800846E8:
/* 74E0418 800846E8 45004292 */  lbu        $v0, 0x45($s2)
/* 74E041C 800846EC 0C00448E */  lw         $a0, 0xC($s2)
/* 74E0420 800846F0 1000458E */  lw         $a1, 0x10($s2)
/* 74E0424 800846F4 21104300 */  addu       $v0, $v0, $v1
/* 74E0428 800846F8 450042A2 */  sb         $v0, 0x45($s2)
/* 74E042C 800846FC 0780033C */  lui        $v1, %hi(D_80070328)
/* 74E0430 80084700 2803638C */  lw         $v1, %lo(D_80070328)($v1)
/* 74E0434 80084704 0780023C */  lui        $v0, %hi(D_80070328 + 4)
/* 74E0438 80084708 2C03428C */  lw         $v0, %lo(D_80070328 + 4)($v0)
/* 74E043C 8008470C 23206400 */  subu       $a0, $v1, $a0
/* 74E0440 80084710 203A010C */  jal        func_8004E880
/* 74E0444 80084714 23284500 */   subu      $a1, $v0, $a1
/* 74E0448 80084718 21204002 */  addu       $a0, $s2, $zero
/* 74E044C 8008471C 21284000 */  addu       $a1, $v0, $zero
/* 74E0450 80084720 04000624 */  addiu      $a2, $zero, 0x4
/* 74E0454 80084724 01000724 */  addiu      $a3, $zero, 0x1
/* 74E0458 80084728 01000224 */  addiu      $v0, $zero, 0x1
/* 74E045C 8008472C 1000A2AF */  sw         $v0, 0x10($sp)
/* 74E0460 80084730 17D6000C */  jal        func_8003585C
/* 74E0464 80084734 1400A0AF */   sw        $zero, 0x14($sp)
/* 74E0468 80084738 21206002 */  addu       $a0, $s3, $zero
/* 74E046C 8008473C 5E3C010C */  jal        func_8004F178
/* 74E0470 80084740 21282002 */   addu      $a1, $s1, $zero
/* 74E0474 80084744 21206002 */  addu       $a0, $s3, $zero
/* 74E0478 80084748 9000A28F */  lw         $v0, 0x90($sp)
/* 74E047C 8008474C 20030524 */  addiu      $a1, $zero, 0x320
/* 74E0480 80084750 F4014224 */  addiu      $v0, $v0, 0x1F4
/* 74E0484 80084754 6564000C */  jal        func_80019194
/* 74E0488 80084758 9000A2AF */   sw        $v0, 0x90($sp)
/* 74E048C 8008475C 0A004010 */  beqz       $v0, .Llevel_34_80084788
/* 74E0490 80084760 0500822A */   slti      $v0, $s4, 0x5
/* 74E0494 80084764 0780053C */  lui        $a1, %hi(D_8007190C)
/* 74E0498 80084768 0C19A524 */  addiu      $a1, $a1, %lo(D_8007190C)
/* 74E049C 8008476C 5E3C010C */  jal        func_8004F178
/* 74E04A0 80084770 21202002 */   addu      $a0, $s1, $zero
/* 74E04A4 80084774 1400428E */  lw         $v0, 0x14($s2)
/* 74E04A8 80084778 00000000 */  nop
/* 74E04AC 8008477C 0CFE4224 */  addiu      $v0, $v0, -0x1F4
/* 74E04B0 80084780 140042AE */  sw         $v0, 0x14($s2)
/* 74E04B4 80084784 0500822A */  slti       $v0, $s4, 0x5
.Llevel_34_80084788:
/* 74E04B8 80084788 D1004014 */  bnez       $v0, .Llevel_34_80084AD0
/* 74E04BC 8008478C 21204002 */   addu      $a0, $s2, $zero
/* 74E04C0 80084790 4957010C */  jal        func_80055D24
/* 74E04C4 80084794 05000524 */   addiu     $a1, $zero, 0x5
/* 74E04C8 80084798 21204002 */  addu       $a0, $s2, $zero
/* 74E04CC 8008479C 21280000 */  addu       $a1, $zero, $zero
/* 74E04D0 800847A0 9800B127 */  addiu      $s1, $sp, 0x98
/* 74E04D4 800847A4 C557010C */  jal        func_80055F14
/* 74E04D8 800847A8 21302002 */   addu      $a2, $s1, $zero
/* 74E04DC 800847AC 21204002 */  addu       $a0, $s2, $zero
/* 74E04E0 800847B0 01000524 */  addiu      $a1, $zero, 0x1
/* 74E04E4 800847B4 A800B027 */  addiu      $s0, $sp, 0xA8
/* 74E04E8 800847B8 C557010C */  jal        func_80055F14
/* 74E04EC 800847BC 21300002 */   addu      $a2, $s0, $zero
/* 74E04F0 800847C0 21200000 */  addu       $a0, $zero, $zero
/* 74E04F4 800847C4 DBD8000C */  jal        func_8003636C
/* 74E04F8 800847C8 FF000524 */   addiu     $a1, $zero, 0xFF
/* 74E04FC 800847CC 40100200 */  sll        $v0, $v0, 1
/* 74E0500 800847D0 7800A0AF */  sw         $zero, 0x78($sp)
/* 74E0504 800847D4 0680013C */  lui        $at, %hi(D_80065920)
/* 74E0508 800847D8 21082200 */  addu       $at, $at, $v0
/* 74E050C 800847DC 20592484 */  lh         $a0, %lo(D_80065920)($at)
/* 74E0510 800847E0 00000000 */  nop
/* 74E0514 800847E4 80180400 */  sll        $v1, $a0, 2
/* 74E0518 800847E8 21186400 */  addu       $v1, $v1, $a0
/* 74E051C 800847EC 031A0300 */  sra        $v1, $v1, 8
/* 74E0520 800847F0 7C00A3AF */  sw         $v1, 0x7C($sp)
/* 74E0524 800847F4 0680013C */  lui        $at, %hi(D_800658A0)
/* 74E0528 800847F8 21082200 */  addu       $at, $at, $v0
/* 74E052C 800847FC A0582384 */  lh         $v1, %lo(D_800658A0)($at)
/* 74E0530 80084800 00000000 */  nop
/* 74E0534 80084804 80100300 */  sll        $v0, $v1, 2
/* 74E0538 80084808 21104300 */  addu       $v0, $v0, $v1
/* 74E053C 8008480C 03120200 */  sra        $v0, $v0, 8
/* 74E0540 80084810 9171010C */  jal        func_8005C644
/* 74E0544 80084814 8000A2AF */   sw        $v0, 0x80($sp)
/* 74E0548 80084818 01004230 */  andi       $v0, $v0, 0x1
/* 74E054C 8008481C 03004010 */  beqz       $v0, .Llevel_34_8008482C
/* 74E0550 80084820 21206002 */   addu      $a0, $s3, $zero
/* 74E0554 80084824 0C120208 */  j          .Llevel_34_80084830
/* 74E0558 80084828 21282002 */   addu      $a1, $s1, $zero
.Llevel_34_8008482C:
/* 74E055C 8008482C 21280002 */  addu       $a1, $s0, $zero
.Llevel_34_80084830:
/* 74E0560 80084830 5E3C010C */  jal        func_8004F178
/* 74E0564 80084834 00000000 */   nop
/* 74E0568 80084838 21204002 */  addu       $a0, $s2, $zero
/* 74E056C 8008483C 21280000 */  addu       $a1, $zero, $zero
/* 74E0570 80084840 21300000 */  addu       $a2, $zero, $zero
/* 74E0574 80084844 003F073C */  lui        $a3, (0x3F004040 >> 16)
/* 74E0578 80084848 4040E734 */  ori        $a3, $a3, (0x3F004040 & 0xFFFF)
/* 74E057C 8008484C 0780033C */  lui        $v1, %hi(unk_ovlheader_800743B4)
/* 74E0580 80084850 B443638C */  lw         $v1, %lo(unk_ovlheader_800743B4)($v1)
/* 74E0584 80084854 FE000224 */  addiu      $v0, $zero, 0xFE
/* 74E0588 80084858 1000A2AF */  sw         $v0, 0x10($sp)
/* 74E058C 8008485C 5F000224 */  addiu      $v0, $zero, 0x5F
/* 74E0590 80084860 1400A2AF */  sw         $v0, 0x14($sp)
/* 74E0594 80084864 08000224 */  addiu      $v0, $zero, 0x8
/* 74E0598 80084868 1800A2AF */  sw         $v0, 0x18($sp)
/* 74E059C 8008486C 03000224 */  addiu      $v0, $zero, 0x3
/* 74E05A0 80084870 1C00A2AF */  sw         $v0, 0x1C($sp)
/* 74E05A4 80084874 8800A227 */  addiu      $v0, $sp, 0x88
/* 74E05A8 80084878 2000A2AF */  sw         $v0, 0x20($sp)
/* 74E05AC 8008487C 7800A227 */  addiu      $v0, $sp, 0x78
/* 74E05B0 80084880 09F86000 */  jalr       $v1
/* 74E05B4 80084884 2400A2AF */   sw        $v0, 0x24($sp)
/* 74E05B8 80084888 0900822A */  slti       $v0, $s4, 0x9
/* 74E05BC 8008488C 30004014 */  bnez       $v0, .Llevel_34_80084950
/* 74E05C0 80084890 00000000 */   nop
/* 74E05C4 80084894 5800A28E */  lw         $v0, 0x58($s5)
/* 74E05C8 80084898 00000000 */  nop
/* 74E05CC 8008489C 08004014 */  bnez       $v0, .Llevel_34_800848C0
/* 74E05D0 800848A0 21200000 */   addu      $a0, $zero, $zero
/* 74E05D4 800848A4 CF010424 */  addiu      $a0, $zero, 0x1CF
/* 74E05D8 800848A8 0780023C */  lui        $v0, %hi(SpawnMoby)
/* 74E05DC 800848AC E042428C */  lw         $v0, %lo(SpawnMoby)($v0)
/* 74E05E0 800848B0 00000000 */  nop
/* 74E05E4 800848B4 09F84000 */  jalr       $v0
/* 74E05E8 800848B8 21284002 */   addu      $a1, $s2, $zero
/* 74E05EC 800848BC 21204000 */  addu       $a0, $v0, $zero
.Llevel_34_800848C0:
/* 74E05F0 800848C0 0D008010 */  beqz       $a0, .Llevel_34_800848F8
/* 74E05F4 800848C4 003F023C */   lui       $v0, (0x3F00FFFF >> 16)
/* 74E05F8 800848C8 FFFF4234 */  ori        $v0, $v0, (0x3F00FFFF & 0xFFFF)
/* 74E05FC 800848CC 540082AC */  sw         $v0, 0x54($a0)
/* 74E0600 800848D0 FE000224 */  addiu      $v0, $zero, 0xFE
/* 74E0604 800848D4 4F0082A0 */  sb         $v0, 0x4F($a0)
/* 74E0608 800848D8 02000224 */  addiu      $v0, $zero, 0x2
/* 74E060C 800848DC 480082A0 */  sb         $v0, 0x48($a0)
/* 74E0610 800848E0 46004292 */  lbu        $v0, 0x46($s2)
/* 74E0614 800848E4 0000838C */  lw         $v1, 0x0($a0)
/* 74E0618 800848E8 460082A0 */  sb         $v0, 0x46($a0)
/* 74E061C 800848EC FFFF0224 */  addiu      $v0, $zero, -0x1
/* 74E0620 800848F0 060062A4 */  sh         $v0, 0x6($v1)
/* 74E0624 800848F4 5800A4AE */  sw         $a0, 0x58($s5)
.Llevel_34_800848F8:
/* 74E0628 800848F8 5800B18E */  lw         $s1, 0x58($s5)
/* 74E062C 800848FC 00000000 */  nop
/* 74E0630 80084900 13002012 */  beqz       $s1, .Llevel_34_80084950
/* 74E0634 80084904 0C003026 */   addiu     $s0, $s1, 0xC
/* 74E0638 80084908 21200002 */  addu       $a0, $s0, $zero
/* 74E063C 8008490C 9800A527 */  addiu      $a1, $sp, 0x98
/* 74E0640 80084910 653C010C */  jal        func_8004F194
/* 74E0644 80084914 A800A627 */   addiu     $a2, $sp, 0xA8
/* 74E0648 80084918 21200002 */  addu       $a0, $s0, $zero
/* 74E064C 8008491C 443C010C */  jal        func_8004F110
/* 74E0650 80084920 01000524 */   addiu     $a1, $zero, 0x1
/* 74E0654 80084924 4F002392 */  lbu        $v1, 0x4F($s1)
/* 74E0658 80084928 00000000 */  nop
/* 74E065C 8008492C 3D00622C */  sltiu      $v0, $v1, 0x3D
/* 74E0660 80084930 07004014 */  bnez       $v0, .Llevel_34_80084950
/* 74E0664 80084934 EFFF6224 */   addiu     $v0, $v1, -0x11
/* 74E0668 80084938 4F0022A2 */  sb         $v0, 0x4F($s1)
/* 74E066C 8008493C FF004230 */  andi       $v0, $v0, 0xFF
/* 74E0670 80084940 3C00422C */  sltiu      $v0, $v0, 0x3C
/* 74E0674 80084944 02004010 */  beqz       $v0, .Llevel_34_80084950
/* 74E0678 80084948 3C000224 */   addiu     $v0, $zero, 0x3C
/* 74E067C 8008494C 4F0022A2 */  sb         $v0, 0x4F($s1)
.Llevel_34_80084950:
/* 74E0680 80084950 5000A28E */  lw         $v0, 0x50($s5)
/* 74E0684 80084954 00000000 */  nop
/* 74E0688 80084958 07004014 */  bnez       $v0, .Llevel_34_80084978
/* 74E068C 8008495C 01000424 */   addiu     $a0, $zero, 0x1
/* 74E0690 80084960 80000524 */  addiu      $a1, $zero, 0x80
/* 74E0694 80084964 4800063C */  lui        $a2, (0x489090 >> 16)
/* 74E0698 80084968 14BB000C */  jal        func_8002EC50
/* 74E069C 8008496C 9090C634 */   ori       $a2, $a2, (0x489090 & 0xFFFF)
/* 74E06A0 80084970 27004010 */  beqz       $v0, .Llevel_34_80084A10
/* 74E06A4 80084974 5000A2AE */   sw        $v0, 0x50($s5)
.Llevel_34_80084978:
/* 74E06A8 80084978 5000A48E */  lw         $a0, 0x50($s5)
/* 74E06AC 8008497C 00000000 */  nop
/* 74E06B0 80084980 11008390 */  lbu        $v1, 0x11($a0)
/* 74E06B4 80084984 00000000 */  nop
/* 74E06B8 80084988 F300622C */  sltiu      $v0, $v1, 0xF3
/* 74E06BC 8008498C 02004010 */  beqz       $v0, .Llevel_34_80084998
/* 74E06C0 80084990 0C006224 */   addiu     $v0, $v1, 0xC
/* 74E06C4 80084994 110082A0 */  sb         $v0, 0x11($a0)
.Llevel_34_80084998:
/* 74E06C8 80084998 0600822A */  slti       $v0, $s4, 0x6
/* 74E06CC 8008499C 16004014 */  bnez       $v0, .Llevel_34_800849F8
/* 74E06D0 800849A0 7800B027 */   addiu     $s0, $sp, 0x78
/* 74E06D4 800849A4 21200002 */  addu       $a0, $s0, $zero
/* 74E06D8 800849A8 A800A527 */  addiu      $a1, $sp, 0xA8
/* 74E06DC 800849AC 9800B127 */  addiu      $s1, $sp, 0x98
/* 74E06E0 800849B0 723C010C */  jal        func_8004F1C8
/* 74E06E4 800849B4 21302002 */   addu      $a2, $s1, $zero
/* 74E06E8 800849B8 21200002 */  addu       $a0, $s0, $zero
/* 74E06EC 800849BC 7A3B010C */  jal        func_8004EDE8
/* 74E06F0 800849C0 01000524 */   addiu     $a1, $zero, 0x1
/* 74E06F4 800849C4 21200002 */  addu       $a0, $s0, $zero
/* 74E06F8 800849C8 21284000 */  addu       $a1, $v0, $zero
/* 74E06FC 800849CC FBFF8226 */  addiu      $v0, $s4, -0x5
/* 74E0700 800849D0 80300200 */  sll        $a2, $v0, 2
/* 74E0704 800849D4 2130C200 */  addu       $a2, $a2, $v0
/* 74E0708 800849D8 233C010C */  jal        func_8004F08C
/* 74E070C 800849DC 40300600 */   sll       $a2, $a2, 1
/* 74E0710 800849E0 5000A48E */  lw         $a0, 0x50($s5)
/* 74E0714 800849E4 21282002 */  addu       $a1, $s1, $zero
/* 74E0718 800849E8 653C010C */  jal        func_8004F194
/* 74E071C 800849EC 21300002 */   addu      $a2, $s0, $zero
/* 74E0720 800849F0 81120208 */  j          .Llevel_34_80084A04
/* 74E0724 800849F4 00000000 */   nop
.Llevel_34_800849F8:
/* 74E0728 800849F8 5000A48E */  lw         $a0, 0x50($s5)
/* 74E072C 800849FC 5E3C010C */  jal        func_8004F178
/* 74E0730 80084A00 9800A527 */   addiu     $a1, $sp, 0x98
.Llevel_34_80084A04:
/* 74E0734 80084A04 5000A38E */  lw         $v1, 0x50($s5)
/* 74E0738 80084A08 08000224 */  addiu      $v0, $zero, 0x8
/* 74E073C 80084A0C 130062A0 */  sb         $v0, 0x13($v1)
.Llevel_34_80084A10:
/* 74E0740 80084A10 5400A28E */  lw         $v0, 0x54($s5)
/* 74E0744 80084A14 00000000 */  nop
/* 74E0748 80084A18 07004014 */  bnez       $v0, .Llevel_34_80084A38
/* 74E074C 80084A1C 01000424 */   addiu     $a0, $zero, 0x1
/* 74E0750 80084A20 80000524 */  addiu      $a1, $zero, 0x80
/* 74E0754 80084A24 4800063C */  lui        $a2, (0x489090 >> 16)
/* 74E0758 80084A28 14BB000C */  jal        func_8002EC50
/* 74E075C 80084A2C 9090C634 */   ori       $a2, $a2, (0x489090 & 0xFFFF)
/* 74E0760 80084A30 27004010 */  beqz       $v0, .Llevel_34_80084AD0
/* 74E0764 80084A34 5400A2AE */   sw        $v0, 0x54($s5)
.Llevel_34_80084A38:
/* 74E0768 80084A38 5400A48E */  lw         $a0, 0x54($s5)
/* 74E076C 80084A3C 00000000 */  nop
/* 74E0770 80084A40 11008390 */  lbu        $v1, 0x11($a0)
/* 74E0774 80084A44 00000000 */  nop
/* 74E0778 80084A48 F300622C */  sltiu      $v0, $v1, 0xF3
/* 74E077C 80084A4C 02004010 */  beqz       $v0, .Llevel_34_80084A58
/* 74E0780 80084A50 0C006224 */   addiu     $v0, $v1, 0xC
/* 74E0784 80084A54 110082A0 */  sb         $v0, 0x11($a0)
.Llevel_34_80084A58:
/* 74E0788 80084A58 0600822A */  slti       $v0, $s4, 0x6
/* 74E078C 80084A5C 16004014 */  bnez       $v0, .Llevel_34_80084AB8
/* 74E0790 80084A60 7800B027 */   addiu     $s0, $sp, 0x78
/* 74E0794 80084A64 21200002 */  addu       $a0, $s0, $zero
/* 74E0798 80084A68 9800A527 */  addiu      $a1, $sp, 0x98
/* 74E079C 80084A6C A800B127 */  addiu      $s1, $sp, 0xA8
/* 74E07A0 80084A70 723C010C */  jal        func_8004F1C8
/* 74E07A4 80084A74 21302002 */   addu      $a2, $s1, $zero
/* 74E07A8 80084A78 21200002 */  addu       $a0, $s0, $zero
/* 74E07AC 80084A7C 7A3B010C */  jal        func_8004EDE8
/* 74E07B0 80084A80 01000524 */   addiu     $a1, $zero, 0x1
/* 74E07B4 80084A84 21200002 */  addu       $a0, $s0, $zero
/* 74E07B8 80084A88 21284000 */  addu       $a1, $v0, $zero
/* 74E07BC 80084A8C FBFF8226 */  addiu      $v0, $s4, -0x5
/* 74E07C0 80084A90 80300200 */  sll        $a2, $v0, 2
/* 74E07C4 80084A94 2130C200 */  addu       $a2, $a2, $v0
/* 74E07C8 80084A98 233C010C */  jal        func_8004F08C
/* 74E07CC 80084A9C 40300600 */   sll       $a2, $a2, 1
/* 74E07D0 80084AA0 5400A48E */  lw         $a0, 0x54($s5)
/* 74E07D4 80084AA4 21282002 */  addu       $a1, $s1, $zero
/* 74E07D8 80084AA8 653C010C */  jal        func_8004F194
/* 74E07DC 80084AAC 21300002 */   addu      $a2, $s0, $zero
/* 74E07E0 80084AB0 B1120208 */  j          .Llevel_34_80084AC4
/* 74E07E4 80084AB4 00000000 */   nop
.Llevel_34_80084AB8:
/* 74E07E8 80084AB8 5400A48E */  lw         $a0, 0x54($s5)
/* 74E07EC 80084ABC 5E3C010C */  jal        func_8004F178
/* 74E07F0 80084AC0 A800A527 */   addiu     $a1, $sp, 0xA8
.Llevel_34_80084AC4:
/* 74E07F4 80084AC4 5400A38E */  lw         $v1, 0x54($s5)
/* 74E07F8 80084AC8 08000224 */  addiu      $v0, $zero, 0x8
/* 74E07FC 80084ACC 130062A0 */  sb         $v0, 0x13($v1)
.Llevel_34_80084AD0:
/* 74E0800 80084AD0 0780023C */  lui        $v0, %hi(D_8006C770)
/* 74E0804 80084AD4 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 74E0808 80084AD8 00000000 */  nop
/* 74E080C 80084ADC 91004010 */  beqz       $v0, .Llevel_34_80084D24
/* 74E0810 80084AE0 CF010424 */   addiu     $a0, $zero, 0x1CF
/* 74E0814 80084AE4 0780023C */  lui        $v0, %hi(SpawnMoby)
/* 74E0818 80084AE8 E042428C */  lw         $v0, %lo(SpawnMoby)($v0)
/* 74E081C 80084AEC 00000000 */  nop
/* 74E0820 80084AF0 09F84000 */  jalr       $v0
/* 74E0824 80084AF4 21284002 */   addu      $a1, $s2, $zero
/* 74E0828 80084AF8 5000A38E */  lw         $v1, 0x50($s5)
/* 74E082C 80084AFC 00000000 */  nop
/* 74E0830 80084B00 03006010 */  beqz       $v1, .Llevel_34_80084B10
/* 74E0834 80084B04 21A04000 */   addu      $s4, $v0, $zero
/* 74E0838 80084B08 100060A0 */  sb         $zero, 0x10($v1)
/* 74E083C 80084B0C 5000A0AE */  sw         $zero, 0x50($s5)
.Llevel_34_80084B10:
/* 74E0840 80084B10 5400A28E */  lw         $v0, 0x54($s5)
/* 74E0844 80084B14 00000000 */  nop
/* 74E0848 80084B18 03004010 */  beqz       $v0, .Llevel_34_80084B28
/* 74E084C 80084B1C 00000000 */   nop
/* 74E0850 80084B20 100040A0 */  sb         $zero, 0x10($v0)
/* 74E0854 80084B24 5400A0AE */  sw         $zero, 0x54($s5)
.Llevel_34_80084B28:
/* 74E0858 80084B28 5800A48E */  lw         $a0, 0x58($s5)
/* 74E085C 80084B2C 00000000 */  nop
/* 74E0860 80084B30 04008010 */  beqz       $a0, .Llevel_34_80084B44
/* 74E0864 80084B34 00000000 */   nop
/* 74E0868 80084B38 C656010C */  jal        func_80055B18
/* 74E086C 80084B3C 00000000 */   nop
/* 74E0870 80084B40 5800A0AE */  sw         $zero, 0x58($s5)
.Llevel_34_80084B44:
/* 74E0874 80084B44 3F008012 */  beqz       $s4, .Llevel_34_80084C44
/* 74E0878 80084B48 21204002 */   addu      $a0, $s2, $zero
/* 74E087C 80084B4C 21280000 */  addu       $a1, $zero, $zero
/* 74E0880 80084B50 B800B127 */  addiu      $s1, $sp, 0xB8
/* 74E0884 80084B54 0000938E */  lw         $s3, 0x0($s4)
/* 74E0888 80084B58 C557010C */  jal        func_80055F14
/* 74E088C 80084B5C 21302002 */   addu      $a2, $s1, $zero
/* 74E0890 80084B60 21204002 */  addu       $a0, $s2, $zero
/* 74E0894 80084B64 01000524 */  addiu      $a1, $zero, 0x1
/* 74E0898 80084B68 C800B027 */  addiu      $s0, $sp, 0xC8
/* 74E089C 80084B6C C557010C */  jal        func_80055F14
/* 74E08A0 80084B70 21300002 */   addu      $a2, $s0, $zero
/* 74E08A4 80084B74 0C009626 */  addiu      $s6, $s4, 0xC
/* 74E08A8 80084B78 2120C002 */  addu       $a0, $s6, $zero
/* 74E08AC 80084B7C 21282002 */  addu       $a1, $s1, $zero
/* 74E08B0 80084B80 653C010C */  jal        func_8004F194
/* 74E08B4 80084B84 21300002 */   addu      $a2, $s0, $zero
/* 74E08B8 80084B88 2120C002 */  addu       $a0, $s6, $zero
/* 74E08BC 80084B8C 443C010C */  jal        func_8004F110
/* 74E08C0 80084B90 01000524 */   addiu     $a1, $zero, 0x1
/* 74E08C4 80084B94 003F023C */  lui        $v0, (0x3F00FFFF >> 16)
/* 74E08C8 80084B98 FFFF4234 */  ori        $v0, $v0, (0x3F00FFFF & 0xFFFF)
/* 74E08CC 80084B9C 2120C002 */  addu       $a0, $s6, $zero
/* 74E08D0 80084BA0 540082AE */  sw         $v0, 0x54($s4)
/* 74E08D4 80084BA4 3C000224 */  addiu      $v0, $zero, 0x3C
/* 74E08D8 80084BA8 4F0082A2 */  sb         $v0, 0x4F($s4)
/* 74E08DC 80084BAC 46004292 */  lbu        $v0, 0x46($s2)
/* 74E08E0 80084BB0 0780053C */  lui        $a1, %hi(D_80070328)
/* 74E08E4 80084BB4 2803A524 */  addiu      $a1, $a1, %lo(D_80070328)
/* 74E08E8 80084BB8 460082A2 */  sb         $v0, 0x46($s4)
/* 74E08EC 80084BBC 64000224 */  addiu      $v0, $zero, 0x64
/* 74E08F0 80084BC0 040062A6 */  sh         $v0, 0x4($s3)
/* 74E08F4 80084BC4 0600E396 */  lhu        $v1, 0x6($s7)
/* 74E08F8 80084BC8 01000224 */  addiu      $v0, $zero, 0x1
/* 74E08FC 80084BCC 160062A2 */  sb         $v0, 0x16($s3)
/* 74E0900 80084BD0 FFFF0224 */  addiu      $v0, $zero, -0x1
/* 74E0904 80084BD4 060062A6 */  sh         $v0, 0x6($s3)
/* 74E0908 80084BD8 32006324 */  addiu      $v1, $v1, 0x32
/* 74E090C 80084BDC CD3C010C */  jal        func_8004F334
/* 74E0910 80084BE0 140063A6 */   sh        $v1, 0x14($s3)
/* 74E0914 80084BE4 21204000 */  addu       $a0, $v0, $zero
/* 74E0918 80084BE8 0780023C */  lui        $v0, %hi(D_80070328 + 8)
/* 74E091C 80084BEC 3003428C */  lw         $v0, %lo(D_80070328 + 8)($v0)
/* 74E0920 80084BF0 1400858E */  lw         $a1, 0x14($s4)
/* 74E0924 80084BF4 21300000 */  addu       $a2, $zero, $zero
/* 74E0928 80084BF8 203A010C */  jal        func_8004E880
/* 74E092C 80084BFC 23284500 */   subu      $a1, $v0, $a1
/* 74E0930 80084C00 450082A2 */  sb         $v0, 0x45($s4)
/* 74E0934 80084C04 0000628E */  lw         $v0, 0x0($s3)
/* 74E0938 80084C08 00000000 */  nop
/* 74E093C 80084C0C 07004014 */  bnez       $v0, .Llevel_34_80084C2C
/* 74E0940 80084C10 01000424 */   addiu     $a0, $zero, 0x1
/* 74E0944 80084C14 FE000524 */  addiu      $a1, $zero, 0xFE
/* 74E0948 80084C18 4800063C */  lui        $a2, (0x489090 >> 16)
/* 74E094C 80084C1C 14BB000C */  jal        func_8002EC50
/* 74E0950 80084C20 9090C634 */   ori       $a2, $a2, (0x489090 & 0xFFFF)
/* 74E0954 80084C24 07004010 */  beqz       $v0, .Llevel_34_80084C44
/* 74E0958 80084C28 000062AE */   sw        $v0, 0x0($s3)
.Llevel_34_80084C2C:
/* 74E095C 80084C2C 0000648E */  lw         $a0, 0x0($s3)
/* 74E0960 80084C30 5E3C010C */  jal        func_8004F178
/* 74E0964 80084C34 2128C002 */   addu      $a1, $s6, $zero
/* 74E0968 80084C38 0000638E */  lw         $v1, 0x0($s3)
/* 74E096C 80084C3C 08000224 */  addiu      $v0, $zero, 0x8
/* 74E0970 80084C40 130062A0 */  sb         $v0, 0x13($v1)
.Llevel_34_80084C44:
/* 74E0974 80084C44 21204002 */  addu       $a0, $s2, $zero
/* 74E0978 80084C48 21280000 */  addu       $a1, $zero, $zero
/* 74E097C 80084C4C 16000224 */  addiu      $v0, $zero, 0x16
/* 74E0980 80084C50 480082A0 */  sb         $v0, 0x48($a0)
/* 74E0984 80084C54 01000224 */  addiu      $v0, $zero, 0x1
/* 74E0988 80084C58 D0D3000C */  jal        func_80034F40
/* 74E098C 80084C5C 490082A0 */   sb        $v0, 0x49($a0)
/* 74E0990 80084C60 49130208 */  j          .Llevel_34_80084D24
/* 74E0994 80084C64 0600A0A6 */   sh        $zero, 0x6($s5)
.L80084C68_:
/* 74E0998 80084C68 21204002 */  addu       $a0, $s2, $zero
/* 74E099C 80084C6C 64000624 */  addiu      $a2, $zero, 0x64
/* 74E09A0 80084C70 0400E386 */  lh         $v1, 0x4($s7)
/* 74E09A4 80084C74 1400428E */  lw         $v0, 0x14($s2)
/* 74E09A8 80084C78 21380000 */  addu       $a3, $zero, $zero
/* 74E09AC 80084C7C 21104300 */  addu       $v0, $v0, $v1
/* 74E09B0 80084C80 140042AE */  sw         $v0, 0x14($s2)
/* 74E09B4 80084C84 0400E296 */  lhu        $v0, 0x4($s7)
/* 74E09B8 80084C88 0200E586 */  lh         $a1, 0x2($s7)
/* 74E09BC 80084C8C F0FF4224 */  addiu      $v0, $v0, -0x10
/* 74E09C0 80084C90 0400E2A6 */  sh         $v0, 0x4($s7)
/* 74E09C4 80084C94 1000A0AF */  sw         $zero, 0x10($sp)
/* 74E09C8 80084C98 B8D7000C */  jal        func_80035EE0
/* 74E09CC 80084C9C 1400A0AF */   sw        $zero, 0x14($sp)
/* 74E09D0 80084CA0 2120E002 */  addu       $a0, $s7, $zero
/* 74E09D4 80084CA4 69D6000C */  jal        func_800359A4
/* 74E09D8 80084CA8 02000524 */   addiu     $a1, $zero, 0x2
/* 74E09DC 80084CAC 0D004014 */  bnez       $v0, .Llevel_34_80084CE4
/* 74E09E0 80084CB0 21204002 */   addu      $a0, $s2, $zero
/* 74E09E4 80084CB4 0400E286 */  lh         $v0, 0x4($s7)
/* 74E09E8 80084CB8 00000000 */  nop
/* 74E09EC 80084CBC 0F004104 */  bgez       $v0, .Llevel_34_80084CFC
/* 74E09F0 80084CC0 0C004426 */   addiu     $a0, $s2, 0xC
/* 74E09F4 80084CC4 58020524 */  addiu      $a1, $zero, 0x258
/* 74E09F8 80084CC8 01000624 */  addiu      $a2, $zero, 0x1
/* 74E09FC 80084CCC 21380000 */  addu       $a3, $zero, $zero
/* 74E0A00 80084CD0 1000A0AF */  sw         $zero, 0x10($sp)
/* 74E0A04 80084CD4 4E64000C */  jal        func_80019138
/* 74E0A08 80084CD8 1400A0AF */   sw        $zero, 0x14($sp)
/* 74E0A0C 80084CDC 07004010 */  beqz       $v0, .Llevel_34_80084CFC
/* 74E0A10 80084CE0 21204002 */   addu      $a0, $s2, $zero
.Llevel_34_80084CE4:
/* 74E0A14 80084CE4 6EDA000C */  jal        func_800369B8
/* 74E0A18 80084CE8 28000524 */   addiu     $a1, $zero, 0x28
.Llevel_34_80084CEC:
/* 74E0A1C 80084CEC C656010C */  jal        func_80055B18
/* 74E0A20 80084CF0 21204002 */   addu      $a0, $s2, $zero
/* 74E0A24 80084CF4 49130208 */  j          .Llevel_34_80084D24
/* 74E0A28 80084CF8 00000000 */   nop
.Llevel_34_80084CFC:
/* 74E0A2C 80084CFC 3D004392 */  lbu        $v1, 0x3D($s2)
/* 74E0A30 80084D00 04000224 */  addiu      $v0, $zero, 0x4
/* 74E0A34 80084D04 07006214 */  bne        $v1, $v0, .Llevel_34_80084D24
/* 74E0A38 80084D08 00000000 */   nop
/* 74E0A3C 80084D0C 45004292 */  lbu        $v0, 0x45($s2)
/* 74E0A40 80084D10 44004392 */  lbu        $v1, 0x44($s2)
/* 74E0A44 80084D14 06004224 */  addiu      $v0, $v0, 0x6
/* 74E0A48 80084D18 01006324 */  addiu      $v1, $v1, 0x1
/* 74E0A4C 80084D1C 450042A2 */  sb         $v0, 0x45($s2)
/* 74E0A50 80084D20 440043A2 */  sb         $v1, 0x44($s2)
.Llevel_34_80084D24:
/* 74E0A54 80084D24 F800BF8F */  lw         $ra, 0xF8($sp)
/* 74E0A58 80084D28 F400B78F */  lw         $s7, 0xF4($sp)
/* 74E0A5C 80084D2C F000B68F */  lw         $s6, 0xF0($sp)
/* 74E0A60 80084D30 EC00B58F */  lw         $s5, 0xEC($sp)
/* 74E0A64 80084D34 E800B48F */  lw         $s4, 0xE8($sp)
/* 74E0A68 80084D38 E400B38F */  lw         $s3, 0xE4($sp)
/* 74E0A6C 80084D3C E000B28F */  lw         $s2, 0xE0($sp)
/* 74E0A70 80084D40 DC00B18F */  lw         $s1, 0xDC($sp)
/* 74E0A74 80084D44 D800B08F */  lw         $s0, 0xD8($sp)
/* 74E0A78 80084D48 0001BD27 */  addiu      $sp, $sp, 0x100
/* 74E0A7C 80084D4C 0800E003 */  jr         $ra
/* 74E0A80 80084D50 00000000 */   nop
.size func_level_34_80083834, . - func_level_34_80083834
