.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_44_8007548C
/* 8B489BC 8007548C B8380980 */ .word .L800938B8_
/* 8B489C0 80075490 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B489C4 80075494 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B489C8 80075498 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B489CC 8007549C 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B489D0 800754A0 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B489D4 800754A4 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B489D8 800754A8 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B489DC 800754AC 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B489E0 800754B0 08390980 */ .word .L80093908_
/* 8B489E4 800754B4 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B489E8 800754B8 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B489EC 800754BC 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B489F0 800754C0 70390980 */ .word .L80093970_
/* 8B489F4 800754C4 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B489F8 800754C8 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B489FC 800754CC 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A00 800754D0 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A04 800754D4 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A08 800754D8 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A0C 800754DC 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A10 800754E0 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A14 800754E4 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A18 800754E8 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A1C 800754EC 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A20 800754F0 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A24 800754F4 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A28 800754F8 083A0980 */ .word .L80093A08_
/* 8B48A2C 800754FC 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A30 80075500 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A34 80075504 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A38 80075508 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A3C 8007550C 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A40 80075510 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A44 80075514 9C3A0980 */ .word .Llevel_44_80093A9C
/* 8B48A48 80075518 B8380980 */ .word .L800938B8_
.size jtbl_level_44_8007548C, . - jtbl_level_44_8007548C


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_44_8009387C
/* 8B66DAC 8009387C E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 8B66DB0 80093880 FCFF8424 */  addiu      $a0, $a0, -0x4
/* 8B66DB4 80093884 2400822C */  sltiu      $v0, $a0, 0x24
/* 8B66DB8 80093888 1C00BFAF */  sw         $ra, 0x1C($sp)
/* 8B66DBC 8009388C 1800B2AF */  sw         $s2, 0x18($sp)
/* 8B66DC0 80093890 1400B1AF */  sw         $s1, 0x14($sp)
/* 8B66DC4 80093894 81004010 */  beqz       $v0, .Llevel_44_80093A9C
/* 8B66DC8 80093898 1000B0AF */   sw        $s0, 0x10($sp)
/* 8B66DCC 8009389C 80100400 */  sll        $v0, $a0, 2
/* 8B66DD0 800938A0 0780013C */  lui        $at, %hi(jtbl_level_44_8007548C)
/* 8B66DD4 800938A4 21082200 */  addu       $at, $at, $v0
/* 8B66DD8 800938A8 8C54228C */  lw         $v0, %lo(jtbl_level_44_8007548C)($at)
/* 8B66DDC 800938AC 00000000 */  nop
/* 8B66DE0 800938B0 08004000 */  jr         $v0
/* 8B66DE4 800938B4 00000000 */   nop
.L800938B8_:
/* 8B66DE8 800938B8 0780103C */  lui        $s0, %hi(D_8006E048)
/* 8B66DEC 800938BC 48E01026 */  addiu      $s0, $s0, %lo(D_8006E048)
/* 8B66DF0 800938C0 01000224 */  addiu      $v0, $zero, 0x1
/* 8B66DF4 800938C4 000000AE */  sw         $zero, 0x0($s0)
/* 8B66DF8 800938C8 0780013C */  lui        $at, %hi(D_8006E138)
/* 8B66DFC 800938CC 38E120A0 */  sb         $zero, %lo(D_8006E138)($at)
/* 8B66E00 800938D0 0780013C */  lui        $at, %hi(D_8006E139)
/* 8B66E04 800938D4 39E120A0 */  sb         $zero, %lo(D_8006E139)($at)
/* 8B66E08 800938D8 0780013C */  lui        $at, %hi(D_8006E13A)
/* 8B66E0C 800938DC 3AE122A0 */  sb         $v0, %lo(D_8006E13A)($at)
/* 8B66E10 800938E0 0780013C */  lui        $at, %hi(D_8006E13D)
/* 8B66E14 800938E4 3DE120A0 */  sb         $zero, %lo(D_8006E13D)($at)
/* 8B66E18 800938E8 0780013C */  lui        $at, %hi(D_8006E054)
/* 8B66E1C 800938EC 54E020A0 */  sb         $zero, %lo(D_8006E054)($at)
/* 8B66E20 800938F0 B850000C */  jal        func_800142E0
/* 8B66E24 800938F4 2C001126 */   addiu     $s1, $s0, 0x2C
/* 8B66E28 800938F8 21202002 */  addu       $a0, $s1, $zero
/* 8B66E2C 800938FC D8FF0526 */  addiu      $a1, $s0, -0x28
/* 8B66E30 80093900 724E0208 */  j          .Llevel_44_800939C8
/* 8B66E34 80093904 10000626 */   addiu     $a2, $s0, 0x10
.L80093908_:
/* 8B66E38 80093908 0780103C */  lui        $s0, %hi(D_8006E048)
/* 8B66E3C 8009390C 48E01026 */  addiu      $s0, $s0, %lo(D_8006E048)
/* 8B66E40 80093910 01000224 */  addiu      $v0, $zero, 0x1
/* 8B66E44 80093914 000000AE */  sw         $zero, 0x0($s0)
/* 8B66E48 80093918 0780013C */  lui        $at, %hi(D_8006E138)
/* 8B66E4C 8009391C 38E120A0 */  sb         $zero, %lo(D_8006E138)($at)
/* 8B66E50 80093920 0780013C */  lui        $at, %hi(D_8006E139)
/* 8B66E54 80093924 39E122A0 */  sb         $v0, %lo(D_8006E139)($at)
/* 8B66E58 80093928 0780013C */  lui        $at, %hi(D_8006E13A)
/* 8B66E5C 8009392C 3AE122A0 */  sb         $v0, %lo(D_8006E13A)($at)
/* 8B66E60 80093930 0780013C */  lui        $at, %hi(D_8006E13D)
/* 8B66E64 80093934 3DE120A0 */  sb         $zero, %lo(D_8006E13D)($at)
/* 8B66E68 80093938 0780013C */  lui        $at, %hi(D_8006E054)
/* 8B66E6C 8009393C 54E020A0 */  sb         $zero, %lo(D_8006E054)($at)
/* 8B66E70 80093940 B850000C */  jal        func_800142E0
/* 8B66E74 80093944 2C001126 */   addiu     $s1, $s0, 0x2C
/* 8B66E78 80093948 21202002 */  addu       $a0, $s1, $zero
/* 8B66E7C 8009394C D8FF0526 */  addiu      $a1, $s0, -0x28
/* 8B66E80 80093950 BC4D000C */  jal        func_800136F0
/* 8B66E84 80093954 10000626 */   addiu     $a2, $s0, 0x10
/* 8B66E88 80093958 21202002 */  addu       $a0, $s1, $zero
/* 8B66E8C 8009395C 284E000C */  jal        func_800138A0
/* 8B66E90 80093960 21282002 */   addu      $a1, $s1, $zero
/* 8B66E94 80093964 54000426 */  addiu      $a0, $s0, 0x54
/* 8B66E98 80093968 7E4E0208 */  j          .Llevel_44_800939F8
/* 8B66E9C 8009396C 21282002 */   addu      $a1, $s1, $zero
.L80093970_:
/* 8B66EA0 80093970 0780113C */  lui        $s1, %hi(D_8006E048)
/* 8B66EA4 80093974 48E03126 */  addiu      $s1, $s1, %lo(D_8006E048)
/* 8B66EA8 80093978 10003226 */  addiu      $s2, $s1, 0x10
/* 8B66EAC 8009397C 21204002 */  addu       $a0, $s2, $zero
/* 8B66EB0 80093980 01000224 */  addiu      $v0, $zero, 0x1
/* 8B66EB4 80093984 000020AE */  sw         $zero, 0x0($s1)
/* 8B66EB8 80093988 0780013C */  lui        $at, %hi(D_8006E138)
/* 8B66EBC 8009398C 38E120A0 */  sb         $zero, %lo(D_8006E138)($at)
/* 8B66EC0 80093990 0780013C */  lui        $at, %hi(D_8006E139)
/* 8B66EC4 80093994 39E122A0 */  sb         $v0, %lo(D_8006E139)($at)
/* 8B66EC8 80093998 0780013C */  lui        $at, %hi(D_8006E13A)
/* 8B66ECC 8009399C 3AE122A0 */  sb         $v0, %lo(D_8006E13A)($at)
/* 8B66ED0 800939A0 0780013C */  lui        $at, %hi(D_8006E13D)
/* 8B66ED4 800939A4 3DE120A0 */  sb         $zero, %lo(D_8006E13D)($at)
/* 8B66ED8 800939A8 5E3C010C */  jal        func_8004F178
/* 8B66EDC 800939AC 34012526 */   addiu     $a1, $s1, 0x134
/* 8B66EE0 800939B0 2C003026 */  addiu      $s0, $s1, 0x2C
/* 8B66EE4 800939B4 21200002 */  addu       $a0, $s0, $zero
/* 8B66EE8 800939B8 D8FF2526 */  addiu      $a1, $s1, -0x28
/* 8B66EEC 800939BC 21304002 */  addu       $a2, $s2, $zero
/* 8B66EF0 800939C0 0780013C */  lui        $at, %hi(D_8006E064)
/* 8B66EF4 800939C4 64E020AC */  sw         $zero, %lo(D_8006E064)($at)
.Llevel_44_800939C8:
/* 8B66EF8 800939C8 BC4D000C */  jal        func_800136F0
/* 8B66EFC 800939CC 00000000 */   nop
/* 8B66F00 800939D0 0780043C */  lui        $a0, %hi(D_8006E074)
/* 8B66F04 800939D4 74E08424 */  addiu      $a0, $a0, %lo(D_8006E074)
/* 8B66F08 800939D8 0780053C */  lui        $a1, %hi(D_8006E074)
/* 8B66F0C 800939DC 74E0A524 */  addiu      $a1, $a1, %lo(D_8006E074)
/* 8B66F10 800939E0 284E000C */  jal        func_800138A0
/* 8B66F14 800939E4 00000000 */   nop
/* 8B66F18 800939E8 0780043C */  lui        $a0, %hi(D_8006E09C)
/* 8B66F1C 800939EC 9CE08424 */  addiu      $a0, $a0, %lo(D_8006E09C)
/* 8B66F20 800939F0 0780053C */  lui        $a1, %hi(D_8006E074)
/* 8B66F24 800939F4 74E0A524 */  addiu      $a1, $a1, %lo(D_8006E074)
.Llevel_44_800939F8:
/* 8B66F28 800939F8 694D000C */  jal        func_800135A4
/* 8B66F2C 800939FC 21300000 */   addu      $a2, $zero, $zero
/* 8B66F30 80093A00 A74E0208 */  j          .Llevel_44_80093A9C
/* 8B66F34 80093A04 00000000 */   nop
.L80093A08_:
/* 8B66F38 80093A08 0780023C */  lui        $v0, %hi(D_80070328 + 0x250)
/* 8B66F3C 80093A0C 7805428C */  lw         $v0, %lo(D_80070328 + 0x250)($v0)
/* 8B66F40 80093A10 0780033C */  lui        $v1, %hi(D_8006E140)
/* 8B66F44 80093A14 40E16324 */  addiu      $v1, $v1, %lo(D_8006E140)
/* 8B66F48 80093A18 0000508C */  lw         $s0, 0x0($v0)
/* 8B66F4C 80093A1C 0780023C */  lui        $v0, %hi(D_80070328 + 0x64)
/* 8B66F50 80093A20 8C03428C */  lw         $v0, %lo(D_80070328 + 0x64)($v0)
/* 8B66F54 80093A24 00000000 */  nop
/* 8B66F58 80093A28 000062AC */  sw         $v0, 0x0($v1)
/* 8B66F5C 80093A2C 0780013C */  lui        $at, %hi(D_8006E144)
/* 8B66F60 80093A30 44E120AC */  sw         $zero, %lo(D_8006E144)($at)
/* 8B66F64 80093A34 0780013C */  lui        $at, %hi(D_8006E158)
/* 8B66F68 80093A38 58E120AC */  sw         $zero, %lo(D_8006E158)($at)
/* 8B66F6C 80093A3C 0780013C */  lui        $at, %hi(D_8006E15C)
/* 8B66F70 80093A40 5CE120AC */  sw         $zero, %lo(D_8006E15C)($at)
/* 8B66F74 80093A44 404E000C */  jal        func_80013900
/* 8B66F78 80093A48 84FF6424 */   addiu     $a0, $v1, -0x7C
/* 8B66F7C 80093A4C 01000224 */  addiu      $v0, $zero, 0x1
/* 8B66F80 80093A50 0780013C */  lui        $at, %hi(D_8006E13D)
/* 8B66F84 80093A54 3DE122A0 */  sb         $v0, %lo(D_8006E13D)($at)
/* 8B66F88 80093A58 0780013C */  lui        $at, %hi(D_8006E138)
/* 8B66F8C 80093A5C 38E122A0 */  sb         $v0, %lo(D_8006E138)($at)
/* 8B66F90 80093A60 0780013C */  lui        $at, %hi(D_8006E139)
/* 8B66F94 80093A64 39E122A0 */  sb         $v0, %lo(D_8006E139)($at)
/* 8B66F98 80093A68 01000224 */  addiu      $v0, $zero, 0x1
/* 8B66F9C 80093A6C 0780013C */  lui        $at, %hi(D_8006C768)
/* 8B66FA0 80093A70 68C722AC */  sw         $v0, %lo(D_8006C768)($at)
/* 8B66FA4 80093A74 00020224 */  addiu      $v0, $zero, 0x200
/* 8B66FA8 80093A78 0780013C */  lui        $at, %hi(D_8006E12C)
/* 8B66FAC 80093A7C 2CE120AC */  sw         $zero, %lo(D_8006E12C)($at)
/* 8B66FB0 80093A80 0780013C */  lui        $at, %hi(D_8006E130)
/* 8B66FB4 80093A84 30E120AC */  sw         $zero, %lo(D_8006E130)($at)
/* 8B66FB8 80093A88 0780013C */  lui        $at, %hi(D_8006E054)
/* 8B66FBC 80093A8C 54E020A0 */  sb         $zero, %lo(D_8006E054)($at)
/* 8B66FC0 80093A90 500000AE */  sw         $zero, 0x50($s0)
/* 8B66FC4 80093A94 540000AE */  sw         $zero, 0x54($s0)
/* 8B66FC8 80093A98 580002AE */  sw         $v0, 0x58($s0)
.Llevel_44_80093A9C:
/* 8B66FCC 80093A9C 1C00BF8F */  lw         $ra, 0x1C($sp)
/* 8B66FD0 80093AA0 1800B28F */  lw         $s2, 0x18($sp)
/* 8B66FD4 80093AA4 1400B18F */  lw         $s1, 0x14($sp)
/* 8B66FD8 80093AA8 1000B08F */  lw         $s0, 0x10($sp)
/* 8B66FDC 80093AAC 2000BD27 */  addiu      $sp, $sp, 0x20
/* 8B66FE0 80093AB0 0800E003 */  jr         $ra
/* 8B66FE4 80093AB4 00000000 */   nop
.size func_level_44_8009387C, . - func_level_44_8009387C
