.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata.jtbl
.align 3
dlabel jtbl_cutscene_66_80074490
/* 12CA9C0 80074490 304A0780 */ .word .L80074A30_
/* 12CA9C4 80074494 B84A0780 */ .word .L80074AB8_
/* 12CA9C8 80074498 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CA9CC 8007449C B0560780 */ .word .Lcutscene_66_800756B0
/* 12CA9D0 800744A0 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CA9D4 800744A4 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CA9D8 800744A8 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CA9DC 800744AC B0560780 */ .word .Lcutscene_66_800756B0
/* 12CA9E0 800744B0 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CA9E4 800744B4 404B0780 */ .word .L80074B40_
/* 12CA9E8 800744B8 A44B0780 */ .word .L80074BA4_
/* 12CA9EC 800744BC AC4C0780 */ .word .L80074CAC_
/* 12CA9F0 800744C0 344D0780 */ .word .L80074D34_
/* 12CA9F4 800744C4 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CA9F8 800744C8 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CA9FC 800744CC B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA00 800744D0 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA04 800744D4 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA08 800744D8 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA0C 800744DC B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA10 800744E0 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA14 800744E4 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA18 800744E8 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA1C 800744EC B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA20 800744F0 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA24 800744F4 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA28 800744F8 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA2C 800744FC B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA30 80074500 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA34 80074504 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA38 80074508 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA3C 8007450C B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA40 80074510 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA44 80074514 AC4D0780 */ .word .L80074DAC_
/* 12CAA48 80074518 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA4C 8007451C B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA50 80074520 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA54 80074524 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA58 80074528 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA5C 8007452C B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA60 80074530 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA64 80074534 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA68 80074538 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA6C 8007453C B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA70 80074540 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA74 80074544 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA78 80074548 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA7C 8007454C B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA80 80074550 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA84 80074554 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA88 80074558 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA8C 8007455C B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA90 80074560 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA94 80074564 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA98 80074568 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAA9C 8007456C B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAAA0 80074570 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAAA4 80074574 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAAA8 80074578 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAAAC 8007457C 504E0780 */ .word .L80074E50_
/* 12CAAB0 80074580 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAAB4 80074584 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAAB8 80074588 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAABC 8007458C B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAAC0 80074590 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAAC4 80074594 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAAC8 80074598 F04E0780 */ .word .L80074EF0_
/* 12CAACC 8007459C B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAAD0 800745A0 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAAD4 800745A4 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAAD8 800745A8 DC4F0780 */ .word .L80074FDC_
/* 12CAADC 800745AC CC510780 */ .word .L800751CC_
/* 12CAAE0 800745B0 40530780 */ .word .L80075340_
/* 12CAAE4 800745B4 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAAE8 800745B8 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAAEC 800745BC B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAAF0 800745C0 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAAF4 800745C4 B0560780 */ .word .Lcutscene_66_800756B0
/* 12CAAF8 800745C8 7C540780 */ .word .L8007547C_
/* 12CAAFC 800745CC 7C550780 */ .word .L8007557C_
.size jtbl_cutscene_66_80074490, . - jtbl_cutscene_66_80074490


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_cutscene_66_80074960
/* 12CAE90 80074960 98FFBD27 */  addiu      $sp, $sp, -0x68
/* 12CAE94 80074964 4800B2AF */  sw         $s2, 0x48($sp)
/* 12CAE98 80074968 0780123C */  lui        $s2, %hi(D_8006C554)
/* 12CAE9C 8007496C 54C5528E */  lw         $s2, %lo(D_8006C554)($s2)
/* 12CAEA0 80074970 5800B6AF */  sw         $s6, 0x58($sp)
/* 12CAEA4 80074974 21B08000 */  addu       $s6, $a0, $zero
/* 12CAEA8 80074978 6000BFAF */  sw         $ra, 0x60($sp)
/* 12CAEAC 8007497C 5C00B7AF */  sw         $s7, 0x5C($sp)
/* 12CAEB0 80074980 5400B5AF */  sw         $s5, 0x54($sp)
/* 12CAEB4 80074984 5000B4AF */  sw         $s4, 0x50($sp)
/* 12CAEB8 80074988 4C00B3AF */  sw         $s3, 0x4C($sp)
/* 12CAEBC 8007498C 4400B1AF */  sw         $s1, 0x44($sp)
/* 12CAEC0 80074990 4000B0AF */  sw         $s0, 0x40($sp)
/* 12CAEC4 80074994 01004492 */  lbu        $a0, 0x1($s2)
/* 12CAEC8 80074998 FF000224 */  addiu      $v0, $zero, 0xFF
/* 12CAECC 8007499C FF008330 */  andi       $v1, $a0, 0xFF
/* 12CAED0 800749A0 4C036210 */  beq        $v1, $v0, .Lcutscene_66_800756D4
/* 12CAED4 800749A4 21104002 */   addu      $v0, $s2, $zero
/* 12CAED8 800749A8 40B81600 */  sll        $s7, $s6, 1
/* 12CAEDC 800749AC 80A81600 */  sll        $s5, $s6, 2
/* 12CAEE0 800749B0 01005026 */  addiu      $s0, $s2, 0x1
/* 12CAEE4 800749B4 18005426 */  addiu      $s4, $s2, 0x18
/* 12CAEE8 800749B8 04005326 */  addiu      $s3, $s2, 0x4
/* 12CAEEC 800749BC FF008330 */  andi       $v1, $a0, 0xFF
.Lcutscene_66_800749C0:
/* 12CAEF0 800749C0 FE000224 */  addiu      $v0, $zero, 0xFE
/* 12CAEF4 800749C4 3A036210 */  beq        $v1, $v0, .Lcutscene_66_800756B0
/* 12CAEF8 800749C8 04000224 */   addiu     $v0, $zero, 0x4
/* 12CAEFC 800749CC 0780033C */  lui        $v1, %hi(D_8006E344)
/* 12CAF00 800749D0 44E3638C */  lw         $v1, %lo(D_8006E344)($v1)
/* 12CAF04 800749D4 00000000 */  nop
/* 12CAF08 800749D8 0A006214 */  bne        $v1, $v0, .Lcutscene_66_80074A04
/* 12CAF0C 800749DC 42000224 */   addiu     $v0, $zero, 0x42
/* 12CAF10 800749E0 00004392 */  lbu        $v1, 0x0($s2)
/* 12CAF14 800749E4 00000000 */  nop
/* 12CAF18 800749E8 31036214 */  bne        $v1, $v0, .Lcutscene_66_800756B0
/* 12CAF1C 800749EC 00000000 */   nop
/* 12CAF20 800749F0 0780023C */  lui        $v0, %hi(D_8006C598)
/* 12CAF24 800749F4 98C5428C */  lw         $v0, %lo(D_8006C598)($v0)
/* 12CAF28 800749F8 00000000 */  nop
/* 12CAF2C 800749FC 17034014 */  bnez       $v0, .Lcutscene_66_8007565C
/* 12CAF30 80074A00 00000000 */   nop
.Lcutscene_66_80074A04:
/* 12CAF34 80074A04 00004392 */  lbu        $v1, 0x0($s2)
/* 12CAF38 80074A08 00000000 */  nop
/* 12CAF3C 80074A0C 5000622C */  sltiu      $v0, $v1, 0x50
/* 12CAF40 80074A10 27034010 */  beqz       $v0, .Lcutscene_66_800756B0
/* 12CAF44 80074A14 80100300 */   sll       $v0, $v1, 2
/* 12CAF48 80074A18 0780013C */  lui        $at, %hi(jtbl_cutscene_66_80074490)
/* 12CAF4C 80074A1C 21082200 */  addu       $at, $at, $v0
/* 12CAF50 80074A20 9044228C */  lw         $v0, %lo(jtbl_cutscene_66_80074490)($at)
/* 12CAF54 80074A24 00000000 */  nop
/* 12CAF58 80074A28 08004000 */  jr         $v0
/* 12CAF5C 80074A2C 00000000 */   nop
.L80074A30_:
/* 12CAF60 80074A30 21206002 */  addu       $a0, $s3, $zero
/* 12CAF64 80074A34 21286002 */  addu       $a1, $s3, $zero
/* 12CAF68 80074A38 6A3D010C */  jal        func_8004F5A8
/* 12CAF6C 80074A3C 21308002 */   addu      $a2, $s4, $zero
/* 12CAF70 80074A40 1D000286 */  lh         $v0, 0x1D($s0)
/* 12CAF74 80074A44 00000000 */  nop
/* 12CAF78 80074A48 06004010 */  beqz       $v0, .Lcutscene_66_80074A64
/* 12CAF7C 80074A4C 01000224 */   addiu     $v0, $zero, 0x1
/* 12CAF80 80074A50 1B000296 */  lhu        $v0, 0x1B($s0)
/* 12CAF84 80074A54 00000000 */  nop
/* 12CAF88 80074A58 01004224 */  addiu      $v0, $v0, 0x1
/* 12CAF8C 80074A5C 1B0002A6 */  sh         $v0, 0x1B($s0)
/* 12CAF90 80074A60 01000224 */  addiu      $v0, $zero, 0x1
.Lcutscene_66_80074A64:
/* 12CAF94 80074A64 09000392 */  lbu        $v1, 0x9($s0)
/* 12CAF98 80074A68 1D000496 */  lhu        $a0, 0x1D($s0)
/* 12CAF9C 80074A6C 21187700 */  addu       $v1, $v1, $s7
/* 12CAFA0 80074A70 090003A2 */  sb         $v1, 0x9($s0)
/* 12CAFA4 80074A74 0C000392 */  lbu        $v1, 0xC($s0)
/* 12CAFA8 80074A78 23104400 */  subu       $v0, $v0, $a0
/* 12CAFAC 80074A7C 1D0002A6 */  sh         $v0, 0x1D($s0)
/* 12CAFB0 80074A80 0B000292 */  lbu        $v0, 0xB($s0)
/* 12CAFB4 80074A84 23187500 */  subu       $v1, $v1, $s5
/* 12CAFB8 80074A88 0C0003A2 */  sb         $v1, 0xC($s0)
/* 12CAFBC 80074A8C 0D000392 */  lbu        $v1, 0xD($s0)
/* 12CAFC0 80074A90 23105500 */  subu       $v0, $v0, $s5
/* 12CAFC4 80074A94 0B0002A2 */  sb         $v0, 0xB($s0)
/* 12CAFC8 80074A98 01000292 */  lbu        $v0, 0x1($s0)
/* 12CAFCC 80074A9C 23187500 */  subu       $v1, $v1, $s5
/* 12CAFD0 80074AA0 21105600 */  addu       $v0, $v0, $s6
/* 12CAFD4 80074AA4 010002A2 */  sb         $v0, 0x1($s0)
/* 12CAFD8 80074AA8 FF004230 */  andi       $v0, $v0, 0xFF
/* 12CAFDC 80074AAC 2000422C */  sltiu      $v0, $v0, 0x20
/* 12CAFE0 80074AB0 EFD30108 */  j          .Lcutscene_66_80074FBC
/* 12CAFE4 80074AB4 0D0003A2 */   sb        $v1, 0xD($s0)
.L80074AB8_:
/* 12CAFE8 80074AB8 21206002 */  addu       $a0, $s3, $zero
/* 12CAFEC 80074ABC 21286002 */  addu       $a1, $s3, $zero
/* 12CAFF0 80074AC0 6A3D010C */  jal        func_8004F5A8
/* 12CAFF4 80074AC4 21308002 */   addu      $a2, $s4, $zero
/* 12CAFF8 80074AC8 1D000286 */  lh         $v0, 0x1D($s0)
/* 12CAFFC 80074ACC 00000000 */  nop
/* 12CB000 80074AD0 06004010 */  beqz       $v0, .Lcutscene_66_80074AEC
/* 12CB004 80074AD4 01000224 */   addiu     $v0, $zero, 0x1
/* 12CB008 80074AD8 1B000296 */  lhu        $v0, 0x1B($s0)
/* 12CB00C 80074ADC 00000000 */  nop
/* 12CB010 80074AE0 01004224 */  addiu      $v0, $v0, 0x1
/* 12CB014 80074AE4 1B0002A6 */  sh         $v0, 0x1B($s0)
/* 12CB018 80074AE8 01000224 */  addiu      $v0, $zero, 0x1
.Lcutscene_66_80074AEC:
/* 12CB01C 80074AEC 09000392 */  lbu        $v1, 0x9($s0)
/* 12CB020 80074AF0 1D000496 */  lhu        $a0, 0x1D($s0)
/* 12CB024 80074AF4 21187500 */  addu       $v1, $v1, $s5
/* 12CB028 80074AF8 090003A2 */  sb         $v1, 0x9($s0)
/* 12CB02C 80074AFC 0C000392 */  lbu        $v1, 0xC($s0)
/* 12CB030 80074B00 23104400 */  subu       $v0, $v0, $a0
/* 12CB034 80074B04 1D0002A6 */  sh         $v0, 0x1D($s0)
/* 12CB038 80074B08 0B000292 */  lbu        $v0, 0xB($s0)
/* 12CB03C 80074B0C 23187500 */  subu       $v1, $v1, $s5
/* 12CB040 80074B10 0C0003A2 */  sb         $v1, 0xC($s0)
/* 12CB044 80074B14 0D000392 */  lbu        $v1, 0xD($s0)
/* 12CB048 80074B18 23105500 */  subu       $v0, $v0, $s5
/* 12CB04C 80074B1C 0B0002A2 */  sb         $v0, 0xB($s0)
/* 12CB050 80074B20 01000292 */  lbu        $v0, 0x1($s0)
/* 12CB054 80074B24 23187500 */  subu       $v1, $v1, $s5
/* 12CB058 80074B28 21105600 */  addu       $v0, $v0, $s6
/* 12CB05C 80074B2C 010002A2 */  sb         $v0, 0x1($s0)
/* 12CB060 80074B30 FF004230 */  andi       $v0, $v0, 0xFF
/* 12CB064 80074B34 1800422C */  sltiu      $v0, $v0, 0x18
/* 12CB068 80074B38 EFD30108 */  j          .Lcutscene_66_80074FBC
/* 12CB06C 80074B3C 0D0003A2 */   sb        $v1, 0xD($s0)
.L80074B40_:
/* 12CB070 80074B40 21206002 */  addu       $a0, $s3, $zero
/* 12CB074 80074B44 21286002 */  addu       $a1, $s3, $zero
/* 12CB078 80074B48 6A3D010C */  jal        func_8004F5A8
/* 12CB07C 80074B4C 21308002 */   addu      $a2, $s4, $zero
/* 12CB080 80074B50 1D000286 */  lh         $v0, 0x1D($s0)
/* 12CB084 80074B54 00000000 */  nop
/* 12CB088 80074B58 05004010 */  beqz       $v0, .Lcutscene_66_80074B70
/* 12CB08C 80074B5C 00000000 */   nop
/* 12CB090 80074B60 1B000296 */  lhu        $v0, 0x1B($s0)
/* 12CB094 80074B64 00000000 */  nop
/* 12CB098 80074B68 01004224 */  addiu      $v0, $v0, 0x1
/* 12CB09C 80074B6C 1B0002A6 */  sh         $v0, 0x1B($s0)
.Lcutscene_66_80074B70:
/* 12CB0A0 80074B70 1D000396 */  lhu        $v1, 0x1D($s0)
/* 12CB0A4 80074B74 01000224 */  addiu      $v0, $zero, 0x1
/* 12CB0A8 80074B78 23104300 */  subu       $v0, $v0, $v1
/* 12CB0AC 80074B7C 09000392 */  lbu        $v1, 0x9($s0)
/* 12CB0B0 80074B80 1D0002A6 */  sh         $v0, 0x1D($s0)
/* 12CB0B4 80074B84 01000292 */  lbu        $v0, 0x1($s0)
/* 12CB0B8 80074B88 21187700 */  addu       $v1, $v1, $s7
/* 12CB0BC 80074B8C 21105600 */  addu       $v0, $v0, $s6
/* 12CB0C0 80074B90 010002A2 */  sb         $v0, 0x1($s0)
/* 12CB0C4 80074B94 FF004230 */  andi       $v0, $v0, 0xFF
/* 12CB0C8 80074B98 2000422C */  sltiu      $v0, $v0, 0x20
/* 12CB0CC 80074B9C EFD30108 */  j          .Lcutscene_66_80074FBC
/* 12CB0D0 80074BA0 090003A2 */   sb        $v1, 0x9($s0)
.L80074BA4_:
/* 12CB0D4 80074BA4 0780033C */  lui        $v1, %hi(D_80070328 + 0x48)
/* 12CB0D8 80074BA8 7003638C */  lw         $v1, %lo(D_80070328 + 0x48)($v1)
/* 12CB0DC 80074BAC 1E000224 */  addiu      $v0, $zero, 0x1E
/* 12CB0E0 80074BB0 06006214 */  bne        $v1, $v0, .Lcutscene_66_80074BCC
/* 12CB0E4 80074BB4 00000000 */   nop
/* 12CB0E8 80074BB8 0780023C */  lui        $v0, %hi(D_80070328 + 0x280)
/* 12CB0EC 80074BBC A805428C */  lw         $v0, %lo(D_80070328 + 0x280)($v0)
/* 12CB0F0 80074BC0 00000000 */  nop
/* 12CB0F4 80074BC4 A5024004 */  bltz       $v0, .Lcutscene_66_8007565C
/* 12CB0F8 80074BC8 00000000 */   nop
.Lcutscene_66_80074BCC:
/* 12CB0FC 80074BCC 0780053C */  lui        $a1, %hi(D_80070328 + 0x288)
/* 12CB100 80074BD0 B005A524 */  addiu      $a1, $a1, %lo(D_80070328 + 0x288)
/* 12CB104 80074BD4 0000A28C */  lw         $v0, 0x0($a1)
/* 12CB108 80074BD8 00000000 */  nop
/* 12CB10C 80074BDC 9F024014 */  bnez       $v0, .Lcutscene_66_8007565C
/* 12CB110 80074BE0 00000000 */   nop
/* 12CB114 80074BE4 0780023C */  lui        $v0, %hi(D_80070328 + 0x284)
/* 12CB118 80074BE8 AC05428C */  lw         $v0, %lo(D_80070328 + 0x284)($v0)
/* 12CB11C 80074BEC 00000000 */  nop
/* 12CB120 80074BF0 9A024010 */  beqz       $v0, .Lcutscene_66_8007565C
/* 12CB124 80074BF4 1000A427 */   addiu     $a0, $sp, 0x10
/* 12CB128 80074BF8 5E3C010C */  jal        func_8004F178
/* 12CB12C 80074BFC 78FDA524 */   addiu     $a1, $a1, -0x288
/* 12CB130 80074C00 17000486 */  lh         $a0, 0x17($s0)
/* 12CB134 80074C04 8B3A010C */  jal        func_8004EA2C
/* 12CB138 80074C08 00000000 */   nop
/* 12CB13C 80074C0C 1000A38F */  lw         $v1, 0x10($sp)
/* 12CB140 80074C10 03110200 */  sra        $v0, $v0, 4
/* 12CB144 80074C14 21186200 */  addu       $v1, $v1, $v0
/* 12CB148 80074C18 1000A3AF */  sw         $v1, 0x10($sp)
/* 12CB14C 80074C1C 17000486 */  lh         $a0, 0x17($s0)
/* 12CB150 80074C20 793A010C */  jal        func_8004E9E4
/* 12CB154 80074C24 00000000 */   nop
/* 12CB158 80074C28 21206002 */  addu       $a0, $s3, $zero
/* 12CB15C 80074C2C 1000A527 */  addiu      $a1, $sp, 0x10
/* 12CB160 80074C30 03110200 */  sra        $v0, $v0, 4
/* 12CB164 80074C34 1400A38F */  lw         $v1, 0x14($sp)
/* 12CB168 80074C38 1800A68F */  lw         $a2, 0x18($sp)
/* 12CB16C 80074C3C 21186200 */  addu       $v1, $v1, $v0
/* 12CB170 80074C40 0001C624 */  addiu      $a2, $a2, 0x100
/* 12CB174 80074C44 1400A3AF */  sw         $v1, 0x14($sp)
/* 12CB178 80074C48 413D010C */  jal        func_8004F504
/* 12CB17C 80074C4C 1800A6AF */   sw        $a2, 0x18($sp)
/* 12CB180 80074C50 17000496 */  lhu        $a0, 0x17($s0)
/* 12CB184 80074C54 00000000 */  nop
/* 12CB188 80074C58 40008424 */  addiu      $a0, $a0, 0x40
/* 12CB18C 80074C5C 170004A6 */  sh         $a0, 0x17($s0)
/* 12CB190 80074C60 00240400 */  sll        $a0, $a0, 16
/* 12CB194 80074C64 0780023C */  lui        $v0, %hi(D_8006E040)
/* 12CB198 80074C68 40E04284 */  lh         $v0, %lo(D_8006E040)($v0)
/* 12CB19C 80074C6C 03240400 */  sra        $a0, $a0, 16
/* 12CB1A0 80074C70 23208200 */  subu       $a0, $a0, $v0
/* 12CB1A4 80074C74 8B3A010C */  jal        func_8004EA2C
/* 12CB1A8 80074C78 FF0F8430 */   andi      $a0, $a0, 0xFFF
/* 12CB1AC 80074C7C 6060033C */  lui        $v1, (0x60606061 >> 16)
/* 12CB1B0 80074C80 61606334 */  ori        $v1, $v1, (0x60606061 & 0xFFFF)
/* 12CB1B4 80074C84 02004104 */  bgez       $v0, .Lcutscene_66_80074C90
/* 12CB1B8 80074C88 00000000 */   nop
/* 12CB1BC 80074C8C 23100200 */  negu       $v0, $v0
.Lcutscene_66_80074C90:
/* 12CB1C0 80074C90 18004300 */  mult       $v0, $v1
/* 12CB1C4 80074C94 C3170200 */  sra        $v0, $v0, 31
/* 12CB1C8 80074C98 10380000 */  mfhi       $a3
/* 12CB1CC 80074C9C 83190700 */  sra        $v1, $a3, 6
/* 12CB1D0 80074CA0 23186200 */  subu       $v1, $v1, $v0
/* 12CB1D4 80074CA4 ACD50108 */  j          .Lcutscene_66_800756B0
/* 12CB1D8 80074CA8 090003A2 */   sb        $v1, 0x9($s0)
.L80074CAC_:
/* 12CB1DC 80074CAC 1D000286 */  lh         $v0, 0x1D($s0)
/* 12CB1E0 80074CB0 00000000 */  nop
/* 12CB1E4 80074CB4 05004010 */  beqz       $v0, .Lcutscene_66_80074CCC
/* 12CB1E8 80074CB8 21206002 */   addu      $a0, $s3, $zero
/* 12CB1EC 80074CBC 15000296 */  lhu        $v0, 0x15($s0)
/* 12CB1F0 80074CC0 00000000 */  nop
/* 12CB1F4 80074CC4 01004224 */  addiu      $v0, $v0, 0x1
/* 12CB1F8 80074CC8 150002A6 */  sh         $v0, 0x15($s0)
.Lcutscene_66_80074CCC:
/* 12CB1FC 80074CCC 21286002 */  addu       $a1, $s3, $zero
/* 12CB200 80074CD0 12004626 */  addiu      $a2, $s2, 0x12
/* 12CB204 80074CD4 1D000396 */  lhu        $v1, 0x1D($s0)
/* 12CB208 80074CD8 01000224 */  addiu      $v0, $zero, 0x1
/* 12CB20C 80074CDC 23104300 */  subu       $v0, $v0, $v1
/* 12CB210 80074CE0 6A3D010C */  jal        func_8004F5A8
/* 12CB214 80074CE4 1D0002A6 */   sh        $v0, 0x1D($s0)
/* 12CB218 80074CE8 09000292 */  lbu        $v0, 0x9($s0)
/* 12CB21C 80074CEC 0B000392 */  lbu        $v1, 0xB($s0)
/* 12CB220 80074CF0 21105700 */  addu       $v0, $v0, $s7
/* 12CB224 80074CF4 090002A2 */  sb         $v0, 0x9($s0)
/* 12CB228 80074CF8 0A000292 */  lbu        $v0, 0xA($s0)
/* 12CB22C 80074CFC FCFF6324 */  addiu      $v1, $v1, -0x4
/* 12CB230 80074D00 0B0003A2 */  sb         $v1, 0xB($s0)
/* 12CB234 80074D04 0D000392 */  lbu        $v1, 0xD($s0)
/* 12CB238 80074D08 21105500 */  addu       $v0, $v0, $s5
/* 12CB23C 80074D0C 0A0002A2 */  sb         $v0, 0xA($s0)
/* 12CB240 80074D10 0C000292 */  lbu        $v0, 0xC($s0)
/* 12CB244 80074D14 FCFF6324 */  addiu      $v1, $v1, -0x4
/* 12CB248 80074D18 0D0003A2 */  sb         $v1, 0xD($s0)
/* 12CB24C 80074D1C FF006330 */  andi       $v1, $v1, 0xFF
/* 12CB250 80074D20 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 12CB254 80074D24 4D026010 */  beqz       $v1, .Lcutscene_66_8007565C
/* 12CB258 80074D28 0C0002A2 */   sb        $v0, 0xC($s0)
/* 12CB25C 80074D2C F1D30108 */  j          .Lcutscene_66_80074FC4
/* 12CB260 80074D30 00000000 */   nop
.L80074D34_:
/* 12CB264 80074D34 21206002 */  addu       $a0, $s3, $zero
/* 12CB268 80074D38 21286002 */  addu       $a1, $s3, $zero
/* 12CB26C 80074D3C 0A000292 */  lbu        $v0, 0xA($s0)
/* 12CB270 80074D40 21308002 */  addu       $a2, $s4, $zero
/* 12CB274 80074D44 08004224 */  addiu      $v0, $v0, 0x8
/* 12CB278 80074D48 6A3D010C */  jal        func_8004F5A8
/* 12CB27C 80074D4C 0A0002A2 */   sb        $v0, 0xA($s0)
/* 12CB280 80074D50 0B000292 */  lbu        $v0, 0xB($s0)
/* 12CB284 80074D54 00000000 */  nop
/* 12CB288 80074D58 02004010 */  beqz       $v0, .Lcutscene_66_80074D64
/* 12CB28C 80074D5C F8FF4224 */   addiu     $v0, $v0, -0x8
/* 12CB290 80074D60 0B0002A2 */  sb         $v0, 0xB($s0)
.Lcutscene_66_80074D64:
/* 12CB294 80074D64 0C000292 */  lbu        $v0, 0xC($s0)
/* 12CB298 80074D68 00000000 */  nop
/* 12CB29C 80074D6C 02004010 */  beqz       $v0, .Lcutscene_66_80074D78
/* 12CB2A0 80074D70 F8FF4224 */   addiu     $v0, $v0, -0x8
/* 12CB2A4 80074D74 0C0002A2 */  sb         $v0, 0xC($s0)
.Lcutscene_66_80074D78:
/* 12CB2A8 80074D78 0D000292 */  lbu        $v0, 0xD($s0)
/* 12CB2AC 80074D7C 00000000 */  nop
/* 12CB2B0 80074D80 02004010 */  beqz       $v0, .Lcutscene_66_80074D8C
/* 12CB2B4 80074D84 F8FF4224 */   addiu     $v0, $v0, -0x8
/* 12CB2B8 80074D88 0D0002A2 */  sb         $v0, 0xD($s0)
.Lcutscene_66_80074D8C:
/* 12CB2BC 80074D8C FF00033C */  lui        $v1, (0xFFFFFF >> 16)
/* 12CB2C0 80074D90 0B00028E */  lw         $v0, 0xB($s0)
/* 12CB2C4 80074D94 FFFF6334 */  ori        $v1, $v1, (0xFFFFFF & 0xFFFF)
/* 12CB2C8 80074D98 24104300 */  and        $v0, $v0, $v1
/* 12CB2CC 80074D9C 2F024010 */  beqz       $v0, .Lcutscene_66_8007565C
/* 12CB2D0 80074DA0 00000000 */   nop
/* 12CB2D4 80074DA4 F1D30108 */  j          .Lcutscene_66_80074FC4
/* 12CB2D8 80074DA8 00000000 */   nop
.L80074DAC_:
/* 12CB2DC 80074DAC 21206002 */  addu       $a0, $s3, $zero
/* 12CB2E0 80074DB0 21286002 */  addu       $a1, $s3, $zero
/* 12CB2E4 80074DB4 6A3D010C */  jal        func_8004F5A8
/* 12CB2E8 80074DB8 21308002 */   addu      $a2, $s4, $zero
/* 12CB2EC 80074DBC 1D000286 */  lh         $v0, 0x1D($s0)
/* 12CB2F0 80074DC0 00000000 */  nop
/* 12CB2F4 80074DC4 05004010 */  beqz       $v0, .Lcutscene_66_80074DDC
/* 12CB2F8 80074DC8 00000000 */   nop
/* 12CB2FC 80074DCC 1B000296 */  lhu        $v0, 0x1B($s0)
/* 12CB300 80074DD0 00000000 */  nop
/* 12CB304 80074DD4 01004224 */  addiu      $v0, $v0, 0x1
/* 12CB308 80074DD8 1B0002A6 */  sh         $v0, 0x1B($s0)
.Lcutscene_66_80074DDC:
/* 12CB30C 80074DDC 0B000292 */  lbu        $v0, 0xB($s0)
/* 12CB310 80074DE0 1D000496 */  lhu        $a0, 0x1D($s0)
/* 12CB314 80074DE4 09000392 */  lbu        $v1, 0x9($s0)
/* 12CB318 80074DE8 23285700 */  subu       $a1, $v0, $s7
/* 12CB31C 80074DEC 01000224 */  addiu      $v0, $zero, 0x1
/* 12CB320 80074DF0 23104400 */  subu       $v0, $v0, $a0
/* 12CB324 80074DF4 21187700 */  addu       $v1, $v1, $s7
/* 12CB328 80074DF8 1D0002A6 */  sh         $v0, 0x1D($s0)
/* 12CB32C 80074DFC 0200A104 */  bgez       $a1, .Lcutscene_66_80074E08
/* 12CB330 80074E00 090003A2 */   sb        $v1, 0x9($s0)
/* 12CB334 80074E04 21280000 */  addu       $a1, $zero, $zero
.Lcutscene_66_80074E08:
/* 12CB338 80074E08 01000292 */  lbu        $v0, 0x1($s0)
/* 12CB33C 80074E0C 0B0005A2 */  sb         $a1, 0xB($s0)
/* 12CB340 80074E10 0C0005A2 */  sb         $a1, 0xC($s0)
/* 12CB344 80074E14 0D0005A2 */  sb         $a1, 0xD($s0)
/* 12CB348 80074E18 21105600 */  addu       $v0, $v0, $s6
/* 12CB34C 80074E1C 010002A2 */  sb         $v0, 0x1($s0)
/* 12CB350 80074E20 FF004230 */  andi       $v0, $v0, 0xFF
/* 12CB354 80074E24 2000422C */  sltiu      $v0, $v0, 0x20
/* 12CB358 80074E28 0C024010 */  beqz       $v0, .Lcutscene_66_8007565C
/* 12CB35C 80074E2C 00000000 */   nop
/* 12CB360 80074E30 02000292 */  lbu        $v0, 0x2($s0)
/* 12CB364 80074E34 00000000 */  nop
/* 12CB368 80074E38 08024010 */  beqz       $v0, .Lcutscene_66_8007565C
/* 12CB36C 80074E3C 00000000 */   nop
/* 12CB370 80074E40 0602A010 */  beqz       $a1, .Lcutscene_66_8007565C
/* 12CB374 80074E44 00000000 */   nop
/* 12CB378 80074E48 ADD50108 */  j          .Lcutscene_66_800756B4
/* 12CB37C 80074E4C 20001026 */   addiu     $s0, $s0, 0x20
.L80074E50_:
/* 12CB380 80074E50 21206002 */  addu       $a0, $s3, $zero
/* 12CB384 80074E54 21286002 */  addu       $a1, $s3, $zero
/* 12CB388 80074E58 0A000292 */  lbu        $v0, 0xA($s0)
/* 12CB38C 80074E5C 21308002 */  addu       $a2, $s4, $zero
/* 12CB390 80074E60 08004224 */  addiu      $v0, $v0, 0x8
/* 12CB394 80074E64 6A3D010C */  jal        func_8004F5A8
/* 12CB398 80074E68 0A0002A2 */   sb        $v0, 0xA($s0)
/* 12CB39C 80074E6C 0780023C */  lui        $v0, %hi(D_8006C640)
/* 12CB3A0 80074E70 40C6428C */  lw         $v0, %lo(D_8006C640)($v0)
/* 12CB3A4 80074E74 00000000 */  nop
/* 12CB3A8 80074E78 01004230 */  andi       $v0, $v0, 0x1
/* 12CB3AC 80074E7C 05004010 */  beqz       $v0, .Lcutscene_66_80074E94
/* 12CB3B0 80074E80 00000000 */   nop
/* 12CB3B4 80074E84 19000296 */  lhu        $v0, 0x19($s0)
/* 12CB3B8 80074E88 00000000 */  nop
/* 12CB3BC 80074E8C 01004224 */  addiu      $v0, $v0, 0x1
/* 12CB3C0 80074E90 190002A6 */  sh         $v0, 0x19($s0)
.Lcutscene_66_80074E94:
/* 12CB3C4 80074E94 0B000292 */  lbu        $v0, 0xB($s0)
/* 12CB3C8 80074E98 00000000 */  nop
/* 12CB3CC 80074E9C 02004010 */  beqz       $v0, .Lcutscene_66_80074EA8
/* 12CB3D0 80074EA0 FCFF4224 */   addiu     $v0, $v0, -0x4
/* 12CB3D4 80074EA4 0B0002A2 */  sb         $v0, 0xB($s0)
.Lcutscene_66_80074EA8:
/* 12CB3D8 80074EA8 0C000292 */  lbu        $v0, 0xC($s0)
/* 12CB3DC 80074EAC 00000000 */  nop
/* 12CB3E0 80074EB0 02004010 */  beqz       $v0, .Lcutscene_66_80074EBC
/* 12CB3E4 80074EB4 FCFF4224 */   addiu     $v0, $v0, -0x4
/* 12CB3E8 80074EB8 0C0002A2 */  sb         $v0, 0xC($s0)
.Lcutscene_66_80074EBC:
/* 12CB3EC 80074EBC 0D000292 */  lbu        $v0, 0xD($s0)
/* 12CB3F0 80074EC0 00000000 */  nop
/* 12CB3F4 80074EC4 02004010 */  beqz       $v0, .Lcutscene_66_80074ED0
/* 12CB3F8 80074EC8 FCFF4224 */   addiu     $v0, $v0, -0x4
/* 12CB3FC 80074ECC 0D0002A2 */  sb         $v0, 0xD($s0)
.Lcutscene_66_80074ED0:
/* 12CB400 80074ED0 FF00033C */  lui        $v1, (0xFFFFFF >> 16)
/* 12CB404 80074ED4 0B00028E */  lw         $v0, 0xB($s0)
/* 12CB408 80074ED8 FFFF6334 */  ori        $v1, $v1, (0xFFFFFF & 0xFFFF)
/* 12CB40C 80074EDC 24104300 */  and        $v0, $v0, $v1
/* 12CB410 80074EE0 DE014010 */  beqz       $v0, .Lcutscene_66_8007565C
/* 12CB414 80074EE4 00000000 */   nop
/* 12CB418 80074EE8 F1D30108 */  j          .Lcutscene_66_80074FC4
/* 12CB41C 80074EEC 00000000 */   nop
.L80074EF0_:
/* 12CB420 80074EF0 2F00C01A */  blez       $s6, .Lcutscene_66_80074FB0
/* 12CB424 80074EF4 21880000 */   addu      $s1, $zero, $zero
.Lcutscene_66_80074EF8:
/* 12CB428 80074EF8 01000292 */  lbu        $v0, 0x1($s0)
/* 12CB42C 80074EFC 00000000 */  nop
/* 12CB430 80074F00 01004230 */  andi       $v0, $v0, 0x1
/* 12CB434 80074F04 23004010 */  beqz       $v0, .Lcutscene_66_80074F94
/* 12CB438 80074F08 00000000 */   nop
/* 12CB43C 80074F0C 03000296 */  lhu        $v0, 0x3($s0)
/* 12CB440 80074F10 0F000496 */  lhu        $a0, 0xF($s0)
/* 12CB444 80074F14 05000396 */  lhu        $v1, 0x5($s0)
/* 12CB448 80074F18 11000596 */  lhu        $a1, 0x11($s0)
/* 12CB44C 80074F1C 21104400 */  addu       $v0, $v0, $a0
/* 12CB450 80074F20 030002A6 */  sh         $v0, 0x3($s0)
/* 12CB454 80074F24 07000296 */  lhu        $v0, 0x7($s0)
/* 12CB458 80074F28 13000496 */  lhu        $a0, 0x13($s0)
/* 12CB45C 80074F2C 21186500 */  addu       $v1, $v1, $a1
/* 12CB460 80074F30 050003A6 */  sh         $v1, 0x5($s0)
/* 12CB464 80074F34 01000392 */  lbu        $v1, 0x1($s0)
/* 12CB468 80074F38 21104400 */  addu       $v0, $v0, $a0
/* 12CB46C 80074F3C 02006330 */  andi       $v1, $v1, 0x2
/* 12CB470 80074F40 14006010 */  beqz       $v1, .Lcutscene_66_80074F94
/* 12CB474 80074F44 070002A6 */   sh        $v0, 0x7($s0)
/* 12CB478 80074F48 9171010C */  jal        func_8005C644
/* 12CB47C 80074F4C 00000000 */   nop
/* 12CB480 80074F50 0F000396 */  lhu        $v1, 0xF($s0)
/* 12CB484 80074F54 02004230 */  andi       $v0, $v0, 0x2
/* 12CB488 80074F58 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 12CB48C 80074F5C 21186200 */  addu       $v1, $v1, $v0
/* 12CB490 80074F60 9171010C */  jal        func_8005C644
/* 12CB494 80074F64 0F0003A6 */   sh        $v1, 0xF($s0)
/* 12CB498 80074F68 11000396 */  lhu        $v1, 0x11($s0)
/* 12CB49C 80074F6C 02004230 */  andi       $v0, $v0, 0x2
/* 12CB4A0 80074F70 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 12CB4A4 80074F74 21186200 */  addu       $v1, $v1, $v0
/* 12CB4A8 80074F78 9171010C */  jal        func_8005C644
/* 12CB4AC 80074F7C 110003A6 */   sh        $v1, 0x11($s0)
/* 12CB4B0 80074F80 13000396 */  lhu        $v1, 0x13($s0)
/* 12CB4B4 80074F84 02004230 */  andi       $v0, $v0, 0x2
/* 12CB4B8 80074F88 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 12CB4BC 80074F8C 21186200 */  addu       $v1, $v1, $v0
/* 12CB4C0 80074F90 130003A6 */  sh         $v1, 0x13($s0)
.Lcutscene_66_80074F94:
/* 12CB4C4 80074F94 01000292 */  lbu        $v0, 0x1($s0)
/* 12CB4C8 80074F98 01003126 */  addiu      $s1, $s1, 0x1
/* 12CB4CC 80074F9C 01004224 */  addiu      $v0, $v0, 0x1
/* 12CB4D0 80074FA0 010002A2 */  sb         $v0, 0x1($s0)
/* 12CB4D4 80074FA4 2A103602 */  slt        $v0, $s1, $s6
/* 12CB4D8 80074FA8 D3FF4014 */  bnez       $v0, .Lcutscene_66_80074EF8
/* 12CB4DC 80074FAC 00000000 */   nop
.Lcutscene_66_80074FB0:
/* 12CB4E0 80074FB0 01000292 */  lbu        $v0, 0x1($s0)
/* 12CB4E4 80074FB4 00000000 */  nop
/* 12CB4E8 80074FB8 1800422C */  sltiu      $v0, $v0, 0x18
.Lcutscene_66_80074FBC:
/* 12CB4EC 80074FBC A7014010 */  beqz       $v0, .Lcutscene_66_8007565C
/* 12CB4F0 80074FC0 00000000 */   nop
.Lcutscene_66_80074FC4:
/* 12CB4F4 80074FC4 02000292 */  lbu        $v0, 0x2($s0)
/* 12CB4F8 80074FC8 00000000 */  nop
/* 12CB4FC 80074FCC A3014010 */  beqz       $v0, .Lcutscene_66_8007565C
/* 12CB500 80074FD0 00000000 */   nop
/* 12CB504 80074FD4 ADD50108 */  j          .Lcutscene_66_800756B4
/* 12CB508 80074FD8 20001026 */   addiu     $s0, $s0, 0x20
.L80074FDC_:
/* 12CB50C 80074FDC 01000292 */  lbu        $v0, 0x1($s0)
/* 12CB510 80074FE0 00000000 */  nop
/* 12CB514 80074FE4 01004224 */  addiu      $v0, $v0, 0x1
/* 12CB518 80074FE8 010002A2 */  sb         $v0, 0x1($s0)
/* 12CB51C 80074FEC FF004230 */  andi       $v0, $v0, 0xFF
/* 12CB520 80074FF0 2000422C */  sltiu      $v0, $v0, 0x20
/* 12CB524 80074FF4 99014010 */  beqz       $v0, .Lcutscene_66_8007565C
/* 12CB528 80074FF8 00000000 */   nop
/* 12CB52C 80074FFC 02000292 */  lbu        $v0, 0x2($s0)
/* 12CB530 80075000 00000000 */  nop
/* 12CB534 80075004 95014010 */  beqz       $v0, .Lcutscene_66_8007565C
/* 12CB538 80075008 00000000 */   nop
/* 12CB53C 8007500C 09000486 */  lh         $a0, 0x9($s0)
/* 12CB540 80075010 03000286 */  lh         $v0, 0x3($s0)
/* 12CB544 80075014 00000000 */  nop
/* 12CB548 80075018 23208200 */  subu       $a0, $a0, $v0
/* 12CB54C 8007501C 43200400 */  sra        $a0, $a0, 1
/* 12CB550 80075020 2000A4A7 */  sh         $a0, 0x20($sp)
/* 12CB554 80075024 0B000286 */  lh         $v0, 0xB($s0)
/* 12CB558 80075028 05000386 */  lh         $v1, 0x5($s0)
/* 12CB55C 8007502C 00000000 */  nop
/* 12CB560 80075030 23104300 */  subu       $v0, $v0, $v1
/* 12CB564 80075034 43100200 */  sra        $v0, $v0, 1
/* 12CB568 80075038 2200A2A7 */  sh         $v0, 0x22($sp)
/* 12CB56C 8007503C 0D000286 */  lh         $v0, 0xD($s0)
/* 12CB570 80075040 07000386 */  lh         $v1, 0x7($s0)
/* 12CB574 80075044 00000000 */  nop
/* 12CB578 80075048 23104300 */  subu       $v0, $v0, $v1
/* 12CB57C 8007504C 43100200 */  sra        $v0, $v0, 1
/* 12CB580 80075050 2400A2A7 */  sh         $v0, 0x24($sp)
/* 12CB584 80075054 03000296 */  lhu        $v0, 0x3($s0)
/* 12CB588 80075058 00000000 */  nop
/* 12CB58C 8007505C 21104400 */  addu       $v0, $v0, $a0
/* 12CB590 80075060 030002A6 */  sh         $v0, 0x3($s0)
/* 12CB594 80075064 05000296 */  lhu        $v0, 0x5($s0)
/* 12CB598 80075068 2200A397 */  lhu        $v1, 0x22($sp)
/* 12CB59C 8007506C 00000000 */  nop
/* 12CB5A0 80075070 21104300 */  addu       $v0, $v0, $v1
/* 12CB5A4 80075074 050002A6 */  sh         $v0, 0x5($s0)
/* 12CB5A8 80075078 07000296 */  lhu        $v0, 0x7($s0)
/* 12CB5AC 8007507C 2400A397 */  lhu        $v1, 0x24($sp)
/* 12CB5B0 80075080 00000000 */  nop
/* 12CB5B4 80075084 21104300 */  addu       $v0, $v0, $v1
/* 12CB5B8 80075088 9171010C */  jal        func_8005C644
/* 12CB5BC 8007508C 070002A6 */   sh        $v0, 0x7($s0)
/* 12CB5C0 80075090 2000A397 */  lhu        $v1, 0x20($sp)
/* 12CB5C4 80075094 02004230 */  andi       $v0, $v0, 0x2
/* 12CB5C8 80075098 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 12CB5CC 8007509C 21186200 */  addu       $v1, $v1, $v0
/* 12CB5D0 800750A0 9171010C */  jal        func_8005C644
/* 12CB5D4 800750A4 2000A3A7 */   sh        $v1, 0x20($sp)
/* 12CB5D8 800750A8 2200A397 */  lhu        $v1, 0x22($sp)
/* 12CB5DC 800750AC 02004230 */  andi       $v0, $v0, 0x2
/* 12CB5E0 800750B0 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 12CB5E4 800750B4 21186200 */  addu       $v1, $v1, $v0
/* 12CB5E8 800750B8 2200A3A7 */  sh         $v1, 0x22($sp)
/* 12CB5EC 800750BC 01000292 */  lbu        $v0, 0x1($s0)
/* 12CB5F0 800750C0 00000000 */  nop
/* 12CB5F4 800750C4 01004230 */  andi       $v0, $v0, 0x1
/* 12CB5F8 800750C8 05004010 */  beqz       $v0, .Lcutscene_66_800750E0
/* 12CB5FC 800750CC 00000000 */   nop
/* 12CB600 800750D0 2400A297 */  lhu        $v0, 0x24($sp)
/* 12CB604 800750D4 00000000 */  nop
/* 12CB608 800750D8 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 12CB60C 800750DC 2400A2A7 */  sh         $v0, 0x24($sp)
.Lcutscene_66_800750E0:
/* 12CB610 800750E0 09000296 */  lhu        $v0, 0x9($s0)
/* 12CB614 800750E4 2000A397 */  lhu        $v1, 0x20($sp)
/* 12CB618 800750E8 00000000 */  nop
/* 12CB61C 800750EC 21104300 */  addu       $v0, $v0, $v1
/* 12CB620 800750F0 090002A6 */  sh         $v0, 0x9($s0)
/* 12CB624 800750F4 0B000296 */  lhu        $v0, 0xB($s0)
/* 12CB628 800750F8 2200A397 */  lhu        $v1, 0x22($sp)
/* 12CB62C 800750FC 00000000 */  nop
/* 12CB630 80075100 21104300 */  addu       $v0, $v0, $v1
/* 12CB634 80075104 0D000396 */  lhu        $v1, 0xD($s0)
/* 12CB638 80075108 0B0002A6 */  sh         $v0, 0xB($s0)
/* 12CB63C 8007510C 0F000292 */  lbu        $v0, 0xF($s0)
/* 12CB640 80075110 2400A497 */  lhu        $a0, 0x24($sp)
/* 12CB644 80075114 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 12CB648 80075118 21186400 */  addu       $v1, $v1, $a0
/* 12CB64C 8007511C 0F0002A2 */  sb         $v0, 0xF($s0)
/* 12CB650 80075120 FF004230 */  andi       $v0, $v0, 0xFF
/* 12CB654 80075124 8000422C */  sltiu      $v0, $v0, 0x80
/* 12CB658 80075128 03004010 */  beqz       $v0, .Lcutscene_66_80075138
/* 12CB65C 8007512C 0D0003A6 */   sh        $v1, 0xD($s0)
/* 12CB660 80075130 80000224 */  addiu      $v0, $zero, 0x80
/* 12CB664 80075134 0F0002A2 */  sb         $v0, 0xF($s0)
.Lcutscene_66_80075138:
/* 12CB668 80075138 10000292 */  lbu        $v0, 0x10($s0)
/* 12CB66C 8007513C 00000000 */  nop
/* 12CB670 80075140 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 12CB674 80075144 100002A2 */  sb         $v0, 0x10($s0)
/* 12CB678 80075148 FF004230 */  andi       $v0, $v0, 0xFF
/* 12CB67C 8007514C 6000422C */  sltiu      $v0, $v0, 0x60
/* 12CB680 80075150 02004010 */  beqz       $v0, .Lcutscene_66_8007515C
/* 12CB684 80075154 60000224 */   addiu     $v0, $zero, 0x60
/* 12CB688 80075158 100002A2 */  sb         $v0, 0x10($s0)
.Lcutscene_66_8007515C:
/* 12CB68C 8007515C 13000292 */  lbu        $v0, 0x13($s0)
/* 12CB690 80075160 110000A2 */  sb         $zero, 0x11($s0)
/* 12CB694 80075164 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 12CB698 80075168 130002A2 */  sb         $v0, 0x13($s0)
/* 12CB69C 8007516C FF004230 */  andi       $v0, $v0, 0xFF
/* 12CB6A0 80075170 C000422C */  sltiu      $v0, $v0, 0xC0
/* 12CB6A4 80075174 02004010 */  beqz       $v0, .Lcutscene_66_80075180
/* 12CB6A8 80075178 C0000224 */   addiu     $v0, $zero, 0xC0
/* 12CB6AC 8007517C 130002A2 */  sb         $v0, 0x13($s0)
.Lcutscene_66_80075180:
/* 12CB6B0 80075180 14000292 */  lbu        $v0, 0x14($s0)
/* 12CB6B4 80075184 00000000 */  nop
/* 12CB6B8 80075188 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 12CB6BC 8007518C 140002A2 */  sb         $v0, 0x14($s0)
/* 12CB6C0 80075190 FF004230 */  andi       $v0, $v0, 0xFF
/* 12CB6C4 80075194 8000422C */  sltiu      $v0, $v0, 0x80
/* 12CB6C8 80075198 02004010 */  beqz       $v0, .Lcutscene_66_800751A4
/* 12CB6CC 8007519C 80000224 */   addiu     $v0, $zero, 0x80
/* 12CB6D0 800751A0 140002A2 */  sb         $v0, 0x14($s0)
.Lcutscene_66_800751A4:
/* 12CB6D4 800751A4 15000292 */  lbu        $v0, 0x15($s0)
/* 12CB6D8 800751A8 00000000 */  nop
/* 12CB6DC 800751AC FAFF4224 */  addiu      $v0, $v0, -0x6
/* 12CB6E0 800751B0 150002A2 */  sb         $v0, 0x15($s0)
/* 12CB6E4 800751B4 FF004230 */  andi       $v0, $v0, 0xFF
/* 12CB6E8 800751B8 2000422C */  sltiu      $v0, $v0, 0x20
/* 12CB6EC 800751BC 3C014010 */  beqz       $v0, .Lcutscene_66_800756B0
/* 12CB6F0 800751C0 20000224 */   addiu     $v0, $zero, 0x20
/* 12CB6F4 800751C4 ACD50108 */  j          .Lcutscene_66_800756B0
/* 12CB6F8 800751C8 150002A2 */   sb        $v0, 0x15($s0)
.L800751CC_:
/* 12CB6FC 800751CC 01000292 */  lbu        $v0, 0x1($s0)
/* 12CB700 800751D0 00000000 */  nop
/* 12CB704 800751D4 01004224 */  addiu      $v0, $v0, 0x1
/* 12CB708 800751D8 010002A2 */  sb         $v0, 0x1($s0)
/* 12CB70C 800751DC FF004230 */  andi       $v0, $v0, 0xFF
/* 12CB710 800751E0 2000422C */  sltiu      $v0, $v0, 0x20
/* 12CB714 800751E4 1D014010 */  beqz       $v0, .Lcutscene_66_8007565C
/* 12CB718 800751E8 00000000 */   nop
/* 12CB71C 800751EC 02000292 */  lbu        $v0, 0x2($s0)
/* 12CB720 800751F0 00000000 */  nop
/* 12CB724 800751F4 19014010 */  beqz       $v0, .Lcutscene_66_8007565C
/* 12CB728 800751F8 00000000 */   nop
/* 12CB72C 800751FC 09000286 */  lh         $v0, 0x9($s0)
/* 12CB730 80075200 03000386 */  lh         $v1, 0x3($s0)
/* 12CB734 80075204 00000000 */  nop
/* 12CB738 80075208 23104300 */  subu       $v0, $v0, $v1
/* 12CB73C 8007520C 2800A2AF */  sw         $v0, 0x28($sp)
/* 12CB740 80075210 0B000286 */  lh         $v0, 0xB($s0)
/* 12CB744 80075214 05000386 */  lh         $v1, 0x5($s0)
/* 12CB748 80075218 00000000 */  nop
/* 12CB74C 8007521C 23104300 */  subu       $v0, $v0, $v1
/* 12CB750 80075220 2C00A2AF */  sw         $v0, 0x2C($sp)
/* 12CB754 80075224 0D000286 */  lh         $v0, 0xD($s0)
/* 12CB758 80075228 07000386 */  lh         $v1, 0x7($s0)
/* 12CB75C 8007522C 00000000 */  nop
/* 12CB760 80075230 23104300 */  subu       $v0, $v0, $v1
/* 12CB764 80075234 9171010C */  jal        func_8005C644
/* 12CB768 80075238 3000A2AF */   sw        $v0, 0x30($sp)
/* 12CB76C 8007523C 2800A38F */  lw         $v1, 0x28($sp)
/* 12CB770 80075240 02004230 */  andi       $v0, $v0, 0x2
/* 12CB774 80075244 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 12CB778 80075248 21186200 */  addu       $v1, $v1, $v0
/* 12CB77C 8007524C 9171010C */  jal        func_8005C644
/* 12CB780 80075250 2800A3AF */   sw        $v1, 0x28($sp)
/* 12CB784 80075254 2C00A38F */  lw         $v1, 0x2C($sp)
/* 12CB788 80075258 02004230 */  andi       $v0, $v0, 0x2
/* 12CB78C 8007525C FFFF6324 */  addiu      $v1, $v1, -0x1
/* 12CB790 80075260 21186200 */  addu       $v1, $v1, $v0
/* 12CB794 80075264 9171010C */  jal        func_8005C644
/* 12CB798 80075268 2C00A3AF */   sw        $v1, 0x2C($sp)
/* 12CB79C 8007526C 3000A38F */  lw         $v1, 0x30($sp)
/* 12CB7A0 80075270 02004230 */  andi       $v0, $v0, 0x2
/* 12CB7A4 80075274 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 12CB7A8 80075278 21186200 */  addu       $v1, $v1, $v0
/* 12CB7AC 8007527C 3000A3AF */  sw         $v1, 0x30($sp)
/* 12CB7B0 80075280 2800A38F */  lw         $v1, 0x28($sp)
/* 12CB7B4 80075284 09000296 */  lhu        $v0, 0x9($s0)
/* 12CB7B8 80075288 00000000 */  nop
/* 12CB7BC 8007528C 21104300 */  addu       $v0, $v0, $v1
/* 12CB7C0 80075290 090002A6 */  sh         $v0, 0x9($s0)
/* 12CB7C4 80075294 2C00A38F */  lw         $v1, 0x2C($sp)
/* 12CB7C8 80075298 0B000296 */  lhu        $v0, 0xB($s0)
/* 12CB7CC 8007529C 00000000 */  nop
/* 12CB7D0 800752A0 21104300 */  addu       $v0, $v0, $v1
/* 12CB7D4 800752A4 0B0002A6 */  sh         $v0, 0xB($s0)
/* 12CB7D8 800752A8 3000A38F */  lw         $v1, 0x30($sp)
/* 12CB7DC 800752AC 0D000296 */  lhu        $v0, 0xD($s0)
/* 12CB7E0 800752B0 00000000 */  nop
/* 12CB7E4 800752B4 21104300 */  addu       $v0, $v0, $v1
/* 12CB7E8 800752B8 0D0002A6 */  sh         $v0, 0xD($s0)
/* 12CB7EC 800752BC 2800A38F */  lw         $v1, 0x28($sp)
/* 12CB7F0 800752C0 09000296 */  lhu        $v0, 0x9($s0)
/* 12CB7F4 800752C4 00000000 */  nop
/* 12CB7F8 800752C8 23104300 */  subu       $v0, $v0, $v1
/* 12CB7FC 800752CC 030002A6 */  sh         $v0, 0x3($s0)
/* 12CB800 800752D0 2C00A38F */  lw         $v1, 0x2C($sp)
/* 12CB804 800752D4 0B000296 */  lhu        $v0, 0xB($s0)
/* 12CB808 800752D8 00000000 */  nop
/* 12CB80C 800752DC 23104300 */  subu       $v0, $v0, $v1
/* 12CB810 800752E0 050002A6 */  sh         $v0, 0x5($s0)
/* 12CB814 800752E4 13000292 */  lbu        $v0, 0x13($s0)
/* 12CB818 800752E8 3000A48F */  lw         $a0, 0x30($sp)
/* 12CB81C 800752EC 15000392 */  lbu        $v1, 0x15($s0)
/* 12CB820 800752F0 FEFF4224 */  addiu      $v0, $v0, -0x2
/* 12CB824 800752F4 130002A2 */  sb         $v0, 0x13($s0)
/* 12CB828 800752F8 14000292 */  lbu        $v0, 0x14($s0)
/* 12CB82C 800752FC FCFF6324 */  addiu      $v1, $v1, -0x4
/* 12CB830 80075300 150003A2 */  sb         $v1, 0x15($s0)
/* 12CB834 80075304 10000392 */  lbu        $v1, 0x10($s0)
/* 12CB838 80075308 FEFF4224 */  addiu      $v0, $v0, -0x2
/* 12CB83C 8007530C 140002A2 */  sb         $v0, 0x14($s0)
/* 12CB840 80075310 0F000292 */  lbu        $v0, 0xF($s0)
/* 12CB844 80075314 FDFF6324 */  addiu      $v1, $v1, -0x3
/* 12CB848 80075318 100003A2 */  sb         $v1, 0x10($s0)
/* 12CB84C 8007531C 0D000396 */  lhu        $v1, 0xD($s0)
/* 12CB850 80075320 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 12CB854 80075324 0F0002A2 */  sb         $v0, 0xF($s0)
/* 12CB858 80075328 11000292 */  lbu        $v0, 0x11($s0)
/* 12CB85C 8007532C 23186400 */  subu       $v1, $v1, $a0
/* 12CB860 80075330 070003A6 */  sh         $v1, 0x7($s0)
/* 12CB864 80075334 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 12CB868 80075338 ACD50108 */  j          .Lcutscene_66_800756B0
/* 12CB86C 8007533C 110002A2 */   sb        $v0, 0x11($s0)
.L80075340_:
/* 12CB870 80075340 01000292 */  lbu        $v0, 0x1($s0)
/* 12CB874 80075344 00000000 */  nop
/* 12CB878 80075348 01004224 */  addiu      $v0, $v0, 0x1
/* 12CB87C 8007534C 010002A2 */  sb         $v0, 0x1($s0)
/* 12CB880 80075350 FF004230 */  andi       $v0, $v0, 0xFF
/* 12CB884 80075354 3800422C */  sltiu      $v0, $v0, 0x38
/* 12CB888 80075358 C0004010 */  beqz       $v0, .Lcutscene_66_8007565C
/* 12CB88C 8007535C 00000000 */   nop
/* 12CB890 80075360 02000292 */  lbu        $v0, 0x2($s0)
/* 12CB894 80075364 00000000 */  nop
/* 12CB898 80075368 BC004010 */  beqz       $v0, .Lcutscene_66_8007565C
/* 12CB89C 8007536C 00000000 */   nop
/* 12CB8A0 80075370 03000286 */  lh         $v0, 0x3($s0)
/* 12CB8A4 80075374 09000386 */  lh         $v1, 0x9($s0)
/* 12CB8A8 80075378 00000000 */  nop
/* 12CB8AC 8007537C 23104300 */  subu       $v0, $v0, $v1
/* 12CB8B0 80075380 43100200 */  sra        $v0, $v0, 1
/* 12CB8B4 80075384 2000A2AF */  sw         $v0, 0x20($sp)
/* 12CB8B8 80075388 05000286 */  lh         $v0, 0x5($s0)
/* 12CB8BC 8007538C 0B000386 */  lh         $v1, 0xB($s0)
/* 12CB8C0 80075390 00000000 */  nop
/* 12CB8C4 80075394 23104300 */  subu       $v0, $v0, $v1
/* 12CB8C8 80075398 43100200 */  sra        $v0, $v0, 1
/* 12CB8CC 8007539C 2400A2AF */  sw         $v0, 0x24($sp)
/* 12CB8D0 800753A0 07000286 */  lh         $v0, 0x7($s0)
/* 12CB8D4 800753A4 0D000386 */  lh         $v1, 0xD($s0)
/* 12CB8D8 800753A8 00000000 */  nop
/* 12CB8DC 800753AC 23104300 */  subu       $v0, $v0, $v1
/* 12CB8E0 800753B0 43100200 */  sra        $v0, $v0, 1
/* 12CB8E4 800753B4 9171010C */  jal        func_8005C644
/* 12CB8E8 800753B8 2800A2AF */   sw        $v0, 0x28($sp)
/* 12CB8EC 800753BC 2000A38F */  lw         $v1, 0x20($sp)
/* 12CB8F0 800753C0 04004230 */  andi       $v0, $v0, 0x4
/* 12CB8F4 800753C4 FEFF6324 */  addiu      $v1, $v1, -0x2
/* 12CB8F8 800753C8 21186200 */  addu       $v1, $v1, $v0
/* 12CB8FC 800753CC 9171010C */  jal        func_8005C644
/* 12CB900 800753D0 2000A3AF */   sw        $v1, 0x20($sp)
/* 12CB904 800753D4 2400A38F */  lw         $v1, 0x24($sp)
/* 12CB908 800753D8 04004230 */  andi       $v0, $v0, 0x4
/* 12CB90C 800753DC FEFF6324 */  addiu      $v1, $v1, -0x2
/* 12CB910 800753E0 21186200 */  addu       $v1, $v1, $v0
/* 12CB914 800753E4 9171010C */  jal        func_8005C644
/* 12CB918 800753E8 2400A3AF */   sw        $v1, 0x24($sp)
/* 12CB91C 800753EC 2800A38F */  lw         $v1, 0x28($sp)
/* 12CB920 800753F0 02004230 */  andi       $v0, $v0, 0x2
/* 12CB924 800753F4 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 12CB928 800753F8 21186200 */  addu       $v1, $v1, $v0
/* 12CB92C 800753FC 2800A3AF */  sw         $v1, 0x28($sp)
/* 12CB930 80075400 2000A38F */  lw         $v1, 0x20($sp)
/* 12CB934 80075404 03000296 */  lhu        $v0, 0x3($s0)
/* 12CB938 80075408 00000000 */  nop
/* 12CB93C 8007540C 21104300 */  addu       $v0, $v0, $v1
/* 12CB940 80075410 030002A6 */  sh         $v0, 0x3($s0)
/* 12CB944 80075414 2400A38F */  lw         $v1, 0x24($sp)
/* 12CB948 80075418 05000296 */  lhu        $v0, 0x5($s0)
/* 12CB94C 8007541C 00000000 */  nop
/* 12CB950 80075420 21104300 */  addu       $v0, $v0, $v1
/* 12CB954 80075424 050002A6 */  sh         $v0, 0x5($s0)
/* 12CB958 80075428 2800A38F */  lw         $v1, 0x28($sp)
/* 12CB95C 8007542C 07000296 */  lhu        $v0, 0x7($s0)
/* 12CB960 80075430 00000000 */  nop
/* 12CB964 80075434 21104300 */  addu       $v0, $v0, $v1
/* 12CB968 80075438 070002A6 */  sh         $v0, 0x7($s0)
/* 12CB96C 8007543C 2000A28F */  lw         $v0, 0x20($sp)
/* 12CB970 80075440 03000396 */  lhu        $v1, 0x3($s0)
/* 12CB974 80075444 40100200 */  sll        $v0, $v0, 1
/* 12CB978 80075448 23186200 */  subu       $v1, $v1, $v0
/* 12CB97C 8007544C 090003A6 */  sh         $v1, 0x9($s0)
/* 12CB980 80075450 2400A28F */  lw         $v0, 0x24($sp)
/* 12CB984 80075454 05000396 */  lhu        $v1, 0x5($s0)
/* 12CB988 80075458 40100200 */  sll        $v0, $v0, 1
/* 12CB98C 8007545C 23186200 */  subu       $v1, $v1, $v0
/* 12CB990 80075460 0B0003A6 */  sh         $v1, 0xB($s0)
/* 12CB994 80075464 2800A28F */  lw         $v0, 0x28($sp)
/* 12CB998 80075468 07000396 */  lhu        $v1, 0x7($s0)
/* 12CB99C 8007546C 40100200 */  sll        $v0, $v0, 1
/* 12CB9A0 80075470 23186200 */  subu       $v1, $v1, $v0
/* 12CB9A4 80075474 ACD50108 */  j          .Lcutscene_66_800756B0
/* 12CB9A8 80075478 0D0003A6 */   sh        $v1, 0xD($s0)
.L8007547C_:
/* 12CB9AC 8007547C 01000292 */  lbu        $v0, 0x1($s0)
/* 12CB9B0 80075480 00000000 */  nop
/* 12CB9B4 80075484 01004224 */  addiu      $v0, $v0, 0x1
/* 12CB9B8 80075488 010002A2 */  sb         $v0, 0x1($s0)
/* 12CB9BC 8007548C FF004230 */  andi       $v0, $v0, 0xFF
/* 12CB9C0 80075490 2800422C */  sltiu      $v0, $v0, 0x28
/* 12CB9C4 80075494 71004010 */  beqz       $v0, .Lcutscene_66_8007565C
/* 12CB9C8 80075498 00000000 */   nop
/* 12CB9CC 8007549C 02000292 */  lbu        $v0, 0x2($s0)
/* 12CB9D0 800754A0 00000000 */  nop
/* 12CB9D4 800754A4 6D004010 */  beqz       $v0, .Lcutscene_66_8007565C
/* 12CB9D8 800754A8 00000000 */   nop
/* 12CB9DC 800754AC 03000296 */  lhu        $v0, 0x3($s0)
/* 12CB9E0 800754B0 0F000396 */  lhu        $v1, 0xF($s0)
/* 12CB9E4 800754B4 11000496 */  lhu        $a0, 0x11($s0)
/* 12CB9E8 800754B8 13000596 */  lhu        $a1, 0x13($s0)
/* 12CB9EC 800754BC 21104300 */  addu       $v0, $v0, $v1
/* 12CB9F0 800754C0 030002A6 */  sh         $v0, 0x3($s0)
/* 12CB9F4 800754C4 05000296 */  lhu        $v0, 0x5($s0)
/* 12CB9F8 800754C8 07000396 */  lhu        $v1, 0x7($s0)
/* 12CB9FC 800754CC 21104400 */  addu       $v0, $v0, $a0
/* 12CBA00 800754D0 21186500 */  addu       $v1, $v1, $a1
/* 12CBA04 800754D4 050002A6 */  sh         $v0, 0x5($s0)
/* 12CBA08 800754D8 9171010C */  jal        func_8005C644
/* 12CBA0C 800754DC 070003A6 */   sh        $v1, 0x7($s0)
/* 12CBA10 800754E0 0F000396 */  lhu        $v1, 0xF($s0)
/* 12CBA14 800754E4 02004230 */  andi       $v0, $v0, 0x2
/* 12CBA18 800754E8 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 12CBA1C 800754EC 21186200 */  addu       $v1, $v1, $v0
/* 12CBA20 800754F0 9171010C */  jal        func_8005C644
/* 12CBA24 800754F4 0F0003A6 */   sh        $v1, 0xF($s0)
/* 12CBA28 800754F8 11000396 */  lhu        $v1, 0x11($s0)
/* 12CBA2C 800754FC 02004230 */  andi       $v0, $v0, 0x2
/* 12CBA30 80075500 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 12CBA34 80075504 21186200 */  addu       $v1, $v1, $v0
/* 12CBA38 80075508 9171010C */  jal        func_8005C644
/* 12CBA3C 8007550C 110003A6 */   sh        $v1, 0x11($s0)
/* 12CBA40 80075510 13000396 */  lhu        $v1, 0x13($s0)
/* 12CBA44 80075514 02004230 */  andi       $v0, $v0, 0x2
/* 12CBA48 80075518 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 12CBA4C 8007551C 21186200 */  addu       $v1, $v1, $v0
/* 12CBA50 80075520 130003A6 */  sh         $v1, 0x13($s0)
/* 12CBA54 80075524 001C0300 */  sll        $v1, $v1, 16
/* 12CBA58 80075528 031C0300 */  sra        $v1, $v1, 16
/* 12CBA5C 8007552C 03006328 */  slti       $v1, $v1, 0x3
/* 12CBA60 80075530 02006014 */  bnez       $v1, .Lcutscene_66_8007553C
/* 12CBA64 80075534 02000224 */   addiu     $v0, $zero, 0x2
/* 12CBA68 80075538 130002A6 */  sh         $v0, 0x13($s0)
.Lcutscene_66_8007553C:
/* 12CBA6C 8007553C 13000286 */  lh         $v0, 0x13($s0)
/* 12CBA70 80075540 00000000 */  nop
/* 12CBA74 80075544 FCFF4228 */  slti       $v0, $v0, -0x4
/* 12CBA78 80075548 02004010 */  beqz       $v0, .Lcutscene_66_80075554
/* 12CBA7C 8007554C FCFF0224 */   addiu     $v0, $zero, -0x4
/* 12CBA80 80075550 130002A6 */  sh         $v0, 0x13($s0)
.Lcutscene_66_80075554:
/* 12CBA84 80075554 0B000292 */  lbu        $v0, 0xB($s0)
/* 12CBA88 80075558 0D000392 */  lbu        $v1, 0xD($s0)
/* 12CBA8C 8007555C FEFF4224 */  addiu      $v0, $v0, -0x2
/* 12CBA90 80075560 0B0002A2 */  sb         $v0, 0xB($s0)
/* 12CBA94 80075564 0C000292 */  lbu        $v0, 0xC($s0)
/* 12CBA98 80075568 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 12CBA9C 8007556C 0D0003A2 */  sb         $v1, 0xD($s0)
/* 12CBAA0 80075570 FEFF4224 */  addiu      $v0, $v0, -0x2
/* 12CBAA4 80075574 ACD50108 */  j          .Lcutscene_66_800756B0
/* 12CBAA8 80075578 0C0002A2 */   sb        $v0, 0xC($s0)
.L8007557C_:
/* 12CBAAC 8007557C 09000486 */  lh         $a0, 0x9($s0)
/* 12CBAB0 80075580 03000286 */  lh         $v0, 0x3($s0)
/* 12CBAB4 80075584 00000000 */  nop
/* 12CBAB8 80075588 23208200 */  subu       $a0, $a0, $v0
/* 12CBABC 8007558C 43200400 */  sra        $a0, $a0, 1
/* 12CBAC0 80075590 2000A4A7 */  sh         $a0, 0x20($sp)
/* 12CBAC4 80075594 0B000286 */  lh         $v0, 0xB($s0)
/* 12CBAC8 80075598 05000386 */  lh         $v1, 0x5($s0)
/* 12CBACC 8007559C 00000000 */  nop
/* 12CBAD0 800755A0 23104300 */  subu       $v0, $v0, $v1
/* 12CBAD4 800755A4 43100200 */  sra        $v0, $v0, 1
/* 12CBAD8 800755A8 2200A2A7 */  sh         $v0, 0x22($sp)
/* 12CBADC 800755AC 0D000286 */  lh         $v0, 0xD($s0)
/* 12CBAE0 800755B0 07000386 */  lh         $v1, 0x7($s0)
/* 12CBAE4 800755B4 00000000 */  nop
/* 12CBAE8 800755B8 23104300 */  subu       $v0, $v0, $v1
/* 12CBAEC 800755BC 43100200 */  sra        $v0, $v0, 1
/* 12CBAF0 800755C0 2400A2A7 */  sh         $v0, 0x24($sp)
/* 12CBAF4 800755C4 03000296 */  lhu        $v0, 0x3($s0)
/* 12CBAF8 800755C8 00000000 */  nop
/* 12CBAFC 800755CC 21104400 */  addu       $v0, $v0, $a0
/* 12CBB00 800755D0 030002A6 */  sh         $v0, 0x3($s0)
/* 12CBB04 800755D4 05000296 */  lhu        $v0, 0x5($s0)
/* 12CBB08 800755D8 2200A397 */  lhu        $v1, 0x22($sp)
/* 12CBB0C 800755DC 00000000 */  nop
/* 12CBB10 800755E0 21104300 */  addu       $v0, $v0, $v1
/* 12CBB14 800755E4 050002A6 */  sh         $v0, 0x5($s0)
/* 12CBB18 800755E8 07000296 */  lhu        $v0, 0x7($s0)
/* 12CBB1C 800755EC 2400A397 */  lhu        $v1, 0x24($sp)
/* 12CBB20 800755F0 00000000 */  nop
/* 12CBB24 800755F4 21104300 */  addu       $v0, $v0, $v1
/* 12CBB28 800755F8 070002A6 */  sh         $v0, 0x7($s0)
/* 12CBB2C 800755FC 09000296 */  lhu        $v0, 0x9($s0)
/* 12CBB30 80075600 2000A397 */  lhu        $v1, 0x20($sp)
/* 12CBB34 80075604 00000000 */  nop
/* 12CBB38 80075608 21104300 */  addu       $v0, $v0, $v1
/* 12CBB3C 8007560C 090002A6 */  sh         $v0, 0x9($s0)
/* 12CBB40 80075610 0B000296 */  lhu        $v0, 0xB($s0)
/* 12CBB44 80075614 2200A397 */  lhu        $v1, 0x22($sp)
/* 12CBB48 80075618 00000000 */  nop
/* 12CBB4C 8007561C 21104300 */  addu       $v0, $v0, $v1
/* 12CBB50 80075620 0D000396 */  lhu        $v1, 0xD($s0)
/* 12CBB54 80075624 0B0002A6 */  sh         $v0, 0xB($s0)
/* 12CBB58 80075628 01000292 */  lbu        $v0, 0x1($s0)
/* 12CBB5C 8007562C 2400A497 */  lhu        $a0, 0x24($sp)
/* 12CBB60 80075630 01004224 */  addiu      $v0, $v0, 0x1
/* 12CBB64 80075634 21186400 */  addu       $v1, $v1, $a0
/* 12CBB68 80075638 010002A2 */  sb         $v0, 0x1($s0)
/* 12CBB6C 8007563C FF004230 */  andi       $v0, $v0, 0xFF
/* 12CBB70 80075640 1800422C */  sltiu      $v0, $v0, 0x18
/* 12CBB74 80075644 05004010 */  beqz       $v0, .Lcutscene_66_8007565C
/* 12CBB78 80075648 0D0003A6 */   sh        $v1, 0xD($s0)
/* 12CBB7C 8007564C 02000292 */  lbu        $v0, 0x2($s0)
/* 12CBB80 80075650 00000000 */  nop
/* 12CBB84 80075654 05004014 */  bnez       $v0, .Lcutscene_66_8007566C
/* 12CBB88 80075658 00000000 */   nop
.Lcutscene_66_8007565C:
/* 12CBB8C 8007565C 4159010C */  jal        func_80056504
/* 12CBB90 80075660 21204002 */   addu      $a0, $s2, $zero
/* 12CBB94 80075664 ADD50108 */  j          .Lcutscene_66_800756B4
/* 12CBB98 80075668 20001026 */   addiu     $s0, $s0, 0x20
.Lcutscene_66_8007566C:
/* 12CBB9C 8007566C 11000292 */  lbu        $v0, 0x11($s0)
/* 12CBBA0 80075670 15000392 */  lbu        $v1, 0x15($s0)
/* 12CBBA4 80075674 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 12CBBA8 80075678 110002A2 */  sb         $v0, 0x11($s0)
/* 12CBBAC 8007567C 10000292 */  lbu        $v0, 0x10($s0)
/* 12CBBB0 80075680 FDFF6324 */  addiu      $v1, $v1, -0x3
/* 12CBBB4 80075684 150003A2 */  sb         $v1, 0x15($s0)
/* 12CBBB8 80075688 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 12CBBBC 8007568C 100002A2 */  sb         $v0, 0x10($s0)
/* 12CBBC0 80075690 14000292 */  lbu        $v0, 0x14($s0)
/* 12CBBC4 80075694 13000392 */  lbu        $v1, 0x13($s0)
/* 12CBBC8 80075698 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 12CBBCC 8007569C 140002A2 */  sb         $v0, 0x14($s0)
/* 12CBBD0 800756A0 0600622C */  sltiu      $v0, $v1, 0x6
/* 12CBBD4 800756A4 02004014 */  bnez       $v0, .Lcutscene_66_800756B0
/* 12CBBD8 800756A8 FAFF6224 */   addiu     $v0, $v1, -0x6
/* 12CBBDC 800756AC 130002A2 */  sb         $v0, 0x13($s0)
.Lcutscene_66_800756B0:
/* 12CBBE0 800756B0 20001026 */  addiu      $s0, $s0, 0x20
.Lcutscene_66_800756B4:
/* 12CBBE4 800756B4 20009426 */  addiu      $s4, $s4, 0x20
/* 12CBBE8 800756B8 20007326 */  addiu      $s3, $s3, 0x20
/* 12CBBEC 800756BC 00000492 */  lbu        $a0, 0x0($s0)
/* 12CBBF0 800756C0 FF000224 */  addiu      $v0, $zero, 0xFF
/* 12CBBF4 800756C4 FF008330 */  andi       $v1, $a0, 0xFF
/* 12CBBF8 800756C8 BDFC6214 */  bne        $v1, $v0, .Lcutscene_66_800749C0
/* 12CBBFC 800756CC 20005226 */   addiu     $s2, $s2, 0x20
/* 12CBC00 800756D0 21104002 */  addu       $v0, $s2, $zero
.Lcutscene_66_800756D4:
/* 12CBC04 800756D4 6000BF8F */  lw         $ra, 0x60($sp)
/* 12CBC08 800756D8 5C00B78F */  lw         $s7, 0x5C($sp)
/* 12CBC0C 800756DC 5800B68F */  lw         $s6, 0x58($sp)
/* 12CBC10 800756E0 5400B58F */  lw         $s5, 0x54($sp)
/* 12CBC14 800756E4 5000B48F */  lw         $s4, 0x50($sp)
/* 12CBC18 800756E8 4C00B38F */  lw         $s3, 0x4C($sp)
/* 12CBC1C 800756EC 4800B28F */  lw         $s2, 0x48($sp)
/* 12CBC20 800756F0 4400B18F */  lw         $s1, 0x44($sp)
/* 12CBC24 800756F4 4000B08F */  lw         $s0, 0x40($sp)
/* 12CBC28 800756F8 6800BD27 */  addiu      $sp, $sp, 0x68
/* 12CBC2C 800756FC 0800E003 */  jr         $ra
/* 12CBC30 80075700 00000000 */   nop
.size func_cutscene_66_80074960, . - func_cutscene_66_80074960
