name: Build and verify checksums

on:
  pull_request:

jobs:
  build:
    name: "Build and verify checksums (antipiracy = ${{ matrix.antipiracy }})"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        antipiracy: [true, false]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Docker image
        run: docker build -t s3_dev_env .

      - name: Run build
        run: |
          docker run --rm -v "$PWD:/s3" s3_dev_env \
            python3 build_multiproc.py ${{ matrix.antipiracy && '--antipiracy --compile-dragonbreath' || '' }}

