.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_level_44_800746D0
/* 8B47C00 800746D0 98FC0780 */ .word .L8007FC98_
/* 8B47C04 800746D4 CCFE0780 */ .word .L8007FECC_
/* 8B47C08 800746D8 70010880 */ .word .L80080170_
/* 8B47C0C 800746DC 94010880 */ .word .Llevel_44_80080194
/* 8B47C10 800746E0 94010880 */ .word .Llevel_44_80080194
/* 8B47C14 800746E4 94010880 */ .word .Llevel_44_80080194
/* 8B47C18 800746E8 94010880 */ .word .Llevel_44_80080194
/* 8B47C1C 800746EC 94010880 */ .word .Llevel_44_80080194
/* 8B47C20 800746F0 94010880 */ .word .Llevel_44_80080194
/* 8B47C24 800746F4 94010880 */ .word .Llevel_44_80080194
/* 8B47C28 800746F8 94010880 */ .word .Llevel_44_80080194
/* 8B47C2C 800746FC 94010880 */ .word .Llevel_44_80080194
/* 8B47C30 80074700 94010880 */ .word .Llevel_44_80080194
/* 8B47C34 80074704 94010880 */ .word .Llevel_44_80080194
/* 8B47C38 80074708 94010880 */ .word .Llevel_44_80080194
/* 8B47C3C 8007470C 94010880 */ .word .Llevel_44_80080194
/* 8B47C40 80074710 94010880 */ .word .Llevel_44_80080194
/* 8B47C44 80074714 94010880 */ .word .Llevel_44_80080194
/* 8B47C48 80074718 94010880 */ .word .Llevel_44_80080194
/* 8B47C4C 8007471C 94010880 */ .word .Llevel_44_80080194
/* 8B47C50 80074720 E4FC0780 */ .word .L8007FCE4_
/* 8B47C54 80074724 94010880 */ .word .Llevel_44_80080194
/* 8B47C58 80074728 74FE0780 */ .word .L8007FE74_
.size jtbl_level_44_800746D0, . - jtbl_level_44_800746D0


.section .text
/* Generated by spimdisasm 1.28.1 */

glabel func_level_44_8007FB5C
/* 8B5308C 8007FB5C 98FFBD27 */  addiu      $sp, $sp, -0x68
/* 8B53090 8007FB60 5400B3AF */  sw         $s3, 0x54($sp)
/* 8B53094 8007FB64 21988000 */  addu       $s3, $a0, $zero
/* 8B53098 8007FB68 8A00033C */  lui        $v1, (0x8A0000 >> 16)
/* 8B5309C 8007FB6C 6000BFAF */  sw         $ra, 0x60($sp)
/* 8B530A0 8007FB70 5C00B5AF */  sw         $s5, 0x5C($sp)
/* 8B530A4 8007FB74 5800B4AF */  sw         $s4, 0x58($sp)
/* 8B530A8 8007FB78 5000B2AF */  sw         $s2, 0x50($sp)
/* 8B530AC 8007FB7C 4C00B1AF */  sw         $s1, 0x4C($sp)
/* 8B530B0 8007FB80 4800B0AF */  sw         $s0, 0x48($sp)
/* 8B530B4 8007FB84 1800628E */  lw         $v0, 0x18($s3)
/* 8B530B8 8007FB88 0000758E */  lw         $s5, 0x0($s3)
/* 8B530BC 8007FB8C 24104300 */  and        $v0, $v0, $v1
/* 8B530C0 8007FB90 36004010 */  beqz       $v0, .Llevel_44_8007FC6C
/* 8B530C4 8007FB94 00000000 */   nop
/* 8B530C8 8007FB98 1000A58E */  lw         $a1, 0x10($s5)
/* 8B530CC 8007FB9C F0EF000C */  jal        func_8003BFC0
/* 8B530D0 8007FBA0 00000000 */   nop
/* 8B530D4 8007FBA4 05004010 */  beqz       $v0, .Llevel_44_8007FBBC
/* 8B530D8 8007FBA8 21206002 */   addu      $a0, $s3, $zero
/* 8B530DC 8007FBAC 1000A48E */  lw         $a0, 0x10($s5)
/* 8B530E0 8007FBB0 9CEF000C */  jal        func_8003BE70
/* 8B530E4 8007FBB4 00000000 */   nop
/* 8B530E8 8007FBB8 21206002 */  addu       $a0, $s3, $zero
.Llevel_44_8007FBBC:
/* 8B530EC 8007FBBC 02000524 */  addiu      $a1, $zero, 0x2
/* 8B530F0 8007FBC0 21300000 */  addu       $a2, $zero, $zero
/* 8B530F4 8007FBC4 FFFF0224 */  addiu      $v0, $zero, -0x1
/* 8B530F8 8007FBC8 AFEE000C */  jal        func_8003BABC
/* 8B530FC 8007FBCC 1000A2AE */   sw        $v0, 0x10($s5)
/* 8B53100 8007FBD0 21206002 */  addu       $a0, $s3, $zero
/* 8B53104 8007FBD4 21280000 */  addu       $a1, $zero, $zero
/* 8B53108 8007FBD8 21300000 */  addu       $a2, $zero, $zero
/* 8B5310C 8007FBDC 9ADA000C */  jal        func_80036A68
/* 8B53110 8007FBE0 21380000 */   addu      $a3, $zero, $zero
/* 8B53114 8007FBE4 05000424 */  addiu      $a0, $zero, 0x5
/* 8B53118 8007FBE8 13010524 */  addiu      $a1, $zero, 0x113
/* 8B5311C 8007FBEC 00010224 */  addiu      $v0, $zero, 0x100
/* 8B53120 8007FBF0 1000A0AF */  sw         $zero, 0x10($sp)
/* 8B53124 8007FBF4 1400A2AF */  sw         $v0, 0x14($sp)
/* 8B53128 8007FBF8 0C00A78E */  lw         $a3, 0xC($s5)
/* 8B5312C 8007FBFC 0780023C */  lui        $v0, %hi(SpawnFragments)
/* 8B53130 8007FC00 5C43428C */  lw         $v0, %lo(SpawnFragments)($v0)
/* 8B53134 8007FC04 00000000 */  nop
/* 8B53138 8007FC08 09F84000 */  jalr       $v0
/* 8B5313C 8007FC0C 21306002 */   addu      $a2, $s3, $zero
/* 8B53140 8007FC10 10000424 */  addiu      $a0, $zero, 0x10
/* 8B53144 8007FC14 46000524 */  addiu      $a1, $zero, 0x46
/* 8B53148 8007FC18 0C006626 */  addiu      $a2, $s3, 0xC
/* 8B5314C 8007FC1C 0780023C */  lui        $v0, %hi(SpawnParticle)
/* 8B53150 8007FC20 E442428C */  lw         $v0, %lo(SpawnParticle)($v0)
/* 8B53154 8007FC24 00000000 */  nop
/* 8B53158 8007FC28 09F84000 */  jalr       $v0
/* 8B5315C 8007FC2C 20000724 */   addiu     $a3, $zero, 0x20
/* 8B53160 8007FC30 21206002 */  addu       $a0, $s3, $zero
/* 8B53164 8007FC34 04000524 */  addiu      $a1, $zero, 0x4
/* 8B53168 8007FC38 0800A38E */  lw         $v1, 0x8($s5)
/* 8B5316C 8007FC3C 0200023C */  lui        $v0, (0x20000 >> 16)
/* 8B53170 8007FC40 4957010C */  jal        func_80055D24
/* 8B53174 8007FC44 180062AC */   sw        $v0, 0x18($v1)
/* 8B53178 8007FC48 80EE000C */  jal        func_8003BA00
/* 8B5317C 8007FC4C 21206002 */   addu      $a0, $s3, $zero
/* 8B53180 8007FC50 21206002 */  addu       $a0, $s3, $zero
/* 8B53184 8007FC54 6EDA000C */  jal        func_800369B8
/* 8B53188 8007FC58 20000524 */   addiu     $a1, $zero, 0x20
/* 8B5318C 8007FC5C C656010C */  jal        func_80055B18
/* 8B53190 8007FC60 21206002 */   addu      $a0, $s3, $zero
/* 8B53194 8007FC64 65000208 */  j          .Llevel_44_80080194
/* 8B53198 8007FC68 00000000 */   nop
.Llevel_44_8007FC6C:
/* 8B5319C 8007FC6C 48006392 */  lbu        $v1, 0x48($s3)
/* 8B531A0 8007FC70 00000000 */  nop
/* 8B531A4 8007FC74 1700622C */  sltiu      $v0, $v1, 0x17
/* 8B531A8 8007FC78 46014010 */  beqz       $v0, .Llevel_44_80080194
/* 8B531AC 8007FC7C 80100300 */   sll       $v0, $v1, 2
/* 8B531B0 8007FC80 0780013C */  lui        $at, %hi(jtbl_level_44_800746D0)
/* 8B531B4 8007FC84 21082200 */  addu       $at, $at, $v0
/* 8B531B8 8007FC88 D046228C */  lw         $v0, %lo(jtbl_level_44_800746D0)($at)
/* 8B531BC 8007FC8C 00000000 */  nop
/* 8B531C0 8007FC90 08004000 */  jr         $v0
/* 8B531C4 8007FC94 00000000 */   nop
.L8007FC98_:
/* 8B531C8 8007FC98 43020424 */  addiu      $a0, $zero, 0x243
/* 8B531CC 8007FC9C 46006292 */  lbu        $v0, 0x46($s3)
/* 8B531D0 8007FCA0 0780033C */  lui        $v1, %hi(SpawnMoby)
/* 8B531D4 8007FCA4 E042638C */  lw         $v1, %lo(SpawnMoby)($v1)
/* 8B531D8 8007FCA8 21286002 */  addu       $a1, $s3, $zero
/* 8B531DC 8007FCAC 09F86000 */  jalr       $v1
/* 8B531E0 8007FCB0 0400A2AE */   sw        $v0, 0x4($s5)
/* 8B531E4 8007FCB4 21184000 */  addu       $v1, $v0, $zero
/* 8B531E8 8007FCB8 36016010 */  beqz       $v1, .Llevel_44_80080194
/* 8B531EC 8007FCBC 0800A3AE */   sw        $v1, 0x8($s5)
/* 8B531F0 8007FCC0 46006292 */  lbu        $v0, 0x46($s3)
/* 8B531F4 8007FCC4 00000000 */  nop
/* 8B531F8 8007FCC8 460062A0 */  sb         $v0, 0x46($v1)
/* 8B531FC 8007FCCC 4C006292 */  lbu        $v0, 0x4C($s3)
/* 8B53200 8007FCD0 00000000 */  nop
/* 8B53204 8007FCD4 4C0062A0 */  sb         $v0, 0x4C($v1)
/* 8B53208 8007FCD8 4A006292 */  lbu        $v0, 0x4A($s3)
/* 8B5320C 8007FCDC 63000208 */  j          .Llevel_44_8008018C
/* 8B53210 8007FCE0 4A0062A0 */   sb        $v0, 0x4A($v1)
.L8007FCE4_:
/* 8B53214 8007FCE4 1800A427 */  addiu      $a0, $sp, 0x18
/* 8B53218 8007FCE8 0780113C */  lui        $s1, %hi(D_80070328 + 0x98)
/* 8B5321C 8007FCEC C0033126 */  addiu      $s1, $s1, %lo(D_80070328 + 0x98)
/* 8B53220 8007FCF0 5E3C010C */  jal        func_8004F178
/* 8B53224 8007FCF4 21282002 */   addu      $a1, $s1, $zero
/* 8B53228 8007FCF8 1800A427 */  addiu      $a0, $sp, 0x18
/* 8B5322C 8007FCFC 1800A38F */  lw         $v1, 0x18($sp)
/* 8B53230 8007FD00 06000524 */  addiu      $a1, $zero, 0x6
/* 8B53234 8007FD04 00110300 */  sll        $v0, $v1, 4
/* 8B53238 8007FD08 23104300 */  subu       $v0, $v0, $v1
/* 8B5323C 8007FD0C 1C00A38F */  lw         $v1, 0x1C($sp)
/* 8B53240 8007FD10 40100200 */  sll        $v0, $v0, 1
/* 8B53244 8007FD14 1800A2AF */  sw         $v0, 0x18($sp)
/* 8B53248 8007FD18 00110300 */  sll        $v0, $v1, 4
/* 8B5324C 8007FD1C 23104300 */  subu       $v0, $v0, $v1
/* 8B53250 8007FD20 2000A38F */  lw         $v1, 0x20($sp)
/* 8B53254 8007FD24 40100200 */  sll        $v0, $v0, 1
/* 8B53258 8007FD28 1C00A2AF */  sw         $v0, 0x1C($sp)
/* 8B5325C 8007FD2C 00110300 */  sll        $v0, $v1, 4
/* 8B53260 8007FD30 23104300 */  subu       $v0, $v0, $v1
/* 8B53264 8007FD34 40100200 */  sll        $v0, $v0, 1
/* 8B53268 8007FD38 443C010C */  jal        func_8004F110
/* 8B5326C 8007FD3C 2000A2AF */   sw        $v0, 0x20($sp)
/* 8B53270 8007FD40 1800A427 */  addiu      $a0, $sp, 0x18
/* 8B53274 8007FD44 21288000 */  addu       $a1, $a0, $zero
/* 8B53278 8007FD48 68FF3426 */  addiu      $s4, $s1, -0x98
/* 8B5327C 8007FD4C 653C010C */  jal        func_8004F194
/* 8B53280 8007FD50 21308002 */   addu      $a2, $s4, $zero
/* 8B53284 8007FD54 0C007226 */  addiu      $s2, $s3, 0xC
/* 8B53288 8007FD58 21204002 */  addu       $a0, $s2, $zero
/* 8B5328C 8007FD5C CD3C010C */  jal        func_8004F334
/* 8B53290 8007FD60 1800A527 */   addiu     $a1, $sp, 0x18
/* 8B53294 8007FD64 21804000 */  addu       $s0, $v0, $zero
/* 8B53298 8007FD68 0040022A */  slti       $v0, $s0, 0x4000
/* 8B5329C 8007FD6C 09004010 */  beqz       $v0, .Llevel_44_8007FD94
/* 8B532A0 8007FD70 21206002 */   addu      $a0, $s3, $zero
/* 8B532A4 8007FD74 04000524 */  addiu      $a1, $zero, 0x4
/* 8B532A8 8007FD78 02000624 */  addiu      $a2, $zero, 0x2
/* 8B532AC 8007FD7C CFD5000C */  jal        func_8003573C
/* 8B532B0 8007FD80 01000724 */   addiu     $a3, $zero, 0x1
/* 8B532B4 8007FD84 0800A38E */  lw         $v1, 0x8($s5)
/* 8B532B8 8007FD88 46006292 */  lbu        $v0, 0x46($s3)
/* 8B532BC 8007FD8C 00000000 */  nop
/* 8B532C0 8007FD90 460062A0 */  sb         $v0, 0x46($v1)
.Llevel_44_8007FD94:
/* 8B532C4 8007FD94 B036022A */  slti       $v0, $s0, 0x36B0
/* 8B532C8 8007FD98 FE004010 */  beqz       $v0, .Llevel_44_80080194
/* 8B532CC 8007FD9C 21300000 */   addu      $a2, $zero, $zero
/* 8B532D0 8007FDA0 0C00638E */  lw         $v1, 0xC($s3)
/* 8B532D4 8007FDA4 0780043C */  lui        $a0, %hi(D_8006E020)
/* 8B532D8 8007FDA8 20E0848C */  lw         $a0, %lo(D_8006E020)($a0)
/* 8B532DC 8007FDAC 1000628E */  lw         $v0, 0x10($s3)
/* 8B532E0 8007FDB0 0780053C */  lui        $a1, %hi(D_8006E024)
/* 8B532E4 8007FDB4 24E0A58C */  lw         $a1, %lo(D_8006E024)($a1)
/* 8B532E8 8007FDB8 23206400 */  subu       $a0, $v1, $a0
/* 8B532EC 8007FDBC 203A010C */  jal        func_8004E880
/* 8B532F0 8007FDC0 23284500 */   subu      $a1, $v0, $a1
/* 8B532F4 8007FDC4 0780043C */  lui        $a0, %hi(D_8006E040)
/* 8B532F8 8007FDC8 40E08494 */  lhu        $a0, %lo(D_8006E040)($a0)
/* 8B532FC 8007FDCC 21284000 */  addu       $a1, $v0, $zero
/* 8B53300 8007FDD0 00240400 */  sll        $a0, $a0, 16
/* 8B53304 8007FDD4 993C010C */  jal        func_8004F264
/* 8B53308 8007FDD8 03250400 */   sra       $a0, $a0, 20
/* 8B5330C 8007FDDC 18004228 */  slti       $v0, $v0, 0x18
/* 8B53310 8007FDE0 EC004010 */  beqz       $v0, .Llevel_44_80080194
/* 8B53314 8007FDE4 21300000 */   addu      $a2, $zero, $zero
/* 8B53318 8007FDE8 68FF238E */  lw         $v1, -0x98($s1)
/* 8B5331C 8007FDEC 0C00648E */  lw         $a0, 0xC($s3)
/* 8B53320 8007FDF0 0780023C */  lui        $v0, %hi(D_80070328 + 4)
/* 8B53324 8007FDF4 2C03428C */  lw         $v0, %lo(D_80070328 + 4)($v0)
/* 8B53328 8007FDF8 1000658E */  lw         $a1, 0x10($s3)
/* 8B5332C 8007FDFC 23206400 */  subu       $a0, $v1, $a0
/* 8B53330 8007FE00 203A010C */  jal        func_8004E880
/* 8B53334 8007FE04 23284500 */   subu      $a1, $v0, $a1
/* 8B53338 8007FE08 46006492 */  lbu        $a0, 0x46($s3)
/* 8B5333C 8007FE0C 993C010C */  jal        func_8004F264
/* 8B53340 8007FE10 21284000 */   addu      $a1, $v0, $zero
/* 8B53344 8007FE14 10004228 */  slti       $v0, $v0, 0x10
/* 8B53348 8007FE18 DE004010 */  beqz       $v0, .Llevel_44_80080194
/* 8B5334C 8007FE1C 21204002 */   addu      $a0, $s2, $zero
/* 8B53350 8007FE20 21288002 */  addu       $a1, $s4, $zero
/* 8B53354 8007FE24 1400628E */  lw         $v0, 0x14($s3)
/* 8B53358 8007FE28 21300000 */  addu       $a2, $zero, $zero
/* 8B5335C 8007FE2C 20034224 */  addiu      $v0, $v0, 0x320
/* 8B53360 8007FE30 8E4F000C */  jal        func_80013E38
/* 8B53364 8007FE34 140062AE */   sw        $v0, 0x14($s3)
/* 8B53368 8007FE38 09004010 */  beqz       $v0, .Llevel_44_8007FE60
/* 8B5336C 8007FE3C 01000324 */   addiu     $v1, $zero, 0x1
/* 8B53370 8007FE40 0800A28E */  lw         $v0, 0x8($s5)
/* 8B53374 8007FE44 00000000 */  nop
/* 8B53378 8007FE48 480043A0 */  sb         $v1, 0x48($v0)
/* 8B5337C 8007FE4C 0800A48E */  lw         $a0, 0x8($s5)
/* 8B53380 8007FE50 D0D3000C */  jal        func_80034F40
/* 8B53384 8007FE54 01000524 */   addiu     $a1, $zero, 0x1
/* 8B53388 8007FE58 16000224 */  addiu      $v0, $zero, 0x16
/* 8B5338C 8007FE5C 480062A2 */  sb         $v0, 0x48($s3)
.Llevel_44_8007FE60:
/* 8B53390 8007FE60 1400628E */  lw         $v0, 0x14($s3)
/* 8B53394 8007FE64 00000000 */  nop
/* 8B53398 8007FE68 E0FC4224 */  addiu      $v0, $v0, -0x320
/* 8B5339C 8007FE6C 65000208 */  j          .Llevel_44_80080194
/* 8B533A0 8007FE70 140062AE */   sw        $v0, 0x14($s3)
.L8007FE74_:
/* 8B533A4 8007FE74 21206002 */  addu       $a0, $s3, $zero
/* 8B533A8 8007FE78 04000524 */  addiu      $a1, $zero, 0x4
/* 8B533AC 8007FE7C 02000624 */  addiu      $a2, $zero, 0x2
/* 8B533B0 8007FE80 CFD5000C */  jal        func_8003573C
/* 8B533B4 8007FE84 01000724 */   addiu     $a3, $zero, 0x1
/* 8B533B8 8007FE88 0800A38E */  lw         $v1, 0x8($s5)
/* 8B533BC 8007FE8C 46006292 */  lbu        $v0, 0x46($s3)
/* 8B533C0 8007FE90 00000000 */  nop
/* 8B533C4 8007FE94 460062A0 */  sb         $v0, 0x46($v1)
/* 8B533C8 8007FE98 0800A28E */  lw         $v0, 0x8($s5)
/* 8B533CC 8007FE9C 00000000 */  nop
/* 8B533D0 8007FEA0 48004390 */  lbu        $v1, 0x48($v0)
/* 8B533D4 8007FEA4 02000224 */  addiu      $v0, $zero, 0x2
/* 8B533D8 8007FEA8 BA006214 */  bne        $v1, $v0, .Llevel_44_80080194
/* 8B533DC 8007FEAC 21206002 */   addu      $a0, $s3, $zero
/* 8B533E0 8007FEB0 E0D3000C */  jal        func_80034F80
/* 8B533E4 8007FEB4 01000524 */   addiu     $a1, $zero, 0x1
/* 8B533E8 8007FEB8 46006392 */  lbu        $v1, 0x46($s3)
/* 8B533EC 8007FEBC 01000224 */  addiu      $v0, $zero, 0x1
/* 8B533F0 8007FEC0 480062A2 */  sb         $v0, 0x48($s3)
/* 8B533F4 8007FEC4 65000208 */  j          .Llevel_44_80080194
/* 8B533F8 8007FEC8 0400A3AE */   sw        $v1, 0x4($s5)
.L8007FECC_:
/* 8B533FC 8007FECC 1000A58E */  lw         $a1, 0x10($s5)
/* 8B53400 8007FED0 F0EF000C */  jal        func_8003BFC0
/* 8B53404 8007FED4 21206002 */   addu      $a0, $s3, $zero
/* 8B53408 8007FED8 05004014 */  bnez       $v0, .Llevel_44_8007FEF0
/* 8B5340C 8007FEDC 21206002 */   addu      $a0, $s3, $zero
/* 8B53410 8007FEE0 21280000 */  addu       $a1, $zero, $zero
/* 8B53414 8007FEE4 AFEE000C */  jal        func_8003BABC
/* 8B53418 8007FEE8 04000624 */   addiu     $a2, $zero, 0x4
/* 8B5341C 8007FEEC 1000A2AE */  sw         $v0, 0x10($s5)
.Llevel_44_8007FEF0:
/* 8B53420 8007FEF0 0000A296 */  lhu        $v0, 0x0($s5)
/* 8B53424 8007FEF4 00000000 */  nop
/* 8B53428 8007FEF8 03004224 */  addiu      $v0, $v0, 0x3
/* 8B5342C 8007FEFC 0000A2A6 */  sh         $v0, 0x0($s5)
/* 8B53430 8007FF00 00140200 */  sll        $v0, $v0, 16
/* 8B53434 8007FF04 031C0200 */  sra        $v1, $v0, 16
/* 8B53438 8007FF08 00016228 */  slti       $v0, $v1, 0x100
/* 8B5343C 8007FF0C 25004014 */  bnez       $v0, .Llevel_44_8007FFA4
/* 8B53440 8007FF10 40100300 */   sll       $v0, $v1, 1
/* 8B53444 8007FF14 1000A58E */  lw         $a1, 0x10($s5)
/* 8B53448 8007FF18 F0EF000C */  jal        func_8003BFC0
/* 8B5344C 8007FF1C 21206002 */   addu      $a0, $s3, $zero
/* 8B53450 8007FF20 04004010 */  beqz       $v0, .Llevel_44_8007FF34
/* 8B53454 8007FF24 00000000 */   nop
/* 8B53458 8007FF28 1000A48E */  lw         $a0, 0x10($s5)
/* 8B5345C 8007FF2C 9CEF000C */  jal        func_8003BE70
/* 8B53460 8007FF30 00000000 */   nop
.Llevel_44_8007FF34:
/* 8B53464 8007FF34 0000A386 */  lh         $v1, 0x0($s5)
/* 8B53468 8007FF38 FFFF0224 */  addiu      $v0, $zero, -0x1
/* 8B5346C 8007FF3C 1000A2AE */  sw         $v0, 0x10($s5)
/* 8B53470 8007FF40 02006104 */  bgez       $v1, .Llevel_44_8007FF4C
/* 8B53474 8007FF44 21106000 */   addu      $v0, $v1, $zero
/* 8B53478 8007FF48 FF006224 */  addiu      $v0, $v1, 0xFF
.Llevel_44_8007FF4C:
/* 8B5347C 8007FF4C 21206002 */  addu       $a0, $s3, $zero
/* 8B53480 8007FF50 02000524 */  addiu      $a1, $zero, 0x2
/* 8B53484 8007FF54 03120200 */  sra        $v0, $v0, 8
/* 8B53488 8007FF58 00120200 */  sll        $v0, $v0, 8
/* 8B5348C 8007FF5C 23106200 */  subu       $v0, $v1, $v0
/* 8B53490 8007FF60 0000A2A6 */  sh         $v0, 0x0($s5)
/* 8B53494 8007FF64 02000224 */  addiu      $v0, $zero, 0x2
/* 8B53498 8007FF68 D0D3000C */  jal        func_80034F40
/* 8B5349C 8007FF6C 480062A2 */   sb        $v0, 0x48($s3)
/* 8B534A0 8007FF70 0800A38E */  lw         $v1, 0x8($s5)
/* 8B534A4 8007FF74 04000224 */  addiu      $v0, $zero, 0x4
/* 8B534A8 8007FF78 480062A0 */  sb         $v0, 0x48($v1)
/* 8B534AC 8007FF7C 0800A48E */  lw         $a0, 0x8($s5)
/* 8B534B0 8007FF80 D0D3000C */  jal        func_80034F40
/* 8B534B4 8007FF84 04000524 */   addiu     $a1, $zero, 0x4
/* 8B534B8 8007FF88 21206002 */  addu       $a0, $s3, $zero
/* 8B534BC 8007FF8C 01000524 */  addiu      $a1, $zero, 0x1
/* 8B534C0 8007FF90 21300000 */  addu       $a2, $zero, $zero
/* 8B534C4 8007FF94 AFEE000C */  jal        func_8003BABC
/* 8B534C8 8007FF98 0200A0A6 */   sh        $zero, 0x2($s5)
/* 8B534CC 8007FF9C 65000208 */  j          .Llevel_44_80080194
/* 8B534D0 8007FFA0 00000000 */   nop
.Llevel_44_8007FFA4:
/* 8B534D4 8007FFA4 2800B027 */  addiu      $s0, $sp, 0x28
/* 8B534D8 8007FFA8 21200002 */  addu       $a0, $s0, $zero
/* 8B534DC 8007FFAC 0780113C */  lui        $s1, %hi(D_80070328 + 0x98)
/* 8B534E0 8007FFB0 C0033126 */  addiu      $s1, $s1, %lo(D_80070328 + 0x98)
/* 8B534E4 8007FFB4 0680013C */  lui        $at, %hi(D_800658A0)
/* 8B534E8 8007FFB8 21082200 */  addu       $at, $at, $v0
/* 8B534EC 8007FFBC A0582294 */  lhu        $v0, %lo(D_800658A0)($at)
/* 8B534F0 8007FFC0 0400A38E */  lw         $v1, 0x4($s5)
/* 8B534F4 8007FFC4 00140200 */  sll        $v0, $v0, 16
/* 8B534F8 8007FFC8 C3150200 */  sra        $v0, $v0, 23
/* 8B534FC 8007FFCC 21104300 */  addu       $v0, $v0, $v1
/* 8B53500 8007FFD0 460062A2 */  sb         $v0, 0x46($s3)
/* 8B53504 8007FFD4 0800A38E */  lw         $v1, 0x8($s5)
/* 8B53508 8007FFD8 21282002 */  addu       $a1, $s1, $zero
/* 8B5350C 8007FFDC 5E3C010C */  jal        func_8004F178
/* 8B53510 8007FFE0 460062A0 */   sb        $v0, 0x46($v1)
/* 8B53514 8007FFE4 21200002 */  addu       $a0, $s0, $zero
/* 8B53518 8007FFE8 2800A38F */  lw         $v1, 0x28($sp)
/* 8B5351C 8007FFEC 06000524 */  addiu      $a1, $zero, 0x6
/* 8B53520 8007FFF0 00110300 */  sll        $v0, $v1, 4
/* 8B53524 8007FFF4 23104300 */  subu       $v0, $v0, $v1
/* 8B53528 8007FFF8 2C00A38F */  lw         $v1, 0x2C($sp)
/* 8B5352C 8007FFFC 40100200 */  sll        $v0, $v0, 1
/* 8B53530 80080000 2800A2AF */  sw         $v0, 0x28($sp)
/* 8B53534 80080004 00110300 */  sll        $v0, $v1, 4
/* 8B53538 80080008 23104300 */  subu       $v0, $v0, $v1
/* 8B5353C 8008000C 3000A38F */  lw         $v1, 0x30($sp)
/* 8B53540 80080010 40100200 */  sll        $v0, $v0, 1
/* 8B53544 80080014 2C00A2AF */  sw         $v0, 0x2C($sp)
/* 8B53548 80080018 00110300 */  sll        $v0, $v1, 4
/* 8B5354C 8008001C 23104300 */  subu       $v0, $v0, $v1
/* 8B53550 80080020 40100200 */  sll        $v0, $v0, 1
/* 8B53554 80080024 443C010C */  jal        func_8004F110
/* 8B53558 80080028 3000A2AF */   sw        $v0, 0x30($sp)
/* 8B5355C 8008002C 21200002 */  addu       $a0, $s0, $zero
/* 8B53560 80080030 21280002 */  addu       $a1, $s0, $zero
/* 8B53564 80080034 653C010C */  jal        func_8004F194
/* 8B53568 80080038 68FF2626 */   addiu     $a2, $s1, -0x98
/* 8B5356C 8008003C 0C006426 */  addiu      $a0, $s3, 0xC
/* 8B53570 80080040 CD3C010C */  jal        func_8004F334
/* 8B53574 80080044 21280002 */   addu      $a1, $s0, $zero
/* 8B53578 80080048 B1364228 */  slti       $v0, $v0, 0x36B1
/* 8B5357C 8008004C 18004014 */  bnez       $v0, .Llevel_44_800800B0
/* 8B53580 80080050 00000000 */   nop
/* 8B53584 80080054 1000A58E */  lw         $a1, 0x10($s5)
/* 8B53588 80080058 F0EF000C */  jal        func_8003BFC0
/* 8B5358C 8008005C 21206002 */   addu      $a0, $s3, $zero
/* 8B53590 80080060 05004010 */  beqz       $v0, .Llevel_44_80080078
/* 8B53594 80080064 21206002 */   addu      $a0, $s3, $zero
/* 8B53598 80080068 1000A48E */  lw         $a0, 0x10($s5)
/* 8B5359C 8008006C 9CEF000C */  jal        func_8003BE70
/* 8B535A0 80080070 00000000 */   nop
/* 8B535A4 80080074 21206002 */  addu       $a0, $s3, $zero
.Llevel_44_80080078:
/* 8B535A8 80080078 21280000 */  addu       $a1, $zero, $zero
/* 8B535AC 8008007C FFFF0224 */  addiu      $v0, $zero, -0x1
/* 8B535B0 80080080 D0D3000C */  jal        func_80034F40
/* 8B535B4 80080084 1000A2AE */   sw        $v0, 0x10($s5)
/* 8B535B8 80080088 14000224 */  addiu      $v0, $zero, 0x14
/* 8B535BC 8008008C 480062A2 */  sb         $v0, 0x48($s3)
/* 8B535C0 80080090 0800A48E */  lw         $a0, 0x8($s5)
/* 8B535C4 80080094 D0D3000C */  jal        func_80034F40
/* 8B535C8 80080098 03000524 */   addiu     $a1, $zero, 0x3
/* 8B535CC 8008009C 0800A38E */  lw         $v1, 0x8($s5)
/* 8B535D0 800800A0 03000224 */  addiu      $v0, $zero, 0x3
/* 8B535D4 800800A4 480062A0 */  sb         $v0, 0x48($v1)
/* 8B535D8 800800A8 65000208 */  j          .Llevel_44_80080194
/* 8B535DC 800800AC 0200A0A6 */   sh        $zero, 0x2($s5)
.Llevel_44_800800B0:
/* 8B535E0 800800B0 0200A296 */  lhu        $v0, 0x2($s5)
/* 8B535E4 800800B4 00000000 */  nop
/* 8B535E8 800800B8 01004230 */  andi       $v0, $v0, 0x1
/* 8B535EC 800800BC 27004014 */  bnez       $v0, .Llevel_44_8008015C
/* 8B535F0 800800C0 60020424 */   addiu     $a0, $zero, 0x260
/* 8B535F4 800800C4 0780023C */  lui        $v0, %hi(SpawnMoby)
/* 8B535F8 800800C8 E042428C */  lw         $v0, %lo(SpawnMoby)($v0)
/* 8B535FC 800800CC 00000000 */  nop
/* 8B53600 800800D0 09F84000 */  jalr       $v0
/* 8B53604 800800D4 21286002 */   addu      $a1, $s3, $zero
/* 8B53608 800800D8 21A04000 */  addu       $s4, $v0, $zero
/* 8B5360C 800800DC 1F008012 */  beqz       $s4, .Llevel_44_8008015C
/* 8B53610 800800E0 21206002 */   addu      $a0, $s3, $zero
/* 8B53614 800800E4 0000928E */  lw         $s2, 0x0($s4)
/* 8B53618 800800E8 4957010C */  jal        func_80055D24
/* 8B5361C 800800EC 05000524 */   addiu     $a1, $zero, 0x5
/* 8B53620 800800F0 21206002 */  addu       $a0, $s3, $zero
/* 8B53624 800800F4 21280000 */  addu       $a1, $zero, $zero
/* 8B53628 800800F8 3800B127 */  addiu      $s1, $sp, 0x38
/* 8B5362C 800800FC C557010C */  jal        func_80055F14
/* 8B53630 80080100 21302002 */   addu      $a2, $s1, $zero
/* 8B53634 80080104 21206002 */  addu       $a0, $s3, $zero
/* 8B53638 80080108 01000524 */  addiu      $a1, $zero, 0x1
/* 8B5363C 8008010C 0C009026 */  addiu      $s0, $s4, 0xC
/* 8B53640 80080110 C557010C */  jal        func_80055F14
/* 8B53644 80080114 21300002 */   addu      $a2, $s0, $zero
/* 8B53648 80080118 21200002 */  addu       $a0, $s0, $zero
/* 8B5364C 8008011C 21280002 */  addu       $a1, $s0, $zero
/* 8B53650 80080120 653C010C */  jal        func_8004F194
/* 8B53654 80080124 21302002 */   addu      $a2, $s1, $zero
/* 8B53658 80080128 21200002 */  addu       $a0, $s0, $zero
/* 8B5365C 8008012C 443C010C */  jal        func_8004F110
/* 8B53660 80080130 01000524 */   addiu     $a1, $zero, 0x1
/* 8B53664 80080134 02000224 */  addiu      $v0, $zero, 0x2
/* 8B53668 80080138 480082A2 */  sb         $v0, 0x48($s4)
/* 8B5366C 8008013C 20000224 */  addiu      $v0, $zero, 0x20
/* 8B53670 80080140 4F0082A2 */  sb         $v0, 0x4F($s4)
/* 8B53674 80080144 64000224 */  addiu      $v0, $zero, 0x64
/* 8B53678 80080148 000042AE */  sw         $v0, 0x0($s2)
/* 8B5367C 8008014C 46006392 */  lbu        $v1, 0x46($s3)
/* 8B53680 80080150 FE000224 */  addiu      $v0, $zero, 0xFE
/* 8B53684 80080154 450082A2 */  sb         $v0, 0x45($s4)
/* 8B53688 80080158 460083A2 */  sb         $v1, 0x46($s4)
.Llevel_44_8008015C:
/* 8B5368C 8008015C 0200A296 */  lhu        $v0, 0x2($s5)
/* 8B53690 80080160 00000000 */  nop
/* 8B53694 80080164 01004224 */  addiu      $v0, $v0, 0x1
/* 8B53698 80080168 65000208 */  j          .Llevel_44_80080194
/* 8B5369C 8008016C 0200A2A6 */   sh        $v0, 0x2($s5)
.L80080170_:
/* 8B536A0 80080170 0780023C */  lui        $v0, %hi(D_8006C770)
/* 8B536A4 80080174 70C7428C */  lw         $v0, %lo(D_8006C770)($v0)
/* 8B536A8 80080178 00000000 */  nop
/* 8B536AC 8008017C 05004010 */  beqz       $v0, .Llevel_44_80080194
/* 8B536B0 80080180 21206002 */   addu      $a0, $s3, $zero
/* 8B536B4 80080184 D0D3000C */  jal        func_80034F40
/* 8B536B8 80080188 21280000 */   addu      $a1, $zero, $zero
.Llevel_44_8008018C:
/* 8B536BC 8008018C 14000224 */  addiu      $v0, $zero, 0x14
/* 8B536C0 80080190 480062A2 */  sb         $v0, 0x48($s3)
.Llevel_44_80080194:
/* 8B536C4 80080194 6000BF8F */  lw         $ra, 0x60($sp)
/* 8B536C8 80080198 5C00B58F */  lw         $s5, 0x5C($sp)
/* 8B536CC 8008019C 5800B48F */  lw         $s4, 0x58($sp)
/* 8B536D0 800801A0 5400B38F */  lw         $s3, 0x54($sp)
/* 8B536D4 800801A4 5000B28F */  lw         $s2, 0x50($sp)
/* 8B536D8 800801A8 4C00B18F */  lw         $s1, 0x4C($sp)
/* 8B536DC 800801AC 4800B08F */  lw         $s0, 0x48($sp)
/* 8B536E0 800801B0 6800BD27 */  addiu      $sp, $sp, 0x68
/* 8B536E4 800801B4 0800E003 */  jr         $ra
/* 8B536E8 800801B8 00000000 */   nop
.size func_level_44_8007FB5C, . - func_level_44_8007FB5C
